### ISSUE TITLE
live main.tf overwriting module's main.tf

### ISSUE THREAD

**Issue by gmetzker** [gruntwork-io/terragrunt#1001]
I'm having an issue where a terraform file `main.tf` in a 'live' repository is overwriting the modules `main.tf` file.  Which ends up loosing all resources in the module's `main.tf` file.  I'm new to Terragrunt so chances are I'm doing something wrong.  

My goal is to use Terragrunt to solve several use-cases:

1. Single command to plan/apply multiple terraform modules.
2. When developing, use the `--terragrunt-source` argument to quickly switch the module source from GIT to a local path.
3. Keep the backend/S3 config DRY.

#### Modules Repository
```
.
├── aws_account_settings
│   ├── main.tf
```
```
# /modules/aws_account_settings/main.tf
terraform {
  required_version = ">= 0.12.18"
  required_providers {
    aws = "~> 2.4"
  }
}

resource "aws_iam_account_password_policy" "strict" {
  allow_users_to_change_password = true
  hard_expiry                    = true
  max_password_age               = 60
  minimum_password_length        = var.minimum_password_length
  password_reuse_prevention      = 3
  require_lowercase_characters   = true
  require_numbers                = true
  require_symbols                = true
  require_uppercase_characters   = true
}
```

#### Live Folder
```
.
├── aws_account_settings
│   ├── main.tf
│   └── terragrunt.hcl
└── terragrunt.hcl
```
```
# live/terragrunt.hcl (root)
remote_state {
  disable_init = false
  backend = "s3"
  config = {
    region         = "us-east-1"
    bucket         = "XXXX-some-bucket"
    key            = "account/${path_relative_to_include()}/terraform.tfstate"
    encrypt        = true
    dynamodb_table = "terraform-state-lock-devops"
  }
}
```
```
# live/aws_account_settings/main.tf
terraform {
  backend "s3" {}
}

provider "aws" {
  region = "us-east-1"
}
```
```
# live/aws_account_settings/terragrunt.hcl
include {
  path = find_in_parent_folders()
}

terraform {
  source = "git::git@bitbucket.org:XXXX/aws-terraform-modules.git//aws_account_settings?ref=0.1.0"
}

```

When I do a `terragrunt init` it doesn't think there are any changes or resources to apply.  If I dig into the `.terragrunt-cache` folder I can see it pulled down the module but the `maint.tf` from my live folder overwrote the one from the module, and all it has is a basic provider and empty back end.
```
.
└── Zb35RRzAxTPumUstnhDglKVI4GQ
    └── hEj9rlpjUs7gvGwkrbpB6c38mk4
        ├── aws_account_settings
        │   ├── main.tf
        │   ├── terragrunt.hcl

# cat main.tf
terraform {
  backend "s3" {}
}

provider "aws" {
  region = "us-east-1"
}
```

As far as I can tell this is consistent with the documentation in [Keeping Your Remote State Configuration DRY](https://terragrunt.gruntwork.io/use-cases/keep-your-remote-state-configuration-dry/#motivation).

My expectation was that the `live` `main.tf` would be merged with the module's `main.tf` but it appears to be writing on top of it.

I can solve this by renaming `maint.tf` --> `backend.tf` and it solves the issue but is there something else I'm missing?   

If I am using Terragrunt to apply modules should I not include any `*.tf` files in the live folders as they may conflict with the name of the module tf files?

In my examples where would be the best place to have the provider block and the empty backend block?

Thanks in advance

**Comment by yorinasub17** [comment]
Terragrunt does not do intelligent merging of files: it does a blind copy of all files in the live folder into the terraform working directory. Renaming the file to `backend.tf` is the appropriate workaround for this.

There is no first class support for configuring the backend and provider blocks in terragrunt right now. You can track https://github.com/gruntwork-io/terragrunt/issues/746 for the proper feature implementation.
