### ISSUE TITLE
terragrunt v0.21.11 has wired behaviour on handling map variable in .hcl file

### ISSUE THREAD

**Issue by neo-liang-sap** [gruntwork-io/terragrunt#1007]
Hello,

I found in v0.21.11 terragrunt has wired behaviour on handling map variable in .hcl file.

e.g.

in my terragrunt.hcl file i defined an map like this

```
inputs = {
annotations = {"garden.sapcloud.io/purpose" = "development"}
}
```

the variable `annotations` is defined in my variables.tf like this 
```
variable annotations {
  default = {
    "garden.sapcloud.io/purpose" = "development"
    "confirmation.garden.sapcloud.io/deletion" = true
  }
}
```

the command `terragrunt apply` reported following error:

```
Error: Incorrect attribute value type

  on .terraform/modules/aws_gardener_shoot/gardener-shoot.tf line 40, in resource "gardener_shoot" "aws_cluster":
  40:     annotations = var.annotations
    |----------------
    | var.annotations is "{\"garden.sapcloud.io/purpose\":\"development\"}"

Inappropriate value for attribute "annotations": map of string required.

2020-01-16T19:50:18.864+0800 [DEBUG] plugin: plugin process exited: path=/Users/i352986/git_repo/argonautsmunich/terraform/garden-su1/.terragrunt-cache/TtHnNl84NCmqpsmezYmiB1OUNVo/N2NOnrP2xXmgXiVFDlM5QZN7owo/.terraform/plugins/darwin_amd64/terraform-provider-gardener_v0.0.3_x4 pid=51434
2020-01-16T19:50:18.864+0800 [DEBUG] plugin: plugin exited
[terragrunt] 2020/01/16 19:50:18 Hit multiple errors:
exit status 1
```

this issue only exist with map definition in hcl files, if i define same variable in .tf file there's no problem

`{"garden.sapcloud.io/purpose" = "development"}` is obviously an map of string but terragrunt doesn't work.

Thanks.

-Neo

**Comment by neo-liang-sap** [comment]
sorry i forgot the env info - i'm on Mac
![image](https://user-images.githubusercontent.com/42594392/72523284-6ba02d80-389a-11ea-982d-649fe4fae889.png)

**Comment by yorinasub17** [comment]
This is the same issue as https://github.com/gruntwork-io/terragrunt/issues/997 and https://github.com/gruntwork-io/terragrunt/issues/1002. You need to add the `type` information to the `annotations` variable in terraform, `type = map(string)`.

**Comment by neo-liang-sap** [comment]
thanks a lot for your kind help! @yorinasub17
