### ISSUE TITLE
Ansible playbook not being invoked by terraform module

### ISSUE THREAD

**Issue by pkaramol** [gruntwork-io/terragrunt#1008]
I have created a `terraform` module which in turn calls via a `local-exec` provisioner an `ansible` playbook as follows:

```
resource "null_resource" "run_ansible" {
  count = "${var.install_jenkins}"

  triggers {
    run_me_everytime = "${uuid()}"
  }

  provisioner "local-exec" {
    command = "ansible-playbook -vvv ./playbooks/playbook.yaml"
  }
}
```

When calling the `terraform` module directly, via say a `main.tf` file the above invocation works just fine.

However, when wrapping the entire process within `terragrunt` this fails most likely due to erroneous path resolution

> ERROR! the playbook: ./playbooks/playbook.yaml could not be found

Is there a way to address this when invoking the `module` using `terragrunt` ?

```
pkaramol@my-server:~$ terragrunt --version
terragrunt version v0.17.3
pkaramol@my-server:~$ terraform version
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.19. You can update by downloading from www.terraform.io/downloads.html
```

**Comment by fazith27** [comment]
> Hi @pkaramol , How did you fix this issue? I am into similar issue when running a python script using terragrunt

Please ignore. It is no longer an issue.
