### ISSUE TITLE
terragrunt.hcl full arg documentation

### ISSUE THREAD

**Issue by jeffdyke** [gruntwork-io/terragrunt#1010]
I'm really hoping i'm going to be pointed at an RTFM link, but i'm not finding this item.  What are all of the argument options that are allowed in `terragrunt.hcl`, what is allowed in the `terraform` block, only the `config_path` or can there be more.  I'm using terragrunt and am a big fan, but am looking for what more i can take advantage of.  I'll take a look at the code that parses terragrunt.hcl but i don't know go if at all.  I'd be happy to contribute this change to a readme.

Thanks for the great software!

**Comment by jeffdyke** [comment]
I did got to the SO first, as documented, and answered a question, but that is a pretty dry resource at this point. FWIW

**Comment by yorinasub17** [comment]
I am currently working on this now. You can track the progress here: https://github.com/gruntwork-io/terragrunt/pull/1009

**Comment by jeffdyke** [comment]
i gave it a thumbs up, but wanted to explicitly say thank you @yorinasub17, this will be a great resource!

**Comment by yorinasub17** [comment]
This is now live at https://terragrunt.gruntwork.io/docs/#reference
