### ISSUE TITLE
Provider error while migrating

### ISSUE THREAD

**Issue by mattayes** [gruntwork-io/terragrunt#1012]
Hi folks,

I'm trying to migrate to the immutable, versioned Terraform modules as described in [the docs](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#promote-immutable-versioned-terraform-modules-across-environments). I'm running into an issue with providers: I'm told provider configurations are missing.

Here's the original `main.tf`:

```
terraform {
  required_version = ">= 0.12"
  backend "gcs" {}	
}

module "gke" {
  source = "../../../modules/gke"

  project_id         = "lyticsio"
  network_name       = "liovpc"
}
```

Here's the current `terragrunt.hcl`:

```
include {
  path = find_in_parent_folders() # the backend is defined in a parent terragrunt.hcl file
}

terraform {
  source = "../../..//modules/gke"
}

inputs = {
  project_id         = "lyticsstaging"
  network_name       = "liovpc"
}
```

Here's an example of the error I'm getting:

```
Error: Provider configuration not present

To work with module.gke.google_service_account.gke_node its original provider
configuration at module.gke.provider.google is required, but it has been
removed. This occurs when a provider configuration is removed while objects
created by that provider still exist in the state. Re-add the provider
configuration to destroy module.gke.google_service_account.gke_node, after
which you can remove the provider configuration again.
```

Here's the output to `terragrunt providers`:

```
├── provider.google ~> 2.12
├── provider.google-beta ~> 2.14
├── provider.random 2.1.1
└── module.gke
    ├── provider.google (from state)
    ├── provider.google-beta (from state)
    └── provider.random (from state)
```

It looks like that, since the original approach used the `module` block, the providers are nested inside that module (e.g., `module.gke.provider.google`). However, since `terragrunt` copies the original module and operate on that copy directly, that the providers are all at the root level (e.g., provider.google). Since these don't match, Terraform can't move on.

Do you have any recommendations on how to resolve this?

**Comment by brikis98** [comment]
Terragrunt is running whatever code you have in here:

```hcl
terraform {
  source = "../../..//modules/gke"
}
```

The module in that folder needs to define a `provider` block.

**Comment by mattayes** [comment]
@brikis98 It does define a `provider` block. Here's a snippet of the source code for reference:

```terraform
terraform {
  required_version = ">= 0.12"
  backend "gcs" {}
}

provider "random" {
  version = "2.1.1"
}

provider "google" {
  version = "~> 2.12"
  project = var.project_id
}

resource "google_service_account" "gke_node" {
  account_id   = "gke-node-${random_id.rand.hex}"
  display_name = "Account for all GKE clusters' nodes to run as"
}
```

The issue (I think) is that originally the provider was nested inside the module, whereas now it's defined a the root level (see `terragrunt providers` output above). So the state is looking for `modules.gke.provider.google` and can't find it.

**Comment by brikis98** [comment]
Oh, so you're saying you had already deployed the `../../..//modules/gke` module directly, with a `provider` block in it, and now you'er trying to use the same state file, but with the `provider` block outside of the `module`? If so, this doesn't seem like a Terragrunt question, but more of a question of how to refactor Terraform code when you move provider definitions around. 

From that error message, it looks like Terraform doesn't handle this sort of refactor gracefully! Perhaps you can [explicitly pass the provider info](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly) to that module? If not, you may have to do as the error message says: put the `provider` config back into the `module` block and then either try to migrate what you have with `terraform state mv` (or perhaps even `terraform state rm` and `terraform import`)... Or run `destroy` and then `apply` with the `provider` outside the module.

**Comment by yorinasub17** [comment]
This is because of a state incompatibility when migrating from the terraform version to terragrunt. To solve this, you need to make `state mv` calls to move the resources, provider, data sources in the state outside the `module.gke` key to the root. It is painful, but hopefully is a one time thing.

The workaround proposed above also works.

Given the workaround and full solution, closing as solved. If there are any follow up questions, please open a new issue with relevant context.
