### ISSUE TITLE
hclfmt should exit 1 when reformatting a file

### ISSUE THREAD

**Issue by pgaxatte** [gruntwork-io/terragrunt#1015]
To be consistent with `terraform fmt` and easier to use in a script, the `hclfmt` command should exit 1 when it fixes the format of a file.

**Comment by pgaxatte** [comment]
OK so it needs the `--terragrunt-check` option to be passed but this option is not documented [here](https://terragrunt.gruntwork.io/docs/getting-started/cli-options/#cli-options)

**Comment by yorinasub17** [comment]
Will add this in the reference update I am working on now: https://github.com/gruntwork-io/terragrunt/pull/1009

**Comment by pgaxatte** [comment]
Thanks @yorinasub17 I'll close this issue
