### ISSUE TITLE
Quotes must be escaped when importing a resource created using for_each

### ISSUE THREAD

**Issue by wjoe** [gruntwork-io/terragrunt#1017]
I have a set of AWS DynamoDB tables which are created using a for_each loop from a variable:

```
locals {
  table_names = [
    "foo",
    "bar"
  ]
}

resource "aws_dynamodb_table" "my_tables" {
  for_each = toset(local.table_names)
  name = ${each.value}
  billing_mode = "PAY_PER_REQUEST"
  hash_key = "id"

  attribute {
    name = "id"
    type = "S"
  }
}
```

I wanted to import existing resources which match these names, using the suggested syntax from the Terraform documentation for resources created with a for_each loop https://www.terraform.io/docs/internals/resource-addressing.html 

`terragrunt import module.my_module.aws_dynamodb_table.my_tables["foo"]`

But I get the following error:
```
[terragrunt] 2020/01/23 18:30:36 Running command: terraform import module.my_module.aws_dynamodb_table.my_tables[foo] foo
Error: Index value required

  on <import-address> line 1:
   1: module.dynamodb.aws_dynamodb_table.stream_consumer[foo]

Index brackets must contain either a literal number or a literal string.

For information on valid syntax, see:
https://www.terraform.io/docs/internals/resource-addressing.html

```

This is a rather confusing error as I am using a quoted string, and following the same syntax as the Terraform docs suggest. It seems that Terragrunt is stripping out the quotes somehow during the process of running Terraform (or this is a bug in Terraform itself, I've not been able to test it outside of Terragrunt so far).

If I backslash escape the quotes in the command, it does work, eg 

`terragrunt import module.my_module.aws_dynamodb_table.my_tables[\"foo\"]`

This imports the resource as intended.

**Comment by yorinasub17** [comment]
This is a terraform issue, not terragrunt, since terragrunt is just forwarding the args. In fact, the requirement to quote is shown in the docs on how to import a for_each resource: https://www.terraform.io/docs/commands/import.html#example-import-into-resource-configured-with-for_each

**Comment by ggorge-etiqa** [comment]
For the folks who get here because they still get the error despite correctly escaping the quotes, if you use some credential tool like `saml2aws` or `awsvault` you may need to add extra backslashes.

`saml2aws exec -a account -- terragrunt import module.my_module.aws_dynamodb_table.my_tables[\\\"foo\\\"]`
