### ISSUE TITLE
Provider configuration per environment

### ISSUE THREAD

**Issue by kromol** [gruntwork-io/terragrunt#1018]
I have `terraform` module for `S3` and my `terrugrunt.hcl` looks like this:
```
terraform {
  source = "git::ssh://git@....tf-modules.git//s3-static-website?ref=1.0.0"
}

include {
  path = find_in_parent_folders()
}
```

The module itself is pretty simple and it works with current setup. But I want to use `Localstack` for local development and I'd like to be able to provision local infrastructure using existing code. 
According to [terraform documentation](https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html#localstack) it should be very easy and I just need to adjust `aws provider` and set custom `endpoints`. Since I need it for this particular project, I don't want to put it into module itself and seems like `terrugrunt.hcl` is ideal place for doing it. So I tried with following code:
```
terraform {
  source = "git::ssh://git@....tf-modules.git//s3-static-website?ref=1.0.0"

  provider "aws" {
    endpoints {
      s3  = "http://localhost:4572"
    }
  }
}
```
But it does not work and I'm getting error: `Blocks of type "provider" are not expected here.` I am probably doing it in a wrong way, but I could not find any example in the documentation so any help would be appreciated.

Thanks

**Comment by yorinasub17** [comment]
This is not a supported feature of `terragrunt`. With that said, the way to workaround this is to include a `.tf` file in the terragrunt live dir with the provider code. Terragrunt will copy all the contents of the live folder to the working directory before calling terraform, so effectively will share the provider config.

Note that this is still not ideal because you need the provider tf file in every child module. You can't just define once and copy.

We are actively discussing a feature improvement to address this very use case. Will update this ticket when we have more to share.

**Comment by kromol** [comment]
Thanks for the response, I will try this way.

My initial idea was to do something like this in the module:
```
provider "aws" {
  region = var.region
  version = "~>2.31"

  dynamic "endpoints" {
    for_each = var.environment == "local" ? [1] : []
    content {
      s3             = "http://localhost:4572" // this will come from variable
    }
  }
}
```
I did not try it yet, but actually it also seems like a workaround.

**Comment by jack-of-AllTrades** [comment]
Is there any update on this feature? seems like this [block code](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#keep-your-provider-configuration-dry) does not work and returns **Blocks of type "generate" are not expected here** error

**Comment by yorinasub17** [comment]
> seems like this block code does not work and returns Blocks of type "generate" are not expected here error

What version of terragrunt are you using? `generate` blocks were introduced in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.22.0 so you need to be using at least that version.

**Comment by kromol** [comment]
Yes, new `generate` block solves this issue, so I am closing it. @jack-of-AllTrades I can share example how we use it if it helps.

**Comment by rubelw** [comment]
@jack-of-AllTrades Yes, if you could share an example, this would be great.  Thanks!
