### ISSUE TITLE
Nested maps/complex types converted to strings

### ISSUE THREAD

**Issue by justicel** [gruntwork-io/terragrunt#1019]
Howdy. I'm using the latest version of TF and Terragrunt 
TF: 0.12.20
TG: 0.21.11

I have a complex data type defined in inputs like so:

```
inputs = {
  ingress_rules = {
    "dns_tcp" = {
      "port" = "53"
      "protocol" = "tcp"
    }
    "dns_udp" = {
      "port" = "53"
      protocol = "udp"
    }
  }
}
```

It appears that it is getting converted to a json string which I can't jsondecode to use it in for_each statements. Any ideas on what to do here?

Error: Invalid for_each argument

  on ../default_sg/main.tf line 94, in resource "aws_security_group_rule" "default_sg_ingress":
  94:   for_each = var.ingress_rules

The given "for_each" argument value is unsuitable: the "for_each" argument
must be a map, or set of strings, and you have provided a value of type
string.

**Comment by yorinasub17** [comment]
This is the same issue as https://github.com/gruntwork-io/terragrunt/issues/1007, https://github.com/gruntwork-io/terragrunt/issues/997, and https://github.com/gruntwork-io/terragrunt/issues/1002. You need to add the `type` information to the `annotations` variable in terraform, `type = map(map(string))`.

**Comment by justicel** [comment]
Ahhh! Thanks. This makes sense now. It might be something to add to the documentation if it's not there already! Appreciate it!

**Comment by konstantin-recurly** [comment]
@justicel  it's already there
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#inputs
```Note that because the values are being passed in with environment variables and json, the type information is lost when crossing the boundary between Terragrunt and Terraform. You must specify the proper type constraint on the variable in Terraform in order for Terraform to process the inputs to the right type.
```

**Comment by yorinasub17** [comment]
Closing as the question has been answered. To clarify one thing, if you do not have control over the underlying module (e.g., the module is on the public registry and not a repo you maintain), you will need to create a wrapper module that exposes the variables with the relevant types, and have terragrunt call that wrapper module. If there is interest in a better way, please 👍 and follow [this RFC](https://github.com/gruntwork-io/terragrunt/pull/1809) which proposes a terragrunt feature to dynamically install types onto variables.
