### ISSUE TITLE
Add ability for a before_hook that runs before initializing remote state

### ISSUE THREAD

**Issue by sleungcy** [gruntwork-io/terragrunt#1020]
I am attempting to set up a hook before terragrunt initialize remote state to retrieve AWS credential from vault. However terragrunt just initializes the remote state before triggering the "init" before_hook..

[terragrunt] 2020/01/27 20:28:27 Reading Terragrunt config file at /app/microservices/terragrunt.hcl
[terragrunt] [/app/microservices/terragrunt.hcl] 2020/01/27 20:28:27 Running command: terraform --version
[terragrunt] 2020/01/27 20:28:27 Initializing remote state for the s3 backend
[terragrunt] 2020/01/27 20:28:47 Error finding AWS credentials in file '/tmp/.aws_credentials' (did you set the correct file name and/or profile?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by sleungcy** [comment]
Are there other hooks i can use that are before "init"? Is there a way I can put a hook before it runs terraform --version?

**Comment by yorinasub17** [comment]
I think you want to use `init-from-module`. See the last bullet in https://terragrunt.gruntwork.io/docs/features/before-and-after-hooks/ for more details.

**Comment by sleungcy** [comment]
unfortunately, init-from-module also runs after the state initialization.

**Comment by yorinasub17** [comment]
Gotcha. Then we don't currently support this feature, so we will need to implement it. We're unlikely to get to this anytime soon, so if you are in need of this in the short term, your best bet is to submit a PR to add support for this. Otherwise, you can wait for someone from the community or us to get around to implementing this.

**Comment by sleungcy** [comment]
Do I need an RFC for this?

**Comment by yorinasub17** [comment]
Thanks for checking in on that! This is simple enough that the corresponding README updates to [the before hook docs](https://github.com/gruntwork-io/terragrunt/blob/master/docs/_docs/02_features/before-and-after-hooks.md) is sufficient.
