### ISSUE TITLE
Configure issue with terragrunt

### ISSUE THREAD

**Issue by kiran266** [gruntwork-io/terragrunt#1029]
Hi There,

I have downloaded https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.3/terragrunt_linux_amd64, renamed it to terragrunt and moved to /usr/local/bin 
did chmod +x /usr/local/bin/terragrunt

But I am still getting below error on my mac
$ terragrunt
-bash: /usr/local/bin/terragrunt: cannot execute binary file

I am trying to install Terragrunt v0.18.3 and facing issues doing so.

Please help resolving this issue. thanks in advance.

Thanks.

**Comment by yorinasub17** [comment]
Since you are on a mac, you need the darwin version of the binary: https://github.com/gruntwork-io/terragrunt/releases/download/v0.18.3/terragrunt_darwin_amd64

**Comment by kiran266** [comment]
Thank you so Much! that worked.
