### ISSUE TITLE
Add interpolation to read hcl file

### ISSUE THREAD

**Issue by barryib** [gruntwork-io/terragrunt#1031]
It would be nice if there was an interpolation to read hcl file. Maybe something like `get_hcl_file()`.This can be used instead of `yamldecode(file("FILE_PATH"))` within locals.

```hcl
locals {
  common_vars = get_hcl_file("FILE_PATH.hcl"),
  region = "us-east-1"
}
```

**Comment by yorinasub17** [comment]
Please see [the RFC on imports](https://github.com/gruntwork-io/terragrunt/pull/1025). Will close this as we have plenty of tickets requesting similar functionality and there is already an RFC to design a solution. You can follow that PR to get updates on the progress.
