### ISSUE TITLE
Terragrunt validate prompts for backend creation

### ISSUE THREAD

**Issue by umairidris** [gruntwork-io/terragrunt#1039]
When running terragrunt validate I expect the command to be fully self contained. However, it presently seems to still check for the existence and access to the backend remote state.

e.g.

$ terragrunt validate
...
Remote state GCS bucket REDACTED does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)

Can we bypass remote state creation in validate?

**Comment by brikis98** [comment]
Does the `--terragrunt-no-auto-init` param work for you?

**Comment by umairidris** [comment]
Hi @brikis98,

A bit unintuitive, but works :) thanks!

If you would like I can send a pr to default auto init to false when validate/validate-all are the commands but if you prefer the existing behaviour then feel free to close.

**Comment by brikis98** [comment]
A PR for that would be great, thanks!

**Comment by umairidris** [comment]
On further testing, it looks like if you have modules you do need to run terraform init before terraform validate.. and terraform init will check the backend GCS if it is set. So I don't think this is possible. I will close the PR and issue for now and if I have any other solution will report back. Thanks!
