### ISSUE TITLE
Terragrunt support for .tfvars files.

### ISSUE THREAD

**Issue by p0bailey** [gruntwork-io/terragrunt#104]
Hello there,

I'm currently looking into get to work terragrunt with a .tfvars file which contains AWS credentials. I'm fully aware that best practices encourage to use env variables or EC2 roles to manage access to AWS api. 

Whenever I try to run terragrunt with the following command it doesn't work.
`terragrunt apply -var-file=credentials.tfvars`

However, terraform apply works as expected.

`terraform apply -var-file=credentials.tfvars`

Any thoughts on this?

Best,

Phillip

**Comment by brikis98** [comment]
What are you defining in `credentials.tfvars`? When you say the terragrunt command "doesn't work", can you be more specific? What happens?

**Comment by p0bailey** [comment]
Hi Yevgeniy,

sorry for not being more specific on the problem.

Well, inside credentials.tvars I'm defining AWS secrets as follow.

aws_access_key = “XXXXXXXXXXX”
aws_secret_key = “XXXXXXXXXXXXXXXXXXXXXXXX”
aws_region = "eu-west-1"

and whenever I run `terragrunt apply -var-file=credentials.tfvars` i get: 


terragrunt apply -var-file=~/credentials/terraform.tfvars
[terragrunt] 2017/01/23 00:27:08 Reading Terragrunt config file at /Users/phillip/Development/cloud/terraform/environments/aws-vpc-public/.terragrunt
[terragrunt] 2017/01/23 00:27:08 Attempting to acquire lock for state file my-app in DynamoDB
Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[terragrunt] 2017/01/23 00:27:09 Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
make: *** [apply] Error 1

**Comment by brikis98** [comment]
Oh, I see. I'm guessing in your Terraform code, you're doing something like this:

```hcl
provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
}
```

If so, the reason that works is you're explicitly using Terraform variables. Currently, Terraform does not try to read any variables from Terraform, nor would it know to use those two variables in particular, as you could name them whatever you want.

Is there a reason you can use environment variables, AWS profiles, AWS roles, etc?

**Comment by p0bailey** [comment]
Hi Yevgeniy,

we have managed and sort it out using ENV variables. Thanks anyway.

Best,

Phillip

**Comment by brikis98** [comment]
Got it, thanks for the update!

**Comment by pablokbs** [comment]
@p0bailey can you share how did you do that?

I'm currently trying to use the TF_VAR variables with terragrunt, I have the something like this:

```
module "elb" {
  source = "../modules/network/loadbalancing"
  instance_port_http  = "${var.elb_instance_port_http}"
  instance_port_https = "${var.elb_instance_port_https}"
}
```

For terraform, I just declare `TF_VAR_elb_instance_port_http` and it works. How can I make it work with terragrunt?

Thanks 

cc @brikis98

**Comment by p0bailey** [comment]
HI @pablokbs 

the fix was quite simple, we stopped to put the cred in the .tfvars file and we are passing them as an environment var. That's it.

Best,

Phillip

**Comment by pablokbs** [comment]
Hi @p0bailey thanks for your response, actually I came back to post that was my mistake and I wasn't declaring them. Everything is good.

Thanks!

**Comment by ozbillwang** [comment]
@pablokbs 

Can you use `TF_VAR_*` variable in terragrunt?

I have same issue when deploy a new tag within target definition in ECS, it doesn't work with `TF_VAR_tag=0.1.2`

    TF_VAR_tag=0.1.2 terragrunt plan
