### ISSUE TITLE
Add the possibility to customize the RETRYABLE_ERRORS using environment variables

### ISSUE THREAD

**Issue by andreluiznsilva** [gruntwork-io/terragrunt#1040]
My CI/CD sometimes fail because of a "ssh_exchange_identification: Connection closed by remote host" error. 

Would be nice to include the error on the RETRYABLE_ERRORS list and/or allow the list to be customized by a environment variable.

Regards

**Comment by brikis98** [comment]
A big +1 on this. In fact, it would be great to be able to add to the list of retryable errors in `terragrunt.hcl`: 

```hcl
retryable_errors = {
  "a regex to match the error": "more information about the error"
}
```

A PR for this is very welcome.
