### ISSUE TITLE
How to exclude dependencies?

### ISSUE THREAD

**Issue by dudicoco** [gruntwork-io/terragrunt#1041]
Hi,

I am running the following command:
```
terragrunt apply-all --terragrunt-include-dir devops/amazing-app/k8s/
```
In the ```terragrunt.hcl``` file there is a dependency block defined for another component.

When running the above command the component specified in the dependency block is being installed, I would like to install only the components specified in ```--terragrunt-include-dir``` without their dependencies.

Is there a way to achieve this?

Thanks

**Comment by yorinasub17** [comment]
Is `devops/amazing-app/k8s` a single module, or a folder with multiple modules?

- If it is a single module, you should use `terragrunt apply --terragrunt-config devops/amazing-app/k8s/terragrunt.hcl` instead. This has a few advantages, like skipping the check to collect all the modules to run on and bypassing terragrunt's multi-module functionality to make it virtually impossible to have terragrunt run multiple modules.
- If it is a folder with multiple modules, you can use `--terragrunt-ignore-external-dependencies`

**Comment by dudicoco** [comment]
@yorinasub17, ```devops/amazing-app/k8s``` contains a single ```terragrunt.hcl``` file with a reference to a single module.

What I would like to do, is to run ```terragrunt apply-all --terragrunt-include-dir devops/app1/k8s/ --terragrunt-include-dir devops/app2/k8s/``` and have terrgrunt to install only the components specified in ```--terragrunt-include-dir``` (app1 and app2) and install them according in the order of dependencies between them. I don't want terragrunt to install dependencies specified within these components which I have not included with ```--terragrunt-include-dir```.

Please let me know if it makes sense.
Thanks!

**Comment by yorinasub17** [comment]
`--terragrunt-ignore-external-dependencies` is probably the flag you are looking for: https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-ignore-external-dependencies

**Comment by dudicoco** [comment]
@yorinasub17 I've already tried using this flag and it did nothing.
I assume it's meant for ignoring the dependencies of the dependencies.

**Comment by yorinasub17** [comment]
That's probably a bug then. Can you share the following so we can take a look?

- Your folder structure
- `terragrunt.hcl` of `devops/amazing-app/k8s`
- `terragrunt.hcl` of a dependency being pulled in
- The FULL output of the logs from a `terragrunt` call.

**Comment by dudicoco** [comment]
So it seems that the behaviour is irregular.
Now when running ```terragrunt apply-all --terragrunt-include-dir devops/amazing-app/k8s``` the dependency is not being included, but running the same command on a different component which is configured exactly the same the dependency is being included. 
I have cleared the cache on all folders with the same results.

Folder structure:
```
.
├── Makefile
├── README.md
├── devops
│   ├── amazing-app
│   │   ├── k8s
│   │   │   ├── terragrunt.hcl
│   │   │   └── values_us-east-1_dev.yaml
│   │   └── s3
│   │       ├── terragrunt.hcl
│   │       └── values_us-east-1_dev.yaml
│   ├── eks-ocean
│   │   └── eks-ocean
│   │       ├── terragrunt.hcl
│   │       └── values_us-east-1_dev.yaml
│   ├── example
│   │   ├── ecr
│   │   │   ├── terragrunt.hcl
│   │   │   └── values.yaml
│   │   ├── helm
│   │   │   └── values.yaml
│   │   ├── k8s
│   │   │   ├── terragrunt.hcl
│   │   │   ├── values.yaml
│   │   │   └── values_example.yaml
│   │   ├── kms
│   │   │   ├── terragrunt.hcl
│   │   │   └── values.yaml
│   │   └── s3
│   │       ├── terragrunt.hcl
│   │       └── values.yaml
│   ├── kms
│   │   └── kms
│   │       ├── terragrunt.hcl
│   │       ├── values_us-east-1_dev.yaml
│   └── testonico
│       ├── k8s
│       │   ├── terragrunt.hcl
│       │   └── values_us-east-1_dev.yaml
│       └── legacy
│           ├── main.tf
│           ├── outouts.tf
│           ├── terragrunt.hcl
│           ├── values_us-east-1_dev.tfvars
│           └── variables.tf
```

```terragrunt.hcl``` of ```devops/amazing-app/k8s``` and ```devops/testonico/k8s```:
```
terraform {
  source = "../../../modules/k8s"
}

skip = fileexists("values_${get_env("TF_VAR_environment", "")}.yaml") ? false : true

dependency "eks-ocean" {
  config_path  = "../../../devops/eks-ocean/eks-ocean"
  skip_outputs = true
}

include {
  path = find_in_parent_folders()
}
```

```terragrunt.hcl``` of ```devops/eks-ocean/eks-ocean```:
terraform {
  source = "../../../modules/eks"
}

skip = fileexists("values_${get_env("TF_VAR_environment", "")}.yaml") ? false : true

prevent_destroy = true

include {
  path = find_in_parent_folders()
}
```

Logs from ```devops/amazing-app/k8s```:
```
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra to /Repositories/infra/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Module /Repositories/infra does not have an associated terraform configuration and will be skipped.
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/amazing-app/k8s to /Repositories/infra/devops/amazing-app/k8s/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/amazing-app/s3 to /Repositories/infra/devops/amazing-app/s3/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/eks-ocean/eks-ocean to /Repositories/infra/devops/eks-ocean/eks-ocean/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/example/ecr to /Repositories/infra/devops/example/ecr/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/example/k8s to /Repositories/infra/devops/example/k8s/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/example/kms to /Repositories/infra/devops/example/kms/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/example/s3 to /Repositories/infra/devops/example/s3/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/kms/kms to /Repositories/infra/devops/kms/kms/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/testonico/k8s to /Repositories/infra/devops/testonico/k8s/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Setting download directory for module /Repositories/infra/devops/testonico/legacy to /Repositories/infra/devops/testonico/legacy/.terragrunt-cache
[terragrunt] 2020/02/19 10:48:55 Stack at /Repositories/infra:
  => Module /Repositories/infra/devops/amazing-app/k8s (excluded: false, dependencies: [/Repositories/infra/devops/eks-ocean/eks-ocean])
  => Module /Repositories/infra/devops/amazing-app/s3 (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/eks-ocean/eks-ocean (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/example/ecr (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/example/k8s (excluded: true, dependencies: [/Repositories/infra/devops/eks-ocean/eks-ocean])
  => Module /Repositories/infra/devops/example/kms (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/example/s3 (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/kms/kms (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/testonico/k8s (excluded: true, dependencies: [/Repositories/infra/devops/eks-ocean/eks-ocean])
  => Module /Repositories/infra/devops/testonico/legacy (excluded: true, dependencies: [])
[terragrunt] 2020/02/19 10:48:55 [terragrunt]  Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

Logs from ```devops/testionico/k8s```:
```
[terragrunt] 2020/02/19 10:55:29 Module /Repositories/infra does not have an associated terraform configuration and will be skipped.
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/amazing-app/k8s to /Repositories/infra/devops/amazing-app/k8s/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/amazing-app/s3 to /Repositories/infra/devops/amazing-app/s3/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/eks-ocean/eks-ocean to /Repositories/infra/devops/eks-ocean/eks-ocean/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/example/ecr to /Repositories/infra/devops/example/ecr/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/example/k8s to /Repositories/infra/devops/example/k8s/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/example/kms to /Repositories/infra/devops/example/kms/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/example/s3 to /Repositories/infra/devops/example/s3/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/kms/kms to /Repositories/infra/devops/kms/kms/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/testonico/k8s to /Repositories/infra/devops/testonico/k8s/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Setting download directory for module /Repositories/infra/devops/testonico/legacy to /Repositories/infra/devops/testonico/legacy/.terragrunt-cache
[terragrunt] 2020/02/19 10:55:29 Stack at /Repositories/infra:
  => Module /Repositories/infra/devops/amazing-app/k8s (excluded: true, dependencies: [/Repositories/infra/devops/eks-ocean/eks-ocean])
  => Module /Repositories/infra/devops/amazing-app/s3 (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/eks-ocean/eks-ocean (excluded: false, dependencies: [])
  => Module /Repositories/infra/devops/example/ecr (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/example/k8s (excluded: true, dependencies: [/Repositories/infra/devops/eks-ocean/eks-ocean])
  => Module /Repositories/infra/devops/example/kms (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/example/s3 (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/kms/kms (excluded: true, dependencies: [])
  => Module /Repositories/infra/devops/testonico/k8s (excluded: false, dependencies: [/Repositories/infra/devops/eks-ocean/eks-ocean])
  => Module /Repositories/infra/devops/testonico/legacy (excluded: true, dependencies: [])
[terragrunt] 2020/02/19 10:55:29 [terragrunt]  Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

**Comment by yorinasub17** [comment]
Can you update the logs with:

- The actual command you ran
- Which folder you ran from

**Comment by dudicoco** [comment]
I've updated the logs with the command I ran.
I ran it from the root directory where the parent ```terragrunt.hcl``` file is placed - ```/Repositories/infra/```

**Comment by yorinasub17** [comment]
Thanks! Will take a look at this at my earliest convenience.

**Comment by dudicoco** [comment]
Thanks @yorinasub17.

I did run the commands several times with and without ```--terragrunt-ignore-external-dependencies``` and it did not make a difference.

**Comment by yorinasub17** [comment]
Ok I have reproduced the behavior and have a fix in https://github.com/gruntwork-io/terragrunt/pull/1062

**Comment by dudicoco** [comment]
Thanks!

**Comment by yorinasub17** [comment]
This should now be fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.22.4. You can use `--terragrunt-strict-include` to exclude the dependencies.

**Comment by dudicoco** [comment]
I tested the fix to ```--terragrunt-include-dir``` and the new ```--terragrunt-strict-include``` feature and they are both working as expected.

Thanks!
