### ISSUE TITLE
Should --terragrunt-source skip local paths?

### ISSUE THREAD

**Issue by kromol** [gruntwork-io/terragrunt#1046]
Hello, 

I am not sure if it's bug or feature, but currently seems like `--terragrunt-source` does not skip `source` which references to the local filesystem.

Can someone pls clarify expected behavior? Should it only replace remote modules or local modules as well?

**Comment by brikis98** [comment]
What do you mean by skip? `--terragrunt-source` *overrides* the `source` URL in a `terragrunt.hcl` file. Is that not what you're seeing? Can you provide a bit more info?

**Comment by kromol** [comment]
> --terragrunt-source overrides the source URL in a terragrunt.hcl

Yes, this is what it does. Probably I misunderstood that part, because I thought that it should replace only remote `source`s.  For example if I have three different modules and two of them are remote I was expecting that it will not replace local module since it's already in the filesystem.

I have following setup:
```
dev
 |--lambda
 |     |--terragrunt.hcl // source from git
 |--apigw
 |     |--terragrunt.hcl // source from git
 |--remote_state
 |     |--terragrunt.hcl // source is local tf module
```

Basically `lambda` can be optionally put into VPC and if it needs to be there, `subnets` and `security group` comes from the external remote state. I did not want to put it into module in order to keep it de-coupled, and instead I pass it as inputs. But in order to get those values in `terragrunt` I created local `terraform` module which actually fetches output from remote state and then I use that module as `dependency` to access it's output and pass it into `lambda` module.

The above structure did not work since it also replaced my `remote_state` module.

There is also a chance that the part with remote state is done in the wrong way, but I did not find how to access remote state directly from `terragrunt`. Any hints about the better way of doing it are highly appreciated.

**Comment by brikis98** [comment]
> Probably I misunderstood that part, because I thought that it should replace only remote sources. For example if I have three different modules and two of them are remote I was expecting that it will not replace local module since it's already in the filesystem.

It replaces all `source` URLs. There is currently no support for replacing only some of the URLs.

> There is also a chance that the part with remote state is done in the wrong way, but I did not find how to access remote state directly from terragrunt. 

The main options are to add a `terraform_remote_state` data source to your Terraform code (the `.tf` files) or to use a `dependency` block in a `terragrunt.hcl` file to pull in outputs from another module.

**Comment by kromol** [comment]
> The main options are to add a terraform_remote_state data source to your Terraform code (the .tf files) or to use a dependency block in a terragrunt.hcl file to pull in outputs from another module.

This is actually what I am doing. I wrapped `terraform` data source that fetches remote state into local module for convenience and use `dependency` to access it. With this approach I could not test it using `--terragrunt-source` since other modules are from git repo. As a workaround I can probably use terraform data source directly without a module on top of that.

Anyway, closing this issue since it works as expected. Thanks for help.

**Comment by trallnag** [comment]
I could tear off my face right now. I have been trying for hours to get my Terragrunt setup to work with local checked out sources. One of the issues was that `--terraform-source` just did not work.

For whatever reason I always used `--terraform-source` instead of `--terragrunt-source`. Now it all works 🤦
