### ISSUE TITLE
Chocolatey (Choco) package is outdated

### ISSUE THREAD

**Issue by Hayorti** [gruntwork-io/terragrunt#1052]
The Chocolatey package at https://chocolatey.org/packages/terragrunt is for version 0.21.9 and is outdated.

A contributor created the package and submitted issue #862 and the documentation was changed through PR #865 , but the package hasn't been maintained consistently.

Considering that Gruntwork.io won't be maintaining packages as noted in #717 , I think it should either be noted in the [official installation documentation](https://terragrunt.gruntwork.io/docs/getting-started/install/) that the Choco packages aren't officially maintained so that people don't think that the version they're installing is actually current or official. I'd even consider removing Chocolatey as a primary method of installation for Windows and maybe including it as an alternative.

I, for one, only realized that the package was outdated when I went to check Terragrunt's release history since I know that Chocolatey packages aren't always maintained or up-to-date.

**Comment by yorinasub17** [comment]
FWIW, we already indicate this in [the docs](https://terragrunt.gruntwork.io/docs/getting-started/install/#install-terragrunt)

> Note that third-party Terragrunt packages may not be updated with the latest version, but are often close. Please check your version against the latest available on the Releases Page.

**Comment by Hayorti** [comment]
Yeah, I think that would be fair to the end-users. Realistically, unless someone were to dig up issue #862 , they wouldn't have any way of knowing that DrFaust (the choco package maintainer) isn't part of the Terragrunt team and that the package is in fact third-party.

I'd go so far as to move the manual installation to the top of the documentation and flag it as the recommended method.

**Comment by brikis98** [comment]
Agreed! I'd list manual install (perhaps renamed to "download from releases page") as option #1... Then list the caveat about package managers being a bit out of date more clearly below that... And then list all the package manager install options.

Anyone up for a quick PR to make this change?
