### ISSUE TITLE
variable reference in dependent module

### ISSUE THREAD

**Issue by erichrockman** [gruntwork-io/terragrunt#1053]
root
 - mod1
 - mod2

I only want to run mod2 if there is an output from mod1.

I have declared this in mod2. How do I reference "public_firewall_management_ip" in the .tf file in mod2? I keep getting invalid reference. What is the correct syntax?

dependency "azureInfr" {
  config_path = "../azureInfr"

  mock_outputs = {
      public_firewall_management_ip = "dummy"
      public_firewall_management_fqdn = "dummy"
    }
}

inputs = {
  public_firewall_management_ip = dependency.azureInfr.outputs.public_firewall_management_ip
  public_firewall_management_fqdn = dependency.azureInfr.outputs.public_firewall_management_fqdn
}

**Comment by yorinasub17** [comment]
To reference `public_firewall_management_ip` in the `.tf` file, you need to declare a `variable` block. `terragrunt` passes on each key value pair in the `inputs` map as a variable input. This is basically the same as [setting each variable using a `tfvars` file](https://www.terraform.io/docs/configuration/variables.html#variable-definitions-tfvars-files).

**Comment by yorinasub17** [comment]
Closing as stale. If there is still an issue here, please open a new ticket with the updated context. Thanks!
