### ISSUE TITLE
Feature Request: CLI flag to batch *-all actions

### ISSUE THREAD

**Issue by jleeh** [gruntwork-io/terragrunt#1063]
With a large mono-repo, I often need to run `plan-all` and `apply-all` with 20+ Terragrunt resources at once. Typically, these modules include around 3-4 providers, and when you run them all at once, it can kill the best of spec'd machines.

My proposal is a new CLI flag, for example `terragrunt-batch-count` which can be set to an arbitrary number dictating how many resources are applied/planned at once.

Eg: `--terragrunt-batch-count=3` would mean there's a concurrency of 3 for `plan-all` and `apply-all`.

**Comment by yorinasub17** [comment]
There is a WIP to add this in https://github.com/gruntwork-io/terragrunt/pull/636, but we have a few unresolved issues.

**Comment by yorinasub17** [comment]
I'll be closing this as duplicate. Please follow the PR and related issue https://github.com/gruntwork-io/terragrunt/issues/511 for updates. Thanks!
