### ISSUE TITLE
Half a day lost trying to get it to work

### ISSUE THREAD

**Issue by assertnotnull** [gruntwork-io/terragrunt#1067]
I have this configuration
/terraform
-> /modules/ with many tf files on same level

/terragrunt
-> /staging/main.tf
```
module "app" {
  source "../../terraform/modules"
}
etc. (left for to keep it short)
```
and 
-> /staging/terragrunt.hcl
```
terraform {
  source = "../../terraform//modules"
}
```

Now when I run `terragrunt plan`:

```
Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../terraform: no such file or
directory
```
I find this terraform + terragrunt path resolution is very confusing and the documentation is not intuitive.

**Comment by brikis98** [comment]
Why do you have both a `staging/main.tf` pointing to `/terraform/modules` *and* a `staging/terragrunt.hcl` pointing to it?

This code in `terragrunt.hcl`:

```hcl
terraform {
  source = "../../terraform//modules"
}
```

Will copy the code from `../../terraform/modules`, plus any `.tf` files from current working directory—including, `staging/main.tf`—into a `.terragrunt-cache` folder and run Terraform in that folder. The relative path in your `staging/main.tf` is what's causing the error, as that file is now in a `.terragrunt-cache` subfolder and `../../terraform` is not a valid path from there.

**Comment by assertnotnull** [comment]
I thought I could still use the module block with it.
Thanks, it got me figure out that I need to remove them and I need to update all relative paths
