### ISSUE TITLE
Unclear documentation for locals

### ISSUE THREAD

**Issue by bholzer** [gruntwork-io/terragrunt#1069]
In the local documentation, the final line includes:

`Note that because locals is a block, there currently is a way to merge the map into the top level`

Is this a typo, intending to relay that there is no way to merge locals?

Is the `common_vars` method described in the docs the suggested way to inherit some locals through the hierarchy?

**Comment by yorinasub17** [comment]
Ah yes this is indeed a typo! The `locals` blocks will not merge through the `include` references. The `common_vars` method or using [read_terragrunt_config](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_terragrunt_config) are the ways to inherit locals.

Also see https://github.com/gruntwork-io/terragrunt/pull/1025 for relevant context.

**Comment by bholzer** [comment]
Thanks for the confirmation.

I have created a PR for the typo fix here: https://github.com/gruntwork-io/terragrunt/pull/1071

**Comment by yorinasub17** [comment]
Thanks for fixing the typo! Closing as resolved.
