### ISSUE TITLE
Migrating to Terragrunt when previously using the -state option

### ISSUE THREAD

**Issue by trevorr** [gruntwork-io/terragrunt#107]
My Terraform state file is currently stored separately from my templates, because the state file is specific to the environment (e.g. production vs. QA/staging) but the templates are not (generally speaking). Therefore, when I run Terraform with local state, my scripts always specify the `-state` option.

I'm now trying to migrate to remote state using Terragrunt. When Terragrunt runs `terraform remote config`, there doesn't seem to be a way to pass the [`-state`](https://www.terraform.io/docs/commands/remote-config.html#_state_path) option such that it's used by `remote config` but not by the actual command. This results in a Terraform error:

```
export TERRAGRUNT_CONFIG=/opt/deploy/state/dev/.terragrunt
cd /opt/deploy/generated/dev && terragrunt refresh -state=/opt/deploy/state/dev/terraform.tfstate -var-file=dev.tfvars
[terragrunt] 2017/01/24 09:58:10 Reading Terragrunt config file at /opt/deploy/state/dev/.terragrunt
[terragrunt] 2017/01/24 09:58:10 Initializing remote state for the s3 backend
[terragrunt] 2017/01/24 09:58:10 Configuring remote state for the s3 backend
[terragrunt] 2017/01/24 09:58:10 Running command: terraform remote config -backend s3 -backend-config=key=terraform.tfstate -backend-config=encrypt=false -backend-config=region=us-east-1 -backend-config=bucket=my-bucket
Remote configuration updated
Remote state configured and pulled.
[terragrunt] 2017/01/24 09:58:13 Attempting to acquire lock for state file dev in DynamoDB
[terragrunt] 2017/01/24 09:58:13 Attempting to create lock item for state file dev in DynamoDB table terragrunt_locks
[terragrunt] 2017/01/24 09:58:14 Lock acquired!
[terragrunt] 2017/01/24 09:58:14 Running command: terraform refresh -state=/opt/deploy/state/dev/terraform.tfstate -var-file=dev.tfvars
Failed to load state: Remote state found, but state file '/opt/deploy/state/dev/terraform.tfstate' also present.
[terragrunt] 2017/01/24 09:58:15 Attempting to release lock for state file dev in DynamoDB
[terragrunt] 2017/01/24 09:58:15 Lock released!
exit status 1
[terragrunt] 2017/01/24 09:58:15 exit status 1
```

It seems like I need to run `terraform remote config` manually with the `-state` option as a one-time migration, and then never pass it to Terragrunt. Since this wasn't immediately obvious, perhaps it would be worthwhile to document this case? Ideally, Terragrunt could provide a way to perform the `remote config` explicitly (i.e. with `-state`, but without running any other command) based on the settings in `.terragrunt`, including creation and configuration of the S3 bucket, if necessary. I tried running `terragrunt remote config`, but it refuses to do anything:

```
Instead of manually using the 'remote config' command, define your remote state settings in .terragrunt and Terragrunt will automatically configure it for you (and all your team members) next time you run it.
```

That behavior makes sense unless `-state` is being specified.

**Comment by brikis98** [comment]
> Since this wasn't immediately obvious, perhaps it would be worthwhile to document this case? 

Good point! We should definitely have a "migrating state to Terragrunt" section in the Readme. PR's for that are very welcome!

> Ideally, Terragrunt could provide a way to perform the remote config explicitly (i.e. with -state, but without running any other command) based on the settings in .terragrunt, including creation and configuration of the S3 bucket, if necessary.

Agreed. Perhaps we need a `terragrunt terragrunt-init` command that:

1. Prompts you for the location of your current state (if any)
1. Prompts you to enter where you'd like state to be stored
1. Prompts you to specify if you'd like to enable locking
1. Based on all this info, terragrunt executes any necessary `remote config` commands and (optionally) generates the `.terragrunt` file for you. 
1. The command could also support various command-line flags so you can run it non-interactively.

A PR for that would also be very welcome!

**Comment by bwhaley** [comment]
At a glance, this looks to not be so relevant at this point. Since this issue was first opened, the `terraform remote` command has been removed entirely, and remote state and locking is native to Terraform. A local state can be migrated to remote by using `terraform state push`. 

Going to close this, but please reopen if I've misunderstood something here!
