### ISSUE TITLE
Terragrunt panic due to api body size.

### ISSUE THREAD

**Issue by bpastiu** [gruntwork-io/terragrunt#1073]
Hello,

We've encountered an interesting issue while deploying one of our stacks.
I can't go into specifics of the configuration for obvious reasons but I'll try to explain the best I can.

We are trying to deploy a aws_api_gateway_rest_api resource with the body being a rendered openapi template file. 
We didn't experience any issues up until now when there were some changes done to the openapi file. 
The openapi file is now about 3500 lines big and is causing the panic. We tested that this is the issue using a smaller openapi file and it worked fine.

I would like to as if there is any limitation to this we should take into account going forward.

**Comment by yorinasub17** [comment]
When you say "a rendered openapi template file", do you mean generated in terragrunt using `generate` blocks, or the template file data source? Also, does it work when you use terraform directly, instead of through terragrunt?

**Comment by bpastiu** [comment]
Hi, sorry for the delay. We are using the template file data source. We have the file (a openapi.yaml file) and just render it to be used as the body api. We only tried it with terragrunt.

**Comment by yorinasub17** [comment]
In that case, this is an issue with the AWS provider and not terragrunt, as at that point terragrunt is not doing anything. You should file the issue in https://github.com/terraform-providers/terraform-provider-aws/ so that they can look into it.
