### ISSUE TITLE
Failure when running apply-all for the first time within folder containing a terragrunt.hcl file

### ISSUE THREAD

**Issue by thisiscab** [gruntwork-io/terragrunt#1074]
Hello, 

I'm not sure if this is by design or if it is a bug, but I couldn't find documentation / related issues about this. 

Here is our folder structure:

```
.
|-- project
|   `-- web
|       `-- review
|           |-- dynamic
|           |   |-- cluster
|           |   |   `-- terragrunt.hcl
|           |   |-- provider.tf
|           |   |-- services
|           |   |   `-- api
|           |   |       `-- terragrunt.hcl
|           |   `-- terragrunt.hcl
|           |-- static
|           |   |-- certificates
|           |   |   |-- api
|           |   |   |   `-- terragrunt.hcl
|           |   |   |-- front-end
|           |   |   |   `-- terragrunt.hcl
|           |   |   `-- websocket
|           |   |       `-- terragrunt.hcl
|           |   |-- network
|           |   |   |-- vpc
|           |   |   |   `-- terragrunt.hcl
|           |   |   `-- vpc_peering
|           |   |       `-- terragrunt.hcl
|           |   |-- storage
|           |   |   |-- cache
|           |   |   |   `-- terragrunt.hcl
|           |   |   `-- db
|           |   |       `-- terragrunt.hcl
|           |   `-- terragrunt.hcl
```

It seems to pull all the states of the relevant dependency when running `terragrunt apply-all` from within `project/web/review/dynamic/services/api` but ultimately it fails because it tried to use my `mock_outputs` values of the dependencies.  Obviously, my mock_outputs values aren't pointing to real resources. 

Example of output: https://gist.github.com/cabouffard/9e21d3472d837708d8f5be414389fc3e

Ultimately, when running `terragrunt apply-all` from `project/web/review`, everything works as expected and it's able to pull the state of all my modules and `apply` (i.e. deploy) the ones that haven't been deployed. 

I had assumed that running `terragrunt apply-all` from a specific folder, would `apply-all` the dependencies specific to that module. 

The error I was seeing wasn't very straightforward and it took me a while to try to run it at the "root" folder which then worked.

I was wondering if perhaps this was a "bug" or it was a misunderstanding that I had about how this works. Perhaps, it's worth documenting this somewhere?

Thanks!
Have a great day!

**Comment by yorinasub17** [comment]
Did you run `terragrunt apply-all` with `--terragrunt-non-interactive`? If so, the behavior of the non interactive flag is to ignore external dependencies. If you wish to include them, you need to use [--terragrunt-include-external-dependencies](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-external-dependencies) in addition to the non interactive flag.

We could probably clarify that in the `--terragrunt-non-interactive` CLI arg docs. Would you be up for a quick PR to add that in?

**Comment by cabouffard** [comment]
Yes, I was using `--terragrunt-non-interactive` without `--terragrunt-include-external-dependencies`. I'll give it a shot and let you know if this works!

If it does, then I'll propose a PR with updated documentation.

Thanks!

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue, please create a new ticket with the updated context. Thanks!
