### ISSUE TITLE
terragrunt iam-role flag throws UnauthorizedOperation error

### ISSUE THREAD

**Issue by abhishiekgowtham** [gruntwork-io/terragrunt#1075]
when i expose the aws credentials (secret key & access key) via env vars and try to run terragrunt with **iam-role flag** it throws UnauthorizedOperation error. 

But same as the above same scenario this time, i didn't expose the aws credentials via env vars instead i put them in .aws folder (aws profile) terragrunt is successful when assuming the role. 

Not sure what's the problem with env vars for aws creds, i've read the documentation clearly and it doesn't mention about this use case. 

Probably, this is more of a question rather than an issue.

**Comment by brikis98** [comment]
> when i expose the aws credentials (secret key & access key) via env vars and try to run terragrunt with iam-role flag it throws UnauthorizedOperation error.

Could you share the actual error? And how you're setting your credentials (but not the credentials themselves!).

**Comment by vikas027** [comment]
I too remember facing the same issue. The env variable worked fine for me
`TERRAGRUNT_IAM_ROLE="arn:aws:iam::${account_number}:role/${iam_role}"`

@jack-of-AllTrades  Can you pls try to use the environment variable, something like this?

```
TERRAGRUNT_IAM_ROLE="arn:aws:iam::${account_number}:role/${iam_role}" terragrunt validate-all
```

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue, please open a new ticket with the updated context. Thanks!
