### ISSUE TITLE
Bump Terraform version to 0.12.10

### ISSUE THREAD

**Issue by lennoxj** [gruntwork-io/terragrunt#1080]
# Description
In version [0.12.10](https://github.com/hashicorp/terraform/blob/v0.12.21/CHANGELOG.md#01210-october-07-2019) of Terraform includes a function `cidrsubnets`.

`cidrsubnets`, which is a companion to the existing function `cidrsubnet` which can allocate multiple consecutive subnet prefixes (possibly of different prefix lengths) in a single call.

# Current behaviour
With the following `terragrunt.hcl`:

```
locals {
    subnets = [for cidr_block in cidrsubnets("10.0.0.0/8", 8, 8, 8, 8) : cidrsubnets(cidr_block, 4, 4)]
}
```

Terragrunt fails with:

```
terragrunt.hcl:2,34-45: Call to unknown function; There is no function named "cidrsubnets". Did you mean "cidrsubnet"?
```
# Expected behavior
Terragrunt should be able to execute `cidrsubnets`.

# Proposed fix
Update the terraform version constraint to [0.12.10 (October 07, 2019)](https://github.com/hashicorp/terraform/blob/v0.12.21/CHANGELOG.md#01210-october-07-2019).

**Comment by yorinasub17** [comment]
This is now addressed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.4
