### ISSUE TITLE
OS specific run_cmd

### ISSUE THREAD

**Issue by sleungcy** [gruntwork-io/terragrunt#1089]
since terragrunt support multi platforms including windows, linux, and macOS.

Is there a way I can determine the the platform before run_cmd function? For example it should run the .bat rather than the .sh in windows, a different version of the .sh on macOs.. etc.

**Comment by yorinasub17** [comment]
We currently don't support this. I think the way to support this would be to add a terragrunt helper function that returns the current OS platform information. Then you can use conditionals logic for this:

```
get_platform() == "windows" ? run_cmd("powershell.exe") : run_cmd("bash")
```

**Comment by edgarsandi** [comment]
@sleungcy @yorinasub17 
This issue/enhancement has been done and can be closed!

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_platform

**Comment by brikis98** [comment]
That's right! Thanks to @edgarsandi, you can now use the `get_platform()` helper to solve this issue with the [v0.23.21 release](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.21)!
