### ISSUE TITLE
Docs on website use low contrast navigation

### ISSUE THREAD

**Issue by rdonkin** [gruntwork-io/terragrunt#1090]
The docs website is very nice and I'm sure a lot of effort went into this.

One thing that should be improved is the low contrast navigation on the left - this is quite illegible making the site much harder to use.

In this screenshot, note how the main doc text on right is easily readable while the text in navigation is not:

![navigation example with low contrast](https://user-images.githubusercontent.com/2864605/76619734-7803d800-6523-11ea-8f01-f61f555953c6.png)

Some reasons why low-contrast text is a problem for usability as well as accessibility:   https://www.nngroup.com/articles/low-contrast/

**Comment by brikis98** [comment]
Good point! Would you be up for a PR to fix this?

**Comment by rdonkin** [comment]
I'm not a web developer so won't be doing a PR, but a simple adjustment of this light grey to darker grey may be enough.

**Comment by brikis98** [comment]
Fixed by @agseijas in #1094.
