### ISSUE TITLE
Terragrunt graph-all?

### ISSUE THREAD

**Issue by akingscote** [gruntwork-io/terragrunt#1093]
Hello,

Im trying to create a terraform graph of my entire infrastructure. not just the individual modules.

my project structure is as follows:
```
myproject
├── production
│   ├── nic-vm1
│   │   └── terragrunt.hcl
│   ├── nic-vm2
│   │   └── terragrunt.hcl
│   ├── subnet-vm1
│   │   └── terragrunt.hcl
│   ├── subnet-vm2
│   │   └── terragrunt.hcl
│   ├── aks-prod
│   │   └── terragrunt.hcl
│   └─── terragrunt.hcl
└── modules
    ├── azurerm_nic
    │   ├── main.tf
    │   ├── outputs.tf
    │   └── vars.tf
    ├── azurerm_aks
    │   ├── main.tf
    │   ├── outputs.tf
    │   └── vars.tf
    └── azurerm_vm
        ├── main.tf
        ├── outputs.tf
        └── vars.tf

```

If I got into each production item (vm1, vm2 etc..) i can run `terragrunt graph` and use the output and it will automatically include any dependencies for that item.

When i build my infrastructure, i simply run `terragrunt apply-all` from the production directory, which will use the top level terragrunt.hcl.

What I dont know how to do, it get a terragrunt graph-all type output which shows my entire infrastructure in one command. Or even a way of concatenating the outputs from the individual terragrunt graphs would work.

This modular layout that im using seems very popular, so im suprised nobody has asked it before. unless there is something obvious about how to do it that im missing.

```

**Comment by brikis98** [comment]
I've personally found the `graph` command to not be too useful for large infrastructure, as the graph gets too big and intertwined to read... But if you can find a way to support this, a PR is welcome. See also #492.

**Comment by akingscote** [comment]
I just ran the following: https://github.com/gruntwork-io/terragrunt/pull/1117
Which looked like this:
```
terragrunt graph-dependencies | dot -Tsvg > graph.svg
```
And it does the job!
The formatting isnt ideal, but i can play around with that myself.

**Comment by yyarmoshyk** [comment]
the following will generate the graphs with objects in rectangular shapes (shape=rect) and will connect them with lines with sharp edges (splines=ortho)
```bash
terragrunt graph-dependencies | dot -Tsvg -Nshape=rect -Gsplines=ortho -o graph.svg
```
