### ISSUE TITLE
Environment spanning multiple regions

### ISSUE THREAD

**Issue by nithyk** [gruntwork-io/terragrunt#1096]
1. What is the recommended folder structure for environments that have resources in multiple regions, for example, "cross-region AWS RDS" or "geo-redundant Azure storage account"?
2. I tried using "include" to reference a secondary region but that is traversing to a different child from the parent.  I dont think that is elegant!
3. What about the state file in such a case?   The need is to still have it per-environment but where should the definition be - continue in environment.hcl or move up to region.hcl or account.hcl?
4. Should a Disaster-Recovery setup be considered as another environment parallel to Production?  Or can a special folder structure be prepared for this, since the deployment would be to multiple-regions?

**Comment by brikis98** [comment]
The answer to most of these is that it depends on your specific details and trade-offs. That said, here is some general advice:

One option is to deploy using separate `terragrunt.hcl` files: e.g., for RDS in prod, you might have `infrastructure-live/prod/us-east-1/rds/terragrunt.hcl` and `infrastructure-live/prod/eu-west-1/rds/terragrunt.hcl`. The benefit of this approach is that it keeps each region truly independent, including all the resources and Terraform state, so if one region goes down, you can still make changes in the other. The downside is that this very property makes it harder to share data between those regions: e.g., if you need the ID or URL of a resource in one region to set up replication in the other, you either use a `dependency` block (but then the regions aren't as decoupled!) or you manually copy/paste the value. 

Another option is to deploy both regions from a single `terragrunt.hcl` that points to Terraform code with multiple `provider` blocks (on per region). This has the opposite set of trade-offs: easy to share data, but the resources and state aren't really separate, so if a region goes down, you won't be able to use Terraform to manage it.

You may want disaster recovery in a separate AWS *account* (e.g., `infrastructure-live/prod/...` and `infrastructure-live/disaster-recovery/...`), or in a separate *environment* within the same account (e.g., `infrastructure-live/prod/us-east-1/prod/rds` and `infrastructure-live/prod/us-east-1/disaster-recovery/rds`), or in a separate *region* within the same account (e.g., `infrastructure-live/prod/us-east-1/rds` and `infrastructure-live/prod/eu-west-1/rds`), or some combination (e.g., separate account and separate region). What's best depends on what you want to optimize for. Different regions optimize for keeping the infrastructure isolated from a physical location perspective, so you can survive regional outages. Different accounts optimize for keeping the infrastructure more isolated from a security / authn / authz perspective, so you can survive human error. Different environments within an account optimize mostly for easy of use.

**Comment by nithyk** [comment]
Thanks for the detailed response.  Having separate terragrunt.hcl files under each region made sense for our PROD setup.  And since our DR is not truly across multiple account so we used the same approach as PROD and it works too.  But I see your point on DR being on multiple accounts and having terragrunt.hcl files separate at that level, thanks for that tip too!
