### ISSUE TITLE
No "trim" like functions available in terragrunt.hcl

### ISSUE THREAD

**Issue by mnedelchevbg** [gruntwork-io/terragrunt#1099]
Hi,
I'm trying to use the **built-in terraform** trim functions in my terragrunt.hcl files, but it appears that for some reason they are not available.
**TG Version:** v0.23.2 (latest version up to 25.03.2020)
**TF Version:** v0.12.24 (latest version up to 25.03.2020)

terragrunt.hcl code:
`inputs = {
  domain_name = trim("FancyText.", ".")
}`

Output when running plan/apply function:
`Call to unknown function; There is no function named "trim".`

**Same error when trying to use:**
- trim
- trimprefix
- trimsuffix

**Comment by brikis98** [comment]
I think those are relatively new functions. We'd have to bump our Terraform dependency version ([here](https://github.com/gruntwork-io/terragrunt/blob/master/Gopkg.toml#L80-L82)) to support those new functions. Would you be up for a quick PR to add this?

**Comment by mnedelchevbg** [comment]
@brikis98 you are right. After double checking the TF changelog, it appears that the trim* functions are introduced starting from TF 0.12.17. 
Do you want me to raise a PR by bumping the TF version to the latest available one (i.e v0.12.24) ?

**Comment by brikis98** [comment]
Assuming it's backwards compatible, then yes please!

**Comment by yorinasub17** [comment]
This is now addressed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.4
