### ISSUE TITLE
Q: First-class support for other cloud providers?

### ISSUE THREAD

**Issue by mlafeldt** [gruntwork-io/terragrunt#1100]
Hey,

Terragrunt currently allows to bootstrap AWS accounts (create S3 buckets and DynamoDB tables) and to assume IAM roles.

Are you generally interested in adding those features for other cloud providers like Azure, Alibaba, etc. as well?

This is more a question of design philosophy. If you want to primarily support AWS, fine. Otherwise, I would be more than happy to create a pull request.

Thanks!

**Comment by brikis98** [comment]
Currently, Terragrunt has first-class support for AWS and GCP. We are definitely interested in Azure as well. However, to be transparent, we (Gruntwork) are not currently working on Azure, so our ability to support it is very limited. See https://github.com/gruntwork-io/terratest/issues/89#issuecomment-582494195 for details and what we'd need to make it work.

**Comment by mlafeldt** [comment]
OK, thanks. I just wanted to know if there's interest in general. So you've answered my question.
