### ISSUE TITLE
AWS - Unable to tag S3 bucket and DynamboDB Table

### ISSUE THREAD

**Issue by vikas027** [gruntwork-io/terragrunt#1101]
## Environment
```
~ $ terragrunt --version
terragrunt version v0.23.2
~ $ terraform --version
Terraform v0.12.24
~ $
```

## Problem
I am trying to create S3 bucket and a DynamoDB table with tag. S3 Bucket and DyanamoDB table gets created but It looks like `s3_bucket_tags` and `dynamodb_table_tags` are ignored.

## Code

```hcl
remote_state {
  backend = "s3"

  config = {
    encrypt        = true
    bucket         = "terraform-state"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "ap-southeast-2"
    dynamodb_table = "terraform-locks"

    s3_bucket_tags = {
      mytag       = "myvalue"
    }

    dynamodb_table_tags = {
      mytag       = "myvalue"
    }
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

**Comment by brikis98** [comment]
Could you share the log output from the _first_ run? That is, the one that creates the bucket and table?

**Comment by vikas027** [comment]
Hey @brikis98 ,

I am not sure the cause of the same but the same code has started working now, maybe there was a slight glitch with AWS.

Anyways, I am closing this issue now.
