### ISSUE TITLE
Versioning is not enabled

### ISSUE THREAD

**Issue by naimishatshahconsulting** [gruntwork-io/terragrunt#1106]
Here's my remote config.
`remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    bucket         = "naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-west-2"
    encrypt        = true
    dynamodb_table = "my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60"
    profile        = "personal-services-dev"
  }
}`

Here is the output from Terragrunt/Terraform.

[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Waiting for bucket naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60 to be created
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 S3 bucket naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60 created.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 WARNING: Versioning is not enabled for the remote state S3 bucket naimishshah-dev-terraform-c13f60a4-e2a6-4c1b-9647-db3a47932b60. We recommend enabling versioning so that you can roll back to previous versions of your Terraform state in case of error.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Lock table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Creating table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 in DynamoDB
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:30 Table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 is not yet in active state. Will check again after 10s.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:40 Success! Table my-lock-table-c13f60a4-e2a6-4c1b-9647-db3a47932b60 is now in active state.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:40 No tags for lock table given.
[terragrunt] [/Users/naimishshah/Workspace/Personal/terragrunt-trial] 2020/03/29 18:39:40 Running command: terraform init

**Comment by brikis98** [comment]
What version of Terragrunt?

Also, minor request: could you wrap your code and log output in a [fenced code block](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) so it's easier to read? Thanks!

**Comment by Quaiks** [comment]
Hello! I am having the same issue
 This is my remote state configuration 

```
remote_state {
  backend      = "s3"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    encrypt        = true
    region         = "eu-west-1"
    key            = format("%s/terraform.tfstate", path_relative_to_include())
    bucket         = "terraform-states-stg"
    dynamodb_table = "terraform-locks-stg"
  }
}
```
The S3 bucket ends like this

<img width="1065" alt="Captura de pantalla 2020-05-14 a las 16 48 27" src="https://user-images.githubusercontent.com/2082202/81949128-c6f0eb00-9602-11ea-9aa1-3d4531f8e1cf.png">

terraform version v0.12.25
terragrunt  v0.23.17

**Comment by gmaghera** [comment]
I am also seeing this, and I'm wondering if it's an issue with terragrunt or some restriction imposed by my AWS account settings.

**Comment by ahummel25** [comment]
Also seeing this same issue. My `remote_state` looks the same as @Quaiks. Any solution for this?

**Comment by brikis98** [comment]
Did Terragrunt create the S3 buckets for you? If so, do you have the log output from that?

**Comment by ahummel25** [comment]
I ended up tearing down my state management infra (S3, dynamo, etc.) and recreating. It versioned my S3 bucket that time. I probably did something incorrect the first time or maybe had the versioning flag set to false by accident.

**Comment by yorinasub17** [comment]
I believe the fundamental issue exposed here is that terragrunt only enforces these features on the initial bucket creation, and not on existing buckets that were created outside terragrunt, or by older versions of terragrunt.

I recall seeing a ticket requesting this exact feature, but can't find it at the moment. Will keep this open with the `needs-triage` label, until we can find (or create a new one) that feature request ticket and link to it.

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.37.0
