### ISSUE TITLE
Delete Dependencies are out of order. 

### ISSUE THREAD

**Issue by Vad1mo** [gruntwork-io/terragrunt#1111]
I have three modules VPC, DB and APP. DB and the APP has a dependency to the VPC and APP to DB.

I am able to bring the infra up with `apply-all` because I have setup `mock_outputs` and `mock_outputs_allowed_terraform_commands`

However I am not able to `destroy-all` correctly because VPC is gets destroyed first resulting in empty outputs for APP and DB which then fail. 

I would expect that there is some sort of reverse dependency resolution during destroy but it seems there isn't one.

**Comment by yorinasub17** [comment]
Thanks for reporting. Will be taking a look at this next week.

**Comment by yorinasub17** [comment]
Sorry for the delay in responding. After investigation, I could not repro: the `destroy-all` command does destroy everything in the expected order.

Can you share your terragrunt config and run logs, with any sensitive information redacted?

**Comment by Vad1mo** [comment]
Sorry could not carve out a reproducible case anymore. I close it for now if I happen to reproduce it I'll reopen.

**Comment by jlarfors** [comment]
I ran into this issue as well. Here's my experience:

1. `terragrunt run-all destroy` works as expected and ordering is correct
2. `terragrunt run-all apply -destroy` destroys the dependencies in the order they would be `apply`'d (which is wrong for a destroy!)

**Comment by brikis98** [comment]
> I ran into this issue as well. Here's my experience:
> 
> 1. `terragrunt run-all destroy` works as expected and ordering is correct
> 2. `terragrunt run-all apply -destroy` destroys the dependencies in the order they would be `apply`'d (which is wrong for a destroy!)

Ah, that makes sense. Terragrunt currently only detects `run-all destroy` as the one that needs to be run in reverse order; I don't think we've added support for `run-all apply -destroy` yet. A PR to add that is very welcome.
