### ISSUE TITLE
Add a terragrunt-debug command

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#1112]
Add a new `terragrunt terragrunt-debug` command that can help debug Terragrunt issues. It would do the following:

1. Enable debug logging
1. Generate a `terraform.tfvars` file with all the variables in the `inputs = { ... }` block.
1. Print all the variables, and if possible, where they were read from, to `stderr` so they user can see them directly. 
1. Print other diagnostic info to `stderr`: Terragrunt version, Terraform version, file paths, etc.
1. Print the path to the working dir. This is often something convoluted like `.terragrunt-cache/xxx/yyy/<repo>/<your module>`, so being able to see it easily, and know that there is a `terraform.tfvars` file sitting in that folder will allow you to run `terraform` directly in that folder. This helps diagnose issues that are in Terraform itself, rather than Terragrunt.

Other ideas for what would help debug Terragrunt issues are welcome!

**Comment by steve-a-jones** [comment]
You should be able to achieve this with hooks, but requires a bit of setup -- would be nice to trivially see what inputs were passed to a module when errors like "Error: Invalid value for module argument" arise.

**Comment by yorinasub17** [comment]
This is implemented now https://terragrunt.gruntwork.io/docs/features/debugging/

**Comment by dmitriy-kharchenko** [comment]
@yorinasub17 but `--terragrunt-debug` doesn't work.

I execute `terragrunt  apply-all --terragrunt-debug` but don't see `terragrunt-debug.tfvars.json` file.

```
terragrunt version v0.27.1
Terraform v0.14.4
```

**Comment by yorinasub17** [comment]
The current implementation of debug does not work with `xxx-all` commands. They are intended to be used with single modules. We should have a new ticket for supporting `xxx-all` debug though.
