### ISSUE TITLE
Version not printing when building from source

### ISSUE THREAD

**Issue by mjrc** [gruntwork-io/terragrunt#1113]
When building the lastest version of terragrunt (0.23.4) from source the program does not print any version information to the console when being invoked without any command line arguments. It also does not recognize the `--version` argument, returning `flag provided but not defined: -version`. I do not get this behavior when using the binary release (terragrunt_darwin_amd64). Are there specific build instructions I need for getting this to work?

- macOS 10.15.4 (19E266)
- go version go1.14.1 darwin/amd64

**Comment by yorinasub17** [comment]
This is by design, as we don't want to autocommit the version after we tag or vice versa. The version is set using ldflags at build time:

```
go build -o terragrunt --ld-flags "-X main.VERSION=v0.23.4" .
```

See https://github.com/gruntwork-io/terragrunt/blob/master/main.go#L14 for more info.
