### ISSUE TITLE
Graph representation of the terragrunt dependencies similar to terraform graph

### ISSUE THREAD

**Issue by mauriciopoppe** [gruntwork-io/terragrunt#1116]
It would be great to have a visual representation similar to `terraform graph` but with the terragrunt dependencies, something like:

```sh
terragrunt plan-all --terragrunt-graph | dot -Tsvg > graph.svg
```

This could be applied to the *-all commands

Related https://github.com/gruntwork-io/terragrunt/issues/1093

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.7. Binaries will show up shortly
