### ISSUE TITLE
Qeustion - Common State file for modules?

### ISSUE THREAD

**Issue by vikas027** [gruntwork-io/terragrunt#1126]
### Environment
```bash
➜  ~ terraform --version 
Terraform v0.12.24
➜  ~ terragrunt --version
terragrunt version v0.23.6
```

### Problem/Question
I have forked [terragrunt-infrastructure-live-example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example) and stripped down to a very basic structure and pushed to my [branch](https://github.com/vikas027/terragrunt-infrastructure-live-example/tree/test).

After applying all modules, the terraform state file gets populated into different directories. Is there a way to have one common file for all modules, in my example `module1` and `module2`? This way I would be able to use variables like `${module.<module_name>.<output_var>}` in the code.

```bash
~/.../qa (test) $ aws s3 ls --recursive s3://vikasxxx-terragrunt-example-terraform-state-non-prod-us-east-1/non-prod/us-east-1/qa 
2020-04-08 15:17:29        563 non-prod/us-east-1/qa/module1/terraform.tfstate
2020-04-08 15:17:29        563 non-prod/us-east-1/qa/module2/terraform.tfstate
```

**Comment by brikis98** [comment]
That's precisely the opposite of what the multi-folder structure is trying to achieve! Having all your state in a single file creates lots of issues in terms of security, performance, all-eggs-in-one-basket, etc. See [5 Lessons Learned From Writing Over 300,000 Lines of Infrastructure Code](https://blog.gruntwork.io/5-lessons-learned-from-writing-over-300-000-lines-of-infrastructure-code-36ba7fadeac1), [Terraform, VPC, and why you want a tfstate file per env](https://charity.wtf/2016/03/30/terraform-vpc-and-why-you-want-a-tfstate-file-per-env/), and [How to Manage Terraform State](https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa).

**Comment by vikas027** [comment]
Thanks, @brikis98 

I am closing the ticket.
