### ISSUE TITLE
Add information about AUR packages to the installation docs

### ISSUE THREAD

**Issue by sudoforge** [gruntwork-io/terragrunt#1131]
I maintain two packages for Arch Linux users in the AUR (user repository):

* [`aur/terragrunt`][0], which builds Terragrunt from a versioned release (the `.tar.gz`)
* [`aur/terragrunt-bin`][1], which fetches a prebuilt binary for a release

I'm able to follow releases pretty close to when they are created, and plan on automating this in the future. I'd like to update the documentation to inform users that this installation option is available, but per the contributing docs, thought I should check in first.

[0]: https://aur.archlinux.org/packages/terragrunt
[1]: https://aur.archlinux.org/packages/terragrunt-bin

**Comment by yorinasub17** [comment]
That sounds great to add! Feel free to open a PR to mention them in this list: https://github.com/gruntwork-io/terragrunt/blob/master/docs/_docs/01_getting-started/install.md
