### ISSUE TITLE
ability to use `cd` in the before hook execute command

### ISSUE THREAD

**Issue by gittur** [gruntwork-io/terragrunt#1136]
I would like to create a global plugins directory but do not want to commit the plugins to git. So everytime `terragrunt` | `init` |  `apply` | `plan` are run they have a before hook that `cd`'s into the global directory and does a terraform init.

```
terraform {
before_hook "before_hook" {
    commands     = ["init", "apply", "plan"]
    execute      = ["cd", "${get_parent_terragrunt_dir()}/global", "&&", "terraform init"]
  }
  extra_arguments "init_args" {
    commands = [
      "init"
    ]

    arguments = [
      "-get-plugins=true",
      "-plugin-dir=../global/.terraform/plugins/linux_amd64/",
    ]
  }
  }
```

`cd` is not an executable so it does not work! any other possibilities to accomplish this?

`terragrunt version v0.23.8`

**Comment by brikis98** [comment]
To answer your direct question, Terragrunt expects a binary and arguments to be passed, whereas  `cd` and `&&` are shell built-ins. If you want to rely on those, you need to execute a shell explicitly: something along the lines of: 

```hcl
execute = ["bash", "-c", "cd ${get_parent_terragrunt_dir()}/global && terraform init"]
```

Also, Terraform has a way to configure the [provider cache globally](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache).

**Comment by gittur** [comment]
thankyou for your response. Yes, I eventually used `bash`.
