### ISSUE TITLE
Option to reuse downloaded plugins?

### ISSUE THREAD

**Issue by kernelold** [gruntwork-io/terragrunt#1142]
I have a lot of modules related same plugins like hashicorp/aws
So while init I see a lot of messages like: 
```
- Downloading plugin for provider "aws" (hashicorp/aws) 2.57.0...
```
Is it possible to have an option to store this plugin somewhere in cache after first download and re-use it in other modules if version is the same instead of downloading every time?

In general the issue is - init can take a lot of time 
```
real    0m30.394s
user    0m7.236s
sys     0m5.631s
```
I guess it might be related to downloads.

**Comment by brikis98** [comment]
Have you looked at https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache?

**Comment by kernelold** [comment]
Yes, I tried `export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"`
but I still can see :
```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.11.1...
- Downloading plugin for provider "kubernetes" (hashicorp/kubernetes) 1.11.1...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.58.0...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.58.0...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.58.0...
- Downloading plugin for provider "null" (hashicorp/null) 2.1.2...

```
does it mean a real downloading or it's just a same message if cache is was used?

I'm doing it on mac btw
```
$ uname -v
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020
```

**Comment by ramnamy** [comment]
@kernelold What It is not a real download but a copy from plugin-cache folder to your project folder...You can see observe that by seeing how fast the command completes

**Comment by kernelold** [comment]
In that case can `Downloading plugin` message be changed to 'Got from cache' or something alike? Might be useful to understand what's really happening without assumptions.

**Comment by brikis98** [comment]
That output is from Terraform, not Terragrunt.
