### ISSUE TITLE
Proposal for fmt-all [-check]

### ISSUE THREAD

**Issue by jlsan92** [gruntwork-io/terragrunt#1145]
Hello, all 👋I really love how the `-all` commands work and how they propagate into subfolders, but I noticed that `fmt` is missing at this group. 

Just reaching out if this would make sense within this tool, personally speaking, I usually place `terraform fmt -check` on my CI pipelines, would love to have this feature with terragrunt as well. Also, I'd be more than happy to contribute on this 🙏 Thx

**Comment by lorengordon** [comment]
You could try `terraform fmt -recursive -check`...

**Comment by jlsan92** [comment]
Omg how could I miss that flag, thank you 👍
