### ISSUE TITLE
url location for plugins download

### ISSUE THREAD

**Issue by abhijitvikash** [gruntwork-io/terragrunt#1146]
Can you please provide the url location of these plugins: 
Downloading plugin for provider "aws" (hashicorp/aws) 2.58.0...
Downloading plugin for provider "datadog" (terraform-providers/datadog) 2.7.0...

**Comment by brikis98** [comment]
Plugins/providers are downloaded by Terraform, not Terragrunt. The exact location depends on your configuration. Typically, they end up in a `.terraform` folder in your working directory (though [there may be caching too](https://github.com/gruntwork-io/terragrunt/issues/1149)). The working directory depends on how you're using Terragrunt, but if you have a `source = "..."` URL in your `terragrunt.hcl`, it'll be within `.terragrunt-cache`.
