### ISSUE TITLE
Terragrunt do not handle cache plugin setting from .terraformrc

### ISSUE THREAD

**Issue by magnetik** [gruntwork-io/terragrunt#1149]
Hi,

I've set in my ~/.terraformrc: `plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"`

When running terraform without terragrunt, I can see that the providers are in this directory.

When using terragrunt, I see that all providers are redownloaded in the `.terragrunt-cache/xxxx/.terraform/plugins/` directory.

Is there something wrong in my configuration?

**Comment by brikis98** [comment]
Terragrunt does not download any provider code; that's 100% handled by Terraform. 

Also, note the following items from the [docs](https://www.terraform.io/docs/configuration/providers.html):

> This directory must already exist before Terraform will cache plugins; Terraform will not create the directory itself.

You need to create `$HOME/.terraform.d/plugin-cache` manually, if you haven't already.

> If the selected plugin is not already in the cache, it will be downloaded into the cache first and **then copied from there into the correct location under your current working directory.**

(emphasis mine)

With a plugin cache, Terraform will still copy the plugin code into your working dir (e.g., into `.terragrunt-cache/xxxx/.terraform/plugins/` when using Terragrunt)... It just doesn't download those plugins via the Internet.

**Comment by magnetik** [comment]
Oh my bad I missunderstood the documentation and thought caching was also about gaining disk space. 

Thanks for your detailled answer.

**Comment by cveld** [comment]
I don't think terragrunt can work with a centralized `plugin_cache_dir`; at least on Windows. Whenever terraform is running parallel processes it starts complaining and fails when a plugin file is being read by another process.
