### ISSUE TITLE
Error while applying local module with dependencies

### ISSUE THREAD

**Issue by Ludonope** [gruntwork-io/terragrunt#1153]
This error seems to have appeared out of nowhere, I'm fairly sure there was no modification to the modules.

I have a repository with several modules defined:
```
infra-modules/
    api_gateway/
    lambda/
```

I have instances of the lambda module, which are dependencies to the api_gateway one:
```hcl
# lambda_1/terragrunt.hcl

terraform {
  source = "git::git@.../infra-modules.git//lambda?ref=v0.4.7"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  # those are good since I can deploy this module alone
}
```

```hcl
# api_gateway/terragrunt.hcl

terraform {
  source = "git::git@.../infra-modules.git//api_gateway?ref=v0.4.7"
}

include {
  path = find_in_parent_folders()
}

dependency "lambda_1" {
  config_path = "../lambda_1"
}

inputs = {
  # ...
  routes = {
    "lambda/1" = {
      invoke_arn = dependency.lambda_1.outputs.invoke_arn
    }
  }
}
```

I have made some changes to the api_gateway module sources, and deployed it with `--terragrunt-source ../../some/path/infra-modules/api_gateway`. I've been doing it for some times and it worked until now.

Now when doing the same command I get the following output:
```
[terragrunt] 2020/04/25 06:56:50 Reading Terragrunt config file at project/api_gateway/terragrunt.hcl
[terragrunt] [project/lambda_1] 2020/04/25 06:56:50 Reading Terragrunt config file at project/lambda_1/terragrunt.hcl
[terragrunt] [project/lambda_1] 2020/04/25 06:56:50 Running command: terraform --version
[terragrunt] [project/lambda_1] 2020/04/25 06:56:50 Downloading Terraform configurations from file:///.../infra-modules/api_gateway into project/lambda_1/.terragrunt-cache/3TdfHHS0BO_0v2vC-ft0NU2NOfc/1R8eB7ZsOBj7_ZZv88Euel22VWc
[terragrunt] [project/lambda_1] 2020/04/25 06:56:50 Copying files from project/lambda_1 into project/lambda_1/.terragrunt-cache/3TdfHHS0BO_0v2vC-ft0NU2NOfc/1R8eB7ZsOBj7_ZZv88Euel22VWc/lambda
[terragrunt] [project/lambda_1] 2020/04/25 06:56:50 Setting working directory to project/lambda_1/.terragrunt-cache/3TdfHHS0BO_0v2vC-ft0NU2NOfc/1R8eB7ZsOBj7_ZZv88Euel22VWc/lambda
[terragrunt] 2020/04/25 06:56:50 Did not find any Terraform files (*.tf) in project/lambda_1/.terragrunt-cache/3TdfHHS0BO_0v2vC-ft0NU2NOfc/1R8eB7ZsOBj7_ZZv88Euel22VWc/lambda
[terragrunt] 2020/04/25 06:56:50 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

I obfuscated a little and simplified the output as much as possible to make it readable since there are quite a few lambda modules giving some similar output.

The interesting part is that making a new tag on the `infra-module` repository, pushing it, and using that new version in the `api_gateway` module (so without using `--terragrunt source`) makes it work, without changing anything to its implementation.

This bug occured after updating my system packages, even tho neither terragrunt or terraform was updated in the process, so it probably doesn't come from there.

I'm running OSX Catalina, `uname -a` gives the following output:
```
Darwin ludonopes-mbp.home 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_6
```

**Comment by brikis98** [comment]
What version of Terragrunt?

See https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.9 for what might be the fix for the issue you're seeing.

**Comment by Ludonope** [comment]
I'm using terragrunt v0.23.10 with terraform v0.12.24. It seems pretty similar to the issue you linked, but I'm not sure if it's that.

**Comment by yorinasub17** [comment]
This is the same issue. It should work if you used the following for the source:

```
--terragrunt-source ../../some/path/infra-modules//api_gateway
```

(note the double slash before `api_gateway`). You can check out https://github.com/gruntwork-io/terragrunt/pull/1134#discussion_r407167726 for the description of what is going on and why you need `//` (ignore the suggestion about `--terragrunt-source-map` as that is not implemented yet).

**Comment by Ludonope** [comment]
Oooh okay, got it.

Thank you!
