### ISSUE TITLE
issue with find_in_parent_folders

### ISSUE THREAD

**Issue by moos3** [gruntwork-io/terragrunt#1155]
There's some odd behavior with find_in_parent_folders() I'm getting an error every time I use this function. It basically boils down to the pathing it is returning. 

```
Error in function call; Call to function "file" failed: no file exists at 
/Users/moos3/workspace/infra/terraform-envs/Zeus-2.0/environments/dev/folder/Users/moos3/workspace/infra/terraform-envs/Zeus-2.0/empty.yaml., 
and 2 other diagnostic(s)
```

This should be returning a path like such:

```
Users/moos3/workspace/infra/terraform-envs/Zeus-2.0/empty.yaml
```
and not 

```
/Users/moos3/workspace/infra/terraform-envs/Zeus-2.0/environments/dev/folder/Users/moos3/workspace/infra/terraform-envs/Zeus-2.0/empty.yaml
```

My hcl looks like this and it lives in `Zeus-2.0/environments/dev/` and empty lives in the root of `Zeus-2.0`

```
locals {
  contact           = "devops"                             # default contact
  company_id        = "mb"                                 # any string to identify the company for better resources naming. Keep max size of five chars.
  default_yaml_path = find_in_parent_folders("empty.yaml") 
  enabled_api_services = [                                 # APIs enabled by default for all projects when created
    "compute.googleapis.com",
    "cloudkms.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com",
    "serviceusage.googleapis.com",
    "storage-api.googleapis.com",
  ]
```

Any ideas on how to fix this issue ?

**Comment by yorinasub17** [comment]
Can you also share the call to `file`? I am suspecting you are running into the backwards incompatible change introduced in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.0

**Comment by moos3** [comment]
```
# Configure root level variables that all resources can inherit. This is especially helpful with multi-account configs
# where terraform_remote_state data sources are placed directly into the modules.
inputs = merge(
  yamldecode(
    file("${get_terragrunt_dir()}/${find_in_parent_folders("region.yaml", local.default_yaml_path)}"),
  ),
  yamldecode(
    file("${get_terragrunt_dir()}/${find_in_parent_folders("env.yaml", local.default_yaml_path)}"),
  ),
  yamldecode(
    file("${get_terragrunt_dir()}/${find_in_parent_folders("service.yaml", local.default_yaml_path)}"),
  ),
  {
    billing_account : local.gcp_billing_account,
    company_id : local.company_id,
    org_id : local.gcp_org_id,
    region : local.region
  },
  {
    enabled_api_services : local.enabled_api_services
  },
  {
    inet_ranges : local.inet_ranges
  },
  {
    contact : local.contact
  }
)
```

**Comment by yorinasub17** [comment]
Ah yes you need to update `${get_terragrunt_dir()}/${find_in_parent_folders()}` to be `${find_in_parent_folders()}` as described in the release notes for `0.23.0`.

**Comment by sheldonhull** [comment]
@antonbabenko  i looked at your new repo, but don't see how to set any common or region variables to be imported as in this repo. Any tips? I'm new to terragrunt and this is the snag I'm currently hitting as well.

**Comment by antonbabenko** [comment]
@sheldonhull I am not sure which repo you are referring to so please open an issue there or ask a general Terragrunt question in this repository (probably open a new issue for that if it is not related to the current one).

**Comment by sheldonhull** [comment]
> @sheldonhull I am not sure which repo you are referring to so please open an issue there or ask a general Terragrunt question in this repository (probably open a new issue for that if it is not related to the current one).

I'm really sorry was juggling tabs. This was meant to be in the terragrunt architecture reference guide.

My issue still stands that looking up a common.tfvars using this method fails to ever find it.
Will open as a new issue. Sorry for the confusion.

**Comment by yorinasub17** [comment]
Closing this issue as the original question has been answered.
