### ISSUE TITLE
get-all command?

### ISSUE THREAD

**Issue by jamesgoodhouse** [gruntwork-io/terragrunt#1157]
I like the idea of being able to run `plan-all` and `apply-all`, but our current Terraform setup has us running `terraform get -update` to check for any updates of modules before running. I see there's a `terragrunt get`, but what about a `terragrunt get-all` command?

**Comment by yorinasub17** [comment]
Closing as duplicate of https://github.com/gruntwork-io/terragrunt/issues/492. Please follow that ticket to stay informed. Thanks!
