### ISSUE TITLE
point to output variable from another module with terraform.tfvars

### ISSUE THREAD

**Issue by mshenhera** [gruntwork-io/terragrunt#116]
Hello,

I setup project structure according to readme file:

```
infrastructure-live
  └ stage
    └ vpc
        └ .terragrunt
        └ terraform.tfvars
    └ app
        └ .terragrunt
        └ terraform.tfvars
```

And .terragrunt from APP runs module that requires vpc_id variable. VPC runs module that outputs vpc_id variable. The question is how to declare vpc_id from VPC in terraform.tfvars? I tried to refer to variable ${module.MODULE_NAME.OUTPUT_NAME} but without any success.

--
Thank you

**Comment by brikis98** [comment]
Use the `terraform_remote_state` resource. See the "read only state" section of [How to manage Terraform state](https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa#.1575oag7f) for an example.

**Comment by mshenhera** [comment]
Thank for the replay. Actually I went through this documentation before creating the issue. I can't figure out how to use  `terraform_remote_state` within `terraform.tfvars`.  I understand how to get it from terraform template file but not from terragrunt variables file.

**Comment by josh-padnick** [comment]
> I can't figure out how to use `terraform_remote_state` within `terraform.tfvars`

You can't include Terraform resources in the `terraform.tfvars`, only variable initializations like:

```
foo = bar
baz = 1
woz = ["a","b","c"]
dez = {
   "bla" = "hello"
   "wah" = "hi"
}
```

You need to declare your `terraform_remote_state` block in your `.tf` file, but if some part of it needs to be dynamic, you can pass variables to it.

**Comment by npepinpe** [comment]
Sorry for piggybacking on this question, but I ran into the same issue.

I did get it to work with terraform_remote_state if I hard-code the path to the correct bucket/key, but I'm using interpolation in my main terraform.tfvars file.

Example:

./global/terraform.tfvars
```hcl
terragrunt = {
  remote_state = {
    backend = "s3"
    config {
      region = "eu-west-1"
      bucket = "terraform"
      key = "${path_relative_to_include()}/terraform.tfstate"
    }
  }
}
```

./iam/terraform.tfvars
```hcl
terragrunt = {
  include = {
    path = "../global/terraform.tfvars"
  }
}
```

Now, this works:

```hcl
data "terraform_remote_state" "iam" {
  backend = "s3"
  config {
    bucket = "terraform"
    key = "iam/terraform.tfstate"
    region = "eu-west-1"
  }
}
```

Is there any way to somehow refer to my `iam` module without hard-coding the S3 key settings?

**Comment by brikis98** [comment]
You can read the `key` from a variable:

```hcl
data "terraform_remote_state" "iam" {
  backend = "s3"
  config {
    bucket = "terraform"
    key = "${var.iam_remote_state_key}"
    region = "eu-west-1"
  }
}

variable "iam_remote_state_key" {}
```

However, if you're asking whether you can automatically set that variable to the value defined in the Terragrunt configuration in some `terraform.tfvars` file, then the answer is currently no. Currently, Terragrunt configuration and variables do not interact with Terraform variables in any way. It may be possible to build some solution for that, but I'm not sure if that would be a good idea...

**Comment by npepinpe** [comment]
You're probably right, I'll stick to variables for now. Thanks!

**Comment by brikis98** [comment]
OK, hopefully all questions in this issue have been answered, so I'm going to close it.
