### ISSUE TITLE
Code validation excludes `*.tf.json` files.

### ISSUE THREAD

**Issue by atlaskerr** [gruntwork-io/terragrunt#1167]
`checkFolderContainsTerraformCode` only checks for `*.tf` file extensions and excludes valid `*.tf.json` files.

See the following:
https://github.com/gruntwork-io/terragrunt/blob/a316898e9043efe4d5333efeeee941a16a738608/cli/cli_app.go#L592

Upon inspection of the validation logic, I think we could solve this by using `zglob.Match` instead of `zglob.Glob` to check for the existence of both `**/*.tf` && `**/*.tf.json` files.

**Comment by brikis98** [comment]
Good point. Are you up for a PR to fix this?
