### ISSUE TITLE
Feature request: dynamic backend storage

### ISSUE THREAD

**Issue by bluemalkin** [gruntwork-io/terragrunt#1168]
Hi,

In my terragrunt.hcl I can configure the remote state:
```
remote_state {
  backend = "gcs"

  config = {
    bucket = "BUCKET-NAME"
    prefix = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```

This requires the .tf code to have somewhere:
```
terraform {
  required_version = ">=0.12.24"
  backend "gcs" {}
}
```

Since I am coding modules, I do not want to explicitly enforce that my module MUST use the backend  storage of type gcs.

Some user may want to use the backend storage of another cloud. 
I am looking to instead have something like this:
```
terraform {
  required_version = ">=0.12.24"
  backend  {}
}
```

And terragrunt.hcl will magically inject in the backend config.

Is this feasible or too complex to achieve ?

**Comment by brikis98** [comment]
You can use a [generate block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate) to code-generate whatever `backend` settings you want so you don't need it in the Terraform (`.tf` files) at all.

**Comment by kromol** [comment]
I had similar problem and solved it with `generate` block as suggested above. When we develop modules we keep backend configuration in a separate file named `backend.tf`. It does not contain anything else. (We do the same for provider as well).

In root `terragrunt.hcl` we just put this:
```hcl
generate "backend.tf" {
  path      = "backend.tf"
  if_exists = "overwrite"
  contents  = file("${get_parent_terragrunt_dir()}/backend.tf.template")
}
```
And then template is simple backend config:
```hcl
# Values will be injected by terragrunt
terraform {
  backend "s3" {}
}
```

It also works for modules which do not have any backend configuration defined..

**Comment by yorinasub17** [comment]
Also want to mention that you can use the `generate` attribute of `remote_state` (https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#using-the-generate-property-to-generate-terraform-code-for-managing-remote-state) if you wish to use the features of terragrunt autocreating s3 and gcs buckets without explicitly specifying a backend block using the `generate` block.

**Comment by yorinasub17** [comment]
Closing as `generate` is the recommended approach for handling this.
