### ISSUE TITLE
terragrunt import broken for indexed resources

### ISSUE THREAD

**Issue by madarve** [gruntwork-io/terragrunt#1174]
It might not be the import command per se, but that's where this issue becomes evident:

1. When trying to import a resource that has a named index (i.e. it was created with a `for_each`), the terraform import command is unable to parse the quoted index, making it impossible to run the command via terragrunt:

```
terragrunt import aws_iam_policy.my_policy["my_named_policy_in_a_loop"] arn:aws:iam::123456789:policy/my_policy
```

Running the above command results in an unquoted terraform output that will of course fail:
```
Running command: terraform import -var-file=/path/to/account.tfvars aws_iam_policy.my_policy[my_named_policy_in_a_loop] my_named_policy_in_a_loop

Error: Index value required
  on <import-address> line 1:
   1: aws_iam_policy.my_policy[my_named_policy_in_a_loop]
Index brackets must contain either a literal number or a literal string.
```
Somehow the `"` are being translated and missed in the terraform command to execute.

Trying with single quotation also doesn't do the trick

**Comment by lorengordon** [comment]
@madarve this happens with straight terraform also. the shell is interpreting the quotes. try putting the whole resource id in single quotes... e.g.

```
terragrunt import 'aws_iam_policy.my_policy["my_named_policy_in_a_loop"]' arn:aws:iam::123456789:policy/my_policy
```

**Comment by madarve** [comment]
@lorengordon That's correct, my bad for the overlook :)
