### ISSUE TITLE
Download terraform using terragrunt

### ISSUE THREAD

**Issue by andrzejressel** [gruntwork-io/terragrunt#1177]
I have an idea for following feature:

There should be an option of setting desired terraform version (or git source) - terragrunt would download it and use it for execution.

In my workplace we have a lot of "state was created with newer terraform version, update your terraform" errors. Thanks to this feature everybody would be using the same terraform version. Also, updating terraform version by one person would update it everywhere.

**Comment by brikis98** [comment]
Hm, on the one hand, having Terragrunt automatically install Terraform has a nice charm to it, as it simplifies usage. On the other hand, there are quite a few questions to think through:

1. Which version of Terraform should be installed? Would Terragrunt have to parse the `required_version` in the Terraform code? Or would `terragrunt.hcl` define its own Terraform version? Or would we need to read it from the Terraform state file? What if all these various versions conflict?
1. What if Terraform is already installed on the current system? Use that? Override it if the version doesn't match? As per the previous item, which version to look at?
1. What operating systems should be supported? OS X? Windows? Linux? Which versions of each?
1. What method should be used to do the installation? E.g., Download the binary from the website and put it in `.terragrunt-cache`? Or some tmp folder? Or use some OS specific command like `brew install` or `apt-get install`? 
1. Should this be the default behavior? Or only enabled via some `--auto-install-terraform` CLI flag or `auto_install_terraform = true` config in `terragrunt.hcl`?

My guess is that this is a lot of complexity to take on without a clean solution that would work well for everyone, so I'm tempted to not add this as a Terragrunt feature, recommending instead that you install it out of band, or if it must be done by Terragrunt itself, creating a before hook that fits your use case.

That said, I'm open to input and suggestions. @yorinasub17, curious to hear your take too.

**Comment by yorinasub17** [comment]
I think there are also issues around disk usage sprawl. We already have a problem of terragrunt bloating the disk space, and if we are not clever about caching versions, this feature would only make things worse.

FWIW, you can enforce the particular terraform version that terragrunt uses using [terraform_version_constraint](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_version_constraint). This way, you ensure that terragrunt won't run unless the user is using that particular version of terraform. You can also consider using [tfenv](https://github.com/tfutils/tfenv) (depending on your OS) to handle the management of the terraform binary. See [our blog post](https://blog.gruntwork.io/how-to-manage-multiple-versions-of-terragrunt-and-terraform-as-a-team-in-your-iac-project-da5b59209f2d) for more details. I think you can also do something clever with `before_hook` to run `tfenv` based on the `terraform_version_constraint` to have an interim version of this.

Given all the workarounds available, I'm inclined to agree with @brikis98 that this is probably a lot of complexity to include into terragrunt. That said, if someone is willing to think through all these cases and propose a design into an RFC that addresses these concerns in a way that is maintainable, then I think it is worth adding in.
