### ISSUE TITLE
Feature Request: Support SOPS Decryption of Secrets

### ISSUE THREAD

**Issue by js-timbirkett** [gruntwork-io/terragrunt#1179]
Hi 👋 

I'm a heavy user of Terragrunt and it solves a lot of problems for us. I think something that would be awesome would be native static secret handling (decryption) and I think that SOPS (https://github.com/mozilla/sops) would be a good option.

This feature would let you store static secrets in your infrastructure repository and use them as inputs to your terragrunt stack or root modules at runtime.  

There are sops plugins for terraform you _could_ decrypt a file outside of terragrunt and then include it in your inputs but I think it might be a worthy addition to Terragrunt. 

### Why use `sops`?
It would externalise / decouple the encryption and the many ways of encrypting / decrypting data. Sops is able to encrypt / decrypt data with:
- PGP Keys
- AWS KMS Keys
- GCP KMS
- Azure Key Vault

and takes care of rotating / updating keys, is configurable for auditing etc... Basically, using it programmatically would reduce the need for Terragrunt to manage all those things and allow a handful of new functions to allow passing inputs from sops encrypted files and values to your modules.

**Comment by js-timbirkett** [comment]
This is really a placeholder issue as I intend to raise a PR for review very soon.

**Comment by brikis98** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.18. Thanks @js-timbirkett!!
