### ISSUE TITLE
spin-up should support terrgrunt plan

### ISSUE THREAD

**Issue by vincentkwok** [gruntwork-io/terragrunt#118]
`spin-up` could do `terragrunt apply` for multiple .terragrunt files in sub-directories. 

However, it still needs  `terragrunt plan` within each sub-directories to see the diff before apply. How about make spin-up support `plan` to see the summary of change in sub-directories as well?

**Comment by brikis98** [comment]
Are you suggesting that `spin-up` shows you the `terraform plan` output for each module before running `terraform apply` in all of them? I suppose an interactive "does this plan look OK?" that lets you preview what will happen before you do it would make sense. Perhaps it should be part of a new command like (e.g. `terragrunt spin-up-plan`). PRs welcome :)

**Comment by dhoer** [comment]
I think `spin-up` and `tear-down` should be deprecated in favor of; `plan-all`, `apply-all`, and `destroy-all`.  Not having a plan-all makes the use of spin-up risky and not really feasible for use.

**Comment by brikis98** [comment]
@dhoer I like that idea!

**Comment by beanderson** [comment]
a `output-all` would also be a helpful command to have instead of going into each directory to do an `output` there.

**Comment by fajpunk** [comment]
I started to work on `plan-all` in this branch:

https://github.com/fajpunk/terragrunt/tree/plan-all

The conceptual problem that I've run into is that a `plan` for one module (using `module` here as in the codebase--a collection of terraform config with its own remote state--rather than `module` as in a terraform module) may depend on remote state that is created by another as-yet-unapplied module.  This is caught in this update to the integration tests:

https://github.com/fajpunk/terragrunt/blob/plan-all/test/integration_test.go#L193'

Is there any way around this?

**Comment by fajpunk** [comment]
I think the closest we could get is to show `plan` output for each module, and an interactive confirmation to apply, before moving on to the next module, like @brikis98 suggested in https://github.com/gruntwork-io/terragrunt/issues/118#issuecomment-277235348 .

**Comment by brikis98** [comment]
Yes, I think that's correct. If a module has dependencies that haven't been deployed yet, you can't show a `plan` for it, so the interactive, `plan`-confirm-`apply`-repeat approach is probably as good as it'll get here.

**Comment by fajpunk** [comment]
Ok, I'll give this a shot over the weekend.  What should the command be called? `confirm-apply-all`?

**Comment by brikis98** [comment]
Perhaps `spin-up-interactive`? Or if the commands are going to be renamed to `apply-all` and `destroy-all`, then I guess this one would be `apply-all-interactive`.

**Comment by dhoer** [comment]
@fajpunk could `output-all` mentioned by @beanderson be added to the PR as well?

**Comment by dhoer** [comment]
Could the interactive be a switch, e.g. `apply-all -i` or `apply-all --interactive`?  I can see using this for plan-all as well to look at each section.

**Comment by luis-silva** [comment]
@fajpunk Is this something you're still working on?

**Comment by fajpunk** [comment]
Sorry @luis-silva, I'm not working on this anymore.  Go for it!

**Comment by brikis98** [comment]
Fixed in #195.
