### ISSUE TITLE
[question] redeclare 3rd party module variables

### ISSUE THREAD

**Issue by veilig2000** [gruntwork-io/terragrunt#1183]
I might be doing this all wrong or have my structure configured wrong.  But **how do I not have to redeclare 3rd party module variables**?  do I not write these modules into my personal module repo?

I have my module repo

```
terragrunt-modules
|
+-aws
  +-vpc
    +-connection
      + main.tf
      + variables.tf
      + outputs.tf
 ```

now say in my `main.tf`, I want to reference a 3rd party module from the terraform registry?
say this one for example: https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.33.0

if my `main.tf` module looks something like this

```
...

module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.33.0"

  name = var.name
  cidr = var.cidr
  azs = var.azs
  ...
}

resource "aws_network_acl" "private" {
  vpc_id = module.vpc.vpc_id

  subnet_ids = concat(module.vpc.private_subnets, module.vpc.database_subnets)
  ...
}

...
```

and my "live" repo looks like this

```
terragrunt-modules
+ company1
  +-aws
    +-prod
      +-vpc
        +-connection
          +-terragrunt.hcl
    +-dev
      +-vpc
        +-connection
          +-terragrunt.hcl
 ```

say one of these terragrunt.hcl files looks something like this

```
# ------------------------
# TERRAGRUNT CONFIGURATION
# ------------------------

terraform {
    source = "git::git@github.com:company/terraform-modules.git//aws/vpc/connection?ref=v1.0.0"
}

# Include all settings from the root terragrunt.hcl file
include {
    path = find_in_parent_folders()
}

prevent_destroy = true

# -------------------------------------------------------
# MODULE PARAMETERS
# These are the variables we have to pass in to use the
# module specifieid in the terragrunt configuration above
# -------------------------------------------------------
inputs = {
    aws_region = "us-east-1"

    name                = "company-web-vpc"
    cidr                = "172.24.0.0/20"
    azs                 = ["us-east-1a", "us-east-1b", "us-east-1c"]
   ...
}
```

I can't use the inputs (name, cidr, azs, etc...) that the 3rd party module needs unless I define them in my modules repo - but I don't think that sounds right?  since I'm not responsible for that module.  Do I create a `module.tf` in my "live" repo alongside my `terragrunt.hcl` file?  What is considered best practice for this?

**Comment by brikis98** [comment]
Terraform, by it's nature, prefers explicit over implicit. So, yes, if you are wrapping some module `foo` and you want to be able to pass variables to it from the operator (e.g., from `-var` arguments or from Terragrunt or anywhere else), then you have to re-declare those variables.

**Comment by veilig2000** [comment]
Gotcha,  given that - I was curious if there's a "best practice" when managing this scenario? As I often leverage modules from the terraform repository, I can see both sides of the coin. If I constantly am redeclaring a module in my "live" repo, then I'm constantly copy/pasting as I deploy that module (feels like it goes against the DRY mantra a bit).  But on the flip side, if I store the 3rd party module in my "modules" repo, then I'm constantly updating the modules repository if I want to keep the 3rd party module up to date.

**Comment by brikis98** [comment]
If you're using the modules from the registry directly, with 0 changes, then you don't need to copy/paste any variables. You set the `source` URL to the registry URL and you can provide the inputs you need via the `inputs = { ... }` block with no extra fuss.

If you're creating your own modules that reference several things from the registry and add your own resources, then you have no option but to copy/paste inputs.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
