### ISSUE TITLE
Feature request: before_hook before copying files to .terragrunt-cache

### ISSUE THREAD

**Issue by timecast** [gruntwork-io/terragrunt#1186]
we would like to use the git commit hash in a tag on our AWS resources. this information is not available anymore as Terragrunt is copying the files to .terragrunt-cache before using them

can we have something similar as a before_hook that is executed before TG is copying the code?

Thanks!

**Comment by yorinasub17** [comment]
I don't quite follow the full use case (why is the information not available?), but I think the after hook `terragrunt-read-config` is early enough that it achieves what you want.

See the example in https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform

**Comment by timecast** [comment]
when you specify in terragrunt.hcl:
terraform {
  source = "some_path"
}

and some_path is part of a git repo then you lose all git related information when TG is copying the files to the .terragrunt-cache folder

so if you want to apply the git commit ID in a AWS tag you need to get this information before TG is copying this - or you run something when executing TG in the original "some_path" directory

with after_hook "terragrunt-read-config" it works, but handling is not nice cause you have to create an external sript

Anyway with your proposal I was able to get it work - so you can close this
Cheers!

**Comment by yorinasub17** [comment]
Ahhh ok that makes sense.

Yea I think using hooks is the only way right now. I don't think we can implement any helper function that gets this information, as we need to parse `terragrunt.hcl` to get the source info, but the function needs to be evaluated to parse `terragrunt.hcl` so there is a chicken and egg problem here. I suppose we can overhaul the execution pipeline to take advantage of partial parsing more, but then the function implementation gets complicated.

Given all that, `after_hook "terragrunt-read-config"` is the official solution to this problem, so I will go ahead and close this.
