### ISSUE TITLE
data resource referencing module output from a terregrunt.hcl file

### ISSUE THREAD

**Issue by luisamador** [gruntwork-io/terragrunt#1187]
I'm giving a go to Terragrunt and I've come across an issue/scenario which I don't know how to overcome.

this is my terragrunt.hcl file:

```locals {
  # Automatically load environment-level variables
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))

  # Extract out common variables for reuse
  environment = local.environment_vars.locals.environment
  public_subnets = local.environment_vars.locals.public_subnets
  private_subnets = local.environment_vars.locals.private_subnets
  vpc_cidr_block   = local.environment_vars.locals.vpc_cidr_block

  region_vars = read_terragrunt_config(find_in_parent_folders("region.hcl"))

  availability_zones = local.region_vars.locals.availability_zones
  
}

# Use Terragrunt to download the module code
terraform {
  source = "git::git@github.com:terraform-aws-modules/terraform-aws-vpc.git?ref=v2.33.0"
}

# Include all settings from the root terragrunt.hcl file
include {
  path = find_in_parent_folders()
}

# These are the variables we have to pass in to use the module specified in the terragrunt configuration above
inputs = {
  
  name            = local.environment
  cidr            = local.vpc_cidr_block

  azs             = local.availability_zones
  private_subnets = local.private_subnets
  public_subnets  = local.public_subnets

  enable_nat_gateway   = true
  single_nat_gateway   = true
  one_nat_gateway_per_az = false
  enable_vpn_gateway   = false
  enable_dns_hostnames = true

  #Gateway VPC Endpoints
  enable_s3_endpoint   = true
  enable_dynamodb_endpoint = true

  #Interface VPC Endpoints
  enable_ec2_endpoint = true
  ec2_endpoint_security_group_ids  = [data.aws_security_group.default.id]

  tags = {
    Terraform   = "true"
    Environment = local.environment
  }
}
```

The problem here is that I'm using the Terraform vpc module and I need to pass in a Security Group ID to the ec2_endpoint_security_group_ids input. I need to somehow reference the default SG ID created by the module itself.

I've created an sg.tf file which sits next to the terragrunt.hcl file that looks like this:

```
data "aws_security_group" "default" {
  name   = "default"
  vpc_id = module.vpc.vpc_id
}
```

I don't know how to reference the vpc_id output from the VPC module exposed from the terragrunt.hcl file. I don't even know if I'm doing this correctly, can someone point me to the right direction?

So far I have always had the need to create additional resources which are not created by default from the Terraform modules that I'm calling from the terragrunt.hcl files. Is there any way to create a resource from the "terragrunt.hcl" file itself?
Here's also a snapshot of my current repository folder structure:

![image](https://user-images.githubusercontent.com/18208396/82239588-e94f7500-9930-11ea-923e-743a22c8023d.png)

Thank you.

**Comment by yorinasub17** [comment]
This is the same request as https://github.com/gruntwork-io/terragrunt/issues/1150 (the ability to call terraform data sources in terragrunt), and unfortunately, there isn't a clean way to do this nor is it something we will be supporting in the short term.

The reason the tf file doesn't work is because there is no way to update a variable using data sources in native terraform.

Your options for workarounds are:

- Create a module that runs the data source and outputs the results, and use `dependency` blocks to feed it in to the target module.
- Use `run_cmd` and `jsonencode` with the aws CLI instead of terraform data sources to look up the relevant data from within terragrunt.

**Comment by luisamador** [comment]
thanks for the explanation @yorinasub17

**Comment by adamwshero** [comment]
To specifically answer this question. You can solve by doing two things.

1. Create a local variable in your locals block to perform the query.
`image_id = trimspace(run_cmd("sh", "-c", "aws ssm get-parameters --names /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2 --region us-east-1 --query 'Parameters[0].[Value]' --output yaml"))
`
2. Create an input to refer to this local variable and use the replace function to remove the extra - and space from the YAML output. 

`image_id = replace(local.image_id, "- ", "")`
