### ISSUE TITLE
Source local terraform files.

### ISSUE THREAD

**Issue by konstantin-recurly** [gruntwork-io/terragrunt#1195]
```
Terraform v0.12.24
terragrunt version v0.23.14
```
In some cases, we would like to use data_source. 
For that was implemented this structure
```bash
.
├── cluster
│   └── terragrunt.hcl
├── data
│   ├── data.tf
│   └── terragrunt.hcl
├── firewalls
│   └── terragrunt.hcl
├── ips
│   ├── data.tf
│   └── terragrunt.hcl
├── kms
│   └── terragrunt.hcl
├── nat
│   └── terragrunt.hcl
└── subnets
    └── terragrunt.hcl
```
Where we have data folder with 
`data.tf` that has:
```hcl
variable "project_id" {
  type = string
}
data "google_project" "project" {
  project_id = var.project_id
}

output "project_number" {
  value = data.google_project.project.number
}
```
`terragrunt.hcl` that has: 
```hcl
terraform {
  source = "./"
}

# Include all settings from the root terragrunt.hcl file
include {
  path = find_in_parent_folders()
}
inputs = {}
```
Now we try to use the outputs from data folder like so
```hcl
terraform {
  source = "git@github.com:terraform-google-modules/terraform-google-kubernetes-engine.git//modules/beta-private-cluster?ref=v8.1.0"
}

dependency "subnets" {
  config_path = "../subnets"
}
dependency "kms_key" {
  config_path = "../kms"
}
dependency "data" {
  config_path = "../data"
}

dependencies {
  paths = ["../subnets", "../kms", "../data"]
}

```
All this works while we run it such as `terragrunt plan` 
If we would like to test a local module like so
```
terragrunt plan  --terragrunt-source "$TF_MODULES_PATH/terraform-google-kubernetes-engine//modules/beta-private-cluster"
``` 
I got an error
```
[terragrunt] [gke/subnets] 2020/05/22 14:57:54 Copying files from gke/subnets into /gke/subnets/.terragrunt-cache/XNuYzS1soLSZZEiouXjaCk7IReM/9XEm-aaMM4kcrssbEgiLlQVYJvY/modules/subnets
[terragrunt] [gke/subnets] 2020/05/22 14:57:54 Setting working directory to /gke/subnets/.terragrunt-cache/XNuYzS1soLSZZEiouXjaCk7IReM/9XEm-aaMM4kcrssbEgiLlQVYJvY/modules/subnets
[terragrunt] 2020/05/22 14:57:54 Unable to obtain the module path from the source URL './'. Ensure that the URL is in a supported format.
[terragrunt] 2020/05/22 14:57:54 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
It seems that it doesn't like the source path in `data/terragrunt.hcl` which is `source = "./"`
Not sure if that happened after the upgrade to the latest terragrunt version(v0.23.18) or it never worked with the ` --terragrunt-source`

I guess, my question would be is this by design or a bug?

**Comment by brikis98** [comment]
In the `terragrunt.hcl` in your `data` folder, you don't need this at all:

```
terraform {
  source = "./"
}
```

The default is to assume the Terraform code is in the same folder, so just remove that block, and I think things will work.

**Comment by yorinasub17** [comment]
FYI this will still fail even after the `"./"` fix if the module repo of the dependency blocks and gke modules are different, because you can't override the local state for just one of the modules. We need to implement https://github.com/gruntwork-io/terragrunt/issues/1138 to handle that scenario.

**Comment by konstantin-recurly** [comment]
I have removed that part from the `terragrunt.hcl` in the `data` folder
Now I have a different error.
```
terragrunt plan --terragrunt-source /git/terraform-modules/terraform-google-kubernetes-engine//modules/beta-private-cluster

[terragrunt] [/gke/data] 2020/05/23 10:39:40 Running command: terraform output -json
[terragrunt] 2020/05/23 10:39:41 Did not find any Terraform files (*.tf) in /gke/kms/.terragrunt-cache/v86ibmgQV_n58E7UWKa-Pn4cH84/9XEm-aaMM4kcrssbEgiLlQVYJvY/terraform-google-kms
[terragrunt] 2020/05/23 10:39:41 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
Is this could be related that I have dependencies?
```hcl
dependency "subnets" {
  config_path = "../subnets"
}
dependency "kms_key" {
  config_path = "../kms"
}
dependency "data" {
  config_path = "../data"
}

dependencies {
  paths = ["../subnets", "../kms", "../data"]
}
```
and the run with `--terragrunt-source` ignores their remote sources and tries to source them locally?

**Comment by yorinasub17** [comment]
> the run with --terragrunt-source ignores their remote sources and tries to source them locally?

Yes that is the issue, and unfortunately we don't currently have a workaround for this using CLI args until we implement `--terragrunt-source-map`.

To make this work, you have to actually switch the source in the `terragrunt.hcl` config to the local version temporarily...
