### ISSUE TITLE
Interrupt of `terragrunt plan` doesn't wait for the child proess to stop.

### ISSUE THREAD

**Issue by siers** [gruntwork-io/terragrunt#120]
Reproduction: run `terragrunt plan`, `^C` quickly thereafter, which drops you back to bash while seas of debug output, which you can't stop, overwhelm you.

This happens because `terragrunt plan` didn't `wait(3)` for `terraform plan` to finish, so the second `^C` may not be delivered, which, in case of `terraform plan` would have killed it, with the first one enabling prints of debug output.

**Comment by brikis98** [comment]
Good catch. I think this same problem happens with all Terragrunt commands and not only `plan`. The relevant code for how we execute Terraform is here: https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd.go. PRs welcome!
