### ISSUE TITLE
--terragrunt-parallelism should not be passed to terraform

### ISSUE THREAD

**Issue by gmyx** [gruntwork-io/terragrunt#1200]
I was doing some debugging and wanted to reduce or disable parallelism to figure out where my apply-all was failing. I tried to use: 
`terragrunt apply-all --terragrunt-parallelism 4`

But it immediately fails with terreform errors. Terraform does not like the unknown parameter. This can be shown with an empty folder and terraform apply --terragrunt-parallelism 4.

It seems terragrunt specific parameters are being passed to terraform and should not.

Terraform v0.12.24
Terragrunt v0.23.10
Windows Terminal on Windows 10 1909

**Comment by brikis98** [comment]
That flag was sonly added in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.16. Please upgrade and try again!

**Comment by gmyx** [comment]
I will have to hide in shame, should of checked for new version first. It works with 23.16. Sorry about that!

**Comment by brikis98** [comment]
No prob! Thx for closing the loop.
