### ISSUE TITLE
Update for terraform 0.12.26

### ISSUE THREAD

**Issue by moos3** [gruntwork-io/terragrunt#1203]
Can we get a fresh build for 0.12.26 support?

**Comment by yorinasub17** [comment]
Could you provide some context on what's in the new version that you need support for or that terragrunt is incompatible with?

**Comment by brikis98** [comment]
Closing, as Terragrunt has supported 0.12, 0.13, and 0.14 for a while. https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
