### ISSUE TITLE
How does terragrunt track with terraform 13 beta

### ISSUE THREAD

**Issue by jeffdyke** [gruntwork-io/terragrunt#1209]
My thinking is there is a chance that not much has to change, per how your software is built, but wanted to know if there are any specifics.  I'd like to beta test, but don't want to go away from terragrunt....so being lazy.

Thanks

**Comment by yorinasub17** [comment]
You should be able to start testing terragrunt with terraform 0.13 by using something like [tfenv](https://github.com/tfutils/tfenv) to install it alongside terragrunt. Alternatively, you can install terraform 0.13 under a different name (e.g. `terraform13`) and point terragrunt to it (either using [--terragrunt-tfpath](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-tfpath) or [terraform_binary](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_binary)).

Note that any new (or updates to existing) functions introduced in tf13 won't be available until we rebuild terragrunt.

If you find any issues, report back and happy to take a look!

**Comment by artemsablin** [comment]
Doesn't work with beta releases, due to 
https://github.com/gruntwork-io/terragrunt/blob/master/cli/version_check.go#L16

**Comment by yorinasub17** [comment]
Ah missed that. Thanks for pointing that out and the PR: https://github.com/gruntwork-io/terragrunt/pull/1227

**Comment by brikis98** [comment]
Closing, as Terragrunt has supported 0.13 for a while. https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
