### ISSUE TITLE
destroy-all seems to destroy all dependencies no matter what I do

### ISSUE THREAD

**Issue by bholzer** [gruntwork-io/terragrunt#1216]
I have a structure where multiple environments can depend on some global components. For example, I have environments `alpha` and `beta` that both depend on a docker repo created in a `global` directory.

```
.
.
├── alpha
│   ├── applicationA
│   └── applicationB
├── beta
│   ├── applicationA
│   └── applicationB
└── global
    └── repo
```

If I cd into `alpha` and `destroy-all`, it also wants to destroy the repo dependency which lives in `global`. This is a problem since `beta` still also depends on that component. What is the right approach here? Is there something I am missing?

I have tried using the `--terragrunt-ignore-external-dependencies` with no success.

**Comment by yorinasub17** [comment]
Are you by chance running it with `--terragrunt-non-interactive`? This will include all external dependencies. To ignore them without prompts, you need to run `--terragrunt-ignore-external-dependencies` without `terragrunt-non-interactive`.

**Comment by yorinasub17** [comment]
See https://github.com/gruntwork-io/terragrunt/issues/524 for background info on this.

**Comment by bholzer** [comment]
Ah, yes, that's exactly it. Thanks for the guidance!
