### ISSUE TITLE
prevent_destroy flag override ignored in child terragrunt.hcl

### ISSUE THREAD

**Issue by dudicoco** [gruntwork-io/terragrunt#1217]
Hi,

I have set `prevent_destroy = true` in my root terragrunt.hcl.
In one of the child terragrunt.hcl files I've tried to override this with `prevent_destroy = false`.

When trying to run destroy terragrunt is throwing an error that the `prevent_destroy` flag should be set to `false`.

Is this a bug?

Thanks

**Comment by brikis98** [comment]
So you're saying that when you run `destroy` in the child module, which has `prevent_destroy = false`, it's acting as if `prevent_destroy = true`? What version of Terragrunt?

**Comment by dudicoco** [comment]
@brikis98 correct.

Terragrunt version v0.23.23

**Comment by brikis98** [comment]
Hm, this is indeed a bug! I was able to repro with the following simple test case:

Root `terragrunt.hcl`:

```hcl
prevent_destroy = true
```

In `child/terragrunt.hcl`:

```hcl
include {
  path = find_in_parent_folders()
}

prevent_destroy = false
```

Run `terragrunt apply` in `child`... Then run `terragrunt destroy` in `child` and you get:

```
[terragrunt] [/tmp/ter-prevent/child] 2020/06/16 09:29:25 Running command: terraform --version
[terragrunt] 2020/06/16 09:29:25 Reading Terragrunt config file at /tmp/ter-prevent/child/terragrunt.hcl
[terragrunt] 2020/06/16 09:29:25 Module is protected by the prevent_destroy flag in /tmp/ter-prevent/child/terragrunt.hcl. Set it to false or delete it to allow destroying of the module.
[terragrunt] 2020/06/16 09:29:25 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

There must be some bug in the [code that merges child configs with included configs](https://github.com/gruntwork-io/terragrunt/blob/master/config/config.go#L492). Does anyone have time to take a look and submit a PR with the fix?

**Comment by brikis98** [comment]
This was fixed in https://github.com/gruntwork-io/terragrunt/pull/1223 and released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.31.
