### ISSUE TITLE
Can't retrieve outputs from data block

### ISSUE THREAD

**Issue by AzySir** [gruntwork-io/terragrunt#1225]
Apologies if this is a basic question. 

I've created this module -  

```
data "aws_iam_policy_document" "policy" { 
    version = "2012-10-17"
    policy_id  = var.policy_id


    dynamic "statement" {
        for_each = var.statements
        content {
            effect = statement.value["effect"]
            actions = statement.value["actions"]
            resources = statement.value["resources"]

            dynamic "condition" {
                for_each = statement.value["condition"]
                content {
                    test     = condition.value["test"]
                    variable = condition.value["variable"]
                    values   = condition.value["values"]
                }
            }
        }
    }
}
```

I want to read the output of this to my S3 module. But I literally can't seem to find how. I have the outputs set and it's displayed when I do a terragrunt apply. However when I reference the output(or data) in the S3 module I receive the below error

```
A data resource "aws_iam_policy_document" "policy" has not been declared in
the root module.
```

I've tried both below combinations with the S3 Module 

```
resource "aws_s3_bucket" "s3_bucket" {
  bucket = "mybucket-${var.environment}-${var.domain}-${var.name}"
  acl    = var.acl
  policy = data.aws_iam_policy_document.policy
}
```

```
resource "aws_s3_bucket" "s3_bucket" {
  bucket = "mybucket-${var.environment}-${var.domain}-${var.name}"
  acl    = var.acl
  policy = output.output_policy
}
```

**Comment by AzySir** [comment]
I wish the documentation was a little easier to understand but basically I got this working with a help of a friend.

Between the "inputs" and the "dependencies" documentation it is amazingly confusing.

Basically this is what I did (with his help)

First he linked me this. I read it but it still missed/wasn't clear enough on what the "inputs" actually does.

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/?fbclid=IwAR1P1l5So-ElyC_ExvYHKIlEFvqXPnBASd3BMjqHdf40EzSAlKw7IZ-HnSU#dependency

In the example or discussion of inputs it makes it sounds like it stores an environment variable which sounds like a dirty work around.

What it actually does is read the input from the dependency and stores it as a variable {}.

Steps to fix 

1. Declare a variable you will read into. Your output block will be read into this from your dependency. 
```
variable "policy" {
    type = string
    description = "asd"
}
```

2. Set your dependency (terragrunt.hcl)
```
dependency "policy" {
  config_path = "../policy"
}
```

3. Read your output from your dependency (terragrunt.hcl)
```
inputs = {
    policy = dependency.policy.outputs.output_policy
}
```

4. Use your output inside of your module (main.tf) - Refer to policy section 
```
resource "aws_s3_bucket" "s3_bucket" {
  bucket = "cbus-${var.environment}-${var.domain}-${var.name}"
  acl    = var.acl
  policy = var.policy
}
```

**Comment by AzySir** [comment]
Took me a while to find this and there was literally not one clear example of this just a reference to environment variables.

https://terragrunt.gruntwork.io/docs/features/inputs/

"Whenever you run a Terragrunt command, Terragrunt will set any inputs you pass in as **environment variables**."

**Comment by brikis98** [comment]
Sorry you struggled with this. Do you have suggestions on how to make the docs clearer?

**Comment by AzySir** [comment]
@brikis98 all you have to do is literally show other usages. I would've loved to create a PR.

I would've thought a more common use case was to read the variables from the dependencies.  Then use those variables inside of some resources.

By all means correct me if I'm wrong. I don't see much value to below personally. 

```
$ terragrunt apply

# Roughly equivalent to:

TF_VAR_instance_type="t2.micro" \
TF_VAR_instance_count=10 \
TF_VAR_tags='{"Name":"example-app"}' \
terraform apply
```

I think this (image below) also highlights that the documentation here may have taken a back seat. Why can't this be I
Input > Usage with Environment Variables 
Input > Usage with Resources

![Screen Shot 2020-06-22 at 6 44 58 pm](https://user-images.githubusercontent.com/37623164/85267430-9b420a00-b4b8-11ea-898d-d2b33c7baff8.png)

**Comment by brikis98** [comment]
> @brikis98 all you have to do is literally show other usages. I would've loved to create a PR.

PRs are welcome!

> By all means correct me if I'm wrong. I don't see much value to below personally.
> 
> ```
> $ terragrunt apply
> 
> # Roughly equivalent to:
> 
> TF_VAR_instance_type="t2.micro" \
> TF_VAR_instance_count=10 \
> TF_VAR_tags='{"Name":"example-app"}' \
> terraform apply
> ```

This shows that Terragrunt is setting those `inputs` as environment variables. Which seems to be what you were confused about? Is this not clear because you aren't familiar with this syntax for setting environment variables?

> I think this (image below) also highlights that the documentation here may have taken a back seat. Why can't this be -
> 
> ```
> Input > Usage with Environment Variables 
> Input > Usage with Resources
> ```
> 
> _(After a resource usage example has been added)_

Not sure I 100% follow, but if you think adding new sections to the `inputs` docs would be helpful, a PR is welcome!

**Comment by AzySir** [comment]
> This shows that Terragrunt is setting those inputs as environment variables. Which seems to be what you were confused about? Is this not clear because you aren't familiar with this syntax for setting environment variables?

No I'm well aware of what environment variables are but why would you be saving the number of instances as an environment variable? I mean every now and then, yes possibly. But again the more common use case I would've thought was reading a dependency variable!


> Not sure I 100% follow, but if you think adding new sections to the inputs docs would be helpful, a PR is welcome!

I'll add a PR on the page but I don't think I can edit the section can I? would have something like this

![Screen Shot 2020-06-22 at 7 06 32 pm](https://user-images.githubusercontent.com/37623164/85270026-122cd200-b4bc-11ea-90f2-1973b7b3bd98.png)

**Comment by yorinasub17** [comment]
Do these docs work for you in terms of explaining the usage you are looking for? https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules

If so, perhaps we could move it verbatim under inputs for better discoverability.

**Comment by AzySir** [comment]
@yorinasub17 It does - but I still think that can be written better. I actually got to this page (after my bashing head again this for a while) and overlooked creating a `variable block` for the `inputs`. 

Embarrassingly I'm happy to admit here I should have correlated this better! However idea of documentation is for it to be easy to follow and in this case it's just as simple as one detailed example and/or better flowing documentation

**Comment by yorinasub17** [comment]
I agree our docs can be better. The tricky part about all the docs is that you need to understand how terragrunt works at a high level with inputs, and then how terragrunt handles multiple modules, before you can understand how dependencies work. Otherwise, it won't be clear that the `dependency` block is taking the outputs of another module and passing it as inputs, and that it needs to be applied first (or applied with `apply-all`) before you can get the data (even if the module is just data sources).

Even if we add the docs under `inputs`, I worry if it would still be buried given that it is not a natural place for people to look unless they are reading through the docs top to bottom.

Not quite sure what the best approach is here...

---

With that said, I just realized that our docs never introduce `inputs` in the quickstart. We only mention it in passing at the end in "Promote immutable, versioned Terraform modules across environments", yet it is a very important piece of the config.

Perhaps one improvement is to start by introducing inputs in the introduction of the quick start?

**Comment by AzySir** [comment]
@yorinasub17 Terragrunt is a fantastic tool!! Even though there is that added level of complexity and pre-knowledge is required, Terragrunt finds a unique challenge because they have to attempt to follow the KISS principles whilst explaining a more complex solution (than say basic Terraform).

My recommendation would be to almost mirror the Terraform documentation in some way. If you think about it - no one is going directly to Terragrunt without coming via the Terraform route right? Is there an opportunity here to align the "basic terragrunt concepts" in a way that mirrors Terraform docs (whilst also providing examples)?

Then there could be more in-depth explanations?

Just a thought I'm happy to put something together for inputs and create a PR

**Comment by yorinasub17** [comment]
Since OP, we have an updated quick start that introduces `inputs` much earlier in the docs. I think this is probably the best we can do here for now regarding this confusion, so will close.

If there are other suggestions or follow ups, please open a new ticket with updated context. Thanks!
