### ISSUE TITLE
Terragrunt destroy-all ignore dependencies

### ISSUE THREAD

**Issue by thomashoef** [gruntwork-io/terragrunt#1228]
Hi all,

in our config we have a lambda we deploy which needs the IDs of other resources (vpc etc.) which is another repo.

```
dependencies {
  paths = [
    "../../remote-state-rds", "../../remote-state-vpc"
  ]
}

dependency "remote-state-rds" {
  config_path = "../../remote-state-rds"
}
```

We used dependency blocks to get the terraform_remote_state of these objects and output it. Works well, but it seems when we call destroy-all, it is trying to also destroy the dependency state. Can this be prevented?

**Comment by artemsablin** [comment]
Would one of these [options](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-ignore-external-dependencies) help? 

Also from what I can tell, running `xxx-all` commands affects the entire dependency-tree. Can you make do with just `destroy` rather than `destroy-all`?

**Comment by d4n13lbc** [comment]
I have the same issue, I'm deploying different api gateway stages which depends on an api gateway module. When I delete an stage I don't want to delete the api gateway because it is use by the rest of stages. Using destroy without all is not an option because I have dependencies in each api gateway stage module that indeed I want to delete (vpclink and nlb).

**Comment by yorinasub17** [comment]
You can either:

- Use [--terragrunt-exclude-dir](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-exclude-dir) to exclude that module from the `-all` command.
- Use the [prevent_destroy](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#prevent_destroy) flag in your `terragrunt.hcl` config to protect that module.

**Comment by d4n13lbc** [comment]
I solved it. I wanted to delete the modules inside uat (apigw-vpc-link, nlb, stage-uat, target-attach) without deleting the apigw one.

```
├── apigw
│   ├── swagger.yaml
│   ├── terraform.tfstate
│   └── terragrunt.hcl
├── cw-role
│   └── terragrunt.hcl
├── prod
│   ├── apigw-vpc-link
│   │   └── terragrunt.hcl
│   ├── nlb
│   │   └── terragrunt.hcl
│   ├── stage_proddev
│   │   └── terragrunt.hcl
│   ├── stage_prodprm
│   │   └── terragrunt.hcl
│   ├── stage_prodstd
│   │   └── terragrunt.hcl
│   └── target-attach
│       └── terragrunt.hcl
└── uat
    ├── apigw-vpc-link
    │   └── terragrunt.hcl
    ├── nlb
    │   └── terragrunt.hcl
    ├── stage-uat
    │   └── terragrunt.hcl
    └── target-attach
        └── terragrunt.hcl
```
 So this is the command that I employed:

```
cd uat
terragrunt destroy-all --terragrunt-ignore-external-dependencies
```

In this way I avoided to delete the apigw module which is an external dependency of my stage-uat module. It would be good to have a clear example in the documentaion for the --terragrunt-ignore-external-dependencies flag, it is quite confusing how to use it

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
