### ISSUE TITLE
--terragrunt-source fails for module that works fine via source ref

### ISSUE THREAD

**Issue by eoliphan** [gruntwork-io/terragrunt#1233]
Hi, I'm running into a really weird problem.  I've a module in a terragrunt config that has deps on a few other modules in the environment.  When I'm working on it in my `live-repo/<env>/..`tree and use `-terragrunt-source <rel or abs path>/local-module-source`, I get errors like the following:

```
[terragrunt] 2020/06/23 10:23:21 Did not find any Terraform files (*.tf) in /xxx/lab/eb-app-bucket/.terragrunt-cache/zZRVc7gnF9RUWaGdRzuXpBqEJ6c/EtuJte3jxsNZSbJkriGT3i-f3LU/eb-app-bucket
```
where `eb-app-bucket` is one of the modules the current one depends on.    

But if I push the module to my git repo and update the source ref in the terragrunt.hcl everything works fine.  Any Idea what might be causing this? 

Versions:
Terragrunt  v0.23.24
Terraform  v0.12.26
OS X: 10.15.5

**Comment by brikis98** [comment]
As of [v0.23.9](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.9), when you use `--terragrunt-source`, Terragrunt overrides the `source` not only of the current module, but also any `dependency` blocks. You most likely need a `//` to make sure it does it correctly. See the https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.9 release notes for an example.

**Comment by eoliphan** [comment]
Ok, understand.  But not 100% sure  how to fix my issue.  In my case, per the example in the release notes, my "app" is in a different repo in this case, so I actually just want "vpc" to behave as it did before.  We keep our common infrastructure modules in a "modules" repo and this update works fine when developing updates there.   But some app specific configs live with their associated apps (e.g. "app/tf_src"), so switching to 'alternatve' will break them.

**Comment by yorinasub17** [comment]
This use case unfortunately would need https://github.com/gruntwork-io/terragrunt/issues/1138 . Reintroducing the old behavior actually causes other things to break in subtle ways and the current mechanism is the most robust and easiest to understand.

Sorry I don't have a better suggestion for the moment...

**Comment by eoliphan** [comment]
Gotcha, for now will use the workaround of just pushing to the git repo

**Comment by yorinasub17** [comment]
Basic support for `--terragrunt-source-map` [is now released](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-source-map), which should provide a workaround for this issue. Will close as solved, but if there are any follow ups, please open a new ticket with updated context. Thanks!
