### ISSUE TITLE
0.9.9 checks out module folders as empty

### ISSUE THREAD

**Issue by justicel** [gruntwork-io/terragrunt#124]
Howdy. There seems to be some sort of regression between 0.9.9 and 0.9.8. If I have modules in my code defined something like:

module "my_module" {
  source = "git::ssh://git@github.com/myorg/mymodule.git//submodule"
}

It works fine in 0.9.8. If I upgrade to 0.9.9 and run the same code, it does not check out any of the sourcecode (any of the .tf files) for the module or submodule.

**Comment by brikis98** [comment]
I can't seem to repro this. What I tried:

1. Did a fresh checkout of a Git repo with Terraform configurations.
1. Went into a folder that had a `.tf` file with a `module` that sets its `source` URL to a git repo.
1. Ran `terragrunt plan`.

I can see Terragrunt running the `get` command and downloading the module's code.

What am I missing?

**Comment by justicel** [comment]
@brikis98 Hrmm. So I am both using a source definition inside .terragrunt as well as module that has sub-modules inside it. So for instance the .terragrunt definition that includes the module {} definition is:

include = {
  path = "${find_in_parent_folders()}"
}

terraform {
  source = "../../modules//network"
}

And then the code in there has a module call like I originally posted. This all works fine in 0.9.8 so I suspect it has something to do with the // module changes made in 0.9.9

**Comment by brikis98** [comment]
I'm still struggling to repro. Here's what I did this time:

1. Created `/tmp/issue-124/live` and `/tmp/issue-124/modules`.
1. Under `/tmp/issue-124/modules/network/main.tf`, added Terraform code with `module` that has a `source` URL set to a remote `git` repo.
1. Under `/tmp/issue-124/live/network/main.tf`, created a `.terragrunt` file that has a `terraform` block with the `source` set to `../../modules//network`.
1. Ran `terragrunt apply` in `/tmp/issue-124/live/network/main.tf`.

I see an output like this (edited a bit for clarity):

```
[terragrunt] 2017/02/09 11:51:39 Reading Terragrunt config file at /tmp/issue-124/live/network/.terragrunt
[terragrunt] 2017/02/09 11:51:39 Downloading Terraform configurations from file:///tmp/issue-124/modules into /var/folders/39/w935myd14p9197wbp67pz4940000gn/T/terragrunt-download/-h92qG3G-tBm47erEDvbSj-RYCs=/IfJEmd5i3xgfFGbJQWhLXW7w6Ro=
[terragrunt] 2017/02/09 11:51:40 Copying files from /tmp/issue-124/live/network into /var/folders/39/w935myd14p9197wbp67pz4940000gn/T/terragrunt-download/-h92qG3G-tBm47erEDvbSj-RYCs=/IfJEmd5i3xgfFGbJQWhLXW7w6Ro=/network
[terragrunt] 2017/02/09 11:51:40 Setting working directory to /var/folders/39/w935myd14p9197wbp67pz4940000gn/T/terragrunt-download/-h92qG3G-tBm47erEDvbSj-RYCs=/IfJEmd5i3xgfFGbJQWhLXW7w6Ro=/network
[terragrunt] 2017/02/09 11:51:40 Running command: terraform get -update
Get: git::ssh://git@github.com/brikis98/terraform-up-and-running-code.git (update)
[terragrunt] 2017/02/09 11:51:42 WARNING: you have not configured locking in your .terragrunt file. Concurrent changes to your .tfstate files may cause conflicts!
[terragrunt] 2017/02/09 11:51:42 Running command: terraform apply

... (code applies succesfully) ...
``` 

Notice the `Running command: terraform get -update`.

**Comment by justicel** [comment]
@brikis98 Pretty sure this will fix my bug if you wanted to close this issue https://github.com/gruntwork-io/terragrunt/pull/126

**Comment by brikis98** [comment]
Ah, gotcha! Thx for following up.
