### ISSUE TITLE
Terragrunt console not working in non-interactive mode

### ISSUE THREAD

**Issue by thomas-desforges** [gruntwork-io/terragrunt#1244]
**Versions**
Terragrunt v0.23.29
Terraform v0.12.28

**description**
Unable to use the terragrunt console in non-interactive scripts (supported by terraform console)

**Reproducing**
> `echo "1 + 5" | terragrunt console`

`[terragrunt] 2020/07/02 10:47:50 Running command: terraform console
[terragrunt] 2020/07/02 10:47:50 Hit multiple errors:
inappropriate ioctl for device
[terragrunt] 2020/07/02 10:47:50 error resizing pty: inappropriate ioctl for device`

**Comment by brikis98** [comment]
I didn't know `terraform console` supported non-interactive mode! Interesting feature. I think Terragrunt would have to forward `stdin` to make this work. If anyone is up for looking into it, a PR with a fix is very welcome.

**Comment by ngocketit** [comment]
This can be very crucial for scripting

**Comment by levkohimins** [comment]
Resolved in [v0.50.7](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.7) release.
