### ISSUE TITLE
Unable to pass variables into my terragrunt.hcl file.

### ISSUE THREAD

**Issue by devops-ameyer** [gruntwork-io/terragrunt#1248]
I'm looking to dynamically update my terragrunt hcl file by passing in variables into the provider information and keys. Unfortunately that doesn't seem to work for me..
```remote_state {
  backend = "s3"
   generate = {
       path = "backend.tf"
       if_exists = "overwrite"
  }
  config = {
    bucket                  = "bucket"
    key                     = "${path_relative_to_include()}/terraform.tfstate"
    region                  = "us-west-2"
    dynamodb_table          = "arm-terraform-state-lock"
    access_key              = "${var.tf_master_key}"
    secret_key              = "${var.tf_master_secret}"

  }
  generate = {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "aws" {
  region                  = "${var.region}"
}
EOF
```

When running
 ```
terragrunt apply --auto-approve \
   -var env=$ENV_SUFFIX \ 
   -var tf_master_key=$TF_MASTER_ACCESS_KEY \
   -var tf_master_secret_key=$TM_MASTER_ACCOUNT_ACCESS_KEY_ID \
   -var region=$AWS_DEFAULT_REGION
```

I get a var. doesn't exist. Is there no way to pass in and replace these variables?

**Comment by yorinasub17** [comment]
Unfortunately, Terragrunt doesn't support variables, as the main purpose of terragrunt is to set variables for terraform.

With that said, you can get something similar by using the [get_env](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_env) function and environment variables.

**Comment by devops-ameyer** [comment]
This is great! Thank you so much

sent from smart device.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!

**Comment by haytham-salhi** [comment]
Hi @yorinasub17, do we still have same limitation? We have a case where we need to substitute terraform variables in the generate block but it looks like it is not working? We true the get_env as well in generate block and it didn't work. Could you plz advise?
