### ISSUE TITLE
release-lock fails to parse .terragrunt file due to env_var function call: Invalid Interpolation Syntax

### ISSUE THREAD

**Issue by umeat** [gruntwork-io/terragrunt#125]
When attempting to run `terragrunt release-lock` I get the following exception:

> [terragrunt] 2017/02/14 01:39:23 Reading Terragrunt config file at ***/.terragrunt  
>Error parsing Terragrunt config file ***/.terragrunt: Error parsing Terragrunt config file ***/terraform/.terragrunt: Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${get_env("BUCKET_NAME", "")}'   

Where that .terragrunt file contains:

```
remote_state = {
  backend = "s3"
  config {
    encrypt = "true"
    bucket = "${get_env("BUCKET_NAME", "")}"
    key = "${path_relative_to_include()}/terraform.tfstate"
    region = "ap-southeast-2"
  }
}
```

`terragrunt plan` and `apply` both parse this config file without issue.

**Comment by brikis98** [comment]
Weird. I think `plan`, `apply`, and `release-lock` all go through the same code path for parsing...

What version of Terragrunt?

**Comment by l0010o0001l** [comment]
@umeat 

You may be using an outdated version of Terragrunt. I am on latest, and after testing your bucket syntax I had no issues acquiring a lock. The obvious difference I see here is that you are using a `.terragrunt` file which is soon to be deprecated. Try moving your `terragrunt` variables into a `terraform.tfvars` file and give it another go.

**Comment by brikis98** [comment]
No follow up on the issue. Moreover, since Terraform now natively supports locking, Terragrunt no longer does locking, and no longer has a `release-lock` command, so closing this issue.
