### ISSUE TITLE
File Content as Input Value

### ISSUE THREAD

**Issue by jcbagtas** [gruntwork-io/terragrunt#1251]
Scenario:
I need to extract the contents of the src_addr.txt file and use it as an input value to my Firewall Module.
Is there a proper way to do this?

My Current Firewall Module Usage:

**`src_addr.txt` Content**
``` json
[
    "192.168.0.4"
]
```

**Terragrunt Inputs**
``` hcl
nat_config = {
    source_addresses = file("./assets/src_addr.txt")
}
```

**Expected output:**
Build should push through because the content of the txt file is a set of string

**Actual Output:**
``` cmd
Error: Inappropriate value for attribute "source_addresses": set of string required.
```

**Comment by yorinasub17** [comment]
You need to use `json` or `yaml` with `yamldecode`/`jsondecode`. In fact, the contents of the file is valid `json` already so wrapping the `file` call with `jsondecode` should do the trick.

**Comment by jcbagtas** [comment]
> You need to use `json` or `yaml` with `yamldecode`/`jsondecode`. In fact, the contents of the file is valid `json` already so wrapping the `file` call with `jsondecode` should do the trick.

Thank you for this. I'll try it as soon as I can.

**Comment by jcbagtas** [comment]
This seems an easy problem to solve, thank you for helping. Does Terragrunt inherit all Terraform Functions? Do we have a documentation stating these capabilities?

Also, This worked. :) 
``` hcl
source_addresses = jsondecode(file("./assets/test.json"))
```

**Comment by yorinasub17** [comment]
> Does Terragrunt inherit all Terraform Functions? Do we have a documentation stating these capabilities?

Yes see https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#terraform-built-in-functions

**Comment by jcbagtas** [comment]
> > Does Terragrunt inherit all Terraform Functions? Do we have a documentation stating these capabilities?
> 
> Yes see https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#terraform-built-in-functions

Yes I've been reading this. Is it safe to assume that all terraform built-in functions are compatible with Terragrunt?

**Comment by yorinasub17** [comment]
Yes you can assume all the functions are compatible. If you find any that is not (which can happen if you are using functions released in newer terraform versions), file an issue and we can merge in the newer function relatively quickly.
