### ISSUE TITLE
Inputs - Optional Collections

### ISSUE THREAD

**Issue by akingscote** [gruntwork-io/terragrunt#1254]
Hi All,

Ive had a look through the issues and i cant quite find what im after.

How can i define optional collections as inputs in my terragrunt?

Specifically, how can i declare multiple `oauth2_permissions" blocks in my `terragrunt.hcl`?
[https://www.terraform.io/docs/providers/azuread/r/application.html#example-usage](https://www.terraform.io/docs/providers/azuread/r/application.html#example-usage)

I tried making an array of objects and passing that in, but if you look on that example, the declaration is:
```
 oauth2_permissions {
...
  }
```

and not
```
 oauth2_permissions = {
...
  }
```

There isnt a "type _equals_ value", its just declared?
Ive had this problem in the past and i end up creating a custom module for each varient of the azuread app registration, but im wondering if there is a better way to achieve this?

Thanks,
Ashley

**Comment by yorinasub17** [comment]
Terragrunt can only invoke modules, not resources directly. So the way to do this is to define a terraform module that creates the resource and translates the list of objects to the subblocks using [dynamic](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks).

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
