### ISSUE TITLE
terragrunt refresh does not work with local state defined

### ISSUE THREAD

**Issue by ibacalu** [gruntwork-io/terragrunt#1255]
I will try to explain the issue following my example below:

Consider my root hcl config
```yml
# terraform/aws/root.hcl
[...]
remote_state {
  backend = "local"
  generate = {
    path      = "backend.tf"
    if_exists = "skip"
  }
  config = {
    path = "terraform/state/${path_relative_to_include()}/default.tfstate"
  }
}
[...]
```

My mock org
```yml
# terraform/aws/terragrunt.hcl
include {
  path = find_in_parent_folders("root.hcl")
}

terraform {
  source = "${get_parent_terragrunt_dir()}/modules/aws//aws_organizations_organization"
}

inputs = {
  config = {
    feature_set = "ALL"
    enabled_policy_types = [
      "SERVICE_CONTROL_POLICY",
      "TAG_POLICY",
    ]
  }
}
```

Now, the issues:
* terragrunt plan works
* terragrunt refresh doesn't
```yml
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.


Outputs:

config = {
  "enabled_policy_types" = [
    "SERVICE_CONTROL_POLICY",
    "TAG_POLICY",
  ]
  "feature_set" = "ALL"
}
```

I've been able to fix it by adding following params to my root.hcl
```yml
terraform {
  extra_arguments "refresh_args" {
    commands = [
      "refresh"
    ]

    arguments = [
      "-state=terraform/state/${path_relative_to_include()}/default.tfstate",
    ]
  }
}
```
So, unfortunately I am not Go dev, but I am guessing that this local backend config is not passed correctly to refresh.
Cheers!

**Comment by yorinasub17** [comment]
My suspicion is with `if_exists = "skip"`. Do you by chance already have a `backend.tf` file in defined in your module? Does it work if you use `overwrite_terragrunt` instead?

**Comment by ibacalu** [comment]
> My suspicion is with `if_exists = "skip"`. Do you by chance already have a `backend.tf` file in defined in your module? Does it work if you use `overwrite_terragrunt` instead?

I don't have the backend.tf. I always clean the cache completely too.

**Comment by yorinasub17** [comment]
If you `cd` to the folder and run `terraform refresh`, does it use the backend config or the local path?

Note that what terragrunt is doing roughly is:

- Clone module to working dir
- `cd` to working dir
- Generate the backend.tf file
- Run `terraform init` if it hasn't yet.
- Run `terraform refresh` (with any extra args passed in through `extra_arguments`).

We don't have any special logic with the remote state if you have `generate` set (if `generate` isn't set, we pass the args in during `init`), so if there is an issue here, it is most likely with the way the terraform config is set up or how `terraform` handles `refresh`.

**Comment by yorinasub17** [comment]
Closing this as stale. If this is still an issue, please open a new ticket with updated context. Thanks!
