### ISSUE TITLE
Piping output to variable

### ISSUE THREAD

**Issue by devops-ameyer** [gruntwork-io/terragrunt#1264]
Hello,

I'm trying to run a "Terragrunt plan -out=$PLAN" but it seems I'm unable to use a variable with my plan. I'm trying to use gitlab ci to output the plan into gitlab merge requests but I'm unable to output the plan into a variable or create a plan file. 

This may be a specific problem with my gitlab ci but I wanted to run it by you guys as well.

**Comment by brikis98** [comment]
What is the full command you're running? And the full log output?

**Comment by devops-ameyer** [comment]
Sorry I decided to go a different route and didn't see this message. Thank you for responding!
