### ISSUE TITLE
"init" during single plan fails, but "init" during plan-all succeeds

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [gruntwork-io/terragrunt#1265]
I just started using Terragrunt, but I can't seem to figure out how to perform a terragrunt plan in a single module.

My directory structure looks like this
```
parentfolder/
-- terragrunt.hcl
-- isprod/
---- region/
------ env/
-------- module1/
---------- terragrunt.hcl
-------- module2/
---------- terragrunt.hcl
...
```

If I CD into any of my modules in my project and hit "terragrunt plan", I'll get an error during the part where it downloads the plugins for providers (like aws):

```
Error installing provider "aws": open .terraform\plugins\windows_amd64\terraform-provider-aws_v2.70.0_x4.exe: The system cannot find the path specified..
```

There's no terraform-provider-aws_v2.70.0_x4.exe downloaded into the terragrunt-cache, and when I check the logs, I only see these lines:

```
2020/07/24 16:12:06 [DEBUG] plugin cache is disabled, so downloading aws 2.70.0 from https://releases.hashicorp.com/terraform-provider-aws/2.70.0/terraform-provider-aws_2.70.0_windows_amd64.zip?checksum=sha256:76880f29fca7a0a3ff1caef31d245af2fb12a40709d67262e099bc22d039a51d
2020/07/24 16:12:06 [TRACE] HTTP client HEAD request to https://releases.hashicorp.com/terraform-provider-aws/2.70.0/terraform-provider-aws_2.70.0_windows_amd64.zip
2020/07/24 16:12:06 [TRACE] HTTP client GET request to https://releases.hashicorp.com/terraform-provider-aws/2.70.0/terraform-provider-aws_2.70.0_windows_amd64.zip
```

Yet if I go to the "env" folder (the parent of the modules folder) and run a `terragrunt plan-all`, I won't get this error.

Why? How do I fix this? Running this on a Windows 10 build btw.

**Comment by BrandonALXEllisSS** [comment]
I ended up moving the project up a few levels onto the C:/ drive, and it ended up working. I think the path name limit is the issue here.

But that's weird, I've got "LongPathsEnabled" enabled in my Windows registry, so I'm not sure why I would still be be getting such errors...

**Comment by brikis98** [comment]
Hm, it's Terraform that downloads providers, not Terragrunt... Perhaps there's a long path issue in Terraform?

**Comment by BrandonALXEllisSS** [comment]
Yes, that appears to be the case. [According to this issue](https://github.com/hashicorp/terraform/issues/21173), apparently it's been known for quite some time, but no action was ever taken. Terraform doesn't even see it as much of an issue at the current moment.
However, it appears that **Terragrunt's long filestructure practices and cache folder names exacerbate the problem much more than regular Terraform usage would**. Filename lengths can be more than doubled, which may come as a surprise to many Windows users.

For example, this is what my file structure looks like:
`C:\Users\MyName\Documents\GitHub\Company\SomeModerateLengthNameFromGit\terragrunt\non-prod\us-east-1\dev\ModuleName1` (116) characters
When using Terrgrunt, this file length more than doubles in length to something like this, which would break the character limit.
`C:\Users\MyName\Documents\GitHub\Company\SomeModerateLengthNameFromGit\terragrunt\non-prod\us-east-1\dev\ModuleName1\.terragrunt-cache\wbyIahsF75NRUmqsgfkayoriB2U\GWN0qcRXM-jg4-VfLLocS_sqUcw\.terraform\plugins\windows_amd\terraform-provider-aws_v2.70.0_x4.exe`  (259 characters)

Until Terraform/Go/Windows can put together a solution for this, it might be a good idea to at least put a warning out there for Windows users since this seems to happen under a normal use case in Terragrunt. Furthermore, it doesn't show error messages relevant to the problem (nothing about file-length) and hardly has any documentation at the current time...

**Comment by brikis98** [comment]
Understood. Would you be up for a PR to update the docs to mention this? Or even a warning that automatically shows up if we detect (a) Windows and (b) long file paths? 

BTW, one workaround is too override the [download dir](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-download-dir) to a shorter path.

**Comment by yorinasub17** [comment]
Closing this as stale. If there are any follow ups, please open a new ticket with updated context. Thanks!
