### ISSUE TITLE
Correct use of remote state dependencies

### ISSUE THREAD

**Issue by phatcher** [gruntwork-io/terragrunt#1268]
I'm converting my terraform scripts over to terragrunt, but I'm not sure if I'm doing in the best way.  Here's a simple example where I'm creating an Azure Container Registry...

```
# Providers
provider "azurerm" {
  version = "=2.0.0"
  features {}
}

terraform {
  required_version = ">= 0.12"
  backend "azurerm" {
  }
}

# External data
data "terraform_remote_state" "rg" {
  backend = "azurerm" 
  config = {
    subscription_id      = var.tf_subscription_id
    resource_group_name  = var.tf_resource_group_name
    storage_account_name = var.tf_storage_account_name
    container_name       = var.tf_container_name
    key                  = var.tf_rg_key
  }
}

# Resources
resource "azurerm_container_registry" "this" {
  name                   = "${lower(var.app_name)}${lower(var.environment)}acr"
  resource_group_name    = data.terraform_remote_state.rg.outputs.value.name
  location               = data.terraform_remote_state.rg.outputs.value.location
  sku                    = "Standard"
  admin_enabled          = true

  lifecycle {
    ignore_changes = [
      sku
    ]
  }
}
```
I can pass in all of the terraform_remote_state parameters apart from tf_rg_key but it seems a bit clunky. I had a look at module dependencies but the issue there was how to mock complex objects.

I know this one is simple and I could pass the parameters explicitly, but I'm trying to keep the dependency graph correct.  I also have other use-cases where I'm passing a list of regions for example or much more complex objects and I want to ensure that I can see the actual state object.

**Comment by yorinasub17** [comment]
Terragrunt provides the following two mechanisms for passing outputs between modules:

- Using `dependency` block to pull in the outputs in `terragrunt`.
- Using `terraform_remote_state` in your terraform module and pass through the state configuration as vars. Note that you could DRY this up by using common vars and `generate` blocks. See [the docs on generate blocks](https://terragrunt.gruntwork.io/docs/features/keep-your-terraform-code-dry/#dry-common-terraform-code-with-terragrunt-generate-blocks) for more info. You will also want to use `dependencies` blocks to hook the terragrunt graph in this case.

We don't actually have any other mechanism, and we are likely to invest more heavily into the `dependency` block.

**Comment by yorinasub17** [comment]
Closing this as stale. If this still an issue, please open a new ticket with updated context. Thanks!
