### ISSUE TITLE
After Terragrunt version 0.9+, missing permissions on AWS

### ISSUE THREAD

**Issue by cultavix** [gruntwork-io/terragrunt#127]
Good morning,

After upgrading to version `0.9.9`, CircleCI has started to error due to missing the following permission: 

`"dynamodb:ListTagsOfResource"`

This was not required before and the problem is that it's not included with the default, `arn:aws:iam::aws:policy/ReadOnlyAccess` policy from AWS.

As a work-around, I've added the above permission to my role.

**Comment by brikis98** [comment]
Are you sure it's Terragrunt? Could you post the log output?

A quick grep of the DynamoDB code shows the following calls using the AWS Go SDK:

```
GetItem
DeleteItem
PutItem
CreateTable
DescribeTable
DeleteTable
```

I don't see any calls to [ListTagsOfResource](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ListTagsOfResource.html)...

**Comment by brikis98** [comment]
Have not heard back on this in a few months, so closing. If it's still a problem, please post additional detail.
