### ISSUE TITLE
before_hook with apply runs with terraform output command 

### ISSUE THREAD

**Issue by wapmesquita** [gruntwork-io/terragrunt#1274]
I have Module A with a `before_hook` with `apply` command. I have Module B which has a dependency on Module A.

The before_hook is executed when I deploy only the Module B, on the `terraform output` command to get the values from the Module A.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.32

**Comment by StanBorbatTR** [comment]
It appears that now hooks do not run at all when processing dependencies. Neither of the following configurations triggers a hook during the output gathering phase:

`
before_hook "workspace_select" {
    commands = ["plan", "apply", "destroy", "output"]
    execute  = ["/bin/bash", "-c", "terraform workspace select ${get_env("ENV")} || terraform workspace new ${get_env("ENV")}"]
}

after_hook "workspace_select" {
    commands = ["init"]
    execute  = ["/bin/bash", "-c", "terraform workspace select ${get_env("ENV")} || terraform workspace new ${get_env("ENV")}"]
}
`

**Comment by StanBorbatTR** [comment]
Adding `disable_dependency_optimization = true` to the `remote_state` configuration block allows the hooks to run.

**Comment by yorinasub17** [comment]
Yup this is a known limitation and documented under [the docs for dependency](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency), section "Can I speed up dependency fetching?".

The relevant issue for the underlying fix is https://github.com/gruntwork-io/terragrunt/issues/1318
