### ISSUE TITLE
Terragrunt plan-all, apply-all workflow after running apply-all

### ISSUE THREAD

**Issue by esn89** [gruntwork-io/terragrunt#1278]
**Problem Statement:**

With a small dependency chain of the following modules as an example:  network <- database <- instances

I am using mock outputs like this, as an example for database:

```
dependency "network" {
  config_path = "../../../../resources/dev/network"

  mock_outputs = {
    network_id = "asdf1234"
    vpc_id = "12345"
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan"]
}

dependencies {
  paths = ["../network"]
}
```
When I have 0 resources in my infrastructure (very very first time running this), running `plan-all` shows that everything is fine, I see my mock outputs, the code in terragrunt.hcl code is syntactically correct and the infra is good.

Afterwards I run `apply-all` and voila, my infra is there.  

**Problem:**

Now that I have existing infra set up and running, whenever I run `plan-all` _in the future_, I want to see the **ACTUAL/CURRENT** outputs used throughout my stack, meaning the `network_id` should reflect the actual `network_id`, not "asdf1234", etc.

This is important because I will be making changes in my `terragrunt.hcl` inputs file, and I will change values there (for example, updating autoscaling group min/max, the values of DNS names) and `plan-all` is a way for me to verify against what values I have in my environment and what the change will be like.

Is there an easy way around this aside from going through every `terragrunt.hcl` after initial deployment and changing this:
```
mock_outputs_allowed_terraform_commands = ["validate", "plan"]
```

to 

```
mock_outputs_allowed_terraform_commands = ["validate"]
```

**Comment by yorinasub17** [comment]
This semantic is already supported in `mock_outputs`. That is, the dependency block only uses the mocks if no state file exists. So you can actually keep the code as is, and then run `plan-all` to see what it looks like with the real outputs.

**Comment by esn89** [comment]
This. Is. Amazing!  Thank you.
