### ISSUE TITLE
When was the 'dependency' block and 'input' block added into Terragrunt ?

### ISSUE THREAD

**Issue by AzySir** [gruntwork-io/terragrunt#1280]
Could someone help me find when the "dependency" block along with the "inputs" was added. I'm currently working on an old repository that needs some serious upgrading. I need to make a case as to why we should stick with Terraform and Terragrunt - or go to CloudFormation.

We are literally running Terragrunt v0.14.10 (face palm) - I want to incrementally upgrade it. At the same time we have tasks still coming in - so if I can get these dependency and input blocks working for the mean while that would be handy and I could show some immediate value. 

Can't search via the commit history in github and the releases are documentation so you can only go tag-to-tag. 

(Any help is more than welcome! - apologies if this is more of a GitHub question rather than a Terragrunt)

**Comment by brikis98** [comment]
It was first added in [v0.19.20](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.20). However, there were a number of improvements and bug fixes in subsequent releases, so if you're upgrading to `v0.19.x` anyway, you should at least use [v0.19.31](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.31).

In general, when upgrading, check the minor version bumps (e.g., `v0.10.x` to `v0.11.x`) to see what the backwards compatible change was, and if there's a migration step you need to do.

**Comment by AzySir** [comment]
@brikis98 really keen to know how you found it so quickly!!

I'm deliberating with the team now thank you for the advice!! Terragrunt has come along way !!

**Comment by brikis98** [comment]
> @brikis98 really keen to know how you found it so quickly!!

Haha, nothing fancy, just clicked a few times through the releases page :)

> I'm deliberating with the team now thank you for the advice!! Terragrunt has come along way !!

Good luck!
