### ISSUE TITLE
--terragrunt-debug in v0.23.33 does not seem to work

### ISSUE THREAD

**Issue by dcfsc** [gruntwork-io/terragrunt#1281]
I just saw the new 0.23.33 release with debugging from issue #1263. Woot! I need that now!

Installed and run:

```
$  terragrunt --terragrunt-debug init
Incorrect Usage. flag provided but not defined: -terragrunt-debug

DESCRIPTION:
   terragrunt - Terragrunt is a thin wrapper for Terraform that provides extra tools for working with multiple
...
VERSION:
   v0.23.33

AUTHOR(S):
   Gruntwork <www.gruntwork.io>
   
[terragrunt] 2020/08/03 15:42:30 flag provided but not defined: -terragrunt-debug
[terragrunt] 2020/08/03 15:42:30 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
The [Debugging](https://terragrunt.gruntwork.io/docs/features/debugging/#debugging) page shows `$ terragrunt --terragrunt-debug apply`.  I tried `apply` and it gives the same results as `init`.

I also tried `$  terragrunt --debug init` in case I was not understanding something. To me, it looks like the build was not successful. Perhaps someone else can tell me what I am doing wrong.

**Comment by yorinasub17** [comment]
Ah that is a bug in the docs! Terragrunt generally requires the terragrunt args to be at the end of the command, so it is actually supposed to be `terragrunt apply --terragrunt-debug`.

**Comment by dcfsc** [comment]
That did the trick. Thanks for your help.
