### ISSUE TITLE
Outputs not available after terragrunt import (Question/Help)

### ISSUE THREAD

**Issue by jeffdyke** [gruntwork-io/terragrunt#1287]
I have a modular set up so everything in in 4 vpcs across 2 regions share the same modules (that sounded stupid)  When i run `terragrunt import aws_vpc.main vpc-tftgtftg`.  The import succeeds but the state file doesn't have any outputs.  So when running `terragrunt plan/refresh` in a folder that will call a module that requires a `terraform_remote_state`  of `vpc.id` the outputs are empty.  I imported 3 vpcs in Janurary or so....Hoping i just forgot something simple!

Thanks, hard to search for, so i'm reaching out here and on reddit.

**Comment by brikis98** [comment]
Terragrunt doesn't have much to do with `import`, output variables, or state storage. I believe the question you're asking is more related to Terraform itself. My guess is that you may need to run `apply` after `import`. This may be a no-op in terms of infrastructure created, but I think running `apply` is what will update the available output variables.

**Comment by jeffdyke** [comment]
Thanks @brikis98  i was thinking that same thing later, i was able to get the outputs by commenting out the `terraform` block in terragrunt.hcl and run `terragrunt refresh`.
