### ISSUE TITLE
Passing an output from a remote state as a variable into a module

### ISSUE THREAD

**Issue by weebaws** [gruntwork-io/terragrunt#1295]
staging
├---terragrunt.hcl
├---process
----├---ec2.tf
----├---terragrunt.hcl
├---network
----├---subnet.tf
----├---output.tf
----├---terragrunt.hcl

in the Root `terragrunt.hcl` under `staging` i have the following `terraform_remote_state` to get the `state` of network and make it available to all. 
```
generate "provider" {
  path = "grunt-remote-states.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
data "terraform_remote_state" "networking" {
  backend = "s3"
  config = {
    bucket = "foo-tf-state"
    key    = "dev/networking/terraform.tfstate"
    region = "eu-west-1"
  }
}
EOF
}
```
in the `terragrunt.hcl` file under the `process` folder i have the following
```
terraform {
  source = "git::git@github.com:foo/tf_modules.git//process/aws_ec2?ref=v0.1"
}
inputs = {
    ami_id = "ami-07d9160fa81ccffb5"
    sub_id = data.terraform_remote_state.networking.outputs.subnet_eu_west_1a_id  <-- This is not recognised 
}

include {
  path = find_in_parent_folders()
}
```
 when i run it i get `terragrunt init `
`Unknown variable; There is no variable named "data"

Is it possible to pass a output from a remote state and an input into a module call using terragrunt ?

**Comment by yorinasub17** [comment]
Terragrunt does not do any processing of terraform data sources or resources in the terragrunt config. To do what you want, you need to use the `dependency` block. See [the docs](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules) for more information.

**Comment by weebaws** [comment]
thanks @yorinasub17

**Comment by drarko** [comment]
Is there a way to generate file "as is" 
I dont need terragrunt to interpret data, only write file in all child modules
