### ISSUE TITLE
Call a Terragrunt module from another module is not generating any Terragrunt related file

### ISSUE THREAD

**Issue by enrique-fernandez-polo** [gruntwork-io/terragrunt#1297]
Hello!!

Is it possible to call a terragrunt module from another terragrunt module? 

```terraform
module "the_called_module" {
  source = "..//the_called_module" #this is another terragrunt module
}
```

I am generating some common variables that I want to have available in every module.

```terraform
generate "common_variables" {
  path      = "_common_variables.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
  variable "aws_region" {
    description = "AWS region to create infrastructure in"
    type        = string
  }
  variable "environment" {
    type = string
  }
  variable "namespace" {
    type = string
  }
EOF
}
```

`the_called_module` is complaining because is not able to find any variable defined in the `_common_variables.tf` file. If I look into the `.terragrunt-cache`folder I can see that no terrargunt related file is created. It looks like terragrunt thinks that the imported module is a regular terraform module.

Any advice?

Regards!

**Comment by yorinasub17** [comment]
This isn't a supported mode of terragrunt (calling terragrunt from terraform). This isn't really possible either, as the whole point of terragrunt is to break out the state files where terraform can not (all state goes into one place for terraform modules).

The canonical way to interop between terragrunt modules is to use `dependency` blocks. See [the docs on it](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules) for more details.

**Comment by Quaiks** [comment]
I have a `sqs-module` with all mi default values and alarms that I want to reuse in other modules. I have to apply the `sqs-module` and import it as a dependency?

**Comment by yorinasub17** [comment]
Sorry for the delay in responding here. To answer the question, terragrunt doesn't support the feature that you want, which is to inject reusable terraform modules into terraform. You will need to create wrapper terraform modules to achieve what you want, and use standard terraform module reuse.

Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
