### ISSUE TITLE
Record public IP address also

### ISSUE THREAD

**Issue by antonbabenko** [gruntwork-io/terragrunt#13]
Terragrunt writes private IP address into DynamoDB lock table, while CloudTrail shows public IP address in "Source IP address".

I think it would be great to store public IP also in lock table. (I don't have a clear use case for this now, but it may potentially simplify debug when we can see same kind of IP in both places. Especially when `terragrunt show-lock` is ready).

Feature request ? :)

**Comment by brikis98** [comment]
Hm, the code that figures out your IP is here: https://github.com/gruntwork-io/terragrunt/blob/master/locks/lock_metadata.go#L40. It just loops through all network interfaces and picks the first reasonable looking one. I suppose that if you're behind a router, that'll always be a private IP, so to get the public one, we'd have to consult some external service...

**Comment by antonbabenko** [comment]
I think there can be configurable option inside `dynamoDbLock` section to log public or private IP. Yes, consulting external service may not always be a good idea.

**Comment by antonbabenko** [comment]
Found _a hidden gem_ by AWS: `wget -q -O - ‘checkip.amazonaws.com’`. Not sure about official SLA for it, but it can be a more reliable alternative to other similar services.

**Comment by brikis98** [comment]
Since Terraform now natively supports locking, Terragrunt no longer does locking. Closing this issue.
