### ISSUE TITLE
read_terragrunt_config doesn't respect relative paths

### ISSUE THREAD

**Issue by dudicoco** [gruntwork-io/terragrunt#1301]
I have a dependency defined as follows:

```
dependency "eks-cluster" {
  config_path = "../../../devops/eks-ocean/eks-cluster"

  skip_outputs = true
}
```

When reading the dependency with `read_terragrunt_config`, the config path is relative to the file with the dependency block. I would expect it to be relative to the file reading the config.

**Comment by yorinasub17** [comment]
This can go either way as far as understandability goes. I find it more intuitive that everything is relative to the file and not the calling context. I also understand that it might feel more intuitive if it was based on the original source dir. I also had folks ask if it can always be relative to the working dir. In this case, we chose to implement it this way as it is more intuitive if the logic is self contained in the config (you should be able to understand exactly what happens just by looking at the single config file).

---

Side note: there is a major bug with using dependencies in `read_terragrunt_config` and it is currently not recommended to do this. See https://github.com/gruntwork-io/terragrunt/issues/1128

**Comment by dudicoco** [comment]
Thanks @yorinasub17. Maybe it's best to specify that it's currently not recommended to use in the docs?

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!

Side note: we now have `dependency` sharing with deep merge in `include`, which should be a working alternative for this use case. That has support for the different `include` related functions, which should make it easier to build the relative paths.
