### ISSUE TITLE
S3 backend doesn't work for Minio

### ISSUE THREAD

**Issue by stephenliberty** [gruntwork-io/terragrunt#1304]
As title says, it doesn't seem that the S3 remote backend works for Minio. If I just use regular ol' terraform, it works just fine, but terragrunt seems to force itself to talk to the AWS services regardless of what I enable/disable/etc. Right now, my config is..

```hcl
remote_state {
  backend = "s3"
  disable_init = false
  config = {
    access_key="<access key>"
    secret_key="<secret key>"
    endpoint = format("http://%s.<minio url>/", get_env("BOX_NAME"))
    key = replace(path_relative_to_include(), "/", "_")
    bucket = "terraform-state"
    region = "main"
    skip_requesting_account_id = true
    skip_credentials_validation = true
    skip_get_ec2_platforms = true
    skip_metadata_api_check = true
    skip_region_validation = true
    disable_aws_client_checksums = true
    skip_bucket_ssencryption = true
    skip_bucket_accesslogging = true
    skip_bucket_root_access = true
    force_path_style = true
  }
}
```

Output is (after terragrunt inits everything else):

```
2020/08/20 21:07:23 [DEBUG] [aws-sdk-go] 
[terragrunt] [/project/path] 2020/08/20 21:07:23 Initializing remote state for the s3 backend
[terragrunt] [/project/path] 2020/08/20 21:07:23 WARNING: encryption is not enabled on the S3 remote state bucket terraform-state. Terraform state files may contain secrets, so we STRONGLY recommend enabling encryption!
[terragrunt] [/project/path] 2020/08/20 21:07:23 [terragrunt] [/project/path]  Remote state S3 bucket terraform-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
```

Perhaps I'm just missing something? Terragrunt version 25.37.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!

**Comment by lazzurs** [comment]
I can confirm for anyone looking at this closed issue that terragrunt does currently work with minio with the following options.

```
remote_state {
  backend = "s3"

  config = {
    encrypt                            = false
    endpoint                           = "https://s3.domain.com"
    bucket                             = "terragrunt-state"
    key                                = "${path_relative_to_include()}/terraform.tfstate"
    region                             = "eu-west-1"
    disable_aws_client_checksums       = true
    skip_bucket_ssencryption           = true
    skip_bucket_public_access_blocking = true
    skip_bucket_enforced_tls           = true
    skip_bucket_root_access            = true
    skip_credentials_validation        = true
    force_path_style                   = true
  }
}
```

**Comment by adwiza** [comment]
I have found workaround
`locals {
  terraform_state_key = replace("${path_relative_to_include()}/terraform.tfstate", "./", "")
}

inputs = {
  terraform_state_key = local.terraform_state_key
}

generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
    backend "s3" {
        bucket  = "terragrunt"
        endpoints = { s3 = "http://192.168.1.1:9000" }
        access_key = ""
        secret_key = "j"  
        key = "${local.terraform_state_key}"
        region  = "us-east-1"
        encrypt = false
        skip_credentials_validation  = true
        skip_requesting_account_id   = true
        skip_metadata_api_check      = true
        skip_region_validation       = true
        use_path_style               = true
    }
}
EOF
}`

**Comment by 13567436138** [comment]
can not work with minio
how to solve

**Comment by GeoffreyStemys** [comment]
I confirm that the terragrunt block `backend "s3"` does not work to target `minio`, but I manged to make it work by templatting the terraform  `backend.tf` via terragrunt with:
```hcl
generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
  backend "s3" {
    bucket = "terraform"
    key    = "terraform.tfstate"
    region = "eu-central-1"
    endpoints = {
      s3 = "${get_env("minio_url")}"
    }
    access_key = "${get_env("minio_admin_username")}"
    secret_key = "${get_env("minio_admin_password")}"
    encrypt                     = false
    use_path_style              = true
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
  }
}
EOF
}
```
