### ISSUE TITLE
Improve documentation regarding mono-repo terraform and terragrunt scripts/config

### ISSUE THREAD

**Issue by Zyntogz** [gruntwork-io/terragrunt#1309]
Hey folks,

i recently discovered terragrunt and what should i say: it has simply gorgeous functionalities. I wished i knew from its existence long ago so all these awkward improvised terraform wrapper script to roll out to different environments/regions would have been avoided. So many thanks for that!

During the read-through of the docs one major question rose: Why not have one repo containing the terragrunt config structures (live repo in your docs) and the terraform scripts (module repo in your docs)? When you have an adequate project structure (terraform and terragrunt folder on the same file system hierarchy level) it seems totally reasonable. Using git clone and specifying a local path as source in the respective terragrunt configs one could even leverage branching possibilities (as far as i know when specifying a git repo as source terragrunt is only able to check out specific tags). Am I missing something here? Are my thoughts legit? Are there advantages/disadvantages i don't see? 

I think other people could ask themselves these questions too. If there would be a doc explaining these specific design choices (for example you did so with monorepo vs polyrepo regarding modules: https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example) newer terragrunt users could get up&running faster with better design decisions.

Many thanks and I appreciate your work!

**Comment by yorinasub17** [comment]
I think it's important to clarify that everything is about trade offs, and we've recommended a set of options based on our opinions about what trade offs to optimize for.

In our case, we were optimizing for stability and understandability over absolute speed of delivery. Immutable tags allow you to keep a lot of things stable, while having separate repos with different version tags allows you to track what version of the infra code is deployed at any given point in time.

Keeping that in mind:

> When you push something into the live repo, how to make your CI/CD pipeline run no unnecessary tests? For example, if you changed something in your dev environment, why redeploy everything? Or is it always "just deploy everything, it will make unnecessary stuff but that doesn't harm anyone"?

The canonical way to handle this is to implement scripts that can detect which modules changed, and only invoking the pipeline for those modules. You can leverage some combination of `git diff`, `grep`, and `find` to identify terragrunt modules and act accordingly.

> Regarding your terraform module repo, whenever you push something into the master there, i think the CI/CD stuff shall go off and test/deploy your stuff to the dev environment right? But to do so, it would have to check out your live repo and modify respective terragrunt config sources of changed modules right? If that's true and if i'm not missing something, that seems like a lot of effort. Furthermore, when deploying new modules I understood that you have to push your module first, let the CI/CD do unnecessary stuff and afterwards push your live config so the module gets actually deployed, right?

You wouldn't want to do this everytime you merge to `master`, but rather every time you cut a release. The CI pipeline is different for `modules` and `live` config. In particular, getting into the habit of "unit testing" your modules to ensure they work can catch a lot of bugs before you go in and updating a live environment.

Internally at Gruntwork, our CI pipeline for `master` on the modules repo runs a suite of [terratest tests](terratest.gruntwork.io) to make sure the modules are working as expected in isolation. Then, when we feel that the modules are in a state that can be deployed to an actual environment, we cut a release tag to indicate that it can be deployed to an existing environment.

At this point, you can decide what to do. For example, you can have a script that automatically bumps the tag and deploys it for `dev`, and then have [renovatebot](https://renovate.whitesourcesoftware.com/) setup to open PRs to autobump each environment to that module version each time you cut a release. The advantage of this is that you can choose to merge that `stage` PR after confirming it works for `dev`. Or you can decide you want more control over releases (e.g., avoiding an infrastructure failure while your app team is running tests on the dev env) and opt for PRs for all the environments.

> Now here comes the question: During a deployment, what could be a "good practice" to access the application code repo while having terraform code in a different repo? Clone it via terragrunt with a before_hook or something like that? Or shall, like i did it before, the terraform code and the application code be in the same repo?

I would recommend a process in the application repo to push immutable versioned packages of your serverless application to AWS, and reference those tags in the terraform code. This could be as simple as building the zip file and pushing to s3, to as complex as creating a [SAR](https://aws.amazon.com/serverless/serverlessrepo/). This is similar to what you would do for Docker or Packer apps, where the app repo builds a container image / AMI and publishes that.

In this model, terraform/terragrunt doesn't need to touch the application repo during the deploy process, and instead have everything handled in the cloud.

Just to complete the picture, to do CD to a dev environment here, you would have the build process for the app repo clone the infra live repo and commit a change to the tag in the live config that manages the serverless app.

**Comment by Zyntogz** [comment]
Many thanks for your reply. I think you was a great help! The many parts start assembling into a whole picture and everything is becoming much clearer to me.  I definitely will apply these techniques while using terragrunt :)
