### ISSUE TITLE
Log which AWS call fails during bucket creation

### ISSUE THREAD

**Issue by cah-andrew-fitzgerald** [gruntwork-io/terragrunt#1312]
I missed the docs on terragrunt and AWS permissions ([link](https://terragrunt.gruntwork.io/docs/features/aws-auth/#aws-credentials)) and was working off the terraform docs instead ([link](https://www.terraform.io/docs/backends/types/s3.html)) which have a reduced set of permissions.

While trying to execute `terragrunt init`, I received this error:
```
[terragrunt] [<build-dir>] 2020/08/24 05:12:20 Initializing remote state for the s3 backend
[terragrunt] 2020/08/24 05:12:20 AccessDenied: Access Denied
	status code: 403, request id: <request-id>, host id: <host-id>
```
It took me quite a while to figure out that the issue was missing `s3:GetBucketVersioning`.

It would be nice if the error message explicitly mentioned the request that failed or gave some other hint.

**Comment by brikis98** [comment]
Ah, yea, AWS error messages leave much to be desired. We'll need to add some extra decoration when we catch those errors to make it clearer what was happening. A PR to improve this is very welcome!

**Comment by stayman** [comment]
Is there anywhere in the docs with a list of required IAM permissions?

**Comment by cah-andrew-fitzgerald** [comment]
>Is there anywhere in the docs with a list of required IAM permissions?

terragrunt permissions: https://terragrunt.gruntwork.io/docs/features/aws-auth/
terraform permissions: https://www.terraform.io/docs/backends/types/s3.html#s3-bucket-permissions

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.9
