### ISSUE TITLE
Inconsistent resolution of path in `sops_decrypt_file`

### ISSUE THREAD

**Issue by lukiffer** [gruntwork-io/terragrunt#1319]
Given the following block, when running `terragrunt apply` in the module directory the path resolves correctly and works, however running a `terragrunt apply-all` from the root directory fails:

```hcl
locals {
  example = yamldecode(sops_decrypt_file("${path_relative_from_include()}/../../example/secrets.yaml"))
}
```

The resulting error when running `terragrunt apply-all`:

> `Call to function "sops_decrypt_file" failed: Failed to read "../../../../../../example/secrets.yaml": open ../../../../../../example/secrets.yaml: no such file or directory.`

If I replace `sops_decrypt_file(...)` with a simple `file(...)` the apply works (albeit with encrypted values). There appears to be inconsistent resolution of the path between these two functions and/or an inconsistency between the former's implementation in `apply` and `apply-all`.

**Comment by lukiffer** [comment]
After a bit more debugging, it appears that `sops_decrypt_file(...)` expects a path relative to `$PWD` rather than relative to the location of the `terragrunt.hcl`. This isn't expected – especially given the behaviour of `file(...)`, and isn't documented.

Happy to contribute a documentation update if this is the intended behaviour, but I don't have the bandwidth to do a PR for changes to the functionality and corresponding tests. 😢 

As a workaround, instead of using `path_relative_from_include()` I'm using a path relative of `get_parent_terragrunt_dir()` which isn't ideal in all scenarios, but works for this specific case.

**Comment by bartelemi** [comment]
Could we give some love to this issue? It is also causing problems when referencing a module that uses `sops_decrypt_file` as a dependency. A workaround I found is to wrap a call to this function with a `try` statement:
```hcl
locals {
    secrets = try(yamldecode(sops_decrypt_file("secrets.enc.yaml")), {})
}
```

**Comment by Eji4h** [comment]
> Could we give some love to this issue? It is also causing problems when referencing a module that uses `sops_decrypt_file` as a dependency. A workaround I found is to wrap a call to this function with a `try` statement:
> 
> ```terraform
> locals {
>     secrets = try(yamldecode(sops_decrypt_file("secrets.enc.yaml")), {})
> }
> ```

Your solution `try` function always gets a fallback value `{}`.

My solution:
```terraform
locals {
  secrets  = yamldecode(sops_decrypt_file("${get_terragrunt_dir()}/secrets.enc.yaml"))
}
```

**Comment by thnee** [comment]
Also ran into this issue, when trying to use `sops_decrypt_file` with `path_relative_from_include` in an "intermediate" terragrunt include.
It works as expected with `file`, but not with `sops_decrypt_file`.

It would make sense to change `sops_decrypt_file` to accept the same type of path as `file`.
But this would probably be a breaking change.

However, IMO, it seems like bad practice to rely on relative paths in this kind of case.
Using absolute paths should be preferred when pointing to a file.
Relative paths should only be used when generating dynamic configuration, like defining path to tfstate in backend.

It seems like `get_terragrunt_dir` will be acceptable in my case, as it renders an absolute path.

But I have to say, sometimes it can be pretty difficult to understand the purpose of all the various Terragrunt path functions, and which one is correct/appropriate in different cases. The examples in the documentation are very simplistic, compared to the real world projects where Terragrunt actually is relevant.
