### ISSUE TITLE
DRY-promote-immutable-versioned-terraform-modules-across-environments local paths

### ISSUE THREAD

**Issue by alankis** [gruntwork-io/terragrunt#1324]
According to the [documentation](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#promote-immutable-versioned-terraform-modules-across-environments), the splitting environment should be pretty straightforward. However, for various reasons, all my modules are within the local paths and I am not able to reference those as versioned modules. 

Is the above concept even possible with modules on local paths? Use case and explanation bellow. 

The current structure of the project looks like this: 

```
├── config
│   ├── common.tfvars
│   └── terragrunt.hcl
├── environments
│   └── dev
├── infrastructure-modules
│   └── ecs
├── terraform-modules
│   ├── terraform-aws-ecr
```

All my infrastructure is described in `infrastructure-modules/ecs/*.tf` files, which are basically just instantiating child modules declared in `terraform-modules/terraform-aws-*/`.

With that, I can simply execute the terragrunt (terraform commands) from the `infrastructure-modules/ecs` directory. 

To have a possibility to create the same environment in another account, I have introduced a new directory `environments/dev/eu-central-1/ecs` as shown on tree output from the root directory.

The `environments/dev/eu-central-1/ecs`, consists just of two files, *terragrunt.hcl* and *common.tfvars*. 

I guess, that the usage of the *common.tfvars* is quite self-explanatory, where my *terragrunt.hcl* consists of `remote_state {}` and `terraform {}` blocks.  

The important part of the terragrunt configuration file: 

```
remote_state {}

terraform {
  source = "../../../../infrastructure-modules/ecs"

  {...}
}
```

Above I am basically referencing my root modules, declared in `infrastructure-modules/ecs/*.tf`. Where my root modules are instantiating child-modules declared in `terraform-modules/terraform-aws-*/`. 

Child modules from `infrastructure-modules/ecs/*.tf` are instantianed like this: 

```
module my_module {
  source = "../../terraform-modules/terraform-aws-*"

  {...}
}
```

In an ideal world, I would be able to execute terragrunt (terraform) commands from `environments/dev/eu-central-1/ecs` directory, but as I am using local (relative) paths, this is failing during the *initialization* of the modules, as the root module **my_module** loads the child module with following relative path: 

```
module my_module {
  source = "../../terraform-modules/terraform-aws-*"

  {...}
}
```
This is causing a module instantiation in `environments/dev/eu-central-1/ecs` to fail as the relative path is different, based on parent module instantiation. 

```
Initializing modules...
- my_module in 

Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../terraform-modules: no such
file or directory
```

So far, according to the documentation, `path_relative_*`, should be able to return the relative path between the path specified in its include block and the current terragrunt.hcl, but the problem here is that I am not having any `include {}` block(s) within my `terragrunt.hcl` files and thus this approach doesn't works. Symlinks are the last option.

**Comment by brikis98** [comment]
As mentioned in several places in the Terragrunt docs ([example](https://terragrunt.gruntwork.io/docs/features/keep-your-terraform-code-dry/)), you need a double-slash in your `source` URLs in `terragrunt.hcl`:

```hcl
terraform {
  source = "../../../../infrastructure-modules//ecs"

  {...}
}
```

This will allow relative paths to work correctly.

**Comment by alankis** [comment]
Hi, @brikis98 Yes, I agree, this was a typo, but still, I am facing the same issue. Maybe it would be a good idea to put some more details. 

So when I want to execute 'terragrunt init' on path `/environments/dev/eu-central-1/ecs`, where I am having only `terragrunt.hcl` and `common.tfvars`, I see that Terragrunt downloaded all the sourced templates in `.terragrunt-cache`. 

`terragrunt.hcl` looks like this: 

```
remote_state {
 {...}
}

terraform {
  source = "../../../../infrastructure-modules//ecs"
  {...}
}

Where the actual content of the `/infrastructure-modules/ecs` is root Terraform modules which are instantiating child modules defined in `terraform-modules`. 

For example, one of the root modules is being called `ecr-repos.tf`, which is instantiating a child module like this: 

```
module ecr_module {
  source = "../../terraform-modules/terraform-aws-ecr"

  {<MODULE_ARGUMENTS>}
}
```

Guess I am missing a `terragrunt.hcl` in root of the `infrastructure-modules/ecs' which would define to fetch the local modules and copy them into local `.terragrunt-cache`. I will check this and update the issue. Maybe it helps someone.

**Comment by brikis98** [comment]
Relative paths only work for things within the "repo" you identify via the double-slash. So if you have `infrastructure-modules//xxx`, then relative paths for anything in `infrastructure-modules` to any other module in `infrastructure-modules` will work fine. However, if you have a relative path to some folder outside of `infrastructure-modules`—which is what I assume `terraform-modules` is?—then those paths won't work.

So then you have two options:

1. Move the double-slash. E.g., if both `infrastructure-modules` and `terraform-modules` have a common parent folder—e.g., `/foo/bar/infrastructure-modules` and `/foo/bar/terraform-modules`—then put the double-slash after `/foo/bar`: e.g., `/foo/bar//infrastructure-modules/xxx`.
1. Refactor your modules to all be in one folder.

**Comment by alankis** [comment]
@brikis98 Now I understand. I was able to refactor the structure and achieve the desired behavior. I am closing the issue.
