### ISSUE TITLE
How to have one local value defined in one module available in another module

### ISSUE THREAD

**Issue by shubhamnegi1** [gruntwork-io/terragrunt#1328]
I am having some name which I am using in A module, I want to refer same variable in module B. All i have is terragrunt.hcl file written in each module.
I am using dependency for all oter outputs from module A. but this var is not available as a output. What is the best way to get this var from module A.

**Comment by brikis98** [comment]
There are a number of ways to do this, including:

1. Add it as an output to module A.
1. Store the variable in a `.tfvars` file and include it in both `terragrunt.hcl` files using [`extra_arguments`](https://terragrunt.gruntwork.io/docs/features/keep-your-cli-flags-dry/).
1. Store the variable in a `.hcl` file and have both `terragrunt.hcl` files read it in using [`read_terragrunt_config`](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_terragrunt_config) and pass it to `inputs`.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
