### ISSUE TITLE
Terraform extra_arguments are not being honored. 

### ISSUE THREAD

**Issue by beanderson** [gruntwork-io/terragrunt#133]
I am using the extra_arguments resource in a terraform config block that is also specifying a remote source:

```
terragrunt = {
  include = {
    path = "${find_in_parent_folders()}"
  }
  terraform = {
    extra_arguments "variables" {
      arguments = [
        "-var-file=terraform.tfvars",
        "-var-file=variables.tfvars"
      ]
      commands = [
        "apply",
        "plan",
        "import",
        "push",
        "refresh"
      ]
    }
    source = "git::ssh://git@privategitserver.git//http-redirect?ref=${get_env("TF_VAR_http_redirect_version", "master")}"
  }
}
```

variables.tfvars has the required variables to successfully bring up the resource. I can do a `terragrunt apply -var-file=variables.tfvars` and things work as expected, but when I do just a `terragrunt apply` with the above configuration, it asks for the vars the resource is expecting. 

I'm using terragrunt 0.10.1 and terraform 0.8.6

**Comment by brikis98** [comment]
Extra arguments was added in [0.10.2](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.10.2), which *just* came out!

**Comment by beanderson** [comment]
Oh perfect, I just realized I was reading the master version of the readme and realized it wasn't out in 0.10.1
