### ISSUE TITLE
Question: Allow variables for Terragrunt in remote_state

### ISSUE THREAD

**Issue by wesleywh** [gruntwork-io/terragrunt#1336]
Is this even possible for me to do?
```
export AWS_PROFILE=non_prod; terragrunt init -var region=us-west-2 -var profile=non_prod
```
terragrunt.hcl
```
locals {
  account_type = "nonprod"
}
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket  = "xva-${local.account_type}-terraform-uw2"
    
    key     = "${path_relative_to_include()}/terraform.tfstate"
    region  = var.region
    profile = var.profile
    acl     = "private"
    encrypt = true
  }
}
```
It simply doesn't like variables in `remote_state`.

How can I make this a universal, modifiable hcl file if I have to hard code variables? Do I have to hard code variables now or is there another way to actually supply variables here?

and yes there is a different bucket for each region and account for the backend.

**Comment by yorinasub17** [comment]
Terragrunt doesn't support variables, but there is a workaround using environment variables and [get_env](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_env).

**Comment by wesleywh** [comment]
Alright, that's good to know. I have started down the route of just separating out my config files in separate directories per environment.

**Comment by jf** [comment]
if I could just ask: how difficult is it to get terragrunt to support being able to use variables in remote_state?
