### ISSUE TITLE
Terragrunt 0.24.1 dependency block bug

### ISSUE THREAD

**Issue by bubalush** [gruntwork-io/terragrunt#1338]
I have `dependency` block to fetch subnets from output but got the following error:
```
[terragrunt] 2020/09/11 17:27:49 Could not parse output from terragrunt config /network/vpc/terragrunt.hcl. Underlying error: invalid primitive type name "list"
```
**All works well with 0.23.34**

**Comment by yorinasub17** [comment]
Thanks for reporting the issue. It's a bit hard to tell what might be going on without seeing your `terragrunt.hcl` config. Would you be able to share it?

Also, I suspect this is an incompatibility between what you are doing in your terragrunt config and the new shallow dependency fetching optimization. Does it work if you annotate the `remote_state` block with `disable_dependency_optimization = true`?

**Comment by bubalush** [comment]
`disable_dependency_optimization = true` block helps. I close the issue.
