### ISSUE TITLE
`apply-all` should error if TERRAGRUNT_SOURCE is specified

### ISSUE THREAD

**Issue by yinzara** [gruntwork-io/terragrunt#1339]
I caused a MAJOR production outage across a set of tenants because I accidentally had the TERRAGRUNT_SOURCE environment variable set when I performed an "apply-all" across our tenants.  This caused more than 800 resources across 6 customers to be deleted because TG attempt to apply the source from TERRAGRUNT_SOURCE against a set of terragrunt.hcl files that were for different modules.

TERRAGRUNT_SOURCE is incompatible with `apply-all` unless all modules being applied are for the same source.  `apply-all` should have prevented this from happening either by erroring or prompting me to confirm specifically about TERRAGRUNT_SOURCE.

**Comment by brikis98** [comment]
Sorry to hear you hit this issue. That sounds really painful 😕 

FWIW, we use `TERRAGRUNT_SOURCE` quite regularly with `apply-all`, especially when spinning up totally new environments. That said, there are a number of limitations / gotchas with `TERRAGRUNT_SOURCE`, and we've captured a proposal for a better replacement in #1138. Let's continue the discussion in there. I'll close this issue for now.
