### ISSUE TITLE
Dependency to terraform resouce

### ISSUE THREAD

**Issue by arik-porat** [gruntwork-io/terragrunt#1340]
Hi,
How can I create a dependency to a resource that is created with a terraform?
for example 

resource "aws_s3_bucket" "athena-query-result" {
  bucket = "aws-athena-query-results-123456789012-${var.aws_region}"
}

I would like create a dependency on this in different module
inputs = {
  name = "test"
  bucket  =  aws_s3_bucket.athena-query-result.arn
...
}

**Comment by brikis98** [comment]
This has been asked many times and is covered in the docs. See [`dependency` blocks](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules) and [`terraform_remote_state`](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) for two possible approaches.
