### ISSUE TITLE
heavy use of sops_decrypt + dependencies causes massive slowdown

### ISSUE THREAD

**Issue by abeluck** [gruntwork-io/terragrunt#1343]
I was ecstatic when I saw the `sops_decrypt` function in terragrunt. Many thanks for this feature! We use sops heavily and are in the process of migrating a big an unwieldy terraform setup to terragrunt.

Our use of sops is mostly with PGP keys on smartcards. Each decrypt operation takes 2-3 seconds, sometimes 3-4. 

We are now seeing that `terragrunt apply`s take a very long time just due to the `sops_decrypt` calls, particularly with dependency trees where each layer uses sops.  In most cases our layers are decrypting the same set of files over and over. 

Would it be possible to add an in memory cache of the output of `sops_decrypt(file)` for the duration of the terragrunt execution?

FWIW, the new ansible sops plugin [does exactly this](https://github.com/ansible-collections/community.sops/blob/main/plugins/vars/sops.py#L89-91).

**Comment by brikis98** [comment]
That's a good idea. An in-memory cache of (absolute path of file -> decrypted contents) sounds straightforward and would definitely make things faster. Would you be up for a PR  to add this?

**Comment by abeluck** [comment]
My go fu is pretty much non-existent, :sob:  N

Looking [at the source though](https://github.com/gruntwork-io/terragrunt/blob/master/config/config_helpers.go#L527), it seems like storing the result of `decrypt.File` in some sort of global hashmap would work? Not sure how globals are handled in go. Or perhaps better, is there a memoize feature in the standard library?

**Comment by brikis98** [comment]
A global `map` would probably be the way to go. Any variable declared outside of a function is essentially a global.

**Comment by abeluck** [comment]
PR added :) it is definitely a speed improvement.

**Comment by brikis98** [comment]
Thanks!
