### ISSUE TITLE
configure terragrunt

### ISSUE THREAD

**Issue by payamzowghi** [gruntwork-io/terragrunt#135]
Hi Guys,

please help me to configure this part:
Install Terraform, and let Terragrunt know where to find it using one of the following options:

Place terraform in a directory on your PATH.

Caution: this makes it easy to accidentally invoke Terraform directly from the command line (thus bypassing the protections offered by Terragrunt).

Specify the full path to the Terraform binary in the environment variable TERRAGRUNT_TFPATH.

Specify the full path to the Terraform binary in --terragrunt-tfpath each time you run Terragrunt (see CLI Options).

Install Terragrunt by going to the Releases Page, downloading the binary for your OS, renaming it to terragrunt, and adding it to your PATH.

**Comment by brikis98** [comment]
Which of those options are you trying to do?

**Comment by payamzowghi** [comment]
Option 2.I'd like to know all of them,if possible.I added terragrunt file to /usr/bin directory.is it correct?

**Comment by brikis98** [comment]
`PATH` is an [environment variable](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps) that contains a list of paths where the OS will look for executables. When you type in a command like `grep` or `terraform`, the OS will loop through the list of paths in `PATH` and call the first executable in those paths that matches your command (or exit with an error if a match can't be found).

`/usr/bin` and `/usr/local/bin` are part of the default `PATH` on many operating systems, so putting the Terragrunt and Terraform binaries in one of those will work. Alternatively, you could put them in a new folder (e.g. `/foo/bar/terraform`) and add that folder to `PATH`:

```
export PATH=/foo/bar:$PATH
```

The code above prepends `/foo/bar` to the previous value of `PATH`. Note that if you just run the command above, it only affects your current shell. If you want to set an environment variable that's available in every shell you open, see [here](http://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables).

If you want to set the `TERRAGRUNT_TFPATH` variable, you take a similar approach:

```
export TERRAGRUNT_TFPATH=/foo/bar
```

**Comment by payamzowghi** [comment]
thank you man
my os is:Ubuntu(16.04) x86_64
I downloaded this file:terragrunt-0.10.2.tar.gz(Source code (tar.gz))
I added Terragrunt and Terraform binaries to /usr/bin and /usr/local.(and two other methods)
I got this error after ran terragrunt plan:
payamzowghi@ubuntu:~/Downloads/terraform_0.8.6/chapter3$ terragrunt plan
bash: /usr/bin/terragrunt: cannot execute binary file: Exec format error
 
then I downloaded the other files(terragrunt_linux_386 or terragrunt_linux_amd64).they aren't binary.

I don't know what is the problem :(

**Comment by brikis98** [comment]
> I downloaded this file:terragrunt-0.10.2.tar.gz(Source code (tar.gz))

Why did you download the source code? You want the binary. For example, for your OS, you want `terragrunt_linux_amd64`.

**Comment by payamzowghi** [comment]
I downloaded this file and changed the name to terragrunt and copy in /usr/bin
payamzowghi@ubuntu:~/Downloads/terraform_0.8.6/chapter3$ ls /usr/bin | grep terra
terraform
terragrunt

but it didn't work as the command. It seems that it is not the binary :(
I'm confused.

**Comment by brikis98** [comment]
You need to give it execute permissions too.

```
chmod u+x /usr/bin/terragrunt
chmod u+x /usr/bin/terraform
```

**Comment by payamzowghi** [comment]
thank you it works but it should be:
chmod +x /usr/bin/terragrunt

**Comment by kiran266** [comment]
Hi,

I am getting the below error on my MAC while executing : terragrunt 
/usr/local/bin/terragrunt: cannot execute binary file

I have downloaded terragrunt_linux_amd64 and renamed it to terragrunt and moved to /usr/local/bin

Lastly, executed chmod +x /usr/bin/terragrunt 

But I am still getting error as mentioned above. 

Could someone please suggest ? I am trying to install Terragrunt v0.18.3. thanks in advance for your help.

**Comment by shivamkh90** [comment]
> Hi,
> 
> I am getting the below error on my MAC while executing : terragrunt
> /usr/local/bin/terragrunt: cannot execute binary file
> 
> I have downloaded terragrunt_linux_amd64 and renamed it to terragrunt and moved to /usr/local/bin
> 
> Lastly, executed chmod +x /usr/bin/terragrunt
> 
> But I am still getting error as mentioned above.
> 
> Could someone please suggest ? I am trying to install Terragrunt v0.18.3. thanks in advance for your help.

 @kiran266   Check the kernel version with uname -a. It is Darwin for mac. Please download the file specific to darwin "terragrunt_darwin_amd64" and that should solve your problem
