### ISSUE TITLE
Documentation should be updated to make it suitable  for customers

### ISSUE THREAD

**Issue by tgavaliuk** [gruntwork-io/terragrunt#1350]
https://davidbegin.github.io/terragrunt/index#install-terragrunt
this document as any other should contain each step in details how to setup application , but step 1-2 are clear for developers only and as usual contain steps which are hidden (I don't think this is what you need),
sequence numbers of steps are incorrect everywhere . Relation and integration to terraform is not described. Integration to existing code is not covered.Where are cases when '*.tfvars' files are not in use ?

**Comment by brikis98** [comment]
> https://davidbegin.github.io/terragrunt/index#install-terragrunt

This is not an official Terragrunt website.

Please see https://terragrunt.gruntwork.io/ instead.
