### ISSUE TITLE
Terragrunt S3 backend access issue

### ISSUE THREAD

**Issue by madhuryg** [gruntwork-io/terragrunt#1352]
the terragrunt plan and terragrunt apply command fails with aan issue 
Error loading state: AccessDenied: Access Denied
	status code: 403, request id: somerequestid, host id: someid

Validate Response s3/PutObject failed, attempt 0/5, error AccessDenied: Access Denied for s3
but S3 has access. it is the same error even if it creates a new s3 bucket 
Error: Failed to persist state to backend.

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate

How do i fix it in terragrunt

**Comment by brikis98** [comment]
Terragrunt does not read/write state to your S3 bucket; that's all done by Terraform. This looks like an S3 or permissions issue with how you're configuring your credentials.

**Comment by kwilczynski** [comment]
Hi @madhuryg, it's exactly like @brikis98 said.

Have a look at [S3 Bucket Permissions](https://www.terraform.io/docs/backends/types/s3.html#s3-bucket-permissions) and make sure that your user or the role you are assuming has access to the S3 bucket you are using to store remote state.

**Comment by madhuryg** [comment]
> Hi @madhuryg, it's exactly like @brikis98 said.
> 
> Have a look at [S3 Bucket Permissions](https://www.terraform.io/docs/backends/types/s3.html#s3-bucket-permissions) and make sure that your user or the role you are assuming has access to the S3 bucket you are using to store remote state.

**Comment by madhuryg** [comment]
No it is not s3 issue as sane code same access I was able to execute earlier ... it is stuck on the error.tfstate file .. I am unable to find it .

**Comment by kwilczynski** [comment]
Hi @madhuryg,

OK. Which version of Terragrunt and Terraform do you have?

Also, can you verify using something like the AWSCLI that you can list, upload and download from the this particular S3 bucket?

**Comment by yorinasub17** [comment]
Just wanted to chime in to mention that this can also happen when your STS token expires, if you are using assumed role or temporary credentials.

**Comment by madhuryg** [comment]
aws s3 cp ~/sample.txt s3://mgdev-terraform-backend-dev-qsixl-us-east-1 --sse aws:kms
upload: ..\..\..\..\..\..\sample.txt to s3://mgdev-terraform-backend-dev-qsixl-us-east-1/sample.txt

this works. so it is not s3 issue
but i think it is taking the wrong kms key

**Comment by madhuryg** [comment]
i am sorry i am giving the wrong key ..... thank you so much

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
