### ISSUE TITLE
Multiple terragrunt requests.., how to destroy 

### ISSUE THREAD

**Issue by madhuryg** [gruntwork-io/terragrunt#1355]
Hey I have terragrunt code to create 3 buckets and give the name in the hcl file as a parameter. I change it and run it again. How does the code recignuze which bucket to destroy ???

**Comment by yorinasub17** [comment]
I am not exactly sure what the desired behavior is from the question, but this is a basic feature of terraform in how it tracks state.

Read [our blog post](https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa) on terraform state for more info.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
