### ISSUE TITLE
Allow templates to be shared

### ISSUE THREAD

**Issue by dhoer** [gruntwork-io/terragrunt#136]
When switching from terraform to terragrunt, I can't share a template file across modules.  Is there a way to do this?

It seems there needs to be a way to include the template(s) along with the module.  

One proposal to do this is to allow multiple sources of directories or files, e.g.
```hcl
  terraform {
    source = ["../../../../templates", "../../../../modules/mymodule"]
  }
```
or

```hcl
  terraform {
    source = ["../../../../templates/user_data.sh", "../../../../modules/mymodule"]
  }
```

**Comment by dhoer** [comment]
Another possible solution could be to add a templates param that would allow for one or more template sources to be declared, e.g.
```hcl
terraform {
    templates = "../../../../templates", 
    source = "../../../../modules/mymodule"
}
```

**Comment by brikis98** [comment]
> When switching from terraform to terragrunt, I can't share a template file across modules. Is there a way to do this?

I'm not sure what you mean by this? Could you give an example?

**Comment by dhoer** [comment]
We have multiple modules that include the same template to keep it DRY. 
```
/modules
  /moduleA
  /moduleB
/templates
  /user_data.sh
```
We used relative paths to include the templates in the modules:
```hcl
resource "template_file" "instance_user_data" {
  template = "${file("../../templates/user_data.sh")}"

  vars {
    ...
  }
}
```
This worked fine in terraform, but when switching to terragrunt, the module are copied and ran from a temp directory breaking the relative path relationship. 

I don't know how to share the template in terragrunt.  I have copied the user_data.sh file to each module for now.  If there was a mechanism to copy templates to the same temp directory as the modules, then templates could be shared across multiple modules.

**Comment by brikis98** [comment]
Ah, just use a double-slash.

```hcl
terragrunt = {
  terraform {
    source = "../../../..//modules/mymodule"
  }
}
```

Terragrunt will copy the entire folder before the double slash, so the `templates` folder will be in the same relative path.

**Comment by dhoer** [comment]
Nice!  Thanks for the tip!

**Comment by shapi78** [comment]
Hi, This works great when you have plain text file. I need to generate user_data with variables per module, while some modules use the same user_data rendering, with different variables. I couldn't make it work
