### ISSUE TITLE
terragrunt generate: Hit multiple errors: exit status 127

### ISSUE THREAD

**Issue by AnthonyWC** [gruntwork-io/terragrunt#1375]
I want to use a single `terragrunt.hcl` to generate both provider.tf and backend.tf but when I run terragrunt generate, I get error which appears to come from `terraform generate`, I think because it isn't a command in terraform anymore:

```
terraform generate --help 
Usage: terraform [-version] [-help] <command> [args]
```

```
terraform --version                                                              
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/aws v3.8.0

terragrunt --version
terragrunt version v0.25.1
```

However terragrunt generate will still work but that doesn't mean I need to ignore error if i want to use terragrunt generate to generate those files, which isn't ideal.

**Comment by AnthonyWC** [comment]
The workaround is just run `terragrunt init` which will generate those files but without the errors.  The generate command should be depreciated or removed altogether.

**Comment by lorengordon** [comment]
There is no `terragrunt generate` command, is there? Not seeing anything in the docs anyway. Pretty sure that is _only_ an option in the config, not a cli command... https://terragrunt.gruntwork.io/docs/reference/cli-options/#cli-commands

**Comment by AnthonyWC** [comment]
Right, I thought that used to be one.
