### ISSUE TITLE
How to get terragrunt directory name ?

### ISSUE THREAD

**Issue by rgarrigue** [gruntwork-io/terragrunt#1378]
Hi there

I've been reading the doc, I fail to see how I can get the terragrunt.hcl directory name only, meaning not the path ? 

I'ld like to use it to fill in some metadata, most of the time my service name equals to the directory name where it's defined.

Thanks,

**Comment by lorengordon** [comment]
Did you try the `dirname()` function? https://www.terraform.io/docs/configuration/functions/dirname.html

**Comment by rgarrigue** [comment]
Tried this, without success

```
inputs = {
  service = "${dirname(get_terragrunt_dir())}"
}
```

**Comment by lorengordon** [comment]
I suppose I'm not following what you are looking for. Maybe provide enough of an example of what you want, including an expected result?

**Comment by rgarrigue** [comment]
I've a lot of directories named `my_service_test`, `my_service_that`, `my_service_this`, etc. With just one file, `terragrunt.hcl`.  calling a module with just one input

```
inputs = {
  service = "my_service_test"
}
```

Having a `get_directory_name()` function (or equivalent) like this 

```
inputs = {
  service = "${get_directory_name()}"
}
```

Would save time for me, and be less error prone when I c/c this a dozen of time to create a bunch of new things. Of course I could develop a new module to loop over a list of services, but that's not the way I want to do it atm.

**Comment by lorengordon** [comment]
ah. did you try the terraform function `basename()`? https://www.terraform.io/docs/configuration/functions/basename.html

```
> basename("foo/bar/baz")
baz
``

**Comment by rgarrigue** [comment]
Indeed, `"${basename(get_terragrunt_dir())}"` works. Thanks !
