### ISSUE TITLE
tflint support

### ISSUE THREAD

**Issue by kulmam92** [gruntwork-io/terragrunt#1379]
I'm having trouble integrating TFLint with Terragrunt.

I tried to add using before_hook. However, it seems like Terragrunt's inputs are not passed to TFLint.
```
  before_hook "before_hook" {
    commands = ["validate"]
    execute  = ["tflint", "--module", "."]
  }
```
I found a good suggestion from TFLint's issue history. Would it be possible to implement this?

[Terragrunt support #119](https://github.com/terraform-linters/tflint/issues/119)

> Terragrunt is focused on reducing Terraform boilerplate by generating root modules at runtime and then calling through to terraform by invoking its CLI. It provides constructs for generating repetitive root configuration (providers, backends) as well as module calls. Terragrunt's mode of operation (exec-ing terraform) is dissimilar from TFLint, which relies on Terraform's libraries for loading and parsing configuration and not the Terraform CLI.
> 
> Child modules
> You can run TFLint on your child modules. Anything you're putting in terraform.source in your Terragrunt config should be something TFLint can evaluate.
> 
> Root modules
> At the moment, the only option seems to be to use hooks to run TFLint before or after Terraform commands. You could invoke TFLint before plan and apply and/or after validate.
> 
> However, you'd find that TFLint is not able to evaluate Terragrunt's inputs and thus enabling --modules is less useful than expected. The map of inputs is written to a JSON file and passed to relevant Terraform via --var-file. Terragrunt can also generate arbitrary Terraform arguments for certain commands, allowing you to pass additional --var-file flags (or -var).
> 
> Terragrunt could add support for invoking binaries other than Terraform, perhaps something like exec and exec-all. This would help support any Terraform static analysis tool. TFLint, by using -var-file and -var flags to match Terraform, seems to be doing everything it can to be interoperable.
> 
> Since there's no clear action for TFLint to take here, I'm going to go ahead and close this issue. If Terragrunt users want to contribute docs that's welcome, otherwise at least this issue is searchable for anyone wondering. If Terragrunt does pursue invoking commands other than terraform, then I can definitely see documenting a recommended setup.

**Comment by kulmam92** [comment]
- Inputs in the terragrunt.hcl file are exposed as environment variables when you call TFLint using before/after hook.
- You may have terragrunt output inputs to "terragrunt-debug.tfvars.json" using --terragrunt-debug flag like below. That file can be provided to TFLint using --var-file flag.
`$ terragrunt apply --terragrunt-debug`

**Comment by babilen5** [comment]
@kulmam92 Could you be so kind to elaborate on how you integrate `tflint` into terragrunt exactly, using `--terragrunt-debug` ? I would love to integrate tflint runs into a CI pipeline.

Based on your comment above, you utilise hooks and have TFLint read inputs from environment variables?

**Comment by Andrew-Wichmann** [comment]
@babilen5 I believe he is saying you can to it two ways

- You can maybe write a small script as a hook to place those environment variables into a var file then call `tflint --var-file=<that_new_file>`
- or, you could run `terragrunt apply --terragrunt-debug` then `tflint --var-file=terragrunt-debug.tfvars.json`

**Comment by alikhil** [comment]
@kulmam92 Did you succeed to run tflint as a hook? I would appreciate if you will share your findings

**Comment by stefan-sesser** [comment]
I had the same issue and created an after_hook inline script:
`  after_hook "validate_tflint" {
    commands = ["validate"]
    execute = [
      "sh", "-c", <<EOT
        echo "Run tflint for project '${path_relative_to_include()}'..."
        (cd "$project" && tflint --config="${path_relative_from_include()}/.tflint.hcl" --loglevel=warn -f default)
        error_code=$?
        echo "Run tflint for project '${path_relative_to_include()}'...DONE\n"
        exit $error_code
      EOT
    ]
  }`
Just be sure to add the `.tflint.hcl` file at the root project dir or remove the argument.

`terragrunt run-all validate` will do the linting afterwards

**Comment by stefan-sesser** [comment]
> > @alikhil I had the same issue and created an after_hook inline script:
> > ```
> >   after_hook "validate_tflint" {
> >     commands = ["validate"]
> >     execute = [
> >       "sh", "-c", <<EOT
> >         echo "Run tflint for project '${path_relative_to_include()}'..."
> >         (cd "$project" && tflint --config="${path_relative_from_include()}/.tflint.hcl" --loglevel=warn -f default)
> >         error_code=$?
> >         echo "Run tflint for project '${path_relative_to_include()}'...DONE\n"
> >         exit $error_code
> >       EOT
> >     ]
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Just be sure to add the `.tflint.hcl` file at the root project dir or remove the argument.
> > `terragrunt run-all validate` will do the linting afterwards
> 
> @stefan-sesser could you explain me the $project variable? what is that to be set to? also, does the after_hook need to be configured in every module, or can it be configured at the root level somehow?
> 
> Many thanks

This is just a leftover from a previous itteration which i forgot to delete. you can safely delete the `cd "$project"` part.
Regarding the configuration: Just put it in your root terragrunt.hcl file. The validation will take place on each module recognized by terragrunt.

Cheers Stefan

**Comment by duynhepi** [comment]
> > > @alikhil I had the same issue and created an after_hook inline script:
> > > ```
> > >   after_hook "validate_tflint" {
> > >     commands = ["validate"]
> > >     execute = [
> > >       "sh", "-c", <<EOT
> > >         echo "Run tflint for project '${path_relative_to_include()}'..."
> > >         (cd "$project" && tflint --config="${path_relative_from_include()}/.tflint.hcl" --loglevel=warn -f default)
> > >         error_code=$?
> > >         echo "Run tflint for project '${path_relative_to_include()}'...DONE\n"
> > >         exit $error_code
> > >       EOT
> > >     ]
> > >   }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Just be sure to add the `.tflint.hcl` file at the root project dir or remove the argument.
> > > `terragrunt run-all validate` will do the linting afterwards
> > 
> > 
> > @stefan-sesser could you explain me the $project variable? what is that to be set to? also, does the after_hook need to be configured in every module, or can it be configured at the root level somehow?
> > Many thanks
> 
> This is just a leftover from a previous attemp to solve the problem which I forgot to delete. You can safely delete the `cd "$project"` part. Regarding the configuration: Just put it in your root terragrunt.hcl file. The validation will take place on each module recognized by terragrunt.
> 
> I already updated the hook script.
> 
> Cheers Stefan

Hi, thanks for the suggestion. It worked nicely.

However, in my tests, it only work if I configure the child terragrunt file and put .tflint.hcl under the same child folder. When I put the configuration in the root terragrunt, it will return an error saying the .tflint.hcl is not found.

Also, during my successful lint, terragrunt still returns an error saying ```Errors encountered running before_hooks. Not running 'terraform'```

Any ideas?

**Comment by ioancatana** [comment]
> > > > @alikhil I had the same issue and created an after_hook inline script:
> > > > ```
> > > >   after_hook "validate_tflint" {
> > > >     commands = ["validate"]
> > > >     execute = [
> > > >       "sh", "-c", <<EOT
> > > >         echo "Run tflint for project '${path_relative_to_include()}'..."
> > > >         (cd "$project" && tflint --config="${path_relative_from_include()}/.tflint.hcl" --loglevel=warn -f default)
> > > >         error_code=$?
> > > >         echo "Run tflint for project '${path_relative_to_include()}'...DONE\n"
> > > >         exit $error_code
> > > >       EOT
> > > >     ]
> > > >   }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Just be sure to add the `.tflint.hcl` file at the root project dir or remove the argument.
> > > > `terragrunt run-all validate` will do the linting afterwards
> > > 
> > > 
> > > @stefan-sesser could you explain me the $project variable? what is that to be set to? also, does the after_hook need to be configured in every module, or can it be configured at the root level somehow?
> > > Many thanks
> > 
> > 
> > This is just a leftover from a previous attemp to solve the problem which I forgot to delete. You can safely delete the `cd "$project"` part. Regarding the configuration: Just put it in your root terragrunt.hcl file. The validation will take place on each module recognized by terragrunt.
> > I already updated the hook script.
> > Cheers Stefan
> 
> Hi, thanks for the suggestion. It worked nicely.
> 
> However, in my tests, it only work if I configure the child terragrunt file and put .tflint.hcl under the same child folder. When I put the configuration in the root terragrunt, it will return an error saying the .tflint.hcl is not found, eventhough it searches the correct path.
> 
> Also, during my successful lint, terragrunt still returns an error saying `Errors encountered running before_hooks. Not running 'terraform'`
> 
> Any ideas?

I have the same issue, and I don't find anything in their docs.
