### ISSUE TITLE
Retryable errors: make default list extendable

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/terragrunt#1383]
As mentioned in [this comment](https://github.com/gruntwork-io/terragrunt/pull/1232/files#r444285628), we should expose a helper function that returns the default retryable errors, so that the configurable list of retryable errors can be extended rather than replaced.

**Comment by autodeck** [comment]
Is there any ETA for this please?

**Comment by infraredgirl** [comment]
> Is there any ETA for this please?

Hi Rich, we (Gruntwork) are not currently working on this as we're super busy with other things on our roadmap. However, if you'd like to try and contribute a PR to add this feature, I'll be more than happy to provide reviews/help/guideance.

**Comment by levkohimins** [comment]
Resolved in [v0.51.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.51.4) release.
