### ISSUE TITLE
Rename the gostructToCty function in config_as_cty.go

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/terragrunt#1384]
As per [this comment](https://github.com/gruntwork-io/terragrunt/pull/1232/files#r444288437) the [`gostructToCty`](https://github.com/gruntwork-io/terragrunt/blob/master/config/config_as_cty.go#L184) function has a misleading name, because it works not only for structs but also for other data types, such as arrays. It should be renamed to better reflect its true use.

**Comment by VishalCR7** [comment]
@infraredgirl  Hi! I would like to work on this (eventually others later) Can you please assign it to me ?

**Comment by infraredgirl** [comment]
> @infraredgirl Hi! I would like to work on this (eventually others later) Can you please assign it to me ?

Thanks, Vishal! I just assigned the issue to you.
