### ISSUE TITLE
Ignore dependencies outputs while perfoming destroy-all command

### ISSUE THREAD

**Issue by mordowiciel** [gruntwork-io/terragrunt#1385]
I have an environment consisting of 3 modules, each containing some number of submodules:

    environment/
        moduleA/
            A1/
                 terragrunt.hcl
            A2/
                 terragrunt.hcl
        moduleB/
           B1/
               terragrunt.hcl
           B2/
               terragrunt.hcl
           B3/
               terragrunt.hcl
        moduleC/
            C1/
                terragrunt.hcl
            C2/
                terragrunt.hcl

Each of this submodules declare its outputs, which then can be used in another modules, for example in moduleC1:

    dependency "moduleC1" {
      config_path = "../C1"
    }

    dependency "moduleA1" {
      config_path = "../../moduleA/A1"
    }

    dependency "moduleB3" {
      config_path = "../../moduleB/B3"
    }

Now let's consider theoretical situation, in which I perform`terragrunt apply-all` in the `environment/ `directory and the deployment of modules B3 and C1 fails, for example because of unproper configuration which was provided.

Then, I'd like to delete whole environment to "remove the trash" left after unsuccessfull deployment. I would like to run `terragrunt destroy-all` in the `/environment` directory again, expecting that the remaining leftovers would be successfully deleted.

Unfortunately that's not the case, because then I'm receiving errors showing that the outputs of modules B3 and C1 could not be resolved.

I know that I can add skip_outputs manually to the depedencies in moduleC1 just for the sake of performing this destroy, but that seems quite a brittle solution for me. I've also tried using `--terragrunt-ignore-dependency-errors` and `--terragrunt-ignore-external-dependencies`, but that didn't solve the case. The `--terragrunt-ignore-external-dependencies` helped resolving the errors only in external dependencies (i.e moduleA1 and B3 in this example case), but the outputs error of module C1 still remains.

Is there any possibility to skip outputs of modules described in dependency block only during certain Terraform commands, in my case, the destroy?

**Comment by yorinasub17** [comment]
I believe you can use [the mock outputs feature](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#unapplied-dependency-and-mock-outputs) with `destroy` in the `mock_outputs_allowed_terraform_commands` for this.

**Comment by mordowiciel** [comment]
That solves my problem, thanks!
