### ISSUE TITLE
Terraform "live repo" version constraints vs. Terragrunt single-version support

### ISSUE THREAD

**Issue by tillig** [gruntwork-io/terragrunt#1387]
I'm following the [live repo example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example) and the _Terraform Up and Running_ book, trying to make sure things are stable and 1:1 with what's deployed. So far, so good.

However, I'm having trouble rectifying a couple of things that seem to conflict and I'm hoping you might be able to shed some light on how you handle it:

- Individual modules ([like the `mysql` example](https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/blob/2fd692d1afdb2305226ddc6ba90a272e6dec083a/mysql/main.tf#L12)) pin _exact_ versions of Terraform to ensure the backend contents don't change.
- The live repo [has multiple modules across different repos](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/tree/master/prod/us-east-1/prod) which can potentially diverge on Terraform version on a per-module basis.
- Terragrunt only supports one Terraform version at a time _but_
- Once you specify [dependencies across modules](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules), you can potentially end up with multiple Terraform versions required to fulfill the dependencies.

This leads me to think that my options are:

- Don't specify the Terraform version in the modules - instead, specify in the Terragrunt repo and control it centrally.
- If there are dependencies across modules all of those need to be updated roughly simultaneously to stay on the same version of Terraform all the time.
- Specify Terraform version _ranges_ in individual modules rather than _exact versions_.

If I ever _wanted_ to do `terragrunt plan-all` or any of those commands I'd have to make sure the whole live repo is at the same Terraform version. We don't really use the `*-all` commands, but they won't work with all the disparate versions in one repo anyway.

I'm not entirely sure the precise pros and cons of these since I'm not sure how often or how breaking the backend changes really are across Terraform versions. I'm guessing the "right" answer is to keep specifying exact versions and make sure all modules that are dependent all end up on the same Terraform version... but I figured I'd ask to see if there's an option I'm missing.

**Comment by brikis98** [comment]
As always, the answer is, "it depends"... That said, the most common approach we use nowadays is:

> * Don't specify the Terraform version in the modules - instead, specify in the Terragrunt repo and control it centrally.

We do this by using a [`generate` block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate) to create the `terraform { ... }` block and version config (typically in a root `terragrunt.hcl`). We then try to update all modules to the new version at once.

Of course, sometimes, this doesn't work. E.g., Sometimes, a new version of Terraform is backwards incompatible, and you don't have time to upgrade all your modules everywhere all at once. In those cases, you have to override the version on a module-by-module basis (typically, in a child `terragrunt.hcl`). This does cause problems with cross-module dependencies, so you're often forced to upgrade the "roots" of your dependency tree right away (i.e., the modules everyone depends on, such as the VPC), but can afford to be a bit slower on the "leaves."

**Comment by tillig** [comment]
This is very helpful! Thank you! I'll see about trying this approach. It'll be nice when the version of Terraform is more about features and less about potential backwards incompatibility.
