### ISSUE TITLE
Dynamic `generate` block

### ISSUE THREAD

**Issue by s1mark** [gruntwork-io/terragrunt#1388]
Dear Gruntwork,

First of all let me thank you for providing `terragrunt` with its ton of useful features. Keep it up!

Hashicorp have introduced the `for_each` functionality for modules with the release of terraform 0.13 . However they still lack to solve the dynamic provider issue which is still causing pain where multiple provider declarations are necessary. Hashicorp is not planning to work on this feature until they release v1.0 https://github.com/hashicorp/terraform/issues/24476#issuecomment-700368878

I was wondering if `terragrunt` could help us by somehow extending the `generate` functionality. At the moment I use the `generate` block in the following way https://github.com/hashicorp/terraform/issues/24476#issuecomment-619450972
Would it be possible to somehow templatize the `generate` functionality and generate the code in an iterative way?
For example:

```hcl
generate "modules" {
  path      = "modules.tf"
  if_exists = "overwrite"
  for_each  = {
    "module01" = {
      ...
    }
    "module02" = {
      ...
    }
  }
  contents = <<EOF
module each.key {
  source    = "./modules/my_module"
  providers = {
    azurerm = "azurerm.${each.key}"
  }
}
EOF
} 
```

**Comment by s1mark** [comment]
I see that the https://github.com/gruntwork-io/terragrunt/pull/853 issue is in correlation. Still the above described situation is a missing feature on both `terraform` and `terragrunt`

**Comment by lorengordon** [comment]
@s1mark have you tried using the string template syntax in your heredoc? it supports for loops. you could maybe set a local with the values, then loop over it in a string template, in the generate block. https://www.terraform.io/docs/configuration/expressions.html#directives

**Comment by s1mark** [comment]
Thank you for the great tip @lorengordon 
I have managed to solve the problem in the following way
https://github.com/hashicorp/terraform/issues/24476#issuecomment-709571582
