### ISSUE TITLE
Can only deploy when pointing to the subfolders level. When trying to deploy from parent folder it fails.

### ISSUE THREAD

**Issue by Felipewdc** [gruntwork-io/terragrunt#1389]
Hi,

We have our deployments going through Azure Devops and leveraging Terragrunt to keep our code dry. If I point my deployments to each folder named after the server it works just fine. 

If I try and point to the folder named Application then the deployment does not work. The whole issue seems to stem from the ${path_relative_to_include()} in the terragrunt.hcl file is not getting populated.  So the workspace name ends with a dash and since it is not a supported ending value, it crashes. 

What am I missing so that I can just run terragrunt against the Application folder instead of having to run it folder by folder?

- Application
  terragrunt.hcl
    - Server1
           main.tf
           terragrunt.hcl
    - Server2
           main.tf
           terragrunt.hcl
  
Error:
[terragrunt] [/azp/agent/_work/4/s/CompanyName/Prod/Test] 2020/10/13 18:39:45 Running command: terraform init
Initializing the backend...
Error loading state: Error creating workspace Azure-companyname-Prod-trtest-.: invalid attribute

This is part of the terragrunt.hcl file in the application folder:
generate "backend" {
  path = "backend.tf"
  if_exists = "overwrite"
  contents = <<EOF
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "CompanyName"
    workspaces {
      name = "Azure-companyname-${local.subscription}-${local.application}-${path_relative_to_include()}"
    }
  }
}

EOF
}

**Comment by brikis98** [comment]
What command are you running in the `Application` folder? What else is in `Application/terragrunt.hcl`? What's in `Server1/terragrunt.hcl`? Also, to make the code easier to use, would you mind using a [fenced code block](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks)?

**Comment by Felipewdc** [comment]
Hi Yevgeniy,

We are running our applies out of Azure Devops and the commands that would be run against the applications folder would be the following:
        export TOKEN=$(token)
        terragrunt init
        terragrunt apply -auto-approve

This is the content of the terragrunt.hcl file in the application folder, with some stuff redacted. 

locals {
  # Automatically load environment-level variables
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl", "./env.hcl"))

  # Extract out common variables for reuse
  application = local.environment_vars.locals.application
  subscription = local.environment_vars.locals.subscription

  token = get_env("token")
}


generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite"
  contents = <<EOF
provider "azurerm" {
  features {}
  version         = "=2.9.0"
  tenant_id = "<Tenant ID>"
  subscription_id = "<Subscription ID>"
}
EOF
}

generate "backend" {
  path = "backend.tf"
  if_exists = "overwrite"
  contents = <<EOF
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "<Organization Name>"
    workspaces {
      name = "Azure-<Organization Name>-${local.subscription}-${local.application}-${terraform.workspace}"
    }
  }
}

EOF
}

generate "script" {
  path = "localexec.sh"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
curl --request PATCH --header "Content-Type: application/vnd.api+json" --header "Authorization: Bearer ${local.token}" --data '{"data":{"attributes":{"operations":false}}}' --url https://app.terraform.io/api/v2/organizations/<Oragnization Name>/workspaces/Azure-<Organization Name>-${local.subscription}-${local.application}-${path_relative_to_include()}
EOF
}

terraform {

  before_hook "before_hook" {
    commands     = ["apply", "plan"]
    execute      = ["bash", "localexec.sh"]
  }
}

inputs = merge(
  local.environment_vars.locals,
)


This is the content of the Terragrunt.hcl file in the Server Folders:
include {
  path = find_in_parent_folders()
}

We do not mind using a fenced code block if that is what you recommend. 

Thank you for jumping in and answering questions! Also, thank you for writing Terraform up and running, GREAT book. I have learned a lot from it.

**Comment by brikis98** [comment]
What I meant was, please use a fenced code block in your comments here on GitHub! I can't read the code snippet above, as it's being interpreted as Markdown instead! Wrap it in triple back ticks and label it as `hcl` please.

**Comment by Felipewdc** [comment]
Sorry about that. Hopefully this does the trick. 

This is the terragrunt.hcl in the application folder. 

```
locals {
  # Automatically load environment-level variables
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl", "./env.hcl"))

  # Extract out common variables for reuse
  application         = local.environment_vars.locals.application
  appowner            = local.environment_vars.locals.appowner

  token = get_env("<token>")
}


generate "provider" {
  path = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
provider "vsphere" {
  user           = "<vsphere user>"
  password       = <vsphere creds>
  vsphere_server = "<vsphere server>"
  #version = "1.17"
  allow_unverified_ssl = true
}
EOF
}

generate "backend" {
  path = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "<org name>"
    workspaces {
      name = "vsphere-<org name>-${path_relative_to_include()}"
    }
  }
}
EOF
}

generate "script" {
  path = "localexec.sh"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
curl --request PATCH "https://app.terraform.io/api/v2/organizations/<org name>/workspaces/vsphere-<org name>-${path_relative_to_include()}" --header "Content-Type: application/vnd.api+json" --header "Authorization: Bearer ${local.token}" --data '{"data":{"attributes":{"operations":false}}}'
EOF
}

terraform {

  before_hook "before_hook" {
    commands     = ["apply", "plan"]
    execute      = ["bash", "localexec.sh"]
  }
}

inputs = merge(
  local.environment_vars.locals,
)
```

This is the terragrunt.hcl in the Server folders. 

```
include {
  path = find_in_parent_folders()
}
```

**Comment by brikis98** [comment]
OK, so when running in the `Application` folder, you're executing `terragrunt apply`? If so, that will not work. If your goal is to apply both the child modules (the `Server` modules), what you need is `apply-all`. See: https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/

**Comment by Felipewdc** [comment]
Thanks again for your help!

So, I had tried that before and just tried it again. I get the same error I have been getting all along when I try and do that. 

The calculation I am using to create the name of the workspace name up on Terraform Enterprise is not getting the folder name and therefore ends with a dash and therefore it crashes.  

This is the error:
Error loading state: Error creating workspace vsphere-<Org Name Redacted>-.: invalid attribute

The terraform plan still spits out the plan but then errors out. with the message above. 

The odd thing is the script I am running in that same terragrunt.hcl using the same exact variable ${path_relative_to_include()} does calculate out the folder names properly. 

```
generate "script" {
  path = "localexec.sh"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
curl --request PATCH "https://app.terraform.io/api/v2/organizations/<org name>/workspaces/vsphere-<org name>-${path_relative_to_include()}" --header "Content-Type: application/vnd.api+json" --header "Authorization: Bearer ${local.token}" --data '{"data":{"attributes":{"operations":false}}}'
EOF
}
```

**Comment by brikis98** [comment]
Hm, that's very weird.

Did you actually try looking at the generated `backend.tf` and `localexec.sh`?

**Comment by Felipewdc** [comment]
Hi,

Thanks again for helping out. It is much appreciated. 

Looking at the backend.tf file that gets generated has a period at the end of the workspace name. The Patch command also has the . at the end of the name. 

It looks like it is not passing that variable down to those files that are created. 

We are using Azure Devops for the deployment and storing our states on Terraform Enterprise Cloud. 

Please let me know what else I can provide to assist in tracking this down. 

```
# Generated by Terragrunt. Sig: <Random character redacted>
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "<Orgname redacted>"
    workspaces {
      name = "vsphere-<orgname redacted>-."
    }
  }
}
```

This is the local.sh

```
# Generated by Terragrunt. Sig: <Random character redacted>
curl --request PATCH "https://app.terraform.io/api/v2/organizations/<orgname redacted>/workspaces/vsphere-<orgname redacted>-." --header "Content-Type: application/vnd.api+json" --header "Authorization: Bearer ***" --data '{"data":{"attributes":{"operations":false}}}'
```

**Comment by brikis98** [comment]
Hm, I'm not able to reproduce. I tried to create a minimal repro as follows:

In `/tmp/parent/terragrunt.hcl`:

```hcl
generate "backend" {
  path = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents = <<EOF
# terraform {
#   backend "remote" {
#     hostname = "app.terraform.io"
#     organization = "<org name>"
#     workspaces {
#       name = "vsphere-<org name>-${path_relative_to_include()}"
#     }
#   }
# }
EOF
}
```

This should generate a `backend.tf` and make use of `path_relative_to_include`. Note that the generated file will generate commented out code; that's just to make the test cycle faster, so I don't have to deal with backends/auth. That said, it should still show if `path_relative_to_include` works or not.

Then, in `/tmp/parent/child/terragrunt.hcl`:

```hcl
include {
  path = find_in_parent_folders()
}
```

And also, just to have something to deploy, in `/tmp/parent/child/main.tf`:

```hcl
output "foo" {
  value = "foo"
}
```

Whether I run `terragrunt apply` in `/tmp/parent/child` or `terragrunt apply-all` in `/tmp/parent`, I get the same `backend.tf` file generated:

```hcl
# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# terraform {
#   backend "remote" {
#     hostname = "app.terraform.io"
#     organization = "<org name>"
#     workspaces {
#       name = "vsphere-<org name>-child"
#     }
#   }
# }
```

Note how `child` is filled in.

Does the above work for you? Is there something different in your code?

**Comment by brikis98** [comment]
No response in a few months, so closing.
