### ISSUE TITLE
Expected syntax of the form '${function_name()}', but got '${var.environment}' - What?

### ISSUE THREAD

**Issue by notjames** [gruntwork-io/terragrunt#139]
terragrunt 0.10.2

The error specified doesn't make sense in the context of the `terraform.tfvars` file being used:

```
## AWS stuff.
region            = ""
company           = "company"
profile           = "default"
azones            = []

## Environment stuff
project-name      = "project"
ssh_key_name      = ""

## VPC stuff
vpc-cidr          = "172.16.0.0/16"
vpc-name          = ""
vpc-id            = ""

## Subnets
public-cidrs      = ["172.16.2.0/26", "172.16.3.0/26", "172.16.1.0/26"]
public-subnets    = []

private-cidrs     = ["172.16.108.0/22", "172.16.104.0/22", "172.16.100.0/22"]
private-subnets   = []

## DNS
tl_domain_name    = "company.com."

## bootstrap stuff
bstrap_glbal_args = ""

## terragrunt stuffs
terragrunt        = {
                      # Configure Terragrunt to use DynamoDB for locking
                      lock
                      {
                        backend = "dynamodb"
                        config
                        {
                          state_file_id = "project-terragrunt"
                          aws_profile   = "default"
                          table_name    = "terragrunt_locks"
                        }
                      }

                      # Configure Terragrunt to automatically store tfstate files in an S3 bucket
                      remote_state
                      {
                        backend = "s3"
                        config
                        {
                          encrypt = "true"
                          bucket  = "project-terraform-terragrunt"
                          key     = "terraform.tfstate"
                          region  = "us-east-1"
                        }
                      }
                    }
```

So far, I've whittled the issue down to something in my variables, but I'm not yet sure what. If I remove all of the other variables leaving the terragrunt variable alone, I don't get this error:

```
$ TERRAGRUNT_DEBUG=true terragrunt get -update=true
[terragrunt] 2017/02/20 12:32:11 Reading Terragrunt config file at /home/user/company-projects/github/aws/project/terraform/base/test/terraform.tfvars
Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${var.environment}'
[terragrunt] 2017/02/20 12:32:11 config.InvalidInterpolationSyntax Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${var.environment}'
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config_helpers.go:45 (0x4f8728)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config_helpers.go:29 (0x4f9c54)
/usr/local/go/src/regexp/regexp.go:486 (0x4c3d1a)
/usr/local/go/src/regexp/regexp.go:523 (0x4bd406)
/usr/local/go/src/regexp/regexp.go:487 (0x4bd142)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config_helpers.go:34 (0x4f85c9)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config.go:195 (0x4f7677)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config.go:185 (0x4f73f6)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/config/config.go:170 (0x4f72c7)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:130 (0x479e25)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:123 (0x479d5f)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:485 (0x4e47e4)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:259 (0x4e25ff)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/main.go:21 (0x401097)
/usr/local/go/src/runtime/proc.go:183 (0x42b844)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x459ec1)
```

**Comment by brikis98** [comment]
I just copy and pasted your exact `terraform.tfvars` file into an empty folder on my computer, added an empty `main.tf`, and ran `terragrunt get`. I did not get the error you're indicating.

Am I missing something else? Do you happen to have the `TERRAGRUNT_CONFIG` environment variable set and pointing to some *other* `.tfvars` file?

**Comment by notjames** [comment]
I have no other TF or TG env variables set. I don't think you're missing anything else, but let me double check.

**Comment by notjames** [comment]
OK. I've double-checked my env and there's nothing for TF or TG in my env nor do I or have I ever used such env variables. 

I just ran it again and I'm getting the *exact* same outcome. Usually I run a wrapper script to execute terraform. I refactored the script to use terragrunt. I ran terragrunt outside of the wrapper script and the same error occurred.

Unfortunately, the error doesn't say *where* the issue is occurring; just what's occurring. Short of sending you my entire configuration, this seems like looking for a needle in a haystack in email.

**Comment by brikis98** [comment]
Can you try the repro steps I listed:

1. Copy your `.tfvars` file into a totally empty folder.
1. Put an empty `main.tf` in that folder.
1. Run `terragrunt get`.

**Comment by notjames** [comment]
Sorry this took so long...

```
$ cp *tfvars /var/tmp/tgtest/
$ cd /var/tmp/tgtest/
$ touch main.tf
$ terragrunt get
[terragrunt] 2017/03/01 14:54:39 Reading Terragrunt config file at /var/tmp/tgtest/terraform.tfvars
Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${var.environment}'
[terragrunt] 2017/03/01 14:54:39 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${var.environment}'
```

**Comment by brikis98** [comment]
> cp *tfvars /var/tmp/tgtest/

Can you do an `ls` to show what files got copied and `cat` to show their exact contents?

Also, can you paste the output of `terragrunt --version` just to be extra sure? I'm sure there is some simple bug, but if I can't repro it, I can't fix it :(

**Comment by notjames** [comment]
sure!

```
$ cd /var/tmp/tgtest/
$ ls -ltr
total 4
-rw-rw-r-- 1 me me 1804 Mar  1 14:54 terraform.tfvars
-rw-rw-r-- 1 me me    0 Mar  1 14:54 main.tf
```

terraform.tfvars:

```
## AWS stuff.
region            = ""
company           = "company"
profile           = "default"
azones            = []

## Environment stuff
project-name      = "project"
provisioner-user  = "provisioner"
private-key       = "${var.privkey-path}/${var.privkey-name}"
ssh_key_name      = ""

## VPC stuff
vpc-cidr          = "172.16.0.0/16"
vpc-name          = ""
vpc-id            = ""

## Subnets
public-cidrs      = ["172.16.2.0/26", "172.16.3.0/26", "172.16.1.0/26"]
public-subnets    = []

private-cidrs     = ["172.16.108.0/22", "172.16.104.0/22", "172.16.100.0/22"]
private-subnets   = []

## DNS
tl_domain_name    = "companycloud.com."

## S3 buckets
forge_bucket_name = "project-tf-${var.environment}"

## bootstrap stuff
bstrap_glbal_args = ""

## terragrunt stuffs
terragrunt        = {
                      # Configure Terragrunt to use DynamoDB for locking
                      lock
                      {
                        backend = "dynamodb"
                        config
                        {
                          state_file_id = "project-terragrunt"
                          aws_profile   = "default"
                          table_name    = "terragrunt_locks"
                        }
                      }

                      # Configure Terragrunt to automatically store tfstate files in an S3 bucket
                      remote_state
                      {
                        backend = "s3"
                        config
                        {
                          encrypt = "true"
                          bucket  = "project-terraform-terragrunt"
                          key     = "terraform.tfstate"
                          region  = "us-west-2"
                        }
                      }
                    }
```

**Comment by brikis98** [comment]
The `terraform.tfvars` file in your most recent comment is not the same one in the original bug. I'm going to assume the extra dollar signs at the end of the line are a copy/paste issue and not actually part of the file and instead point you to this:

```
private-key       = "${var.privkey-path}/${var.privkey-name}"
project_bucket_name = "project-tf-${var.environment}"
```

The second one is what happens to be causing the error, but both are problematic:

1. `.tfvars` files don't allow interpolation, so this won't work. This has nothing to do with Terragrunt, it's just how Terraform treats `.tfvars` files.
1. For some reason, Terragrunt is trying to process interpolations inside of the entire file rather than just the `terragrunt = { ... }` block. This is definitely a bug and should be fixed.

**Comment by notjames** [comment]
Glad we nailed down the issue!! Thanks for keeping up on it. Apologies for the files not being same between the first paste and the last one. I've been working on our environment so changes happen.

The '$' signs in the output above are from that `cat -A` command (shown in the example) to show that there are no carriage returns in the file that could potentially cause odd issues with commands that read config files.

I'm not sure what causes you to think that TF can't interpolate variables in the tfvars file because the implementation as I currently use works as expected interpolating the variables as desired. One reason this may work is because of the variables being given at runtime as `-var` arguments to TF.

**Comment by brikis98** [comment]
> I'm not sure what causes you to think that TF can't interpolate variables in the tfvars file because the implementation as I currently use works as expected interpolating the variables as desired. One reason this may work is because of the variables being given at runtime as -var arguments to TF.

I'm not sure what you're seeing, but for me, interpolation is completely ignored in `.tfvars` files. 

Example:

**main.tf**

```hcl
variable "foo" {}
variable "bar" {}

output "foo" { value = "${var.foo}" }
output "bar" { value = "${var.bar}" }
```

**terraform.tfvars**

```hcl
foo = "foo"
bar = "${var.foo}"
```

Output from running `terraform apply`:

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

bar = ${var.foo}
foo = foo
```

Same thing if I run `terraform apply -var foo="foo"`.

**Comment by notjames** [comment]
I see. The reason it's "working" for me is because of a module upstream performing the interpolation, which causes my output to work properly.

Thanks @brikis98
