### ISSUE TITLE
Constructing terragrunt cache is extremely slow for local modules

### ISSUE THREAD

**Issue by casparrolfe** [gruntwork-io/terragrunt#1390]
Our project is structured similar to this: https://github.com/tfutils/tfscaffold

For example:

```
├─ components/
│  └─ a-component/
│     └─ main.tf
└─ modules/
│  └─ a-module/
│  │  └─ main.tf
│  └─ b-module/
│     └─ main.tf
└─ config/
   └─ target/
      └─ terragrunt.hcl
```

In `components/a-component/main.tf`
```
module "aws_vpc_cni" {
  source = "../../modules/a-module"
}
```

In `config/target/terragrunt.hcl`
```
terraform {
  source = "../..//components/a-component"
}
```

All works nicely, but we've noticed that the entire project gets copied into the `terragrunt-cache` for local modules, so even though `b-module` is not used by `a-component` it is still copied into the cache. For smaller projects this is fine, but as a project grows things can get extremely slow on apply (seems to take minutes while it copies into the cache) and disk usage can quickly grow up to many gigabytes in size.

**Comment by brikis98** [comment]
This is true, but I'm not sure what a good solution would be? Terragrunt copies more than just the module you're using due to the double-slash: e.g., `xxx//components/a-component` tells Terragrunt to copy the entire `xxx` folder so that any relative paths within `a-component` will work correctly. If you don't need relative paths, you can perhaps reduce the amount copied by removing double-slashes, but we don't usually recommend that, as it can lead to confusing errors...

**Comment by casparrolfe** [comment]
Ah, I see what you mean about the relative paths. So if `component-a` uses `module-a` and `module-a` uses `module-b` then there is no guarantee that the path to `module-b` would be correct! Is it possible to calculate the local dependencies and file paths before the cache is copied and rewrite them to work within the cache?

We did have the double slash removed for a while, but it just confuses the IDE amongst other things!

**Comment by brikis98** [comment]
> Is it possible to calculate the local dependencies and file paths before the cache is copied and rewrite them to work within the cache?

I suspect it's quite tricky. It would require parsing all your Terraform code and knowing all the places where a relative path could be. Examples:

- `source` URLs in `module { ... }` blocks. 
- Paths passed to the [`file` function](https://www.terraform.io/docs/configuration/functions/file.html).
- Paths passed to the [`local_file` resource](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file).
- Paths passed to the [`fileset` function](https://www.terraform.io/docs/configuration/functions/fileset.html).
- Paths passed to the [`templatefile` function](https://www.terraform.io/docs/configuration/functions/templatefile.html).
- Paths passed to the [`abspath` function](https://www.terraform.io/docs/configuration/functions/abspath.html).
- Probably a dozen other functions I'm not aware of... Plus all the ones added in the future.
- Paths used with `provider` blocks. 
- Paths used with specific resources (e.g., `aws_s3_object`).
- And so on.

**Comment by nigelgbanks** [comment]
I've had some success in using this to decrease the time as for me, it mostly came from re-downloading the provider plugins for multiple times.
```hcl
terraform {
  before_hook "before_cache" {
    commands     = [get_terraform_command()]
    execute      = ["mkdir", "-p", abspath("${get_parent_terragrunt_dir()}/../build/terraform")]
  }
  extra_arguments "cache" {
    commands = [get_terraform_command()]
    env_vars = {
      TF_PLUGIN_CACHE_DIR = abspath("${get_parent_terragrunt_dir()}/../build/terraform")
    }
  }
}
```

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered, and there isn't anything actionable for terragrunt side. If there are any follow ups, please open a new ticket with updated context. Thanks!
