### ISSUE TITLE
Can destroy-all ignore undeployed-stack related dependency errors while still erroring in other situations? (eg a child stack failed to destroy)

### ISSUE THREAD

**Issue by Makeshift** [gruntwork-io/terragrunt#1394]
When running destroy-all today, I accidentally left some logfiles in an S3 bucket, meaning that the destruction of that stack failed.

I didn't see this error until the end of the run, by which time the stack containing the VPC that the failed stack depended on had been destroyed. 

After emptying the bucket, I then wasn't able to destroy that stack due to dependent stack not being deployed. I had to redeploy my VPC stack in order to delete the failed stack.

I'm aware that `mock_outputs` are a thing (#1385) that I'm now slowly applying to my codebase, but it would be preferable to be able to avoid this situation entirely.

Related: #1230

**Comment by brikis98** [comment]
I'm not sure I follow entirely. Could you explain your dependency graph a bit more? What modules depend on what, and through what mechanisms (e.g., are you using `dependency { ... }` blocks)?

**Comment by Makeshift** [comment]
I put together an [example repo](https://github.com/Makeshift/terragrunt-1394-complete-example) to try and replicate, and then realised what I did - I used the `--terragrunt-ignore-dependency-errors` flag in order to avoid errors for modules that hadn't been deployed, but obviously that also means that errors like this are also ignored:

```
Cannot process module Module /home/connor/WebstormProjects/wsl/terragrunt-1394-complete-example/terragrunt/make-vpc (excluded: false, dependencies: []) because one of its dependencies, Module /home/connor/WebstormProjects/wsl/terragrunt-1394-complete-example/terragrunt/make-bucket (excluded: false, dependencies: [/home/connor/WebstormProjects/wsl/terragrunt-1394-complete-example/terragrunt/make-vpc]), finished with an error: Hit multiple errors:
```

So I suppose I should probably revise my question - Is it possible to do `destroy-all` commands, telling it to ignore issues where dependencies don't exist (due to not being deployed), but still exiting in situations where a dependent failed to destroy?

Here's how to replicate the situation in the issue description, given my [example repo](https://github.com/Makeshift/terragrunt-1394-complete-example):

* deploy `make-bucket` and `make-vpc`, leaving `dont-deploy-this-stack` and `dont-deploy-this-stack-either` undeployed
    * This replicates a common situation I'm in, where I have a mixture of deployed and undeployed stacks in the same folder, due to errors or other means.
* run `terragrunt destroy-all`
   * At this point, destruction will fail early due to one of the `dont-deploy` stacks depending on the other, even though neither are deployed
* run `terragrunt destroy-all --terragrunt-ignore-dependency-errors` (to ignore the dependency error the two `dont-deploy` stacks create)
   * Here, you end up in the horrific place I put myself in, as `make-vpc` gets destroyed, but `make-bucket` does not, and now `make-bucket` can't be destroyed OR deployed without first re-deploying `make-vpc`


Am I over-complicating this? Can this be easily solved with `skip_outputs` or something?

**Comment by brikis98** [comment]
> I put together an [example repo](https://github.com/Makeshift/terragrunt-1394-complete-example) to try and replicate, and then realised what I did - I used the `--terragrunt-ignore-dependency-errors` flag in order to avoid errors for modules that hadn't been deployed, but obviously that also means that errors like this are also ignored:
> 
> ```
> Cannot process module Module /home/connor/WebstormProjects/wsl/terragrunt-1394-complete-example/terragrunt/make-vpc (excluded: false, dependencies: []) because one of its dependencies, Module /home/connor/WebstormProjects/wsl/terragrunt-1394-complete-example/terragrunt/make-bucket (excluded: false, dependencies: [/home/connor/WebstormProjects/wsl/terragrunt-1394-complete-example/terragrunt/make-vpc]), finished with an error: Hit multiple errors:
> ```
> 
> So I suppose I should probably revise my question - Is it possible to do `destroy-all` commands, telling it to ignore issues where dependencies don't exist (due to not being deployed), but still exiting in situations where a dependent failed to destroy?

Oh, I gotcha. I'm of two minds on this. On the one hand, it's not an unreasonable request... But on the other, it's yet another CLI flag, another behavior to document/understand/maintain, etc... Perhaps the better workaround here is if you have modules with known errors, you exclude them? See https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-exclude-dir.

**Comment by Makeshift** [comment]
That's fair - I can totally understand not wanting to clutter everything up with more flags. The only real effect now that I understand what I was doing wrong is that I need to pay more attention to which stacks I haven't deployed.

Thanks for your help. I'll rename the issue to better track the actual request, but feel free to close it if you don't think it needs to be implemented.

**Comment by brikis98** [comment]
Thanks for understanding! I think for now, to avoid too many flags, I'll  close this.
