### ISSUE TITLE
Allow setting undeclared variables in tfvars files, without warnings or errors

### ISSUE THREAD

**Issue by djfinnoy** [gruntwork-io/terragrunt#1395]
Terraform currently throws this warning if you assign a value to an undeclared variable in a `tfvars` file:

```
Warning: Value for undeclared variable

The root module does not declare a variable named "core_workers_disk_size" but
a value was found in file "/path/to/stuff". To use this value, add a "variable" block to the configuration.

Using a variables file to set an undeclared variable is deprecated and will
become an error in a future release. If you wish to provide certain "global"
settings to all configurations in your organization, use TF_VAR_...
environment variables to set these instead.
```

Related: https://github.com/hashicorp/terraform/issues/22004

People are worried Hashicorp will actually go through with this absurd restriction.
It would be neat if Terragrunt is prepared, and allows us to continue setting undeclared variables in variables files; something that I personally find works well with Terragrunt's approach to keeping CLI flags DRY.

Feature request:
- Prevent warnings (and errors) from occuring when setting undeclared variables in a `tfvars` file.

**Comment by brikis98** [comment]
I thought this _was_ already an error with TF 0.13?

Terragrunt already lets you work around it, albeit not via `.tfvars` files, but by defining your variables in `terragrunt.hcl`, or other `.hcl` / `.yml` / `.json` files that you load into Terragrunt and pass via the `inputs = { ... }` block.

**Comment by djfinnoy** [comment]
Hmm. Our desire is to organize input values for different environments in different files, eg. `prod.tfvars`, `dev.tfvars`.
We also want to have a `shared.tfvars` file so we don't have to repeat a bunch of identical input values across both of the aforementioned files.

Terragrunt lets us handle in a neat way:
```
# Directory structure
|-- my-project
    |-- live
        |-- prod
        |-- dev
    |-- settings
        |-- prod
            |-- settings.tfvars
        |-- dev
            |-- settings.tfvars
        |-- shared
            |-- settings.tfvars

# Example: ./live/prod/terragrunt.hcl
terraform {
  extra_arguments "variables" {
    commands = get_terraform_commands_that_need_vars()
    required_var_files = [
       "${get_parent_terragrunt_dir()}/../settings/shared/settings.tfvars",
       "${get_parent_terragrunt_dir()}/../settings/${split("/", path_relative_to_include())[0]}/settings.tfvars"
    ]
  }
}
```
This even lets us overwrite values that are defined in `settings/shared/`, because the other `.tfvars` files take precedence.
Works great, but it produces a bit of `Warning: Value for undeclared variable` spam when there are module differences between the environments.

Are there any alternative ways of accomplishing this within Terragrunt? We're happy with the above, but worried that Terraform will disallow values for undeclared variables in the future.

**Comment by yorinasub17** [comment]
The current recommended way to handle this is to define common variable files as `hcl` files that are then read in using [read_terragrunt_confg](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_terragrunt_config) and merged into the `inputs` map. See https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/master/terragrunt.hcl#L54 for example.

Terragrunt `inputs` avoids this problem by going through environment variables, which currently still works, so by using `read_terragrunt_config` and `merge`, you avoid using `tfvars`. This has the additional benefit of consolidating how variable inputs are passed through to terraform, making the debug experience more consistent (e.g., when [going through the terragrunt debug features](https://terragrunt.gruntwork.io/docs/features/debugging/)).

Also, FYI, the warnings are errors in terraform 13 and above.

**Comment by djfinnoy** [comment]
Excellent, thank you. I'll try out the approach you've described.
