### ISSUE TITLE
Per environment state file

### ISSUE THREAD

**Issue by lsc** [gruntwork-io/terragrunt#14]
It would be really nice if you could use terragrunt with a environment argument, and have it map the argument value to a state file configured. 

Something like `terragrunt -environment=staging plan` and then be able to do something like 
```
remoteState = {
  backend = "s3"
  backendConfigs = {
    encrypt = "true"
    bucket = "my-bucket"
    key = "${environment}.tfstate"
    region = "us-east-1"
  }
}
```

**Comment by brikis98** [comment]
One of the goals for Terragrunt was to make the state management completely declarative for a given folder. That is, you don't have to remember to set any flags or do anything manually, as managing state manually is precisely what leads to mistakes with vanilla Terraform. Having a flag that changes where state is stored seems to bring some of that manual effort back, which would lead to errors.

It's also worth mentioning that when we use Terraform, we keep separate environments in totally separate folders (and therefore, totally separate `tfstate` files). This ensures you have true isolation (you can never change prod while working on stage) and if a `tfstate` file becomes corrupt, it only affects one environment and not all. See [Terraform, VPC, and why you want a tfstate file per env](https://charity.wtf/2016/03/30/terraform-vpc-and-why-you-want-a-tfstate-file-per-env/) for a fun read.

Our typical folder structure looks like this:

```
stage
 └ main.tf
 └ .terragrunt
prod
 └ main.tf
 └ .terragrunt
global
 └ main.tf
 └ .terragrunt
```

That way, the key in each `.terragrunt` file can be hard-coded to the environment you're in, and there is no chance of setting it to the wrong value by accident.

**Comment by lsc** [comment]
That makes a lot of sense, thanks for the input.
