### ISSUE TITLE
before_hook hanging on a certain command (ssh related)

### ISSUE THREAD

**Issue by esn89** [gruntwork-io/terragrunt#1401]
I have a hook which opens up an SSH tunnel before doing any Terragrunt related things:
```
  before_hook "gcloud" {
    commands = ["apply", "plan"]
    execute  = ["gcloud", "beta", "compute", "ssh", "--tunnel-through-iap", "--project=my-test-project", "ssh-jumphost", "--", "-D", "6656", "-N", "-f"]
  }
```

It runs without any problem but it refuses to 'complete' and move on to the plan stage.  Here is the output from when I run `terragrunt plan`

```
[terragrunt] 2020/10/23 19:13:20 Detected 2 Hooks
[terragrunt] 2020/10/23 19:13:20 Executing hook: gcloud
[terragrunt] 2020/10/23 19:13:20 Running command: gcloud beta compute ssh --zone us-central1-a --tunnel-through-iap --project=my-test-project ssh-jumphost -- -D 1080 -N -f
```

From here, after I wait about 2 minutes for something to happen, I have to hit "ctrl-c" to interrupt it and only then, does it continue:

```
^C[terragrunt] 2020/10/23 19:14:12 Forward signal interrupt to terraform.
[terragrunt] 2020/10/23 19:14:12 Error forwarding signal: os: process already finished
Connection to compute.20266247743088432 closed by remote host.
[terragrunt] 2020/10/23 19:14:12 Executing hook: get_cred
```

Any help would be appreciated.

**Comment by yorinasub17** [comment]
This is currently not possible with terragrunt, due to https://github.com/gruntwork-io/terragrunt/issues/856#issuecomment-530091210

**Comment by esn89** [comment]
I see.  Thanks for your reply, @yorinasub17

**Comment by Lillecarl** [comment]
https://gist.github.com/Lillecarl/184e6760ef59d710ff234336ab165f54

Using this to set up an SSH tunnel to reach postgres databases for extension installation and such.
