### ISSUE TITLE
Running Terragrunt init hangs after init is complete. CTRL-C shows terraform process already stopped.

### ISSUE THREAD

**Issue by vsabella** [gruntwork-io/terragrunt#1407]
On Terragrunt 0.25.5 - whenever I run terragrunt init, it completes correctly,

However it hangs and never returns back to the console. If I ctrl-C I get the following message:

```
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
^C[terragrunt] 2020/10/30 11:51:42 Forward signal interrupt to terraform.
[terragrunt] 2020/10/30 11:51:42 Error forwarding signal: os: process already finished

```

It also appears to do this only when I use http git references for module sources - perhaps terragrunt is waiting for the git credential helper to exit?

**Comment by brikis98** [comment]
What happens if you run `git clone` on the exact same Git repo?

**Comment by vsabella** [comment]
It clones - asks for https credentials and clones (we can't use ssh for module sources for this scenario)

I'll hook up a debugger at some point this week and try it outside of docker.

**Comment by brikis98** [comment]
> It clones - asks for https credentials and clones (we can't use ssh for module sources for this scenario)

Ah, it's possible that the interactive prompt is precisely the issue. Terragrunt might not be showing you the prompt, so it's not hanging, but waiting for you to type in credentials! 

Could you try the same code, but with an https URL that doesn't require auth?

**Comment by brikis98** [comment]
No response in a few months, so closing the issue.

**Comment by nibatandukar** [comment]
Hi, @brikis98 . I am trying to setup the landing zone but after I use terragrunt plan my system goes down. The terragrunt init will be successfully complete. But after I sue terragrunt plan the system goes down and I have to restartt my machine.

**Comment by brikis98** [comment]
Your computer crashes? Or `plan` just seems to hang for a long time?

Also, which Landing Zone modules are you using?
