### ISSUE TITLE
Remote state S3 bucket does not exist or you don't have permissions to access it

### ISSUE THREAD

**Issue by supratim-persistent** [gruntwork-io/terragrunt#1408]
While testing the ECS deploy runner through the infrastructure-deployer, I am using my machine user present in account1 to assume the IAM role allow-auto-deploy-from-other-accounts for account2 using aws-auth(aws-auth --role-arn "arn:aws:iam::<Account2>:role/allow-auto-deploy-from-other-accounts") and that shows up as success. After that I am using the infrastructure-deployer on command line by passing required arguments(like ref, deploy_path, etc with deploy_path being a folder that has Account2 info in it) but it keeps failing with below error even though I think the permissions are set correctly as well as the S3 bucket for tfstate also exists in Account2.
Error - _[ecs-deploy-runner][2020-10-30T06:04:03+0000] [terragrunt] [/tmp/tmp5_r2xt90/sandbox/us-east-1/_global/kms-master-key] 2020/10/30 06:04:03 [terragrunt] [/tmp/tmp5_r2xt90/sandbox/us-east-1/_global/kms-master-key]  Remote state S3 bucket <TF_STATE_BUCKET_NAME_OF_ACCOUNT2> does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)
[ecs-deploy-runner][2020-10-30T06:04:03+0000] [terragrunt] 2020/10/30 06:04:03 EOF
[ecs-deploy-runner][2020-10-30T06:04:03+0000] [terragrunt] 2020/10/30 06:04:03 Unable to determine underlying exit code, so Terragrunt will exit with error code 1_
My permissions are as follows
ECS deploy runner is installed in Account1 with machine-user in A]ccount1.
machine-user has a policy(called machine-user-assume-role-policy) attached to it that allows it to sts:AssumeRole on 2 role arns - one being a role in Account1 itself that has invoke-ecs-deploy-runner policy attached to it and the other being a role in account2 that has some permissions for few services including S3 in that account.
In account2, the same role is configured with trust permission for machine-user in account1.
However, after all this, i see failure with above error, anything on this?

**Comment by yorinasub17** [comment]
NOTE: Migrating this to `module-ci` as this is not a terragrunt bug, but an issue with the ECS deploy runner.

https://github.com/gruntwork-io/module-ci/issues/246
