### ISSUE TITLE
Question: How can I run Ephemeral environments using Terragrunt?

### ISSUE THREAD

**Issue by avnerenv0** [gruntwork-io/terragrunt#1409]
I've been using Terraform a lot, and am eyeing a move to Terragrunt, as it seems to address a lot of needs that are unanswered in "vanilla" Terraform.

What I am missing, or I don't understand, is how can ephemeral environments be created ?

Besides the DEV / STAGING / PROD environments that I have set up in folders, sometimes I need to have a temporary environment. In Terraform I just do - `terraform workspaces new && terraform apply`, So I get a clean state, I can deploy what I need, and get rid of it later.

How can this be achieved using Terragrunt?

Thanks

**Comment by brikis98** [comment]
Terragrunt fills in several different gaps in Terraform, so the question is, which features are you looking to use?

One of the main ideas with Terragrunt is to define all your environments using file/folders: we find this makes it much clearer and more visible what's going on. It then offers various helpers to (a) help keep your code DRY with such a file/folder layout and (b) automatically calculate analogous paths for state storage in a backend. With such a set up, you create new environments, including ephemeral ones, by creating more files/folders. When you're done with them, you can run `destroy` (or `destroy-all`) and delete those files/folders.

Of course, nothing requires you to do it this way. You could manage persistent environments using files/folders and ephemeral ones using Terraform workspaces.

**Comment by avnerenv0** [comment]
Thanks @brikis98 !

So to reiterate - the Terragrunt way of creating a new environment is creating a new folder.

Just making sure - there is no way to run Terragrunt while overriding the `automatically calculate analogous paths for state storage in a backend`? Something like manually passing a CLI argument with the backend path?

**Comment by brikis98** [comment]
> So to reiterate - the Terragrunt way of creating a new environment is creating a new folder.

Yep.

> Just making sure - there is no way to run Terragrunt while overriding the `automatically calculate analogous paths for state storage in a backend`? Something like manually passing a CLI argument with the backend path?

Do you mean you want a way to set the `backend` configuration from the CLI? If so, there are various ways to do that. For example, in your `terragrunt.hcl`, you could have:

```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket = get_env("BACKEND_BUCKET", "my-terraform-state")

    key = get_env("BACKEND_KEY", "${path_relative_to_include()}/terraform.tfstate")
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "my-lock-table"
  }
}
```

Notice how `bucket` and `key` use `get_env` to read an env var, and only fall back to the options in the file if no env var is set. This allows you to override those settings on the CLI:

```bash
BACKEND_BUCKET=my-override-bucket BACKEND_KEY=foo/bar/terraform.tfstate terragrunt apply
```

**Comment by avnerenv0** [comment]
Thanks!

Is there an option to provide `-backend-config=PATH` to the CLI like we do with vanilla Terraform?

**Comment by brikis98** [comment]
Terragrunt forwards all flags to Terraform, so yea, you can run `terragrunt init -backend-config=xxx`.

**Comment by avnerenv0** [comment]
Thanks for all the help 🙏
