### ISSUE TITLE
Is the new release v0.26.0 or v0.26.1?

### ISSUE THREAD

**Issue by ahmad-hamade** [gruntwork-io/terragrunt#1413]
I've downloaded the latest release `v0.26.0` however running `terragrunt --version` reporting `terragrunt version v0.26.1`

**Comment by brikis98** [comment]
Doh! We accidentally created `v0.26.1` initially, realized we had skipped `v0.26.0`, and then renamed the release... But of course, the binaries had already been built with `v0.26.1` in them. @ina-stoyanova, To reduce confusion, it might be best to delete the `v0.26.0` release (and tag), and then recreate it with the exact same content (so make sure to make a copy of the release notes first!). That will result in the binaries being rebuilt with the proper version number.

**Comment by ina-stoyanova** [comment]
@brikis98 @ahmad-hamade I've deleted the old tag and release **(v0.26.0)** & released a new version under the same tag. You should now be able to install the latest (v0.26.0) and see the correct tag on the binaries too (tested it on my machine too & can get the right version numbers)

https://github.com/gruntwork-io/terragrunt/releases/tag/v0.26.0

Apologies for the confusion!

**Comment by ina-stoyanova** [comment]
I'll keep this issue open today, just to see if there's any other confusion around this! @ahmad-hamade let us know if that's working for you when you have a chance to test it :)

**Comment by ahmad-hamade** [comment]
Thanks a lot, @ina-stoyanova. It's working correctly now.

```
terragrunt --version
terragrunt version v0.26.0
```

**Comment by ina-stoyanova** [comment]
Thanks a lot for confirming @ahmad-hamade 👍  Closing this issue now.

**Comment by ldormoy** [comment]
What about Homebrew? The stable version is still 0.26.1

https://formulae.brew.sh/formula/terragrunt

**Comment by ina-stoyanova** [comment]
Looking into this @ldormoy. Thanks for raising!

**Comment by ina-stoyanova** [comment]
I've now raised an issue on the [**Homebrew Core repo**](https://github.com/Homebrew/homebrew-core/pull/64096)

This is not under our control, as we do not currently control, automate and release these taps - it's entirely done by the contributors to that open-source tool. 

Will post further updates as they come in.

**Comment by ina-stoyanova** [comment]
https://github.com/Homebrew/homebrew-core/pull/64096

**Comment by ina-stoyanova** [comment]
@ldormoy the PR for Homebrew has now been merged. I just tested running 
```
brew install terragrunt | brew upgrade terragrunt
```
which now has the correct latest version "v0.26.2" 

```
~ terragrunt --version                                                                             
terragrunt version v0.26.2
```

**Comment by ina-stoyanova** [comment]
I'll be closing this issue later today. 

If anything else comes up - you're welcome to raise a new issue 🙂
