### ISSUE TITLE
terraform.TgApplyAll(t, terraformOptions) is failing to perform --terragrunt-include-external-dependencies operation · Issue #1417 · gruntwork-io/terragrunt

### ISSUE THREAD

**Issue by pandu-bhojaraj-mf** [gruntwork-io/terragrunt#1418]
> @bruno @yorinasub17 @yupvr
> 
> 
> If i run **terragrunt apply-all --terragrunt-non-interactive** command manually from **command line** then I am getting below error
> 
> ![image](https://user-images.githubusercontent.com/73541850/98210373-80070100-1f66-11eb-8845-5b7bd3812d89.png)
> 
> 
> If i run below command manually from **command line** then I am getting positive response **without any error**
> 
> **terragrunt apply-all --terragrunt-non-interactive --terragrunt-include-external-dependencies**
> 
> 
> But if i invoke same module from terratest using **terraform.TgApplyAll(t, terraformOptions)** function then i am getting below **error same error as** of #**1**
> 
> ![image](https://user-images.githubusercontent.com/73541850/98210571-c2c8d900-1f66-11eb-979b-a608f375432f.png)
> 
> 
> So In terratest please let me know how can i run **terragrunt apply-all --terragrunt-non-interactive --terragrunt-include-external-dependencies** because **terraform.TgApplyAll(t, terraformOptions)** is not solving the problem
> Are there any way/option/modifications do i need to do in terraform.TgApplyAll(t, terraformOptions) function to pass **--terragrunt-include-external-dependencies** ??
> 
> Please help

Below solution dint work

# 1
options := &Options{
			TerraformDir:    "../with-infra/vertica-console",
			TerraformBinary: "terragrunt",
			EnvVars: map[string]string{
				"TF_CLI_ARGS": "--terragrunt-include-external-dependencies",
			},
		}

# 2
RunTerraformCommandE(t, options, FormatArgs(options, "apply-all", "-input=false", "-lock=false", "-auto-approve", "--terragrunt-non-interactive", "--terragrunt-include-external-dependencies")...)

**Comment by yorinasub17** [comment]
This is actually an issue with terratest, so moving it over there. The underlying feature that is needed is https://github.com/gruntwork-io/terratest/issues/699
