### ISSUE TITLE
terragrunt always re-runs `terraform init` with terraform 0.14.0-rc1

### ISSUE THREAD

**Issue by ksvladimir** [gruntwork-io/terragrunt#1423]
It seems terragrunt fails to detect when initialization is not necessary when using terraform 0.14.0-rc1. It always runs `terraform init` no matter what, and it takes a lot of time especially when dependencies are involved.

I also tried `terragrunt apply --terragrunt-no-auto-init`, and here's what happens:

```
$ terragrunt apply --terragrunt-no-auto-init
...
[terragrunt] 2020/11/13 01:29:18 Cannot continue because init is needed, but Auto-Init is disabled.  You must run 'terragrunt init' manually.
[terragrunt] 2020/11/13 01:29:18 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by ksvladimir** [comment]
This is the problem: https://github.com/gruntwork-io/terragrunt/blob/7f0920ab4b961984a8d1cb60af48a2bb00961ad9/cli/cli_app.go#L723

It seems that terraform renamed `.terraform/plugins` into `.terraform/providers`. So the check needs to be:
```go
        providersPath013 := util.JoinPath(terragruntOptions.DataDir(), "plugins")
	providersPath014 := util.JoinPath(terragruntOptions.DataDir(), "providers")
	return !(util.FileExists(providersPath013) || util.FileExists(providersPath013))
```

**Comment by brikis98** [comment]
Thanks for reporting! Since 0.14.0 is not out yet, we have not yet tested or updated Terragrunt to work with it. We will do so once the final version is released.

**Comment by michelzanini** [comment]
Now that 0.14 is out I think this must be locked at

**Comment by brikis98** [comment]
Ah, good point, thanks for the reminder!

**Comment by faucherb94** [comment]
Also just ran into this myself 😄

**Comment by anagarjunr** [comment]
Facing the same issue

**Comment by johnlinvc** [comment]
A temporary workaround for this issue is to create a empty folder `plugins` in 
`.terragrunt-cache/RANDOM_HASH/ANOTHER_RANDOM_HASH/.terraform/`
like
`mkdir .terragrunt-cache/X0em602TiSrcCnD8MSB9SfZ-Wiw/Dtif5ds3Xi5dZzANQWFL-b_aEkQ/.terraform/plugins`

Terragrunt stops reinit after created this empty folder.

**Comment by tjtaill** [comment]
@johnlinvc thanks your workaround makes it a lot more usable was so slow before

**Comment by vsabella** [comment]
can we release that!

**Comment by vsabella** [comment]
Super thanks for the fix! Is it possible to get it released soon?

**Comment by brikis98** [comment]
We're working on it in https://github.com/gruntwork-io/terragrunt/pull/1459. We were out on vacation the last couple weeks for the holidays, but will pick it up again later this week.

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.27.0 a shot!

**Comment by Morley93** [comment]
Thanks @brikis98, 0.27.0 fixed this for me. 👍
