### ISSUE TITLE
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-vpc.git?ref=v2.31.0': /usr/bin/git exited with 128: git@github.com: Permission denied (publickey). fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by mirkomat79** [gruntwork-io/terragrunt#1430]
Hi, 
I've tried to deploy infrastructure created as output of CloudCraft Architecture drawings, on Ubuntu 18.4. 

Terraform v0.13.5
terragrunt version v0.26.0

but with multiple architectures I receive following errors: 

[terragrunt] 2020/11/14 22:28:38 Encountered the following errors:
Hit multiple errors:
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git?ref=v2.13.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/ec2-instance_2/.terragrunt-cache/ibRBIExDudNe_P5RQ44PYch5CjQ/u0xMEnw2Ajc7FeaD1uEijx3U6hU'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Hit multiple errors:
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git?ref=v2.13.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/frontendvm1/.terragrunt-cache/9amtaHo95HnsTpfZ4-oGU826UuA/u0xMEnw2Ajc7FeaD1uEijx3U6hU'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Hit multiple errors:
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git?ref=v2.13.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/frontendvm2/.terragrunt-cache/tgG0JYFlLC_zCzMLV5KucBK-25I/u0xMEnw2Ajc7FeaD1uEijx3U6hU'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Hit multiple errors:
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-vpc.git?ref=v2.31.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/dev-lab-vpc/.terragrunt-cache/grlEVdlo9M7AAJWhSskB8k0tjBM/BoKn_3NNiOJEg4PmxaP5wYFi3M8'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Cannot process module Module /home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/dmz (excluded: false, dependencies: [/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/dev-lab-vpc]) because one of its dependencies, Module /home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/dev-lab-vpc (excluded: false, dependencies: [/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/aws-data]), finished with an error: Hit multiple errors:
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-vpc.git?ref=v2.31.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/dev-lab-vpc/.terragrunt-cache/grlEVdlo9M7AAJWhSskB8k0tjBM/BoKn_3NNiOJEg4PmxaP5wYFi3M8'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Hit multiple errors:
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git?ref=v2.13.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/ec2-instance_1/.terragrunt-cache/sRiDadggXUYq_EPCMniQ2XGR6ys/u0xMEnw2Ajc7FeaD1uEijx3U6hU'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

[terragrunt] 2020/11/14 22:28:38 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

I've tried to with downgrading terragrunt to V0.21.2, but over there couldn't recognize generate

Can you please take a look, I can provide more info and logs if necessary.

**Comment by brikis98** [comment]
```
error downloading 'ssh://git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git?ref=v2.13.0': /usr/bin/git exited with 128: Cloning into '/home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/ec2-instance_2/.terragrunt-cache/ibRBIExDudNe_P5RQ44PYch5CjQ/u0xMEnw2Ajc7FeaD1uEijx3U6hU'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

This looks like a Git permissions error. Are you able to directly `git clone` the `source` URL shown there: 

```bash
git clone git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git
```

Do you have git configured properly? Do you need to `ssh-add` your key?

**Comment by mirkomat79** [comment]
Hi Yevgeniy, 
thank you for picking up my question. 
Bare with me, I'm a beginner in this field.
I've just used advice from README.md to export account key variables: 
 export AWS_DEFAULT_REGION=us-east-1
export AWS_ACCESS_KEY_ID=<my access key>
export AWS_SECRET_ACCESS_KEY=<my secret key>

Is this what is expected to be done with keys ?

I've tried git clone now, but it failed with below error: 
ubuntu@ip-172-31-45-187:~/Proba/hybrid_cloud_architecture/us-east-1$ git clone git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git
fatal: repository 'git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git' does not exist

Also, just to mention, maybe is important - I get some other error during terragrunt init, 
[terragrunt] 2020/11/16 09:01:29 The file path /home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/main_providers.tf a
[terragrunt] 2020/11/16 09:01:29 open /home/ubuntu/Proba/hybrid_cloud_architecture/us-east-1/main_providers.tf:  permission denied
[terragrunt] 2020/11/16 09:01:29 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

Looking forward for your advice and suggestion . 
kind regards, 
Mirko

**Comment by brikis98** [comment]
```
fatal: repository 'git@github.com/terraform-aws-modules/terraform-aws-ec2-instance.git' does not exist
```

The proper Git URL should be: `git@github.com:terraform-aws-modules/terraform-aws-ec2-instance.git` (note the `:` instead of `/` after `github.com`). Could you try that?

**Comment by mirkomat79** [comment]
Hi Yevgenij, 

I followed the guide from github : 
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
1) after generating new ssh key and
2) adding it to agent :
ssh-add ~/.ssh/id_rsa 
3) and adding it to Github account, 

I could run successfully command that you proposed:

ubuntu@ip-172-31-45-187:~/hybrid_cloud_architecture/us-east-1$ git clone git@github.com:terraform-aws-modules/terraform-aws-ec2-instance.git
Cloning into 'terraform-aws-ec2-instance'...
remote: Enumerating objects: 470, done.
remote: Total 470 (delta 0), reused 0 (delta 0), pack-reused 470
Receiving objects: 100% (470/470), 116.62 KiB | 12.96 MiB/s, done.
Resolving deltas: 100% (225/225), done.

Also, terragrunt apply is not giving the previous error message with permission denied, so I think that issue is solved. 

Still the script is not fully executed, Now I get error mesage of type:
Cannot process module Module /home/ubuntu/hybrid_cloud_architecture/us-east-1/dmz (excluded: false, dependencies: [/home/ubuntu/hybrid_cloud_architecture/us-east-1/dev-lab-vpc]) because one of its dependencies, Module /home/ubuntu/hybrid_cloud_architecture/us-east-1/dev-lab-vpc (excluded: false, dependencies: [/home/ubuntu/hybrid_cloud_architecture/us-east-1/aws-data]), finished with an error: Hit multiple errors:
exit status 1
but I think that might be related to other problems in that terragrunt scripts...

If you have a clue, please, advice related to that also. 

I'll test a bit more and look  for if there is some known issue related to this. 

Thank you for support, 

kind regards, Mirko

**Comment by brikis98** [comment]
> I followed the guide from github :
> https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
> 
> 1. after generating new ssh key and
> 2. adding it to agent :
>    ssh-add ~/.ssh/id_rsa
> 3. and adding it to Github account,
> 
> I could run successfully command that you proposed:

Perfect!

> Still the script is not fully executed, Now I get error mesage of type:
> Cannot process module Module /home/ubuntu/hybrid_cloud_architecture/us-east-1/dmz (excluded: false, dependencies: [/home/ubuntu/hybrid_cloud_architecture/us-east-1/dev-lab-vpc]) because one of its dependencies, Module /home/ubuntu/hybrid_cloud_architecture/us-east-1/dev-lab-vpc (excluded: false, dependencies: [/home/ubuntu/hybrid_cloud_architecture/us-east-1/aws-data]), finished with an error: Hit multiple errors:
> exit status 1
> but I think that might be related to other problems in that terragrunt scripts...

This message in the logs says there's an error, but the error itself should be earlier in the log output. Scroll up to find it!

**Comment by mirkomat79** [comment]
Hi yevgenij, in the meantime I had opened a case at CloudCraft. They advised me to downgrade terraform to V0.12.5 and I got b it further in the execution of terragrunt script. But, now I receive this error message:
There are some problems with the configuration, described below:

execution logs: 
"
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Reserved argument name in resource block

  on main.tf line 1002, in resource "aws_customer_gateway" "this":
1002:   for_each = var.customer_gateways

The name "for_each" is reserved for use in a future version of Terraform.

Also, further in the log reports dependency issues as before:
"
[terragrunt] [/home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dev-lab-vpc] 2020/11/25 15:44:31 Module /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dev-lab-vpc has finished with an error: Hit multiple errors:
exit status 1
[terragrunt] [/home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dmz] 2020/11/25 15:44:31 Dependency /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dev-lab-vpc of module /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dmz just finished with an error. Module /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dmz will have to return an error too.
[terragrunt] [/home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dmz] 2020/11/25 15:44:31 Module /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dmz has finished with an error: Cannot process module Module /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dmz (excluded: false, dependencies: [/home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dev-lab-vpc]) because one of its dependencies, Module /home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/dev-lab-vpc (excluded: false, dependencies: [/home/ubuntu/1test/hybrid_cloud_architecture/us-east-1/aws-data]), finished with an error: Hit multiple errors:
exit status 1
"
and errors to function calls:
"
Error: Error in function call

  on main.tf line 12, in resource "aws_instance" "this":
  12:   subnet_id = length(var.network_interface) > 0 ? null : element(
  13:
  14:
  15:
    |----------------
    | count.index is 0
    | var.subnet_id is ""
    | var.subnet_ids is empty list of string

Call to function "element" failed: cannot use element function with an empty
list.


Error: Error in function call

  on main.tf line 12, in resource "aws_instance" "this":
  12:   subnet_id = length(var.network_interface) > 0 ? null : element(
  13:
  14:
  15:
    |----------------
    | count.index is 0
    | var.subnet_id is ""
    | var.subnet_ids is empty list of string

Call to function "element" failed: cannot use element function with an empty
list.
"
Are these known problems ?
Do you have some advice how to solve them ?

Thank you for support, 
kind regards, 
Mirko

**Comment by brikis98** [comment]
OK, you're now hitting Terraform syntax/logic errors. I don't think those are related to Terragrunt, but due to the logic of your own Terraform code. Please seek the Terraform forums for help with those!
