### ISSUE TITLE
Provide arm64 asset

### ISSUE THREAD

**Issue by mijdavis2** [gruntwork-io/terragrunt#1432]
AWS now supports ARM64 instances, so would be great to run terragrunt on arm64 cloud instances for ci/cd, etc.

**Comment by zhiguangwang** [comment]
Might as well be useful to provide `darwin/arm64` to run on Apple Silicon (M1).

**Comment by yorinasub17** [comment]
Just wanted to mention that we will most likely add arm64 to the mix as soon as [golang 1.16](https://tip.golang.org/doc/go1.16) is released, which adds `darwin/arm64` support.

**Comment by yorinasub17** [comment]
FYI we are now publishing `arm64` binaries starting with https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.12

**Comment by jaypatrickhoward** [comment]
Is it more or less impossible to build arm64 versions of older (read: very old) releases, e.g. 0.18.7?  I had hoped to run the amd64 version of 0.18.7 in emulation mode, but unfortunately it segfaults.

**Comment by yorinasub17** [comment]
Unfortunately, it's not really going to be possible to do that since `0.18.7` requires an older version of go, and older versions of go do not support building `arm64`. I would love to investigate why it segfaults/doesn't work, but I don't really have the bandwidth at the moment.

My suggestion is to go through Docker, which I know is painful but unfortunately is the best workaround I can offer at the moment.

**Comment by jaypatrickhoward** [comment]
Docker is my backup plan, yeah.  If I install the older go version (via brew) in arm64 native mode, is it likely to be able to build arm64 binaries?

**Comment by yorinasub17** [comment]
go couldn't build proper `darwin/arm64` binaries until `1.16`. That's because up until `1.16`, `darwin/arm64` actually meant IOS. So it will try to build IOS binaries if you use an older version of go on M1.

**Comment by jaypatrickhoward** [comment]
Hmm.  What version of go does 0.18.7 require/expect?  I took a look at the 0.18.7 source and it wasn't obvious to me, but I'm also not a go dev.  If the build process isn't overly complicated I'm happy to try re-building it (with the older go, but in my arm64 environment) and see if at least produces an x86 binary that runs correctly under emulation.

**Comment by yorinasub17** [comment]
I think go 1.13 is a good version to try on. That should support [dep](https://golang.github.io/dep/), which is what we were using for dependency management at the time.

**Comment by denis256** [comment]
Hi, build arm version for 0.18.7, use at own risk :)

https://github.com/denis256/terragrunt/releases/tag/v0.18.7

**Comment by slavvka** [comment]
@denis256 Is it possible to build a binary for x86_64 architecture for MacOS Monterrey based on Intel chip?
