### ISSUE TITLE
Add option to specify target prefix when setting access logging on terraform state bucket

### ISSUE THREAD

**Issue by dsecik** [gruntwork-io/terragrunt#1437]
In addition to the `accesslogging_bucket_name` configuration option introduced in #1400 allowing to specify target bucket for s3 access logs, it would be handy to have an ability to specify also the target prefix to override the default `targetPrefix := "TFStateLogs/"` This will add more flexibility to access logging configuration, for example to be able to send access logs from multiple terraform state buckets to single logging bucket and not mix them together.

**Comment by brikis98** [comment]
Seems worthwhile. PR to add this is welcome!

**Comment by ina-stoyanova** [comment]
I'll pick this up this week!

**Comment by ina-stoyanova** [comment]
Closing this issue. The feature has been implemented.
