### ISSUE TITLE
[Question] request/doubt, not an issue

### ISSUE THREAD

**Issue by mauricioscastro** [gruntwork-io/terragrunt#1445]
When launching a after_hook is it possible to do a 'cd' (change directory) before executing the command?

I know I can wrap what I need in a script and do it, but I wanted to run a clean "ansible-playbook" whithout the need for wrapping it. 

I am far from Go, really newbie at it, but I could give it a try to make it work for the xxxxx_hook's or is there already something previewed for this?

Thank you all for your attention.

**Comment by brikis98** [comment]
There's nothing natively built into Terragrunt to change the working directory for hooks. If you need to do that, you need to build it into the script you're executing. Alternatively, you can shove it into the script command itself. Something like:

```hcl
 after_hook "example" {
  commands     = ["apply", "plan"]
  execute      = ["bash", "-c", "cd /foo/bar && run-some-command"]
}
```

**Comment by mauricioscastro** [comment]
yep, that's what I've been doing.
thanks for the answer

**Comment by brikis98** [comment]
You bet!
