### ISSUE TITLE
Import an existing resource

### ISSUE THREAD

**Issue by arik-porat** [gruntwork-io/terragrunt#1446]
Hi,
Can someone please explain me how can I import a state of an existing resource and make a use of it for example in a module?

Is there any example somewhere you can share?

**Comment by brikis98** [comment]
When you run `terragrunt xxx`, in almost all cases, Terragrunt forwards your command to Terraform, resulting in `terraform xxx`. So to import resources, you run `terragrunt import`, and it'll call `terraform import` as normal. See the [Terraform `import` docs](https://www.terraform.io/docs/import/usage.html) for examples / instructions.

**Comment by atulatri** [comment]
Can I generate "inputs" section automatically while importing a resource?

**Comment by brikis98** [comment]
Why do you need inputs while importing?

**Comment by yorinasub17** [comment]
Closing as stale and the original question has been answered. If there are any follow ups, please open a new ticket with the updated context. Thanks!
