### ISSUE TITLE
Terraform sub module path issue

### ISSUE THREAD

**Issue by samcon** [gruntwork-io/terragrunt#1449]
Hi, I'm facing an issue when using a module inside a module

I've the following directory structure:
```
./modules/test_module
./modules/test_submodule
./terragrunt/prod/test_env

# ./modules/test_module/main.tf:
module "test_submodule" {
  source = "../test_submodule"
}

# ./modules/test_submodule/main.tf:
resource "some_resource" "name" {
...
}

# ./prod/test_env/terragrunt.hcl
terraform {
  source = "${get_parent_terragrunt_dir()}/modules/test_module"
}

include {
  path = find_in_parent_folders()
}
...
```

In `./prod/test_env`, when I run 
`terragrunt init`

I'm getting
```Error: Unreadable module directory
Unable to evaluate directory symlink: lstat ../test_submodule: no such file or directory
Error: Failed to read module directory
Module directory  does not exist or cannot be read.
Error: Unreadable module directory
Unable to evaluate directory symlink: lstat ../test_submodule: no such file or directory
Error: Failed to read module directory
Module directory  does not exist or cannot be read.
```

If I change ./modules/test_module/main.tf to:
```
module "test_submodule" {
  source = "../../../../../../modules/test_submodule"
}
```

(Which isn't very desirable) and run `terragrunt init` - init succeeds . That's because it seems that the cwd is set to 
`prod/test_env/test_env/.terragrunt-cache/IyH8IDXe2nfEwZHzlEyghVc_c6s/wWNOAm2DrhmLRuAOZITIobZzYGs`
and not to `./modules/test_module` (which is the calling module).

Is this intend behavior? Are you not supposed to call module inside your modules? Is there a way to make the "source" relative to the calling module (and not the calling env)?
```
$ terragrunt -v && terraform -v
terragrunt version v0.26.2
Terraform v0.13.5
```

Thanks!

**Comment by brikis98** [comment]
You need a double-slash in your `source` URL for relative paths to work: https://terragrunt.gruntwork.io/docs/features/keep-your-terraform-code-dry/#remote-terraform-configurations

**Comment by samcon** [comment]
Thanks for the quick reply! Interesting - I suspected that it's only relevant for remote module. 
Changing ./prod/test_env/terragrunt.hcl to:
```
terraform {
  source = "${get_parent_terragrunt_dir()}//modules/test_module"
}
...
```
(note double slash)

Allowed me to change ./modules/test_module/main.tf to:
```
module "test_submodule" {
  source = "../test_submodule"
}
```

💯 
Thanks!

**Comment by brikis98** [comment]
Glad to hear it worked!
