### ISSUE TITLE
Copy Provider Dependency Lock file to `teragrunt.hcl` directory

### ISSUE THREAD

**Issue by lawliet89** [gruntwork-io/terragrunt#1454]
Terraform 0.14 adds support for [Provider Dependency Lock file](https://www.terraform.io/upgrade-guides/0-14.html#provider-dependency-lock-file).

This is a feature request for Terragrunt to work with this new lock file.

- If Terragrunt notices that the lock file does not exist, it should copy it from the `.terragrunt-cache` directory to the directory that Terragrunt was invoked from (i.e. the one with `terragrunt.hcl`).
- If the file already exists, there's nothing to do because Terragrunt will copy the file into `.terragrunt-cache` and Terraform will work with it.

**Comment by brikis98** [comment]
Ah, yes, I think this make sense. Otherwise, there's no reasonable way to check that file into version control. A PR to add this functionality is welcome!

**Comment by brikis98** [comment]
Working on it in https://github.com/gruntwork-io/terragrunt/pull/1459

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.27.0 a shot!

**Comment by lawliet89** [comment]
Works very well. Thank you everyone who was involved.
