### ISSUE TITLE
Terragrunt init fails while checking AWS config profile for S3 bucket

### ISSUE THREAD

**Issue by sumitsingh306** [gruntwork-io/terragrunt#1458]
Hi ,

We already have terragrunt module for dev,qa, prod to install an application on AWS Ec2. I cloned the repository and I want to initialize the terragrunt to make sure its connecting with AWS or not. But Im getting below error while running 'terragrunt init' command on gitbash and powershell. 

Any suggestion and help is most welcome. Thanks !

Set up have - 
aws-cli/2.1.1 Python/3.7.7
terragrunt version v0.25.4
Terraform v0.13.4

Error -----------------------------------------------------
[terragrunt] 2020/12/03 21:54:49 Initializing remote state for the s3 backend
[terragrunt] 2020/12/03 21:54:49 Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by gtirloni** [comment]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by brikis98** [comment]
Looks like an AWS auth error. Check out [A Comprehensive Guide to Authenticating to AWS on the Command Line](https://blog.gruntwork.io/a-comprehensive-guide-to-authenticating-to-aws-on-the-command-line-63656a686799) for instructions.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
