### ISSUE TITLE
Terraform is introducing its own state locking

### ISSUE THREAD

**Issue by jeffbyrnes** [gruntwork-io/terragrunt#146]
I only glanced at it, but potentially relevant: hashicorp/terraform#11187

Does Terragrunt need this feature any longer, if TF has its own, built-in, locking?

Apologies if I’m duping; I didn’t see any issues bringing this up.

**Comment by mechastorm** [comment]
This seems to be already covered in #115 which I think will also cover what Terragrunt plans to do once Terraform 0.9.0 is official

**Comment by josh-padnick** [comment]
Agreed this is covered in #115, so I'll close so comments can be handled there.

**Comment by jeffbyrnes** [comment]
Ok, thanks, sorry about the dupe!
