### ISSUE TITLE
[Question] - How to use aws registry moudles

### ISSUE THREAD

**Issue by arik-porat** [gruntwork-io/terragrunt#1460]
Hi,
I would like to use an aws registry moudle (for example the https://github.com/terraform-aws-modules/terraform-aws-vpc)
This module doesn't have this code in it

> terraform {
>   backend "s3" {}
> }
> 
> provider "aws" {
>   region = "${var.region}"
> }

I wonder if there's a way I can use the module directly from my live instead of creating a new module that call the aws module which set the backend and provider. This seems a bit redundant and require me to create a module per every registry module or other ready to use module that I choose to use.

**Comment by gtirloni** [comment]
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform

> source (attribute): Specifies where to find Terraform configuration files. This parameter supports the exact same syntax as the module source parameter for Terraform module blocks, including local file paths, Git URLs, and Git URLS with ref parameters. Terragrunt will download all the code in the repo (i.e. the part before the double-slash //) so that relative paths work correctly between modules in that repo.

https://www.terraform.io/docs/modules/sources.html#terraform-registry

> Modules on the public Terraform Registry can be referenced using a registry source address of the form <NAMESPACE>/<NAME>/<PROVIDER>, with each module's information page on the registry site including the exact address to use.

```
module "consul" {
  source = "hashicorp/consul/aws"
  version = "0.1.0"
}
```

**Comment by arik-porat** [comment]
Not sure I've understand you answer...
Can you supply an example?

This is my hcl file:

terraform {
  source =  "github.com/terraform-aws-modules/terraform-aws-sqs.git//?ref=v2.1.0"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  name = "sqs-tf-test"
  tags = {
    product_unit = "devops"
    product_component = "devops"
    service_name = "SQS"
    group = "devops"
    environment = "integration"
  }
}

Where should I set the s3 backend and the provider?

**Comment by brikis98** [comment]
You can use a [`generate` block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate) to configure the `provider` and a [`remote_state` block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state) to configure the `backend`.

**Comment by arik-porat** [comment]
Actually I've tried to use the generate block. The issue is that I do have some modules that contains the backend and the provider inside them in some .tf file (can have different names) so I get an error of duplicate backend and/or duplicated provider. Is there a way to overcome this? or an alternative methods to achieve what I want?

**Comment by brikis98** [comment]
There's no magic here. If your Terraform modules are inconsistent—some have no `provider` / `backend`, some do, and they all use different file names—you'll have to update your Terragrunt code to match those various patterns. That is, some of your `terragrunt.hcl` will have to use a `generate` block, and some won't, depending on what you're deploying with that `terragrunt.hcl`.

**Comment by arik-porat** [comment]
Thanks for answering

**Comment by brikis98** [comment]
Glad to help!
