### ISSUE TITLE
Terragrunt ignores arguments passed into `terragrunt init` when invoking `terraform init`

### ISSUE THREAD

**Issue by benderillo** [gruntwork-io/terragrunt#1461]
I am trying to run an `init` in a specific folder using terragrunt with a set of arguments like this:
`terragrunt init -get=true -input=false -backend=false --terragrunt-debug`

I am expecting terragrunt to pass the arguments to `terraform` and eventually do the initialisation without trying to configure the backend. But this is what I get instead:
```
>terragrunt init -get=true -input=false -backend=false --terragrunt-debug
[terragrunt] [/work/terraform-code/core] 2020/12/07 14:07:51 Running command: terraform --version
[terragrunt] 2020/12/07 14:07:51 Terraform version: 0.13.4
[terragrunt] 2020/12/07 14:07:51 Reading Terragrunt config file at /work/terraform-code/core/terragrunt.hcl
[terragrunt] 2020/12/07 14:07:51 The file path /work/terraform-code/core/_terragrunt_gen-provider.tf already exists and if_exists for code generation set to "overwrite". Regenerating file.
[terragrunt] 2020/12/07 14:07:51 Generated file /work/terraform-code/core/_terragrunt_gen-provider.tf.
[terragrunt] 2020/12/07 14:07:51 The file path /work/terraform-code/core/_terragrunt_gen-version.tf already exists and if_exists for code generation set to "overwrite". Regenerating file.
[terragrunt] 2020/12/07 14:07:51 Generated file /work/terraform-code/core/_terragrunt_gen-version.tf.
[terragrunt] 2020/12/07 14:07:51 The file path /work/terraform-code/core/_terragrunt_gen-backend.tf already exists, but was a previously generated file by terragrunt. Since if_exists for code generation is set to "overwrite_terragrunt", regenerating file.
[terragrunt] 2020/12/07 14:07:51 Generated file /work/terraform-code/core/_terragrunt_gen-backend.tf.
[terragrunt] 2020/12/07 14:07:51 Debug mode requested: generating debug file terragrunt-debug.tfvars.json in working dir /work/terraform-code/core
[terragrunt] 2020/12/07 14:07:51 Variables passed to terraform are located in "/work/terraform-code/core/terragrunt-debug.tfvars.json"
[terragrunt] 2020/12/07 14:07:51 Run this command to replicate how terraform was invoked:
[terragrunt] 2020/12/07 14:07:51        terraform init -get=true -input=false -backend=false -var-file="/work/terraform-code/core/terragrunt-debug.tfvars.json" "/work/terraform-code/core"
[terragrunt] 2020/12/07 14:07:51 Initializing remote state for the s3 backend
[terragrunt] 2020/12/07 14:07:52 [terragrunt]  Remote state S3 bucket atmail-tf-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
^C
```

1. Note that it tries to access S3 to initialise remote state for the s3 backend.
2. Note that it says:
> Run this command to replicate how terraform was invoked:
>        terraform init -get=true -input=false -backend=false -var-file="/work/terraform-code/core/terragrunt-debug.tfvars.json" "/work/terraform-code/core"
3. The contents of the `/work/terraform-code/core/terragrunt-debug.tfvars.json` is just an empty block `{}`

When I run the `terraform` directly, it acts as expected. I.e. it succeeds without accessing S3 (as told):
```
terraform init -get=true -input=false -backend=false -var-file="/work/terraform-code/core/terragrunt-debug.tfvars.json" "/work/terraform-code/core
Initializing modules...
- alerting in ../modules/alerting
- buckets in ../modules/buckets
- dns in ../modules/dns
- vpc in ../modules/vpc

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.11"...
- Installing hashicorp/aws v3.20.0...
- Installed hashicorp/aws v3.20.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

I don't understand why is this happening. Terragrunt documentation says that this command will be passed to terraform with all its arguments but apparently this is not the case.

The `terragrunt.hcl`in this folder has nothing but include for a parent dir. And the root config file has `remote_state` block that generates an "S3" backend.

```
terragrunt --version
terragrunt version v0.26.7
```

```
terraform --version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.20.0
```

What I ultimately want to achieve is to run `terraform validate` for all directories with terraform stacks that we have. 
I thought I could use `terragrunt validate-all` but I don't know how to pass init arguments for it to use, like `-get=true -backend=false`. I do not want it to talk to S3 at all.

Any help here would be appreciated.

**Comment by yorinasub17** [comment]
This is terragrunt's feature to auto create the bucket from the [remote_state block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state), and currently there is no way to disable that from the CLI. Terragrunt intentionally does not do any parsing of terraform args to make sure that features are enabled/disabled independently (hence, why we have those `--terragrunt-*` flags).

A workaround is to disable it in the config using the `disable_init` flag on the `remote_state` block. If you want to make that a toggle, you can use conditional logic with [get_env](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_env) to make that work.

> I thought I could use terragrunt validate-all but I don't know how to pass init arguments for it to use, like -get=true -backend=false. I do not want it to talk to S3 at all.

Similar to above suggestion, you can use `get_env` to toggle conditionals that affect the `extra_arguments` setting on the [terraform](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform) block.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
