### ISSUE TITLE
Constant reinitialization with Terraform 14

### ISSUE THREAD

**Issue by whoracle** [gruntwork-io/terragrunt#1464]
Running terraform 14.2 and terragrunt 0.26.7 on Archlinux. Terragrunt keeps running terraform init on every command, even between two plans back-to-back. Terraform by itself does not exhibit this behaviour, but I noticed that TF14 writes a .teraform.lock.hcl in the directory with the following (partially redacted, since I don't know what it encodes) content:

```[user@machine ~/tfkubernetes ] cat .terraform.lock.hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/kubernetes" {
  version     = "1.13.3"
  constraints = "1.13.3"
  hashes = [
    "h1:A_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
    "zh:SOME_DIFFERENT_HASH",
  ]
}
```

This file is not there on TF13.5, so maybe something changed there.

**Comment by tinder-tder** [comment]
it has been brought up
https://github.com/gruntwork-io/terragrunt/pull/1459

**Comment by whoracle** [comment]
Ah, so my search-fu was weak. I'll close this then. Thanks for the heads-up!
