### ISSUE TITLE
Assume role error while working with multiple accounts

### ISSUE THREAD

**Issue by abhinav10kaushik** [gruntwork-io/terragrunt#1465]
Hi, I'm trying to create a private host zone which needs to have a vpc associated from different account. But I'm getting the 
`Error: error configuring Terraform AWS Provider: IAM Role (arn:aws:iam::{account-2-id}:role/myrole) cannot be assumed` 
and 
`Error: NoCredentialProviders: no valid providers in chain. Deprecated`

There are two providers being used for two different aws accounts.

Default aws provider is picked from the terragrunt config along with the `iam_role` in the terragrunt config which looks like this

```
generate "provider" {
  path      = "provider.tf"
  contents  = <<EOF
     provider "aws" {
             region = "${local.aws_region}"
            }
         EOF
  }

iam_role = "arn:aws:iam::${local.account_id}:role/${local.role_name}" 
```

The source terraform module has one additional aws provider to associate the vpc from different account (account-2) to the private host zone.

``` 
provider "aws" {
  alias = "remote_account"
  region = "ap-southeast-2"
  assume_role {
    role_arn = "arn:aws:iam::${var.remote_account_id}:role/myrole"
  }
} 
```

This provider config is being used to associate the vpc of different account in `aws_route53_zone_association` resource. 

Rest of the resources i.e. `aws_route53_zone` , `aws_route53_vpc_association_authorization` , `and aws_route53_record` are using the provider that is set in terragrunt config.

I tried doing the same thing directly in terraform, by putting both the provider configs to assume their respective roles, and that worked. But similar thing is not working in terragrunt.

#### Terraform version 
14.2

#### Terragrunt Version
26.7

### Logs: 

``` 
INFO] TGENV_VERSION is 0.26.7
[terragrunt] [account-1/route53-hosted-zone] 2020/12/10 15:03:37 Running command: terraform --version
[terragrunt] 2020/12/10 15:03:38 Terraform version: 0.14.2
[terragrunt] 2020/12/10 15:03:38 Reading Terragrunt config file at account-1/route53-hosted-zone/terragrunt.hcl
[terragrunt] 2020/12/10 15:03:38 Assuming IAM role arn:aws:iam::{account-1-id}:role/myrole
[terragrunt] 2020/12/10 15:03:39 WARNING: no double-slash (//) found in source URL private-repo-souce-url.git. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2020/12/10 15:03:39 Terraform files in account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6 are up to date. Will not download again.
[terragrunt] 2020/12/10 15:03:39 Copying files from account-1/route53-hosted-zone into account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6
[terragrunt] 2020/12/10 15:03:39 Setting working directory to account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6
[terragrunt] 2020/12/10 15:03:39 The file path account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6/provider.tf already exists, but was a previously generated file by terragrunt. Since if_exists for code generation is set to "overwrite_terragrunt", regenerating file.
[terragrunt] 2020/12/10 15:03:39 Generated file account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6/provider.tf.
[terragrunt] 2020/12/10 15:03:39 The file path account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6/backend.tf already exists, but was a previously generated file by terragrunt. Since if_exists for code generation is set to "overwrite_terragrunt", regenerating file.
[terragrunt] 2020/12/10 15:03:39 Generated file account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6/backend.tf.
[terragrunt] 2020/12/10 15:03:39 Debug mode requested: generating debug file terragrunt-debug.tfvars.json in working dir account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6
[terragrunt] 2020/12/10 15:03:39 Variables passed to terraform are located in "account-1/route53-hosted-zone/terragrunt-debug.tfvars.json"
[terragrunt] 2020/12/10 15:03:39 Run this command to replicate how terraform was invoked:
[terragrunt] 2020/12/10 15:03:39 	terraform plan -var-file="account-1/route53-hosted-zone/terragrunt-debug.tfvars.json" "account-1/route53-hosted-zone/.terragrunt-cache/k8s7dtviykgbcyk8vhkfjIHIKDS&U/tfsdf6sd5f6776sd6f5rcs6dg6gcs6"
[terragrunt] [account-1/route53-hosted-zone] 2020/12/10 15:03:40 Running command: terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v3.20.0...
- Installed hashicorp/aws v3.20.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2020/12/10 15:03:50 Running command: terraform plan

Error: error configuring Terraform AWS Provider: IAM Role (arn:aws:iam::{account-2-id}:role/myrole) cannot be assumed.

There are a number of possible causes of this - the most common are:
  * The credentials used in order to assume the role are invalid
  * The credentials do not have appropriate permission to assume the role
  * The role ARN is not valid

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

[terragrunt] 2020/12/10 15:03:58 Hit multiple errors:
exit status 1 
```

**Comment by yorinasub17** [comment]
Based on your configuration, the assume role chain is:

```
CURRENT_CREDS_IN_SHELL
===assume role====> arn:aws:iam::${local.account_id}:role/${local.role_name} (this configures `provider.aws`)
    ====assume role====> arn:aws:iam::${var.remote_account_id}:role/myrole
```

Does your role `local.role_name` have the necessary permissions to do the assume role call to `myrole`?

If not and you want to assume the role from `CURRENT_CREDS_IN_SHELL`, then you will want to have terraform assume the `local.role_name` role in the provider, as opposed to managing that assume in terragrunt with `iam_role` attribute.

**Comment by abhinav10kaushik** [comment]
Roles and Accounts:

role A - account A ( all assumes initiates from here)

role B - account B

```
    CURRENT_CREDS_IN_SHELL
B   ===assume role====> arn:aws:iam::${account-B}:role/role-B (this configures `provider.aws`)
A      ====assume role====> arn:aws:iam::${account-A}:role/myrole-A      
```

1. role A and role B, both roles have administrator access. 
2. role A is in the source authentication account (account A) of the credentials and all assume roles to all other accounts happen from this one account.

#### In other words:

I'm a user in account-A and there is a role in account-A, role-A. I can assume this role.

I can assume role-B in account-B using account-A's credentials as well.

role A can assume role B but vice-versa not possible (we want to manage all roles one account).

Both the roles, role-A and role-B, have Administrator access.

----------------------------------------------------------------------------------------------------------------------------

#### My opinion:
 I think what's happening that terragrunt starts with assuming A and then A assumes B, which works because A is in the source account . But when it starts with B and B assumes A, it won't work because it is not allowed otherwise it will create a loop.

I would expect it to create the AWS resources by assuming their corresponding roles through their respective providers, such as, my user assume role B to create resources which use the default provider.tf.
And for the resources attached with the alternative (secondary) provider, again my user should assume role A to create them.

And I think terraform works the same way as well, that's why I don't face this issue in terraform.



#### Terraform Code (this works)

```
# Default provider
provider "aws"{
  region = "ap-southeast-2"
  assume_role {
  role_arn = "arn:aws:iam::{account-B}:role/{role-B}"
  }
}

# secondary account provider
provider "aws" {
  alias = "secondary_account"
  region = "ap-southeast-2"
  assume_role {
  role_arn = "arn:aws:iam::${account-A}:role/{role-A}"
  }
}

# Private hosted zone
resource "aws_route53_zone" "hosted_zone" {
    name = var.zone_name
    dynamic "vpc" {
      for_each = var.vpc
      content {
        vpc_id     = vpc.value["vpc_id"]
        vpc_region = vpc.value["region"]
      }
    }
  }

# Authorise cross-account vpcs to be associated with this hosted zone
resource "aws_route53_vpc_association_authorization" "vpc_association_authorization" {
  count   = length(var.secondary_vpc_id)
  vpc_id  = var.secondary_vpc_id[count.index]
  zone_id = aws_route53_zone.hosted_zone.zone_id
  depends_on = [ aws_route53_zone.hosted_zone ]
}

# Association of the secondary_vpc to private hosted zone
resource "aws_route53_zone_association" "zone_association" {

  provider = aws.secondary_account

  count   = length(var.secondary_vpc_id)
  vpc_id  = var.secondary_vpc_id[count.index]
  zone_id = aws_route53_zone.hosted_zone.zone_id
  vpc_region = var.region
  depends_on = [ aws_route53_vpc_association_authorization.vpc_association_authorization ]
}

```

**Comment by yorinasub17** [comment]
> I think what's happening that terragrunt starts with assuming A and then A assumes B, which works because A is in the source account . But when it starts with B and B assumes A, it won't work because it is not allowed otherwise it will create a loop.

This is happening because you have the `iam_role` attribute configured in your terragrunt configuration. It will work exactly like terraform if you get rid of that.

I am assuming you have this because you want terragrunt to assume a role during state bucket creation. You can avoid that by adding the relevant parameter to the `remote_state` config (https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state).

**Comment by abhinav10kaushik** [comment]
Actually I did get rid of that main  `iam_role` attribute in main config and ran using AWS_PROFILE  of account-B but I have been getting the same error.

**Comment by kkirpichnikov** [comment]
@abhinav10kaushik not sure if this is still relevant but anyway
It seems that I was able to find a solution to this problem. I used this as a reference 
[Why did I receive an "AccessDenied" or "Invalid information" error trying to assume a cross-account IAM role?](https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-error/)
First step 
`role A` config - `account A`
You would need to create a policy that will allow a role to assume the target role, like `role B`
policy config that needs to be assigned to `role A` in the `account A`
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PermissionToAssumeRoleB",
      "Effect": "Allow",
      "Action": "sts:AssumeRole",
      "Resource": "arn:aws:iam::AWS_ACCOUNT_B:role/ROLE_TO_ASSUME"
    }
  ]
}
```

`role B` config - `account B`
Assign a policy to this role that you need and add a `Trust relationships` config
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::AWS_ACCOUNT_A:role/role_A"
                ]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```
Now you should be able to do something like this
It will use the default role that you exported for Terragrunt
```export TERRAGRUNT_IAM_ROLE="arn:aws:iam::AWS_ACCOUNT_A:role/role_A"```
```hcl
resource "aws_organizations_account" "this" {
  name                       = var.name
  email                      = var.email
  iam_user_access_to_billing = var.iam_user_access_to_billing

  tags      = var.tags
  parent_id = var.parent_id
}
```

This will assume a role from the `account B` and creates some stuff in that `account B`
```hcl
provider "aws" {
  alias  = "admin"
  region = var.region
  assume_role {
    role_arn = "arn:aws:iam::AWS_ACCOUNT_B:role/ROLE_TO_ASSUME"
  }
}

module "aws_config" {
  providers = { aws = aws.admin }
  source    = "lacework/config/aws"
  version   = "~> 0.7.1"

  use_existing_iam_role = true
}
```
