### ISSUE TITLE
Programatically configure --terragrunt-source

### ISSUE THREAD

**Issue by AlmogCohen** [gruntwork-io/terragrunt#1472]
I have just started changing our infra to use terragrunt on top of our existing terraform. At the moment, I'd like to work fully locally with all of our terraform modules that are found in another folder.

I started using the double slash together with the `--terragrunt-source` CLI option. The problem is that I have to manually input the `--terragrunt-source` for every time I run `terragrunt init`, otherwise many errors occur. I'm trying to see if there was a way to specify this terragrunt source folder in the root `hcl` file....and never specify this again via the CLI. In that way, this whole structure would work for other engineers as well without the need for them to know specifically how terragrunt should be used.

Is it possible to somehow configure terragrunt to work like that? Or a programmatic way to specify this as an environment variable as part of the `hcl` file? I couldn't find anyway to do this.

The best I came up with is adding this to the root `terragrunt.hcl` file 
```
 terraform {
  # point to the local module folder for all commands
  extra_arguments "terragrunt_source" {
    commands = [
      "init",
      "apply",
      "refresh",
      "import",
      "plan",
      "taint",
      "untaint"
    ]

    env_vars = {
      TERRAGRUNT_SOURCE = "${path_relative_from_include()}/../modules"
    }
  }
}
```
But I guess it didn't work because these become the extra_arguments for the `terraform` command, rather than the `terragrunt` command.

Your help would be much appreciated!

**Comment by yorinasub17** [comment]
Just to make sure I understand, is the desired behavior to DRY the path before `//` in the `source` attribute of the `terraform` block in your `terragrunt.hcl` configs?

If so, I believe you can define a file called `module_path.hcl` in your repo root that has the following:

```hcl
locals {
  modules_dir = "${get_terragrunt_dir()}/modules"
}
```

And then in your child config:

```hcl
locals {
  module_path_config = read_terragrunt_config(find_in_parent_folders("module_path.hcl"))
}

terraform {
  source = "${local.module_path_config}//path/to/submodule"
}
```

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
