### ISSUE TITLE
Terragrunt cache directory not created/used

### ISSUE THREAD

**Issue by eyalzek** [gruntwork-io/terragrunt#1475]
I use terragrunt and terraform in 2 separate projects, in one of them terragrunt creates a cache dir (`.terragrunt-cache`) and stores all provider configuration/out plan/etc in it. In the other project, the cache dir is not created, provider config goes into `.terraform` as if terragrunt is not used, and generated configuration/out plans go into the current working directory. My flow of using terragrunt is similar in both projects, so is the structure and configuration within `terragrunt.hcl`. In one project I'm using only the `github` and `random` providers, in the other one `aws`, `google`, `google-beta`, `random`, `null` and `template`. 

This wasn't really a problem until now, mostly confusing, but now with TF v0.14 I get `.terraform.lock.hcl` files generated properly so I can commit them in only one of the projects (even though this is technically not yet supported by terragrunt). Also files created by terragrunt `generate` blocks need to be gitignored instead of being generated in the cache directory...

Can anyone shed light on what might cause this difference in behavior? I'll gladly supply extra information upon request.

**Comment by yorinasub17** [comment]
Is there any difference in where the terraform source code is stored across the two projects? One case I know that will cause terragrunt to avoid creating `.terragrunt-cache` is if you are using local paths in `terraform.source`. When the `source` attribute is a local path as opposed to remote (e.g., git), then terragrunt will cd straight into that path instead of cloning a copy in `.terragrunt-cache`.

**Comment by eyalzek** [comment]
> Is there any difference in where the terraform source code is stored across the two projects? One case I know that will cause terragrunt to avoid creating `.terragrunt-cache` is if you are using local paths in `terraform.source`. When the `source` attribute is a local path as opposed to remote (e.g., git), then terragrunt will cd straight into that path instead of cloning a copy in `.terragrunt-cache`.

Hmm, in the repo where the cache dir is generated I have a `terraform.source` field, but it's local:
`source = "../${path_relative_from_include()}//modules/organization"`

and on the other one there is no `source` at all... Can this be the cause?

**Comment by eyalzek** [comment]
Thanks for the workaround. I feel like this is slightly confusing, as I had expected to have this cache dir creates (and all files created by `generate` blocks, output plans and provider to be in it). I'm wondering if it would make sense to state this somewhere in the documentation - or alternatively always create a terragrunt cache directory, since the user is indeed using terragrunt :)

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
