### ISSUE TITLE
Permision Denied S3 with admin user

### ISSUE THREAD

**Issue by DMEvanCT** [gruntwork-io/terragrunt#1477]
Here is the terragrunt hcl.  This was for a demo so I am not worried about data

# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "terraform-state-dev"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
    bucket         = "terraform-dmitdemo-dev"
  }
}

Here is the error I get. 

1.) The user is an admin though so I am not sure how it is denied. 
2.) Terragrunt created the S3 bucket to begin with. 

Error refreshing state: AccessDenied: Access Denied
        status code: 403, request id: 54448C00919BBEB4, host id: xXpmDCZDk/GmqQhoyraaQdLIBO1377BmYuV76+2XQ1nt5cBMhz7mWlWtZhhd4pja1KJaacswZBs=
[terragrunt] 2021/01/02 23:15:43 Hit multiple errors:

**Comment by yorinasub17** [comment]
This is a bit hard to debug without seeing the terragrunt config (what you have in `terragrunt.hcl`, `remote_state` block), but I would sanity check your account config to make sure the bucket is in the right account.

**Comment by fliphess** [comment]
I'm having the same issue after upgrading terragrunt from `0.23.38` to `0.27.3`: The bucket is in the same flat account as before and was created by the same user with the admin role (we don't use organisations, terraform get's it's api credentials from the environment) 

My remote_state block is: 
```
remote_state {
  backend = "s3"
  config = {
    bucket         = "some-name-tfstate"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "eu-central-1"
    encrypt        = true
    dynamodb_table = "terraform-some-name-tflock"

    skip_metadata_api_check     = true
    skip_region_validation            = true
    skip_credentials_validation.   = true
  }
}
```

**Comment by fliphess** [comment]
Found my issue which was not related to terragrunt: some idiot (me) disabled the wrong api credentials....

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
