### ISSUE TITLE
Terragrunt runtime exception

### ISSUE THREAD

**Issue by kahyin** [gruntwork-io/terragrunt#1478]
Terraform version: 0.14.3
Terragrunt version: 0.26.7
OS: Windows 10 Pro 64bit

Hello,

I am experiencing a weird Terragrunt runtime error. I've tested this on two different machines. My desktop PC is working fine but I am getting an exception when I run terragrunt on my laptop. I've pasted a snippet of the exception below. Just wondering if anyone has encountered this before?

Both my desktop and laptop are on Windows 10 Pro 64 bit.

```
C:\terragrunt>terragrunt.exe
Exception 0xc0000005 0x0 0x7ffe0e650fff 0x285c0000
PC=0x285c0000

runtime: unknown pc 0x285c0000
stack: frame={sp:0x2d6e820, fp:0x0} stack=[0x0,0x2d6ff00)
0000000002d6e720:  0000000002d6e768  0000000002d6e790
0000000002d6e730:  0000000002d6e758  0000000002d6e750
0000000002d6e740:  0000000002d6e754  0000000002eb0000
0000000002d6e750:  0000000000000000  0000000000000000
0000000002d6e760:  0000000000000000  0000000000000005
0000000002d6e770:  0000000002d6e8b8  00007ffe0c3fb35f
```

**Comment by yorinasub17** [comment]
This looks like the binary is for the wrong architecture/OS. Can you try downloading from the following link and try again? https://github.com/gruntwork-io/terragrunt/releases/download/v0.26.7/terragrunt_windows_amd64.exe

If it still fails, then the build process must have failed and I will investigate further.

**Comment by kahyin** [comment]
I've just downloaded it again from that link and it works on my laptop now.

Thanks!

**Comment by yorinasub17** [comment]
Glad to hear it worked!
