### ISSUE TITLE
DRY coding for dependency

### ISSUE THREAD

**Issue by r32rtb** [gruntwork-io/terragrunt#1480]
I'm working on a deployment and would like to utilize a region.yml as a locals input to reference across different dependency outputs based on region.  This way I only have to adjust one file.  Is there an appropriate way to combine a dependency outputs with a local.region_vars to determine the appropriate input?

locals {
  region_vars = yamldecode(file(find_in_parent_folders("region.yml")))
}
dependency "baseline_account_key" {
  config_path = "../../../baseline-account-key"
}
inputs = {
    key_arn         = dependency.baseline_account_key.outputs.key_arn.${local.region_vars.aws_region}
}

**Comment by yorinasub17** [comment]
You can also use `[]`:

```hcl
key_arn = dependency.baseline_account_key.outputs.key_arns[local.region_vars.aws_region]
```

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
