### ISSUE TITLE
Add get_workspace() function

### ISSUE THREAD

**Issue by mattparkes** [gruntwork-io/terragrunt#1481]
I wanted to use `required_var_files` to dynamically load in a tfvars file based on the workspace and I expected Terragrunt to be able to do this easily, but I was surprised by the lack of a `get_workspace()` function.

What I ended up doing was:

```
    required_var_files = [
        "${ join("/", ["${get_parent_terragrunt_dir()}", "configuration", "${file("${get_parent_terragrunt_dir()}/.terraform/environment")}"]) }.tfvars"
    ]
```

This makes use of the `.terraform/environment` file which Terraform automatically creates when you change workspace.

So whilst this works, a `get_workspace()` function would be a nice shorthand to the above (or `run_cmd("terraform" "workspace" "show")` which is also an option, albeit a bit slow).

**Comment by brikis98** [comment]
To make sure I understand your use case: you're trying to look up the name of the currently selected workspace so that you can pass different `.tfvars` files to different workspaces?

FWIW, Terragrunt doesn't have much (if any) support for workspaces, as, in many ways, it provides an alternative to using workspaces. The Terragrunt approach is to make environments visible through files/folders on the file system, rather than hiding them behind commands.

**Comment by mattparkes** [comment]
Yeah that's exactly our use case.

We have a pretty mature native Terraform project that's several years old which has been using this pattern of feeding in a tfvars file per workspace (with our own wrapper scripts) but we want to move over to how Terragrunt way of doing things.

As a first step towards Terragrunt, we wanted to implement what we already have (which I have done with the above `required_var_files` block).

If this request is not something you would consider idiomatic to Terragrunt then I'm happy to close it since I have a workaround for now, I just naively assumed there would be such a function when I skimmed the function list originally.

**Comment by brikis98** [comment]
I think given the very limited use of workspaces with Terragrunt, it's probably best to skip this function for now, as you have a workaround. If, in the future, there are compelling reasons to do lots of workspace stuff with Terragrunt, we can revisit. Thanks!
