### ISSUE TITLE
Replace multierror implementation with go-multierror

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/terragrunt#1482]
Terragrunt currently implements its own [multierror package](https://github.com/gruntwork-io/terragrunt/blob/master/errors/multierror.go). We should scrap this and use [go-multierror](https://github.com/hashicorp/go-multierror) instead.

**Comment by derom** [comment]
Hi @infraredgirl I think this issue is resolved

**Comment by infraredgirl** [comment]
Yep, that's right, many thanks for your contribution!

Closing this issue.
