### ISSUE TITLE
How to use pipe or redirect on hooks commands?

### ISSUE THREAD

**Issue by bcochofel** [gruntwork-io/terragrunt#1491]
I'm trying to execute "terraform show -no-color -json ..." to generate json file so I can parse it with contest after each plan command.

I have this piece of code

```
terraform {
  extra_arguments "plan_vars" {
    commands = [
      "plan",
    ]

    arguments = [
      "-out",
      "plan.tfplan",
    ]
  }

  extra_arguments "apply_vars" {
    commands = [
      "apply",
    ]

    arguments = [
      "-auto-approve",
      "-input=false",
      "plan.tfplan",
    ]
  }

  after_hook "tflint" {
    commands = ["validate"]
    execute  = ["tflint", "--module", "."]
  }

  after_hook "show" {
    commands = ["plan"]
    execute  = ["terraform", "show", "-no-color", "-json", "plan.tfplan", "|", "tee", "plan.json"]
  }

  after_hook "debug" {
    commands = ["plan"]
    execute  = ["ls", "-al"]
  }
}
```

but the terraform show after_hook is failing because of the '|' (I guess). I can run the hook without that last part.

How can I use the pipe (or redirect) on the hook?

**Comment by yorinasub17** [comment]
Unfortunately we don't run the commands through a shell. The best way to achieve this is to create a script and call out to that.

**Comment by bcochofel** [comment]
Thanks @yorinasub17 gonna use a wrapper script to solve this

**Comment by fool65c** [comment]
I was able to work around this by calling out to /bin/bash -c and passing a string

```terraform
terraform {
  ...
  after_hook "after_hook" {
    commands     = ["apply"]
    execute      = ["/bin/bash", "-c", "echo test | grep t"]
    run_on_error = false
  }
}
```
