### ISSUE TITLE
Getting type issues when passing outputs between modules

### ISSUE THREAD

**Issue by tluzon-digibank** [gruntwork-io/terragrunt#1492]
I'm getting this:
Error: Iteration over non-iterable value

  on locals.tf line 3, in locals:
   2:   routes = flatten([
   3:     for table in var.private_route_table_ids : [
   4:       for route in var.route_cidr : {
   5:         table = table
   6:         route = route
   7:       }
   8:     ]
   9:   ])
    |----------------
    | var.private_route_table_ids is "[\"rtb-00xxxxxxxxxxxxxxx\",\"rtb-06yyyyyyyyyyyyyyy\",\"rtb-01zzzzzzzzzzzzzzzz\"]"

A value of type string cannot be used as the collection in a 'for' expression.

when var.private_route_table_ids is sent by dependency output.
it takes the list of strings and puts these backslashes which makes it a string.
this worked when using terraform_remote_state and pulling the outputs using TF.

Any way out of this?

**Comment by tluzon-digibank** [comment]
Github removed the backslashes, anyhow there are backslashes before each inner quote sign

**Comment by brikis98** [comment]
Could you put your code in a [fenced code block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks) to make the code more readable, add syntax highlighting, and allow characters like backslashes?

**Comment by tluzon-digibank** [comment]
I've just encountered a simpler example of the same issue;
I'm sending an input value which is a list of strings and TF gets it as a string because of the backslashes.
This is from the terragrunt.hcl file:
`inputs = {
  allowed_cidrs = ["0.0.0.0/0"]
}`

And this is the error I get:

```Error: Incorrect attribute value type

  on main.tf line 53, in resource "aws_security_group_rule" "rule":
  53:   cidr_blocks       = var.allowed_cidrs
    |----------------
    | var.allowed_cidrs is "[\"0.0.0.0/0\"]"

Inappropriate value for attribute "cidr_blocks": list of string required.
```

**Comment by yorinasub17** [comment]
Do you have a type annotation (e.g., `type = list(string)`) in the terraform code for the variable (`allowed_cidrs`)? Unlike a `tfvars` file, terragrunt inputs are passed through via env vars using json encoding, and without the `type` annotation on terraform side, terraform defaults to parsing it as string.

**Comment by tluzon-digibank** [comment]
I don't have a type set.
Sounds like this is the issue.
Thank you!
