### ISSUE TITLE
terraform_binary is ignored starting 0.23.35

### ISSUE THREAD

**Issue by jan-cipa** [gruntwork-io/terragrunt#1496]
Hi,
I've found that directive [terraform_binary](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_binary) is being ignored started from version 0.23.35

example terragrunt.hcl
`terraform_binary = "terraform-latest"`

0.23.34 works as expected.

```
$ /usr/libexec/terragrunt/0.23.34/terragrunt init
[terragrunt] [2021/01/18 19:33:27 Running command: terraform-latest --version
[terragrunt]  2021/01/18 19:33:27 Terraform version: 0.13.6
```

0.23.35 calls terraform instead of terraform-latest
```
$ /usr/libexec/terragrunt/0.23.35/terragrunt init
[terragrunt] 2021/01/18 19:40:18 Generated file /mnt/tmp/008393736/_backend.tf.
[terragrunt] 2021/01/18 19:40:18 Running command: terraform init
```

**Comment by jan-cipa** [comment]
https://github.com/gruntwork-io/terragrunt/compare/v0.23.34...v0.23.35

**Comment by jan-cipa** [comment]
@yorinasub17
could you please check?

**Comment by pulchart** [comment]
Hello, this issue is fixed by https://github.com/gruntwork-io/terragrunt/pull/1813

**Comment by infraredgirl** [comment]
Thanks for closing the loop! I'll close this issue but feel free to reopen if you still experience problems.
