### ISSUE TITLE
Changes to .terragrunt file aren't picked up after initial terragrunt run.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terragrunt#15]
Currently, terragrunt configures your localdev's terraform remote state with [this code](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state.go#L48-L63).

The problem is that this doesn't guarantee that the contents of the `.terragrunt` file match the current remote state configuration. This particularly becomes an issue when I've made a mistake in the `.terragrunt` file, correct it, and re-run terragrunt expecting terragrunt to pick up the change.

We should consider creating a hash of the `.terragrunt` file and writing it to the `.terraform` folder so that terragrunt can check whether any value in the `.terragrunt` file has changed, and if so, re-execute `terraform remote config`.

**Comment by fortytw2** [comment]
Could this also be fixed by reloading the `.terragrunt` every time the command is run?

**Comment by josh-padnick** [comment]
@fortytw2 Thanks for the upvote and comment! 

Parsing `.terragrunt` and executing `terraform remote config` on every run of Terragrunt would solve the problem, but I'd prefer to avoid running `terraform remote config` on every single Terraform run in case that causes side effects.

For example, Terraform expects the `terraform remote config` command to be run only once, so the test suite for Terraform won't necessarily capture subtle bugs that arise from running this every time.

Also, probably the cleanest way to apply a new `.terragrunt` configuration is to completely delete the `.terraform` folder and start from scratch, but we certainly wouldn't want to do that on every run b/c of all the extra bandwidth, there may be multiple modules to download, etc.

**Comment by fortytw2** [comment]
hmmmm - sounds like some middle ground is needed then, instead of going for a more complex solution (hashing `.terragrunt`), it should be pretty easy to add a `terragrunt reload` command that just re-runs `terraform remote config` when you know you've changed it

**Comment by brikis98** [comment]
I like the idea of hashing `.terragrunt`, but I'm not keen on writing and managing extra files to maintain that hash. There is probably a fairly simple bug in [this code](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state.go#L52) that just needs a second look.

Whatever solution we go with, the `terragrunt reload` command sounds like a good idea to have as a backup.
