### ISSUE TITLE
GLOBAL OPTIONS cli flags not working

### ISSUE THREAD

**Issue by tamsky** [gruntwork-io/terragrunt#150]
Observation:
```
# /usr/local/bin/terragrunt --terragrunt-source-update plan
Incorrect Usage. flag provided but not defined: -terragrunt-source-update
[snip]
VERSION:
   v0.10.3
```

Expectation:
This should work without error:
```
# /usr/local/bin/terragrunt --terragrunt-source-update plan
```

As far as I can tell, the above error originates via:
https://github.com/urfave/cli/blob/347a9884a87374d000eec7e6445a34487c1f4a2b/command.go#L167
and
https://golang.org/src/flag/flag.go#L871

Not sure why all these flags are not working.

**Comment by brikis98** [comment]
Put them after the command (after `plan`). It's a limitation of the CLI library we're using.

**Comment by tamsky** [comment]
Super.  Thanks!
