### ISSUE TITLE
Terragrunt doesn't save .terraform.lock.hcl from `providers lock`

### ISSUE THREAD

**Issue by ZymoticB** [gruntwork-io/terragrunt#1500]
When terragrunt configs may be applied from different platforms, you can see spurious updates to lock files after they have been checked in. To remedy this, you can use the `terraform providers lock` command to target all platforms you support https://www.terraform.io/docs/commands/providers/lock.html#specifying-target-platforms

Currently, terragrunt does not copy the `.terraform.lock.hcl` file when you run `terragrunt providers lock ...`

**Comment by brikis98** [comment]
Could you share the exact commands you ran and the full log output?
