### ISSUE TITLE
--terragrunt-debug dosen't work since v0.27.0

### ISSUE THREAD

**Issue by dmitriy-kharchenko** [gruntwork-io/terragrunt#1502]
Hello folks!

In terragrunt 0.27.1 doesn't work --terragrunt-debug option. Files terragrunt-debug.* aren't created.

**Comment by dmitriy-kharchenko** [comment]
And with `terragrunt apply` doesn't work too.

**Comment by yorinasub17** [comment]
Ahhh yes I confirmed it is a regression. Will look into this today.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.27.2 (binaries should show up shortly)
