### ISSUE TITLE
Structured Logging for Terragrunt Logs

### ISSUE THREAD

**Issue by josuevalverde12** [gruntwork-io/terragrunt#1506]
Hello all! Currently Terragrunt logs output in an unstructured format, for example:
```
[terragrunt] [/Users/josue.valverde/Code/super-cool-terragrunt-project] 2021/01/21 12:39:36 Generated file /Users/josue.valverde/Code/super-cool-terragrunt-project/.terragrunt-cache/12YoLO/bAggiNS42/super-cool-terragrunt-project/backend.tf.
```

To improve readability and log searching through external log aggregators or monitoring systems like DataDog and Honeycomb.io, would it be possible to structure these? For example, having the above structured to be:
```
{
  "runner" : "terragrunt",
  "datetime" : "2021/01/21 12:39:36",
  "action" : "Generated file",
  "message" : "/Users/josue.valverde/Code/super-cool-terragrunt-project/.terragrunt-cache/12YoLO/bAggiNS42/super-cool-terragrunt-project/backend.tf."
}
```

I'm not sure how easy it'd be to split the logs by attributes, but it would make it so much easier to read these logs even while running in the CLI, as it would be clearer what is happening with lines of JSON-formatted logs:
```
{...}
{...}
{...}
```

Thanks!

Somewhat related logging feature: https://github.com/gruntwork-io/terragrunt/issues/662

**Comment by yorinasub17** [comment]
We're working on overhauling terragrunt to use [logrus](https://github.com/Sirupsen/logrus) soon as part of resolving https://github.com/gruntwork-io/terragrunt/issues/662, and then it will be easier to implement this by swapping the logrus formatter.
