### ISSUE TITLE
Question: How to import to module using terragrunt?

### ISSUE THREAD

**Issue by christiansaiki** [gruntwork-io/terragrunt#1511]
Hey guys I've created this [question in SO](https://stackoverflow.com/questions/65878969/how-to-import-to-module-using-terragrunt)

I'm wondering if this is the correct approach, to import to module. Because if I import to resource it just works, but I'm wondering what's the difference between these two approaches and what's the correct one.

Thanks in advance.

**Comment by brikis98** [comment]
I think this is a Terraform knowledge question, not a Terragrunt question. I added a comment on SO to help.
