### ISSUE TITLE
Destruction behaviour of External dependent resources in terragrunt destroy-all command with non-interactive mode flag is improper

### ISSUE THREAD

**Issue by pandu-bhojaraj-mf** [gruntwork-io/terragrunt#1518]
External dependent resource 1 which requires independent resources(EC2/VPC/Lambda) to be destroyed first:

I have a _S3_ resource created by running "**terragrunt apply-all --terragrunt-non-interactive --terragrunt-source-update**" command from below path

                   /infrastructure-vertica-test/qe/_global/

External dependent resource 2 which requires independent resources(EC2/VPC/Lambda) to be destroyed first::

I have a _SNS_ resource created by running "**terragrunt apply-all --terragrunt-non-interactive --terragrunt-source-update**" command from below path

                   /infrastructure-vertica-test/qe/us-east-2/_global

Other resources which can be created and destroyed once _S3_ and _SNS_ are available

I have a So many other resources(_Lambda/IAM/VPC/EC2_ etc..) created by running "**terragrunt apply-all --terragrunt-non-interactive --terragrunt-source-update --terragrunt-download-dir /opt/cache**" command from below path

                  /infrastructure-vertica-test/qe/us-east-2/tenant/iam-services

Now After all services are up and running

If i run terragrunt destroy-all command in **NON-INTERACTIVE** mode using **terragrunt destroy-all --terragrunt-non-interactive --terragrunt-source-update --terragrunt-download-dir /opt/cache**  command from below location then **ONLY** other resources(_Lambda/IAM/VPC/EC2_ etc..) are getting destroyed successfully 
**for non-interactive mode, all prompts should be taken as y which means all dependent resources should also get destroyed... but dependent resources are NOT getting destroyed**
 

                  /infrastructure-vertica-test/qe/us-east-2/tenant/iam-services

Please clarify why is terragrunt destroy-all command with non-interactive mode flag is not destroying external dependent resources

**Comment by sanjaythaire** [comment]
> In general, doing things outside of the working folder is counter intuitive as the behavior of `xxx-all` is to scope things down to the folder tree you are working from. Terragrunt tries to be conservative in its choices of actions for non-interactive mode, and one of the design principles there is that it is safe to automatically apply new infrastructure, but destroying should be done with caution. That's why it doesn't automatically destroy everything outside the folder tree even in non-interactive mode.
> 
> If you wish to do that, you can actually use [--terragrunt-include-external-dependencies](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-external-dependencies) instead.

@yorinasub17 Thanks for clarifying this. To avoid confusion, it will be better if the documentation of the “terragrunt-non-interactive” CLI option is updated here:
https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-non-interactive 

Currently, the above doc link simply says:
When passed in, don’t show interactive user prompts. This will default the answer **_for all prompts to ‘yes’._**

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered, and the docs update has already been made: https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-non-interactive. If there are any follow ups, please open a new ticket with the updated context. Thanks!
