### ISSUE TITLE
Proposal: Error hooks

### ISSUE THREAD

**Issue by Ben10k** [gruntwork-io/terragrunt#1522]
The idea behind error hooks is to execute arbitrary shell commands when a terraform command returns an error. 

Example syntax would be similar to `before_hook` and `after_hook` with required properties `commands` and `execute` and instead of `run_on_error` a different property `on_errors` would be required that would describe a list of errors on which should the hook run, described in the same manner as `retryable_errors`.

An example configuration that imports would run a shell script with `terraform import`:
```hcl
terraform {
  error_hook "import_resource" {
    commands  = ["apply"]
    execute   = ["./import_known_resource.sh"]
    on_errors = [
      "(?s).*A resource with the ID .* already exists.*",
    ]
  }
}
```

The idea behind this proposal is that there are some resources on terraform-providers that create an 'umbrella' resource which can create some child-resources on the cloud provider which are not being represented as a terraform resource. In some cases, the default child-resource configuration is ok, but when that resource needs to be modified, it becomes problematic.

One example of this would be an `azurerm` resource `azurerm_api_management` creates 2 `azurerm_api_management_product` instances which have one `azurerm_api_management_product_policy` each. The `product` can be accessed as `data` but the `product_policy` needs to be imported to state in order to be accessible from terraform.

**Comment by yorinasub17** [comment]
This seems reasonable! We're buried with other initiatives so most likely won't implement this any time soon, but PRs from the community are welcome!

**Comment by smitthakkar96** [comment]
@yorinasub17 @Ben10k anyone working on this? If not I can take this over

**Comment by smitthakkar96** [comment]
Instead of adding new type of hook wouldn't it be better to add `run_only_on_error` to existing hooks and we also add error message and exit code as env vars and let the script that gets executed by the hook decide what to do

**Comment by Ben10k** [comment]
> @yorinasub17 @Ben10k anyone working on this? If not I can take this over

@smitthakkar96 I did not have a chance to work on this, you can take over.

Although I am not sure if adding `run_only_on_error` instead of adding a new hook type is the way to go, as I believe it would increase both the complexity of terragrunt and the readability of the `terragrunt.hcl` configurations.

**Comment by smitthakkar96** [comment]
@Ben10k thanks for your response, your comment regarding complexity and readability makes sense. I have one more question, what will the ordering be like? Will after_hook with `run_on_error` execute first or `error_hook` execute first?

**Comment by rhoboat** [comment]
+1 to @smitthakkar96's question on ordering.
