### ISSUE TITLE
Creating new S3 backend is only possible with --terragrunt-log-level info

### ISSUE THREAD

**Issue by wiegandf** [gruntwork-io/terragrunt#1524]
I was wondering why my `terragrunt plan` didn't do anything for a module that should be stored in a new remote backend (s3).

It turned out that terragrunt 0.28 hides info logs from you - but in those logs you're asked if you want to create a new backend:
```
INFO[0001] Remote state S3 bucket xyz does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)
```
I was only able to see this with --terragrunt-log-level info.

It should only affect terragrunt >= 0.28.0.

**Comment by tkrille** [comment]
This also happens, when doing a `terragrunt run-all apply`. The confirmation message is not shown, because it is logged on `INFO` level. After setting `--terragrunt-log-level info` it is shown:

```
INFO[0000] Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

I think this message should be logged at `WARN` leven or even bypass the logger entirely.

**Comment by brikis98** [comment]
Oooh, good catch. We'll get this fixed.

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.2 a shot!

**Comment by tkrille** [comment]
I can see the confirmation message now without setting the log level. So this works. Thank you very much! :)

But I've noticed this: The message says:

```
Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

But there is no stack described above. Because it is logged at `INFO` and not shown with default settings :)

**Comment by brikis98** [comment]
Let's track that further in https://github.com/gruntwork-io/terragrunt/issues/1530
