### ISSUE TITLE
hclfmt to process also other *.hcl files

### ISSUE THREAD

**Issue by ChristophShyper** [gruntwork-io/terragrunt#1528]
Can `hclfmt` also format other config files with `.hcl` extension?
Currently I use a script that renames all `*.hcl` to `*.tf` and uses `terraform fmt` to fix them.

**Comment by kevcube** [comment]
for me, `hclfmt` correctly processes a file with the name `region.hcl`.

@ChristophShyper Can you describe WHY you need to rename your files and use `terraform fmt`?

**Comment by ChristophShyper** [comment]
But in documentation it says it only applies to `terragrunt.hcl` files. So maybe information should be corrected?

`terraform fmt` works only on `.tf`, `.tfvars`, etc. but not on `.hcl`, or does it now and I missed it in release notes?

**Comment by kevcube** [comment]
I just tested, `terraform fmt` did NOT work on my file which is `region.hcl`

But `terragrunt hclfmt` DID work. So yes, if the docs say that it only works on `terragrunt.hcl` then the docs are wrong.

**Comment by brikis98** [comment]
Ah, you're right, the docs do only mention `terragrunt.hcl` files: https://terragrunt.gruntwork.io/docs/reference/cli-options/#hclfmt. Is anyone up for a quick PR to fix that?

**Comment by ChristophShyper** [comment]
Would it be possible to add functionality to reformat all `.hcl` files in all subdirectories? 
I have a massive tree, hundreds of `terragrunt.hcl` modules with many additional configuration files.
Currently I'm using my [action-format-hcl](https://github.com/devops-infra/action-format-hcl) for it. But it's slow when dealing with amount of files I have.

**Comment by kromol** [comment]
@ChristophShyper running `terragrunt hclfmt` formats all `.hcl` files in all subdirectories recursively:
```
terragrunt hclfmt
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.29.7
INFO[0000] Formatting terragrunt.hcl files from the directory tree /projects/test. 
INFO[0000] Formatting /projects/test/infrastructure/tf/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/common/root.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/prod/sns/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/common/monitoring/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/dev/monitoring/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/dev/iam/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/int/monitoring/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/int/iam/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/int/sns/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/dev/sns/terragrunt.hcl 
INFO[0000] Formatting /projects/test/infrastructure/tf/common/sns/terragrunt.hcl 
```

**Comment by ChristophShyper** [comment]
@kromol Thanks. Confirming it works on `0.29.10` and is very quick.

But still documentation is stating something else https://terragrunt.gruntwork.io/docs/reference/cli-options/#hclfmt

**Comment by ChristophShyper** [comment]
All fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.30.1
Thanks a lot.
