### ISSUE TITLE
Default logging hides directory listing with run-all apply

### ISSUE THREAD

**Issue by apottere** [gruntwork-io/terragrunt#1530]
When running `terragrunt run-all apply`, with the default logging the directory names are hidden, but you're still prompted to confirm you want to operate on that set of directories.

```
$ terragrunt run-all apply
Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)
```

**Comment by brikis98** [comment]
Good point. We'll get this fixed.

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.6 a shot! New binaries should be published shortly.
