### ISSUE TITLE
Terragrunt v0.28.2 shows prompt in warn[default] and error log level for non-interractive run

### ISSUE THREAD

**Issue by ITD27M01** [gruntwork-io/terragrunt#1531]
Hi,

Thanks for the awesome  long awaited feature :)

v0.28.2 now shows the prompt in error log level:

For error log level:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/3703483/107011154-54372980-67a8-11eb-81be-ddd6afe3c42c.png">

For warn[default] log level
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/3703483/107011350-906a8a00-67a8-11eb-8353-e6a1132a136a.png">

And it doesn't show prompt in debug log level.

**Comment by brikis98** [comment]
Not sure I follow. Is the issue that the "stack described above" is not visible, as reported in https://github.com/gruntwork-io/terragrunt/issues/1530? Or is the issue that you can still see the "Are you sure you want to run..." prompt, even in `--non-interactive` mode?

**Comment by ITD27M01** [comment]
Hi,

The issue is that we can still see the "Are you sure you want to run..." prompt, even in --non-interactive mode.

**Comment by brikis98** [comment]
Understood, thanks. I've asked @amnk in #1541 to change prompts to `Debugf` messages if `--non-interactive` is set.

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.6 a shot! New binaries should be published shortly.
