### ISSUE TITLE
before and after hooks with the run-all command

### ISSUE THREAD

**Issue by bcochofel** [gruntwork-io/terragrunt#1532]
Hi, I'm using terragrunt version v0.28.2 and my after hooks don't seem to run when I use ```run-all plan```. Do I need to change something? They run when I execute just ```terragrunt plan```.

Thanks,
Bruno

**Comment by yorinasub17** [comment]
After investigating this (https://github.com/gruntwork-io/terragrunt/pull/1534), I was able to verify the hooks were running when using `run-all apply` or `apply-all`. Can you share a bit more info to help us debug this further?

- The `terragrunt.hcl` config with your hook commands
- Logs, or behavior that makes you think the hooks are not properly running

Thanks!

**Comment by bcochofel** [comment]
Hi @yorinasub17, here are the relevant parts:

```
terraform {
  extra_arguments "plan_vars" {
    commands = [
      "plan",
    ]

    arguments = [
      "-out",
      "plan.tfplan",
    ]
  }

  #  extra_arguments "apply_vars" {
  #    commands = [
  #      "apply",
  #    ]
  #
  #    arguments = [
  #      #        "-auto-approve",
  #      #        "-input=false",
  #      "plan.tfplan",
  #    ]
  #  }

  after_hook "tflint" {
    commands = ["validate"]
    execute  = ["tflint", "--module", "."]
  }

  after_hook "post_plan" {
    commands = ["plan"]
    execute  = ["bash", "${get_terragrunt_dir()}/${path_relative_from_include()}/../scripts/post_plan.sh", "plan.tfplan"]
  }
}
```

and the post_plan.sh

```
#!/bin/bash

# check number of arguments
if [ "$#" -ne 1 ]; then
    cat <<EOT
Usage: $0 FILENAME

FILENAME: terraform plan
EOT
    exit 1
fi

PLAN_FILE=$1
JSON_FILE=plan.json

# check if file exists
if [ ! -f "$PLAN_FILE" ]; then
    echo "Invalid filename ($PLAN_FILE)"
    exit 1
fi

terraform show -no-color -json $PLAN_FILE >$JSON_FILE
terraplanfeed $JSON_FILE -o azuredevops
```

basically I have some output when I run `plan` but got nothing (the output comes from the terraplanfeed tool) when I run `run-all plan`

**Comment by yorinasub17** [comment]
Ah this might be a bug in the log level transfer for `run-all`. Do you see the expected logs if you pass in `--terragrunt-log-level info` or `--terragrunt-log-level debug` to `run-all`?

**Comment by bcochofel** [comment]
Yes :-)

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.6 a shot! New binaries should be published shortly.
