### ISSUE TITLE
Problem with dependency

### ISSUE THREAD

**Issue by sd2020bs** [gruntwork-io/terragrunt#1538]
I use standart aws repo for vpc and ec2. in ec2's terragrunt.hcl i have written:
`
 dependency "vpc" {   
   config_path = "../vpc"   
 }   
`
And in inputs block:
`
subnet_id = dependency.vpc.outputs.vpc
`
When i start terragrunt plan-all, i get error:
[terragrunt] 2021/02/10 14:37:45 Encountered the following errors:
/tg/eu-north-1/test/web-server/terragrunt.hcl:39,37-41: Unsupported attribute; This object does not have an attribute named "vpc".
But there is output.tf in .terragrunt-cache directory of vpc with block:
`
output "vpc_id" {
  description = "The ID of the VPC"
  value       = concat(aws_vpc.this.*.id, [""])[0]
}
`
How resolve this error?
terraform version 0.13.3
teragrunt version 0.27.1

**Comment by yorinasub17** [comment]
The output is `vpc_id`, not `vpc`. Does it work if you change the dependency reference to `dependency.vpc.outputs.vpc_id`? Also separately, it looks like you are mapping the `vpc_id` to the `subnet_id`, which doesn't seem correct.

**Comment by IVBakker** [comment]
Go to "../vpc" run terragrunt output and that will show you the attributes you can use in "outputs"

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
