### ISSUE TITLE
Merge var from shared.hcl

### ISSUE THREAD

**Issue by hdiass** [gruntwork-io/terragrunt#1539]
Hello Guys, 

Sorry if this a noob question but I have one minor question that i can't figure out to solve or handle better.

So i have a terragrunt.hcl which uses a shared.hcl file that has values that are shared across multiple terragrunt definitions. 

In this specific `terragrunt.hcl` i have in locals:
```
locals {
  defaults     = read_terragrunt_config(find_in_parent_folders("shared.hcl"))
}
```
in shared.hcl

```
inputs = {
  specific_var = [
    ["XXXX","YYYY"],
    ["WWWW","ZZZZ"]
  ]
}
```

but now in current `terragrunt.hcl` i want to add more entries in the `shared.hcl` `specific_var` array. 
something like(that doesn't work):
```
inputs = merge(
  local.defaults.inputs,
  {
    specific_var = [
      local.defaults.inputs.specific_var,
      ["AAAAAAA", "BBBBBB"]
    ]
  }
)
```

In my current scenario if i define `specific_var` in terragrunt.hcl it will delete the values from shared and the array will contain only the values i define in the terragrunt.hcl. 
So for now my solution is to maintain those shared values across those two files. In shared one and here in this specific file. 
How can add do to add entries into the `specific_var` without needing to copy all values in `terragrunt.hcl` ?

Thanks in advance,
HD

**Comment by IVBakker** [comment]
Is the space expected: "local.defaults.inputs. specific_var" -> "local.defaults.inputs.specific_var"

Does it work with concat:
```
specific_var = concat(local.defaults.inputs.specific_var, ["AAAAAAA", "BBBBBB"])
```

I would also recommend to use "locals" instead of "inputs" inside your shared.hcl:
`shared.hcl`
```
locals = {
  specific_var = [
    ["XXXX","YYYY"],
    ["WWWW","ZZZZ"]
  ]
}
```
`terragrunt.hcl`
```
locals {
  defaults     = read_terragrunt_config(find_in_parent_folders("shared.hcl"))
}
inputs = merge(
  local.defaults.locals,
  {
    specific_var = concat(local.defaults.inputs.specific_var, ["AAAAAAA", "BBBBBB"])
)
```

**Comment by hdiass** [comment]
@IVBakker you can forget the space, just error of me obfuscating names for the post. 

Tried this approach
```
specific_var = concat(local.defaults.inputs.specific_var, ["AAAAAAA", "BBBBBB"])
```
but this "flattens" the list as explained  [here](https://www.terraform.io/docs/language/functions/concat.html)

I'll try your second approach now, but that would require a lot code change on other definitions.

thanks,

**Comment by hdiass** [comment]
nope, i want to get 
```
specific_var = [ ["XXXX","YYYY"], ["WWWW","ZZZZ"], ["AAAAAAA", "BBBBBB"] ]
```

**Comment by IVBakker** [comment]
Then
```
specific_var = concat(local.defaults.inputs.specific_var, [["AAAAAAA", "BBBBBB"]])
```

**Comment by hdiass** [comment]
Whooop, it works. Thanks a lot !
