### ISSUE TITLE
Add helper function to get `--terragrunt-source`

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terragrunt#1555]
This could be useful to configure hooks that trigger only during local development

**Comment by suhussai** [comment]
I'd like to help with this. Could you provide more information on what you're looking for?

**Comment by yorinasub17** [comment]
Sure! The idea would be to add a new function to https://github.com/gruntwork-io/terragrunt/blob/master/config/config_helpers.go#L98 that returns https://github.com/gruntwork-io/terragrunt/blob/master/options/options.go#L85 and add an integration test that verifies this works both when `--terragrunt-source` is provided, and when it is not.

**Comment by suhussai** [comment]
I created a PR with my changes: https://github.com/gruntwork-io/terragrunt/pull/1575

But I'm running into an issue when testing. I noticed that when I passing a source via the CLI (i.e. `--terragrunt-source`), the `getTerragruntSource` works as expected, but when I pass in a source via the config (i.e. `terraform { source = "./terraform_config_hcl" }`), I get an empty string.

Do you know why that might be happening?

**Comment by suhussai** [comment]
I have another question. As part of the PR (https://github.com/gruntwork-io/terragrunt/pull/1575) , I need to include the use case for this update. Would you be able to elaborate on how users can make use of this feature?

**Comment by yorinasub17** [comment]
> But I'm running into an issue when testing. I noticed that when I passing a source via the CLI (i.e. --terragrunt-source), the getTerragruntSource works as expected, but when I pass in a source via the config (i.e. terraform { source = "./terraform_config_hcl" }), I get an empty string.
> Do you know why that might be happening?

This is the intended behavior of this command. As mentioned in the description, the intention is to be able to determine when a user passes in a different terraform source via the `--terragrunt-source` flag. So returning blank string when that flag is omitted makes sense.

I'll comment on the PR regarding use case.

**Comment by dsantanu** [comment]
Any update on that PR? Is it going to any version any time soon?

**Comment by suhussai** [comment]
Sorry about the delay. I just pushed up another commit addressing the latest comments for https://github.com/gruntwork-io/terragrunt/pull/1575.

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.16
