### ISSUE TITLE
The before_hook and templatefile interaction

### ISSUE THREAD

**Issue by tropnikovvl** [gruntwork-io/terragrunt#1559]
Hi,
I have 2 questions

1) in my code I use generate block to generate main.tf from main.tpl and at the moment I have to keep main.tpl file in the directory with terragrunt.hcl, I am trying to get it there from another repository via before_hook, but it fails because terragrunt apparently checks for main.tpl when starting

```
generate "main.tf" {
  path = "main.tf"
  if_exists = "overwrite"

  contents = templatefile("./main.tpl", {
    list = { for k, v in dependency.databricks.outputs.this : v.name => v.id }
  })
}
```

2) almost a similar question, but now the templatefile is used in the input block, as I understand it is checked later
At the moment this is required to generate ARM templates Azure where I substitute values.

And the main question, is there any way to deliver these files with hook to the root directory (or to a temporary working directory of terragrunt) while it is running?

Thanks in advance.

p.s. the common error I get is
`Error in function call; Call to function "templatefile" failed: no file exists`

**Comment by brikis98** [comment]
Terragrunt must parse your `terragrunt.hcl` file to find the hooks... And it's during parsing that it'll execute functions within that file, such as `templatefile`. So that's why it's not working for you as you expect. 

What is the use case for this? Do you really want to `clone` a repo before every single Terragrunt command you run? Could the `.tpl` file live in the same repo as your Terraform code (i.e., where the `source` URL points to)?

**Comment by tropnikovvl** [comment]
Hi
i have a complicated repository system, so i clone them all the time when i start terragrant.

I would love to put main.tpl in the repository with terraform, but I don't pass validation because there is a generate block and in it you have to clearly specify the path to main.tpl (this is the example I gave in the question).
But there is a way around this I would be extremely happy to hear.

**Comment by yorinasub17** [comment]
I think you can implement your use case using `run_cmd`. It's a bit of a hack, but you do something like the following:


```
generate "main.tf" {
  path = "main.tf"
  if_exists = "overwrite"

  contents = templatefile(run_cmd("./generate_main_template.sh"), {
    list = { for k, v in dependency.databricks.outputs.this : v.name => v.id }
  })
}
```

where `generate_main_template.sh` is a script that does the cloning and echos `./main.tpl` to stdout. This way, `templatefile` is not called until the script to generate the template file is called, as `run_cmd` is evaluated first.

**Comment by tropnikovvl** [comment]
Is there any way to pass parameters to this generate_main_template.sh before execution?
For example the path from where to download the template, depending on the environment.

**Comment by yorinasub17** [comment]
Yup! See the [the docs for the function](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd)

**Comment by tropnikovvl** [comment]
Thank you so much - this solution works great!
