### ISSUE TITLE
Deprecation warning with Terraform 0.9

### ISSUE THREAD

**Issue by NeckBeardPrince** [gruntwork-io/terragrunt#156]
```
Deprecation warning: This environment is configured to use legacy remote state.
Remote state changed significantly in Terraform 0.9. Please update your remote
state configuration to use the new 'backend' settings. For now, Terraform
will continue to use your existing settings. Legacy remote state support
will be removed in Terraform 0.11.

You can find a guide for upgrading here:

https://www.terraform.io/docs/backends/legacy-0-8.html
```

**Comment by NeckBeardPrince** [comment]
Nevermind.. this was on me.

**Comment by josh-padnick** [comment]
Multiple [Gruntwork](http://gruntwork.io) clients have reported this issue, so I wanted to get an official solution posted and searchable.

This error usually means that you're missing the  `backend` block in your Terraform configurations (`.tf` files):

```hcl
terraform {
  backend "s3" {}
}
```

This is a [common mistake](https://github.com/gruntwork-io/terragrunt/issues/212) so we have an open issue to improve the user experience here.
