### ISSUE TITLE
Additional Hooks

### ISSUE THREAD

**Issue by jonwinton** [gruntwork-io/terragrunt#1560]
Hi, 

We're looking at using tools like [Xterraile](https://github.com/devopsmakers/xterrafile) in our pipeline and were hoping to use the native Terragrunt hooks to invoke the tool before each plan/apply. 

From what I can tell, the `before_hook` only runs after some initial Terragrunt setup where it expects the Terraform module to have already been sourced in some way. Since the tools we're looking at bringing into our toolchain handle that sourcing, we can't manage the invocation with Terragrunt. We're hoping to keep everything within the Terragrunt lifecycle to enforce consistency in our pipeline.

That said, has a new hook been discussed before? Maybe an `init_hook`? We're still considering how our pipeline might look so any feedback is appreciated. Thanks!

**Comment by brikis98** [comment]
Are you perhaps looking for `init` or `init-from-module`? You can find both in the docs: https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform

**Comment by jonwinton** [comment]
Oh nice! I'll do a quick sample of this to see if it fits out needs, thanks! If it works for our needs I'll close this issue.

**Comment by jonwinton** [comment]
Sorry, I forgot to update this. `init-from-module` is exactly what's needed, thank you!
