### ISSUE TITLE
Is variable inspection supported in the console?

### ISSUE THREAD

**Issue by thnee** [gruntwork-io/terragrunt#1561]
Looking to debug inputs to modules. Seeing that it should be possible to access local variables in the console when using regular terraform. Cannot find any documentation regarding this for terragrunt, is this supported?

```hcl
include {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../modules//some-module"
}

locals {
  secrets = yamldecode(sops_decrypt_file("secrets.yml"))
  foo = "hello"
}

inputs = {
  account-name = "prod"
}
```

```
λ terragrunt console
... snip ...
Terraform has been successfully initialized!
... snip ...

> local.foo

>  
Error: Reference to undeclared local value

  on <console-input> line 1:
  (source code not available)

A local value with the name "foo" has not been declared.

> local.account-name

>  
Error: Reference to undeclared local value

  on <console-input> line 1:
  (source code not available)

A local value with the name "account-name" has not been declared.
```

terragrunt verision: v0.23.33 (downgraded because of #1329)
terraform version: v0.14.7

**Comment by brikis98** [comment]
No, Terraform has no awareness or visibility of anything in the Terragrunt config. If you want to see the variables Terragrunt is resolving, you probably want the `--terragrunt-debug` flag instead: https://terragrunt.gruntwork.io/docs/features/debugging/

**Comment by thnee** [comment]
Ah cool, the `--terragrunt-debug` flag generates a `terragrunt-debug.tfvars.json` file, that's very helpful, thanks!
