### ISSUE TITLE
Feature request: Enable remote_state config to specify resource policy for state S3 bucket being auto-created

### ISSUE THREAD

**Issue by azec-pdx** [gruntwork-io/terragrunt#1567]
According to [AWS Auth](https://terragrunt.gruntwork.io/docs/features/aws-auth/) and [remote_state configuration block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state) docs it is not possible to specify resource policy for the state S3 bucket that Terragrunt creates for keeping states.

This is bad, because in any given organization, there may be IAM Roles and IAM Users with policies assigned that grant them "s3:*" permissions in co-located accounts. This means that these IAM principals can essentially read (maybe even write) the state S3 bucket and state objects within. This gets worse if there is sensitive data within Terragrunt state files, such as non-sanitized credentials etc. 

As a user of Terragrunt, I would expect to be able to specify resource (S3 bucket) level policy at the time I configure _remote_state_ block and for that policy to be applied as soon as state S3 bucket is auto created. This would allow me to specify only a subset of specific IAM principals (either from same AWS account where S3 bucket is being created or cross-account) which can access state bucket and deny access to all other IAM principals.

One such policy should be something like this:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Deny",
      "Principal": "*",
      "Action": "s3:*",
      "Resource": [
        "arn:aws:s3:::MyExampleBucket",
        "arn:aws:s3:::MyExampleBucket/*"
      ],
      "Condition": {
        "StringNotLike": {
          "aws:userId": [
            "AROAEXAMPLEID:*",
            "111111111111"
          ]
        }
      }
    }
  ]
}
```
inspired by the blog post ["How to Restrict Amazon S3 Bucket Access to a Specific IAM Role"](https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/) (see section **"Granting same-account bucket access to a specific role"**

With inability to specify this currently at the time S3 state bucket is created, security of state bucket is left as an after-thought to the users of Terragrunt that they may or may not remember to check, which leaves it as an entrypoint for many potential security issues.  

At a bare minimum, Terragrunt should mention this in the documentation that describes how the state S3 buckets are created as a reminder to the users to check this out. 

In the next iteration, it should make this required part of remote_state config element.

**Comment by yorinasub17** [comment]
The underlying solution for this is a duplicate of https://github.com/gruntwork-io/terragrunt/issues/924. Please follow that ticket for updates on when the feature for this might be implemented.
