### ISSUE TITLE
before_hook freezes when setting up a SSH tunnel in it. 

### ISSUE THREAD

**Issue by aleksanderaleksic** [gruntwork-io/terragrunt#1569]
I am trying to set up an ssh tunnel with a `before_hook` for a module to configure elasticsearch, but the subprocess "freezes"/gets stuck after running `terragrunt apply`. 

```
before_hook "open_tunnel_through_bastion" {
    commands     = [
      "plan",
      "apply",
      "plan-all",
      "apply-all"
    ]
    execute      = [
      "ssh",
      "ec2-user@bastion.${dependency.dns.outputs.zone.name}",
      "-N",
      "-f",
      "-L",
      "${local.bastion_port}:${dependency.elasticsearch.outputs.elasticsearch_endpoint}:443",
    ]
    run_on_error = true
}
```

The command resolves into something like this: `ssh ec2-user@bastion.dev.domain.com -N -f -L 9921:vpc-some-vpc-endpoint.us-east-1.es.amazonaws.com:443` which runs fine when I execute it in the terminal.

This is parts of the log output:
```
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:48:45 Detected 1 Hooks
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:48:45 Executing hook: open_tunnel_through_bastion
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:48:45 Running command: ssh ec2-user@bastion.dev.domain.com -N -f -L 9921:vpc-some-vpc-endpoint.us-east-1.es.amazonaws.com:443
^C
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:49:35 Forward signal interrupt to terraform.
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:49:35 Error forwarding signal: os: process already finished
^C
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:49:39 Forward signal interrupt to terraform.
[terragrunt] [/home/terragrunt/dev/us-east-1/elasticsearch-config] 2021/03/03 11:49:39 Error forwarding signal: os: process already finished
```
I am able to confirm that the command works as I am able to access the resource from a different terminal session.
If I try to terminate the apply I get the error `Error forwarding signal: os: process already finished`.
The only way I'm able to stop the apply is if I kill the ssh process, `kill $(lsof -t -i:9921)` then it will continue with the apply.

I have been able to work around this by using a `screen` session that runs in the background, but that's not available for windows that some of my team members use.

Any idea why this is happening?

**Comment by yorinasub17** [comment]
This is because of https://github.com/gruntwork-io/terragrunt/issues/856#issuecomment-530091210, and is not supported by terragrunt.

A new construct for managing hooks with background processes is necessary to implement this, which will require some design.

**Comment by azhurbilo** [comment]
@yorinasub17 I have the same problem but not in hooks, but in Terraform plan itself

if you use `data "external"` program / script 
and this program/script use external binary which under the hood run daemon process (even in background)

in our case we use [1password cli](https://developer.1password.com/docs/cli/v1/get-started/)

```
data "external" "one_password" {
  program = ["${path.module}/one_password.sh"]
  
  query = {
    vault    = xxx
    url      = xxx
    email    = xxx
    password = xxx
    secret   = xxx
  }
}
```

one_password.sh >>
```
#!/bin/bash
set -e

...

export OP_DEVICE=xxxxx
export OP_RETRIES=4
export OP_SLEEP=10

eval $(echo "$password" | op signin $url $email $secret --shorthand=xxx) || exit 1
...

echo $json | jq
```

Terraform plan finished successfully but Terragrunt stuck.
Last output log:
```
Plan: 4 to add, 0 to change, 1 to destroy.
------------------------------------------------------------------------
This plan was saved to: /xxx.tfplan
To perform exactly these actions, run the following command to apply:
    terraform apply "/xxx.tfplan"
```
and stuck ...


I thought that 1password (op) client works just as cli tool but then notice that execution of "op signin" run "op daemon" process (cli doesn't support flags to disable this daemon)

```
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/bash
   35 root      0:00 bash
   44 root      0:00 sh
  121 root      0:00 op daemon <<<<
  136 root      0:00 ps aux
 ```

And main concern of course that we don't have such issue with vanilla Terraform, issue reproduced after migrating to Terragrunt :(

**Comment by levkohimins** [comment]
Hi @aleksanderaleksic,

I tried to reproduce the problem using your example, but it didn’t work, everything works fine, the tunnel opened and terragrunt continued working. The code may have been changed since then and this issue has gone away.

Anyway there is a solution, to use `nohup`
https://github.com/gruntwork-io/terragrunt/issues/856#issuecomment-942585497
