### ISSUE TITLE
Terraform 0.9.0 drops remote config command

### ISSUE THREAD

**Issue by jeffbyrnes** [gruntwork-io/terragrunt#157]
As per the [“Remote State” section of the TF 0.9.0 upgrade guide](https://www.terraform.io/upgrade-guides/0-9.html#remote-state), the `remote config` command has been removed.

It would seem, since Terragrunt uses this command, that it will break on upgrade to TF 0.9.0.

I’ve not validated this myself (because up- then downgrading might prove tricky & I need to keep things working).

**Comment by brikis98** [comment]
Thx for the report. They claim full backwards compatibility, so I *suspect* you'll get a deprecation warning, but I haven't had a chance to give it a shot yet.

**Comment by griffint61** [comment]
No deprecation warning. The command is outright gone.

**Comment by brikis98** [comment]
That's... unfortunate. 

I'll update the README to say that Terraform 0.9 is not supported for now, I guess. FWIW, you don't need Terragrunt for locking / remote state configuration with Terraform 0.9 anyway...

**Comment by brikis98** [comment]
OK, added a quick note. 

The proper fix will probably be to remove the remote state and locking stuff from Terragrunt, since Terraform supports them natively now. PRs welcome :)

**Comment by jeffbyrnes** [comment]
Whoops, appears this is a dupe of #115. I knew I didn’t look hard enough. Please close if you feel this is best served by that issue!

**Comment by emoshaya-cognito** [comment]
Hi all,

We've been using [Terragrunt ](https://github.com/gruntwork-io/terragrunt)for a while now to manage state locking. Unfortunately, Terragrunt is not compatible with 0.9.0. Therefore, we now want to deprecate use of Terragrunt and migrate to 0.9.0 which fully supports state locking. However, we've noticed a few discrepancies and missing features available in the Terragrunt tool and missing in 0.9.0 Terraform. Please could you advise if these features will be available in future releases and if so, are their any timelines?

The configuration I had in place was for the following:

**S3 Backend for States and DynamoDB for State Locking**

- In Terragrunt, if the S3 bucket or DynamoDB table is missing, then Terragrunt would create them for you based on the configuration specified. This is missing in Terraform 0.9.0
- In Terragrunt, if you ran a Terragrunt apply, it will poll the dynamoDB table for the lock and will retry based on the value assigned in "max_lock_retries: (Optional) The maximum number of times to retry acquiring a lock. Terragrunt waits 10 seconds between retries. Default: 360 retries (one hour)."

- However, in Terraform 0.9.0 it doesn't retry or poll for lock to be released. Instead you get the following error:

`Error locking state: Error acquiring the state lock: ConditionalCheckFailedException: The conditional request failed
    status code: 400, request id: LTCHNG5G8U10REB2A6DV39LO6BVV4KQNSO5AEMVJF66Q9ASUAAJG
Lock Info:
  ID:        a4728cc3-303d-4987-af4a-25a54e954907
  Path:      ce-cog-test-tfstates/devops-terraform/cog.test.tfstate
  Operation: OperationTypePlan
  Who:       josh@magpie
  Version:   0.9.1
  Created:   2017-03-22 13:19:29.60094345 +0000 UTC
  Info:`

This is potentially a blocker for our CI builds as we have multiple CI builds running simultaneously at any given day and having the build just retrying to acquire the lock is a must to avoid failing builds.

**Comment by elijah** [comment]
I think it's interesting that you're reporting deficiencies in terraform to
the terragrunt repository. ;-)

**Comment by josh-padnick** [comment]
Closing this thread so that we can direct all comments around Terraform 0.9.0 compatibility to https://github.com/gruntwork-io/terragrunt/issues/158.
