### ISSUE TITLE
multiple dependencies from different directories

### ISSUE THREAD

**Issue by tropnikovvl** [gruntwork-io/terragrunt#1571]
Hi
my directory structure:

```
├── location1
│   ├── module1
│   │   └── terragrunt.hcl
│   ├── module2
│   │   └── terragrunt.hcl
├── location2
│   ├── module1
│   │   └── terragrunt.hcl
├── location3
│   ├── module1
│   │   └── terragrunt.hcl
```

I have a module that has to go to all these directories, take an output and apply it, this is needed to assign roles between different regions

I can do it in a non-flexible way, by trivially specifying everything manually, but that's a very, very unpleasant way.

the attempts i have made:

```
dependency "modules" {
  config_path = {
    for k, v in local.modules_map :
    k => 
     {
      config_path = "../../${v.path}/module1"
     }
   }
}
```

or 

```
dependency "modules" {
      config_path = { for k, v in local.modules_map : "../../${v.path}/module1"  }
}
```

and even so it doesn't want to read the data

```
dependency "modules" {
     config_path = "../../**/module1"
}
```

I have a question, how to do it right?
terragrunt version v0.25.5

p.s.
Just in case, I want to make it clear that this is not an endless addiction.
module2 only requests data from module1 to configure access roles, there is no feedback between them anymore
the problem is that in different environments I have a different number of regions and I want to make this code as flexible as possible

**Comment by brikis98** [comment]
Are you trying to generate `dependency` blocks dynamically? If so, that is not currently supported. You'll have to specify them statically.

**Comment by yorinasub17** [comment]
Closing as won't fix. I'm not sure we would support dynamic dependency blocks ever due to the complexity involved. If someone can propose an RFC with details on how we might be able to implement that in a maintainable way, we could definitely consider it.

Side note: the new [multiple include](https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/) feature might be useful here.
