### ISSUE TITLE
 --terragrunt-parallelism should default to 1 by default.

### ISSUE THREAD

**Issue by eddwardo** [gruntwork-io/terragrunt#1574]
For commands such as `plan-all` parallelism param should default 1.
Having parallel execution by default can lead to unexpected results, even with defined explicit dependencies between modules.

**Comment by brikis98** [comment]
Hm, what sort of unexpected results are you referring to?

**Comment by eddwardo** [comment]
I have a hook that authorizes with AWS. That script is not thread safe and caused obscure issue.

**Comment by brikis98** [comment]
I see. TBH, that doesn't sound like a very common case, so I'm not sure changing this default for everyone to fit that corner case would make sense.
