### ISSUE TITLE
is it possible to use generate function to create a common aws tags?

### ISSUE THREAD

**Issue by meet101** [gruntwork-io/terragrunt#1578]
Tags are very important for cloud resources. Not sure if there is a way currently in terragrunt to setup common tags for AWS resources. I tried to find it in the documentation. couldn't find much regarding tags. Found this blog where it says this is something possible to do in terragrunt. https://transcend.io/blog/why-we-use-terragrunt (Automatic resource tagging: Applies metadata universally)
I tried to use generate function for tags. couldn't get it working. 

I understand that i can pass an array of tags as tags = {foo : bar} inside the input block and this will be exported as env vars to terraform. but this will only work where we are passing tag attributes to the resource.

Just curious, if there is a way to add tags to aws resources using generate function from terragrunt?

**Comment by lorengordon** [comment]
fwiw, the terraform aws provider has it on their roadmap for this quarter to add this functionality into the provider... https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md#provider-functionality-default-tags

**Comment by brikis98** [comment]
Tags are resource specific. That is, each resource has a different way to specify tags. I don't think `generate` can help here. If https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md#provider-functionality-default-tags is implemented, as @lorengordon, that may change the story. But until then, the best you can do is to create modules that expose a common variable for specifying tags (e.g., a `custom_tags` variable), pass that variable to every single resource in that module, and set up your Terragrunt config to always set `custom_tags`.
