### ISSUE TITLE
Using 'random_password' in a Terragrunt input?

### ISSUE THREAD

**Issue by boldandbusted** [gruntwork-io/terragrunt#1579]
Howdy. I'd like to use the output from the `random_password` resource in Terragrunt.  What's the best way to do that? Do I have to create a dedicated module just to output the result? Thanks!

**Comment by brikis98** [comment]
Terragrunt doesn't create any resources or data sources, so yes, you'd need Terraform code for this. You can either create a module for it or use a [`generate` block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate).

**Comment by boldandbusted** [comment]
`generate` block! Thank you!

**Comment by vesubramanian** [comment]
Can you please provide the sample? I tried it, but unable to create dependency so that I can get an output (password) to be sent as an input to the terraform module.
