### ISSUE TITLE
Unsupported attribute — but tfstate and output has the attribute

### ISSUE THREAD

**Issue by TheBlackMini** [gruntwork-io/terragrunt#1589]
I cannot figure this out, it's happened a couple of times and this time I'm unable to work around it.

The error I'm getting from terragrunt is

> terragrunt.hcl:25,47-50: Unsupported attribute; This object does not have an attribute named "id".

My issue is that the id which I'm trying to reference is present in the tfstate, why can it not see it?

Shortened code below terragrunt.hcl

> dependency "vm01" {
>   config_path = "../vm01"
> }
> 
> include {
>   path = find_in_parent_folders()
> }
> 
> terraform {
>   source = "//core/azurerm_virtual_machine_extension"
> }
> 
> locals {
>   vm_name = "vm01"
> }
> 
> inputs = {
>   name                  = local.vm_name
>   virtual_machine_id    = dependency.vm01.id
> .....
> }

output.hcl

> output "id" {
>   value = azurerm_windows_virtual_machine.vm.id
> }

tfstate pulled directly from backend storage account

> {
>   "version": 4,
>   "terraform_version": "0.14.7",
>   "serial": 4,
>   "lineage": "abcde-guid-abcde",
>   "outputs": {
>     "id": {
>       "value": "/subscriptions/abcde-guid-abcde/resourceGroups/rg-name/providers/Microsoft.Compute/virtualMachines/vm01",
>       "type": "string"
>     }
>   }
> ...........
> }

terragrunt output from vm01

> [terragrunt] 2021/03/16 10:26:32 Running command: terraform output -json
> {
>   "id": {
>     "sensitive": false,
>     "type": "string",
>     "value": "/subscriptions/abcde-guid-abcde/resourceGroups/rg-name/providers/Microsoft.Compute/virtualMachines/vm01"
>   },
>   "resource_group_name": {
>     "sensitive": false,
>     "type": "string",
>     "value": "rg-name"
>   },
>   "virtual_machine_id": {
>     "sensitive": false,
>     "type": "string",
>     "value": "abcde-vm01guid-abcde"
>   }
> }

**Comment by yorinasub17** [comment]
The outputs are nested under `outputs`, so the path to `id` is `dependency.vm01.outputs.id`. See [the `dependency` block reference](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency) for more info.

**Comment by TheBlackMini** [comment]
Wow, thankyou! That was a rather stupid oversight.
