### ISSUE TITLE
IDE support?

### ISSUE THREAD

**Issue by dmead** [gruntwork-io/terragrunt#1591]
Hi All

Is there any decent ide support for terragrunt? or does it just kind of work well enough to use terraform stuff?

**Comment by yorinasub17** [comment]
Unfortunately, I am not aware of any good IDE support for terragrunt. Would certainly be interested if the community has any suggestions!

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
