### ISSUE TITLE
double-slash (//) is not respected for URLs that start with git::codecommit::<region>

### ISSUE THREAD

**Issue by vroad** [gruntwork-io/terragrunt#1592]
If source URL uses git-remote-codecommit (GRC) style URL, // in URL is not recognized at all. HTTPS CodeCommit urls work as expected, but I need to configure the credential helper instead of git-remote-codecommit.

https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-unixes.html

terragrunt always clones whole repository regardless of the location of //. `terragrunt init` always clones subdirectory only, and fails with errors like this.
```
Error: Unreadable module directory

Unable to evaluate directory symlink: lstat ../../../common: no such file or
directory
```

Suppose I have directory structure like this in modules repo:
```
├── my-app
│   └── modules
│       └── main-module
├── common
└── modules
  ├── example1
```

my-app/modules/main-module/main.tf:
```
module "example1" {
  source = "../../../common/modules/example1"
}
```

terragrunt.hcl, which is located in the live infrastructure repo:
```terraform
terraform {
  source = "git::codecommit::ap-northeast-1://my_app_modules//my-app/modules/main-module?ref=master"
}

include {
  path = find_in_parent_folders()
}
```

versions:
```
Terraform v0.14.8
terragrunt version v0.28.11
```

The same URL works correctly on terraform, so I suspect this issue to be a terragrunt-specific one.

```
module "foo" {
  source = "git::codecommit::ap-northeast-1://my_app_modules//my_app/modules/main-module"
}
```

**Comment by yorinasub17** [comment]
I have a potential fix in https://github.com/gruntwork-io/terragrunt/pull/1594, but not exactly sure if it will work given that I don't have a test repo with codecommit to work with.
