### ISSUE TITLE
Confusing message when terragrunt tries to create an S3 bucket with existing name

### ISSUE THREAD

**Issue by Sh1ftry** [gruntwork-io/terragrunt#1595]
When terragrunt tries to create an S3 bucket for remote state and a bucket with given name already exists, then it outputs really confusing message:
```
Remote state S3 bucket tfstate-vault does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) y
ERRO[0006] Create S3 bucket with retry tfstate-vault returned an error: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'
```

**Comment by brikis98** [comment]
Hm, that's odd. If anyone has time to dig in and improve the error handling for this, a PR is very welcome!

**Comment by max-rocket-internet** [comment]
I'd like to add another case of this error messaging being confusing: When authentication has expired.

Here's is what the AWS CLI correctly says:

```
$ aws s3 ls

An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired.
```

But Terragrunt says:

```
$ terragrunt plan -target=module.sqs_delivery_cancelled
Remote state S3 bucket xxxxxxxx does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)
```

It would be good if Terragrunt could show the real error from the AWS SDK 🙂
