### ISSUE TITLE
Dependencies vs dependency

### ISSUE THREAD

**Issue by phatcher** [gruntwork-io/terragrunt#1597]
If I have `dependency` blocks, do I also have to restate their paths in a `dependencies` block to get correct behaviour from `run-all`.

Reason I ask is that the docs aren't particularly clear on this and it would clean up by hcl files if I could remove the dependencies block

**Comment by brikis98** [comment]
No, you only need one or the other.

**Comment by phatcher** [comment]
ty - that will tidy up my config a fair bit and avoid duplication

Should I propose a doc change?

**Comment by brikis98** [comment]
That would be great, thank you!

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
