### ISSUE TITLE
`--terragrunt-strict-include` is not strict when no include dirs are specified

### ISSUE THREAD

**Issue by celestialorb** [gruntwork-io/terragrunt#1600]
Correct me if this is the intended design for `strict-include`, but I would've assumed that if I had specified `--terragrunt-strict-include` and no accompanying `--terragrunt-include-dir` flags that it would not run on any modules and would return successfully.

I've found that when I run with `--terragrunt-strict-include` and no `--terragrunt-include-dir` flags that Terragrunt acts as if the `--terragrunt-strict-include` flag does not exist and proceeds to operate over all modules under the working directory.

In my problematic command I'm only specifying `--terragrunt-working-dir` and `--terragrunt-strict-include`.

Example:
`terragrunt run-all validate --terragrunt-working-dir <account> --terragrunt-strict-include`

**Comment by brikis98** [comment]
[`--terragrunt-strict-include`](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-strict-include) only modifies the behavior of `--terragrunt-include-dir`. If you don't specify the latter, I believe the former has no effect.

**Comment by celestialorb** [comment]
The Terragrunt documentation seems to indicate that it would be the other way around, or at least that's how I interpret it:
> When passed in, only modules under the directories passed in with `–terragrunt-include-dir` will be included.

Could we consider changing the behavior of the flag?

**Comment by brikis98** [comment]
Changing the behavior to what?

**Comment by celestialorb** [comment]
To not run on any directories when `--terragrunt-strict-include` is supplied without any `--terragrunt-include-dir` flags.

**Comment by brikis98** [comment]
On re-reading the description, I think you're right; that behavior is probably the more expected one. We're buried at the moment, so if someone has the time to make this update, we'd very much welcome the PR!

**Comment by celestialorb** [comment]
I can take a stab at it this weekend, seems like it'd be fairly straight-forward from a quick glance at the codebase. :)

**Comment by celestialorb** [comment]
Basic PR to address this is ready for review.

**Comment by brikis98** [comment]
Fixed in #1631 and released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.20.
