### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by tropnikovvl** [gruntwork-io/terragrunt#1602]
Hello!

I use a lot of dependencies between resources in my code and I would like to determine if I should use a dependency or substitute some other value
For example:

` length(lookup(v, "rg", {})) > 0 ? dependency.resource_groups.outputs.rgs.rg.name : {}`

or 

` length(lookup(v, "rg", {})) > 0 ? dependency.resource_groups.outputs.rgs.rg.name : ""`

or 

` length(lookup(v, "rg", {})) > 0 ? dependency.resource_groups.outputs.rgs.rg.name : null`

different situations require different values
how to do it right? in general, i need to either get a value through dependency or give something that doesn't exist, so that this variable doesn't apply.
I often get errors because of this because the value of "rg" is empty or missing.
Thank you in advance.

**Comment by brikis98** [comment]
Could you provide a bit more context? Are you setting some variable in an `inputs = { ... }` block? What is `v` or `rg`? What is the Terraform code doing? What exact error are you getting?

**Comment by tropnikovvl** [comment]
the problem was in the architecture of the terraform module, thanks for the quick response!

**Comment by brikis98** [comment]
Thanks for the update. Closing.
