### ISSUE TITLE
Terragrunt Apply - Got 0 resources applied when Terraform fails

### ISSUE THREAD

**Issue by lmayorga1980** [gruntwork-io/terragrunt#1606]
I got the following error when deploying through terragrunt

`Error: timeout - last error: http response error: 401 - invalid content type`

This is because my `winrm` configuration was incorrect. Now I would like to destroy whatever resources where created prior the compute instances(firewall rules, networking objects, etc)

```
Error: timeout - last error: http response error: 401 - invalid content type



Error: timeout - last error: http response error: 401 - invalid content type


ERRO[0618] Hit multiple errors:
Hit multiple errors:
exit status 1 
➜  us-east1 git:(dev) ✗ terragrunt destroy 
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Destroy complete! Resources: 0 destroyed.
```

When I was using Terraform binary i could just execute `terraform destroy` and it will destroy the objects that were created prior to the error.

**Comment by brikis98** [comment]
The `destroy` command is based off what is in your state file. How are you managing the state file? Are you using some `backend`? Or is it local, on disk? Could you perhaps have accidentally deleted or moved the file?

**Comment by lmayorga1980** [comment]
The state file is local on disk. But even when using Terraform itself without Terragrunt, I can destroy part of the resources that were created.

**Comment by brikis98** [comment]
If the same thing is happening with Terraform, then I don't think it's related to Terragrunt?

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
