### ISSUE TITLE
`validate-inputs` and `default = null` variables

### ISSUE THREAD

**Issue by lawliet89** [gruntwork-io/terragrunt#1607]
This isn't really a bug report but more of a question.

Consider the following variables:

```hcl
variable "cpu_limit" {
  description = "CPU limit for thing"
  default     = null
  type        = string
}

variable "memory_request" {
  description = "Memory Request for thing"
  default     = null
  type        = string
}
```

I am not sure if this is intended by Terraform core, but I can run plan/apply without providing these values ever. And `null` is meaningful in the usage of these variables and I would like to default them to `null`.

When I run `terragrunt validate-inputs`, terragrunt reports that these required inputs are missing. Is this an intended design, or simply a behavior inherited from using Terraform core code?

**Comment by yorinasub17** [comment]
Yup this is something I ran into as well, and is a bug. I will be looking to fix this sometime this week or next.

**Comment by lawliet89** [comment]
Hey @yorinasub17 thanks for confirming. I noticed that when I publish modules to Terraform Registry, it detects `default = null` as required variables too. Thus my question. But if it can be fixed in Terrragrunt, that's great!

**Comment by yorinasub17** [comment]
Released as https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.18
