### ISSUE TITLE
How to Import Global Parameters From Root terragrunt.hcl File Into Child terragrunt.hcl Files?

### ISSUE THREAD

**Issue by johnsmith-coder** [gruntwork-io/terragrunt#1608]
Hi, I want to access a bunch of global values from all my child terragrunt.hcl files. I can see from the [terragrunt-infrastructure-live-example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example) code that root [terragrunt.hcl](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/master/terragrunt.hcl) specifies at the bottom:

```
# ---------------------------------------------------------------------------------------------------------------------
# GLOBAL PARAMETERS
# These variables apply to all configurations in this subfolder. These are automatically merged into the child
# `terragrunt.hcl` config via the include block.
# ---------------------------------------------------------------------------------------------------------------------

# Configure root level variables that all resources can inherit. This is especially helpful with multi-account configs
# where terraform_remote_state data sources are placed directly into the modules.
inputs = merge(
  local.account_vars.locals,
  local.region_vars.locals,
  local.environment_vars.locals,
)
```
This seems to be exactly what I'm looking for, however I don't know how to access this merged inputs map in my multiple child terragrunt.hcl files, they each have their own inputs {} map already, so how can I import this root inputs {} map as well? I have tried doing something like this (and similar variants) in my child terragrunt.hcl files:

```
locals {
  global_inputs = read_terragrunt_config(find_in_parent_folders("terragrunt.hcl")).inputs.version
}
```
But this doesn't work. Can someone tell me how I can access the inputs {} defined in the root terragrunt.hcl from all the child terragrunt.hcl files or send a link to a working example please?

Thanks!

**Comment by yorinasub17** [comment]
We don't currently support this, and the only way to make this work is to refactor the vars into separate files that are separately read in with `read_terragrunt_config` in each config file.

This particular feature will be possible when https://github.com/gruntwork-io/terragrunt/issues/1566 is implemented. I recommend following that ticket to be notified when we implement this.

Will close as dup.

**Comment by johnsmith-coder** [comment]
Hi @yorinasub17, thank you for your quick response and thank you for the information, I have followed the ticket as per your instruction. So am I right in saying that the following sample code in the terragrunt-infrastructure-live-example below is not actually usable?

```
# Configure root level variables that all resources can inherit. This is especially helpful with multi-account configs
# where terraform_remote_state data sources are placed directly into the modules.
inputs = merge(
  local.account_vars.locals,
  local.region_vars.locals,
  local.environment_vars.locals,
)
```
Thanks again for your help.

**Comment by yorinasub17** [comment]
This is usable, but serve a different use case from what you are expecting. The specific use case here is for setting common variable values for every terraform module in the tree.

In this case, the `inputs` are automatically merged together so that the values passed in the root are set as variable values to flow to `terraform`. So these values are set on the `terraform` call, but are not accessible for further manipulation in the child terragrunt configs (which is what you are looking for).

**Comment by johnsmith-coder** [comment]
Hi @yorinasub17, thank you again for your response. I can see that the inputs are all merged together to create new map, however I don't understand how those individual map key/values can then be mapped to specific input variables, eg I have in several of my child terragrunt.hcl files:

```
inputs = {
  name        = "my-proj1"
  environment = "dev"
}
```
ie, how do I assign a key value from this newly merged inputs map from the root terragrunt.hcl into the inputs section of my child terragrunt.hcl file, would it be something like this?
```
inputs = {
  name        = read_terragrunt_config(find_in_parent_folders("terragrunt.hcl")).inputs.name
}
```
Apologies, but I don't understand how the merged inputs map in the root terragrunt.hcl can be used in other child terragrunt.hcl files to set every other terraform module in the tree. Can you send me a link to a working example if possible please?

Thanks!

**Comment by yorinasub17** [comment]
Ah so the idea is that this is more like an inheritance tree. That is, the inputs from the parent are automatically inherited in the child.

For example, if you had a parent config that specifies:

```
inputs = {
  name = "parent"
}
```

and a child config that specifies:

```
include {
  path = find_in_parent_folders()
}

inputs = {
  environment = "dev"
}
```

the final set of inputs that get passed to terraform when you invoke `terragrunt` at the child is:

```
inputs = {
  name = "parent"
  environment = "dev"
}
```

(note how the `name` key was inherited from the parent config in the merge).

This merge operation is a shallow merge, with the child having precedence. That is, if the child config was instead:

```
include {
  path = find_in_parent_folders()
}

inputs = {
  name = "child"
}
```

Then during the merge the child config will override what is set in the parent to get the final config of:

```
inputs = {
  name = "child"
}
```

Does that make sense?
