### ISSUE TITLE
Files starting with a . are ignored

### ISSUE THREAD

**Issue by Damy3** [gruntwork-io/terragrunt#1609]
I was trying to upload an aws lambda within one of my modules but terragrunt ignores:

- .prettierrc.js
- .eslintrc.js
- .eslintignore

And that makes the deploy script of my lambda fail, is that how it is supposed to be or is it a bug? Maybe I'm just missing a configuration.

Thanks

**Comment by brikis98** [comment]
Closing as duplicate of #394.
