### ISSUE TITLE
Build terragrunt releases built as static binaries

### ISSUE THREAD

**Issue by keymon** [gruntwork-io/terragrunt#161]
Currently terragrunt binary releases are not built statically, but linked to libc:

```
$ ldd terragrunt_linux_amd64 
	linux-vdso.so.1 =>  (0x00007fffe704b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f143f603000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f143f23e000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a7004a3000)
```

This prevents me to use inside of [an alpine container](https://hub.docker.com/_/alpine/).

I suggest you build them using static: 

```
$ CGO_ENABLED=0 go  get  github.com/gruntwork-io/terragrunt
...
$ ldd terragrunt 
	not a dynamic executable
```

**Comment by josh-padnick** [comment]
@keymon Thanks for reporting this issue! This seems like a reasonable request and indeed, I've confirmed that our build code doesn't explicitly set the `CGO_ENABLED` var:

```bash
function build_binaries_for_app {
  local readonly app_name="$1"
  local readonly src_dir="$2"
  local readonly dest_dir="$3"
  local readonly ld_flags="$4"
  local readonly os="$5"
  local readonly arch="$6"
  local readonly parallel="$7"

  echo "Building binaries for app $app_name. src = $src_dir; dest = $dest_dir; ld_flags = $ld_flags; os = $os; arch = $arch;"
  mkdir -p "$dest_dir"
  cd "$src_dir"
  gox -os "$os" -arch "$arch" -parallel "$parallel" -output "$dest_dir/${app_name}_{{.OS}}_{{.Arch}}" -ldflags "$ld_flags"
}
```

This is a straightforward change to make, and since this code is private, we'll have to make it. Forgive the newb question, but if we set `CGO_ENABLED=0` is there any downside we should be concerned about? I don't have a full understanding of this issue.

**Comment by keymon** [comment]
AFAIK there is no concern... I reported the same time ago in the cloudfoundry client (https://github.com/cloudfoundry/cli/issues/807) and other projects and nobody complained.

**Comment by josh-padnick** [comment]
@keymon Ok, based on #162, I believe this is fixed. New binaries should appear in a few minutes. Can you test that out and confirm that it works for me?
