### ISSUE TITLE
Access inherited input

### ISSUE THREAD

**Issue by mijoypad** [gruntwork-io/terragrunt#1624]
Hi, I'm working on my terragrunt infrastructure and did a lot of searching, but haven't been able to find the answer for this question - Is it possible to access inherited input (by include {}) and treat it as kind of local? I have this situation, where I've got dependency on module that delivers aws networking data to my root terragrunt.hcl. I'm able to put that into inputs:

```
--live
   -remote-data
         -terragrunt.hcl
   -environment
         -my-module
              -terragrunt.hcl
         -environment.hcl
   -terragrunt.hcl
```

In the root terragrunt.hcl I setup dependency and put common values to inputs eg.:

```
inputs = merge(
{
  common_security_group = dependency.remote-state.outputs.networking.common_security_group_id
}
)
```

And then in live/environment/my-module/terragrunt.hcl  I define my_specific.security_group_id as local. I would like to pass an array of security groups to inputs and the array would contain:
```
- common_security_group_id 
- my_specific.security_group_id
```

Is it possible to achieve that? I know that if my common_security_group_id was defined in live/environment/environment.hcl I could do:

```
locals {
  env_vars = read_terragrunt_config(find_in_parent_folders("environment.hcl"))
  common_security_group = local.env_vars.inputs.common_security_group_id 
}
```

but it's defined on root terraform.hcl and as it's included into live/environment/my-module/terragrunt.hcl  I cannot simply do read_terragrunt_config(find_in_parent_folders()).

I know that I could setup additional dependency in my-module for the remote-data, but I wonder if I can somehow work it around.

Cheers!

**Comment by yorinasub17** [comment]
We don't currently support this, and the only way to make this work is to separately read in the vars in each config that needs it.

This particular feature will be possible when https://github.com/gruntwork-io/terragrunt/issues/1566 is implemented. I recommend following that ticket to be notified when we implement this.

Will close as dup.
