### ISSUE TITLE
Terragrunt doesn't appear to clear cache properly when branches are updated. 

### ISSUE THREAD

**Issue by queglay** [gruntwork-io/terragrunt#1627]
When using Terragrunt ref's to branch names (not tagged versions) for modules like this:
```
terraform {
  source = "github.com/firehawkvfx/firehawk-main.git//modules/vault?ref=test-pull-request-236"
```

I've noticed that if I update referenced branches and ensure my working tree is updated, terragrunt doesn't appear to correctly recognise this and the Terragrunt cache folder needs to be removed.

- A terragrunt apply before this removal of the cache will not work properly (the module wont be redownloaded).
- Removal of the cache will fix the problem.

I suspect this is because Terragrunt is assuming a ref is to a tagged version, and might just be comparing the cached tag string to the current working tree, which would be fine for those cases.  But if the ref is to a branch name the commit hash in the working tree would have to be used to determine if the cache is invalid, not just the tag name.

Thats just a guess, but it would explain the behaviour I observe.

For now when I update branches, I must always remove the terragrunt cache before any apply operations for updates to work smoothly.

**Comment by brikis98** [comment]
> I suspect this is because Terragrunt is assuming a ref is to a tagged version, and might just be comparing the cached tag string to the current working tree, which would be fine for those cases.

This is exactly right. The [code](https://github.com/gruntwork-io/terragrunt/blob/master/cli/download_source.go#L92) assumes that if you're using `ref`, it's pointing to something immutable, and doesn't bother to re-download. In general, pointing at a branch is an anti-pattern, as you never know what you'll end up deploying or what was deployed previously.

The alternative would be to try to re-download the code for every single `apply`, `plan`, `output`, `destroy`, etc, which would be very slow. 

Feedback/ideas are welcome.

**Comment by queglay** [comment]
Terraform does support the use of branches which is useful for dev, could Terragrunt also do that for coherence?

I'm also curious what your dev workflow looks like, and how you test if you are committing to a branch many times per day.  tagging each one uniquely and updating the refs would not be nice!

**Comment by brikis98** [comment]
> Terraform does support the use of branches which is useful for dev, could Terragrunt also do that for coherence?

Terraform requires you to run `init` manually when you update the `source` URL. You can do the same workflow with Terragrunt.

> I'm also curious what your dev workflow looks like, and how you test if you are committing to a branch many times per day. tagging each one uniquely and updating the refs would not be nice!
> 
> I guess I would like to suggest that if the commit hash were used, then versioned tags would still be immutable, but branches would be an option for those that want it.

For local dev, we use a local check out via [`--terragrunt-source`](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-source). So there's no need to keep pushing branches and re-downloading code, as you just run it directly from the latest on your file system.

**Comment by queglay** [comment]
I tried `terragrunt run-all init`, but this didn't end up redownloading the modules to the latest commits on the branches.

My dev workflow is a little different to how you describe, because I code locally in vscode, and then pull any changes into a cloud 9 instance and test from there - it helps provide a more consistent environment for others (but the code editor is not nice compared to vscode, so I don't edit there really).

**Comment by brikis98** [comment]
Why `run-all init` instead of just `init`?

**Comment by brikis98** [comment]
Oh, actually, I'm not sure `init` will help as this is about downloading the code, which is before `init`. 

Given that this doesn't seem to be a common use case, I think the best workaround may be to run with the `--terragrunt-source-update` flag. That will force Terragrunt to redownload everything every time.

**Comment by queglay** [comment]
This change to my workflow has helped when testing out single modules, thankyou.  One thing I haven't been able to improve in the workflow is if I have a repo with many modules, and then to test before a release, there may be many modules that reference the other repo with version refs.  Sometimes I can miss updating some of these refs to branches to test.

If there is an update that needs to be tested, is there a way to force multiple/many module refs that might point at a repo to use a particular branch to test?  Sometimes I have found I might forget to update some of the refs, and this introduces more human error than I'd like when I test updates.  It's probably just I haven't grasped the proper workflow in some way.

**Comment by brikis98** [comment]
Take a look at [`--terragrunt-source-map`](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-source-map).

**Comment by queglay** [comment]
Thanks @brikis98 that looks excellent.

**Comment by brikis98** [comment]
OK, great. Closing this issue!

**Comment by queglay** [comment]
I was perhaps mistaken because this is an example:
```
source = "github.com/firehawkvfx/firehawk-main.git//modules/vault?ref=v0.0.20"
source = "github.com/firehawkvfx/firehawk-main.git//modules/vault-kv-init?ref=v0.0.20"
source = "github.com/firehawkvfx/firehawk-main.git//modules/vault-policies?ref=v0.0.20"
```

It doesn't appear --terragrunt-source-map would retarget the `github.com/firehawkvfx/firehawk-main.git` to some local path and handle correction of the immutable `?ref=v0.0.20` suffix.
