### ISSUE TITLE
run_cmd helper not receiving AWS_* env variables when using iam_role property

### ISSUE THREAD

**Issue by lmontanag** [gruntwork-io/terragrunt#1636]
Hi Everyone, hope everything is going well

I am using:

```hcl
iam_role = "arn:aws:iam::111111111111:role/iam_target_role"
```

As per documentation [here](https://terragrunt.gruntwork.io/docs/features/work-with-multiple-aws-accounts/)

So terragrunt will call `sts assume-role` before running terraform commands and that is working nice.  

I have a shell script that use `aws-cli` to get a value from aws ssm (parameter store) and I am using [`run_cmd`](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd) to run that in terragrunt like:

```hcl
inputs = {
  certificate_body  = run_cmd("--terragrunt-quiet", "./get-aws-ssm-value.sh", "foo")
}

```

But I got the error: `An error occurred (ParameterNotFound) when calling the GetParameter operation:`

I have been trying to troubleshoot and it seems that for `run_cmd` the environment variables defined after assuming IAM role [here](https://github.com/gruntwork-io/terragrunt/blob/master/aws_helper/config.go#L188-L191)  are not passed as environment variables so `aws-cli` does not have valid AWS credentials.

not sure if I may be missing something, any help/clue, will be much appreciated 

thanks 👍🏼

**Comment by brikis98** [comment]
Ah, yea, the docs aren't clear on this. I think currently, `iam_role` is only used when calling your actual Terraform command (e.g., `terraform apply`) and not anything else. That said, it would be more consistent for `iam_role` to affect everything. A PR to make this change is welcome.

**Comment by lmontanag** [comment]
Closing this issue as it have been fixed , see comment here 

https://github.com/gruntwork-io/terragrunt/pull/1638#issuecomment-948714616

thanks so much for this 👍🏼
