### ISSUE TITLE
Manually generate auto-generated Terraform code when using terraform.tfvars module source.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terragrunt#164]
Recently, I needed to help a Gruntwork customer debug an issue with why a Terraform template could no longer apply. They're using Terragrunt and shared with me the following output:

```
aws_iam_policy.manage_ebs_volume: Refreshing state... (ID: arn:aws:iam::111111111111:policy/jenkins-manage-ebs-volume-vol-0f9999999999999)
aws_iam_policy_attachment.attach_manage_ebs_volume: Refreshing state... (ID: attach-manage-ebs-volume)
Error refreshing state: 1 error(s) occurred:

* aws_lambda_function.scheduled_lambda_job_not_in_vpc: RequestError: send request failed
caused by: Get https://lambda.us-west-2.amazonaws.com/2015-03-31/functions/jenkins-backup: dial tcp: lookup lambda.us-west-2.amazonaws.com on 127.0.0.1:53: read udp 127.0.0.1:58188->127.0.0.1:53: i/o timeout
```

It was a confusing error and we couldn't resolve it prima facie, so the next step is to keep simplifying the setup until we can explain why a simpler failure occurred. That, in turn, required that we use a native Terraform configuration that mimics the automated functionality of `terragrunt apply` in combination with a `terraform.tfvars` that copies a module to a temp directory.

But explaining how such a template should be structued to the client was still non-trivial, so it'd be nice if we had a `terragrunt generate` command (or something better named) that automatically outputs the Terraform code that Terragrunt internally generates for debugging situations like this one.

**Comment by brikis98** [comment]
I'm not sure I fully understand what the `generate` command would do?

BTW, is there a reason you can't do the local testing using the `--terragrunt-source` parameter?

**Comment by josh-padnick** [comment]
> Is there a reason you can't do the local testing using the `--terragrunt-source` parameter?

That mostly solves the problem, but for a true reproduction, it'd be nice if Terragrunt could "generate" the native Terraform equivalent of using `terragrunt.terraform.source` in `terraform.tfvars`.

**Comment by brikis98** [comment]
Isn't that exactly what it does when you run, say, `terragrunt plan`? The contents of the tmp folder are that output...

**Comment by josh-padnick** [comment]
Ah, I didn't make the connection that you could access that tmp folder even after `terragrunt plan` is run, and I suppose it's in the logs, too. Do you know if tmp files get deleted immediately after the terragrunt run finishes? If not, manually accessing the tmp folder solves the problem.

**Comment by brikis98** [comment]
They do not get deleted, so you should be able to `cd` into that folder and use it as you wish.

**Comment by josh-padnick** [comment]
Great, closing this issue. Thanks.
