### ISSUE TITLE
use secrets from aws secret manager

### ISSUE THREAD

**Issue by suppix** [gruntwork-io/terragrunt#1645]
Could you please help me how can I use secret variables from aws secret manager in terragrunt ? 

With terraform I use such approach: 

variables.tf
```
data "aws_secretsmanager_secret_version" "creds" {
  secret_id = "app-prod-config-server"
}

locals {
  app-creds = jsondecode (
    data.aws_secretsmanager_secret_version.creds.secret_string
  )
}
```
Then I can use secret variables in my tf files. 
```
username                   = local.app-creds.DATASOURCE_USERNAME
password                   = local.app-creds.DATASOURCE_PASSWORD
```

**Comment by yorinasub17** [comment]
The best way would be to use [run_cmd](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd) with the AWS CLI.
