### ISSUE TITLE
Invalid legacy provider address

### ISSUE THREAD

**Issue by gnomeria** [gruntwork-io/terragrunt#1646]
Hello. I've been trying to `terragrunt plan` on older state, and I'm in the version of:
```
terraform v0.15
terragrunt v0.28.24
```
I've tried to run this command:
`terragrunt state replace-provider "registry.terraform.io/-/aws" "hashicorp/aws"`

But it seems I'm just stuck with this error:
```
Initializing modules...
- commons in ../../commons
- networking in ../../commons/networking

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
╷
│ Error: Invalid legacy provider address
│ 
│ This configuration or its associated state refers to the unqualified
│ provider "aws".
│ 
│ You must complete the Terraform 0.13 upgrade process before upgrading to
│ later versions.
╵

ERRO[0006] Hit multiple errors:
Hit multiple errors:
exit status 1 
```

Any pointer on how to solve this issue?
Is this regarding our own modules?
Thank you 🙏 

---
I've tried to set the aws provider version in the module to version `3.37.0` but it seems no changes on the output at all.

**Comment by brikis98** [comment]
I believe you need to install Terraform 0.13 and run that command _before_ switching to Terraform 0.15.

**Comment by gnomeria** [comment]
Ah, silly me.
Yes it's now working. I've initiated a tag update with terraform 0.13. When I switched to 0.15, it will then generate a working state with `terragrunt init` and produced `.terraform.lock.hcl` lock file.
Thank you 👍
