### ISSUE TITLE
AWS SSO Login and get_aws_caller_identity_user_id()

### ISSUE THREAD

**Issue by stevie-** [gruntwork-io/terragrunt#1661]
Terragrunt version: 0.29.1
Terraform: 0.14.10
aws-cli: aws-cli/2.1.39 Python/3.9.4 Darwin/20.4.0 source/x86_64 prompt/off

Most of the AWS SSO login issues got solved by updateing go sdk in recent versions, but we still have an isse with terragrunt function `get_aws_caller_identity_user_id()` and aws sso credentials. To work around this issue we use a phyton script to create the old standard `~/.aws/credentials` keys from current SSO login profil.

We've created a small test sample code, which triggers the issue on init already:

`terragrunt.hcl`

```hcl
locals {
  aws_identitiy = get_aws_caller_identity_user_id()
}

terraform {
  source = "./"
}
```

`main.tf`
```hcl
data "aws_caller_identity" "current" {}
```

We set an ENV var `export AWS_PROFILE=sso_profile` and login via `aws sso login` succesfully. We check aws cli works.
Running terragrunt breaks:

```bash
❯ terragrunt --version
terragrunt version v0.29.1

❯ terragrunt init
Error: Error in function call

  on /Users/PATH/TO/test/terragrunt.hcl line 2, in locals:
   2:   aws_identitiy = get_aws_caller_identity_user_id()

Call to function "get_aws_caller_identity_user_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid
providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.

ERRO[0005] Encountered error while evaluating locals.
ERRO[0005] /Users/PATH/TO/test/terragrunt.hcl:2,19-51: Error in function call; Call to function "get_aws_caller_identity_user_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.
ERRO[0005] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

It's possible that tehre are more terragrunt helper function for aws have the same issue.

**Comment by brikis98** [comment]
This might be fixed by https://github.com/gruntwork-io/terragrunt/pull/1663...

**Comment by yorinasub17** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.29.2 a try to see if it resolves your issue!

**Comment by stevie-** [comment]
v0.29.2 solves the code example above

**Comment by stevie-** [comment]
But I found another issue with the [iam_role](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#iam_role)  parameter
