### ISSUE TITLE
'run-all apply' does not seem to cache output values between dependent modules 

### ISSUE THREAD

**Issue by Jamal7511** [gruntwork-io/terragrunt#1666]
Terraform v0.14.7
Terragrunt v0.29.2

I currently have some modules I am applying using the run-all apply command. The base module "VPC" runs and creates the VPC and has an output variable to output the cidr block of the VPC. I can verify the output is successful as running with "--terragrunt-log-level debug --terragrunt-debug" shows the "vpc_cidr_block" output with the expected value in the generated "terragrunt-debug.tfvars.json"

Once the VPC module is applied terragrunt moves onto the SG module which has a dependency on the VPC module. It references the "vpc_cidr_block" output of the VPC module. Instead of retrieving the output value correctly it reverts to using the mock_output value in terragrunt.hcl and fails as I specified an invalid mock cidr range so it falls over.

Now that the VPC exists with its output variables I can run another run-all apply or go into the SG module and run an individual apply on it and it will successfully pickup the output cidr block value from the VPC module. I use an s3 remote backend to store the tfstate files if that may be relevant. 

Looking at the debug log during the failed execution I see a message:
`time=2021-05-05T13:05:30+01:00 level=debug msg=C:/gitrepos/terraform/environments/dev/latest-codeset-light/VPC/terragrunt.hcl was run before. Using cached output. prefix=[C:\gitrepos\terraform\environments\dev\latest-codeset-light\SG]
time=2021-05-05T13:05:30+01:00 level=debug msg=WARNING: config C:/gitrepos/terraform/environments/dev/latest-codeset-light/VPC/terragrunt.hcl is a dependency of C:/gitrepos/terraform/environments/dev/latest-codeset-light/SG/terragrunt.hcl that has no outputs, but mock outputs provided and returning those in dependency output. prefix=[C:\gitrepos\terraform\environments\dev\latest-codeset-light\SG]`

It appears the local cache is failing to store the output variable? I guess it works on the second run because it would presumably retrieve the output values from the s3 tfstate file and the mechanism to store it cached locally on the first run is unable to for some reason? I'm led to believe this isn't an issue with my code as it appears to succeed during the second run but I can share any code snippets if required?

**Comment by s1mark** [comment]
@Jamal7511 
Maybe you could try to add the `disable_dependency_optimization = true` to the `terragrunt.hcl` where you define your dependency on the vpc module.
This setting will force terragrunt to skip searching the cache and go straight to the bucket

**Comment by Jamal7511** [comment]
@s1mark 

Thank you very much for sharing this

This appears to work and allows me to run through my modules start to finish. This would presumably indicate an issue with the way Terragrunt is caching the output values locally and attempting to use the locally cached values during the first run. My thoughts were that perhaps this was to do with permissions but running the same code on the AWS EC2 we have acting as our gitlab runner seems to return the very same problems. 

I am able to progress with my code in the meantime however leaving this open as there still appears to be an underlying issue

**Comment by Jamal7511** [comment]
Apologies this does not seem to work I was mistaken

Our gitlab pipeline had run overnight therefore I ran my local copy of the code on what I thought was a first run but it was actually the second run which as I mentioned seems to work. Doing a run-all destroy and consequent run-all apply still has the same issues with or without the `disable_dependency_optimization = true` unfortunately 

`time=2021-05-06T09:40:38+01:00 level=debug msg=C:/gitrepos/terraform/environments/dev/latest-codeset-light/VPC/terragrunt.hcl was run before. Using cached output. prefix=[C:\gitrepos\terraform\environments\dev\latest-codeset-light\SG]
time=2021-05-06T09:40:38+01:00 level=debug msg=WARNING: config C:/gitrepos/terraform/environments/dev/latest-codeset-light/VPC/terragrunt.hcl is a dependency of C:/gitrepos/terraform/environments/dev/latest-codeset-light/SG/terragrunt.hcl that has no outputs, but mock outputs provided and returning those in dependency output. prefix=[C:\gitrepos\terraform\environments\dev\latest-codeset-light\SG]`

**Comment by Jamal7511** [comment]
Reverting to an older codeset seems to have fixed the issue. Oddly porting all the future changes back into this old code, it still seems to work. What happened to cause this error I have no clue. 

As it does not appear easily reproducible I'm closing
