### ISSUE TITLE
Terragrunt with AWS SSO

### ISSUE THREAD

**Issue by ahmadzaikk** [gruntwork-io/terragrunt#1670]
Hello,
I am getting the following error when I try to use Terragrunt with AWS SSO, is there any instruction to setup Terragrunt to work with SSO?

Initializing the backend...

Error: No valid credential sources found for AWS Provider.
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

ERRO[0002] Hit multiple errors:
Hit multiple errors:
exit status 1

**Comment by brikis98** [comment]
What version of Terragrunt? How are you authenticating?

**Comment by ahmadzaikk** [comment]
@brikis98 I am using terragrunt version v0.29.0, i use aws-vault to authenticate. 

My terragrunt.hcl  state file looks like this


remote_state {
  backend = "s3"
  generate = {
    path      = "backend.auto.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket         = "state-file-buck"
    dynamodb_table = "dynamodb"
    encrypt        = true
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-west-2"
    #role_arn        = "arn:aws:iam::account-id1:role/aws-reserved/sso.amazonaws.com/us-west-2/AWSReservedSSO_managed-full_055b0a1893"
 
  }
}

My account.hcl looks like this

locals {
  account_name   = "account-name"
  aws_account_id = "account-id"
  role_arn = "arn:aws:iam::account-id:role/aws-reserved/sso.amazonaws.com/us-west-2/AWSReservedSSO_managed-full_ee0cc1b8056"
  
}

**Comment by brikis98** [comment]
Can you post the full command you're running and all the log output?

**Comment by brikis98** [comment]
I'm a bit confused... You mentioned `aws-vault` earlier, but it's not in your command... And now you're getting an `Access Denied` error rather than `No valid credential sources found for AWS Provider`. The former implies you're trying to use a backend (e.g., S3 bucket) you don't have access to; the latter implies you haven't authenticated.
