### ISSUE TITLE
Please consider updating go-getter to 1.5.3

### ISSUE THREAD

**Issue by graywolf-at-work** [gruntwork-io/terragrunt#1671]
Hello,

go-getter in version 1.5.3 added support for aws_profile query string for s3
protocol. That is something we really need, so I would like to ask if you would
please consider releasing patch version with just update of go-getter?

**Comment by brikis98** [comment]
PR to bump the dependency versions is welcome!

**Comment by graywolf-at-work** [comment]
I'm reading https://terragrunt.gruntwork.io/docs/community/contributing/ and
not finding it, so just want to make sure: It seems like there is no CLA
required for the contribution?

I will ask management for approval of OS contribution, just want to make sure
if I need to ping legal with CLA approval request.

**Comment by brikis98** [comment]
Correct, there is no CLA for this repo.

**Comment by getjack** [comment]
@graywolf-at-work Any update on that issue? Is there already a PR?

**Comment by graywolf-at-work** [comment]
Sorry did not have time to get to this (and sadly will not have the time for
some time yet).

**Comment by infraredgirl** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.7 a try!
