### ISSUE TITLE
terragrunt run-all resource conflicts on Azure

### ISSUE THREAD

**Issue by phatcher** [gruntwork-io/terragrunt#1682]
I'm trying to create multiple resources via `run-all` but am hitting an issue where a create command is failing since the parent resource is locked by another command, is there a way of expressing to terrragrunt/terraform such dependencies?

For example, I'm creating multiple subnets on a virtual network and I get...

```
module.subnets.module.subnets["uksouth"].azurerm_subnet.this: Creating...
module.subnets.module.subnets["global"].azurerm_subnet.this: Creating...
module.subnets.module.subnets["uksouth"].azurerm_subnet.this: Creating...

Error: creating/updating Subnet: (Name "private-subnet" / Virtual Network Name "vnet-xxx-devtest-uks" / Resource Group "XXX-DevTest-UKS"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/121fc553-44ba-4367-879e-8cde8b65f5c1/providers/Microsoft.Network/locations/uksouth/operations/84868051-xxx-xxx-8ea5-637f1f37a30b?api-version=2020-05-01." Details=[]
```

**Comment by brikis98** [comment]
Please see [the docs](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/), especially using `dependency` blocks to create explicit dependencies and [pass outputs between modules](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules) and using `dependencies` blocks to create [implicit dependencies between modules](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#dependencies-between-modules).

**Comment by phatcher** [comment]
@brikis98 Ok I can do that, it's a bit clunky though since now each subnet has to know about other subnets that are nothing to do with it, might report this at the terraform level since it could check and pause on creation of a subnet if the virtual network is locked

**Comment by yorinasub17** [comment]
There are also a couple other workarounds to consider:

- You can manually implement locking using before and after hooks. We don't really have azure expertise to suggest how to do this, but you can use various strategies for synchronization that ranges from file based locking to DB based locking.
- You can use `--terragrunt-parallelism 1` to serialize the `run-all` apply steps.
- You can add [retry logic](https://terragrunt.gruntwork.io/docs/features/auto-retry/#auto-retry) to have terragrunt retry when it sees this error message.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
