### ISSUE TITLE
--terragrunt-non-interactive not working, still get asked for confirmation prompt

### ISSUE THREAD

**Issue by kristijorgji** [gruntwork-io/terragrunt#1683]
## Problem
I use the documented `--terragrunt-non-interactive ` flag in order to automate the apply command, but still apply hangs and I get prompted "Please enter yes" to proceed.

Example commands:
```
cd $path_of_module
terragrunt apply --terragrunt-non-interactive

#... other stuff
    ]
  + vpc_security_group_ids       = [
      + [
          + "sg-00b9842ecdc6ec402",
        ],
    ]
# more stuff and the prompt below, which I want to automate select YES always
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
```

Same happens also with terragrunt destroy command, I still get asked:

```
Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: 
```

How can I automate this so all prompts are answered "Yes" automatically ?

## Environment
Terragrunt version:

```
 terragrunt --version
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.28.7
terragrunt version v0.28.7

```

**Comment by brikis98** [comment]
Add `-auto-approve`. Those prompts are from Terraform, not Terragrunt, so you need to use the Terraform flag to suppress them.

**Comment by kristijorgji** [comment]
> Add `-auto-approve`. Those prompts are from Terraform, not Terragrunt, so you need to use the Terraform flag to suppress them.

Thanks, I have added that in addition to --terragrunt-non-interactive and did not work, got error

entire command like `terragrunt apply --terragrunt-non-interactive -auto-approve`

**Comment by brikis98** [comment]
> > Add `-auto-approve`. Those prompts are from Terraform, not Terragrunt, so you need to use the Terraform flag to suppress them.
> 
> Thanks, I have added that in addition to --terragrunt-non-interactive and did not work, got error

What error?

**Comment by kristijorgji** [comment]
> > > Add `-auto-approve`. Those prompts are from Terraform, not Terragrunt, so you need to use the Terraform flag to suppress them.
> > 
> > 
> > Thanks, I have added that in addition to --terragrunt-non-interactive and did not work, got error
> 
> What error?

I tried again did not get anymore error, I got before 2 weeks some error like invalid flag.

Now I tried this comand
`terragrunt apply --terragrunt-non-interactive -auto-approve`

and I was still asked for approval


```
        ]
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
