### ISSUE TITLE
Overwrite input terragrunt.hcl

### ISSUE THREAD

**Issue by tropnikovvl** [gruntwork-io/terragrunt#1686]
I use this file allocation scheme and I have a question: in the upstream terragrunt.hcl through input, I will create a "value" = "test" value, and as I understand it, it will be inherited by the downstream terragrunt.hcl.  so how can you overwrite this value?  for example, under some condition, I would like the "value" = "newvalue" to become not "test" in the downstream terragrunt.hcl value.

Scheme:
```
   ├── prod
    │   ├── terragrunt.hcl
    │   ├── app
    │   │   └── terragrunt.hcl
    │   ├── mysql
    │   │   └── terragrunt.hcl
    │   └── vpc
    │       └── terragrunt.hcl
```

I need this so that I can set the main parameters for all modules, but in some I want to create a condition under which it will be chosen what to use: basic for all or unique for the module.

For example:
```
Value = Length(local.nondefaul_param) > 0 ? Local.nondefault_param : inherent_param
```

**Comment by brikis98** [comment]
If you're using `include`, then any values you put in the `inputs = { ... }` block of a child `terragrunt.hcl` will override the values in the `inputs = { ... }` block of the parent.

**Comment by tropnikovvl** [comment]
Hi
I understand that.
but I don't understand how you can make a condition so that in one case these values are overridden and in the other case they are not.

**Comment by yorinasub17** [comment]
You can use `merge` in the child `terragrunt.hcl`:

```
inputs = merge(
  (
    length(local.nondefaul_param) > 0
    ? { param = local.nondefaul_param }
    : {}
  ),
  {
    # other inputs
  },
)
```

**Comment by yorinasub17** [comment]
The order of the merge only matters if you have the `param` key in the `# other inputs` map. If it is defined in the root, then the child inputs attribute (which is computed **after** the merge function call) is always merged after the root. It looks more like this in pseudo code:

```
inputs = merge(
  # From the root terragrunt.hcl
  include.root.inputs,
  # The following is from the child terragrunt.hcl
  merge(
    length ? { param = foo } : {},
    { # other inputs },
  ),
)
```

**Comment by tropnikovvl** [comment]
Thanks a lot
