### ISSUE TITLE
will a dependency's after_hooks run before the dependent module's terraform code applies?

### ISSUE THREAD

**Issue by spacerainbow000** [gruntwork-io/terragrunt#1688]
I have a terragrunt module that needs to wait not only for the dependency to apply but for that dependency's after_hooks to finish before it can be planned or applied. do after_hooks work this way, or does terragrunt collect a list of all the after_hooks to run, then run them after all the terraform actions have finished? `terragrunt run-all plan` output would seem to suggest that a dependency's after_hooks will run after the dependent module is finished planning/applying, but I can't be sure since multiple things seem to be running at once during a run-all plan and the terminal output might not necessarily reflect the order things ran in (please tell me if this is an incorrect assumption)

**Comment by brikis98** [comment]
> do after_hooks work this way, or does terragrunt collect a list of all the after_hooks to run, then run them after all the terraform actions have finished?

The former. If `A` depends on `B`, then `B` will be applied and its hooks will run before `A` is executed.

**Comment by spacerainbow000** [comment]
> > do after_hooks work this way, or does terragrunt collect a list of all the after_hooks to run, then run them after all the terraform actions have finished?
> 
> The former. If `A` depends on `B`, then `B` will be applied and its hooks will run before `A` is executed.

oh okay, cool. this is true even for a plan, right? I have a hook running only on plan currently that solves the issue described here https://github.com/gruntwork-io/terragrunt/issues/262 , where the dependency is configured to output a plan file with the extra arguments parameter, then an after_hook runs a script that does a terraform apply with the resulting plan file. the intention is to make it so that the dependent module is applied before the depending module's plan is run. if I'm understanding you correctly, my solution should work; I thought it would too, but the reason I opened the GitHub issue is because when I run a plan with the setup I just described, the output from the after_hook script is printed after everything else runs - including the plan output from the depending module. is this just a visual thing?

**Comment by brikis98** [comment]
I believe it applies to `run-all plan` as well. I suspect what you're seeing is just a difference in how the logs are summarized at the end of the `run-all plan` run. If you have timestamps in your log messages, you can check.

**Comment by spacerainbow000** [comment]
oh okay, cool. one additional question about the thing I set up, where the module applies itself whenever a plan is run - a terragrunt run-all plan doesn't seem to actually do a plan for any of its dependencies. is there a way to make this happen? right now I'm symlinking the dependency into the folder where I run the run-all plan, but obviously that's not ideal

**Comment by spacerainbow000** [comment]
nvm I just found what I'm looking for - `--terragrunt-include-external-dependencies`

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
