### ISSUE TITLE
`terragrunt get` runs a modified `terraform init` instead of `terraform get`

### ISSUE THREAD

**Issue by marshall7m** [gruntwork-io/terragrunt#1690]
**Problem:**
Running the command `terragrunt get` within a directory that only consists of a`terragrunt.hcl` file mistakenly initializes the backend and downloads the providers. In addition, there isn't an`.terragrunt-cache/.../.../.terraform/modules/modules.json` file that's created which should reflect the `.terraform/modules/modules.json` that is created when `terraform get` is executed.

**Use case:**
I'm developing a pre-commit hook that needs to parse the `modules/modules.json` after `terragrunt get` is performed.  I could create a workaround and just `cd .terragrunt-cache/.../.../.terraform/modules` and then run `terraform get`, although getting `terragrunt get` to emulate `terraform get` would be preferred.

**Comment by brikis98** [comment]
Do you perhaps just need to [disable auto init](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-no-auto-init)?

**Comment by marshall7m** [comment]
@brikis98 using `terragrunt get --terragrunt-no-auto-init` did solve the unintentional backend/provider installation. 

Is there a way to retrieve the terragrunt source via the CLI? I assumed when I opened this issue that `terragrunt get` would create a `modules.json` to reflect the terragrunt source although now I realize that it only reflect the terraform module source. For example, if a `terragrunt.hcl` file consist of:

```
terraform {
    source = "../..//modules"
}
```
And then I can run some magical command to output the `source = "../..//modules"` via the CLI. I'm thinking if not, my best bet is to just parse the `terragrunt.hcl` via grep or some other bash tool.

**Comment by brikis98** [comment]
No, there's currently no command to output the `source` value.

Seems like the original question was answered, so closing!
