### ISSUE TITLE
plan & apply from TF 0.14.11 -> TF 0.15.4 does not update GCS backend version.

### ISSUE THREAD

**Issue by esn89** [gruntwork-io/terragrunt#1693]
I am doing upgrades from TF 0.14.11 -> TF 0.15.4 and I made sure all my plans return cleanly and I have started to run `terragrunt apply` everywhere.
I am using Terragrunt: 0.29.6

On certain modules, it updates the version in my GCS bucket backend as:

```{
  "version": 4,
  "terraform_version": "0.15.4",
  "serial": 3,
  .....
```

Which is correct.  However, there are some modules (which using the same configuration files to the backend) which keep the same "0.14.11" in the "terraform_version" and never gets updated.  I have tried `terragrunt init` and `terragrunt refresh` without luck.

This seems to be hit and miss.  I also did a `terraform state pull` and interestingly enough that returns the correct version of "0.15.4".  But the state of default.tfstate NEVER gets written to.

I think this bug may have started during a prior upgrade from TF13 -> TF14 as well.

**Comment by brikis98** [comment]
Terragrunt does not write to the state file. So if this is an issue, it seems like a Terraform problem, not a Terragrunt one.

That said, it may be worth clearing all caches by running with `--terragrunt-source-update` and seeing if that helps.
