### ISSUE TITLE
Use of Output Variables in after_hook

### ISSUE THREAD

**Issue by rakkur** [gruntwork-io/terragrunt#1699]
Hi - Does anyone know if we can use terraform output variables in our "after_hook" processing scripts?  Assuming my .tf file has this:

```
output "app_identity" {
    value = azurerm_app_service.app.identity[0].principal_id
}
```

I obviously can't use it in the before_hook because the plan hasn't been applied yet and no outputs are made, but what about after?  E.g.

```
after_hook "run powershell" {
    commands = ["apply"]
    execute  = ["powershell", "${get_terragrunt_dir()}/KeyVaultPerms.ps1 -principal ${self.output.app_identity}"]
}
```

I know that I can refer to the output in a dependency hcl, but what about the script's self?

**Comment by brikis98** [comment]
This is not currently supported.

**Comment by rakkur** [comment]
Thank you, @brikis98.  I'll find another way to do it, just wanted to make sure I wasn't missing anything.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
