### ISSUE TITLE
Create an integration test to validate that terragrunt works with arbitrary versions of terraform.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terragrunt#17]
Terragrunt has a relatively lightweight footprint with respect to terraform, but we should automate our validation that terragrunt works with any given version of terraform.

**Comment by brikis98** [comment]
@josh-padnick Is this fixed by #18?

**Comment by josh-padnick** [comment]
@brikis98 Yes! Good catch. I'll close now.
