### ISSUE TITLE
Destroy remote state buckets and locking tables from Terragrunt

### ISSUE THREAD

**Issue by hertzsprung** [gruntwork-io/terragrunt#1701]
It's great that Terragrunt can [create remote state buckets and locking tables](https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#create-remote-state-and-locking-resources-automatically) but, for short-lived testing environments, it'd be great if Terragrunt could destroy these resources, too.

Has this been discussed already?  Perhaps it could be provided as a separate Terragrunt command, or as a Terragrunt CLI option to the `destroy` command?

**Comment by brikis98** [comment]
I believe this is a duplicate of https://github.com/gruntwork-io/terragrunt/issues/250.
