### ISSUE TITLE
Dependency of dependencies

### ISSUE THREAD

**Issue by alxy** [gruntwork-io/terragrunt#1702]
I'm not sure if this is supported, but we have the following directory structure:

```
├───deployment-stamps
│   ├───eu1
│   │   ├───dev
│   │   │   └───aa
│   │   │       └───my-service
│   │   └───test
│   │       ├───aa
│   │       └───ab
│   └───na1
│       └───dev
│           └───ac
└───global
    ├───dev
    └───prod
```

And we basically want to call terragrunt from each level of the hierarchy, so from within `eu1/dev`, from `eu1/dev/aa` and even from  `eu1/dev/aa/my-service`. However, it only works from the first two directories described. If I want to run `terragrunt validate` in the `my-service` folder, then we hit the bug that it doesn't not correctly resolve recursive dependencies. Dependencies are as follows:

- `global/dev` does not have any dependencies
- `eu1/dev` has dependency on `global/dev`
-  `eu1/dev/aa` has a dependency on `global/dev` and  `eu1/dev`
- `eu1/dev/aa/my-service` has a dependency on `eu1/dev/aa` and `eu1/dev`, but **NOT** `global/dev`

Still, whenever we try to run terragrunt inside that module (and I have tried a lot, running `terragrunt run-all` from one level above, directly running inside that directory, etc), we get this error:

```
time=2021-06-04T09:46:55Z level=error msg=Module /home/vsts/work/1/s/deployments/deployment-stamps/eu1/dev/aa/my-service has finished with an error: /home/vsts/work/1/s/deployments/deployment-stamps/global/dev does not exist prefix=[/home/vsts/work/1/s/deployments/deployment-stamps/eu1/dev/aa/my-service] 
time=2021-06-04T09:46:55Z level=error msg=Encountered the following errors:
/home/vsts/work/1/s/deployments/deployment-stamps/global/dev does not exist
time=2021-06-04T09:46:55Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

The error is pretty obvious, it uses the wrong pathes to resolve the dependency, so my question is: Is that something that is not supported? Or do I do something wrong here?

As said, running terragrunt from other levels of the hierarchy does work, so I expect the dependency definitions itself are correct.

**Comment by yorinasub17** [comment]
> eu1/dev has dependency on global/dev

This part doesn't make sense to me. How are you linking the dependencies in this case? From my understanding of the folder structure, `eu1/dev` is a parent folder and thus it doesn't quite make sense to me how the dependencies are linked there.

Can you add `terragrunt.hcl` files to your folder hierarchy and a brief description of how they are linked, as well as where the `dependency` blocks are defined?

**Comment by alxy** [comment]
@yorinasub17 Thanks for your answer and sorry for my bad bug report. The problem was a configuration error on my end I think.

Basically each of the layers had a custom `remote_state` definition except the `my-service` layer which `include`ed the backend from the terragrunt.hcl in `aa`. For whatever reason, that doesnt work, as you get this issue if you want to trigger `terrragrunt apply` from the deepest level - in this case `aa` - of the hierarchy. Now we defined the `remote_state` block at the root of our folder structure and everything works as expected.

**Comment by yorinasub17** [comment]
Thanks for closing the loop!
