### ISSUE TITLE
Terragrunt parallelism and multi-region baseline modules

### ISSUE THREAD

**Issue by parmouraly** [gruntwork-io/terragrunt#1705]
Hi,

This is mainly a performance related question.

We have a `multi-account` setup on AWS and recently we decided it'd make sense to migrate our app accounts over to use the `baseline-app` module instead of manually using a large number of separate modules like `iam-cross-account`, `iam-password-policy` etc.

In doing so, we noticed that `plan` times for migrated accounts sky-rocketed by a number of minutes - roughly around 5mins on average. 
To put this in perspective, for some of our simplest accounts, planning time went from 1-2 minutes to around 8 mins.
This has slowed us down and has become an issue.

We have followed [advice here](https://gruntwork.io/guides/foundations/how-to-configure-production-grade-aws-account-structure/#apply-the-security-baseline-to-the-security-account) and reduced the parallelism, but that seemed to make matters worse and slow `plans` down even further.

To be more specific, it looks like when planning the `account-baseline-app` module in isolation locally, it takes around 5 minutes.

Here is a rough breakdown of these five mins - this is running a plan for an account that's already applied and using the `baseline-app` module:
* 10secs, `terraform` process has started
* 50secs, a bunch of AWS provider processes are up (eventually stabilises to 5 processes), and we start seeing `Refreshing state...` logs for a whole bunch of modules
* 120secs, a whole bunch of provider processes start getting spun up (eventually reaches ~140 processes). Logs are now outputting `module.security_baseline.module.iam_cross_account.... Refreshing state`.
* 200secs, we have had many log lines printed for things like multi-region config refreshing state. Soon afterwards all the `aws-provider` processes disappear.
* 280secs, a large number of provider processes (again ~140) are gradually spun up. As soon as they reach a maximum, we get the plan output.
* 330secs, the plan is output and all processes stop.

One strange thing we observed is that even after lowering the level of parallelism as discussed above, the same number of processes was still spun up, but this time the whole process seemed to take longer; presumably due to the reduced parallelism only a small subset of provider processes was allowed do be active at any one time.

Another thing that we thought was strange as well was the fact that all these 140 provider processes seemed to be killed only to be immediately restarted again before the plan is finally displayed; this alone seemed to introduce at least 1-2 mins of a delay.

All that said, do you have any comments or suggestions on the above behaviour? 
As I mentioned we are keen to standardise our accounts by using `baseline` modules but probably not at the expense of slowing things down so much.

Any advice is more than welcome.

Many thanks

**Comment by yorinasub17** [comment]
One thing I want to callout is that there is a big difference between the account baselines and the individual modules you had before, which is that the account baselines deploy the following additional resources:

- AWS Config
- GuardDuty
- EBS encryption configuration

These are configured to be deployed in every region according to recommendations by AWS landing zone. This is where the major performance hit is coming from.

The account baselines are meant to only be touched occasionally (maybe once every few months, to keep up with Gruntwork module updates). If you have anything that is frequently changing in there (e.g., IAM users), the recommendation is to extract that single configuration out of account baseline into a separate call like you had before.

That should hopefully make the performance hit more palatable.

**Comment by parmouraly** [comment]
Hey @yorinasub17 thanks for the quick reply. Indeed we're well aware of the additional resources and in fact it's one of the reasons we are interested in the baseline modules. We've already been using things like GD and encryption configuration and thought it'd make sense to have all these coming from one baseline as opposed to having them scattered around.

One thing that complicates our lives a bit when it comes to performance, is the fact that every time we have a PR for an AWS account, we execute by default `plan-all`. This obviously plans all modules, including the baseline.
We are doing this as it's a great way to avoid any configuration drift within any one account. It might be that we need to re-consider our approach.

I guess another follow up question would be, do you think it would make sense to provide an option to not check all regions by default?
Also, do you know what is the reason all these 140 provider processes being started, then stopped, and then started again during one single `plan-all` operation?

**Comment by yorinasub17** [comment]
> I guess another follow up question would be, do you think it would make sense to provide an option to not check all regions by default?

We can't really control that in terraform, but you can disable regions using the various `opt_in_regions` input vars.

> Also, do you know what is the reason all these 140 provider processes being started, then stopped, and then started again during one single plan-all operation?

This is because of the way terraform works, and how we are implementing multi-region modules. The only way to implement multi-region modules is to configure a provider block per region, and each provider block spawns a provider process. The part that makes this more complicated is that if the provider block is nested in a module, that ALSO spawns a new provider block. So you are looking at R * M provider process, where R is the number of regions and M is the number of multi region modules.

We've been trying to work around that to reduce the number of provider processes, but we haven't really found a way to trick terraform into avoiding that.

> One thing that complicates our lives a bit when it comes to performance, is the fact that every time we have a PR for an AWS account, we execute by default plan-all. This obviously plans all modules, including the baseline.

I would advise against using `plan-all` (see [this comment](https://github.com/gruntwork-io/terragrunt/issues/720#issuecomment-497888756) for my reasoning), but if you want to go with it, my recommendation would be to omit the account baseline from the plan-all. You can do that either by reorganizing your folder structure, or by using [--terragrunt-exclude-dir](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-exclude-dir).

**Comment by parmouraly** [comment]
I'll close this for now as I think we're going to try and follow your advice and avoid running `*-all` as often as we are at the moment. Thanks!
