### ISSUE TITLE
when we would be the 1.0.0 release for terragrunt?

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/terragrunt#1707]
[HashiCorp just announced Terraform 1.0 General Availability](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability), I wonder what the timeframe for terragrunt GA release. Thanks!

**Comment by estebanz01** [comment]
Same, I'm working with latest terraform version and I'm getting an error trying to execute any command with latest terragrunt:
```bash
$ terragrunt state pull
ERRO[0000] The currently installed version of Terraform (1.0.0) is not compatible with the version Terragrunt requires (= 0.14.10). 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
$ terragrunt --version
terragrunt version v0.29.10
$ terraform --version
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.44.0
```

**Comment by yorinasub17** [comment]
> just curious when would be the GA for terragrunt. Thanks!

Terraform 1.0 was one of the requirements for Terragrunt reaching 1.0, but that doesn't mean it was the only blocker for Terragrunt 1.0. With the Terraform 1.0 release, we will basically be starting the conversation of what it means for Terragrunt to reach 1.0 including what stable APIs of Terragrunt we want to support.

**Comment by yorinasub17** [comment]
> Same, I'm working with latest terraform version and I'm getting an error trying to execute any command with latest terragrunt:


This ticket is about when terragrunt would reach 1.x. I filed https://github.com/gruntwork-io/terragrunt/issues/1710 to track terraform 1.x support in terragrunt. Please follow that ticket for updates on when terragrunt will support tf1.x

**Comment by chenrui333** [comment]
Yeah, totally. We can track terraform 1.0.0 separately.

**Comment by yorinasub17** [comment]
Closing this as we are unlikely to cut terragrunt 1.0.0 anytime soon. We will make a separate ticket/announcement when we are ready to start tracking what it means for terragrunt to reach 1.0. Thanks!

**Comment by josh-padnick** [comment]
Hi folks, closing the loop some 3 years later, but we just announced [The Road to Terragrunt 1.0](https://blog.gruntwork.io/the-road-to-terragrunt-1-0-4d5a0b416086)!
