### ISSUE TITLE
terragrunt run-all destroy does not ask for confirmation per module

### ISSUE THREAD

**Issue by gdsotirov** [gruntwork-io/terragrunt#1708]
While implementing `terragrunt run-all` command I noticed that it asks single confirmation for `destroy` and then executes `terraform destroy` unconditionally (and eventually in parallel) in every sub directory, but I haven't specified `--terragrunt-non-interactive` explicitly. Is there a way to change this behavior? This is useful primarily for testing, so I'd like to have it as option.

**Comment by yorinasub17** [comment]
This is not something we can really do given that `run-all` by definition runs modules in parallel. This causes problems with interactivity as the terminal UI is naturally serial and humans are single threaded.
