### ISSUE TITLE
Add support for terraform 1.x to terragrunt

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terragrunt#1710]

**Comment by yorinasub17** [comment]
This is done in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.0

**Comment by jmooo** [comment]
````
$ terragrunt --version
terragrunt version v0.31.0
$ terraform --version
Terraform v1.0.0```

**Comment by yorinasub17** [comment]
@jmooo Check your config to see if you have any custom [terraform_version_constraints](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_version_constraint) defined.
