### ISSUE TITLE
[question] about build tool for monorepo (terragrunt+terraform)

### ISSUE THREAD

**Issue by lmayorga1980** [gruntwork-io/terragrunt#1712]
Do you recommend any tools associated with terragrunt deployments in a monorepo? I would like to set deployments based on the changes made on specific directories in the directory tree. I have seen something like Nx or Bazel but I am not sure if those are suitable for iAC project.

Any advice would be appreciated.

**Comment by yorinasub17** [comment]
As far as we know, we haven't found a satisfactory build tool that achieves the goals you described. In most cases, teams build custom scripts that use `git diff` to find the updated files and pass it through to terragrunt using `terragrunt-include-dir`.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
