### ISSUE TITLE
Terragrunt should enable all additional security layers on access logging bucket

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#1717]
E.g., Enable encryption, enable blocking all public access, etc. [This logic here](https://github.com/gruntwork-io/terragrunt/blob/fd49e82778353b2fe5bc52e46ef2c5a5130374c9/remote/remote_state_s3.go#L453-L463) currently only creates the bucket, but does not, for example, call [`EnablePublicAccessBlockingForS3Bucket`](https://github.com/gruntwork-io/terragrunt/blob/fd49e82778353b2fe5bc52e46ef2c5a5130374c9/remote/remote_state_s3.go#L716) to block public access.

**Comment by taliesins** [comment]
Resolved by #2040

**Comment by bt-macole** [comment]
#2040 resolves blocking all public access, but it does not enable `all` additional security layers, such as [`EnableSSEForS3BucketWide`](https://github.com/gruntwork-io/terragrunt/blob/7f01a7186c2b6e0e6bbc4bfbb4cb7ec9e6e9478f/remote/remote_state_s3.go#L1020) and [`EnableEnforcedTLSAccesstoS3Bucket`](https://github.com/gruntwork-io/terragrunt/blob/fd49e82778353b2fe5bc52e46ef2c5a5130374c9/remote/remote_state_s3.go#L610).
