### ISSUE TITLE
Ensure minimum terraform version

### ISSUE THREAD

**Issue by robkinyon** [gruntwork-io/terragrunt#172]
With all the migration of features back into Terraform, Terragrunt needs to be able to guarantee a minimum Terraform version. Otherwise, if a tfvars file doesn't specify locking and someone accidentally uses an old version of Terraform, bad things can happen.

There should be a default minimum version and teams should be able to override that version if desired.

**Comment by brikis98** [comment]
Ah, that's a great point. PRs for that are definitely welcome.

**Comment by brikis98** [comment]
Basic fix in #180. Should be available here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.12.5

**Comment by robkinyon** [comment]
In addition to a minimum Terraform version, there should also be a way of specifying a minimum *Terragrunt* version within configuration. If I knew golang better, I'd offer a PR for this.

**Comment by brikis98** [comment]
Ah, that would be handy too. Could you file a separate issue for that?

**Comment by brikis98** [comment]
Closing this issue so we can focus on #182.
