### ISSUE TITLE
[Question] Can remote_state be defined from AWS SSM Parameter Store values?

### ISSUE THREAD

**Issue by Nogginboink** [gruntwork-io/terragrunt#1729]
I'd like to define the S3 bucket name of my remote_state dynamically, so that when terragrunt runs in separate AWS accounts (dev/test/prod) terragrunt will use the appropriate S3 bucket for that account.

I would like to create 3 different accounts in my AWS organization, and in each create a SSM Parameter Store parameter, say "defaults/terragrunt/remote_state_s3_bucket", and have terragrunt query that when it parses the remote_state block. As long as I define that SSM parameter in all accounts in which the terragrunt stack will be deployed, I can ensure the S3 bucket is correct for the account in which the Terragrunt stack is being deployed.

Is there any way to do this? If not, what options are there to dynamically generate the S3 bucket?

**Comment by brikis98** [comment]
The name of the bucket is a parameter called `bucket` and you can set that to a dynamic value. Example:

```hcl
locals {
  # Fetch the bucket name by running script.sh
  bucket_name = run_cmd("script.sh")
}

remote_state {
  backend = "s3"
  config = {
    bucket         = local.bucket_name
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
  }
}
```

The code above gets the bucket name dynamically by executing a script (`script.sh`) and then uses that to set the `bucket` param. So you could have a script that fetches data from AWS Param Store or wherever else.

**Comment by brikis98** [comment]
BTW, an easier alternative may be to use folder structure. E.g., If all the dev account code is in `live/dev` and all the stage account code is in `live/stage` and there is a root `terragrunt.hcl` in the `live` folder, then you could do something like:

```hcl
locals {
  # Parse the bucket name from the folder structure
  parsed_path = regex(".*/live/(?P<env>.*?)/.*, get_parent_terragrunt_dir())
  env         = local.parsed_path.env
}

remote_state {
  backend = "s3"
  config = {
    bucket         = "my-terraform-state-bucket-${local.env}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
  }
}
```

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
