### ISSUE TITLE
terragrunt destroy does not pass extra arguments

### ISSUE THREAD

**Issue by jcharette** [gruntwork-io/terragrunt#173]
my terraform.tfvars file contains arguments to include downward referenced variables

     arguments = [
        "-var-file=${get_tfvars_dir()}/../env.tfvars",
        "-var-file=${get_tfvars_dir()}/../../common.tfvars"
      ]

terragrunt apply includes these arguments and the environment builds.   
terragrunt destroy does not however and thus the environment cannot be torn down.

apply: terraform apply -var-file=/Users/jcharette/vbustash/ox/tf_live/prod/cluster/../env.tfvars -var-file=/Users/jcharette/vbustash/ox/tf_live/prod/cluster/../../common.tfvars

destroy debug: terraform destroy -force -input=false

The expectation is for destroy to include the referenced extra variable argument files.

**Comment by brikis98** [comment]
What `commands` do you have in the `extra_arguments` list?

**Comment by jcharette** [comment]
Never mind.  I figured it out.  My recommendation would be to add the delete command to the example documentation.  

      commands = [
        "apply",
        "plan",
        "import",
        "push",
        "refresh",
        "destroy"
      ]

Destroy was not in the command list.

**Comment by brikis98** [comment]
That would be good to add to the README. PR for that welcome :)
