### ISSUE TITLE
How to rename output from terraform block

### ISSUE THREAD

**Issue by anemptyair** [gruntwork-io/terragrunt#1731]
In terragrunt.hcl

terraform {
  source = "git::https://github.com/terraform-aws-modules/terraform-aws-s3-bucket.git?ref=v2.1.0"
}

I know that the aws s3 module will come out some outputs like "s3_bucket_arn", But I want to re-name it with some prefix like "order_service_s3_bucket_arn". In terraform I can do that with 

output "order_service_s3_bucket_arn" {
  value       = module.aws_s3_bucker.s3_bucket_arn
}

How to do that in terragurnt?  Thanks.

**Comment by yorinasub17** [comment]
There really isn't a way to do this in terragrunt, as terragrunt doesn't manipulate the outputs fed out from terraform. You need to do this at the terraform module level. The only way I can think of to do this is via monkey patching of the terraform module.

Terragrunt supports injecting terraform code into an existing module by `generate` blocks, so you can probably get the output you want by injecting the "right" `output` block using `generate`.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
