### ISSUE TITLE
Terragrunt destroy -target=my-resource fails

### ISSUE THREAD

**Issue by dragosnicolaesava** [gruntwork-io/terragrunt#1734]
After running terragrunt apply I get my resources created, and that is great.

But I migh need to destroy a resource, so I can recreate it later (this cases usually involve VM's and DSC/puppet etc..)
Status: Terraform let's me do this, terragrunt doesn't: terragrunt destroy -target=my-resource

This is the result of a log, i run after this failed 'terragrunt destroy' and it worked.
 terragrunt destroy -target=my-resource-name
[terragrunt] [...] 2021/06/25 08:17:57 Running command: terraform --version
[terragrunt] 2021/06/25 08:17:57 Terraform version: 0.12.29
[terragrunt] 2021/06/25 08:17:57 Reading Terragrunt config file at .../terragrunt.hcl
[terragrunt] 2021/06/25 08:17:57 WARNING: no double-slash (//) found in source URL C.../ Relative paths in downloaded Terraform code may not work.
[terragrunt] 2021/06/25 08:17:57 Downloading Terraform configurations from file://C.../ into C:/...
...copy, generate,etc ..
[terragrunt] 2021/06/25 08:17:57 Backend azurerm has not changed.
[terragrunt] 2021/06/25 08:17:57 Running command: terraform destroy -target=my-resource-name
Usage: terraform destroy [options] [DIR]

  Destroy Terraform-managed infrastructure.

Options:

  -backup=path           Path to backup the existing state file before
                         modifying. Defaults to the "-state-out" path with
                         ".backup" extension. Set to "-" to disable backup.

  -auto-approve          Skip interactive approval before destroying.

  -force                 Deprecated: same as auto-approve.

  -lock=true             Lock the state file when locking is supported.

  -lock-timeout=0s       Duration to retry a state lock.

  -no-color              If specified, output won't contain any color.

  -parallelism=n         Limit the number of concurrent operations.
                         Defaults to 10.

  -refresh=true          Update state prior to checking for differences. This
                         has no effect if a plan file is given to apply.

  -state=path            Path to read and save state (unless state-out
                         is specified). Defaults to "terraform.tfstate".

  -state-out=path        Path to write state to that is different than
                         "-state". This can be used to preserve the old
                         state.

  -target=resource       Resource to target. Operation will be limited to this
                         resource and its dependencies. This flag can be used
                         multiple times.

  -var 'foo=bar'         Set a variable in the Terraform configuration. This
                         flag can be set multiple times.

  -var-file=foo          Set variables in the Terraform configuration from
                         a file. If "terraform.tfvars" or any ".auto.tfvars"
                         files are present, they will be automatically loaded.
[terragrunt] 2021/06/25 08:17:57 Hit multiple errors:
exit status 1

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue for you, please follow up with the requested context above and happy to reopen/investigate. Thanks!
