### ISSUE TITLE
--terragrunt-exclude-dir with a pattern to exclude multiple directories

### ISSUE THREAD

**Issue by os-mram** [gruntwork-io/terragrunt#1735]
Hi, 

i'm trying to use --terragrunt-exclude-dir to exclude multiple directories. It works only for a single directory rather than for all.

For example, i want to exclude  code/devSub/network/peering, code/hubSub/network/peering, code/prodSub/network/peering, code/hubSub/network/peering. 

If i use --terragrunt-exclude multiple times in terragrunt run-all command, it works. but doesn't work for a pattern like code/*/network/peering 

Code:

├── devSub
│   ├── key_vault
│   ├── networking
│   │   ├── associations
│   │   │   ├── nsgassociation
│   │   │   │   └── terragrunt.hcl
│   │   │   └── routetableassociation
│   │   │       └── terragrunt.hcl
│   │   ├── network_security_group
│   │   │   └── terragrunt.hcl
│   │   ├── peering
│   │   │   └── terragrunt.hcl
│   │   ├── route_tables
│   │   │   └── terragrunt.hcl
│   │   └── virtual_network
│   │       └── terragrunt.hcl
│   └── resource_group
│       └── terragrunt.hcl
├── hubSub
│   ├── key_vault
│   ├── networking
│   │   ├── associations
│   │   │   ├── nsgassociation
│   │   │   │   └── terragrunt.hcl
│   │   │   └── routetableassociation
│   │   │       └── terragrunt.hcl
│   │   ├── network_security_group
│   │   │   └── terragrunt.hcl
│   │   ├── peering
│   │   │   └── terragrunt.hcl
│   │   ├── route_tables
│   │   │   └── terragrunt.hcl
│   │   └── virtual_network
│   │       └── terragrunt.hcl
│   └── resource_group
│       └── terragrunt.hcl
├── prodSub
│   ├── key_vault
│   ├── networking
│   │   ├── associations
│   │   │   ├── nsgassociation
│   │   │   │   └── terragrunt.hcl
│   │   │   └── routetableassociation
│   │   │       └── terragrunt.hcl
│   │   ├── network_security_group
│   │   │   └── terragrunt.hcl
│   │   ├── peering
│   │   │   └── terragrunt.hcl
│   │   ├── route_tables
│   │   │   └── terragrunt.hcl
│   │   └── virtual_network
│   │       └── terragrunt.hcl
│   └── resource_group
│       └── terragrunt.hcl
├── root.hcl
└── uatSub
    ├── key_vault
    ├── networking
    │   ├── associations
    │   │   ├── nsgassociation
    │   │   │   └── terragrunt.hcl
    │   │   └── routetableassociation
    │   │       └── terragrunt.hcl
    │   ├── network_security_group
    │   │   └── terragrunt.hcl
    │   ├── peering
    │   │   └── terragrunt.hcl
    │   ├── route_tables
    │   │   └── terragrunt.hcl
    │   └── virtual_network
    │       └── terragrunt.hcl
    └── resource_group
        └── terragrunt.hcl

**Comment by yorinasub17** [comment]
Does it work if you use `--terragrunt-exclude code/**/network/peering`, with two `**`?

**Comment by longnnb** [comment]
I have a relevant question, I accidentally deleted some of state files and now I need to exclude mutliple directories when running plan-all|apply-all. Is there any way to put all the directories that need to be excluded in a config file, instead of put all of them as CLI options?

**Comment by os-mram** [comment]
> --terragrunt-exclude code/**/network/peering

it doesn't work though it doesn't throw any error as well.

**Comment by yorinasub17** [comment]
Hmm I am actually able to get it to work with both `--terragrunt-exclude-dir 'code/**/network/peering'` and `--terragrunt-exclude-dir 'code/*/network/peering'`. Is it possible that you are not quoting the directory expression, so your shell (bash, zsh, or other) is automatically expanding it?

**Comment by yorinasub17** [comment]
Closing this as stale. If there are any follow ups, please open a new ticket with updated context. Thanks!
