### ISSUE TITLE
Can we generate Terrafrom executable code from Teeragrant commands?

### ISSUE THREAD

**Issue by nillohitbanerjee** [gruntwork-io/terragrunt#1737]
Can we generate Terrafrom executable code from Teeragrant commands? or we need to write our own command form that ?

**Comment by yorinasub17** [comment]
Can you provide an example? Terragrunt does provide a way to monkey patch terraform modules (using `generate` blocks), but it doesn't work like a compiler (that is, there is no terragrunt command that only generates the terraform module without doing anything else).

**Comment by yorinasub17** [comment]
Closing as stale. If there is any follow up, please provide the requested context and happy to help/reopen. Thanks!
