### ISSUE TITLE
Respect `disable_checkpoint` flag from `.terraformrc` file.

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/terragrunt#1746]
Hey, a customer has asked whether we support this with terragrunt. I didn't find anywhere that we respect this file config or the `disable_checkpoint` flag itself. 

Is this something we want to support?

Context provided by the user:
```
disable_checkpoint — when set to true, disables upgrade and security bulletin checks that require reaching out to HashiCorp-provided network services.
```

and then the `.terraformrc` file:

```
cat ~/.terraformrc
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
disable_checkpoint = true
```

with `terragrunt plan` running:
```
terragrunt plan
Initializing the backend...
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/template...
- Finding latest version of hashicorp/aws...
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
hashicorp/template: could not connect to registry.terraform.io: Failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": context deadline
exceeded (Client.Timeout exceeded while awaiting headers)
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/aws:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)
ERRO[0022] 1 error occurred:
	* exit status 1
```

**Comment by tburow** [comment]
ty for opening this - this prevents us from operating in a closed network env

**Comment by tburow** [comment]
To workaround this - for now I am using the following settings

.terraformrc file
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
disable_checkpoint = true
provider_installation {
  filesystem_mirror {
    path    = "/home/tburow/.terraform.d/plugin-cache"
    include = ["registry.terraform.io/hashicorp/*"]
  }
}
tree .terraform.d
.terraform.d/
├── checkpoint_signature
└── plugin-cache
    ├── linux_amd64
    │   ├── terraform-provider-aws_v1.60.0_x4
    │   ├── terraform-provider-aws_v2.49.0_x4
    │   ├── terraform-provider-aws_v2.52.0_x4
    │   ├── terraform-provider-aws_v2.55.0_x4
    │   ├── terraform-provider-null_v2.1.2_x4
    │   ├── terraform-provider-postgresql_v1.4.0_x4
    │   └── terraform-provider-template_v2.1.2_x4
    └── registry.terraform.io
        ├── .well-known
        │   └── terraform.json
        └── hashicorp
            ├── aws
            │   └── 3.49.0
            │       └── linux_amd64
            │           └── terraform-provider-aws_v3.49.0_x5
            ├── local
            │   └── 2.1.0
            │       └── terraform-provider-local_v2.1.0_x5
            ├── null
            │   └── 3.1.0
            │       └── linux_amd64
            │           └── terraform-provider-null_v3.1.0_x5
            └── template
                └── 2.2.0
                    └── linux_amd64
                        └── terraform-provider-template_v2.2.0_x4

**Comment by brikis98** [comment]
```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding latest version of hashicorp/template...
- Finding latest version of hashicorp/aws...
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
hashicorp/template: could not connect to registry.terraform.io: Failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": context deadline
exceeded (Client.Timeout exceeded while awaiting headers)
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/aws:
could not connect to registry.terraform.io: Failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)
```

This output is 100% from Terraform. I don't think Terragrunt is involved at all; it doesn't do anything with `.terraformrc` settings or provider downloads. 

Best way to validate is to remove Terragrunt from the equation temporarily and run `terraform init`. I'm guessing the error will be the same.

As you have it working now, perhaps the solution is to add that `provider_installation` block, as you've shown. Marking this issue as closed.
