### ISSUE TITLE
`run-all plan` command with directories without pre-existing remote states stagnates cli

### ISSUE THREAD

**Issue by marshall7m** [gruntwork-io/terragrunt#1747]
**Versions:**
```
Terraform v1.0.2
terragrunt version v0.31.0
```

**Background:**

When running `aws-vault exec foo-profile -- terragrunt run-all plan --terragrunt-log-level DEBUG` on a directory tree like so:

```
├── bar
│   ├── main.tf
│   ├── provider_switches.hcl
│   └── terragrunt.hcl
├── baz
│   ├── main.tf
│   ├── provider_switches.hcl
│   └── terragrunt.hcl
├── doo
│   ├── main.tf
│   ├── provider_switches.hcl
│   └── terragrunt.hcl
├── foo
│   ├── main.tf
│   ├── provider_switches.hcl
│   └── terragrunt.hcl
```

The `doo`  directory successfully outputs the terraform plan since it already has a set s3 bucket remote backend. The other directories without pre-existing backends do not output their plan and the CLI stagnates even after 5 minutes without any timeout.

Here's how the remote state is created via a parent terragrunt.hcl file above the directory tree displayed above:

```
remote_state {
  backend = "s3"
  config = {
    bucket         = local.tf_state_bucket_name
    key            = "${path_relative_to_include()}/terraform.tfstate"
    dynamodb_table = local.tf_state_locking_db_table_name
    encrypt        = true
    region         = local.region
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
}
```

Here are the relevant logs pertaining to the directories that didn't output their plan:

```
ERRO[0001] Module /.../bar has finished with an error: exit status 1  prefix=[ /.../bar] 
ERRO[0002] Module  /.../foo has finished with an error: exit status 1  prefix=[ /.../foo] 
``` 

I'm guessing the cause of the stagnation is because the remote backend doesn't exist and Terragrunt is left hanging and continues to search for the non-existing backends. In this case, it would be great if the `run-all plan` command would prompt, `Remote state S3 foo-bucket does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)` for each non-existing backend as it would if you were to run `plan` within the specified directory. If that involves extensive rewiring of the internal functionality of how terragrunt works, maybe just a simple timeout that lets the user know that terragrunt looked for the specified remote backend but could not be found.

**Comment by yorinasub17** [comment]
We can certainly add a timeout here, but FWIW, the recommended solution to this is to run `terragrunt run-all init --terragrunt-non-interactive` on new projects to ensure the backends get initialized without interactive prompts.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered with a workaround provided. If there are any follow ups, please open a new ticket with updated context. Thanks!
