### ISSUE TITLE
terragrunt-source - Use original module path if not specified

### ISSUE THREAD

**Issue by phatcher** [gruntwork-io/terragrunt#1758]
Currently to run against the local module I have to put the full path e.g. --terragrunt-source c:/devel/myrepo//module, what would be nice is for terragrunt to infer the value after // if I don't specify it.

Given that something similar happens on run-all already and the info is in the original source parameter, I don't think this should be  difficult to implement.

Reason is that having to specify the module means that I can't use the command history in VSCode and I keep having to override the module name as I move between directories

This is similar to part of #444

**Comment by brikis98** [comment]
Does [`--terragrunt-source-map`](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-source-map) help here?

**Comment by yorinasub17** [comment]
Closing this as stale. If this is still an issue, please update with the relevant context and happy to help/reopen. Thanks!
