### ISSUE TITLE
terragrunt output <outputname> result in an error when 'required_var_files' is used in hcl

### ISSUE THREAD

**Issue by bmaltais** [gruntwork-io/terragrunt#1760]
As the title say, I ran into a bug when trying to obtain output values using:

`terragrunt output some-output-values`

if my .hcl file contain an extra argument of type `required_var_files` like in the sample code below:

```hcl
terraform {
  source = "../../../modules//${get_terragrunt_dir()}"

  extra_arguments "force_subscription" {
    commands = [
      "init",
      "apply",
      "destroy",
      "refresh",
      "import",
      "plan",
      "taint",
      "untaint",
      "output",
      "refresh",
      "show"
    ]
    env_vars = {
      ARM_SUBSCRIPTION_ID = local.rscfg.remote_state.subscription_id
    }
    required_var_files = [
      "${get_terragrunt_dir()}/L1.tfvars"
    ]
  }
}
```

The error generated by terragrunt 0.31.1 is:

```
╷
│ Error: Failed to parse command-line flags
│ 
│ flag provided but not defined: -var-file
╵

For more help on using this command, run:
  terraform output -help
ERRO[0000] 1 error occurred:
        * exit status 1
```

If I remove the extra argument from the hcl file I will then get the required output as expected. Obviously, this is not a solution as I need this extra argument to properly run my teragrunt apply commands...

I think terragrunt is passing terraform an unrequired argument "-var-file" when requesting an output. This "-var-file" is not expected by terraform and it result in the error I receive.

**Comment by brikis98** [comment]
You have `"output"` in the `commands` list of `force_subscription`, which also sets `required_var_files`. If you remove `"output"` from that list, I think this will fix your issue?

**Comment by bmaltais** [comment]
Well... you are correct. I must say I don't understand what the `force_subscription` section does as I used a copy of another hcl to tweak for this one... I better go read why I need it in the 1st place ;-)

Many thanks and sorry for wasting your time!
