### ISSUE TITLE
Unable to set terragrunt remote bucket encryption, access logging, etc.

### ISSUE THREAD

**Issue by jacoor** [gruntwork-io/terragrunt#1770]
Hello
A little background.
I have several AWS accounts under TG and TF control, some work started in the middle of 2019. Last account created in July 2021. 

terragrunt version v0.31.4

Here is my remote state conf:
```terraform
remote_state {
  backend = "s3"

  config = {
    bucket = "fn-terragrunt-state-${get_env("TF_VAR_region", "")}-${get_aws_account_id()}"
    accesslogging_bucket_name = "fn-terragrunt-state-${get_env("TF_VAR_region", "")}-${get_aws_account_id()}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "${get_env("TF_VAR_region", "")}"
    encrypt        = true
    dynamodb_table = "terragrunt-locks"
    enable_lock_table_ssencryption = true
  }
}

```
Now, on the most recent bucket missing is:
- access logging

On a bucket from 2019 missing is
- default encryption
- public access blocking
- bucket policy (enforce SSL only)

If I try to create new bucket for the state (change location in config) the bucket is created as expected, with all of the settings in place. 
When I run apply, init, etc, nothing changes on existing buckets. The only thing I was able to enforce was lock table encryption.

Expected behavior:
When running apply or init existing remote state bucket settings should be updated with the defined configuration that is:
- access logging
- default encryption
- public access blocking
- bucket policy (enforce SSL only)

My question is: is this a bug or expected behavior? If expected behavior, how can I enforce updating old buckets with new, proper settings?

Thank you!

**Comment by brikis98** [comment]
Currently, Terragrunt only creates and configures a remote state bucket if it doesn't exist already. If the bucket does exist, Terragrunt does not try to change its configuration. 

We _probably_ should support this behavior. If your `remote_state` config says the bucket should have some setting `X`, and Terragrunt sees that it doesn't, it should probably prompt you whether to update the bucket, and fix it if you say yes. Perhaps there should also be some flag to disable this behavior for users that manage their buckets outside of Terragrunt.

PRs welcome.

**Comment by jacoor** [comment]
Thanks @infraredgirl. I also think there is slight inconsistency there - when I set "enable_lock_table_ssencryption" it did update all my lock tables to use KMS w/o asking for permission.

**Comment by CarterSheehan** [comment]
+1 I'm experiencing this today on Terragrunt 0.36.6 (terraform 1.1.7). We have a large AWS organization consisting of over 80 accounts with several hundred accounts to be created when we're done migrating. In an existing dev environment, when changing the access logging settings the existing settings are not changed.

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.37.0
