### ISSUE TITLE
Allow shortening module path when ERRORs are logged

### ISSUE THREAD

**Issue by dennislapchenko** [gruntwork-io/terragrunt#1773]
When a error happens in a module, its and its dependencies absolute path is logged out miltiple times. This makes finding information rather difficult, especially on smaller screens. If paths could be optionally shrotened at least to git root, if is in git repo. Or allow variable depth.

Current (could be `TG_LOG_PATH_DEPTH=0`): `/Users/Steve/dev/org/repo/terragrunt/europe-west6/infra/k8s/apps/service/chartmuseum/terragrunt.hcl`
- `TG_LOG_PATH_DEPTH=3` = `../apps/service/chartmuseum/terragrunt.hcl`
- `TG_LOG_PATH_GIT_REPO` = `../infra/terragrunt/europe-west6/infra/k8s/apps/service/chartmuseum/terragrunt.hcl`

This:
```
$ terragrunt plan
ERRO[0000] Error processing module at '/Users/Steve/dev/org/repo/terragrunt/europe-west6/infra/k8s/apps/service/chartmuseum/terragrunt.hcl'. How this module was found: dependency of module at '/Users/Steve/dev/org/repo/terragrunt/europe-west6/infra/k8s/apps/service/chartmuseum/chart'. Underlying error: Error reading file at path /Users/Steve/dev/org/repo/terragrunt/europe-west6/infra/k8s/apps/service/chartmuseum/terragrunt.hcl: open /Users/Steve/dev/org/repo/terragrunt/europe-west6/infra/k8s/apps/service/chartmuseum/terragrunt.hcl: no such file or directory
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
could be this:
```
$ terragrunt plan
ERRO[0000] Error processing module at '../apps/service/chartmuseum/terragrunt.hcl'. How this module was found: dependency of module at '../apps/service/chartmuseum/chart'. Underlying error: Error reading file at path ../apps/service/chartmuseum/terragrunt.hcl: open ../apps/service/chartmuseum/terragrunt.hcl: no such file or directory
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Thanks!

**Comment by brikis98** [comment]
Agreed this would be a good idea. Thinking out loud:

1. What should the paths be shortened / relative to? The folder where you ran Terragrunt? The folder where the `terragrunt.hcl` file lives. This is especially important for `run-all` commands.
1. If we shortened it to the folder where `terragrunt.hcl` lives, then the relative paths would mean different things for different modules during `run-all`. You could even have ambiguity, where two relative paths are identical, but actually refer to different folders.
1. So probably, all paths should be relative to the folder from where you run Terragrunt.

PR welcome!
