### ISSUE TITLE
how to configure terragrunt in Github actions to create backend s3 bucket in IAM account and not the role assumed 

### ISSUE THREAD

**Issue by drey0143143** [gruntwork-io/terragrunt#1782]
I configured terragrunt to assume role which works very well but I found out that terragrunt create the backend s3 bucket in the IAM user account.How can I configure terragrunt to create the  backend bucket(s3) in the assume role account and not the IAM user account. I am using GitHub Actions workflows to run the process .some of my code are below

terragrunt.hcl

    remote_state {
        backend = "s3"
        config =
        bucket = "name of bucket"
        key    = "${path_relative_to_include()}/terraform.tfstate
        region = "us-east-1"
        encrypt = true 
        dynamodb_table = "my-lock-table"
}

    generate "provider" {
      path = "provider".tf
      if_exists = "overwrite_terragrunt"
      contents = <<EOF
     provider "aws" {
      assume_role {
        role_arn = "arn:aws:iam::123456789012:role/role_role

below is my GitHub Action YAML 

name: 'Terragrunt GitHub Actions'
on:
  pull_request:
      branches:
       -test
env:
 tf_version: 'latest'
 tg_version: 'latest'
 tf_working_dir: '.'

jobs:
  terragrunt:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
steps:
   - name: 'checkout'
     uses: actions/checkout@master
  -  name: 'Terragrunt Init'
     uses: the-commons-project/terragrunt-github-actions@master 
     with:
      tf_actions_version: ${{ env.tf_version }}
      tg_actions_version: ${{ env.tg_version }}
      tf_actions_subcommand: 'init'
      tf_actions_working_dir: ${{ env.tf_working_dir }}
      tf_actions_comment: true
env:
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      TF_INPUT: false

**Comment by yorinasub17** [comment]
You need to set the assume role settings on the `remote_state` block (see [the config reference, under the section "for s3"](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state) as well. You can also consider using [iam_role setting](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#iam_role) to let Terragrunt do the assume role.

One of those two should resolve this for you.
