### ISSUE TITLE
`mock_outputs_merge_with_state` ignores `mock_outputs_allowed_terraform_commands`

### ISSUE THREAD

**Issue by stevie-** [gruntwork-io/terragrunt#1783]
Terraform version: 0.14.11
Terragrunt version: 0.31.6

When we set the new option `mock_outputs_merge_with_state` we see that the setting for `mock_outputs_allowed_terraform_commands` is ignored

```hcl

dependency "lambda_function_authorizer" {
  config_path = "../../lambda_function/api-auth"

  # mock output, if state hasn't run yet
  mock_outputs_allowed_terraform_commands = [ "validate" ]  # only allow mocks  for validate command
  mock_outputs_merge_with_state           = true
  mock_outputs = {
    lambda_function_name          = "Mock"
  }
}

inputs = {
  aws_lambda_function_authorizer_invoke_name  = dependency.lambda_function_authorizer.outputs.lambda_function_name
}
```

If we run `plan` or `apply` and the output of the dependency is mocked (merge = true) we see the mocked result.

Is this behaviour intended or should `mock_outputs_merge_with_state` follow only the tf commands listed in `mock_outputs_allowed_terraform_commands`?
We've had expected the latter.

**Comment by brikis98** [comment]
This is a question for @yorinasub17.

**Comment by yorinasub17** [comment]
This is indeed a bug. Opened https://github.com/gruntwork-io/terragrunt/pull/1800 to address this
