### ISSUE TITLE
Using MFA with terragrunt 

### ISSUE THREAD

**Issue by drey0143143** [gruntwork-io/terragrunt#1789]
I am running my workflow using GitHub Actions and I need terragrunt to assume a role but to assume the role ,MFA is required. Please how can I dynamically configure terragrunt to authenticate (mfa) to assume the role.

**Comment by brikis98** [comment]
MFA and automation don't typically go together. MFA devices are typically used by humans; machine users don't usually have multiple factors (e.g., an iPhone or key fob) to work with, right?

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
