### ISSUE TITLE
get_aws_caller_identity_arn with AWS credentials profile

### ISSUE THREAD

**Issue by keiransteele** [gruntwork-io/terragrunt#1790]
When using get_aws_caller_identity_arn is it possible to provide a credential profile rather than defaulting to the default profile?

We've got nearly 20 accounts and the account Terraform/Terragrunt file structure is generate from scripts and templates including the terragrunt.hcl files.

I want to use get_aws_caller_identity_arn to create user specific naming and tagging for test environments but there is no way to provide the AWS SSO profile that should be used.

It's possible to set the default profile using ```export AWS_DEFAULT_PROFILE=profilename``` but I don't want users to have to remember this step as part of their workflow. I tried using a before hook to set the env var but they don't work as they don't run before locals are evaluated.

Thanks.

**Comment by brikis98** [comment]
Currently, no, the function uses whatever creds are present in the environment: i.e., env vars, AWS config, IAM role.
