### ISSUE TITLE
Problem with TGEnv and TFEnv

### ISSUE THREAD

**Issue by sujitknandan** [gruntwork-io/terragrunt#1792]
We are trying to use tgenv and tfenv in order to use multiple version of terraform. We are using the following command 
 TGENV_AUTO_INSTALL=true terragrunt run-all plan

but we are facing that sometimes we are getting error 126 from terragrunt. Searching for the error we found out that it has something to due with permission of executable. Is there a race condition happening when tgenv/tfenv is trying to download the correct version based on .terraaform-version/.terragrunt-version and the control going to terragrunt before executable  permission is set.

When i check with output of tfenv list and tgenv list, its showing that its downloaded the correct version of terragrunt and terraform and also enabled it based on folder. But somehow terragrunt run-all plan its giving following error for some module.

 => Module _global/security-auditor-role (excluded: false, dependencies: []) 
ERRO[0014] Module _global/aws-securityhub has finished with an error: exit status 126  prefix=[_global/aws-securityhub]

INFO[0131] .tfenv/libexec/tfenv-exec: line 105: .tfenv/versions/0.14.7/terraform: Permission denied
.tfenv/libexec/tfenv-exec: line 105: exec: .tfenv/versions/0.14.7/terraform: cannot execute: Permission denied 

Isnt TFenv and TGenv recommended way of working with multiple version of terragrunt and terraform? Are there any other option because we want the auto install feature of tfenv and tgenv.

**Comment by brikis98** [comment]
This is probably a better question for the `tgenv` or `tfenv` projects, both of which are independent from Terragrunt. I'm not sure how they auto install the binaries and what timing issues are possible, so better to go to the source. Sorry we can't be of more help here!
