### ISSUE TITLE
how to get root dir within include's path?

### ISSUE THREAD

**Issue by dudicoco** [gruntwork-io/terragrunt#1794]
Hi,

First, thanks for the new awesome deep `merge_strategy` feature!
Finally I can make our `terragrunt.hcl` files DRY.

In order to load a common `hcl` file, I would like to use something like the following:
```hcl
include {
  path           = "${get_parent_terragrunt_dir()}/common/common.hcl"
  merge_strategy = "deep"
}
```

However, the `get_parent_terragrunt_dir` function doesn't work within the `include` block.
Is there a way to get the root dir within the `include` block's `path` value?

**Comment by brikis98** [comment]
We typically use [`find_in_parent_folders`](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders) to solve this. If the file you need is in the parent folder itself, it's easy: `find_in_parent_folders("common.hcl")`. If it's in a sub-folder of a parent folder, then pick some target that's easy to target in the parent folder, and build a path off that: e.g., `find_in_parent_folders("some-file-in-root.hcl")/../common/common.hcl`.

**Comment by dudicoco** [comment]
Thanks @brikis98, I am familiar with `find_in_parent_folders()` but I was hoping that there was a cleaner solution.

`find_in_parent_folders()/../common/common.hcl` did not work, as it resolves to `/root/terragrunt.hcl/../_common/k8s/common.hcl`.
I was able to solve this by using the [dirname](https://www.terraform.io/docs/language/functions/dirname.html) function:
`"${dirname(find_in_parent_folders())}/common/common.hcl"`
