### ISSUE TITLE
 download not supported for scheme 'tfr'

### ISSUE THREAD

**Issue by lcorsini** [gruntwork-io/terragrunt#1805]
first time terragrunt user
terraform ver 1.0.4
terragrunt ver 0.31.4

I'm trying to use a module from terraform registry, if I use this:
terraform {
  source  = "tfr:///terraform-google-modules/network/google/modules/vpc?version=3.4.0"
}
I get the error above: download not supported for scheme 'tfr'

If in the source I put the full https url it download the module code but terraform doesn't apply anything

**Comment by brikis98** [comment]
Support for the Terraform Registry and `tfr:///` protocol was added in v0.31.5: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.5.

**Comment by yorinasub17** [comment]
Closing this as the original question has been answered. If there are any follow ups, please open a new ticket with updated context. Thanks!
