### ISSUE TITLE
TerragruntVersionConstraints configuration in hcl is ignored for dependencies

### ISSUE THREAD

**Issue by pulchart** [gruntwork-io/terragrunt#1812]
**terragrunt version**: all

**Issue**: TerragruntVersionConstraints configuration in hcl is ignored when running terraform init/output for dependency modules.

**Description**:
terraform init/output is executed at depenency modules without checking any Version Constraints (terragrunt_required_version, terraform_required_version, terraform_binary) attributes and runs all the time default terraform.

**Reproducer**:

1/ Have a /usr/bin/terarform-1 as link to latest terraform-1.0.7 and /usr/bin/terarform binary as a link to some older version (like 0.14, 0.13, whatever)
2/ Use hcl environment with some dependencies all dependencies uses `terraform_binary = "terarform-1"`
3/ run terragrunt with debug `terragrunt plan --terragrunt-log-level debug 2>&1 | tee plan.log` 
4/ grep plan.log for "msg=Running command:"

The dependencies will use default terraform path instead of using terraform-1:
```
... level=debug msg=Running command: terraform init ...
... level=debug msg=Running command: terraform output ...
```

**Comment by pulchart** [comment]
This is fixed by https://github.com/gruntwork-io/terragrunt/pull/1813

**Comment by yorinasub17** [comment]
Thanks for closing the loop! Closing now.
