### ISSUE TITLE
Getting "Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]" Error After Terragrunt Upgrade

### ISSUE THREAD

**Issue by johnsmith-coder** [gruntwork-io/terragrunt#1815]
Hi there, I have just upgraded my Terragrunt version from v0.28.16 to the latest version v0.32.2. I noticed in the Releases page that v0.31.10 (released 8 days ago) has a feature described as 'Terragrunt will now show an error if source or dependencies are referencing a folder that doesn't exist.' which probably explains the error I'm now starting to get since I upgraded Terragrunt, however I don't how to fix it.

First of all, this is the error I get when I execute 'terragrunt run-all plan --terragrunt-non-interactive' in my project's root folder: 

```
* Cannot process module Module C:/projects/terragrunt-config/dev/eu-west-1/test/applications/gateway/service-discovery-services (excluded: false, dependencies: [C:/projects/terragrunt-config/dev/eu-west-1/test/shared/service-discovery-core]) because one of its dependencies, Module C:/projects/terragrunt-config/dev/eu-west-1/test/shared/service-discovery-core (excluded: false, dependencies: [C:/projects/terragrunt-config/dev/eu-west-1/test/shared/vpc]), finished with an error: Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Cannot process module Module C:/projects/terragrunt-config/dev/eu-west-1/test/applications/gateway/efs-file-systems (excluded: false, dependencies: [C:/projects/terragrunt-config/dev/eu-west-1/test/shared/vpc, C:/projects/terragrunt-config/dev/eu-west-1/test/shared/efs-core]) because one of its dependencies, Module C:/projects/terragrunt-config/dev/eu-west-1/test/shared/efs-core (excluded: false, dependencies: [C:/projects/terragrunt-config/dev/eu-west-1/test/shared/vpc]), finished with an error: Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Cannot process module Module C:/projects/terragrunt-config/dev/eu-west-1/test/applications/gateway/alb-listener-rules (excluded: false, dependencies: [C:/projects/terragrunt-config/dev/eu-west-1/test/shared/vpc, C:/projects/terragrunt-config/dev/eu-west-1/test/shared/alb-core]) 
because one of its dependencies, Module C:/projects/terragrunt-config/dev/eu-west-1/test/shared/alb-core (excluded: false, dependencies: [C:/projects/terragrunt-config/dev/eu-west-1/test/shared/vpc]), finished with an error: Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]
* Found paths in the 'dependencies' block that do not exist: [../vpc (vpc)]

time=2021-09-17T12:53:14+01:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Here is my project folder layout (every folder has a terragrunt.hcl file in it):

```
C:.
├───applications
│   └───gateway
│       ├───alb-listener-rules
│       ├───cloudwatch-logs
│       ├───efs-file-systems
│       └───service-discovery-services
└───shared
    ├───alb-core
    ├───ec2
    ├───ecs
    ├───efs-core
    ├───nlb
    ├───rds
    ├───service-discovery-core
    └───vpc
```

A brief explanation of the dependency layout: All the terragrunt.hcl files in module folders under the 'shared' folder are dependent on the 'vpc' folder at the same level as themselves and define 'dependency' and 'dependencies' blocks as follows:

```
dependency "vpc" {
  config_path = "../vpc"

  mock_outputs = {
    vpc = {
      vpc_id = "mocked-vpc-id"
    }
  }
}

dependencies {
  paths = ["../vpc"]
}

...etc
```

And all the terragrunt.hcl files in module folders under the 'applications' folder are dependent on various modules in the 'shared' folder and define 'dependency' and 'dependencies' blocks as follows, eg here it is for the /applications/gateway/service-discovery-services/terragrunt.hcl:

```
dependency "service_discovery_core" {
  config_path = "../../../shared/service-discovery-core"

  mock_outputs = {
    service_discovery_private_dns_namespace = {
      id = "mocked-id"
    }
  }
}

dependencies {
  paths = ["../../../shared/service-discovery-core"]
}

...etc
```

So in simple terms, the 'service-discovery-services' module depends on the 'service-discovery-core' module which in turn depends on the 'vpc' module. Or in more specific terms, the '/applications/gateway/service-discovery-services' module depends on the '/shared/service-discovery-services' module by specifying '../../../shared/service-discovery-core' in its 'dependencies' block, and the '/shared/service-discovery-services' module depends on the '/shared/vpc' module by specifying '../vpc' in its 'dependencies' block. 

Clearly Terragrunt v0.32.2 is complaining that it can't find the '../vpc' module (which definitely exists), yet Terragrunt v0.28.16 can execute 'run-all plan' and 'run-all apply' perfectly without any errors.

I suspect that either there is a bug in the newer release of Terragrunt or else I have to redefine my dependencies differently but its not clear what's wrong as these paths are definitely correct.

Can anyone offer some advise please? Thank you.

**Comment by denis256** [comment]
Hi  @johnsmith-coder
I tried to create a test project with similar structure and test issue, however, for my case, it worked fine... no errors about missing modules

```
$ terragrunt --version
terragrunt version v0.32.2

$ terragrunt run-all plan --terragrunt-non-interactive
...
Terraform has been successfully initialized!
```

Here is the repository with the test project: https://github.com/denis256/terragrunt-test-1815
Maybe did set up in a different way?

In parallel, I will try to test on Windows environment

**Comment by denis256** [comment]
Found that on Windows environment issue is happening... will try to investigate and fix

**Comment by infraredgirl** [comment]
Fixed in #1816.

**Comment by infraredgirl** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.32.3

**Comment by johnsmith-coder** [comment]
Hi @denis256 and @infraredgirl, I have just downloaded and tested [v0.32.3](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.32.3) and can confirm that this issue has been fixed! Thanks very much for fixing it so quickly!
