### ISSUE TITLE
Ensure minimum Terragrunt version

### ISSUE THREAD

**Issue by robkinyon** [gruntwork-io/terragrunt#182]
(From #172)

To ensure consistent versioning across a team, please provide a way to specify the minimum Terragrunt version within configuration.

**Comment by brikis98** [comment]
Thanks!

**Comment by brikis98** [comment]
Probably the best way to handle this is with two new settings in the Terragrunt configuration:

```hcl
terragrunt = {
  terragrunt_version_constraint = ">= 0.12.0"
  terraform_version_constraint = ">= 0.9.3"
}
```

**Comment by robkinyon** [comment]
@brikis98 What about just the following with `_constraint`?

```
terragrunt = {
  terragrunt_version = ">= 0.12.0"
  terraform_version = ">= 0.9.3"
}
```

I think that reads better.

**Comment by brikis98** [comment]
Agreed, that's cleaner.

**Comment by brikis98** [comment]
We now have:

1. [`terragrunt_version_constraint`](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terragrunt_version_constraint)
1. [`terraform_version_constraint`](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_version_constraint)
