### ISSUE TITLE
Initialize list with `run_cmd`

### ISSUE THREAD

**Issue by tomasgareau** [gruntwork-io/terragrunt#1820]
Is there any way to initialize a list-type variable with `run_cmd`?

For example, say I had a directory structure like:
```bash
.
├── dir/
│   ├── subdir1/
│   └── subdir2/
└── thing/
    └── terragrunt.hcl
```

where `dir` has some subdirectories whose names I'm interested in.

In `thing/`, I'd like to do something like:

```hcl
locals {
  subdirs = [
    run_cmd("ls", "${get_terragrunt_dir()}/../dir")
  ]
}
```

but this gives me:
```hcl
subdirs = "subdir1\nsubdir2"
```

rather than:
```hcl
subdirs = ["subdir1", "subdir2"]
```

**Comment by yorinasub17** [comment]
Try the following:

```
locals {
  subdirs = split("\n", run_cmd("ls", "${get_terragrunt_dir()}/../dir"))
}
```

**Comment by tomasgareau** [comment]
Thanks @yorinasub17, that works like a charm!
