### ISSUE TITLE
No binaries for v0.32.5 release

### ISSUE THREAD

**Issue by Chuxel** [gruntwork-io/terragrunt#1829]
We have some automated processes that get the latest version of terragrunt for use in developer environments that are bombing at the moment because of this issue.

**Comment by siunb** [comment]
Same here

**Comment by yorinasub17** [comment]
Ah apologies for the error here. The binaries are available now! Also opened a PR for a more permanent fix here: https://github.com/gruntwork-io/terragrunt/pull/1830

**Comment by siunb** [comment]
Thanks so much @yorinasub17
