### ISSUE TITLE
Terragrunt v0.12.6 remote state s3 backend

### ISSUE THREAD

**Issue by ltartarini90** [gruntwork-io/terragrunt#183]
Hi,

First of all thank you for your effort. Today I tried the new patch, downloading Terraform v0.9.3 with Terragrunt v0.12.6 trying to migrate all my templates. Unfortunately, the remote state files are not uploaded to S3 buckets. In particular, this is my terraform.tfvars file:

terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket     = "my-bucket"
      key        = "my-folder/terraform.tfstate"
      region     = "eu-west-1"
      encrypt    = true
      lock_table = "terragrunt_locks"
    }
  }
  terraform {
    source = "git::my-source"
  }
}
access_key = ""
secret_key = ""
aws_region = ""

Then I run the following commands:
- terragrunt plan --terragrunt-source-update
- terragrunt apply

The tfstate file is saved in my temp directory instead of s3 bucket. I get this output from CLI:

$ terragrunt apply
[terragrunt] [C:\...] 2017/04/24 14:07:18 Running command: terraform --version
[terragrunt] 2017/04/24 14:07:19 Reading Terragrunt config file at C:/.../terraform.tfvars
[terragrunt] 2017/04/24 14:07:19 Terraform files in C:/.../terragrunt-download/xg503kJNvTVMtqN2JAmhZHXKe-4=/UnhX7_f3VZm_gKKqTdGLRsX55eg=/... are up to date. Will not download again.
[terragrunt] 2017/04/24 14:07:19 Copying files from C:/.../test into C:/.../Temp/terragrunt-download/xg503kJNvTVMtqN2JAmhZHXKe-4=/UnhX7_f3VZm_gKKqTdGLRsX55eg=/...
[terragrunt] 2017/04/24 14:07:19 Setting working directory to C:/.../Temp/terragrunt-download/xg503kJNvTVMtqN2JAmhZHXKe-4=/UnhX7_f3VZm_gKKqTdGLRsX55eg=/...
[terragrunt] 2017/04/24 14:07:19 Initializing remote state for the s3 backend
[terragrunt] 2017/04/24 14:07:19 Configuring remote state for the s3 backend
[terragrunt] 2017/04/24 14:07:19 Running command: terraform init -backend-config=bucket=my-bucket -backend-config=key=my-folder/terraform.tfstate -backend-config=region=eu-west-1 -backend-config=encrypt=true -backend-config=lock_table=terragrunt_locks
Downloading modules (if any)...
Get: s3::https://s3-eu-west-1.amazonaws.com/s3-bucket/my-module.tar.gz

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your environment. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2017/04/24 14:07:20 Running command: terraform apply
module.eb_application.aws_elastic_beanstalk_application.eb_application: Creating...
  name: "" => "test"
module.eb_application.aws_elastic_beanstalk_application.eb_application: Creation complete (ID: test)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path:

As you can see the state path is null.

Please, let me know if I miss anything.

Regards,

Luca Tartarini

**Comment by brikis98** [comment]
Did you add the `backend` block to your Terraform configurations (`.tf` files)?

```hcl
terraform {
  backend "s3" {}
}
```

**Comment by ltartarini90** [comment]
It works great! I think I skipped the section of the README that explains it. 

Thank you,

Luca

**Comment by brikis98** [comment]
Great!
