### ISSUE TITLE
before_hook fails on run-all apply but not on standard apply

### ISSUE THREAD

**Issue by awiesner4** [gruntwork-io/terragrunt#1834]
We have a fairly large set of layered directories for our terragrunt configurations, and often run cross-cloud terraform, while maintaining all state in AWS S3.

One issue we need to code against is making sure that the terragrunt being run is in the right environment/account for where it's applying resources.  If it's not, but connected to AWS S3 and the correct backend, terraform will run and assume the resources don't exist, say they are deleted, and clear the TF State file.  While we can preserve the older state file with bucket versioning, we'd also like to just have a `before_hook` check that we're in the right environment.

We have created a before hook, like so:
```  
before_hook "validate_azure_env" {
    commands    = ["apply", "destroy", "plan"]
    execute     = ["./validate-acct.sh", "azure", "${local.azure_account_alias}"]
    working_dir = "${path_relative_from_include()}/tools"
  }
  ```
  
Per the above, the script resides in the top/root directory inside the 'tools' folder.  Every `terragrunt.hcl` that we're applying has the following include:
  
  ```
include {
    path = find_in_parent_folders("root.hcl")
}
```

When I run `terragrunt apply` in a module directory, everything works as expected.

However, when I run `terragrunt run-all apply` from a parent folder to run multiple modules, all calls to the script fail:

```
Error running hook validate_azure_env with message: chdir ../../../../../tools: no such file or directory  prefix=[/Users/awiesner/git-v2/ego-infra/azure/staging/eastus2/aws/route53]
```

This shows up for each module (with the pathing adjusted, as appropriate for it's location in the folder hierarchy) and the paths are actually correct based on the location of the module.

My assumption here is that the underlying module is correctly triangulating where the `validate-acct.sh` file is in relation to the terragrunt config, but the `chdir` command being run is not happening from that module directory, but from where `terragrunt run-all apply` is being run.

**Comment by yorinasub17** [comment]
Are you trying to get to the directory where the `root.hcl` is defined? If so, [get_parent_terragrunt_dir](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_parent_terragrunt_dir) is the right function for this, not `path_relative_from_include`, as that returns an absolute path.

**Comment by awiesner4** [comment]
Thank you, @yorinasub17.  My misunderstanding in reading the docs.
