### ISSUE TITLE
No binaries for v0.33.2

### ISSUE THREAD

**Issue by GregoryVds** [gruntwork-io/terragrunt#1838]
Binaries are missing on the new release, hence this is breaking our build.
Thanks for the good work!

**Comment by lorengordon** [comment]
Binaries are there now. Even when it's always working, I think the tag is created first, then the binaries post. So there's always some amount of time where they won't be available. Might be worth pinning your build and using another tool to update the version.

**Comment by yorinasub17** [comment]
@lorengordon Is correct. There is always a ~10 minute delay for the binaries to show up after the tag as we wait for CircleCI to compile and publish them.

**Comment by GregoryVds** [comment]
@lorengordon  @yorinasub17  Thanks for the explanation ! I will make sure to be more patient next time :-)
