### ISSUE TITLE
Terragrunt is not making a local state file

### ISSUE THREAD

**Issue by JordyWTC** [gruntwork-io/terragrunt#1841]
Hi,

I am using terragrunt version : v0.28.18 and when i am doing an apply from any folder, there is not tfstate file created.
in the main folder called wtcnl the terragrunt.hcl is defined  : 
```
remote_state {
    backend = "local"
    config  = {
        path    = "${path_relative_to_include()}/terraform.tfstate"
    }
}
```
and in every subfolder (example wtcnl/repository) i have a tfstate.tf file containing : 
```
terraform {
  backend "local" {}
}
```
I expect that a tfstate file is being created in the folder wtcnl/repository when running a terragrunt apply from the folder wtcnl/repository.

**Comment by yorinasub17** [comment]
> I expect that a tfstate file is being created in the folder wtcnl/repository when running a terragrunt apply from the folder wtcnl/repository.

`path_relative_to_include` returns a relative path, and relative paths in the backend config will be relative to the terraform working dir (the folder in `.terragrunt-cache`), NOT the terragrunt folder (where `terragrunt.hcl` exists).

To get this effect, try the following:

```
remote_state {
    backend = "local"
    config  = {
        path    = "${get_terragrunt_dir()}/terraform.tfstate"
    }
}
```

`get_terragrunt_dir` will return the full path to where the child `terragrunt.hcl` exists, so you should end up with the state file in the right folders, assuming each child folder has a `terragrunt.hcl` file (e.g., you have `wtcnl/repository/terragrunt.hcl`).

**Comment by JordyWTC** [comment]
> > I expect that a tfstate file is being created in the folder wtcnl/repository when running a terragrunt apply from the folder wtcnl/repository.
> 
> `path_relative_to_include` returns a relative path, and relative paths in the backend config will be relative to the terraform working dir (the folder in `.terragrunt-cache`), NOT the terragrunt folder (where `terragrunt.hcl` exists).
> 
> To get this effect, try the following:
> 
> ```
> remote_state {
>     backend = "local"
>     config  = {
>         path    = "${get_terragrunt_dir()}/terraform.tfstate"
>     }
> }
> ```
> 
> `get_terragrunt_dir` will return the full path to where the child `terragrunt.hcl` exists, so you should end up with the state file in the right folders, assuming each child folder has a `terragrunt.hcl` file (e.g., you have `wtcnl/repository/terragrunt.hcl`).

This works for me! Thanks you!
