### ISSUE TITLE
Terragrunt run-all show plan json behaves different

### ISSUE THREAD

**Issue by imti283** [gruntwork-io/terragrunt#1848]
I have below directory structure
```
\---backend
    \---us-west-2
        \---pro
            +---app1
            |   \---
            +---app2
            |   \---
            \---app3
                \---
```

I am running this command at backend directory -
```
terragrunt run-all plan -out plainplan.txt
terragrunt run-all show -json plainplan.txt > plainplanall.json
```
I am hoping second command should generate a combined plan.json file taking plainplan.txt from all directory(i.e app1,app2..etc) in backend directory. But seems terragrunt stops after going into one directory. I am seeing changes from only one directory in plainplanall.json.

I am expecting second command should read all plainplan.txt, merge them and generate one json file. Am I expecting something wrong or doing something wrong.

**Comment by imti283** [comment]
Well, I was able to fix it by doing something like this in PowerShell -

```
$val = terragrunt run-all show -json plan.out
foreach ($v in $val.GetEnumerator()) { 
$curr = $v | ConvertFrom-Json
    foreach ($rc in $curr.resource_changes) { 
        $obj = New-Object psobject -Property @{`
            "Project"      = $curr.variables.application_op.value;
            "Action"       = $rc.change.actions
            "ResourceType" = $rc.type;
            "Adress"       = $rc.address
        }
        $returnObj += $obj
    }
}

$newtab = $returnObj | ? { $_.Action -notmatch "no-op" } | Select Project, Action, Adress, ResourceType
```

My assumption was  `all.json` should contain a single json object having all value merged under single `resource_changes` block. That way it will be easier to parse and group all changes. Anyway, Thanks a lot.

**Comment by karamuz** [comment]
Is there a way to include where the json entry came from? I would like to match each terragrunt dir with the corresponding json plan.
