### ISSUE TITLE
Terragrunt should check your Terraform code defines a backend

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#186]
A common problem that has been hitting a few Terragrunt users is that they define a `remote_state` block in their Terragrunt configuration, but forget to specify a `backend` in their Terraform configurations (`.tf`). As a result, Terragrunt makes it look like it's configuring your `backend`, but Terraform ignores those configurations completely.

If a `remote_state` block is defined, Terragrunt should do a simple `grep` through the `.tf` source files to look for `backend "XXX"` and make sure that the `XXX` matches the backend `type` specified in `remote_state`. If either check fails, Terragrunt should exit with an error.

**Comment by zot24** [comment]
👍 

On the logs when running Terragrunt you can check if the S3 backend configuration worked properly just to be sure it worked useful while these feature it's implemented.

```
Initializing the backend...


Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
```

**Comment by brikis98** [comment]
Whoops, looks like I filed the same bug twice. This is a dupe of #212.
