### ISSUE TITLE
run-all equivalent, but based on graph and not folder tree

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terragrunt#1862]
Consider our reference architecture, where we have multiple modules in the `services` folder that deploy into the EKS cluster that are adjacent to each other. In a full deployment, the `services` folder also contains other modules that are not related to the EKS cluster.

Suppose you want to destroy the EKS cluster only. Ideally, you would be able to use `run-all destroy` to destroy EKS cluster and all the dependents in order, but in the above setup, that could accidentally include other modules that you don't want to destroy.

Instead, what you want is something like a graph prune logic, where you want to destroy the EKS cluster and all of its dependents.

This most likely needs to be a new command other than `run-all`, something like `destroy-graph`, such that if you run `terragrunt destroy-graph` in the `eks-cluster` folder, it will destroy all the modules that deploy in to the EKS cluster and the cluster itself, in the right order.

**Comment by denis256** [comment]
Added support for execution of commands on graph of dependencies in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.0
