### ISSUE TITLE
dynamodb locking table needs to be recreated for 0.12.x

### ISSUE THREAD

**Issue by grimm26** [gruntwork-io/terragrunt#187]
When upgrading my configs for terragrunt 0.12.x and terraform 0.9.x, I hit a problem when running a `terragrunt plan` where it gives me a state locking error:

```
[terragrunt] 2017/04/24 16:18:53 Running command: terraform plan
Error locking state: Error acquiring the state lock: 2 error(s) occurred:

* ValidationException: One or more parameter values were invalid: Missing the key StateFileId in the item
        status code: 400, request id: 4F1E6E59PHP5A664RUM02NJH13VV4KQNSO5AEMVJF66Q9ASUAAJG
* ValidationException: The provided key element does not match the schema
        status code: 400, request id: M1HEMGS1HQRJJOLT54A6OJOOT7VV4KQNSO5AEMVJF66Q9ASUAAJG

Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.
[terragrunt] 2017/04/24 16:18:54 exit status 1
```
It seems like it doesn't like the primary key of `StateFileId`.  If I delete the table and let terragrunt/terraform recreate it, the new primary key is `LockID` and everything works.

I see these options:

1. In the README, have the user specify a new `lock_table` name when migrating from 0.11.x to 0.12.x
2. In the README, have the user delete the existing DynamoDB table right before running the first `terragrunt plan` with the upgraded config/binary.
3. Have terragrunt detect the incorrect primary key on the first run and recreate the table itself.

What say ye?  Am I the only one that hit this?

**Comment by brikis98** [comment]
Ah, you're right. I was just using a totally new lock table name, but if you reuse the old one, Terragrunt isn't smart enough to recreate that table's primary key. 

I've updated the migration docs to explicitly specify that you should use a new lock table name: https://github.com/gruntwork-io/terragrunt/commit/d455c3a252d802e12b04df75c7995ad7f5f7165a.
