### ISSUE TITLE
Terragrunt support for "experiment" attribute in terraform block

### ISSUE THREAD

**Issue by Nods2008** [gruntwork-io/terragrunt#1882]
Hi,

In order to use optional attributes in object type variables such as:
```
type = object({
  param1 = string
  param2 = optional(number)
})

```
terraform requires this line in the terraform block:

```
terraform {
  ......
  experiments = [module_variable_optional_attrs]
}
```

But after adding that line to the terraform block in the root terragrunt.hcl of my project, I get this error:

> ERRO[0000] _**-current directory-**_/terragrunt.hcl:6,5-16: Unsupported argument; An argument named "experiments" is not expected here.
> ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1

The problem here is terragrunt doesn't try running the terraform code at all. After going into the .terragrunt-cache folder, adding the "expirments ..." line, terraform produces the following warning 

> Warning: Experimental feature "module_variable_optional_attrs" is active

But the difference is it doesn't exit immediately.

Is there a way to workaround this error within terragrunt's framework?

Thanks,
Nour

Relevant content of my root terragrunt.hcl:
```
terraform {
    source = "${get_parent_terragrunt_dir()}/common/"
    experiments = [module_variable_optional_attrs]
}
```

**Comment by yorinasub17** [comment]
The `experiments` attribute needs to be set on the `terraform` block **in the terraform source**, not in `terragrunt.hcl`.
So you need to either set that within the module you are calling, or generate a `terraform` block using the [generate block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate).
