### ISSUE TITLE
Skip terragrunt info output

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [gruntwork-io/terragrunt#1883]
Apologies for posting a rather non-issue here, but I took the initiative after reading [this](https://terragrunt.gruntwork.io/docs/community/support/#github-issues), that imho encourages (at least does not directly discourage) asking for help here.

My problem is that no matter what `terragrunt` command I execute, it always starts with the following lines:

```
$ terragrunt show --json outfile 2>/dev/null
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.31.10
```

```
$ terragrunt terragrunt-log-level=error plan
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.31.10
```

I assumed that setting log level to `error` would perhaps help skipping those 2 lines.

Especially in the first case where I need a pure json `stdout` for me to parse, this causes problems.

Any ideas?

**Comment by bjtox** [comment]
we have same issue with same behaviour
