### ISSUE TITLE
ZSH outputting error when using get_env during destroy

### ISSUE THREAD

**Issue by stephenliberty** [gruntwork-io/terragrunt#1887]
Hi - so, I'm not really familiar with zsh, but I confirmed that this was happening with a zsh shell user and wasn't happening to a bash shell user. 

Anyway, I have a block:

```hcl

locals {
  gitlab_address   = "https://<snip>/api/v4/projects/${get_env("GITLAB_PROJECT_ID")}/terraform/state/${replace(path_relative_to_include(), "/", "_")}"
}

```

There is a variable set in my environment for GITLAB_PROJECT_ID. However, I get the following error when I try to run a destroy: 

> Call to function "get_env" failed: EnvVarNotFound: Required environment variable GITLAB_PROJECT_ID - not found.

The error seems to be a red herring. It doesn't actually exit the program and it does seem to update the state appropriately. 

I'm not sure what other information to provide that would be useful. I don't think that this zsh profile is doing anything "odd". Apply seems to work without issue, as does plan.

**Comment by denis256** [comment]
After PR https://github.com/gruntwork-io/terragrunt/pull/1889 I don't see the issue to appear
