### ISSUE TITLE
Using TFR protocol sources with third-party registry providers reporting absolute urls is not working

### ISSUE THREAD

**Issue by spr-mweber3** [gruntwork-io/terragrunt#1895]
Hey there, we're using the Terraform Module Registry from Spacelift and want to use the added support for third-party module registries introduced with version [0.31.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.5). With version [0.31.9](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.9) Terragrunt supports Terraform registries, such as GitLab, that return relative paths. Not all third party providers do that.

Note how the .well-known/terraform.json reports absolute full URLs rather than relative paths - https://spacelift.io/.well-known/terraform.json.

This leads to the following error for us:

```
ERRO[0002] 1 error occurred:
	* error downloading 'tfr://spacelift.io/spring-media/maps-terraform-aws-elastic-ip?version=0.1.1': Error downloading module from https://spacelift.io/https:/app.spacelift.io/registry/modules/v1/spring-media/maps-terraform-aws-elastic-ip/0.1.1/download: error recieving HTTP data

ERRO[0002] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

The url
> https://spacelift.io/https:/app.spacelift.io/registry/modules/v1/spring-media/maps-terraform-aws-elastic-ip/0.1.1/download

is constructed incorrectly.

The problem seems to originate from [here](https://github.com/gruntwork-io/terragrunt/pull/1767/files#diff-2775841193536f9771363fbc0d5e76f8bf3ba22b7b0ac049ece09a529370584dR131-R141).

So the fix in https://github.com/gruntwork-io/terragrunt/pull/1787 might have fixed one problem but introduced a new one.

**Comment by ademspr** [comment]
I Have the same issue, using gitlab terraform registry.

**Comment by denis256** [comment]
Hi @spr-mweber3, which URL is expected to be generated?
url: `https://app.spacelift.io/registry/modules/v1/spring-media/maps-terraform-aws-elastic-ip/0.1.1/download`  return 404 and no `x-terraform-get` header

**Comment by spr-mweber3** [comment]
Hey @denis256, since the module is private the 404 is expected. The url to be constructed is `https://app.spacelift.io/registry/modules/v1/spring-media/maps-terraform-aws-elastic-ip/0.1.1/download` as you assumed correctly.

**Comment by yorinasub17** [comment]
Should be fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.7

**Comment by spr-mweber3** [comment]
Thank you very much! That was fast. Happy to have you guys.

**Comment by spr-mweber3** [comment]
I already had the chance to verify if it's now working for me. Unfortunately this is not the case.

```
ERRO[0001] 1 error occurred:
	* error downloading 'tfr://spacelift.io/spring-media/maps-terraform-aws-eip/aws?version=0.1.2': Error downloading module from https://app.spacelift.io/registry/modules/v1/spring-media/maps-terraform-aws-eip/aws/0.1.2/download: error recieving HTTP data
```

When I curl the location `https://app.spacelift.io/registry/modules/v1/spring-media/maps-terraform-aws-eip/aws/0.1.2/download` with a valid token I get a `2xx` reponse with a `x-terraform-get` header present. If I try to access the url I got from this header I'm able to fetch the module successfully.

However Terragrunt seems to have a problem with that. I tried to figure out what it is by examining the `DEBUG`-level log but unfortunately it doesn't say anything more than what I stated above.

**Comment by spr-mweber3** [comment]
Forget it. I had to set `TG_TF_REGISTRY_TOKEN` for this to work. May I ask why the native way of specifying credentials/a token via `~/.terraformrc` isn't respected?

**Comment by denis256** [comment]
hi, most probably code which handles `~/.terraformrc` is still in Terraform "internal" packages and so far is just used different environment variable for token

https://github.com/gruntwork-io/terragrunt/blob/master/internal/tfr/getter.go#L57

**Comment by spr-mweber3** [comment]
I see. Thank you very much.

**Comment by yorinasub17** [comment]
You can follow https://github.com/gruntwork-io/terragrunt/issues/1771 to be notified when we work on support for the token in `.terraformrc`.

**Comment by jwenz723** [comment]
FYI for other spacelift users who stumble upon this issue, you can set the token for terragrunt to authenticate to the private spacelift module registry using a [before init](https://docs.spacelift.io/concepts/run/#initializing) hook like this:

```bash
export TG_TF_REGISTRY_TOKEN=$SPACELIFT_API_TOKEN
```

**Comment by peterdeme** [comment]
For anyone finding this thread: Spacelift has implemented this feature by default: https://github.com/spacelift-io/user-documentation/pull/143/files

`TG_TF_REGISTRY_TOKEN` variable is now filled with `SPACELIFT_API_TOKEN` during the runs.
