### ISSUE TITLE
Add the ability to set persistent locks on a configuration

### ISSUE THREAD

**Issue by abtreece** [gruntwork-io/terragrunt#19]
Would like the ability to lock/unlock a configuration from further changes.

**Comment by brikis98** [comment]
Ah, neat idea. It should be fairly easy to add a `terragrunt lock` command. 

Out of curiosity, what is your use case?

**Comment by abtreece** [comment]
We are (currently) splitting up the configurations for the network and compute components and would probably consider locking the underlying infrastructure that compute configurations are built on top of.

**Comment by brikis98** [comment]
Is anyone interested in submitting a PR for this? All the code for the locking mechanism is already in place, so all you'd need to do is expose a new command in the CLI.
