### ISSUE TITLE
Overriding config_path causes errors with run-all

### ISSUE THREAD

**Issue by dudicoco** [gruntwork-io/terragrunt#1900]
Hi,

I have a common hcl file as follows:
```hcl
dependency "vpc_requester" {
  config_path = "empty"

  mock_outputs = {
    vpc_id                  = "(known after apply-all)"
  }
}

dependency "vpc_accepter" {
  config_path = "empty"

  mock_outputs = {
    vpc_id                  = "(known after apply-all)"
  }
}

inputs = {
  ...
}
```

I would like to override the config_path parameter within my child `terragrunt.hcl`:
```hcl
terraform {
  source = "git@github.com:xxxxxxxxxx//vpc-peering?ref=vpc-peering_v1.0.3"
}

prevent_destroy = true

dependency "vpc_requester" {
  config_path = "${get_parent_terragrunt_dir("root")}/path/to/file"
}

dependency "vpc_accepter" {
  config_path = "${get_parent_terragrunt_dir("root")}/path/to/other/file"

  mock_outputs = {
    vpc_region = "ap-southeast-2"
  }
}

include "root" {
  path           = find_in_parent_folders()
  merge_strategy = "deep"
}

include "common" {
  path           = "${dirname(find_in_parent_folders())}/_common/vpc-peering.hcl"
  merge_strategy = "deep"
}
```

When running `terragrunt plan` from within the child `terragrunt.hcl` dir it works as expected.
However, when running with `terragrunt run-all plan` it fails:
```sh
$ terragrunt run-all plan --terragrunt-strict-include --terragrunt-include-dir "dy-account/ap-southeast-2/_global/devops/vpc-peering/my-peering/"
ERRO[0013] Error processing module at '/my-account/ap-southeast-2/_global/devops/vpc-peering/my-peering/empty/terragrunt.hcl'. How this module was found: dependency of module at '/my-account/ap-southeast-2/_global/devops/vpc-peering/my-peering'. Underlying error: Error reading file at path /my-account/ap-southeast-2/_global/devops/vpc-peering/my-peering/empty/terragrunt.hcl: no such file or directory
ERRO[0013] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Terragrunt adds `empty` to the config path instead of completely overriding it.

**Comment by yorinasub17** [comment]
This is indeed a bug - deep merge shouldn't concat the strings.

That said, I think you can workaround this by setting `config_path` to empty string (`""`). We have a test case that exercises this path:

- Parent: https://github.com/gruntwork-io/terragrunt/blob/master/test/fixture-include-multiple/terragrunt_vpc_dep.hcl
- Child: https://github.com/gruntwork-io/terragrunt/blob/master/test/fixture-include-multiple/deep-merge-overlapping/child/terragrunt.hcl

**Comment by dudicoco** [comment]
@yorinasub17 thanks by i've already tried setting to an empty string and also failed. Not sure how it passed the tests.

**Comment by yorinasub17** [comment]
This should be addressed/fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.8

**Comment by dudicoco** [comment]
Thanks @yorinasub17! I can confirm that the issue is fixed in the new version.
