### ISSUE TITLE
Autoinit no longer works

### ISSUE THREAD

**Issue by yorinasub17** [gruntwork-io/terragrunt#1901]
Gruntwork team is running into issues with autoinit. Specifically, the case where the module source ref being updated to a new ref is no longer being handled by autoinit.

## Repro:

- Create a `terragrunt.hcl` that references a module by ref.
- Run `terragrunt apply`
- Update `ref` to a new tag.
- Run `terragrunt apply`

### Expected:

Terragrunt runs `init` as part of auto init on the second apply

### Actual:

Terragrunt proceeds to call `terraform` without `init`, leading to a module source change error.

**Comment by denis256** [comment]
I will take a look at this one

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.7
