### ISSUE TITLE
prevent_destroy=true still allow to destroy with terragrunt apply -destroy

### ISSUE THREAD

**Issue by askoriy** [gruntwork-io/terragrunt#1904]
`prevent_destroy = true` should protect selected Terraform module from destroy.
It really prevents from running `terragrunt destroy`, but still allow to destroy with `terragrunt apply -destroy`.

**Comment by yorinasub17** [comment]
This should be fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.10
