### ISSUE TITLE
Terragrunt auto-init always executes if no module is present

### ISSUE THREAD

**Issue by Ic3w0lf** [gruntwork-io/terragrunt#1921]
Hi,

in our project setup we often have the case that our `terragrunt modules` don't require any other modules. It seems that this breaks the `auto-init` behavior to **always** initialize the modules. 

I did some debugging and compared the outputs of a module which relies on an external module (e.g. [vpc](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest)) with a plain module that has no `module` at all. If I see correctly this behavior is coming from the `modulesNeedInit()` function:

```
func modulesNeedInit(terragruntOptions *options.TerragruntOptions) (bool, error) {
        modulesPath := util.JoinPath(terragruntOptions.DataDir(), "modules")
	if util.FileExists(modulesPath) {                                          <----- Always false as no will be downloaded
		return false, nil
	}
	moduleNeedInit := util.JoinPath(terragruntOptions.WorkingDir, moduleInitRequiredFile)
	if util.FileExists(moduleNeedInit) {                                       <----- Will evaluate to true
		return true, nil
	}
        ....
}
```

I can fix this by just creating an empty `module` in all of my modules, but this seems kind of hacky and maybe not the best approach:
```
module "null" {
  source = "../null"  # empty folder
}
```

I first wanted to ask if this is desired behavior or a bug? It is slowing down the development for me a bit as for most of my modules `init` is run all the time (but not too much as its all cached anyway) :)

Terragrunt: v0.35.10
Terraform: 1.0.11

Let me know if I forgot any information!

**Comment by Ic3w0lf** [comment]
I figured out a better workaround for this inspired by #1423 :)

```
after_hook "reinit_workaround" {
    commands = ["plan", "apply"]
    execute = ["/bin/sh", "-c", "mkdir -p .terraform/modules"]
}
```

Works like a charm for my case!

**Comment by denis256** [comment]
hi @Ic3w0lf , can you share an example code where this issue appears

I tried to do with a small subproject:
https://github.com/denis256/terragrunt-tests/tree/master/terragrunt-init-each-time

Initialization happens, but on older versions(v0.32.0) too

**Comment by Ic3w0lf** [comment]
Hi @denis256,

thank you for looking into the issue! I setup a small repo that reflects our development setup and was able to reproduce this issue: https://github.com/Ic3w0lf/terragrunt-test/tree/main/auto-init-issue

I tested it with version 0.35.0 (works as expected) and 0.35.10. The `rds` module is setup too initialize too often, the `vpc` module has an empty module inside and works fine with both versions. I also added a bash recording to show the behavior:

[![asciicast](https://asciinema.org/a/VxGm3ifHpNjC0YzNfVglT4wSz.png)](https://asciinema.org/a/VxGm3ifHpNjC0YzNfVglT4wSz)

I hope this helps! Let me know if you need any more information :)

**Comment by gmuth** [comment]
My tests show that version 0.35.6 does not have this issue.
Currently it looks like version 0.35.7 to 0.35.13 (latest by today) are affected and implement/cause this unpleasant auto-init behavior.

**Comment by denis256** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.18
