### ISSUE TITLE
Optimize local download code behaviour

### ISSUE THREAD

**Issue by BlackDark** [gruntwork-io/terragrunt#1926]
Hi!

Currently we are increasing our usage of terragrunt for a project and experiencing increasing execution times and also not easy optimizable CI/CD in terms of speed.
We use many local modules and therefor have references like `source = ../something`.

While investigating your code i found that local source code is always going to redownloaded and reinitialized.
https://github.com/gruntwork-io/terragrunt/blob/master/cli/download_source.go#L113

How about if we would hash the contents of the source directory with a function like: https://pkg.go.dev/golang.org/x/mod/sumdb/dirhash#HashDir
and save the hash value as the "terragrunt version" and use it to compare if somethings needs to be downloaded or not?

Maybe something like this?

```go
func alreadyHaveLatestCode(terraformSource *tfsource.TerraformSource, terragruntOptions *options.TerragruntOptions) (bool, error) {
	fmt.Println(terraformSource)

	if !util.FileExists(terraformSource.DownloadDir) ||
		!util.FileExists(terraformSource.WorkingDir) ||
		!util.FileExists(terraformSource.VersionFile) {
		return false, nil
	}

	tfFiles, err := filepath.Glob(fmt.Sprintf("%s/*.tf", terraformSource.WorkingDir))
	if err != nil {
		return false, errors.WithStackTrace(err)
	}

	if len(tfFiles) == 0 {
		terragruntOptions.Logger.Debugf("Working dir %s exists but contains no Terraform files, so assuming code needs to be downloaded again.", terraformSource.WorkingDir)
		return false, nil
	}

	currentVersion := terraformSource.EncodeSourceVersion()
	previousVersion, err := readVersionFile(terraformSource)


	fmt.Println(currentVersion)
	fmt.Println(previousVersion)
	if err != nil {
		return false, err
	}

	if tfsource.IsLocalSource(terraformSource.CanonicalSourceURL) {
		sourceHash, err := dirhash.HashDir(terraformSource.WorkingDir, "hi", dirhash.DefaultHash)
		fmt.Println(sourceHash)

		if err != nil {
			return false, err
		}

		return previousVersion == sourceHash, nil
	}
	return previousVersion == currentVersion, nil
}
```

**Comment by yorinasub17** [comment]
This sounds reasonable! We're a bit buried with other initiatives to implement this ourselves, but if anyone from the community wants to open a PR with these changes, that would be greatly appreciated!
