### ISSUE TITLE
Deep merge when using `mock_outputs_merge_with_state` in a `dependency` block

### ISSUE THREAD

**Issue by jon-walton** [gruntwork-io/terragrunt#1934]
Following from https://github.com/gruntwork-io/terragrunt/pull/1765 , it's possible to merge the existing (applied) state into the mocks (state overwrites mocks). However, this is only a shallow merge.

Let's say you have a module that outputs a `map(map(string))`. An existing output of that module could be

```json
{
  "security_groups": {
    "sensitive": false,
    "type": [
      "object",
      {
        "first": [
          "object",
          {
            "arn": "string",
            "description": "string",
            "id": "string",
            "name": "string"
          }
        ]
      }
    ],
    "value": {
      "first": {
        "arn": "arn:aws:ec2:ap-southeast-1:000000000000:security-group/sg-aaaaaaaaaaaaaaaaa",
        "description": "My first security group",
        "id": "sg-aaaaaaaaaaaaaaaaa",
        "name": "my-first-sg"
      }
    }
  }
}
```

and let's say the usage of that module is like so:

```hcl
dependency "security_groups" {
  config_path = "../security_groups"

  mock_outputs_allowed_terraform_commands = ["validate", "plan", "state"]
  mock_outputs_merge_with_state = true
  mock_outputs = {
    security_groups = {
      first = { id = "sg-mock" }
    }
  }
}

inputs = {
  something = [
    dependency.security_groups.outputs.security_groups.first.id
  ]
}
```

If I were to change the inputs of the dependency (the security_groups module), which adds an additional value to the output map, so that it becomes

```diff
{
  "security_groups": {
    "sensitive": false,
    "type": [
      "object",
      {
        "first": [
          "object",
          {
            "arn": "string",
            "description": "string",
            "id": "string",
            "name": "string"
          }
        ],
+        "second": [
+          "object",
+          {
+            "arn": "string",
+            "description": "string",
+            "id": "string",
+            "name": "string"
+          }
+        ]
      }
    ],
    "value": {
      "first": {
        "arn": "arn:aws:ec2:ap-southeast-1:000000000000:security-group/sg-aaaaaaaaaaaaaaaaa",
        "description": "My first security group",
        "id": "sg-aaaaaaaaaaaaaaaaa",
        "name": "my-first-sg"
      },
+      "second": {
+        "arn": "arn:aws:ec2:ap-southeast-1:000000000000:security-group/sg-bbbbbbbbbbbbbbbbb",
+        "description": "My second security group",
+        "id": "sg-bbbbbbbbbbbbbbbbb",
+        "name": "my-second-sg"
+      }
    }
  }
}
```

and attempt to use it BEFORE the updated dependency has been applied

```diff
dependency "security_groups" {
  config_path = "../security_groups"

  mock_outputs_allowed_terraform_commands = ["validate", "plan", "state"]
  mock_outputs_merge_with_state = true
  mock_outputs = {
    security_groups = {
      first = { id = "sg-mock" },
+      second = { id = "sg-mock" }
    }
  }
}

inputs = {
  something = [
    dependency.security_groups.outputs.security_groups.first.id,
+    dependency.security_groups.outputs.security_groups.second.id
  ]
}
```

We'll receive the following error from terragrunt when trying to plan

```
Unsupported attribute; This object does not have an attribute named "second".
```

This is due to the logic in `getTerragruntOutputIfAppliedElseConfiguredDefault` only checking the output key and not supporting a deep merge of the output values https://github.com/gruntwork-io/terragrunt/blob/cc1927746e8883322a0b37394887db4d8d6810ae/config/dependency.go#L322-L327

Would you be open to a PR or discussion on adding support for deep merging the outputs into the mock?

**Comment by yorinasub17** [comment]
Allowing deep merge of mocks to state makes sense to me, and a PR to add it would be welcome. I think this probably makes the most sense as a feature flag similar to `merge_strategy` we have on `include` blocks.

I would probably add a new config `mock_outputs_merge_strategy_with_state` that replaces `mock_outputs_merge_with_state`, and can be set to `no_merge`, `shallow`, or `deep`, with `no_merge` being the default. We could also maintain backward compatibility by having `mock_outputs_merge_with_state = true` mean `mock_outputs_merge_strategy_with_state = "shallow"`.
