### ISSUE TITLE
--terragrunt-modules-that-include does not work

### ISSUE THREAD

**Issue by roehrijn** [gruntwork-io/terragrunt#1944]
Everytime I try to use `--terragrunt-modules-that-include`, `terragrunt` simply returns this and nothing is executed:

      [yyyy@XXXX:~/tg]$ terragrunt run-all plan --terragrunt-modules-that-include incl.hcl 
      INFO[0000] The stack at /home/yyyy/tg will be processed in the following order for command plan: 
      [yyyy@XXXX:~/tg]$ 

I can reproduce this with a very simple project: 
      .
      ├── first
      │   ├── main.tf
      │   └── terragrunt.hcl
      └── incl.hcl

Where the `terragrunt.hcl` file does nothing but include the `incl.hcl` (all other files are empty):

      include "incl" {
          path = "../incl.hcl"
      }

Even after turning on debug logging, I have no glue why terragrunt is constantly refusing to run my stack:

      yyyy@XXXX:~/tg]$ terragrunt run-all plan --terragrunt-modules-that-include incl.hcl --terragrunt-log-level debug
      DEBU[0000] Did not find any locals block: skipping evaluation.  prefix=[/home/yyyy/tg/first] 
      DEBU[0000] Did not find any locals block: skipping evaluation.  prefix=[/home/yyyy/tg/first] 
      DEBU[0000] [Partial] Included config ../incl.hcl has strategy shallow merge: merging config in (shallow).  prefix=[/home/yyyy/tg/first] 
      DEBU[0000] Setting download directory for module /home/yyyy/tg/first to /home/yyyy/tg/first/.terragrunt-cache 
      DEBU[0000] Stack at /home/yyyy/tg:
        => Module /home/yyyy/tg/first (excluded: true, assume applied: false, dependencies: []) 
      INFO[0000] The stack at /home/yyyy/tg will be processed in the following order for command plan: 
      [yyyy@XXXX:~/tg]$

It says the module `/home/yyyy/tg/first` was excluded but when I simply remove the `--terragrunt-modules-that-include` attribute from the command line, my stack is executed.

`terragrunt version v0.35.14`

**Comment by denis256** [comment]
I will take a look at this one, looks like an issue with the detection of included files in
https://github.com/gruntwork-io/terragrunt/blob/master/configstack/module.go#L258

**Comment by yorinasub17** [comment]
Will close this when the release is cut.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.16

**Comment by roehrijn** [comment]
Works now even in the big Terragrunt setup for me. Thanks a lot!

**Comment by roehrijn** [comment]
Hi @denis256, unfortunately I have to revert my statement from yesterday. It doesn't work 100%. It is difficult to track down but I think the bug is here: https://github.com/gruntwork-io/terragrunt/blob/5cf44f6ef421f35c8e16623fdf6f3695f3021bc0/configstack/module.go#L276-L280
Looks like the canonical path fix hasn't been applied to the transitive dependencies' includes. That's why I have now the situation that a module is included through its include blocks but later excluded because it is mentioned as a dependency somewhere.

**Comment by roehrijn** [comment]
@denis256, can you please reopen this issue?
