### ISSUE TITLE
Sops decrypt raw file

### ISSUE THREAD

**Issue by sebastianmacarescu** [gruntwork-io/terragrunt#1947]
According to documentation for sops_decrypt_file: Only YAML and JSON formats are supported by sops_decrypt_file.
It would be really helpful to introduce a "raw" file type like here: https://github.com/carlpett/terraform-provider-sops

This will allow us to store any kind of secrets in our code and be able to push it to AWS SSM with terraform. (eg private ssh keys)

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.16
