### ISSUE TITLE
How to use validate workspace name? 

### ISSUE THREAD

**Issue by giladdi-tr** [gruntwork-io/terragrunt#1950]
Hey, 
I am using a multi-region configuration, and each region should be the same as the other. I tried to decide about what is the best design for it and saw two options: 

1. for_each - but I don't want to allow deployment to more than one region at a time. 
2. workspaces

workplaces in my configuration that inflect the region I am running on. 
After small research online I saw some of the guys using the following configuration. 
```hcl
terraform {
  before_hook "workspace" {
    commands = ["plan", "state", "apply", "destroy", "init", "refresh"]
    execute = ["terraform", "workspace", "select", replace(get_env("TG_REGION"), " ", "")]
  }
}
```
I want to validate that the `TG_REGION` variable input will be validate like in terraform variable validation. for example: 
```hcl
variable "region"{
  type    = "string"
  default = "west europe"
  validation {
    condition     = can(regex("^(?i)(East US|west europe)$", var.region))
    error_message = "The allowed regions are 'west eurpoe'/'East US'"
  }
}
```
I don't need the `TG_REGION` as an environment variable specifically. 
What do you think is the best way?

**Comment by yorinasub17** [comment]
We don't have an official mechanism to do this, but you can workaround with a `local` with a conditional and `run_cmd` to do this:

```hcl
locals {
  raw_region = get_env("TG_REGION", "")
  region = (
    can(regex("^(?i)(East US|west europe)$", local.raw_region))
    ? replace(local.raw_region, " ", "")
    : run_cmd("fail-terragrunt") # This works because fail-terragrunt is a command that doesn't exist, causing the expression to error
  )
}
```

**Comment by giladdi-tr** [comment]
@yorinasub17 cool, thank you!
