### ISSUE TITLE
Publish Terragrunt docker image to ECR Gallery

### ISSUE THREAD

**Issue by bschaatsbergen** [gruntwork-io/terragrunt#1966]
It would be great to have a Docker image available on: https://gallery.ecr.aws/ to avoid the pull rate limit.

Thoughts?

**Comment by bschaatsbergen** [comment]
I'll hand roll my own one as it seems like there's no official one.

**Comment by KhimairaCrypto** [comment]
100% agree! Having an official one will be very helpful, instead of backing our own one :-/.
