### ISSUE TITLE
render-json command should create separate json files in sub folders when run with run-all command

### ISSUE THREAD

**Issue by leiarenee** [gruntwork-io/terragrunt#1973]
When render-json command is ran with run-all it overwrites the same file. Separate files for each terragrunt sub folders should be created in same way terragrunt-debug.tfvars.json is done.
Or Each sub folder should be added under different node name having the folder name relative to include path.

**Comment by hermitmaster** [comment]
I ran into this today as well. I wanted to render json so I could build an aggregate report based on metadata. Whatever runs last clobbers the file.

**Comment by yorinasub17** [comment]
A fix for this has been released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.38.7
