### ISSUE TITLE
Incomplete Release Assets for v0.35.17

### ISSUE THREAD

**Issue by wpp** [gruntwork-io/terragrunt#1977]
Hi and thanks for providing this tool and new releases!

But I'm wondering if the assets for [v0.35.17](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.17) might be incomplete? It seems like only the Source Code archives are currently available.
Feel free to close this issue if the rest is coming.

Cheers

**Comment by hugorut** [comment]
Hello, +1 on adding the rest of the assets to the `v0.35.17` release - this is currently failing our pipeline as we download the latest version of terragrunt from the github releases.

**Comment by SizZiKe** [comment]
this seems to happen frequently...or at least I've seen it happen multiple times. Typically the binary assets lag the zip by a few minutes...I've never seen it take this long.

**Comment by denis256** [comment]
Hi, 
thank you for your patience, after fixing CICD job permissions artifacts are now available 
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.35.17
