### ISSUE TITLE
Include parent config by feeding variables from child config

### ISSUE THREAD

**Issue by gopipara** [gruntwork-io/terragrunt#1979]
Hi Terragrunt team. 

Terragrunt helps us a lot in our infrastructure provisioning. I couldn't get an implementation working using `include` block (which includes parent terragrunt.hcl config) in child terragrunt.hcl and feeding variables to parent config from child, so the parent config is not duplicated and still customizable. I couldn't find any helpful information in the documentation regarding this. Can anyone please shed some light into this. Thank you. 

I have a dir structure below
```
├── modules
│   ├── main.tf
│   ├── outputs.tf
│   └── variables.tf
├── projects
│   ├── project1
│   │   ├── bastion.tfvars
│   │   └── terragrunt.hcl
│   └── project2
│       ├── buckets.tfvars
│       ├── gke.tfvars
│       └── terragrunt.hcl
└── terragrunt.hcl
```

- Parent `terragrunt.hcl` has below config
```
terraform_version_constraint = "= 0.15.5"
terragrunt_version_constraint = "= 0.35.19"

remote_state {
  backend = "gcs"

  config = {
    credentials = local.authentication_json_file
    bucket = local.bucket
    location = local.location
    prefix = path_relative_to_include()
  }
}

terraform {
  source = "${get_parent_terragrunt_dir()}/modules"
  extra_arguments "var_files" {
    commands = get_terraform_commands_that_need_vars()
    required_var_files = fileset(get_terragrunt_dir(), "*.tfvars")
  }
}
```
- Child `terragrunt.hcl`'s has below config
```
include  "root" {
  path = find_in_parent_folders()
  merge_strategy = "deep"
}

locals {
  authentication_json_file = "~/Downloads/test.json"
  bucket = "test"
  location = "us-west1"
}

inputs = {
  authentication_json_file = local.authentication_json_file
  region = "us-west1"
  project_id = "test"
}
```

With the above config, being in `project1`  dir and running `terragrunt init --terragrunt-log-level debug` errored out as below
```
DEBU[0000] Found locals block: evaluating the expressions.
DEBU[0000] Evaluated 3 locals (remaining 0): authentication_json_file, bucket, location
DEBU[0000] Did not find any locals block: skipping evaluation.
DEBU[0000] [Partial] Included config /Users/gopichandupara/Documents/groupm/2sixty/consumer-engagement-platform/yellowstone/yellowstone-infra-iac/terragrunt.hcl has strategy deep merge: merging config in (deep).
DEBU[0000] Running command: terraform --version          prefix=[/Users/gopichandupara/Documents/groupm/2sixty/consumer-engagement-platform/yellowstone/yellowstone-infra-iac/projects/prj_crh_cep_shd_yls_ops_glbl]
DEBU[0000] Terraform version: 0.15.5
DEBU[0000] Reading Terragrunt config file at /Users/gopichandupara/Documents/groupm/2sixty/consumer-engagement-platform/yellowstone/yellowstone-infra-iac/projects/prj_crh_cep_shd_yls_ops_glbl/terragrunt.hcl
DEBU[0000] Found locals block: evaluating the expressions.
DEBU[0000] Evaluated 3 locals (remaining 0): bucket, location, authentication_json_file
DEBU[0000] Did not find any locals block: skipping evaluation.
DEBU[0000] [Partial] Included config /Users/gopichandupara/Documents/groupm/2sixty/consumer-engagement-platform/yellowstone/yellowstone-infra-iac/terragrunt.hcl has strategy deep merge: merging config in (deep).
DEBU[0000] Found locals block: evaluating the expressions.
DEBU[0000] Evaluated 3 locals (remaining 0): bucket, location, authentication_json_file
DEBU[0000] Did not find any locals block: skipping evaluation.
DEBU[0000] Included config /Users/gopichandupara/Documents/groupm/2sixty/consumer-engagement-platform/yellowstone/yellowstone-infra-iac/terragrunt.hcl has strategy deep merge: merging config in (deep) for dependency.
DEBU[0000] Did not find any locals block: skipping evaluation.
DEBU[0000] Did not find any locals block: skipping evaluation.
ERRO[0000] /Users/gopichandupara/Documents/groupm/2sixty/consumer-engagement-platform/yellowstone/yellowstone-infra-iac/terragrunt.hcl:9,24-49: Attempt to get attribute from null value; This value is null, so it does not have any attributes., and 2 other diagnostic(s)
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by yorinasub17** [comment]
`include` only goes one way - that is, the child config can access the parent, but the parent can not access the child data like a two-way `include`.

There is one exception to this, which is `dependency` access in a `deep` merge config for the `include`, where the parent can reference `dependency` blocks of children.

The typical way you deal with child configurations merging upward is by explicitly importing it into the parent context with `file` or `read_terragrunt_config`. Note that there is cycle detection, so you can't straight up import the child into the parent (e.g., `read_terragrunt_config("${get_terragrunt_dir()}/terragrunt.hcl")` will **not work**). Instead, you rely on data files in your directory structure that control what happens in the parent config based on where you are running the config.

See https://github.com/gruntwork-io/terragrunt-infrastructure-live-example for an example of this in action, specifically how the root config materializes the account, region, and environment information based on which folder the child config lives in: https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/master/terragrunt.hcl#L8-L15

**Comment by gopipara** [comment]
@yorinasub17 , thanks for your prompt response. Live examples you provided are very helpful. I was able to get my use-case working by following those.

**Comment by yorinasub17** [comment]
Glad to hear! Marking this as closed!
