### ISSUE TITLE
terragrunt chokes on terraform version string when TF_LOG=TRACE|DEBUG|INFO

### ISSUE THREAD

**Issue by mrtyler** [gruntwork-io/terragrunt#200]
* terraform 0.9.4
* terragrunt v0.12.13

One of the (relatively few) tricks for terraform debugging, as noted [here](https://www.terraform.io/docs/internals/debugging.html), is setting`TF_LOG`.

```
[tyler@toaster:~/empty]$ ls -a
.  ..

[tyler@toaster:~/empty]$ TF_LOG=TRACE terragrunt version
[terragrunt] [/Users/tyler/empty] 2017/04/28 10:19:59 Running command: terraform --version
[terragrunt] 2017/04/28 10:19:59 Malformed version: version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f
[terragrunt] 2017/04/28 10:19:59 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Same output for `TF_LOG=DEBUG` and `TF_LOG=INFO`. `WARN` and `ERROR` are fine.

The reason, I presume (haven't dug into the code) is that standard `terraform version` output looks like this:

```
[tyler@toaster:~/empty]$ terraform version
Terraform v0.9.4
```

But, with more verbose logging, it looks like this:

```
[tyler@toaster:~/empty]$ TF_LOG=INFO terraform version
2017/04/28 10:25:04 [INFO] Terraform version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f
2017/04/28 10:25:04 [INFO] Go runtime version: go1.8
2017/04/28 10:25:04 [INFO] CLI args: []string{"/usr/local/bin/terraform-0.9.4", "version"}
2017/04/28 10:25:04 [DEBUG] Detected home directory from env var: /Users/tyler
2017/04/28 10:25:04 [INFO] CLI command args: []string{"version"}
Terraform v0.9.4
```

FWIW that extra stuff is only on stderr, which may help with ignoring it:

```
[tyler@toaster:~/empty]$ TF_LOG=TRACE terraform version 2>/dev/null
Terraform v0.9.4
```

**Comment by brikis98** [comment]
Ah, you're right. Should be easy to update the regex we use to parse the version if anyone is up for an easy PR :)

**Comment by luis-silva** [comment]
@brikis98 You don't seem to have any CI integration for terragrunt. Can you run the tests for the attached PR and check if you're happy with it.

**Comment by brikis98** [comment]
@luis-silva We do have CI integration, but since the tests talk to a real AWS account, we can't run them automatically for external PRs due to [security concerns](https://circleci.com/docs/1.0/fork-pr-builds/#security-implications).
