### ISSUE TITLE
Terragrunt cannot download module from 3rd party registry: 404

### ISSUE THREAD

**Issue by atikhono** [gruntwork-io/terragrunt#2003]
Hi, I'm facing an issue with tfr source when using a 3rd party Terraform registry implementation.
Module `/download` URL returns `X-Terraform-Get: ./archive.tar.gz`. The implementation in Terragrunt is not corrent: https://github.com/gruntwork-io/terragrunt/blob/master/internal/tfr/getter.go#L251. The comments in the code are good, but the code does not do what it's supposed to, ie does not prepend base module path for relative X-Terraform-Get values. This must be `fmt.Sprintf("%v://%v%v", url.Scheme, url.Host, path.Join(url.Path, "..", terraformGet))` for `./` and `/`.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.36.1. Binaries should be published shortly
