### ISSUE TITLE
skip auto init of S§ backend not working

### ISSUE THREAD

**Issue by AlexanderWiechert** [gruntwork-io/terragrunt#2013]
If try to get terragrunt running in a gitlab ci pipeline I've encountered the following issue. I need to skip the autocreation of the S3 backend or just auto answer with yes.

`terragrunt init --terragrunt-non-interactive
time=2022-02-09T10:25:37+01:00 level=error msg=Create S3 bucket with retry shared-vpc-dev-state returned an error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
	status code: 403, request id: MCAHMRZ8ETD0YNQV, host id: h9VIIPFo+w+PHblL7pAhnRs40WiLoSujZ14+o+u1fX/Ke6ZF23O1KYC2gdBRX9szlnktQb4W3C0=. Sleeping for 10s and will try again. prefix=[/builds/aws-infrastructure/vpc-core/accounts/dev/vpc] 
time=2022-02-09T10:25:47+01:00 level=error msg=Create S3 bucket with retry shared-vpc-dev-state returned an error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

`terragrunt init with variable set TF_INPUT=false
time=2022-02-09T10:42:49+01:00 level=error msg=Create S3 bucket with retry shared-vpc-dev-state returned an error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
	status code: 403, request id: 393TD414NDR802X1, host id: HK7p7aYiO5Dl8Yud4pGWBaLrjHV0VGFpjAFRqd1EuVELXXAkrIM/Lg+Mc2zfD7Vgp/J18EyL5mk=. Sleeping for 10s and will try again. prefix=[/builds/aws-infrastructure/vpc-core/accounts/dev/vpc] 
time=2022-02-09T10:43:00+01:00 level=error msg=Create S3 bucket with retry shared-vpc-dev-state returned an error: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

`terragrunt init --auto-approve
Remote state S3 bucket shared-vpc-dev-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) time=2022-02-09T10:31:38+01:00 level=error msg=EOF
time=2022-02-09T10:31:38+01:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1`

`terragrunt init --terragrunt-no-auto-init
Remote state S3 bucket shared-vpc-dev-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) time=2022-02-09T10:35:07+01:00 level=error msg=EOF
time=2022-02-09T10:35:07+01:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1`

`terragrunt init with variable set TERRAGRUNT_AUTO_INIT=false
declare -x TERRAGRUNT_AUTO_INIT="false"
Remote state S3 bucket shared-vpc-dev-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) time=2022-02-09T10:36:51+01:00 level=error msg=EOF
time=2022-02-09T10:36:51+01:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1`

`terragrunt init  with disable_init set in remote_state
remote_state {
  disable_init = tobool(get_env("TERRAGRUNT_DISABLE_INIT", "false"))
}
Remote state S3 bucket shared-vpc-dev-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) time=2022-02-09T11:06:14+01:00 level=error msg=EOF
time=2022-02-09T11:06:14+0`

I'm not able to get this running. The only thing which looks promissing is the `--terragrunt-non-interactive` flag. But this leds into ` The AWS Access Key Id you provided does not exist in our records`

**Comment by denis256** [comment]
Hi,
in the CICD environment, you have configured `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`?

Usually `AWS Access Key Id you provided does not exist in our records` error means that keys aren't configured.

**Comment by AlexanderWiechert** [comment]
They keys where set via hashicorp vault. This does work. This happens only if I enable the init step with `--terragrunt-non-interactive` flag set.

**Comment by denis256** [comment]
Maybe execution with `--terragrunt-log-level debug` will show more details on what went wrong

**Comment by AlexanderWiechert** [comment]
Can be closed. The issues was a missconfiguration. But the error message does net lead me to it.
