### ISSUE TITLE
Is it possible to switch a module On and Off ?

### ISSUE THREAD

**Issue by sosoriov** [gruntwork-io/terragrunt#2017]
Hi there , I'm working on my terragrunt project for AKS and I was wondering if it's possible to enable or disable modules based on inputs. For example when you create a cluster, you might want to disable  monitoring  module for quick test. Is there something in Terragrunt that help me to achieve this?

Currently this is my folder structure:

``` 
.
├── README.md
├── _base
│   ├── acr.hcl
│   ├── aks-log-diagnostic.hcl
│   ├── aks-provisioning.hcl
│   ├── aks.hcl
│   ├── azure-service-bus.hcl
├── environment
│   ├── acr
│   │   └── terragrunt.hcl
│   ├── aks
│   │   └── terragrunt.hcl
│   ├── aks-log-diagnostic
│   │   └── terragrunt.hcl
│   ├── aks-provisioning
│   │   └── terragrunt.hcl
│   ├── azure-service-bus
│   │   └── terragrunt.hcl
│   ├── environment_specific.hcl

```

I've followed the documentation and I came up with this setup for a nice DRY solution.  However, I'm still struggling with the situation described above

__base/aks.hcl_
```
locals {
  env_config = read_terragrunt_config(find_in_parent_folders("environment_specific.hcl"))

  source_base_url = "git::https://github.com/xxxx/sys-tf-module-acr.git"
}

dependency "aks" {
  config_path = "${get_terragrunt_dir()}/../aks"

  mock_outputs = {
    kubelet_identity_object_id = "temporary-dummy-id"
  }
}

inputs = {
  acr_resource_group_name    = "rg-acr"
  acr_name                   = "acrname"
  kubelet_identity_object_id = dependency.aks.outputs.kubelet_identity.0.object_id
}
```

_environment/aks/terragrunt.hcl_
```
include "root" {
  path = find_in_parent_folders()
}

include "base" {
  path   = "${get_terragrunt_dir()}/../../_base/aks.hcl"
  expose = true
}

# Construct the terraform.source attribute using the source_base_url and custom version
terraform {
  source = "${include.base.locals.source_base_url}?ref=remotes/origin/main"
}

inputs = {
  cluster_name                   = "aks-demo"
  private_cluster_enabled        = false
  enable_log_analytics_workspace = false
  enable_aks_audit               = false
}
```

environment/environment_specific.hcl
```
locals {
  environment                = "test"
  resource_group_name        = "rg-test"
  enable_aks_log_diagnostics = false
  common_tags = { }
}
```

so, my idea is at the moment I set `enable_aks_log_diagnostics = true` then the log-dianostics module should be applied . I know in Terraform you have the option of using `count = var.enable_aks_log_diagnostics ? 1 : 0`  but I don't see how to achieve this in a clean  way via Terragrunt. Any ideas/suggestions  how can I achieve this?

Thanks in advanced.

**Comment by denis256** [comment]
Hi,
I think this function is not supported, however, `aks_log_diagnostics` configurations can be imported from common HCL files for environments that require log diagnostics.

**Comment by PLsergent** [comment]
Hi,

I'm writing on this issue to ask if there is any plan to add the functionality in the future? It would be really beneficial in my case!

Thanks!
