### ISSUE TITLE
README broken link

### ISSUE THREAD

**Issue by conorgil** [gruntwork-io/terragrunt#202]
In the README section titled [Running tests](https://github.com/gruntwork-io/terragrunt#running-tests), the link with text `DynamoDB locking prerequisites` is broken. I think it is related to the most recent update of the README, but I don't know where it should point yet as I'm just getting familiar with Terragrunt.

I will open a PR to fix the link once I figure out how it should be changed.

**Comment by brikis98** [comment]
Ah, good catch. Here is what that link used to point to: https://github.com/gruntwork-io/terragrunt/tree/v0.11.1#dynamodb-locking-prerequisites. We could probably copy that into the test section now.
