### ISSUE TITLE
get_path_[to|from]_repo_root fail when specifying relative path for the Terragrunt working directory

### ISSUE THREAD

**Issue by andreykaipov** [gruntwork-io/terragrunt#2026]
Regarding the recent functions introduced in https://github.com/gruntwork-io/terragrunt/pull/1954. It's better demonstrated through example. Given the following directory structure:

```
a
├── b
│   ├── main.tf
│   └── terragrunt.hcl
└── terragrunt.hcl
```

With contents `a/terragrunt.hcl`:

```hcl
locals {
  _ = run_cmd("sh", "-c", <<EOF
    echo in parent: ${get_path_to_repo_root()}
    echo in parent: ${get_path_from_repo_root()}
  EOF
  )
}
```

And contents `a/b/terragrunt.hcl`:

```hcl
include "root" {
  path = find_in_parent_folders()
}
```

If we kick off the Terragrunt resolution from within `a`, we'll error:

```console
❯ cd a
❯ TERRAGRUNT_WORKING_DIR=b terragrunt version
...
ERRO[0000] Call to function "get_path_to_repo_root" failed: Rel: can't make /tmp/a relative to b.
...
ERRO[0000] Call to function "get_path_from_repo_root" failed: Rel: can't make b relative to /tmp/a.
```

It's easily solved by just specifying an absolute path for the working dir, but it felt a bit strange to have to:

```console
❯ TERRAGRUNT_WORKING_DIR=$PWD/b terragrunt version
in parent: ../
in parent: b
Terraform v1.1.6
on linux_amd64
```

We could also do something like `(cd b; terragrunt version)` to get it to work. I have no clue how this could be fixed permanently without making assumptions about a user's environment, but I figured I'd get this documented.

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.36.3
