### ISSUE TITLE
terragrunt run-all destroy does not work in CI (Jenkins)

### ISSUE THREAD

**Issue by Jessickta** [gruntwork-io/terragrunt#2032]
Hello,

I am having an issue with running the `run-all` command within Jenkins. When the command runs, the usual prompt appears: `WARNING: Are you sure you want to run `terragrunt destroy` in each folder of the stack described above? There is no undo! (y/n)`

This automatically fails the Jenkins build as there is no way I can find to input the y or n to continue the build. I have tried -auto-approve and a number of other flags but nothing so far seems to work. I understand the need for the prompt in the first place but is there no way to skip it at all?

Thanks

**Comment by yorinasub17** [comment]
[--terragrunt-non-interactive](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-non-interactive) should do the trick
