### ISSUE TITLE
I would like to run terragrunt-for all, but have a bit more structure to organize things

### ISSUE THREAD

**Issue by brunzefb** [gruntwork-io/terragrunt#2037]
A picture is worth a thousand words (so see below) I would like to run terragrunt for-all in the us-east-2 folder.  Note that individual terragrunt folders use:
```
terraform {
  source = "${get_parent_terragrunt_dir()}/..//modules/aws-data"
}
```
to access the modules.  Now this works fine, when running the terragrunt separately, in each subfolder, but terragrunt run-all gets confused about where to find the modules folder in the run-all case.  I'm probably expecting too much here, and should probably revert to a flatter structure, where all terragrunt folders are siblings to each other.

My directory structure (much simplified) looks like this:
```
.
├── modules <- All the modules go here
│  ├── aws-data  <- individiual module goes here
│  │  ├── main.tf
│  │  ├── outputs.tf
│  │  └── README.md
│  ├── other modules at this level
└── nca   <- This is the name the 'environment'
   ├── _backend.tf
   ├── common.tfvars
   ├── datadog.enc.yaml
   ├── datadog.yaml
   ├── env.enc.hcl
   ├── env.hcl
   ├── main_providers.tf
   ├── terragrunt.hcl
   └── us-east-2 <- This is the AWS region for the 'environment' want to run terragrunt for-all here
      ├── aws-infrastructure  <- This folder is used for grouping related things
      │  ├── account-assumable-roles
      │  │  └── terragrunt.hcl
      │  ├── aurora
      │  │  └── terragrunt.hcl
      ├── aws-s3-buckets     <- Folder used to group bucket related terraform.hcl's
      │  ├── assembler-s3-bucket
      │  │  └── terragrunt.hcl
      │  ├── cloudtrail-logs-s3-bucket
      │  │  └── terragrunt.hcl
      └── roles-and-policies  <- Folder used to group roles/policies hcl's
         ├── autocluster-policy
         │  └── terragrunt.hcl
         └── autocluster-role
           └── terragrunt.hcl
      
```

**Comment by denis256** [comment]
Hello,
may be helpful to use functions that return path to repository root

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_path_to_repo_root

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_repo_root

**Comment by brunzefb** [comment]
Thanks for the info.  I have put in repo-relative paths to the modules, which is not ideal, but which does work.  I also put in repo-relative paths for dependencies, but the jury is still out on if this works.  Terragrunt seems to crash on apply without providing a good explanation, even with debug logs enabled.

**Comment by brunzefb** [comment]
Hi, I think I figured it out.  Turns out you can have as many nested folders as you need to organize things.
