### ISSUE TITLE
Hooks before remote state initialization

### ISSUE THREAD

**Issue by bporter816** [gruntwork-io/terragrunt#2046]
Hi, is it possible to run a hook before the remote state is initialized? This problem has come up before in https://github.com/gruntwork-io/terragrunt/issues/1020, and an "after" hook on reading the config was added. This works fine for the case where there are no dependencies, but my issue is that reading the config resolves dependency blocks, which itself requires remote state initialization.
My desired use case is similar to the previous issue, where I'd like to fetch AWS credentials for the remote state and backend using a hook when `AWS_PROFILE` is either not set or refers to expired credentials. An alternative solution could be to just wrap the initial call to `terragrunt` on the command line, but this feels harder to maintain across a team than if it were codified as a hook.

**Comment by denis256** [comment]
Hi,
I think this now is not supported, however, may help execution of script in `locals` block that will be evaluated when HCL is parsed

Example:
```
terraform {

  after_hook "hook" {
    commands = ["terragrunt-read-config"]
    execute = ["echo", "terragrunt-read-config"]
  }
}

locals {
  init = run_cmd("bash", "init.sh")
}
```

But this needs to be evaluated if will help in case of remote state initialization

**Comment by bporter816** [comment]
Thanks for the suggestion. This may fit our needs, as it does run before dependencies. I'll close this since I feel like the work to make a hook for this would be substantial (moving dependency resolution to after the `ReadTerragruntConfig` call).
