### ISSUE TITLE
Before and After tests

### ISSUE THREAD

**Issue by Skyere** [gruntwork-io/terragrunt#2048]
How can I do that?
For example:
I have two test for vitrual machine in Azure, they have to be in resource group
I did it in this way:
```
func TestMain(m *testing.M, t *testing.T) {
	setup(t)
	m.Run()
	teardown(t)
}

func setup(t *testing.T) {
	log.Println("\n----------------------------------Setup Start----------------------------------")
	resource := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		TerraformDir:    "../terraform/resource",
		TerraformBinary: "terragrunt",
	})

	terraform.Apply(t, resource)
}

func teardown(t *testing.T) {
	log.Println("\n----------------------------------Teardown Start----------------------------------")
	resource := terraform.WithDefaultRetryableErrors(t, &terraform.Options{
		TerraformDir:    "../terraform/resource",
		TerraformBinary: "terragrunt",
	})

	terraform.Destroy(t, resource)
}
func TestVM1 (...) {...}
func TestVM2 (...) {...}
```
But got this error:
```wrong signature for TestMain, must be: func TestMain(m *testing.M)```
Thank in advance)

**Comment by denis256** [comment]
Hi, 
I think this question is more for `teratest` repository.

Function signature for [testing](https://pkg.go.dev/testing@go1.17#section-documentation) should be `func TestXxx(*testing.T)`, if is required to apply sae HCL code multiple times - can be used different [BackendConfig](https://github.com/gruntwork-io/terratest/blob/master/modules/terraform/options.go#L58)
