### ISSUE TITLE
Getting /usr/local/bin/terragrunt: 1: /usr/local/bin/terragrunt: Syntax error: "(" unexpected when running sudo terragrunt plan

### ISSUE THREAD

**Issue by dbhoyar1** [gruntwork-io/terragrunt#2051]
Hi Team I have installed terragrunt latest version i.e 0.36.6 for ubuntu

Version installed through homebrew - terragrunt_darwin_amd64
but while running terragrunt plan I am getting below error
 **/usr/local/bin/terragrunt: 1: /usr/local/bin/terragrunt: Syntax error: "(" unexpected**

**Comment by denis256** [comment]
Hi,
can be multiple issues:
  * wrong architecture terragrunt_**_darwin_**_amd64 most probably will work only on MacOS or ubuntu on Mac hardware
  * broken downloaded file - what shows `file /usr/local/bin/terragrunt` ? it is executable or text file?

**Comment by dbhoyar1** [comment]
Thank you so much Denis for help. Basd on your suggestion I have tried below executable and it is working now

https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.6/terragrunt_linux_amd64
