### ISSUE TITLE
Verify input {} against module?

### ISSUE THREAD

**Issue by brunzefb** [gruntwork-io/terragrunt#2054]
I made a silly mistake in one of my terragrunt configs -- in this case using the terraform-aws-rds-cluster module
I had
```
input = {
   ...other inputs
   security-groups  = [
                          dependency.rds-security-group.outputs.security_group_id, 
                          dependency.eks.outputs.worker_security_group_id
                        ]
  ...more inputs
}
```
The astute reader will notice that the correct variables.tf in terraform-aws-rds-cluster module is actually `security_groups`, ie with an underscore, not with a dash.
Now if you do it wrong, there is no warning, and since I did not set `'security_group'`, you get the default.

Would it be possible for terraform to check all the inputs against the module - and emit a warning if an unmatched input is used?  This would be a new feature.

**Comment by denis256** [comment]
Hi,
may be tricky to implement since it will require parsing all terraform files before launching and comparing variables and inputs

**Comment by yorinasub17** [comment]
I think https://terragrunt.gruntwork.io/docs/reference/cli-options/#validate-inputs addresses the need here. If not, can you describe how we can improve that command (or what the bug is)? Thanks!

**Comment by brunzefb** [comment]
You are absolutely right, it's there.  How did I not see this?  Will close the issue.
