### ISSUE TITLE
Terragrunt not using existing cache folder and create a new one

### ISSUE THREAD

**Issue by giladdi-tr** [gruntwork-io/terragrunt#2059]
As part of the CI-CD workflow, we are getting a comment with all the plan details on each PR. 
We output the plan binary to a plan file and create a tar of the terragrunt folder to use the same approved plan. 

> NOTE: The CI flow with the plan and the CD flow run differently.

We are creating an artifact to get two main benefits: 
- Getting the plan binary to deploy the same plan we approved (I saw terrgrunt saving it under the .terragrunt-cache folder)
- Save the time of the `terragrunt run-all init` command

### Issue:
We are downloading the artifact on the CD workflow, and it appears that the terragrunt does not find the plan binary.
When debugging it locally and even trying to run the command `terragrunt run-all init` again, the terragrunt creates a new subfolder under the .terragrunt-cache and ignores the existing one.

Listing the .terragrunt-cache folder: 
```bash
ls <path_to_folder>/.terragrunt-cache/
```
output: 
```
34GECzvl5Ryx9H78WqM4rnaTTLE
```

running terragrunt run-all init
```bash
terragrunt run-all init --terragrunt-include-external-dependencies
ls <path_to_folder>/.terragrunt-cache/
```
output:
```
34GECzvl5Ryx9H78WqM4rnaTTLE  vLEqUXUzcMsfws51QRWbVWM2uwI
```

**Comment by denis256** [comment]
Hello,
Is the working directory the same in both cases?
asking since mentioned hash is [calculated](https://github.com/gruntwork-io/terragrunt/blob/master/cli/tfsource/types.go#L116) from working dir.

It is possible to set CICD to run in the same location, like `/tmp/project` ?

**Comment by giladdi-tr** [comment]
Hey @denis256, 
It is not the same one. 
The directory's name is dynamic due to Kubernetes runner's different home dir name.

I will try and update. Thank you for your answer.

**Comment by Carrvin** [comment]
@giladdi-tr How did you solve this issue? We are having the sam issue with using Gitlab a pipeline and runners on AWS. Any help on this is highly appreciated.
