### ISSUE TITLE
Boolean input validation fails

### ISSUE THREAD

**Issue by riccardolocci** [gruntwork-io/terragrunt#2068]
Hi there,

I'm trying to use a boolean input from a terraform module, however `terragrunt plan` fails because the terraform variable validation block does not recognize the value that I'm passing.
This problem exists only when I use that terraform module with terragrunt.
If I don't pass that input, the variable is correctly initialized to its default value.
Here follows some code.

My input file:
```
inputs = {
  ...
  aft_vpc_endpoints           = false
}
```

The variable definition on the terraform module:
```
variable "aft_vpc_endpoints" {
  type        = bool
  description = "Flag turning VPC endpoints on/off for AFT VPC"
  default     = true
  validation {
    condition     = contains([true, false], var.aft_vpc_endpoints)
    error_message = "Valid values for var: aft_vpc_endpoints are (true, false)."
  }
}
```

The error I receive:
```
╷
│ Error: Invalid value for variable
│ 
│   on variables.tf line 94:
│   94: variable "aft_vpc_endpoints" {
│ 
│ Valid values for var: aft_vpc_endpoints are (true, false).
│ 
│ This was checked by the validation rule at variables.tf:98,3-13.
╵
ERRO[0192] 1 error occurred:
        * exit status 1
```

Terraform version: 1.1.7
Terragrunt version: 0.36.6

**Comment by denis256** [comment]
Hi,
since terragrunt passed inputs as environment variables, looks like it is an issue on how terragrunt parse variables, same error occurs when terraform is invoked with `TF_VAR_xxx`:

```
$ TF_VAR_aft_vpc_endpoints=true terraform plan
│ Error: Invalid value for variable
│ 
│   on main.tf line 1:
│    1: variable "aft_vpc_endpoints" {
│ 
│ Valid values for var: aft_vpc_endpoints are (true, false).
│ 
│ This was checked by the validation rule at main.tf:5,3-13.

```

References:

https://github.com/hashicorp/terraform/issues/30609

**Comment by riccardolocci** [comment]
Hi @denis256, thank you for the reference!

I just tried updating to the latest alpha of Terraform 1.2.0 ([v1.2.0-alpha20220413](https://github.com/hashicorp/terraform/releases/tag/v1.2.0-alpha20220413)) and `terragrunt plan` seems to run smoothly.

I tried to find a page to see if version 1.2.0 is already scheduled for release, but I was unlucky: do you have any reference to something similar to a release calendar?

**Comment by sylwit** [comment]
Same bug as [here](https://github.com/hashicorp/terraform/issues/30919) Waiting for the 1.2

**Comment by bethadele** [comment]
Since we're now well past the Terraform 1.2.0, I'm closing this issue.
