### ISSUE TITLE
passing a tfvars file from the cli that is starting with a dot it will result in file not found.

### ISSUE THREAD

**Issue by Raffaello** [gruntwork-io/terragrunt#2078]
This is related to this terraform issue that i reported here: 
https://github.com/hashicorp/terraform/issues/30903

# Terragrunt version

```
terragrunt version v0.36.7
```
 
 
 When using a tfvars file from the CLI input, for e.g.: `terragrunt plan -var-file=.myvars.tfvars`
 
it fails with the following error:
```
│ Error: Failed to read variables file
│ 
│ Given variables file .myvars.tfvars does not exist.

ERRO[0001] 1 error occurred:

	* exit status 1

```

This issue doesn't exists instead if using a file named `_myvars.tfvars`, e.g.: `terragrunt plan -var-file=_myvars.tfvars` this works properly.

----

I don't know why is happening, but it might be the case that the file on unix/linux is hidden and it is not found because escluded from the search?

**Comment by Raffaello** [comment]
I have done a simple quick start test with both Terraform alone and Terragrunt.

Terraform doesn't present this issue.

Terragrunt, even using just the initial quick-start file sample from the documentation.
if it is used passing a variable files, and the file exists, starting with a dot. It will report error: file not found.

**Comment by Raffaello** [comment]
it looks like terragrunt doesn't copy the `.myvars.tfvars` file in the cache directory, so consequently is not found. 

so basically the issue is:

Terragrunt doesn't copy files passed as var-file arguments that are starting with `.` (hidden) into `.terragrunt-cache` working directory.

**Comment by denis256** [comment]
Hi,
hidden files are skipped by default, however, files can be included through `include_in_copy`:

```
terraform {
  include_in_copy = [".myvars.tfvars"]
}
```

https://github.com/denis256/terragrunt-tests/tree/master/copy-hidden-file
