### ISSUE TITLE
terragrunt does not pass -backend=false to terraform

### ISSUE THREAD

**Issue by luispabon** [gruntwork-io/terragrunt#2082]
Looks like terragrunt swallows the `-backend=false` flag during init ops. We need this to run linting against the codebase on an execution env that has no credentials.

```
~ terragrunt init -backend=false
╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "s3"
[...]
~ terragrunt init -backend=false --terragrunt-no-auto-init
╷
│ Error: Backend initialization required, please run "terraform init"
│ 
│ Reason: Initial configuration of the requested backend "s3"
[...]
```
However, with terraform directly:

```
~  terraform init -backend=false 
Initializing modules...
- bastion in ../../modules/bastion

Initializing provider plugins...
- Finding latest version of hashicorp/template...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v4.11.0...
- Installed hashicorp/aws v4.11.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)

[...]

Terraform has been successfully initialized!
[...]
```

**Comment by endriu0** [comment]
Running into the same and the disable_init option doesn't fix it. I'll have to prolly add the credentials just to be able to validate which sucks as it works out of the box with plain terraform.

```
ERRO[0007] Module /home/runner/terraform/my-app has finished with an error: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.

	For verbose messaging see aws.Config.CredentialsChainVerboseErrors  prefix=[/home/runner/terraform/my-app]
ERRO[0007] 1 error occurred:
	* Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

ERRO[0007] Unable to determine underlying exit code, so Terragrunt will exit with error code 1

**Comment by yhakbar** [comment]
Hey folks,

It seems like this is actually a bug in how automatic remote state initialization is done in Terragrunt (confusing, but this is referring to how the backend resources like S3 buckets are created automatically, not anything passed to OpenTofu/Terraform.

The bug appears to be that we don't check that the flag is set here:
https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state.go#L100

Will look to address this soon.

**Comment by yhakbar** [comment]
This is fixed in [v0.66.7](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.66.7).

You should be able to avoid the error experienced here by using the `--terragrunt-disable-bucket-update` to prevent Terragrunt from automatically attempting to provision remote state resources.

**Comment by tarfeef101** [comment]
just finding this a while later, would be WAY better if terragrunt just recognised the TF flag, and disabled this behaviour automatically

requiring users to learn/provide a new extra flag on top of it (which seems to break if you also provide `backend=false` to TF), is pretty bad from a user experience perspective.

**Comment by diofeher** [comment]
In newer versions of terragrunt, this flag is called `--disable-bucket-update`.
