### ISSUE TITLE
[gitconfig] Error when including "~" into /etc/gitconfig

### ISSUE THREAD

**Issue by jmauro** [gruntwork-io/terragrunt#2093]
Hello,

I have the following line in `/etc/gitconfig`
```
$ cat /etc/gitconfig
...
[include]
        path = ~/.gitconfig
...
```
Leading to the following error:
```
DEBU[0001] Evaluated 2 locals (remaining 0): xxxxxxxx  prefix=[/home/repo/XXXXXXX]
DEBU[0001] Found locals block: evaluating the expressions.  prefix=[/home/repo/XXXXXXXXXXX]
DEBU[0001] Evaluated 5 locals (remaining 0): xxxxxxxx  prefix=[/home/repo/XXXXXXX]
DEBU[0001] Evaluated 3 locals (remaining 1): xxxxxxxx
DEBU[0001] Evaluated 1 locals (remaining 0): xxxxxxxx
DEBU[0001] git show-toplevel result:

error: could not expand include path '~/.gitconfig'
fatal: bad config line 28 in file /etc/gitconfig

ERRO[0001] /home/repo/XXX/terragrunt.hcl:27,20-34: Error in function call; Call to function "get_repo_root" failed: exit status 128., and 1 other diagnostic(s)
ERRO[0001] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
Here are the version I am using:
```
$ terragrunt -v
terragrunt version v0.36.8
$ terraform  -v
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
```
Here is the compliance to `~` for [gitconfig](https://git-scm.com/docs/git-config#Documentation/git-config.txt-codegitdircode)

**Comment by denis256** [comment]
Hi,
looks like a bug

if in the same directory will be executed:
```
git rev-parse --show-toplevel
```
it will work fine?

**Comment by jmauro** [comment]
Yeap not issue there.
```
$ git rev-parse --show-toplevel
/home/repo/XXXXXXX
```

**Comment by denis256** [comment]
Try to use v0.36.9 or later if will available, it has a fix on passing env variables to git invocation

https://github.com/gruntwork-io/terragrunt/releases/tag/v0.36.9

**Comment by jmauro** [comment]
Hello,

It seems to be fixed.

Thanks for the heads up.


Kind regards,
JM

**Comment by amontalban** [comment]
Just for anyone having similar issues with Atlantis (We deployed with https://github.com/terraform-aws-modules/terraform-aws-atlantis):

```
fatal: detected dubious ownership in repository at '/home/atlantis/.atlantis/repos/company/terraform/101/default'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/atlantis/.atlantis/repos/company/terraform/101/default


time=2022-11-25T11:58:43Z level=error msg=Error: Error in function call


time=2022-11-25T11:58:43Z level=error msg=  on /home/atlantis/.atlantis/repos/company/terraform/101/default/provider/aws/aws.hcl line 41, in locals:

time=2022-11-25T11:58:43Z level=error msg=  41:     "Config file"    = "${get_path_from_repo_root()}/terragrunt.hcl"

time=2022-11-25T11:58:43Z level=error msg=

time=2022-11-25T11:58:43Z level=error msg=Call to function "get_path_from_repo_root" failed: exit status 128.
```

**Comment by roberc7** [comment]
> Just for anyone having similar issues with Atlantis (We deployed with https://github.com/terraform-aws-modules/terraform-aws-atlantis):
> 
> ```
> fatal: detected dubious ownership in repository at '/home/atlantis/.atlantis/repos/company/terraform/101/default'
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /home/atlantis/.atlantis/repos/company/terraform/101/default
> 
> 
> time=2022-11-25T11:58:43Z level=error msg=Error: Error in function call
> 
> 
> time=2022-11-25T11:58:43Z level=error msg=  on /home/atlantis/.atlantis/repos/company/terraform/101/default/provider/aws/aws.hcl line 41, in locals:
> 
> time=2022-11-25T11:58:43Z level=error msg=  41:     "Config file"    = "${get_path_from_repo_root()}/terragrunt.hcl"
> 
> time=2022-11-25T11:58:43Z level=error msg=
> 
> time=2022-11-25T11:58:43Z level=error msg=Call to function "get_path_from_repo_root" failed: exit status 128.
> ```

did you manage to fix the above @amontalban

**Comment by amontalban** [comment]
@roberc7 I added this command in my Atlantis workflow before running `terragrunt`:

```
git config --global --add safe.directory '*'
```

**Comment by amontalban** [comment]
> > Just for anyone having similar issues with Atlantis (We deployed with https://github.com/terraform-aws-modules/terraform-aws-atlantis):
> > ```
> > fatal: detected dubious ownership in repository at '/home/atlantis/.atlantis/repos/company/terraform/101/default'
> > To add an exception for this directory, call:
> > 
> > 	git config --global --add safe.directory /home/atlantis/.atlantis/repos/company/terraform/101/default
> > 
> > 
> > time=2022-11-25T11:58:43Z level=error msg=Error: Error in function call
> > 
> > 
> > time=2022-11-25T11:58:43Z level=error msg=  on /home/atlantis/.atlantis/repos/company/terraform/101/default/provider/aws/aws.hcl line 41, in locals:
> > 
> > time=2022-11-25T11:58:43Z level=error msg=  41:     "Config file"    = "${get_path_from_repo_root()}/terragrunt.hcl"
> > 
> > time=2022-11-25T11:58:43Z level=error msg=
> > 
> > time=2022-11-25T11:58:43Z level=error msg=Call to function "get_path_from_repo_root" failed: exit status 128.
> > ```
> 
> how did you resolve the get_path_from_repo_root function error?

I ended up doing this: https://github.com/runatlantis/atlantis/issues/2221#issuecomment-1155231919
