### ISSUE TITLE
Running terragrunt in debug mode generates empty terragrunt-debug.tfvars.json

### ISSUE THREAD

**Issue by ruijarimba** [gruntwork-io/terragrunt#2100]
I'm trying to generate the `terragrunt-debug.tfvars.json` file as described in the [Debugging Terragrunt][1] page.

I can see that the file is generated when running `terragrunt plan...` command:
>level=info msg=Debug mode requested: generating debug file terragrunt-debug.tfvars.json in working dir ........

But the file contains just an empty json object:

    {}

Terraform `.tfvars` files are configured as follows in the `terragrunt.hcl` file:

    terraform {
      # other stuff here
	  
      extra_arguments "include_variable_files" {
        commands = [
          "plan"
        ]

        required_var_files = [
          find_in_parent_folders("global.tfvars"),
          find_in_parent_folders("global-${local.environment}.tfvars"),
          find_in_parent_folders("global-${local.region}.tfvars"),
          find_in_parent_folders("global-${local.environment}-${local.region}.tfvars"),
          find_in_parent_folders("shared.tfvars"),
          find_in_parent_folders("shared-${local.local_config.environment}.tfvars"),
          "terraform.tfvars"
        ]

        optional_var_files = [
          "terraform-override.tfvars"
        ]
      }
    }

Any idea on what might be wrong?

  [1]: https://terragrunt.gruntwork.io/docs/features/debugging/

**Comment by yorinasub17** [comment]
The debug mode vars files is meant to help debug misconfiguration issues with the `inputs` map, as it gives you a visual representation of how `terragrunt` is translating that for `terraform`. It is not meant to help debug the var files that are passed in for `required_var_files` and `optional_var_files`, as those should show up in the `terragrunt` logs when you run with `debug` log level.

Given that, the reason the generated var files is empty is because (presumably, based on your config) the `inputs` map is not set in your `terragrunt.hcl`.

**Comment by ruijarimba** [comment]
Thanks @yorinasub17, I was assuming that the generated `terragrunt-debug.tfvars.json` was based on both the `.tfvars` files and `inputs` map from `terragrunt.hcl` - having `.tfvars` in the name of the generated file might confuse people (it did confuse me).

Anyway, changing my `terragrunt.hcl` to the following:

```hcl
include {
  path = find_in_parent_folders()
}

inputs = {
  string      = "string"
  number      = 42
  bool        = true
  list_string = ["a", "b", "c"]
  list_number = [1, 2, 3]
  list_bool   = [true, false]

  map_string = {
    foo = "bar"
  }

  map_number = {
    foo = 42
    bar = 12345
  }

  map_bool = {
    foo = true
    bar = false
    baz = true
  }

  object = {
    str  = "string"
    num  = 42
    list = [1, 2, 3]

    map = {
      foo = "bar"
    }
  }
}
```

And then running a terragrunt command in debug mode still generates a file with an empty json object:

```json
{}
```

**Comment by ruijarimba** [comment]
Is there an easy way to get the paths of all files referenced in `required_var_files` and `optional_var_files`, without having to parse the log files?

My purpose is to use tools like [tfsec](https://github.com/aquasecurity/tfsec) and [tflint](https://github.com/terraform-linters/tflint) but I need to pass all the `.tfvars` files used by a specific stack.

**Comment by ruijarimba** [comment]
Closing this issue, I found the proper way to get  the `tfvars`:
- #2401
