### ISSUE TITLE
Error: Missing required argument

### ISSUE THREAD

**Issue by pandamunich** [gruntwork-io/terragrunt#2102]
Hi,

I get this error message by deployment, I checke already everything, every module, but I have no Idea, what is really missing here! :((((

"The argument "address" is required, but was not set."

Can you help me to debug this issue?

Thank you very much in advance!

Regards!

**Comment by denis256** [comment]
Hello,
try to run with `--terragrunt-log-level debug` it should print in which directory terraform is invoked

**Comment by denis256** [comment]
Hi, 
"Running command:" logs should say where terraform is invoked,
like "Running command: terraform plan prefix=[/home/mqiu/terragrunt_deployment/dev/west-europe/dev/ehyp/platform/database/postgresql/flexible_server/pgdb_flex_server]"

Is module `terraform-provider-vault` used? was tried to define `VAULT_ADDR` env variable?

**Comment by pandamunich** [comment]
Hi,

I really don't know, what is exactly going wrong, but I copied the pgdb_flex_server to pgdb_flex_panda, and I can deploy again.

Regards!
