### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by JudewinVJ** [gruntwork-io/terragrunt#2109]
Hi, 

Terragrunt init or plan - throws runtime error: invalid memory address or nil pointer dereference every-time it runs. 
When I manually run terraform init on the same state, it works. Could you please help ?? 
I run terragrunt - alpine/terragrunt image on gitlab runner (container). 

terragrunt --version
terragrunt version v0.[37]
$ terragrunt init --terragrunt-log-level debug --terragrunt-debug
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=[Partial] Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow).
time=2022-05-16T05:37:58Z level=debug msg=Running command: terraform --version prefix=[/builds/iac/platform/platform-nonprod/gitlab/object-storage] 
time=2022-05-16T05:37:58Z level=debug msg=Terraform version: 1.1.9
time=2022-05-16T05:37:58Z level=debug msg=Reading Terragrunt config file at /builds/iac/platform/platform-nonprod/gitlab/object-storage/terragrunt.hcl
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=[Partial] Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow).
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:37:58Z level=debug msg=Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow) for dependency.
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=[Partial] Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Getting output of dependency /builds/iac/platform/platform-nonprod/base/compartment/terragrunt.hcl for config /builds/iac/platform/platform-nonprod/gitlab/object-storage/terragrunt.hcl
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=[Partial] Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=[Partial] Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Detected single bare include block - exposing as top level prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Did not find any locals block: skipping evaluation. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=[Partial] Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow). prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Detected remote state block with generate config. Resolving dependency by pulling remote state. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Setting dependency working directory to /builds/iac/platform/platform-nonprod/base/compartment/.terragrunt-cache/067795729 prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Generated file /builds/iac/platform/platform-nonprod/base/compartment/.terragrunt-cache/067795729/backend.tf. prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Generated remote state configuration in working dir /builds/iac/platform/platform-nonprod/base/compartment/.terragrunt-cache/067795729 prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:37:58Z level=debug msg=Running command: terraform init -get=false prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
time=2022-05-16T05:[38](https://git.saudidigitalbank.com/iac/platform/platform-nonprod/-/jobs/43777#L38):08Z level=debug msg=Running command: terraform output -json prefix=[/builds/iac/platform/platform-nonprod/base/compartment] 
t
time=2022-05-16T05:38:09Z level=debug msg=Detected single bare include block - exposing as top level
time=2022-05-16T05:38:09Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:38:09Z level=debug msg=Did not find any locals block: skipping evaluation.
time=2022-05-16T05:38:09Z level=debug msg=Included config /builds/iac/platform/platform-nonprod/terragrunt.hcl has strategy shallow merge: merging config in (shallow).
time=2022-05-16T05:38:09Z level=debug msg=Generated file /builds/iac/platform/platform-nonprod/gitlab/object-storage/backend.tf.
time=2022-05-16T05:38:09Z level=info msg=Debug mode requested: generating debug file terragrunt-debug.tfvars.json in working dir /builds/iac/platform/platform-nonprod/gitlab/object-storage
time=2022-05-16T05:38:09Z level=debug msg=The following variables were detected in the terraform module:
time=2022-05-16T05:38:09Z level=debug msg=[compartment_id bucket_name-02 bucket_name-03 bucket_name-04 bucket_name-08 bucket_namespace bucket_name-01 bucket_name-05 bucket_name-06 bucket_name-07 bucket_name-09 bucket_name-10 defined_tags]
time=2022-05-16T05:38:09Z level=debug msg=Variables passed to terraform are located in "/builds/iac/platform/platform-nonprod/gitlab/object-storage/terragrunt-debug.tfvars.json"
time=2022-05-16T05:38:09Z level=debug msg=Run this command to replicate how terraform was invoked:
time=2022-05-16T05:38:09Z level=debug msg=	terraform init -var-file="/builds/iac/platform/platform-nonprod/gitlab/object-storage/terragrunt-debug.tfvars.json" "/builds/iac/platform/platform-nonprod/gitlab/object-storage"
time=2022-05-16T05:38:09Z level=debug msg=Initializing remote state for the s3 backend
time=2022-05-16T05:38:09Z level=warning msg=Encryption is not enabled on the S3 remote state bucket terraform-state. Terraform state files may contain secrets, so we STRONGLY recommend enabling encryption!
time=2022-05-16T05:38:09Z level=warning msg=Versioning is not enabled for the remote state S3 bucket terraform-state. We recommend enabling versioning so that you can roll back to previous versions of your Terraform state in case of error.
time=2022-05-16T05:38:09Z level=debug msg=Checking if SSE is enabled for AWS S3 bucket terraform-state
time=2022-05-16T05:38:09Z level=debug msg=Error checking if SSE is enabled for AWS S3 bucket terraform-state: NotImplemented: S3 Get Bucket encryption configuration operation is not supported.
	status code: [50](https://git.saudidigitalbank.com/iac/platforms/platform-nonprods/-/jobs/43777#L50)1, request id: jed-1:TJbrlwxaMHz-XuGLxbpfJvv1Fdp2aEdr[59](https://git.saudidigitalbank.com/iac/platform/platform-nonprod/-/jobs/43777#L59)KMIVblfZiap0WZla4jYdszxF07XkYp, host id: 
time=2022-05-16T05:38:09Z level=debug msg=Checking if bucket terraform-state is have root access
time=2022-05-16T05:38:09Z level=debug msg=Could not get policy for bucket terraform-state
time=2022-05-16T05:38:09Z level=debug msg=Checking if bucket terraform-state is enforced with TLS
time=2022-05-16T05:38:09Z level=debug msg=Could not get policy for bucket terraform-state
time=2022-05-16T05:38:09Z level=debug msg=Checking if S3 bucket terraform-state is configured to block public access
**time=2022-05-16T05:38:09Z level=error msg=runtime error: invalid memory address or nil pointer dereference
time=2022-05-16T05:38:09Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1**
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1

**Comment by denis256** [comment]
Hi,
can be shared with which permissions have AWS user under which terragrunt was executed? permission `s3:GetBucketPublicAccessBlock` is set?

as a workaround, may help to set `disable_bucket_update` for `remote_state`
```
remote_state {
  ...
  config = {
    disable_bucket_update = true
  ...
  }
}
```

**Comment by JudewinVJ** [comment]
Thanks @denis256 - This fixed the issue.
