### ISSUE TITLE
s3 backend ignored

### ISSUE THREAD

**Issue by grimm26** [gruntwork-io/terragrunt#211]
I've been successfully using terragrunt for a while now, but I have hit a problem when I recently created a new module.  Terragrunt is not uploading the state file to S3.  After a `terragrunt apply`, I get:
```
....
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path:
```

For the life of me, I can't get it to use the backend.  It just creates a terraform.tfstate in the current directory.  I tried to `terragrunt state push terraform.tfstate` but that seemed to do nothing.

```
~ % terragrunt --version
terragrunt version v0.12.15
~ % terraform --version
Terraform v0.9.4
```

**Comment by brikis98** [comment]
Did you follow [step 1 of the migration instructions](https://github.com/gruntwork-io/terragrunt#migration-instructions)?

**Comment by grimm26** [comment]
AAAAARRRRGGGGHHHHH!
I will now hang my head in shame :).  I guess I'm not used to adding that terraform{} block yet to a new config :).  Was wondering why my existing stuff was still working fine.

**Comment by brikis98** [comment]
Not your fault. It's very easy to miss. I filed a bug in case anyone wants to try to catch this common error: https://github.com/gruntwork-io/terragrunt/issues/212.
