### ISSUE TITLE
Disable color output

### ISSUE THREAD

**Issue by pete0emerson** [gruntwork-io/terragrunt#2116]
> is there any way to disable the colored output from the terragrunt binary?

```
 ~ $ terragrunt plan --help | grep color
  -no-color           If specified, output won't contain any color.
 ~ $ terragrunt apply --help | grep color
  -no-color              If specified, output won't contain any color.
```

> that removes the color output from the terraform runs, not from the terragrunt runs.
> the output from the CI pipeline into github has a lot of these strings �[4m{�[0m�[0m i suppose those are color strings/encodings for terminal

>> What is the terragrunt command that your pipeline is running?

> `cd <dir>; terragrunt plan -no-color-out=$planfile`

>> Ah, and it's suppressing terraform color but still generating terragrunt output in color?

> Correct

**Comment by denis256** [comment]
hi,
most probably will help `TF_CLI_ARGS="-no-color"` env variable

https://github.com/hashicorp/terraform/issues/23708#issuecomment-571676112

https://github.com/hashicorp/terraform/issues/15264

**Comment by MaxymVlasov** [comment]
>TF_CLI_ARGS="-no-color"

That not works

![image](https://user-images.githubusercontent.com/11096782/177538000-19350287-9d74-42eb-9846-2238df1dd058.png)

**Comment by derrix060** [comment]
For whoever is coming here with the same problem, it's not fixed by adding `--terragrunt-no-color` to the command, for example:

```console
terragrunt --terragrunt-no-color plan -no-color

# Or using ENV Vars:
TERRAGRUNT_NO_COLOR=true terragrunt plan -no-color
```

Note that the `-no-color` is still required because this is passed to terraform.

**Comment by yhakbar** [comment]
@derrix060 

This will change with the CLI Redesign (#3445). With those changes, using `--no-color` will prevent color for both Terragrunt and OpenTofu/Terraform.

**Comment by michaelbdavidson7** [comment]
For those coming here with this problem, as of now this WORKS:

`terragrunt --no-color plan`

but `--terragrunt-no-color` did not work for me
