### ISSUE TITLE
Provide command line arg to disable remote state bucket updates

### ISSUE THREAD

**Issue by davidsomebody** [gruntwork-io/terragrunt#2121]
Hi,

with [v0.37.0](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.37.0) introduced enforced remote state bucket updates our pipelines start to fail. The root cause is the permission model we use. Our CI pipelines which execute terragrunt are not allowed to update the S3 state bucket (which is managed centrally), therefore we would like to use the newly introduced `disable_bucket_update = true`. Unfortunately, we have many `terragrunt.hcl` files for all the different pipelines distributed across many repositories which would make updating all the remote state configurations cumbersome.
As an alternative, we would like to use this option as a command-line argument, since our terragrunt execution is configured in a central share pipeline template which we could updated easily.

Looking forward if this feature request would be an option.

Best,
David.

**Comment by kim0** [comment]
Would it also make sense to expose this via an environment variable ?

**Comment by demolitionmode** [comment]
> Would it also make sense to expose this via an environment variable ?

Absolutely, we build a tooling image which includes Terragrunt; given that we have the same behaviour across all of our repos, we'd be able to set the env var in that image rather than having to update all of our repos
