### ISSUE TITLE
fork/exec /bin/terraform: argument list too long with long variable

### ISSUE THREAD

**Issue by ArchiFleKs** [gruntwork-io/terragrunt#2132]
Hi,

I'm currently using Terragrunt with the Hashicorp Vault provider and [this module](https://github.com/particuleio/terraform-vault-config).

I need to path some long variable as an input (a policy file with more than 1000 lines in it for example). I guess because Terragrunt passes input as environments variable, it hits the maximum number of argument and also the max size of an environment variable.

I'm not sure there is a workaround for this due to the way Terragrunt works. I have not tested with native Terraform but I suspect it would work.

**Comment by m-eitan** [comment]
Happened to me too, would really like to hear some solutions, trying to set ulimit did not work

**Comment by Binternet** [comment]
+1 
Happens to me as well

**Comment by denis256** [comment]
Hi,
yes, Terragrunt uses environment variables `TF_VAR_*` to pass into Terraform, AFAIK to increase env variable size will be required to recompile kernel... as workaround I think can be attempted to generate `variables.tf` from Terraform with required content which will be picked automatically by Terraform

**Comment by bmicha4** [comment]
+1

**Comment by m-eitan** [comment]
@denis256 Can you please further explain how one can generate a `variables.tf` file from terragrunt? thanks you

**Comment by m-eitan** [comment]
@denis256 Thanks a lot! this works and really a very simple solution, thanks for the quick and detailed help really appreciate it :) I didn't open the ticket but I would consider it resolved

**Comment by ArchiFleKs** [comment]
Haven't tried it yet but seems like a good workaround thanks !

**Comment by martinm82** [comment]
Although there is a workaround for this issue I would expect to keep this issue open and be addressed by terragrunt itself. Any chance we can solve this directly in terragrunt?

**Comment by bharathkarnam** [comment]
> Hi, yes, Terragrunt uses environment variables `TF_VAR_*` to pass into Terraform, AFAIK to increase env variable size will be required to recompile kernel... as workaround I think can be attempted to generate `variables.tf` from Terragrunt with required content which will be picked automatically by Terraform

@denis256 you mentioned increase env variable size, what variable is that? i am thinking of recompiling kernel.

**Comment by sojakub** [comment]
I had the same issue with quite big json file and I solved that with generate function:

```
terraform {
  source = "https://github.com/terraform-aws-modules/terraform-aws-route53//modules/records/.?ref=v3.1.0"
}
...
inputs = {
  zone_name = "mydomain.com"
}

generate "dependencies" {
  path      = "dependencies.auto.tfvars"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
records_jsonencoded     = ${jsonencode(file("records.json"))}
EOF
}
```
In this example `records_jsonencoded` will be used as an input.

**Comment by elouanKeryell-Even** [comment]
To be more precise, I think it is a limitation on the size of the (terraform) command-line that is generated by terragrunt

There seem to be a maximum command-line size, which you can check with the following command:

```
$ getconf ARG_MAX
2097152
```

More info here: https://stackoverflow.com/a/18647755/3037171

I don't think it has anything to do with environment variable size

**Comment by piotrplenik** [comment]
The simplest solution that I found:
```
terraform {
  source = "https://github.com/terraform-aws-modules/terraform-aws-route53//modules/records/.?ref=v3.1.0"
  extra_arguments "common_var" {
    commands = get_terraform_commands_that_need_vars()
    arguments = ["-var-file=${get_terragrunt_dir()}/input.tfvars"]
  }
}
```
And move all input variables into HCL `input.tfvars` file.

**Comment by Sathish7-commits** [comment]
I had the same issue with deploying larger step function which is of json type. 

Slightly tweaked the generate function for my use case

```
generate "vars_input" {
  path              = "variables.auto.tfvars.json"
  if_exists         = "overwrite"
  disable_signature = true
  contents          = <<EOF
{
  "definition": ${file("${get_path_to_repo_root()}/step_function_file.json")}
}
EOF
}
```
