### ISSUE TITLE
Terraform 1.2.x and Terragrunt compatibility

### ISSUE THREAD

**Issue by jlosito** [gruntwork-io/terragrunt#2133]
Terraform 1.2.x is out at the time of writing, and I'm in the process of upgrading my personal state files, but do not know for certain whether I should upgrade to a later version of Terragrunt. I usually make reference of the pages below for the compatibiliy tuple between Terraform and Terragrunt, but there is not one listed yet for Terraform 1.2.x.

https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
https://github.com/gruntwork-io/terragrunt/blob/master/docs/_docs/01_getting-started/supported-terraform-versions.md

It would be extremely helpful if the compatibility between versions was listed there.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.38.0
