### ISSUE TITLE
Terragrunt can't pull private repositories with ssh on gh actions

### ISSUE THREAD

**Issue by pputman-clabs** [gruntwork-io/terragrunt#2139]
I have the log of the issue below.  I have one repository with my terragrunt configuration, calling another private repository in github with my terraform modules.
I have verified my ssh key works because I've used it with other github actions to pull down the private repository, and if I set that private repository to public, then I can run terragrunt and pull down the modules.

Also,  can run this terragrunt setup locally with the same ssh key and pull down the terraform modules.

Is this a problem with terragrunt, or github actions?  Seems like something weird when both of them are together, because separately each one can access the repo, its only when I use terragrunt on github actions that it can't.

with:
    tf_actions_version: latest
    tg_actions_version: latest
    tf_actions_subcommand: init
    tf_actions_working_dir: ./okta/dev/accounts/groups
    tf_actions_comment: true
    tf_actions_binary: terragrunt
    tf_actions_cli_credentials_hostname: app.terraform.io
    tf_actions_fmt_write: false
  env:
    OKTA_API_TOKEN_DEV: ***
    tf_version: latest
    tg_version: latest
    tf_actions_dev_groups_working_dir: ./okta/dev/accounts/groups
    tf_actions_dev_users_working_dir: ./okta/dev/accounts/users
    tf_actions_dev_user_profiles_working_dir: ./okta/dev/accounts/user-profiles
    tf_actions_dev_aws_app_working_dir: ./okta/dev/apps/aws
    tf_actions_dev_google_workspaces_app_working_dir: ./okta/dev/apps/google-workspaces
    tf_actions_dev_google_cloud_app_working_dir: ./okta/dev/apps/google-cloud
    SSH_AUTH_SOCK: /tmp/ssh-M2Ypm[3](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:3)DzkgvD/agent.1760
    SSH_AGENT_PID: 1761
    GITHUB_TOKEN: ***
/usr/bin/docker run --name b319c02[4](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:4)c7e374446a2b7141d6b[5](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:5)bd8[6](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:6)4cb_f42488 --label 294b31 --workdir /github/workspace --rm -e OKTA_API_TOKEN_DEV -e tf_version -e tg_version -e tf_actions_dev_groups_working_dir -e tf_actions_dev_users_working_dir -e tf_actions_dev_user_profiles_working_dir -e tf_actions_dev_aws_app_working_dir -e tf_actions_dev_google_workspaces_app_working_dir -e tf_actions_dev_google_cloud_app_working_dir -e SSH_AUTH_SOCK -e SSH_AGENT_PID -e GITHUB_TOKEN -e INPUT_TF_ACTIONS_VERSION -e INPUT_TG_ACTIONS_VERSION -e INPUT_TF_ACTIONS_SUBCOMMAND -e INPUT_TF_ACTIONS_WORKING_DIR -e INPUT_TF_ACTIONS_COMMENT -e INPUT_TF_ACTIONS_BINARY -e INPUT_TF_ACTIONS_CLI_CREDENTIALS_HOSTNAME -e INPUT_TF_ACTIONS_CLI_CREDENTIALS_TOKEN -e INPUT_TF_ACTIONS_FMT_WRITE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/okta-live-config/okta-live-config":"/github/workspace" 294b31:9c024c[7](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:7)e374446a2b7141d6b5bd[8](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:8)64cb
Checking the latest version of Terraform
Downloading Terraform v1.1.[9](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:9)
Successfully downloaded Terraform v1.1.9
Unzipping Terraform v1.1.9
Successfully unzipped Terraform v1.1.9
Checking the latest version of Terragrunt
Downloading Terragrunt v0.36.7
Successfully downloaded Terragrunt v0.36.7
Moving Terragrunt v0.36.7 to PATH
Successfully moved Terragrunt v0.36.7
init: info: initializing Terragrunt configuration in ./okta/dev/accounts/groups
init: error: failed to initialize Terragrunt configuration in ./okta/dev/accounts/groups
time=2022-04-21T16:02:41Z level=error msg=1 error occurred:
	* error downloading 'ssh://git@github.com/celo-org/tf-service-catalog.git': /usr/bin/git exited with [12](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:12)8: Cloning into '/github/workspace/okta/dev/accounts/groups/.terragrunt-cache/nzkLeP6grxGpGN1eoHw1_Nk0vVk/fLaSWSh_aJYGXkJFdH61Aul2BUI'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
time=2022-04-21T[16](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:16):02:[41](https://github.com/celo-org/okta-live-config/runs/6115439556?check_suite_focus=true#step:7:42)Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1

**Comment by pputman-clabs** [comment]
Hi Denis,

  I originally thought that was the case too, but I'm able to connect to
the github runner and do the following from its terminal:

[image: image.png]


***@***.***:~/work/okta-live-config/okta-live-config$ ssh -Tv
***@***.***
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf
matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to github.com [140.82.113.3] port 22.
debug1: Connection established.
debug1: identity file /home/runner/.ssh/id_rsa type -1
debug1: identity file /home/runner/.ssh/id_rsa-cert type -1
debug1: identity file /home/runner/.ssh/id_dsa type -1
debug1: identity file /home/runner/.ssh/id_dsa-cert type -1
debug1: identity file /home/runner/.ssh/id_ecdsa type -1
debug1: identity file /home/runner/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/runner/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/runner/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/runner/.ssh/id_ed25519 type -1
debug1: identity file /home/runner/.ssh/id_ed25519-cert type -1
debug1: identity file /home/runner/.ssh/id_ed25519_sk type -1
debug1: identity file /home/runner/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/runner/.ssh/id_xmss type -1
debug1: identity file /home/runner/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
debug1: Remote protocol version 2.0, remote software version babeld-dd60f759
debug1: no match: babeld-dd60f759
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: ***@***.*** MAC:
<implicit> compression: none
debug1: kex: client->server cipher: ***@***.*** MAC:
<implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256
SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM
debug1: Host 'github.com' is known and matches the ECDSA host key.
debug1: Found key in /home/runner/.ssh/known_hosts:1
Warning: Permanently added the ECDSA host key for IP address '140.82.113.3'
to the list of known hosts.
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/runner/.ssh/id_rsa
debug1: Will attempt key: /home/runner/.ssh/id_dsa
debug1: Will attempt key: /home/runner/.ssh/id_ecdsa
debug1: Will attempt key: /home/runner/.ssh/id_ecdsa_sk
debug1: Will attempt key: /home/runner/.ssh/id_ed25519
debug1: Will attempt key: /home/runner/.ssh/id_ed25519_sk
debug1: Will attempt key: /home/runner/.ssh/id_xmss
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<
***@***.******@***.***,
***@***.***,
***@***.******@***.***
***@***.***,
***@***.******@***.***,
***@***.******@***.***,
***@***.***
,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/runner/.ssh/id_rsa
debug1: Authentication succeeded (publickey).
Authenticated to github.com ([140.82.113.3]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype ***@***.***
want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = C.UTF-8
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
Hi celo-org/tf-service-catalog! You've successfully authenticated, but
GitHub does not provide shell access.
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2704, received 2348 bytes, in 0.2 seconds
Bytes per second: sent 17230.2, received 14961.7
debug1: Exit status 1


So the ssh key appears to be working properly, but terragrunt isn't using
it for some reason? Not sure how to test this further.

**Comment by asaf-upstream** [comment]
Hi @pputman-clabs , cloud you plz elaborate on your solution?
I am facing the same issue, probably with  the same gh action..
Did you forked it and added the key  into the new repo and dockerfile?

**Comment by Quixotical** [comment]
since OP kind of left a mystery for the reader to solve themselves, I figured I'd leave a comment on a pretty janky solution that seems to be working for me. FWIW I'm shocked that it's this convoluted to get SSH working when terragrunt docs themselves seem to indicate we should be using SSH, and that separating TF modules from HCL implementations is a good practice, but I digress, not here to rant.

So it seems the issue is that for some reason, TG in GitHub actions does not care about your SSH key out of the box and you can set it/tell TG to use it, but it doesn't care. I can no longer find the other issue which gave me this answer, but basically like OP said, the init command is in an isolated container, so it doesn't know anything about our SSH access we configured 🎉 

So we need to do some janky stuff, specifically we need to make a temporary directory for passing our ssh-agent socket to:

```
    - name: create directory to pass ssh-agent socket
      run: "mkdir -p /home/runner/work/_temp/_github_workflow"
      shell: bash

    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.TERRAFORM_MODULES_READ_KEY_PVT }}
        ssh-auth-sock: "/home/runner/work/_temp/_github_workflow/ssh-agent.sock"
```

and then in the terra grunt action for plan/apply, you need to do the following:

```
- name: Terragrunt Plan
      uses: gruntwork-io/terragrunt-action@v1
      with:
        tf_version: ${{ env.tf_version }}
        tg_version: ${{ env.tg_version }}
        tg_dir: ${{ env.working_dir }}
        tg_command: 'run-all plan'
      env:
        SSH_AUTH_SOCK: "/github/workflow/ssh-agent.sock"
```

Then it works 🤷

**Comment by davaba86** [comment]
> since OP kind of left a mystery for the reader to solve themselves, I figured I'd leave a comment on a pretty janky solution that seems to be working for me. FWIW I'm shocked that it's this convoluted to get SSH working when terragrunt docs themselves seem to indicate we should be using SSH, and that separating TF modules from HCL implementations is a good practice, but I digress, not here to rant.
> 
> So it seems the issue is that for some reason, TG in GitHub actions does not care about your SSH key out of the box and you can set it/tell TG to use it, but it doesn't care. I can no longer find the other issue which gave me this answer, but basically like OP said, the init command is in an isolated container, so it doesn't know anything about our SSH access we configured 🎉
> 
> So we need to do some janky stuff, specifically we need to make a temporary directory for passing our ssh-agent socket to:
> 
> ```
>     - name: create directory to pass ssh-agent socket
>       run: "mkdir -p /home/runner/work/_temp/_github_workflow"
>       shell: bash
> 
>     - uses: webfactory/ssh-agent@v0.7.0
>       with:
>         ssh-private-key: ${{ secrets.TERRAFORM_MODULES_READ_KEY_PVT }}
>         ssh-auth-sock: "/home/runner/work/_temp/_github_workflow/ssh-agent.sock"
> ```
> 
> and then in the terra grunt action for plan/apply, you need to do the following:
> 
> ```
> - name: Terragrunt Plan
>       uses: gruntwork-io/terragrunt-action@v1
>       with:
>         tf_version: ${{ env.tf_version }}
>         tg_version: ${{ env.tg_version }}
>         tg_dir: ${{ env.working_dir }}
>         tg_command: 'run-all plan'
>       env:
>         SSH_AUTH_SOCK: "/github/workflow/ssh-agent.sock"
> ```
> 
> Then it works 🤷

Works like a charm; thanks for posting this!

**Comment by AlverezYari** [comment]
Unfortunately this doesn't work with multiple deploy keys. The action says it supports it but it doesn't.

**Comment by MarcelvEPAX8** [comment]
Love this workaround for SSH authentication.
I have succesfully applied this.

I'd prefer using Github Apps instead, but this is second best.
Have not been able to get github app installation token to work with the same issue.
