### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by jakshi** [gruntwork-io/terragrunt#215]
I have this issue when I try to run `terragrunt plan`.

```
$ terragrunt plan
[terragrunt] [/Users/kostiantynlysenko/ddproperty/git-repos/terraform/aws/environments/integration/networking] 2017/05/11 12:01:47 Running command: terraform --version
[terragrunt] 2017/05/11 12:01:47 Reading Terragrunt config file at /Users/kostiantynlysenko/ddproperty/git-repos/terraform/aws/environments/integration/networking/terraform.tfvars
[terragrunt] 2017/05/11 12:01:47 unexpected end of JSON input
[terragrunt] 2017/05/11 12:01:47 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

How can I debug that?

**Comment by jakshi** [comment]
Found the issue.
I migrated terraform.tfstate to s3, and after that terraform.tfstate wasn't removed, but became 0 size terraform.tfstate file.
It seems that terragrunt always try to read local terraform.tfstate even if remote backend is configured.
So when it try to read 0 size terraform.tfstate it throws that error.
Removing terraform.tfstate 0 size file solved this issue.

**Comment by raxod502** [comment]
I had this same problem. Is there a reason that the default behavior is to trim the local state to zero-length, but not remove it? This seems like a bad idea to me.
