### ISSUE TITLE
An `excluded-dir` causes a failure on `run-all apply`

### ISSUE THREAD

**Issue by oatmealb** [gruntwork-io/terragrunt#2167]
I ran a `run-all apply` from `$BASE_PATH/env_A` (referred to in the error log below). The `Required environment variable` wasn't set indeed, but **should/may an `excluded-dir` be able to cause this, or any, failure**? This `some_service` is a leaf in the dependencies graph.

> BASE_PATH=...
> EXCLUDED_DIR=...
> terragrunt run-all apply --terragrunt-exclude-dir $EXCLUDED_DIR                                                          
ERRO[0000] Error processing module at '$BASE_PATH/env_A/$EXCLUDED_DIR/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of $BASE_PATH/env_A/. Underlying error: $BASE_PATH/env_COMMON/some_service.hcl:25,23-31: Error in function call; Call to function "get_env" failed: EnvVarNotFound: Required environment variable TF_VAR_foo - not found. 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 

v0.37.1

**Comment by levkohimins** [comment]
Resolved in [v0.50.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.1) release.
