### ISSUE TITLE
terragrunt clone folder

### ISSUE THREAD

**Issue by shaharmor** [gruntwork-io/terragrunt#218]
Hey,

I want to use a `local-exec` provisioner while using terragrunt, but my command needs to reference a path that is not being cloned when using terragrunt.

My folder structure is as follow:

```
repo
|- scripts
|  |- init.sh
|
|- terraform
|  |- modules
|  |  |- app
|  |
|  |- environments
|  |  |- staging
|  |  |  |- app
```

I run `terragrunt` from within `repo/terraform/environments/staging/app`, but I want to reference the `repo/scripts/init.sh` script from within the `local-exec` provisioner that I configured in `repo/terraform/modules/app/main.tf`.

But when I run `terragrunt` it only clones the `terraform` module and of the folders below it, and not the whole repo which has the scripts I need.

How can i achieve that?

**Comment by brikis98** [comment]
Try putting a double slash in your `source` path. E.g. 

```hcl
terragrunt = {
  terraform {
    source = "repo//terraform/modules/app"
  }
}
```

The double-slash will result in Terragrunt copying everything in the `repo` folder to the temp directory, so that relative paths between those folders should work.

**Comment by shaharmor** [comment]
Thnx, worked!

**Comment by atrakic** [comment]
what if you need to reference file residing in separate repo?
