### ISSUE TITLE
Terragrunt prompting for https clone credentials despite being told to specifically use ssh

### ISSUE THREAD

**Issue by B1T3X** [gruntwork-io/terragrunt#2188]
Hi,
I've been breaking my teeth on this one for a few weeks now.
I'm trying to reference a module in a private self-hosted GitLab repository by specifying the source as such:
`source = "git::ssh://git@************/username/reponame.git//path/to/module?ref=master"`
(Yes, the branch name is master, rather than main)

The following prompt I get:
`Password for 'https://git@***********':`

Anyone managed to solve this?
I'm pulling my hairs out and can't find anything like this issue or a solution anywhere.

Thanks in advance, Orel

OS: MacOS Monterey 12.4
Hardware: Macbook Pro M1 Pro chip
Terraform & Teraggrunt versions:
Terraform v1.2.4
terragrunt version v0.38.3

**Comment by denis256** [comment]
Hi, 
try `git::git@gitlab.com:...`

**Comment by B1T3X** [comment]
> Hi, try `git::git@gitlab.com:...`
> 
> More details:
> 
> https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform
> 
> ```
> ...
> Complete Example:
> ...
> terraform {
>   source = "git::git@...
> }
> ...
> ```

Here's what I get now:
```
ERRO[0000] 1 error occurred:
 error downloading 'file://<CURRENT_PATH>/git@*************/path/to/module.git?ref=master': /opt/homebrew/bin/git exited with 128: Cloning into '<CURRENT_PATH>/.terragrunt-cache/iYial7est-6SZT1TZSFuBe4sts8/0C8A3wRl1cArtYyerBxTED3e4Vc'...
 
fatal: '<CURRENT_PATH>/git@**************/path/to/cloud-module.git' does not appear
 to be a git repository
fatal: Could not read from remote repository.

```

**Comment by yorinasub17** [comment]
I think this might actually be because you have a `git config` entry that replaces SSH URLs with HTTPS URLs. When you do `git config -l`, do you have any entry that looks like the following?

```
url.https://gitlab.com.insteadOf=ssh://git@gitlab.com
```

**Comment by B1T3X** [comment]
> I think this might actually be because you have a `git config` entry that replaces SSH URLs with HTTPS URLs. When you do `git config -l`, do you have any entry that looks like the following?
> 
> ```
> url.https://gitlab.com.insteadOf=ssh://git@gitlab.com
> ```

This is so incredibly awkward. That was the issue. Thank you so much and I apologize.
