### ISSUE TITLE
How to update provider plugin to specific version using terragrunt

### ISSUE THREAD

**Issue by pravindhawas** [gruntwork-io/terragrunt#2206]
I have specific version of aws plugin in main.tf. As shown below:
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27.0"
    }
  }
}
Now I am using terragrunt and want to change the plugin version to specific version apart from mentioned in main.tf.
Lets say, I want to change plugin version to 3.74.0 without changing it in main.tf.
How can I achieve this using terragrunt? Thank you in advance!

**Comment by denis256** [comment]
Hi,
for this case, I was thinking about a "common" hcl file with version definition, and usage of defined value in "generate" blocks where it is required:

```
# terragrunt.hcl
include "aws_configs" {
  path = find_in_parent_folders("aws_config.hcl")
  expose = true
}

generate = {
  test = {
    path      = "providers.tf"
    if_exists = "overwrite"
    contents  = <<EOF
terraform {
  required_providers {
    mycloud = {
      source  = "hashicorp/aws"
      version = "~> ${include.aws_configs.locals.aws_version}"
    }
  }
}
EOF
  }
}

```

```
# aws.hcl
locals {
  aws_version = "3.27.0"
}
```

References:
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#include
https://github.com/denis256/terragrunt-tests/tree/master/issue-2206

**Comment by pravindhawas** [comment]
Thank you for response!

**Comment by pravindhawas** [comment]
Closing the issue
