### ISSUE TITLE
Support for S3 + Zip module source

### ISSUE THREAD

**Issue by maartenvanderhoef** [gruntwork-io/terragrunt#2208]
Terraform has the ability to use .zip file as source on s3, https://www.terraform.io/language/modules/sources#s3-bucket, advantage is the built-in S3 all and the speed of downloading a single module, all free, without having to setup a private repository.

Terragrunt however seems to be limited to either git or using `tfr://` with private repositories.

**Comment by denis256** [comment]
Hi,
`s3::` can also be referenced in `terraform` block since [`go-getter`](https://github.com/hashicorp/go-getter) library is used to download files:
```
# terragrunt.hcl
terraform {
  source = "s3::https://rnd-terraform-test.s3.eu-central-1.amazonaws.com/terraform-test-module-master.zip//terraform-test-module-master/modules/test-file"
}
```

Usage:
```
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=yyy

terragrunt apply

```

**Comment by maartenvanderhoef** [comment]
Awesome, that's it , thank you!
