### ISSUE TITLE
Documentation: Automate the maintenance of the ToC for the README

### ISSUE THREAD

**Issue by conorgil** [gruntwork-io/terragrunt#221]
#216 adds a ToC to the README to help improve usability. However, maintaining this manually is error prone and annoying. Figure out a way to automate the maintenance of the ToC in the README.

Seems like there is a lot of conversation about support of ToC over in https://github.com/isaacs/github/issues/215 and https://github.com/github/markup/issues/904. Several tools are mentioned, which we could try out.

Alternatively, if #220 is determined to be a good idea, then the ToC issue in the README would likely become unnecessary.

**Comment by brikis98** [comment]
Terragrunt now has its own website with a way to manage the TOC: https://terragrunt.gruntwork.io/
