### ISSUE TITLE
Unable to see CLI options for terragrunt subcommands

### ISSUE THREAD

**Issue by infraredgirl** [gruntwork-io/terragrunt#2222]
If the user ones to find out which options are available for e.g. the `terragrunt render-json` subcommand, there is currently no way to see this in the CLI itself, and they have to go to the docs website to find out. We should make it possible to see the options/flags from the CLI itself.

**Comment by denis256** [comment]
CLI help released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.39.1
