### ISSUE TITLE
Warning of S3 state encryption when skip_bucket_ssencryption is set to true

### ISSUE THREAD

**Issue by guidodobboletta** [gruntwork-io/terragrunt#2227]
I'm getting this warning on my CLI
```
WARN[0000] Encryption is not enabled on the S3 remote state bucket REDACTED. Terraform state files may contain secrets, so we STRONGLY recommend enabling encryption!
```

I have these settings in my remote backend block
```
remote_state {
  backend = "s3"
  config = {
    bucket                   = "redacted"
    key                      = "tfstate"
    region                   = "redacted"
    encrypt                  = false
    skip_bucket_ssencryption = true
    skip_bucket_root_access  = true
    skip_bucket_enforced_tls = true
  }
}
```

versions:
```
terragrunt version v0.38.6
Terraform v1.2.6 on linux_amd64
```

Is there any other way to disable this warning for every `terragrunt` command I run?

**Comment by denis256** [comment]
Hi,
looks like the message is set to be printed if encryption is not enabled:
https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L361

**Comment by guidodobboletta** [comment]
Yes I saw that but can we add a way to remove the warning? If I'm purposely enabling `skip_bucket_ssencryption` I shouldn't get a warning message anyway

**Comment by kaden-l-nelson** [comment]
@denis256 there is an open PR to address this, may you please review?
