### ISSUE TITLE
Question on how after_hook execute access to environment variable

### ISSUE THREAD

**Issue by BAu0002** [gruntwork-io/terragrunt#2229]
I'm trying to run a simple execute that acquire the environment variable

after_hook "setvariable" {
    commands    = ["plan"]
    execute     = ["export", "PROPERTY_ID='1'"]
 }

after_hook "getEnvironment" {
    commands    = ["plan"]
    execute     = ["env"]
 }

after_hook "run" {
    commands    = ["plan"]
    execute     = ["echo", "$PROPERTY_ID"]
 }

getEnvironment hook show that environment variable has been set.
run hook just out put $PROPERTY_ID.   The variable not being resolved.   

Can terragrunt execute resolve environment variables?

**Comment by denis256** [comment]
Hi,
AFAIK each `execute` is invoked individually and exported environment variables will not be passed to the next steps

**Comment by BAu0002** [comment]
Your statement does not explain why 'env' command will show the set environment variable.

I'm going to make a guess that execute is running in some kind of shell that does not work with variables.

I've worked around the issue by having one step install results to a file and second step to run a bash script that read the file.
