### ISSUE TITLE
Is there any way to version control terragrunt.hcl?

### ISSUE THREAD

**Issue by buddwm** [gruntwork-io/terragrunt#2237]
I see plenty of examples in Terragrunt where I can version control any TF code via git tags, etc, but I'm finding that if I change my inputs in my `terragrunt.hcl`, the git tag doesn't seem to apply to the file itself.  Example is that I have a `network.hcl` as follows (not a real git source but you get the idea hopefully):

```
locals {
  global_vars     = yamldecode(file("${find_in_parent_folders("global.yaml")}"))
  base_vars       = yamldecode(file("${find_in_parent_folders("base.yaml")}"))
  env_vars        = yamldecode(file("${find_in_parent_folders("env.yaml")}"))

  global_name     = local.global_vars.name
  env_name        = local.env_vars.name
  infra_tag       = local.base_vars.infra_tag[local.global_name]
}

terraform {
  source          = "git::ssh://git@github.com/terragrunt-test.git//terraform/_commonstack/network?ref=${local.infra_tag}"
}

inputs = {
  name            = "${local.global_name}-${local.env_name}",
}
```

The `_commonstack/network?ref=${local.infra_tag}` is a TF module.  I can call on the `network.hcl` with an `include` in a `terragrunt.hcl` elsewhere in my repo.

```
include "root" {
  path = find_in_parent_folders()
}

include "network" {
  path = "${dirname(find_in_parent_folders())}/_tgstack/network.hcl"
}

inputs = merge(
  (read_terragrunt_config("vpc.hcl").locals),
  (read_terragrunt_config("subnet.hcl").locals),
  (read_terragrunt_config("route-table.hcl").locals),
  (read_terragrunt_config("elastic-ip.hcl").locals),
  (read_terragrunt_config("nat-gateway.hcl").locals),
  (read_terragrunt_config("transit-gateway.hcl").locals),
  (read_terragrunt_config("internet-gateway.hcl").locals),
  (read_terragrunt_config("virtual-private-gateway.hcl").locals),
)
```

The problem is that if I change any of the inputs in the `terragrunt.hcl`, the new inputs apply even if I want Terragrunt to pull from and respect the git tag.  How do I "freeze" the terragrunt.hcl file in place?  I tried using git as the source for the `include` but it seems to mangle the path and I'm not sure this would have the desired effect anyway since I want to version control the actual `terragrunt.hcl` and respective inputs.

EDIT: A more complete example of where this problem would reside would be [the terragrunt infrastructure live example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/).  The `_envcommon` files or any of the child `terragrunt.hcl` files don't appear to have a way to be version controlled, so any input changes would get applied regardless of the git tag on the TF source.

**Comment by denis256** [comment]
Hi,
I think it is by design to apply each time inputs, to download terraform source, may be used `terragrunt get / terragrunt run-all get`

**Comment by buddwm** [comment]
I thought `terraform get` was only for grabbing modules - does it apply to getting the `terragrunt.hcl` files as well?  I'll need to test it out when I have time but didn't consider it because I thought it only applied to the module sources.

**Comment by denis256** [comment]
AFAIK, `terragrunt get` will only download all required dependencies without applying of HCLs
