### ISSUE TITLE
How to enable the plan to show the actual difference in data when Json input is used?

### ISSUE THREAD

**Issue by prsshini** [gruntwork-io/terragrunt#2244]
Hello,
I am passing the input as Json to create a SSM parameter with the Json value. When I change my input and run the plan, the plan shows only the hash difference rather than showing what the actual data that is being changed. How can I make my plan show the actual data that will be changed in Json value of the store?

resource "aws_ssm_parameter" "pool_config_param" {
        arn         = "arn:aws:ssm:us-east-1:xxxxxxxx:parameter/myTestStore"
        data_type   = "text"
        description = "test"
        id          = "/myTestStore"
        key_id      = "alias/aws/ssm"
        name        = "/myTestStore"
        overwrite   = true
        tier        = "Standard"
        type        = "String"
      ~ value       = (sensitive value)  ----> I like to see the actual data that will be changed here.. Can I do that?
      ~ version     = 1 -> (known after apply)
    }

terragrunt.hcl :

parameter_value = {
    attribute1           = "test"
    attribute2= "test"
    attribute3   = "test"
  }

main.tf:

resource "aws_ssm_parameter" "myparamterstore" {
  name        = "/myTestStore"
  description = "Test Description"
  type        = "String"
  value       = jsonencode(var.parameter_value )
  overwrite   = true
   tags = merge(
    var.default_tags,
    {
      Name = "Test "
    }
  )
}

**Comment by denis256** [comment]
Hi,
AFAIK 'sensitive' data from terraform can be listed if plan will be saved to a file and used `show` command:

```
terragrunt plan -out=tfplan
terragrunt show -json tfplan
```

Also can be tried to set `sensitive = false` on `parameter_value` but it didn't worked in my attempts
