### ISSUE TITLE
S3 State bucket - put public access block denied

### ISSUE THREAD

**Issue by gpdenny** [gruntwork-io/terragrunt#2245]
We are using a combination of account level S3 public access block, and an organization SCP that prevents the use of `PutBucketPublicAccessBlock`. 

This results in a (non-blocking, but mildly irritating) access denied error when creating new state buckets, and always having to skip bucket update for public access blocking when re-initialising a module to prevent access denied errors.

![Selection_1343](https://user-images.githubusercontent.com/37297485/185663378-599d216c-9cee-43e2-a3e0-cb98b16109cd.png)

I believe we can use `disable_bucket_update` for the second case, but for the first it seems like Terragrunt will always try to enable public access block on new buckets.

Is there a possibility of introducing a skip for public access blocking, similar to other bucket configurations?

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.38.8
