### ISSUE TITLE
Blocks of type "import" are not expected here

### ISSUE THREAD

**Issue by srinathjamboju92** [gruntwork-io/terragrunt#2247]
https://terragrunt.gruntwork.io/docs/rfc/imports/#import-block-hierarchical-variables-included-across-multiple-terragrunthcl-files

Trying to evaluate "import" block from the above URL and replicated the same directory structure. But seeing below error on "terra grunt validate".

Terragrunt version: "v0.38.7"
Terraform version: "v1.2.1"

Unsupported block type; Blocks of type "import" are not expected here., and 1 other diagnostic(s) 
ERRO[0001] Unable to determine underlying exit code, so Terragrunt will exit with error code 1

**Comment by denis256** [comment]
Hi,
it is expected to not work since it is in "Rfc" section with `STATUS: In development`
