### ISSUE TITLE
Confusing error message for data type error in nested struct

### ISSUE THREAD

**Issue by everops-miked** [gruntwork-io/terragrunt#2263]
Dear Terragrunt,
I am getting a confusing error message.
```
Error: Invalid value for input variable

The environment variable TF_VAR_somename does not
contain a valid value for variable "somename ": a number
is required.
```

But it would be better for understanding if the error was this
```
`The environment variable TF_VAR_somename[0].foo does not contain a valid value for variable "somename[0].foo ": a number is required.
```

In fact I think it is a terraform error because I think terragrunt passes the variables to terraform via the env variables. In any case it took me some time to find the error and I wanted to document this for the next person. 

I have a variable like this 
```
variable "somename" {
  type = set(object(
    {
      blah = string
      foo  = number
    }
  ))
  default = []
}
```

and it is used like this
```
somename = [{
blah="ffdsds", 
foo="this should be a number"}]
```

The error message does not tell me what the error is and the part about the environment variables was confusing.

**Comment by levkohimins** [comment]
Hi @everops-miked,

> In fact I think it is a terraform error because I think terragrunt passes the variables to terraform via the env variables.

Your assumption is correct. The same issue was created in terraform issues https://github.com/hashicorp/terraform/issues/27773 
So unfortunately there is nothing we can do about it. I am closing the issue.
