### ISSUE TITLE
How to design directory layout to create folders resource  by terragrunt

### ISSUE THREAD

**Issue by wengchaoxi** [gruntwork-io/terragrunt#2269]
Hi, I'm using terragrunt to create resources with dependencies: folders.

I want to know if the following design makes sense: each `terragrunt.hcl` corresponds to the folder in which it is located and the properties of that folder.
```hcl
root
 ├── folder1
 |   └── terragrunt.hcl    // used to create folder1
 └── folder2
     ├── terragrunt.hcl    // used to create folder2
     └── folder3
         └── terragrunt.hcl    // used to create folder3
```
I worry that this design will make the directory hierarchy more complex as the number of folders increases. If that's not reasonable, is there a better solution?

Thanks.

**Comment by denis256** [comment]
Hi,
indeed deep hierarchical structure will make core complicated to understand the project and it is quite project-specific

Some ideas and references can be found in:
https://terragrunt.gruntwork.io/docs/features/keep-your-terraform-code-dry/ 
https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/
