### ISSUE TITLE
plan-all fails with interpolation in comment

### ISSUE THREAD

**Issue by daveqr** [gruntwork-io/terragrunt#227]
In a terraform.tfvars file, I have the following lines:

```
#  name = "${var.env}-${var.cluster_name}"
cluster_name = "stage-webservers-state"
```

When I run

```
$ terragrunt plan-all
```

I get this error:

```
Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${var.env}-${var.cluster_name}'
```

Maybe this is expected behavior, but because the line is commented, I expected it to be ignored.

**Comment by brikis98** [comment]
Definitely a bug. Terragrunt is searching for interpolations with a simple regex and it's clearly looking beyond where it should.

**Comment by brikis98** [comment]
We switched to proper HCL parsing long ago, so this should no longer be an issue.
