### ISSUE TITLE
Occasional rate limit error when retrieving modules from CodeCommit

### ISSUE THREAD

**Issue by lorengordon** [gruntwork-io/terragrunt#2275]
I'm occasionally seeing rate limit errors when retrieving modules that are hosted in CodeCommit. I think this could be addressed by adding a regex for this error to the [list of retryable errors](https://github.com/gruntwork-io/terragrunt/blob/988144701b12bf51bf8315d1d6fc28539673913d/options/auto_retry_options.go?rgh-link-date=2020-10-09T14%3A51%3A14Z#L10).

The error is of the form:

```
Error: Failed to download module
Could not download module "<MODULE_NAME>" (<FILENAME>:<LINENO>) source code from "<SOURCE URL>":
error downloading '<SOURCE_URL>':
/usr/bin/git exited with 128: Cloning into '<CLONE DIR>'...
fatal: unable to access '<REPO_URL>':
The requested URL returned error: 429
```

I think this regex would work: `"(?s).*Error: Failed to download module.*The requested URL returned error: 429.*"`

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.38.12
