### ISSUE TITLE
Question about Backend Migration

### ISSUE THREAD

**Issue by jevon71-work** [gruntwork-io/terragrunt#228]
Terragrunt appears to do the run of terraform init to do the migration of remote state.  My question is do you still recommend following ALL the instructions of the Terraform upgrade strategy, including using the older version of Terraform to "backup" the old version of the state file prior to migration?

Thanks,

Jevon

**Comment by brikis98** [comment]
Are you talking about [migrating state from Terraform 0.8 to 0.9?](https://www.terraform.io/docs/backends/legacy-0-8.html) If so, then doing a backup is always a good idea before major changes. That said, if you were already using, for example, S3 as your remote state store, and you had [enabled versioning on your S3 bucket](http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html), then backups are built-in, and no further action is necessary.

**Comment by jevon71-work** [comment]
Thanks very much for the clarification - closing issue.
