### ISSUE TITLE
Multiple includes circumvent duplicate generate detection

### ISSUE THREAD

**Issue by erpel** [gruntwork-io/terragrunt#2280]
In #1795 / https://github.com/gruntwork-io/terragrunt/releases/tag/v0.31.9 a feature was released that should alert users to the existence of multiple generate blocks with the same name.
I encountered the situation that this check does not detect multiple generate blocks if they come from different includes.

I created a minimal example to check this: https://github.com/erpel/terragrunt_duplicate_generate_reproducer

Both `/terragrunt.hcl` and `/other_module/generate_a.hcl` define a generate block named "a". In module/terragrunt.hcl both files are included. No error is given and the last block wins silently.

To me this looks like a bug since I see no reason to want the duplicate detection be limited to within the same file.

**Comment by denis256** [comment]
Hi,
indeed, `terragrunt render-json` shows that generate block contains only one entry:
```
{
  "dependencies": null,
  "download_dir": "",
  "generate": {
    "a": {
      "comment_prefix": "# ",
      "contents": "other_module",
      "disable_signature": false,
      "if_exists": "overwrite_terragrunt",
      "path": "a.txt"
    }
  },
  "iam_assume_role_duration": null,
  "iam_assume_role_session_name": "",
  "iam_role": "",
  "inputs": null,
  "locals": null,
  "retry_max_attempts": null,
  "retry_sleep_interval_sec": null,
  "retryable_errors": null,
  "skip": false,
  "terraform_binary": "",
  "terraform_version_constraint": "",
  "terragrunt_version_constraint": ""
}

```
