### ISSUE TITLE
Is it possible to override `skip` attribute?

### ISSUE THREAD

**Issue by bmbferreira** [gruntwork-io/terragrunt#2286]
Currently I have some modules that are being skipped by default with the [`skip` attribute](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#skip). I would like to override the value, setting it to false with through the CLI but seems it is not possible.

I'm trying with the following command, but it is not working:
```
terragrunt plan -no-color -lock=false --terragrunt-override-attr skip=false
```

Appreciate any help! Thank you! 🙇

**Comment by denis256** [comment]
Hi,
I think can be used `get_env` function to read from environment variables which modules to skip or to disable skipping

```
# mod2/terragrunt.hcl
skip = get_env("skip_mod2", true)
```

So by default module will be skipped, and only setting `skip_mod2=false` will enable it

**Comment by bmbferreira** [comment]
Thanks for the reply @denis256 ! That works for me 🙇
