### ISSUE TITLE
Add access_token support for the GCS remote state backend config

### ISSUE THREAD

**Issue by GergelyKalmar** [gruntwork-io/terragrunt#2287]
Hi!

Currently it does not seem to be possible to forward an access token to the GCS remote state backend:

```
remote_state {
  backend = "gcs"
  config = {
    # access_token = local.google_access_token # this doesn't work
    credentials = local.google_credentials # this works
    ...
  }
}
```

I see that credentials were added as a response to https://github.com/gruntwork-io/terragrunt/issues/780 but I think the support for access_token is still missing (it is supported by the Google provider otherwise, see https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference#access_token).

Adding support for the access token would be awesome because then anyone would be able to provision with the gcloud credentials with this trick:

```
locals {
  google_access_token = run_cmd(
    "--terragrunt-quiet", "gcloud", "auth", "print-access-token",
    "--configuration", local.organization_id,
  )
}
```

Note that `credentials` isn't documented at the moment (see https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state, `gcs` backend section), it would be potentially great to document these too.

**Comment by marcportabellaclotet-mt** [comment]
Adding this to [remote_state_gcs.go](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_gcs.go#L427) should do the trick.
```
	if gcsConfigRemote.Credentials != "" {
		opts = append(opts, option.WithCredentialsFile(gcsConfigRemote.Credentials))
	} else if gcsConfigRemote.AccessToken != "" {
		tokenSource := oauth2.StaticTokenSource(&oauth2.Token{
			AccessToken: gcsConfigRemote.AccessToken,
		})
		opts = append(opts, option.WithTokenSource(tokenSource))
```
Also this [struct](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_gcs.go#L52) needs to be updated.
```
type RemoteStateConfigGCS struct {
	Bucket        string `mapstructure:"bucket"`
	Credentials   string `mapstructure:"credentials"`
	AccessToken   string `mapstructure:"access_token"`
	Prefix        string `mapstructure:"prefix"`
	Path          string `mapstructure:"path"`
	EncryptionKey string `mapstructure:"encryption_key"`

	ImpersonateServiceAccount          string   `mapstructure:"impersonate_service_account"`
	ImpersonateServiceAccountDelegates []string `mapstructure:"impersonate_service_account_delegates"`
}

```

Already tested and seems to be working.
Not sure if maintainers accept PR.

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.44.4
