### ISSUE TITLE
Terragrunt only creates Dynamo table if S3 bucket doesn't exist.

### ISSUE THREAD

**Issue by apottere** [gruntwork-io/terragrunt#229]
We had a dynamo locking table for a previous version of terragrunt, but after updating it didn't work anymore.  No sweat, I just deleted the dynamo table and terragrunt should re-create it, right?

Unfortunately, it looks like terragrunt only checks if the dynamo table exists after it creates the S3 bucket for remote state - it should always check for the dynamo table just like it always checks for the S3 bucket.

**Comment by brikis98** [comment]
👍
