### ISSUE TITLE
Allow setting environment variables

### ISSUE THREAD

**Issue by AssafKatz3** [gruntwork-io/terragrunt#2290]
Hi,

There are a few specific [environment variables](https://www.terraform.io/cli/config/environment-variables) that Terraform uses. I think Terragrunt should allow to specify them, especially those that there are no other equivalent options like TF_DATA_DIR & TF_IN_AUTOMATION.
I suggest a simple block that allows a set of any environment variable except those which start with TF_VAR_ or TERRAGRUNT_, for example:
```
environment = {
  TF_IN_AUTOMATION = "true",
  TF_REGISTRY_DISCOVERY_RETRY = 1000
}

```

**Comment by pconstantine** [comment]
This is already doable using runcmd().

```
set_environment = run_cmd("export", "MY_VARIABLE=${local.my_variable}")
```

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd

**Comment by AssafKatz3** [comment]
> This is already doable using runcmd().
> 
> ```
> set_environment = run_cmd("export", "MY_VARIABLE=${local.my_variable}")
> ```
> 
> https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd

Hi,
The code above won't help since it won't modify the environment of children processes.
Thanks

**Comment by denis256** [comment]
Hi,
if environment variables are required only in terraform execution, can be attempted to workaround this through `before_hook`

**Comment by AssafKatz3** [comment]
> Hi, if environment variables are required only in terraform execution, can be attempted to workaround this through `before_hook`

Hi,
As far as I understand, the terraform isn't run through the shell, so I don't see any option to create such a workaround.
Thanks

**Comment by timblaktu** [comment]
@AssafKatz3 IMO the best thing here is to just set the env vars in the parent shell, the one calling terragrunt.

@denis256 Re: setting the env using `before_hook`, over in [this issue](https://github.com/gruntwork-io/terragrunt/issues/1581) it was said that hooks don't actually change the child processes env.  I haven't tested this myself, but the documentation says nothing about thing about any guarantees on the child process is environment. So im guessing that hooks are run in a separate subshell from the terraform process.

..and @pconstantine I would think the same is true for `run_cmd`.

**Comment by AssafKatz3** [comment]
> @AssafKatz3 IMO the best thing here is to just set the env vars in the parent shell, the one calling terragrunt.
> 
> @denis256 Re: setting the env using `before_hook`, over in [this issue](https://github.com/gruntwork-io/terragrunt/issues/1581) it was said that hooks don't actually change the child processes env. I haven't tested this myself, but the documentation says nothing about thing about any guarantees on the child process is environment. So im guessing that hooks are run in a separate subshell from the terraform process.
> 
> ..and @pconstantine I would think the same is true for `run_cmd`.


Hi,
I know that I can set environment variables in the parent shell, but the idea of terragrunt is reducing such requirements. I don't want to repeat it again.
Thanks

**Comment by jonwtech** [comment]
Setting env vars in `before_hook` didn't work for me, however I was able to workaround this using the `env_vars` setting in the `extra_arguments` block.

**Comment by AssafKatz3** [comment]
> Setting env vars in `before_hook` didn't work for me, however I was able to workaround this using the `env_vars` setting in the `extra_arguments` block.

This is probably a solution for my concern, so I will close, thanks.

**Comment by HWiese1980** [comment]
> Setting env vars in `before_hook` didn't work for me, however I was able to workaround this using the `env_vars` setting in the `extra_arguments` block.

Could you give a code example on how you did it?

**Comment by jonwtech** [comment]
> > Setting env vars in `before_hook` didn't work for me, however I was able to workaround this using the `env_vars` setting in the `extra_arguments` block.
> 
> Could you give a code example on how you did it

Sure:
```
terraform {
  extra_arguments "kubernetes_provider_config" {
    commands  = ["plan", "apply"]
    arguments = []
    env_vars = {
      KUBE_HOST                 = foo
      KUBE_CLUSTER_CA_CERT_DATA = bar
      KUBE_TOKEN                = baz
    }
  }
}
```
