### ISSUE TITLE
SEO suggestion: include state and/or tfstate in your desc

### ISSUE THREAD

**Issue by astrostl** [gruntwork-io/terragrunt#23]
As-is, this project doesn't show up on a GitHub search for "terraform" + "state"

**Comment by brikis98** [comment]
Haha, great feedback. I made some tweaks to the README. However, the most important thing, ultimately, will be lots of incoming links from happy Terragrunt users :)

All that said, how did you finally find Terragrunt?

**Comment by astrostl** [comment]
Looks like it was the DevOps Weekly mailing list. I tried to recall the name today and couldn't, then when a GitHub search failed I found it in my email and filed the issue. Thx :)
