### ISSUE TITLE
Can hooks access targets?

### ISSUE THREAD

**Issue by hfinucane** [gruntwork-io/terragrunt#2300]
I have an EKS+Applications deployment in Terraform wrapped by Terragrunt, and a full build & teardown cycle will often leak resources for sort of boring reasons- k8s resources that create AWS resources not tearing down completely, etc- so I have some scripts to sweep for leaked resources and clean them up. I wanted to integrate them into the normal `terragrunt` workflow and get rid of our bespoke shell script wrapping terragrunt, but it looks like if I add an after_hook-
```
  after_hook "after_hook" {
    commands     = ["destroy"]
    execute      = ["./cleanup"]
  }
```
I'm signing up to have it run no matter what. Which sort of breaks interactive/development workflows where people might want to run `terragrunt destroy -target=foo.bar.baz && terragrunt apply` or whatever. Is there a different place I can slot this in, or is it not supported?

Sorry if this isn't the wrong forum, I was unsure if this question should go here or in the knowledge-base repo.

**Comment by denis256** [comment]
Hi,
terragrunt commands can be accessed through `get_terraform_cli_args` function, it is returning an array that should somehow be handled:

```
terraform {
  after_hook "after_hook" {
    commands     = ["destroy"]
    # get --target argument
    execute      = ["./cleanup",  get_terraform_cli_args()[1]]
  }
}
```

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terraform_cli_args

**Comment by hfinucane** [comment]
thanks, that makes a lot of sense!
