### ISSUE TITLE
End User License Agreement for Terragrunt

### ISSUE THREAD

**Issue by vasu2809** [gruntwork-io/terragrunt#2302]
Hi - We require EULA for terragrunt if it exists to seek approval for use from our Legal team in our Organization. I was not able to find one - would somebody have the EULA for terragrunt?

Thanks,
Vasu

**Comment by denis256** [comment]
Hi,
AFAIK, license details are in [LICENSE.txt](https://github.com/gruntwork-io/terragrunt/blob/master/LICENSE.txt) file in the root of the repository
