### ISSUE TITLE
Missing cp from $PATH when running before/after hooks

### ISSUE THREAD

**Issue by DevOpsMichael** [gruntwork-io/terragrunt#2304]
I have the following `module.hcl` in the same folder as my `main.tf` (source):
```
locals {
  source = "${get_terragrunt_dir()}/../_base_modules/module/project/"
}

terraform {
  source = local.source

  after_hook "copy_common_tf_to_source" {
    commands = ["init"]
    execute = ["cp", "${get_terragrunt_dir()}/../_base_modules/module/*.common.tf", "."]
  }
}
```
I am trying to copy all the `*.common.tf` files in the folder above my `source` to the same folder as source copies to in my .terragrunt-cache.

I was thinking that an `after_hook` on `init` was the correct way to go about this since that's how the docs did it (near the bottom of the full example, here: https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform) and after researching it seemed that there was no easier way to get files not in the source folder down into `.terragrunt-cache`.

Anyway, when I call `terragrunt init`, I am met with the most unexpected error: The `cp` command is not in my $PATH? I can `cp` normally, though.
```
time=2022-10-11T15:47:46-04:00 level=debug msg=Detected 1 Hooks prefix=[C:\Users\E092218\repos\EUCOMS\eucoms-iac\TESTING_FOLDER\project]
time=2022-10-11T15:47:46-04:00 level=info msg=Executing hook: copy_common_tf_to_source prefix=[C:\Users\E092218\repos\EUCOMS\eucoms-iac\TESTING_FOLDER\project]
time=2022-10-11T15:47:46-04:00 level=debug msg=Running command: cp C:/Users/E092218/repos/EUCOMS/eucoms-iac/TESTING_FOLDER/project/../_base_modules/cosmosdb/*.common.tf . prefix=[C:\Users\E092218\repos\EUCOMS\eucoms-iac\TESTING_FOLDER\project]
time=2022-10-11T15:47:46-04:00 level=error msg=Error running hook copy_common_tf_to_source with message: exec: "cp": executable file not found in %PATH% prefix=[C:\Users\E092218\repos\EUCOMS\eucoms-iac\TESTING_FOLDER\project]
time=2022-10-11T15:47:46-04:00 level=error msg=1 error occurred:
        * exec: "cp": executable file not found in %!P(MISSING)ATH%!
(MISSING)

time=2022-10-11T15:47:46-04:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

I've deleted my `.terragrunt-cache` and `.terraform.lock` files each time I've tested. I experimented using `before_hook` instead, still the same error. I've tried switching `init` to `init_from_module` too, and there was no error but the files I'm trying to copy were not down in `.terragrunt-cache` so I assume that the hook never even triggered.

I noticed another person had this error too (#581 part 2) but nobody responded.

Could anyone help me diagnose this error?
Thank you!

**Comment by DevOpsMichael** [comment]
Should note that I am doing my local terragrunt development on a windows 10 machine. Thought that is important since according to #581 this seems to be a windows-specific issue.

**Comment by DevOpsMichael** [comment]
Hi all!
I noticed I have not gotten any response from anyone in the past week so I was wondering if I need to provide more information?
I also noticed I can't really label this issue w/ the standard 'awaiting response' tags.
Thanks.

**Comment by denis256** [comment]
Hi,
looking at the error message, looks like "cp" executable is not in the path, not sure in Windows if it is a separate executable or a command of shell...
In such cases can be invoked shell binary and passed required command, like:

```
...
  after_hook "copy_common_tf_to_source" {
    commands = ["init"]
    execute = ["bash", "-c", "cp ${get_terragrunt_dir()}/../_base_modules/*.common.tf ."]
  }
...
```

Simplified example in: https://github.com/denis256/terragrunt-tests/tree/master/issue-2304
