### ISSUE TITLE
Support Terraform 1.3.x functions startswith and endwith

### ISSUE THREAD

**Issue by oscarmorasu** [gruntwork-io/terragrunt#2317]
I am using terragrunt version v0.39.1

The [documentation](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#terraform-built-in-functions) says: 

> All [Terraform built-in functions](https://www.terraform.io/docs/configuration/functions.html) are supported in Terragrunt config files

I am using Terraform 1.3, which introduced introduced the [startwith](https://www.terraform.io/language/functions/startswith) and [endwith](https://www.terraform.io/language/functions/endswith) functions, but they are not supported in Terragrunt yet.

**Comment by denis256** [comment]
Hi,
so far Terraform `1.3` is not yet supported:
https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/

**Comment by denis256** [comment]
Support added since Terragrunt v0.40.0 
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.40.0
