### ISSUE TITLE
Support for Terragrunt to be executed programatically

### ISSUE THREAD

**Issue by saad-uddin** [gruntwork-io/terragrunt#2319]
Hi Folks, Do we have any CDK/SDK for terragrunt, so that it can be executed programatically instead of CLI ? 
Just like terraform has this -> https://pkg.go.dev/github.com/hashicorp/terraform-exec/tfexec . 

Use Case : To create API's out of this, and manage infrastructure more efficiently.

**Comment by denis256** [comment]
Hi,
can be tried to use `RunTerragrunt` function:
https://pkg.go.dev/github.com/gruntwork-io/terragrunt@v0.39.1/cli#RunTerragrunt

**Comment by saad-uddin** [comment]
> Hi, can be tried to use `RunTerragrunt` function: https://pkg.go.dev/github.com/gruntwork-io/terragrunt@v0.39.1/cli#RunTerragrunt

Thanks :)
