### ISSUE TITLE
how to avoid code duplication for different env

### ISSUE THREAD

**Issue by genseb13011** [gruntwork-io/terragrunt#2320]
Hi,

Currently we have a folder structure like this:

- root-folder
  - dev
    - global_vars.hcl
    - ops
        - module_1
          - terragrunt.hcl
        - module_2
          - terragrunt.hcl

where global_vars.hcl contains all environment vars.

So to add a new environment, we have to: 

1. copy "dev" folder
2. paste it as "preprod" (as an example) in root-folder
3. change vars in preprod/global_vars.hcl

So we'll have something like this:

- root-folder
  - dev
    - global_vars.hcl
    - ops
        - module_1
          - terragrunt.hcl
        - module_2
          - terragrunt.hcl
   - preprod
    - global_vars.hcl
    - ops
        - module_1
          - terragrunt.hcl
        - module_2
          - terragrunt.hcl

So if I have to change the source git repo ref in terragrunt.hcl of module_1, I have to do it on several terragrunt.hcl (of all env)

Is there a way to avoid this code deduplication? and have something like this:

- root-folder
  - common
    - module_1
      - terragrunt.hcl
    - module_2
      - terragunt.hcl
   - env
     - dev
       - global_vars.hcl
     - preprod
       - global_vars.hcl
     - prod
       - global_vars.hcl

This we'll allow me to have a common code base and only have to change global_vars.

Thanks for your help and advices.

Seb.

**Comment by denis256** [comment]
Hi,
I think can be used `include` / `dependencies` blocks to avoid repetition of code

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#include

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependencies

**Comment by genseb13011** [comment]
Thanks for your answer 

Seb.
