### ISSUE TITLE
Unexpected fatal error with invalid symlink in the configuration

### ISSUE THREAD

**Issue by tavlima** [gruntwork-io/terragrunt#2322]
I have a local TF configuration mounted in `/terraform`, which happens to have a symlink that, when the mounted like that, is invalid. I was surprised to see TG crash with some fatal error, due to that invalid link.

```
ERRO[0001] 1 error occurred:
	* error downloading 'file:///terraform?ref=HEAD': open /terraform/configurations/Makefile: no such file or directory
```

**Comment by denis256** [comment]
Hi,
may be helpful to add `--terragrunt-log-level debug` to get more debug data, I suspect during execution is attempted to calculate checksum of Terraform files to identify changes, and this operation fails because of a broken symlink.
