### ISSUE TITLE
Terragrunt can`t access to dynamoDB lock state to AWS cross account

### ISSUE THREAD

**Issue by OlesYudin** [gruntwork-io/terragrunt#2325]
Hi, folks! I use AWS SSO so I have more than one infrastructure account. In my case I have 1 s3 bucket and 1 dynamoDB table to store tfstate from different account.
I have all necessary permission to DynamoDB, s3 bucket and AWS KMS.

**Account description:**

- account_1 - account where I store s3, kms, dynamoDB
- account_2 - account with simple infrastructure

root terragrunt.hcl looks like this
```
remote_state {
  backend = "s3"
  generate = {
    path      = "config.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    profile         = "account_1"
    bucket          = "bucket-name"
    key             = "path/path/path/path/path/path/${substr(path_relative_to_include(),3, 3)}.tfstate"
    region          = "us-east-1"
    encrypt         = true
    kms_key_id      = "arn:aws:kms:us-east-1:account_1:alias/key_name"
    dynamodb_table  = "arn:aws:dynamodb:us-east-1:account_1:table/table_name"
    disable_bucket_update = true # Prevent terragrunt update s3 bucket policy
  }
}
```

So, I try to run terragrunt from account_2 and everything is okey, but terragrunt try to describe dynamoDB table from account_2 but necessary table store on account_1. 

What I get from cli:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/49691142/196925299-82b73c3a-f8ae-4870-ac3f-542ec9a966fe.png">
In screenshot you can see that terragrunt try to find: `arn:aws:dynamodb:us-east-1:account_2:table/arn:aws:dynamodb:us-east-1:account_1:table/table_name`. But it should find `arn:aws:dynamodb:us-east-1:account_1:table/table_name` . When I use in dynamodb_table value without arn, for example `dynamodb_table = my_lock_id` terragrunt try to find this resource in `arn:aws:dynamodb:us-east-1:account_2:table/my_lock_id` , but I want that terraform find dynamoDB table in `arn:aws:dynamodb:us-east-1:account_1:table/my_lock_id` .

Also, I have created cross account role for dynamoDB like on this [AWS demo](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/configure-cross-account-access-to-amazon-dynamodb.html).

My question is, how to get access to dynamoDB from account_1 and use it on account_2.

**Comment by OlesYudin** [comment]
My problem was in environment variable. I add temporary credentials to AWS_ACCESS_KEY_ID, AWS_ACCESS_SECRET_KEY_ID, etc.. and paste this value to `aws configure` that is why wen terragrunt run it takes wrong AWS_ACCESS_KEY_ID. So, to resolve this issue, you can unset $AWS_ACCESS_KEY_ID and than run `terragrunt init/plan/apply` or you can change name of AWS_ACCESS_KEY_ID when use script to create temp credentials.

**Comment by zackproser** [comment]
Great - thank you for closing the loop!
