### ISSUE TITLE
Dependency Example Breaks

### ISSUE THREAD

**Issue by andrew-kline** [gruntwork-io/terragrunt#2327]
Hi there, I'm working through converting infrastructure to use terragrunt and was using this guide to structure our initial version of this. I love the architecture, but hitting one snag. In the example, the author sets the dependency's config_path to "../vpc" within the _env/app.hcl file. This doesn't seem to work as the path no longer aligns as the definition has moved out of the directory with the different module's terragrunt files. I can't seem to figure out what the right solution would be in this type of file/environment structure where the dependency's output is referenced in the inputs variable but the dependency's config_path is dynamic depending on the environment.

Ask is twofold:
1. Could someone let me know if I'm potentially just incorrectly implementing this and the documentation is correct?
2. If the documentation is incorrect, let me know what a potential solution/workaround is and update the doc?

Thank you so much in advance!

https://github.com/gruntwork-io/terragrunt/blob/331dcc17f5b4947b4edad4e6f296699ac36ca0f8/docs/_docs/02_features/keep-your-terragrunt-architecture-dry.md?plain=1#L377

**Comment by denis256** [comment]
Hi,
paths can be implemented using `get_repo_root` output, extracted as locals in a common file and  included in each child module

References:
https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_repo_root
https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders

Example:

```
common-config
├── config.hcl
├── app
│   ├── main.tf
│   └── terragrunt.hcl
└── module
    ├── main.tf
    └── terragrunt.hcl
```

```
# config.hcl
locals {
  module_path = "${get_repo_root()}/common-config/module"
}

# app/terragrunt.hcl
include "config" {
  path =  find_in_parent_folders("config.hcl")
  expose = true
}

dependency "module" {
  config_path =  include.config.locals.module_path
}
```

So if `module` directory is moved somewhere, path should be updated only `config.hcl`

https://github.com/denis256/terragrunt-tests/tree/master/common-config

**Comment by andrew-kline** [comment]
perfect, that helped significantly - thanks a ton.
