### ISSUE TITLE
Community: Create some community channels for Terragrunt discussions

### ISSUE THREAD

**Issue by conorgil** [gruntwork-io/terragrunt#233]
Similar to other open source projects, it would be great if Terragrunt had some community channels where people could discuss Terragrunt, ask questions, share experiences, etc. Personally, I am a fan of Slack.

@brikis98 @josh-padnick Thoughts on creating a Terragrunt Slack channel? I can create it if you want (I don't want to steal the name out from under you).

**Comment by brikis98** [comment]
+1 on a place for the community to discuss things.

I'm not sure Slack would be the best choice though. In part, I suspect the Terragrunt community isn't nearly big enough to support regular real-time conversations. In part, I have a personal preference towards async communication like email.

What about a Google Group / mailing list?

**Comment by conorgil** [comment]
Google Group seems like a fine place to start. Can always add Slack or something else in the future if it makes sense. Do you want to create the group so that you're the owner? I'm happy to help if it doesn't mess up the permissions moving forward.

**Comment by brikis98** [comment]
OK, I'll look into setting something up this weekend. Thanks for the suggestion!

**Comment by wyardley** [comment]
Some projects (including Terraform) are using https://gitter.im/

**Comment by conorgil** [comment]
@wyardley I have not used Gitter often, but it seems to me like Slack with less features. Again, I'm biased because I use and like Slack, but they all kinda seem the same. Any reasons you think Gitter might be better than Slack (for down the road since we're starting with email anyways)?

**Comment by brikis98** [comment]
Update: I have not lost track of this, but I've been a bit buried lately. Will get to it as soon as I can :)

**Comment by conorgil** [comment]
No worries! We've all been there.

**Comment by robinbowes** [comment]
gitter.im works for me. Slack is more feature rich, but everyone has their own org and it's a pain to follow multiple projects.

**Comment by brikis98** [comment]
We just created a Discourse channel for all Gruntwork tools, including Terragrunt: https://community.gruntwork.io/
