### ISSUE TITLE
Upgrade Terragrunt version

### ISSUE THREAD

**Issue by raoanees** [gruntwork-io/terragrunt#2338]
Hi,
I joined a new company and they have been using Terragrunt 0.26.3 (Terraform 0.13.6) which is fairly an old version, my first task as DevOps engineer is to upgrade the terragrunt version for the IaC repos. Can someone guide me what should be the way to go for this upgrade process? Where should I start and would there be any breaking changes?

**Comment by denis256** [comment]
Hi,
AFAIK exists a migration guide for upgrading from [0.19.x versions](https://terragrunt.gruntwork.io/docs/upgrade/upgrading_to_terragrunt_0.19.x/), for migration to newer versions should be considered Terragrunt and Terraform [compatibility](https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/) versions
