### ISSUE TITLE
HCL to json

### ISSUE THREAD

**Issue by kamilpi** [gruntwork-io/terragrunt#2342]
Hi,

I would like to have a JSON format of my terragrunt.hcl file for third-party application. Actually I need to read specific sections like '''inputs'' and some analysis and other stuff that are out of the terragrunt functionality.

Do you have some idea about this?
If I have a JSON structure I will be able to do this and also open gate will be ready for some new tools.

**Comment by denis256** [comment]
Hi,
was considered to `terragrunt render-json`?

```
$ terragrunt render-json 
$ cat terragrunt_rendered.json | jq .inputs
```

**Comment by normander** [comment]
Yes, this is a good point but I would like to find dependency variables inside submodules so that when I execute render-json it will be rendered and I will not be able to track variables assigned inside.
```
inputs = {
  globals            = dependency.labels.outputs.globals
...
}
```
