### ISSUE TITLE
Only run the command on modules that have the specified file.

### ISSUE THREAD

**Issue by villers** [gruntwork-io/terragrunt#2351]
This allows to manage workspaces and vars files easily

I would create `--terragrunt-layer-has-file` argument to filter terragrunt modules.

exemple:

```bash
TF_WORKSPACE=staging ./terragrunt run-all plan --terragrunt-layer-has-file=/vars/staging.tfvars
```

with the following terragrunt config:

```terraform
terraform {
  extra_arguments "var_file" {
    commands = [
      "apply",
      "plan",
      "import",
    ]
    required_var_files = ["vars/${get_env("TF_WORKSPACE")}.tfvars"]
  }
}
```

**Comment by denis256** [comment]
Hello,
proposed changes, in the end, look specific for one specific case - I was wondering can't be used `--terragrunt-include-dir / --terragrunt-strict-include` options to pass only dependencies which have required `.tfvars`. file? 

References:

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-dir

https://github.com/denis256/terragrunt-tests/tree/master/include-dir-dependencies

**Comment by villers** [comment]
Hey @denis256  😄

Thanks for considering my pull request for Terragrunt. While I appreciate the team's suggestion of a pre-calculation option for the list of directories to process, I've tested it out and found that it's not very practical for everyday use.

As an alternative, I suggested a feature that only runs a command on modules with a specified file, which I think is a more practical and efficient solution for managing modules and workspaces in Terragrunt. This feature not only simplifies the process of managing modules, but also addresses a common request from the Terragrunt community for a workspace management tool. Plus, my pull request has been tested and is ready to be merged, so I believe it would be a great addition to the tool.

If you have any further questions or concerns about my proposal, feel free to let me know. Thanks for your consideration.

**Comment by dim-ops** [comment]
Hey @denis256,

I need of this feature.

I saw a PR created by @villers, is it possible to merge it ?

**Comment by yhakbar** [comment]
Hey folks,

I know this issue was left stale for a while, but I would like to get some clarity on the use of the word "layer" here. Where does that come from? Does something in the docs refer to a "layer" in this way?

**Comment by villers** [comment]
Hey yhakbar,

I know this issue has been dormant for a while, but I’d like to get some clarity on the use of the word “layer” in this context. In this case, a “layer” typically refers to a Terragrunt folder. Each “layer” represents a separate folder in your Terragrunt setup, which usually corresponds to different environments, modules, or components.

Is there something specific in the Terraform or Terragrunt documentation that clarifies this, or are we just using “layer” as shorthand here?

Thanks in advance!

**Comment by yhakbar** [comment]
Currently, we're using the terminology "module":
- https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-dir
- https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-modules-that-include

You can see [here](https://github.com/gruntwork-io/terragrunt/issues/3313) (under `Quick Detour on "Units"`) that we're trying to standardize on "Unit" for the folders that have `terragrunt.hcl` files in them and "Stack" for folders with multiple Units (and we're proposing adding tooling to make working with Stacks better).

I think a solution that's a lot more simple in your use-case is to leverage `terragrunt-include-dir`, like @denis256 mentioned.
