### ISSUE TITLE
Terragrunt "global" hooks and extra_arguments

### ISSUE THREAD

**Issue by guilhermepozo** [gruntwork-io/terragrunt#2354]
Terragrunt have some functionality to create "global" blocks? (extra_arguments, hooks)

It means to create the same blocks on each stack,

**Comment by denis256** [comment]
Hi,
code that is repeating can be extracted to a common HCL file and later included  

More details in:
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#include  (`merge_strategy`)
