### ISSUE TITLE
get_parent_terragrunt_dir & multi-includes

### ISSUE THREAD

**Issue by JeanFred** [gruntwork-io/terragrunt#2358]
I find that `get_parent_terragrunt_dir` does not behave as I would expect when using multi-includes

My infrastructure repository looks like as follows − mostly following the terragrun-live-example layout, except that modules live in the same repository (not too dissimilar to https://github.com/gruntwork-io/terragrunt/issues/305#issuecomment-598673119):

```
.
├── live
│   └── terragrunt.hcl
│   └── _envcommon
│   │   └── app.hcl
│   └── account1
│   │   ├── app
│   │   │   └── terragrunt.hcl
│   │   └── account.hcl
│   └── account2
│       ├── app
│       │   └── terragrunt.hcl
│       └── account.hcl
└── modules
    └── app
        └── main.tf
```

The top-level `terragrunt.hcl` contains backend definition etc.

The lowest-level `terragrunt.hcl` file is a mere:
```
include "root" {
  path = find_in_parent_folders()
}

include "envcommon" {
  path = "${dirname(find_in_parent_folders())}/_envcommon/app.hcl"
}
```

`_envcommon/app.hcl` is:
```
terraform {
  source = "../../..//modules/app"
}
```

I was not too happy with the `"../../..//modules/app"` relative paths − it’s a bit brittle, as it vary if some environments are nested one level  deeper (and is overall not very readable).

I wanted to replace `"../../..//modules/app"` with a simpler construct using some built-in terragrunt methods. Ideally, something would send me to `/code/terragrunt-repository/` or at worse `/code/terragrunt-repository/live` − something where I can then append a `//modules` − but none appeared to do what I wanted:

* `get_terragrunt_dir` = `/code/terragrunt-repository/live/account1/app`
* `get_parent_terragrunt_dir` = `/code/terragrunt-repository/live/_envcommon`
* `get_parent_terragrunt_dir("root")` = `/code/terragrunt-repository/live/_envcommon`
* `get_original_terragrunt_dir` = `/code/terragrunt-repository/live/account1/app`
* `path_relative_from_include` = `../../_envcommon`
* `path_relative_to_include` = `../account1/app`

In particular I noticed that `get_parent_terragrunt_dir` is not doing at all what i was expecting : based on [the docs](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_parent_terragrunt_dir), I would have expected it to be  `/code/terragrunt-repository/live` − especially with specifying the include with `get_parent_terragrunt_dir("root")`

Am I doing something wrong here?

(Besides that:
* `get_repo_root` would work for me, except that the terragrunt pinned in that repo does not have it :)
* I can do some `find_in_parent_folders` but I need to dance around the paths to add the double-slash: the most straight-forward `find_in_parent_folders('modules')` needs a double-slash so I need `find_in_parent_folders('modules')/..//modules` ; or `find_in_parent_folders('live)/..//modules`
* → Ultimately for now I’m doing `source = "${dirname(path_relative_from_include())}/..//modules/`

**Comment by denis256** [comment]
Hi, 
yes, if code is not on git can be used `path_relative_from_include / find_in_parent_folders`
