### ISSUE TITLE
Terragrunt command line not working any mroe

### ISSUE THREAD

**Issue by PassionateDeveloper86** [gruntwork-io/terragrunt#2359]
Hi,

I start to use terragrunt to deploy my azure resource group and my azure kubernetes cluster.
It worked like 10 times, then I tried to play with K8S a bit and saw that my k8s cluster doesnt have access to my container registry (which I set up manuelly before). I played a bit with service accounts in my tf files and from now to then my terragrunt stopped working completly.
Now even when I just want to "terragrunt plan" on my resource group it will look for the k8S state and throw very not googleable messages:
![grafik](https://user-images.githubusercontent.com/20551244/201472880-ab2ead17-c0ab-44cf-9175-ad95a475b56c.png)

it feels like terragrunt "stucks" or has a bad cache or a bad state file. I cant to anything any more with terragrunt, every command gives this error.

**Comment by PassionateDeveloper86** [comment]
I deleted my state file, now it works again. Seems like a broken state file was the problem.

**Comment by denis256** [comment]
hi, 
since the error is in failing request to `localhost:80` I suspect K8S credentials weren't fetched - the state may contain a record that K8S access details were fetched and it is not fetched second time

**Comment by bethadele** [comment]
@PassionateDeveloper86 -- We're going to close this issue since it sounds like you got the state sorted out.
