### ISSUE TITLE
Issue with Init Command and -backend-config file location 

### ISSUE THREAD

**Issue by yordis** [gruntwork-io/terragrunt#2360]
Hey there,

I have the following `Makefile` and directory structure:

```makefile
terragrunt-init:
	terragrunt run-all init --backend-config=config.do.tfbackend
```

```
.
├── Makefile
├── config.do.tfbackend
├── digitalocean
│   └── my-business-name
│       ├── genesis
│       │   ├── backend.tf
│       │   ├── terragrunt.hcl
│       └── shared
│           └── nyc1
│               ├── backend.tf
│               ├── terragrunt.hcl
└── terragrunt.hcl
```

Using the file location is not working properly because resolving the path is not relative to the `Makefile` but where the `init` runs subproject is located.

## Expected Behavior

- `terragrunt run-all init --backend-config=config.do.tfbackend` will pass the file location relative to where the command was called.

**Comment by denis256** [comment]
Hi,
afaik current implementation is used by people when is helpful to keep separated states, in your case I think can be used `--backend-config=$(pwd)/config.do.tfbackend` approach if is required to have common state

**Comment by yordis** [comment]
I ended up using the following,

```
MAKEFILE_PWD_DIR=$(shell dirname $(MAKEFILE_LIST))

terraform-fmt:
	terraform fmt -recursive

terragrunt-init:
	# TODO: figure out how to fix this command.
	#  Related to: https://github.com/gruntwork-io/terragrunt/issues/2360
	terragrunt run-all init --backend-config=$(MAKEFILE_PWD_DIR)/config.do.tfbackend
```

I would like to have the ability to do it without an absolute path and just do `./config.do.tfbackend`

I feel that it is common to use `terragrunt` to share backends I would expect this to be the case.

**Comment by yordis** [comment]
@denis256 I am ok as it is for now 🤷🏻
