### ISSUE TITLE
Reading file from 'current_directory' or parent_dirs, whichever is found first ?

### ISSUE THREAD

**Issue by mech422** [gruntwork-io/terragrunt#2368]
I'm thinking I have to be doing something wrong... I just want to read the first occurance of "config.hcl" in the directory tree, INCLUDING the 'current dir'.  I'm basically just trying to do a 'find_in_parent_folders()' that INCLUDES the directory containing this terragrunt.hcl.  Given that find_in_parent_folders() knows how to walk the directory tree, it must know where the terragrunt.hcl lives?  After monkeying around the 'best' I've come up with is:
```
locals {
  # find the first 'config.hcl' in the directory hierarchy, including the current dir.
  # the abspath() SHOULD run relative to the directory containing this file
  # so it works BOTH when run from this directory via 'terragrun init|plan|apply, and when run from top level
  # via terragrunt run-all XXX, but that's not the case when using run-all, so we need get_terragrunt_dir()
  local_cfg_path  = abspath("${get_terragrunt_dir()}/config.hcl")
  parent_cfg_path = find_in_parent_folders("config.hcl", "/missing-parent-config")

  # Try looking in current dir first, if not found take the first one found walking up the
  # directory tree.  If not found at all use the default file name "/missing-parent-config",
  # chosen to make the error msgs a lil easier to understand.
  # (We WANT it to bomb if it can't find "config.hcl")
  cfg_path = fileexists(local.local_cfg_path) ? local.local_cfg_path : local.parent_cfg_path
  configs  = read_terragrunt_config(local.cfg_path)
  config   = local.configs.locals
}
```
(I have no idea why I seem to need the get_terragrunt_dir() as the abspath() is supposed to run relative to the 
directory containing the terragrunt.hcl but thats not really my question).  In general, it seems really cumbersome.

There has to be a better way... what am I missing ?

P.S. - You can also do this with a 'try' block ( see  https://github.com/gruntwork-io/terragrunt/issues/1210 ) 
but I think this looks a lil cleaner.

Thanks!

**Comment by yhakbar** [comment]
I've used `try` to resolve this in the past, but with a `merge` to have zero or more configurations merged for a final configuration.

```hcl
  # Load yml configurations in the local folder, or fallback to {}
  override_yml = try(yamldecode(file("${get_terragrunt_dir()}/config.yml")), {})

  # Load first config.yml file found in one of the parent folders of the unit, or fallback to {}
  parent_yml = try(yamldecode(file(find_in_parent_folders("config.yml"))), {})

  # Merge the two
  configs = merge(local.parent_yml, local.override_yml)
```

Given that there are solutions for the issue, I'm closing it out. Feel free to add a discussion or share in the Discord if you have other tricks you'd like to share!
