### ISSUE TITLE
terragrunt run-all plan for GCP modules with dependencies defined

### ISSUE THREAD

**Issue by vasu2809** [gruntwork-io/terragrunt#2370]
We have an architecture deployed using terraform and terragrunt with dependencies included to ensure all services run one after the other due to dependencies. Is there a way to use terragrunt run-all plan to get a plan file for all modules without actually deploying any? I understand this feature did not exist a while back, but would like to know if there is a workaround for this as asking customers to deploy everything directly after init doesnt seem like a good advice.

**Comment by denis256** [comment]
Hi,
was considered to use `run-all plan/apply` with plan files?
```
terragrunt run-all plan -out=plan.out
terragrunt run-all apply plan.out
```

**Comment by vasu2809** [comment]
Thanks for getting back, yes thats exactly the issue as there are module dependencies and output of one module is being leveraged in other modules which fails because in actual the dependencies dont exist
