### ISSUE TITLE
Error when using `expose=true` on included module

### ISSUE THREAD

**Issue by tadejsv** [gruntwork-io/terragrunt#2373]
I have the following file tree:

```
terragrunt.hcl
_envcommon/
    server.hcl
modules/
    server/
        main.tf
staging/
    env.hcl
    vpc/
        terragrunt.hcl
    server/
        terragrunt.hcl
```

And here are the files

```hcl
# staging/server/terragrunt.hcl
include "root" {
  path = find_in_parent_folders()
}

include "common" {
  path = "../../_envcommon/server.hcl"
}
```

```hcl
# _envcommon/server.hcl

locals {
  _env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  env_vars  = local._env_vars.locals
}

terraform {
  source = "../../modules//server"
}

dependency "vpc" {
  config_path = "../vpc"
}

inputs = {
  vpc_id            = dependency.vpc.outputs.vpc_id
  identifier        = "${local.env_vars.env_name}-server"
  name              = "${local.env_vars.env_name}"
}
```

```hcl
# staging/env.hcl
locals {
  env_name    = "staging"
}
```
and root `terragrunt.hcl` just contains common backend/provider config.

Now, with this configuration everything works well. But when I modify `staging/server/terragrunt.hcl` like so (I want to use some `locals` from common env)

```diff
include "root" {
  path = find_in_parent_folders()
}

include "common" {
  path = "../../_envcommon/server.hcl"
+  expose = true
}
```

I get this error

```
ERRO[0000] Error reading file at path /home/tadej/projects/architecture/vpc: open /home/tadej/projects/architecture/vpc: no such file or directory 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
What am I doing wrong?

I am using terragrunt version v0.40.2

**Comment by denis256** [comment]
Hi,
AFAIK, when is set `expose = true` HCL content is parsed and exposed as a variable - in this case, it fail to open `vpc` path since it is specified as a relative path.

Can be attempted to use `get_repo_root()` function to generate valid path from root of repo



https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_repo_root

**Comment by tadejsv** [comment]
Hm, not sure about this. I use `../vpc` because I want this to work for multiple environments - e.g. for `staging/vpc`, `development/vpc`, `prod/vpc`. I think with using `get_repo_root` there would be no way to make this work, if `expose=true` reads the module not from where it is included, but from its original location (`_envcommon`)

**Comment by tadejsv** [comment]
I think it is a bit counterintuitive that `expose = true` changes how parsing happens - it should just expose the state/variables that it already has

**Comment by wmunoz** [comment]
did you already try `get_terragrunt_dir()`:
`  config_path = "${get_terragrunt_dir()}/../vpc"`

**Comment by muzhaqi16** [comment]
Thank you, @wmunoz, that worked for me. I wasted almost two hours figuring out why it wasn't working.
