### ISSUE TITLE
Re-run dependency output when terragrunt run-all apply command

### ISSUE THREAD

**Issue by cem-altuner** [gruntwork-io/terragrunt#2381]
Hi,

I have an edge case about the "run-all apply" command.

I have three modules that are dependent on each other:

module1->module2 (depending on module 1 output)->module3 (depending on both module 1 and module 2 output)

but after module 2 "apply" is finished, I want to re-run Terragrunt refresh output on module 1 because my module 3 takes the output from module 1. I tried to refresh the outputs with the before-hook Terragrunt refresh; I can see the new outputs happen after the before-hook is run, but module 3 still uses the old output values from module1. I have tried something like that:

run-all apply:
module1 (apply) -> module2 (apply) -> (module3 before hook) refresh module 1 -> module3 (apply)

I am using the AWS S3 backend, and in the remote state of module1, I can see the new outputs because of the before hook refresh. But module3, still uses the old output of module1. It looks like in-memory caching is the cause of the problem.

I've tried all before-and-after hook combinations, but I couldn't fix that. Have I missed something?

**Comment by denis256** [comment]
hi,
can be attempted to use `--terragrunt-fetch-dependency-output-from-state` to refresh dependencies but this need to be tested

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-fetch-dependency-output-from-state

**Comment by cem-altuner** [comment]
Hi, I tried it, but it's not working properly. I'm still unable to retrieve the value from the S3 state.
