### ISSUE TITLE
Allow configuring object_ownership for s3 state backend

### ISSUE THREAD

**Issue by koshelevdk** [gruntwork-io/terragrunt#2382]
While configuring s3 backend in Terragrunt there is no way specify [object_ownership](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#object_ownership) parameter for remote_state s3 configuration.

In my particular case it's necessary to use [BucketOwnerEnforced](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#BucketOwnerEnforced) because of account policies.

I know that it's possible to create and configure bucket in advance, but it would be more convenient to use Terragrunt only without executing stand alone Terraform code.

Is it possible to implement this feature in Terragrunt?

**Comment by ab0159w** [comment]
I have the same requirement.
