### ISSUE TITLE
Bug with terragrunt run-all init --terragrunt-non-interactive does not work

### ISSUE THREAD

**Issue by vasu2809** [gruntwork-io/terragrunt#2389]
Hi,

We have a use case where we want to pass y by default to the prompt to create the backend bucket - we have tried using the command 

terragrunt run-all init --terragrunt-non-interactive

But the above command gives a 409 error during initializing saying bucket already exists after its created and init isnt successful

We also tried to non-interactive commands like 

echo "Y" | terragrunt run-all init

echo "y" | terragrunt run-all init

echo "YES" | terragrunt run-all init

echo "yes" | terragrunt run-all init

But none of the work, they end up giving errors, but although the bucket does get created in all the above cases, the initialization fails with errors in all cases

For apply, we have used the same command echo "Y" | terragrunt run-all apply which is working perfectly fine for us for the prompt do you want to run terragrunt in all modules? (y/n)

But the same command does not work for creating the bucket

What we noticed is we get 2 prompts for creating buckets, and we are not sure if that is causing issues when we pass y through non-interactive mode

The request for 2 prompts looks like a bug and maybe this is why non-interactive mode isn't working either where non-interactive provides y for first bucket prompt and creates it, and again provides y for the second prompt too and throws error saying bucket already exists

I am not sure if this is a bug

Terragrunt version AMD - 46
terraform version - 1.3.6

vasudevaner-macbookpro:modules vasudevaner$ terragrunt run-all init
INFO[0000] The stack at /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules will be processed in the following order for command init:
Group 1
- Module /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules
- Module /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules/gcs

Group 2
- Module /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules/pubsub

Group 3
- Module /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules/gcc

Group 4
- Module /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules/cloudrun

Group 5
- Module /Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules/bq
 
Remote state GCS bucket edw-test-tfhcltest-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) Remote state GCS bucket edw-test-tfhcltest-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)

**Comment by denis256** [comment]
Hi,
was attempted to run with `--auto-approve --terragrunt-non-interactive` ?

**Comment by vasu2809** [comment]
Hi,

No it does not work, returns the same 409 bucket exists error - I guess the issue is because of duplicate prompts for bucket creation coming up during run-all init

Here is the output after running it with the suggested option


**terragrunt run-all init --auto-approve --terragrunt-non-interactive**

_ERRO[0004] Create GCS bucket edw-test-tfhcltest-statetestnew returned an error: googleapi: Error 409: Your previous request to create the named bucket succeeded and you already own it., conflict. Sleeping for 10s and will try again.  prefix=[/Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules] 
Usage: terraform [global options] init [options]_

**Comment by zahornyak** [comment]
Hi, I'm using this command

`terragrunt run-all init -no-color -input=false --terragrunt-include-external-dependencies`

or you can use it also like that : `yes | terragrunt run-all init`

**Comment by zahornyak** [comment]
`ERRO[0004] Create GCS bucket edw-test-tfhcltest-statetestnew returned an error: googleapi: Error 409: Your previous request to create the named bucket succeeded and you already own it., conflict. Sleeping for 10s and will try again. prefix=[/Users/vasudevaner/Documents/Data/EDW_E2E/edw-e2e/Foundation/modules]
Usage: terraform [global options] init [options]`

looks like you created bucket using terragrunt and now you are trying to create it again

**Comment by brikis98** [comment]
Just hit the same issue when running `run-all plan`. Here's the log output:

```
time=2023-11-27T23:41:56Z level=info msg=The stack at /home/infra-live/account-3 will be processed in the following order for command plan:
Group 1
- Module /home/infra-live/account-3/_global/account-baseline
- Module /home/infra-live/account-3/_global/github-oidc-role
- Module /home/infra-live/account-3/_global/pipelines-policy-update-role-ro
- Module /home/infra-live/account-3/_global/pipelines-policy-update-role-write
- Module /home/infra-live/account-3/eu-west-1/_regional/service-quotas

Group 2
- Module /home/infra-live/account-3/_global/pipelines-read-only
- Module /home/infra-live/account-3/eu-west-1/gw-test-single-acct-factory-3/networking/vpc


time=2023-11-27T23:42:01Z level=error msg=Module /home/infra-live/account-3/_global/pipelines-policy-update-role-write has finished with an error: OperationAborted: A conflicting conditional operation is currently in progress against this resource. Please try again.
  status code: 409, request id: XXXXX, host id: YYYY prefix=[/home/infra-live/account-3/_global/pipelines-policy-update-role-write] 
time=2023-11-27T23:42:01Z level=error msg=Module /home/infra-live/account-3/_global/github-oidc-role has finished with an error: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
```

AFAIK, the S3 bucket did _not_ exist before running this command. So when `run-all plan` executed, several modules at the same time went to create it. In the past, this worked fine: Terragrunt would detect the concurrent operations and wait, so one operation would succeed, and then the others would use the existing bucket. 

But it looks like something has changed, and now it's failing to handle the concurrent operation, and erroring out.
