### ISSUE TITLE
Support terraform init --reconfigure

### ISSUE THREAD

**Issue by philsttr** [gruntwork-io/terragrunt#239]
We have a use case for a script (and occasionally by hand) that requires reconfiguring the terraform backend _without_ copying state.

With terraform 0.9.4+, this can be accomplished by passing the `--reconfigure` flag to `terraform init` (See [here](https://www.terraform.io/docs/commands/init.html#reconfigure)).

It would be great if terragrunt exposed some cli flag that resulted in passing the `--reconfigure` flag to `terraform init`.  This could be done generically (e.g. `--extra-init-argument xxxx`) or specifically (e.g. `--terragrunt-reconfigure-backend`)

I can currently hack around this by calling terragrunt like this:

```
echo no | terragrunt --terragrunt-non-interactive plan
```

But that is not very elegant.

For reference, this is the prompt from terraform that passing `--reconfigure` will avoid.

```
Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now reconfigure for this backend. If you didn't
intend to reconfigure your backend please undo any changes to the "backend"
section in your Terraform configuration.


Do you want to copy the state from "s3"?
  Would you like to copy the state from your prior backend "s3" to the
  newly configured "s3" backend? If you're reconfiguring the same backend,
  answering "yes" or "no" shouldn't make a difference. Please answer exactly
  "yes" or "no".

  Enter a value: no
```

**Comment by brikis98** [comment]
Ah, good call. Supporting some sort of `--terragrunt-init-arg XXX`, where you can specify whatever you want for `XXX`, would make sense. PRs welcome!

**Comment by philsttr** [comment]
Yeah, looks like [0.10](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md) is adding an `-upgrade` flag as well.  A generic mechanism is probably best.

**Comment by philsttr** [comment]
0.10.0 also added a several flags to the init command [to control plugin installation](https://www.terraform.io/docs/commands/init.html#plugin-installation).  Would be good if there were some way to use these.

**Comment by dscowan** [comment]
Is there any plan to add this anytime soon.  The workaround of "echo no" listed above does not seem to work for me.

**Comment by brikis98** [comment]
As of #261, you should be able to run `terragrunt init` and pass arguments to it, including `--reconfigure`. Is that not working for you?
