### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by ina-stoyanova** [gruntwork-io/terragrunt#2394]
Integration tests seem to be failing for terragrunt master branch. This issue is to hold the work to investigate why they're failing and add fixes for that.

**Comment by denis256** [comment]
Integration tests failed because of AWS account reached limit on number of S3 buckets, cleanup of test buckets wasn't working because of `cloud-nuke` execution errors, after  fixing [execution in](https://github.com/gruntwork-io/cloud-nuke/pull/384), integration tests started to pass
