### ISSUE TITLE
Can CheckDependentModules be made optional to prevent Terragrunt iterating over the entire codebase on destroy?

### ISSUE THREAD

**Issue by xynova** [gruntwork-io/terragrunt#2396]
We are currently having execution hanging issues when running destroy on a stack. Digging in through the logs and code I noticed there is a sanity check when to alert when destroying a stack that is referenced by other stacks. 

Can it be made optional? Our current way around it is to do a Ctrl-C to execute the sanity check loop and jump straight to the destroy part but it is obviously a very obscure workaround.

```
	if command == "destroy" {
		terragruntOptions.CheckDependentModules = true
	}
```

https://github.com/gruntwork-io/terragrunt/blob/c88c3bd3f481391a301aba34c2793714471ce778/cli/cli_app.go#L368

**Comment by yhakbar** [comment]
Hey @xynova ,

There's already a flag for this:
https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-no-destroy-dependencies-check
