### ISSUE TITLE
Migrate terraform to terragrunt for high number of modules

### ISSUE THREAD

**Issue by aladdin55** [gruntwork-io/terragrunt#2397]
I have microservice non-prod env. where each team has its own env. which means a lot of envs, in terms of terrafrom right now I have two github repos:

- The first one has root tf modules.
- The Second one has reusable tf modules.

The first one contains 10 root modules each one of them calls just a single module that resides in the second repo, this module in the second repo calls 13 modules, so one of the modules in the second repo represents a proxy repo.

to recap, the first repo structure:

- tf-env1.tf
- tf-env2.tf
- tf-env3.tf
- ....
- tf-env10.tf

The second one has a structure:

- api-gateway.tf
- vpc.tf
- rds.tf
- ec2.tf
- s3.tf
- lambda.tf
- lb.tf
- SPECIAL_Module.tf

the call chain goes as:

> in repo1 : tf-envX.tf
> |
> in repo2 : SPECIAL_Module.tf
> |
> in repo2 : api-gateway.tf,vpc.tf,rds.tf,s3.tf .... etc

As part of migrating to terragrunt in order to give the developers an ability to control their env. via managing their env. variables and free up the SRE team to just writing new terraform modules.

I'm thinking of getting rid of SPECIAL_Module.tf, since it has a lot of local controls on how terraform works, but the issue is if I remove SPECIAL_Module.tf terragrunt doesn't support more than one source on each hcl file.

Another option is to create an hcl for each module from the second repo, but this means I would manage # of modules * # of envs files., so it came to my mind to group the modules in the second repo into 3 or 4 groups.

One solution I thought about is to move SPECIAL_Module.tf to the first module and include it in each env., but this means a huge single terraform file would reside inside terragrunt repo. which I'm not sure if it's an abuse for terragrunt.

So is there a way to migrate from terraform to terragrunt with a high # of modules and a high # of envs?

**Comment by denis256** [comment]
hi,
ideas on how to adopt Terragrunt can be collected from examples:

- https://github.com/gruntwork-io/terragrunt-infrastructure-live-example
- https://terragrunt.gruntwork.io/docs/features/keep-your-terraform-code-dry/

Code from `SPECIAL` can be referenced in `dependencies`

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependencies

**Comment by aladdin55** [comment]
The first link is very simple example use case, in the second one the # of modules are 3 with 3 env. which is a different case.
