### ISSUE TITLE
terragrunt graph adds header, invalidates dot format

### ISSUE THREAD

**Issue by lsc** [gruntwork-io/terragrunt#24]
Just a cosmetics thing, if you run `terragrunt graph | dot -Tpng > mygraph.png`
you will get an error like so `Error: <stdin>: syntax error in line 1 near '['` because terragrunt adds the two lines `[terragrunt] 2016/08/30 11:41:34 Remote state is already configured for backend s3
[terragrunt] 2016/08/30 11:41:34 Running command: terraform graph`

It's easy to just run `terraform graph` instead, but I wanted to give a heads up

**Comment by brikis98** [comment]
Ah, good point. I suppose there are two options: either a) add a `--silent` flag that suppresses terragrunt logging or b) detect if we're being piped into another process, at least for certain commands like `graph`, and automatically suppress logging in those cases.

**Comment by lsc** [comment]
I was thinking of just disable logging if the command was graph, but maybe figuring out if we are piping the command is the nicer way to solve it.

A flag like --silent would be confusing I think, as it isn't clear if we silence terragrunt only or if it is a flag passed to terraform.

**Comment by dln** [comment]
One solution would be to log to stderr instead of stdout. This would ensure "transparent" wrapping around terraform.

As a personal preference, I would also opt for being quiet by default.

**Comment by brikis98** [comment]
This should be fixed by #94.
