### ISSUE TITLE
Publish a gruntwork hosted Docker image of Terragrunt

### ISSUE THREAD

**Issue by bschaatsbergen** [gruntwork-io/terragrunt#2407]
It would be very nice if we can have a Docker image hosted by gruntwork. This also makes it easier for users to pipe Terragrunt in their existing pipelines, instead of having to maintain and hand-roll your own Dockerfiles/images.

I would be happy to open a PR if there's a couple of :+1: on this issue.

**Comment by denis256** [comment]
Hello,
it may be challenging since different users may use different combinations of Terragrunt and Terraform

**Comment by bschaatsbergen** [comment]
I was thinking about the same but I suppose there should be a pretty solution to this @denis256 .

**Comment by kevcube** [comment]
In the meantime I use the alpine/terragrunt image.

**Comment by denis256** [comment]
In my projects, I use a single docker image with `tfenv` and `tgenv`, and depending on project configurations is selected right version.

References:

https://github.com/tfutils/tfenv

https://github.com/cunymatthieu/tgenv
