### ISSUE TITLE
Can terragrunt destroy be executed without the interactive prompt saying no?

### ISSUE THREAD

**Issue by bshibilov-sh** [gruntwork-io/terragrunt#2409]
As part of CI/CD automation, I need to set destroy option to prompt no to exit with 0. Is this possible?

**Comment by denis256** [comment]
Hi,
AFAIK can be disabled destroy by setting `prevent_destroy = true` on `terraform` block which will prevent destroy but the exit code each time will be different from 0.

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#prevent_destroy
