### ISSUE TITLE
Last build 0.42.8 missing files to download

### ISSUE THREAD

**Issue by pipoe2h** [gruntwork-io/terragrunt#2413]
The last build is missing the SHA256SUMS and the rest of the tar files. Noticed this because the Terraform feature for VS Code Devcontainer has terragrunt enabled by default to the latest. Because the latest exists as a release in the repo, it is picking it up but the files are missing.

**Comment by mrsaiz** [comment]
We are also facing issues due to this, we use the next binary that is missing:

https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64

**Comment by denis256** [comment]
Hi,
looking into, seems to be an issue with the release artifacts publication

**Comment by pipoe2h** [comment]
@mrsaiz if you are using Devcontainer too, what I've done in the interim is to set the feature to the previous release. Here is an extract for the devcontainer.json:

```
	"features": {
		"ghcr.io/devcontainers/features/terraform:1": {
			"version": "1.3.7",
			"tflint": "0.44.1",
			"terragrunt": "0.42.7"
		}
	}
```

**Comment by mrsaiz** [comment]
> @mrsaiz if you are using Devcontainer too, what I've done in the interim is to set the feature to the previous release. Here is an extract for the devcontainer.json:
> 
> ```
> 	"features": {
> 		"ghcr.io/devcontainers/features/terraform:1": {
> 			"version": "1.3.7",
> 			"tflint": "0.44.1",
> 			"terragrunt": "0.42.7"
> 		}
> 	}
> ```

Thanks, we are using a similar workaround. We were downloading the binary with the next command:
`curl -sSLO "https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64"`

As it that link is not working, we are downloading the binary from the previous version using the next command:
`curl -sSLO "https://github.com/gruntwork-io/terragrunt/releases/download/v0.42.7/terragrunt_linux_amd64"`

**Comment by denis256** [comment]
Hello,
CICD integration started to work now, release assets are now available
