### ISSUE TITLE
terragrunt validate ignores variables validation rules

### ISSUE THREAD

**Issue by paolo-rm** [gruntwork-io/terragrunt#2423]
###  The setup:
The terraform code in tf-modules calls a remote module in a private registry.
The terragrunt.hcl source is the local tf-modules code.

The module in the private registry has a variables validation rules.
All inputs are provided in the inputs block in the terragrunt .hcl

.
├── tf-modules
│   ├── README.md
│   ├── main.tf
│   ├── outputs.tf
│   ├── variables.tf
│   └── versions.tf
└── tg-config
    ├── all
    │   └── terragrunt.hcl
    └── root.hcl

### The issue:
Running terragrunt validate whilst providing a value in terragrunt.hcl that breaks the validation rule produce a success

main.tf

_module "test_function" {
  source                = "gitrepo/module-gcp-cloud-function"
  version               = "1.0.0"
  ingress_settings = var.ingress_settings
}_

_inputs = {
  ingress_settings      = "ALLOW_ALL"
}_

**/tg-config/all(main) $ terragrunt validate
Success! The configuration is valid.**

Running terragrunt validate whilst providing the same value in main.tf in the tf-module that breaks the validation rule produce a validation error

_module "test_function" {
  source                = "gitrepo/module-gcp-cloud-function"
  version               = "1.0.0"
  ingress_settings = "ALLOW_ALL"
}_

**│ Error: Invalid value for variable
│
│   on main.tf line 33, in module "test_function":
│   33:   ingress_settings = "ALLOW_ALL"
│     ├────────────────
│     │ var.ingress_settings is "ALLOW_ALL"
│
│ The variable ingress_settings must be one of "ALLOW_INTERNAL_ONLY" or
│ "ALLOW_INTERNAL_AND_GCLB".
│
│ This was checked by the validation rule at
│ .terraform/modules/test_function/variables.tf:57,3-13.**

I was expecting that either way terragrunt validate would produce an error.

**Comment by denis256** [comment]
Hello,
what is the content of `all/terragrunt.hcl` ? it is setting terraform source to be `tf-modules` ?

**Comment by paolo-rm** [comment]
hi @denis256 yes the source in `all/terragrunt.hcl`  is specified as 
`
terraform {
  source = "../..//tf-modules"
}
`

**Comment by paolo-rm** [comment]
I have created a repo to replicate the issue https://github.com/paolo-rm/terragrunt-validation-error

Also forgot to mention that this affect only `terragrunt validate` , terragrunt does report the validation error by running `terragrunt plan`. 

As we run plans only in CI/CD pipelines we would like developers to be able to validate their code locally, we use tflint and validate locally but at the moment due to this bug errors are not picked up until the code has been pushed

**Comment by denis256** [comment]
Hi,
I think this is an issue from `terraform`, adoption of code only for terraform and  invocation of `validate` shows no issues but fail on plan:

```
$ terraform validate
Success! The configuration is valid.

$ terraform plan
╷
│ Error: Invalid value for variable
│ 
│   on main.tf line 9, in module "validation-testing":
│    9:   validation-testing = var.validation-testing # change this to string that doesn't contain "hello" to make terragrunt validate report validation error
│     ├────────────────
│     │ var.validation-testing is "goodbye"
│ 
│ doesn't contain hello
│ 
│ This was checked by the validation rule at ../pretend-remote-module/main.tf:4,3-13.

```

![image](https://user-images.githubusercontent.com/10694338/213763132-c2681e3b-5fbb-4bdd-8d93-3951efa3f546.png)

**Comment by paolo-rm** [comment]
@denis256 It seems that if you pass the variable using default, validate will give a success, I assume like you did above. But if you pass the variable in the module like this then you get the validation error

`module "validation-testing" {
  source = "../pretend-remote-module"
  validation-testing = "goodbye"
}`

`
cloud-shell root ~/home/terragrunt-validation-error/tf-modules(master *+%) $ terraform validate
╷
│ Error: Invalid value for variable
│
│   on main.tf line 8, in module "validation-testing":
│    8:   validation-testing = "goodbye" //var.validation-testing # change this to string that doesn't contain hello to make terragrunt validate report validation error
│     ├────────────────
│     │ var.validation-testing is "goodbye"
│
│ doesn't contain hello
│
│ This was checked by the validation rule at ../pretend-remote-module/main.tf:4,3-13.
`
Is that why terragrunt fails? Because when you pass an attribute via terragrunt terraform treats it as a default value?

**Comment by paolo-rm** [comment]
@denis256 looks like I should have read the `terraform validate` manual. It states
```
To verify configuration in the context of a particular run (a particular target workspace, input variable values, etc), use the terraform plan command instead, which includes an implied validation check.
```
So i guess it's not meant to be used the way we want to anyway.
