### ISSUE TITLE
`run_cmd` in `extra_arguments` block called on any command

### ISSUE THREAD

**Issue by stanb-orca** [gruntwork-io/terragrunt#2426]
I am trying to pass `-var-file` depending on selected workspace.
```
  extra_arguments "var-file" {
    commands  = get_terraform_commands_that_need_vars()
    arguments = ["-var-file", run_cmd("./get_vars_file.sh")]
  }
```
And I realized that `run_cmd` called on every command, not only returned by `get_terraform_commands_that_need_vars()`
For example `terragrunt init` or `terragrunt workspace list` will trigger `run_cmd("./get_vars_file.sh")`.
In my case I tryed to call `terragrunt workspace show` in `get_vars_file.sh` and entered infinite recursion.
Is it a bug? Or what am I doing wrong?

My `./get_vars_file.sh`:
```
#!/usr/bin/env bash
#echo "vars.$(terragrunt workspace show).tfvars"
echo "vars.$(cat $(find . -name "environment")).tfvars"
```

**Comment by denis256** [comment]
Hi,
`run_cmd` is evaluated each time, during HCL evaluation, can be implemented some kind of optimization to evaluate `arguments` if the current command matches one of `commands` but this will complicate even more HCL evaluation.

**Comment by stanb-orca** [comment]
> Hi, `run_cmd` is evaluated each time, during HCL evaluation, can be implemented some kind of optimization to evaluate `arguments` if the current command matches one of `commands` but this will complicate even more HCL evaluation.

Any workarround for it?
Maybe I can use `before_hook` and somhow get it's output in the `extra_arguments` block? Something that will be evaluated during runtime of specific command and not every time?

**Comment by denis256** [comment]
Hello,
yes, can be used `before_hook` to render variables into a file and load rendered file through `extra_arguments`

```
terraform {
  before_hook "before_hook" {
    commands     = get_terraform_commands_that_need_vars()
    execute      = ["./get_vars_file.sh"]  # render file tmp_vars.tfvars
  }

  extra_arguments "var-file" {
    commands  = get_terraform_commands_that_need_vars()
    # use pre-rendered file tmp_vars.tfvars
    arguments = ["-var-file", "/tmp/tmp_vars.tfvars"]
  }
}
```

Simplified example in:
https://github.com/denis256/terragrunt-tests/tree/master/issue-2426/app
