### ISSUE TITLE
GCP / Azure support

### ISSUE THREAD

**Issue by james-powis** [gruntwork-io/terragrunt#243]
Is any one using Terragrunt to handle Azure / GCP / etc. resources?

Documentation is strongly AWS biased and not really clear if there is something preventing the use of another cloud provider.

**Comment by brikis98** [comment]
Yes, I believe there are users using Terragrunt with clouds other than AWS. Do you have specific questions or issues?

**Comment by james-powis** [comment]
It was more a difference of opinion between a peer of mine, thanks that helps.

**Comment by robsonpeixoto** [comment]
@brikis98, but does Terragrunt support Azure Blog Store to keep the state, or the S3 is required to work with terragrunt?

**Comment by josh-padnick** [comment]
@robsonpeixoto, Per the [docs](https://github.com/gruntwork-io/terragrunt#motivation-1), Terragrunt is just wrapping Terraform's [backends](https://www.terraform.io/docs/backends/). It looks like there's an [azurerm backend](https://www.terraform.io/docs/backends/types/azurerm.html) so the answer to your question is yes, Terragrunt will support Azure Storage for remote state.

**Comment by acobaugh** [comment]
There are no remote state initializers for azurerm, only for s3. These would need to be written and added to terragrunt before azure support could be considered complete.

**Comment by brikis98** [comment]
Well, Azure works. It just doesn't have the "extra" features we have for AWS, such as automatically creating an S3 bucket or DynamoDB table. If those would be useful to have for Azure too, a PR to add them would be very welcome.

**Comment by Xtigyro** [comment]
Hey @brikis98! Firstly, I want to thank you for your book on Terraform and for Terragrunt. Your work has been the cornerstone of my knowledge about Terraform.

I just would like to ask whether there are any examples re the usage of Terragrunt on MS Azure/Google Cloud?
