### ISSUE TITLE
What is the DRYest way to have multiple providers?

### ISSUE THREAD

**Issue by vitorfhc** [gruntwork-io/terragrunt#2431]
When I create the root `terragrunt.hcl` I can generate providers' configuration using the `generate` block. What if I need two providers, but not everyone will need them?

Example:

```bash
.
├── bar
│   └── terragrunt.hcl    # needs providers A and B
├── foo
│   └── terragrunt.hcl    # needs only provider A
└── terragrunt.hcl         # generates providers A and B
```

I've tried it using two roots `terragrunt.hcl` files.

```bash
.
├── bar
│   └── terragrunt.hcl
├── foo
│   └── terragrunt.hcl
├── terragrunt.hcl
└── terragrunt_ab.hcl
```

The `terragrunt_ab.hcl` is a copy of `terragrunt.hcl` plus the extra providers I need. It's DRYer than declaring it in every directory, but it's still repeating code.

Multiple `include` blocks would be amazing, but it's impossible. What's the recommended?

**Comment by denis256** [comment]
Hi,
was attempted to use `include` blocks with name?

```
include "aws" {
  path   = find_in_parent_folders("aws.hcl")
}

include "gcp" {
  path   = find_in_parent_folders("gcp.hcl")
}
```

**Comment by vitorfhc** [comment]
Sorry, for some reason, I did something dumb and couldn't include it twice. Maybe the block's name was duplicated.
