### ISSUE TITLE
Feature request: Add marker with module name when running a `run-all` task

### ISSUE THREAD

**Issue by syphernl** [gruntwork-io/terragrunt#2434]
Currently, when running a `run-all` command (e.g. `terragrunt run-all plan`) it is not very clear as to what module Terragrunt is operating in. 
It would be nice if it could add a (preferably colored) sentence such as:

```bash
* Terragrunt: Running task in module foo/bar
.....
No changes. Your infrastructure matches the configuration.
```

**Comment by bryceml** [comment]
Another option, would be to add colored prefixes to each line, I think packer does that.

**Comment by lorengordon** [comment]
See also: https://github.com/gruntwork-io/terragrunt/issues/1194

**Comment by lplazas** [comment]
A fix for this has been implemented by https://github.com/gruntwork-io/terragrunt/releases/tag/v0.45.1 and can be closed.
