### ISSUE TITLE
0.43.1 doesn't see CMK as valid SSE Encryption key

### ISSUE THREAD

**Issue by StorageMatt** [gruntwork-io/terragrunt#2435]
Upgrading Terragrunt from 0.43.0 to 0.43.1 (and leaving everything else on the same versions) gives us the following output on a state bucket that has sse encryption set with a CMK:
```
WARN[0006] The remote state S3 bucket **** needs to be updated:  prefix=[/Users/****/terragrunt/eu-west-1/dev]
WARN[0006]   - Bucket Server-Side Encryption             prefix=[/Users/****/terragrunt/eu-west-1/dev]
Remote state S3 bucket **** is out of date. Would you like Terragrunt to update it? (y/n)
```
When I answer yes to this it changes the KMS key used to the `alias/aws/s3` key.

0.43.0 does not display this same issue.

To replicate, have a backend generation I guess similar to:
```
remote_state {
  backend = "s3"
  config = {
    role_arn            = "arn:aws:iam::${local.account_id}:role/${local.aws_role}"
    bucket              = "${local.environment}-tfstate"
    encrypt             = true
    dynamodb_table      = "central-tflock"
    dynamodb_table_tags = local.required_tags
    key                 = "${local.aws_region}/${local.product}/${local.state_file_name}"
    kms_key_id          = "alias/central-${local.environment}-tfstate"
    region              = "eu-west-1"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

...where that kms key referenced is a CMK. Switch between 0.43.0 and 0.43.1 (note to self: remembering to clear cache in between)

**Comment by asnell** [comment]
We are seeing the same issue with buckets having sse_algorigthm = "aws:kms" with no key specified. When answering yes, Terragrunt sets the key explicitly to `alias/aws/s3`, but on subsequent runs we're still prompted to update bucket SSE settings.

**Comment by StorageMatt** [comment]
@denis256 Is it worth updating the ticket title to better reflect that wider issue to try and catch potential duplicates?
Just a thought.

**Comment by denis256** [comment]
Hello,
I wanted to confirm used configuration for remote_state:

```
remote_state {
  backend = "s3"
  config = {
...
    bucket_sse_algorithm = "aws:kms"
    bucket_sse_kms_key_id = "arn:aws:kms:us-east-1:xyz:key/abc"
...
  }
}
```


https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform

**Comment by asnell** [comment]
Hi, we are using

```
remote_state {
  backend = "s3"
  config = {
    encryption = true
    ...
  }
  ...
}
```

This results in a perpetual cycle of Terragrunt 0.43.1 asking to upgrade the bucket.

If I add `bucket_sse_algorithm = "aws:kms"` to the configuration above, that stops Terragrunt from asking to upgrade at all. So perhaps this is a slightly different (but related?) failure mode to the OP.
