### ISSUE TITLE
What is the best way to write terragrunt hcl for terraform that is composed of multiple modules?

### ISSUE THREAD

**Issue by danielnazareth89** [gruntwork-io/terragrunt#2436]
Apologies if this has been answered before, I am a relatively new user and searched through a bunch of stuff before asking here. I have some terraform where multiple modules are invoked together under one config key in S3/Dynamodb. What is the correct way to migrate this setup this to equivalent terragrunt?

In particular, I have a module for an EKS cluster and then another module for nodegroup creation which is invoked multiple times for different nodegroups. With vanilla terraform I can initialize all these modules together in one directory with one config key (say `eks.tfstate`). Is this possible in terragrunt too? If not, do I need to break `eks/some_tf_files_that_invoke_multiple_modules.tf` into, say, `eks/master/terragrunt.hcl`, `eks/nodegroup1/terragrunt.hcl`, `eks/nodegroup2/terragrunt.hcl` and so on? Would love some insight into the best practice here.

Thank you!

**Comment by denis256** [comment]
Hi,
from the description, looks like can be used `dependency` block https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency

More examples can be found in Terragrunt documentation and examples repo:
https://terragrunt.gruntwork.io/docs/features/keep-your-terraform-code-dry/
https://github.com/gruntwork-io/terragrunt-infrastructure-live-example
