### ISSUE TITLE
-all commands with force

### ISSUE THREAD

**Issue by james-powis** [gruntwork-io/terragrunt#244]
Greetings,

I am working on a pretty complex project and building a CI/CD process using remote state and locking in ephemeral runner containers. As such there is not a human to type 'y' to plan-all and apply-all commands... There does not appear to be a -force flag like there is with destroy. 

I have found a work around which is to pipe 'y' into the all command via `echo 'y' | terragrunt apply-all` but this just feels dirty to me in many ways... any advice would be appreciated.

**Comment by brikis98** [comment]
Does the `--terragrunt-non-interactive` flag do what you want?

**Comment by james-powis** [comment]
It does in fact!

Any advice for the absence of a get-all command?

**Comment by brikis98** [comment]
`terragrunt plan` (and `plan-all`) should call `get` automatically if it has not been called before for a module.

**Comment by james-powis** [comment]
Yep it does, thanks for the assist I have everything working beautifully.

**Comment by brikis98** [comment]
Nice! 👍
