### ISSUE TITLE
Terragrunt fails when executing terraform with .terragrunt-cache with long path

### ISSUE THREAD

**Issue by propyless** [gruntwork-io/terragrunt#2443]
Hello,
Sorry in advance for the weird subject name, wasn't sure how to describe.

I'm hitting an issue when running any terragrunt directory which has a very long path to the terragrunt-cache folder.
```
 terraform plan -var-file="/home/tlarsson/repos/github/organisation/iac-terragrunt-azure/management/networking/westeurope/fw_rcg/100-default-spoke-policy/terragrunt-debug.tfvars.json" "/home/tlarsson/repos/github/organisation/iac-terragrunt-azure/management/networking/westeurope/fw_rcg/100-default-spoke-policy/.terragrunt-cache/NaU1KA44oOWqEkYhFDp6fQEnKiM/iL1GTsjFyolKNjWIqHwxSXwLSEk"
```

It gives me the following error:
```
        * fork/exec /home/tlarsson/.asdf/shims/terraform: argument list too long
 
ERRO[0023] 1 error occurred:
        * fork/exec /home/tlarsson/.asdf/shims/terraform: argument list too long
 
ERRO[0023] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

I got it to run using terraform directly by adding the chdir argument, but running it as the terragrunt debug output suggested, gave the same error as above.
```
terraform  -chdir="/home/tlarsson/repos/github/organisation/iac-terragrunt-azure/management/networking/westeurope/fw_rcg/100-default-spoke-policy/.terragrunt-cache/NaU1KA44oOWqEkYhFDp6fQEnKiM/iL1GTsjFyolKNjWIqHwxSXwLSEk" init -var-file="/home/tlarsson/repos/github/organisation/iac-terragrunt-azure/management/networking/westeurope/fw_rcg/100-default-spoke-policy/terragrunt-debug.tfvars.json"
```

I don't know at which length of the last arg it starts producing this error. But I did notice that if i cut down on the `100-default-spoke-policy` length, it was able to init, plan, apply as expected.

TF/TG version combos tested: [1.3.4, 0.39.2], [1.3.7, 0.42.1]

**Comment by denis256** [comment]
Hi,
in this particular case, can be set `--terragrunt-download-dir / TERRAGRUNT_DOWNLOAD` to be in `/tmp/...`

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-download-dir

**Comment by propyless** [comment]
Ahh I didn't think about that arg. Thanks a million! I'll use that as a workaround for now.

I also suspected some kiind of OS Limit, but the number of chars was like 384 in that line. But if it was the OS limit, it shouldn't be logical to have worked by adding more characters `-chrdir=`?

**Comment by propyless** [comment]
I'm hitting this issue again and it does not seem to be related path length... It feels like terraform is rejecting the command invocation from TG since its not using chdir. But for some reason it works sometimes.

**Comment by propyless** [comment]
Can close this with reference too https://github.com/gruntwork-io/terragrunt/issues/2132
