### ISSUE TITLE
download root folder of modules with // but initialize terraform in source dir

### ISSUE THREAD

**Issue by ebarault** [gruntwork-io/terragrunt#245]
**reference:** 
#113
#121

hi @brikis98, 

In #121, following discussion in #113, you introduced the possibility to download the root of a module repo with the already familiar `//` syntax, which is great.

Although, consider:
- i'm following your best practice from https://github.com/gruntwork-io/terragrunt/issues/169#issuecomment-299145174 
- and say i have the following source defined in terragrunt config inside one of the child folder of `live` folder:
```js
terragrunt {
  terraform {
    source = "${get_tfvars_dir()}/../../../modules//vpc"
  }
}
```

Terragrunt will then download the content of the `modules` folder inside the tmp folder, good, now terraform code inside `/tmp/.../modules/vpc` can have access to other modules inside `/tmp/.../modules/`.

Now, the next thing done by Terragrunt is to `initialize` inside the `/..../modules` folder, which is inconsistent since i have no `.tf` files in `/..../modules/` ! Terraform complains that it's initializing in an empty directory.

```
[terragrunt] 2017/06/28 16:58:00 Reading Terragrunt config file at /Users/Eric/myProject/live/dev/vpc/terraform.tfvars
[terragrunt] 2017/06/28 16:58:00 Downloading Terraform configurations from file:///Users/Eric/myProject/modules into /var/folders/k6/c0n14gn13bq3v1s79f9mg4mc0000gn/T/terragrunt/dk3wBdNKzX1gXLXNlopHh64x1HA/FNGy7wlYkx-8W_DhLAdsXM7fieg
[terragrunt] 2017/06/28 16:58:00 Running command: terraform init -backend=false -get=false file:///Users/Eric/myProject/modules /var/folders/k6/c0n14gn13bq3v1s79f9mg4mc0000gn/T/terragrunt/dk3wBdNKzX1gXLXNlopHh64x1HA/FNGy7wlYkx-8W_DhLAdsXM7fieg
Initializing configuration from: "file:///Users/Eric/myProject/modules"...
Terraform initialized in an empty directory!
```

What I want is to `initialize` inside `/..../modules/vpc/` where I have the `.tf` files for my vpc module.

Do you see my point?

**Comment by brikis98** [comment]
Terragrunt uses `terraform init` to download the code. As you can see, it sets `-backend=false` and `-get=false`:

```
[terragrunt] 2017/06/28 16:58:00 Running command: terraform init -backend=false -get=false file:///Users/Eric/myProject/modules /var/folders/k6/c0n14gn13bq3v1s79f9mg4mc0000gn/T/terragrunt/dk3wBdNKzX1gXLXNlopHh64x1HA/FNGy7wlYkx-8W_DhLAdsXM7fieg
```

It will call `terraform init` in your `vpc` folder, with `backend` and `get` enabled too. Is that not what you're seeing?

**Comment by ebarault** [comment]
ok I see. Then should i just ignore this warning as a collateral effect of using live + modules project structure ?
```
Initializing configuration from: "file:///Users/Eric/myProject/modules"...
Terraform initialized in an empty directory!
```

**Comment by brikis98** [comment]
Yes, just ignore that.

**Comment by ebarault** [comment]
ok, thanks. indeed it works fine
