### ISSUE TITLE
Built-in tflint hook doesn't find .tflint.hcl if it's in the current directory

### ISSUE THREAD

**Issue by brantb** [gruntwork-io/terragrunt#2450]
Minimal example:

```bash
mkdir -p demo
cd demo
touch main.tf
cat > .tflint.hcl <<-END
  config { format = "compact" }
END
cat > terragrunt.hcl <<-END
  terraform {
    before_hook "lint" {
      commands = ["validate"]
      execute  = ["tflint"]
    }
  }
END
terragrunt validate
```

This script fails on the last line with the error "Could not find .tflint.hcl config file in the parent folders: Traversed all the day to the root". Running `tflint` directly works as expected (it reads the config file in the current directory and prints a warning in compact format).

terragrunt version v0.43.2

**Comment by denis256** [comment]
Fix implemented in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.43.3
