### ISSUE TITLE
Interpolation in source attribute

### ISSUE THREAD

**Issue by kevinashaw** [gruntwork-io/terragrunt#2459]
We are setting up our AWS infrastructure to be built using terragrunt across several accounts.
For each account, we have a folder with a top-level `terragrunt.hcl` file with local variables that define all necessary parameters for the account build.  This includes the git-hashes of several containers that need to be installed for the account. 
We also have sub-directories for each of the terraform stacks that need to be run.  The Local variables get passed to the terraform stacks and all is good.  However, in several of the stacks, we need to also control the `source` attribute to have the same git-hash as the container that is being matched to it.  We want to interpolate the git-hash into the `source` string.  For example:
```
terraform {
  source = "git::git@bitbucket.com:my-company/my-repo.git//my_terraform?ref=${local.required_commit}"
}
include "root" {
  path = find_in_parent_folders()
}
```
But I get this error message:
```
ERRO[0000] /Users/my-user/my-project/my-stack/terragrunt.hcl:3,90-102: Attempt to get attribute from null value; This value is null, so it does not have any attributes., and 1 other diagnostic(s) 
```
I infer that interpolation is not allowed in the `source` attribute.  To keep this DRY, it would make sense not to repeat the git-hash in both the project level attribute set and being hard-coded into the source string for the terraform stack.  What am I missing here?

**Comment by denis256** [comment]
Hi,
can be attempted to set `expose = true` on include `block`:

```
terraform {
  source = "git::git@bitbucket.com:my-company/my-repo.git//my_terraform?ref=${include.root.locals.required_commit}"
}

include "root" {
  path = find_in_parent_folders()
  expose = true
}
```

**Comment by kevinashaw** [comment]
Perfect.  Thank you!
