### ISSUE TITLE
`--terragrunt-source-map` does not work with `?ref=`

### ISSUE THREAD

**Issue by norman-zon** [gruntwork-io/terragrunt#2460]
In my workflow one of the main use cases for `--terragrunt-source-map` would be to point all my module-sources to a feature branch I am working on like this:

```
terragrunt plan --terragrunt-source-map git::ssh://git@github.com/myORG/terraform-modules.git=git::ssh://git@github.com/myORG/terraform-modules.git?ref=FEATURE
```

Unfortunately due to the way the source-map is parsed having a `=` in the argument breaks it:

```
ERRO[0000] Invalid key-value pair. Expected format KEY=VALUE, got git::ssh://git@github.com/myORG/terraform-modules.git=git::ssh://git@github.com/myORG/terraform-modules.git?ref=FEATURE.
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

I tried escaping the second `=`, but this didn't help.

**Comment by denis256** [comment]
Fix included in release: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.46.2
