### ISSUE TITLE
Guidance : feat: tag cluster_endpoint, cluster_certificate_authority_data outputs as sensitive

### ISSUE THREAD

**Issue by nikuljain** [gruntwork-io/terragrunt#2461]
**Need guidance on should we have below as sensitive ?**

when we try to create an AKS cluster using terragrunt, we see the following errors complaining about the sensitive outputs.
Error: Output refers to sensitive values

on outputs.tf line 11:
11: output "cluster_endpoint" {

To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.

If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
sensitive = true

Error: Output refers to sensitive values

on outputs.tf line 16:
16: output "cluster_certificate_authority_data"

output referred are below :
azurerm_kubernetes_cluster.default.kube_config[0].host
azurerm_kubernetes_cluster.default.kube_config[0].cluster_ca_certificate

**is there a way to bypass this check in terragrunt apply ?**

**Comment by denis256** [comment]
Hi,
I was wondering if can be used `nonsensitive` function to fetch output as a separate variable, maybe use `generate` block to build an output variables file.

References:

https://developer.hashicorp.com/terraform/language/functions/nonsensitive

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate

**Comment by nikuljain** [comment]
Thank you , i think terragrunt right fully calling the output to be sensitive , its more an issue at our end where we don't have control over the module we call
