### ISSUE TITLE
Changed aws region in terraform.tfvars, terragrunt plan would leave old vpc?

### ISSUE THREAD

**Issue by kcrouch** [gruntwork-io/terragrunt#247]
I used Conor Gilsenan's sample_configurations at

https://github.com/conorgil/terragrunt/commit/d0024f977fb5bb34f8fce2c16ef6c32d80b6c678

Changed bucket, region, and lock_table in 01_one_account_one_region/live/terraform.tfvars

and then hopped over to 01_one_account_one_region/live/staging/vpc

to give it a test.

$ terragrunt plan

Plan: 7 to add, 0 to change, 0 to destroy.

$ terragrunt apply

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

This deployed the VPC to us-east-1 since that was the default in the module.  Exactly what I expected.  I didn't really want to use us-east-1 though, so I added 

aws_region = "us-west-1"

to my 

01_one_account_one_region/live/staging/vpc/terraform.tfvars

and ran the plan again.

Plan: 7 to add, 0 to change, 0 to destroy.

I would have expected terragrunt/terraform to destroy the old resources in us-east-1.  I had to comment the aws_region variable out, do a destroy, uncomment it out, and do an apply to move the VPC.  Is this a bug?  An ambiguity?  A poor expectation on my part?  

Thanks all!

**Comment by brikis98** [comment]
If it comes up as "add" every time, it sounds like perhaps your state isn't being saved? Can you post the log output and more details about your file structure, `.tfvars` contents, etc?

**Comment by kcrouch** [comment]
I configured the vpc for us-east-1

$ grep region terraform.tfvars 
aws_region = "us-east-1"

Ran the apply

$ terragrunt apply
[terragrunt] [/Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc] 2017/07/13 16:22:37 Running command: terraform --version
[terragrunt] 2017/07/13 16:22:38 Reading Terragrunt config file at /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc/terraform.tfvars
[terragrunt] 2017/07/13 16:22:38 WARNING: no double-slash (//) found in source URL /conorgil/terragrunt_sample_vpc.git. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2017/07/13 16:22:38 Terraform files in /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y are up to date. Will not download again.
[terragrunt] 2017/07/13 16:22:38 Copying files from /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc into /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:22:38 Setting working directory to /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:22:38 Remote state is already configured for backend s3
[terragrunt] 2017/07/13 16:22:38 Running command: terraform apply
Acquiring state lock. This may take a few moments...
aws_vpc.main: Creating...
  assign_generated_ipv6_cidr_block: "" => "false"
  cidr_block:                       "" => "172.16.0.0/16"
  default_network_acl_id:           "" => "<computed>"
  default_route_table_id:           "" => "<computed>"
  default_security_group_id:        "" => "<computed>"
  dhcp_options_id:                  "" => "<computed>"
  enable_classiclink:               "" => "<computed>"
  enable_dns_hostnames:             "" => "<computed>"
  enable_dns_support:               "" => "true"
  instance_tenancy:                 "" => "<computed>"
  ipv6_association_id:              "" => "<computed>"
  ipv6_cidr_block:                  "" => "<computed>"
  main_route_table_id:              "" => "<computed>"
aws_vpc.main: Creation complete (ID: vpc-d75dc0ae)
aws_subnet.private.0: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "<computed>"
  cidr_block:                      "" => "172.16.3.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  tags.%:                          "" => "1"
  tags.visibility:                 "" => "private"
  vpc_id:                          "" => "vpc-d75dc0ae"
aws_subnet.public.2: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "<computed>"
  cidr_block:                      "" => "172.16.2.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  tags.%:                          "" => "1"
  tags.visibility:                 "" => "public"
  vpc_id:                          "" => "vpc-d75dc0ae"
aws_subnet.private.1: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "<computed>"
  cidr_block:                      "" => "172.16.4.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  tags.%:                          "" => "1"
  tags.visibility:                 "" => "private"
  vpc_id:                          "" => "vpc-d75dc0ae"
aws_subnet.public.0: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "<computed>"
  cidr_block:                      "" => "172.16.0.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  tags.%:                          "" => "1"
  tags.visibility:                 "" => "public"
  vpc_id:                          "" => "vpc-d75dc0ae"
aws_subnet.private.2: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "<computed>"
  cidr_block:                      "" => "172.16.5.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  tags.%:                          "" => "1"
  tags.visibility:                 "" => "private"
  vpc_id:                          "" => "vpc-d75dc0ae"
aws_subnet.public.1: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "<computed>"
  cidr_block:                      "" => "172.16.1.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  tags.%:                          "" => "1"
  tags.visibility:                 "" => "public"
  vpc_id:                          "" => "vpc-d75dc0ae"
aws_subnet.private.1: Creation complete (ID: subnet-d9c92dbd)
aws_subnet.public.2: Creation complete (ID: subnet-aa5fcb86)
aws_subnet.public.0: Creation complete (ID: subnet-4b2c6303)
aws_subnet.private.2: Creation complete (ID: subnet-c25dc9ee)
aws_subnet.private.0: Creation complete (ID: subnet-48226d00)
aws_subnet.public.1: Creation complete (ID: subnet-d10f838b)

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

The state of your infrastructure has been saved to the path
below. This state is required to modify and destroy your
infrastructure, so keep it safe. To inspect the complete state
use the `terraform show` command.

State path: 
Releasing state lock. This may take a few moments...

Outputs:

private_subnet_ids = [
    subnet-48226d00,
    subnet-d9c92dbd,
    subnet-c25dc9ee
]
public_subnet_ids = [
    subnet-4b2c6303,
    subnet-d10f838b,
    subnet-aa5fcb86
]
voc_cidr_block = 172.16.0.0/16

--

Good.  I see it in AWS.

If I do a show, it works.

$ terragrunt show
[terragrunt] [/Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc] 2017/07/13 16:31:14 Running command: terraform --version
[terragrunt] 2017/07/13 16:31:14 Reading Terragrunt config file at /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc/terraform.tfvars
[terragrunt] 2017/07/13 16:31:14 WARNING: no double-slash (//) found in source URL /conorgil/terragrunt_sample_vpc.git. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2017/07/13 16:31:14 Terraform files in /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y are up to date. Will not download again.
[terragrunt] 2017/07/13 16:31:14 Copying files from /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc into /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:31:14 Setting working directory to /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:31:14 Remote state is already configured for backend s3
[terragrunt] 2017/07/13 16:31:14 Running command: terraform show
aws_subnet.private.0:
  id = subnet-48226d00
  assign_ipv6_address_on_creation = false
  availability_zone = us-east-1c
  cidr_block = 172.16.3.0/24
  map_public_ip_on_launch = false
  tags.% = 1
  tags.visibility = private
  vpc_id = vpc-d75dc0ae
aws_subnet.private.1:
  id = subnet-d9c92dbd
  assign_ipv6_address_on_creation = false
  availability_zone = us-east-1a
  cidr_block = 172.16.4.0/24
  map_public_ip_on_launch = false
  tags.% = 1
  tags.visibility = private
  vpc_id = vpc-d75dc0ae
aws_subnet.private.2:
  id = subnet-c25dc9ee
  assign_ipv6_address_on_creation = false
  availability_zone = us-east-1b
  cidr_block = 172.16.5.0/24
  map_public_ip_on_launch = false
  tags.% = 1
  tags.visibility = private
  vpc_id = vpc-d75dc0ae
aws_subnet.public.0:
  id = subnet-4b2c6303
  assign_ipv6_address_on_creation = false
  availability_zone = us-east-1c
  cidr_block = 172.16.0.0/24
  map_public_ip_on_launch = false
  tags.% = 1
  tags.visibility = public
  vpc_id = vpc-d75dc0ae
aws_subnet.public.1:
  id = subnet-d10f838b
  assign_ipv6_address_on_creation = false
  availability_zone = us-east-1d
  cidr_block = 172.16.1.0/24
  map_public_ip_on_launch = false
  tags.% = 1
  tags.visibility = public
  vpc_id = vpc-d75dc0ae
aws_subnet.public.2:
  id = subnet-aa5fcb86
  assign_ipv6_address_on_creation = false
  availability_zone = us-east-1b
  cidr_block = 172.16.2.0/24
  map_public_ip_on_launch = false
  tags.% = 1
  tags.visibility = public
  vpc_id = vpc-d75dc0ae
aws_vpc.main:
  id = vpc-d75dc0ae
  assign_generated_ipv6_cidr_block = false
  cidr_block = 172.16.0.0/16
  default_network_acl_id = acl-f89f9b81
  default_route_table_id = rtb-7cc3e304
  default_security_group_id = sg-2e5a225f
  dhcp_options_id = dopt-e15e4f83
  enable_classiclink = false
  enable_dns_hostnames = false
  enable_dns_support = true
  instance_tenancy = default
  main_route_table_id = rtb-7cc3e304
  tags.% = 0


Outputs:

private_subnet_ids = [
    subnet-48226d00,
    subnet-d9c92dbd,
    subnet-c25dc9ee
]
public_subnet_ids = [
    subnet-4b2c6303,
    subnet-d10f838b,
    subnet-aa5fcb86
]
voc_cidr_block = 172.16.0.0/16

Running a plan looks good.

$ terragrunt plan
[terragrunt] [/Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc] 2017/07/13 16:31:19 Running command: terraform --version
[terragrunt] 2017/07/13 16:31:19 Reading Terragrunt config file at /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc/terraform.tfvars
[terragrunt] 2017/07/13 16:31:19 WARNING: no double-slash (//) found in source URL /conorgil/terragrunt_sample_vpc.git. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2017/07/13 16:31:19 Terraform files in /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y are up to date. Will not download again.
[terragrunt] 2017/07/13 16:31:19 Copying files from /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc into /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:31:19 Setting working directory to /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:31:19 Remote state is already configured for backend s3
[terragrunt] 2017/07/13 16:31:19 Running command: terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_vpc.main: Refreshing state... (ID: vpc-d75dc0ae)
aws_subnet.public.2: Refreshing state... (ID: subnet-aa5fcb86)
aws_subnet.public.1: Refreshing state... (ID: subnet-d10f838b)
aws_subnet.public.0: Refreshing state... (ID: subnet-4b2c6303)
aws_subnet.private.2: Refreshing state... (ID: subnet-c25dc9ee)
aws_subnet.private.1: Refreshing state... (ID: subnet-d9c92dbd)
aws_subnet.private.0: Refreshing state... (ID: subnet-48226d00)
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, Terraform
doesn't need to do anything.
Releasing state lock. This may take a few moments...

--

I change the region.

$ grep region terraform.tfvars 
aws_region = "us-west-1"

$ terragrunt plan
[terragrunt] [/Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc] 2017/07/13 16:36:42 Running command: terraform --version
[terragrunt] 2017/07/13 16:36:42 Reading Terragrunt config file at /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc/terraform.tfvars
[terragrunt] 2017/07/13 16:36:42 WARNING: no double-slash (//) found in source URL /conorgil/terragrunt_sample_vpc.git. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2017/07/13 16:36:42 Terraform files in /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y are up to date. Will not download again.
[terragrunt] 2017/07/13 16:36:42 Copying files from /Users/kcrouch/code/sample-for-terragrunt/terragrunt/_examples/01_one_account_one_region/live/staging/vpc into /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:36:42 Setting working directory to /var/folders/9q/q0b7ny7s4fgbydsyd0jrsml80000gn/T/terragrunt/1ULOiGxTmhpN-bcnOueAx1RJPiI/VSGbd1s7vFZKolySNYMYG8wTv1Y
[terragrunt] 2017/07/13 16:36:42 Remote state is already configured for backend s3
[terragrunt] 2017/07/13 16:36:42 Running command: terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_vpc.main: Refreshing state... (ID: vpc-d75dc0ae)
aws_subnet.public.1: Refreshing state... (ID: subnet-d10f838b)
aws_subnet.public.0: Refreshing state... (ID: subnet-4b2c6303)
aws_subnet.public.2: Refreshing state... (ID: subnet-aa5fcb86)
aws_subnet.private.0: Refreshing state... (ID: subnet-48226d00)
aws_subnet.private.1: Refreshing state... (ID: subnet-d9c92dbd)
aws_subnet.private.2: Refreshing state... (ID: subnet-c25dc9ee)
The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ aws_subnet.private.0
    assign_ipv6_address_on_creation: "false"
    availability_zone:               "<computed>"
    cidr_block:                      "172.16.3.0/24"
    ipv6_cidr_block:                 "<computed>"
    ipv6_cidr_block_association_id:  "<computed>"
    map_public_ip_on_launch:         "false"
    tags.%:                          "1"
    tags.visibility:                 "private"
    vpc_id:                          "${aws_vpc.main.id}"

+ aws_subnet.private.1
    assign_ipv6_address_on_creation: "false"
    availability_zone:               "<computed>"
    cidr_block:                      "172.16.4.0/24"
    ipv6_cidr_block:                 "<computed>"
    ipv6_cidr_block_association_id:  "<computed>"
    map_public_ip_on_launch:         "false"
    tags.%:                          "1"
    tags.visibility:                 "private"
    vpc_id:                          "${aws_vpc.main.id}"

+ aws_subnet.private.2
    assign_ipv6_address_on_creation: "false"
    availability_zone:               "<computed>"
    cidr_block:                      "172.16.5.0/24"
    ipv6_cidr_block:                 "<computed>"
    ipv6_cidr_block_association_id:  "<computed>"
    map_public_ip_on_launch:         "false"
    tags.%:                          "1"
    tags.visibility:                 "private"
    vpc_id:                          "${aws_vpc.main.id}"

+ aws_subnet.public.0
    assign_ipv6_address_on_creation: "false"
    availability_zone:               "<computed>"
    cidr_block:                      "172.16.0.0/24"
    ipv6_cidr_block:                 "<computed>"
    ipv6_cidr_block_association_id:  "<computed>"
    map_public_ip_on_launch:         "false"
    tags.%:                          "1"
    tags.visibility:                 "public"
    vpc_id:                          "${aws_vpc.main.id}"

+ aws_subnet.public.1
    assign_ipv6_address_on_creation: "false"
    availability_zone:               "<computed>"
    cidr_block:                      "172.16.1.0/24"
    ipv6_cidr_block:                 "<computed>"
    ipv6_cidr_block_association_id:  "<computed>"
    map_public_ip_on_launch:         "false"
    tags.%:                          "1"
    tags.visibility:                 "public"
    vpc_id:                          "${aws_vpc.main.id}"

+ aws_subnet.public.2
    assign_ipv6_address_on_creation: "false"
    availability_zone:               "<computed>"
    cidr_block:                      "172.16.2.0/24"
    ipv6_cidr_block:                 "<computed>"
    ipv6_cidr_block_association_id:  "<computed>"
    map_public_ip_on_launch:         "false"
    tags.%:                          "1"
    tags.visibility:                 "public"
    vpc_id:                          "${aws_vpc.main.id}"

+ aws_vpc.main
    assign_generated_ipv6_cidr_block: "false"
    cidr_block:                       "172.16.0.0/16"
    default_network_acl_id:           "<computed>"
    default_route_table_id:           "<computed>"
    default_security_group_id:        "<computed>"
    dhcp_options_id:                  "<computed>"
    enable_classiclink:               "<computed>"
    enable_dns_hostnames:             "<computed>"
    enable_dns_support:               "true"
    instance_tenancy:                 "<computed>"
    ipv6_association_id:              "<computed>"
    ipv6_cidr_block:                  "<computed>"
    main_route_table_id:              "<computed>"


Plan: 7 to add, 0 to change, 0 to destroy.
Releasing state lock. This may take a few moments...

-- 

It will create new stuff, but not destroy the old...

**Comment by brikis98** [comment]
@kcrouch It looks like this has nothing to do with Terragrunt, but just the way Terraform works. For example, I just created the following `main.tf`:

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_eip" "example" {}

output "ip" {
  value = "${aws_eip.example.public_ip}"
}
```

I ran `terraform apply`:

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

ip = 34.227.85.26
```

Then `terraform plan`:

```
No changes. Infrastructure is up-to-date.
```

Then I changed the region to `eu-west-1`:

```hcl
provider "aws" {
  region = "eu-west-1"
}
```

And ran `terraform plan` again:

```
+ aws_eip.example
    allocation_id:     "<computed>"
    association_id:    "<computed>"
    domain:            "<computed>"
    instance:          "<computed>"
    network_interface: "<computed>"
    private_ip:        "<computed>"
    public_ip:         "<computed>"
    vpc:               "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.
```

Note that there is 1 to add, but nothing to change or destroy. I'm using purely Terraform, so Terragrunt is not related.

My guess on why this happens based on how Terraform works:

* When you run `apply` the first time, it stores data about what was created in the state file. This data includes unique identifiers for each resources, such as the EIP ID.
* When you make changes and run `plan`, it fetches info for each of those resources using their identifiers, and compares the returned data against what's in your code.
* When you change regions, the requests for info about those resources probably *returns no data* because those identifiers don't exist in the new region. As a result, Terraform sees this as a 100% create, as if there is nothing to change.

It's definitely unintuitive and surprising behavior. Perhaps you could open a bug in the Terraform GitHub account to follow-up on this?
