### ISSUE TITLE
Terragrunt destroy command fails with "Could not parse output from terragrunt config"

### ISSUE THREAD

**Issue by yasirub** [gruntwork-io/terragrunt#2479]
I have following directory structure
📦iac
 ┣ 📂environment
 ┃ ┗ 📂dev
 ┃ ┃ ┣ 📂0-vpc
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┣ 📂1-igw
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┣ 📂2-subnets
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┣ 📂3-natgw
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┃ ┃ ┗ 📂4-rtbs
 ┃ ┃ ┃ ┗ 📜terragrunt.hcl
 ┗ 📂modules
 ┃ ┣ 📂igw
 ┃ ┃ ┣ 📜igw.tf
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┣ 📂natgw
 ┃ ┃ ┣ 📜natgw.tf
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┣ 📂rtb
 ┃ ┃ ┣ 📜rtb.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┣ 📂subnet
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┣ 📜subnet.tf
 ┃ ┃ ┗ 📜variables.tf
 ┃ ┗ 📂vpc
 ┃ ┃ ┣ 📜output.tf
 ┃ ┃ ┣ 📜variables.tf
 ┃ ┃ ┗ 📜vpc.tf

I am doing terragrunt apply from each sub folder in the dev folder and all works fine and infrastructure is creating fine. But when I try to do terragrunt destroy it doesn't work and give following error. I am using dependency blocks to get outputs form 0-vpc,1-igw,2-subnets folders to 4-rtbs folder
![image](https://user-images.githubusercontent.com/111842965/223015603-4ecc930f-bed1-4770-a964-15e8609540bb.png)

**Comment by denis256** [comment]
Hello,
will be helpful to have an example source code where this issue happens

**Comment by yasirub** [comment]
/4-rtbs/terragrunt.hcl
```
include "root" {
  path = find_in_parent_folders()
}

dependency "vpc" {
  config_path = "../0-vpc"
}
dependency "igw" {
  config_path = "../1-igw"
}
dependency "subnet" {
  config_path = "../2-subnets"
}
dependency "natgw" {
  config_path = "../3-natgw"
}

terraform{
  source = "../../../modules//rtb"
}

inputs = {
  vpc_id = dependency.vpc.outputs.vpc_details.id
  rtb-list = [
    {rtb_name = "smdb-pvt-rtb1-dev"
    routes = {
      "rt1" = {
        cidr_block = "0.0.0.0/0"
        gateway_id = ""
        nat_gateway_id = dependency.natgw.outputs.natgw[0].id
      }
    }
    subnet_ids = [dependency.subnet.outputs.subnets[0].id]
    rtb_tags = {
        "env" = "dev"
    }}
    ,
    {rtb_name = "smdb-pvt-rtb2-dev"
    routes = {
      "rt1" = {
        cidr_block = "0.0.0.0/0"
        gateway_id = ""
        nat_gateway_id = dependency.natgw.outputs.natgw[1].id
      }
    }
    subnet_ids = [dependency.subnet.outputs.subnets[1].id]
    rtb_tags = {
        "env" = "dev"
    }},
    {rtb_name = "smdb-pub-rtb-dev"
    routes = {
      "rt1" = {
        cidr_block = "0.0.0.0/0"
        gateway_id = dependency.igw.outputs.igw.id
        nat_gateway_id = ""
      }
    }
    subnet_ids = [dependency.subnet.outputs.subnets[2].id,dependency.subnet.outputs.subnets[3].id]
    rtb_tags = {
        "env" = "dev"
    }}
  ]
}
```
/3-natgw/terragrunt.hcl
```
include "root" {
  path = find_in_parent_folders()
}

dependency "subnet" {
  config_path = "../2-subnets"
}

terraform{
  source = "../../../modules//natgw"
}

inputs = {
  natgw-list = [{
    natgw_name = "smdb-nat1-dev"
    eip_name = "smdb-eip1-dev"
    subnet_id = dependency.subnet.outputs.subnets[2]
    natgw_tags = {
        "env" = "dev"
    }
    eip_tags = {
        "env" = "dev"
    }
  },
  {
    natgw_name = "smdb-nat2-dev"
    eip_name = "smdb-eip2-dev"
    subnet_id = dependency.subnet.outputs.subnets[3]
    natgw_tags = {
        "env" = "dev"
    }
    eip_tags = {
        "env" = "dev"
    }
  }
  ]
}
```
/2-subnets/terragrunt.hcl
```
include "root" {
  path = find_in_parent_folders()
}

dependency "vpc" {
  config_path = "../0-vpc"
}

terraform{
  source = "../../../modules//subnet"    
}

inputs = {
"vpc_id" = dependency.vpc.outputs.vpc_details.id
"subnet-list" = [{
  "subnet_name" = "smdb-pv1",
  "subnet_cidr_block" = "10.0.0.0/20",
  "subnet_av_zone" = "a",
  "subnet_tags" = {"owner"="clouda"},
},
{
  "subnet_name" = "smdb-pv2",
  "subnet_cidr_block" = "10.0.16.0/20",
  "subnet_av_zone" = "b",
  "subnet_tags" = {"owner"="clouda"},
},
{
  "subnet_name" = "smdb-pub1",
  "subnet_cidr_block" = "10.0.32.0/20",
  "subnet_av_zone" = "a",
  "subnet_tags" = {"owner"="clouda"},
},
{
  "subnet_name" = "smdb-pub2",
  "subnet_cidr_block" = "10.0.48.0/20",
  "subnet_av_zone" = "b",
  "subnet_tags" = {"owner"="clouda"},
}
]  
}
```
/1-igw/terragrunt.hcl
```
include "root" {
  path = find_in_parent_folders()
}

dependency "vpc" {
  config_path = "../0-vpc"
}

terraform{
  source = "../../../modules//igw"
}

inputs = {
  igw-list = [{
    name = "smdb-igw-dev"
    vpc_id = dependency.vpc.outputs.vpc_details.id
    tags = {
    "environment" = "dev"
    }
  }]
}
```
/0-vpc/terragrunt.hcl
```
include "root" {
  path = find_in_parent_folders()
}

terraform{
  source = "../../../modules//vpc"    
}

inputs = {
  vpc_name = "smart-db-dev"
  vpc_cidr_block = "10.0.0.0/16"
  vpc_tags = { "env" = "dev"}
}

**Comment by mhazegh** [comment]
@yasirub I'm running into this same error with a similar configuration. Were you ever able to find a solution?

Did the occur when you ran destroy from /3-natgw/, or only /4-rtbs/? In my case it is only occurring when I try to destroy a configuration which has multiple dependency blocks.

Running `terragrunt output -json` from the directory logged in the error results in valid JSON.

Upgrading to the latest versions didn't help either (terraform v1.4.6 / terragrunt v0.45.16).

**Comment by mhazegh** [comment]
After debugging the issue further, this seems to be a race condition that’s created when gathering outputs from multiple modules using the `runTerragruntOutputJson` method in config/dependency.go. 

@denis256, please see https://github.com/mhazegh/terragrunt-2479 for a minimal example of this error.

Steps to recreate the error using that repo:

1. Change the names of the buckets in modules a and b to something unique.
2. Run terragrunt apply from live/a, live/b, then live/c.
3. From live/c, run terragrunt destroy.
4. The following error will occur:

`ERRO[0011] Could not parse output from terragrunt config /xxx/terragrunt-2479/live/b/terragrunt.hcl. Underlying error: unexpected end of JSON input `

Adding a mutex around the code that gathers outputs fixes this error.

**config/dependency.go, lines 287-290:**
Old:
```
// Encode the outputs and nest under `outputs` attribute if we should get the outputs or the `mock_outputs`
if err := dependencyConfig.setRenderedOutputs(terragruntOptions); err != nil {
    return err
}
```
New:
```
outputLock := sync.Mutex{}
...
// Lock while gathering outputs.
outputLock.Lock()
// Encode the outputs and nest under `outputs` attribute if we should get the outputs or the `mock_outputs`
if err := dependencyConfig.setRenderedOutputs(terragruntOptions); err != nil {
    return err
}
outputLock.Unlock()
```

I haven't spent much time in this code, so I’m not sure what repercussions this change has. Ideally the call to `runTerragruntOutputJson` would be thread-safe.

**Comment by mhazegh** [comment]
Here is a temporary workaround for this issue:
```
terragrunt plan -destroy -out plan
terragrunt apply plan
```

**Comment by denis256** [comment]
Hello,
based on provided repository, released a fix in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.46.1
