### ISSUE TITLE
output from terraform.rfvars as input to other   terraform.rfvars

### ISSUE THREAD

**Issue by jonathanozvision** [gruntwork-io/terragrunt#248]
Hi,

I have the following directory layout:

env1
 - services
    - app1
          - main.tf
         - terraform.tfvars
 - vpc
    - main.tf
    - terraform.tfvars

I need the "VPC_ID" output from the VPC as input into "APP1". I know I should use terraform_remote_state to retrieve the data.
The problem is how to do is, as I don't use Terraform module, but terragrunt "include".

Can you please give some examples on how to use the output?

**Comment by pgrunwald** [comment]
@jonathanozvision I'm having this issue at the moment as well, how did you solve it?

**Comment by jonathanozvision** [comment]
@pgrunwald I used the 'terraform_remote_state' inside the "modules" repository (remote state in s3). 
In the VPC module I have an "environment" Variable, so I can retrieve the data with ${var.environment}/vpc/terraform.tfstate
Hope This can help you.

**Comment by pgrunwald** [comment]
@jonathanozvision, that helps, thanks. I hadn't seen the "terraform_remote_state" data source before. If anyone else is interested: https://www.terraform.io/docs/providers/terraform/d/remote_state.html.
