### ISSUE TITLE
terragrunt-exclude-dir not respected when running apply-all

### ISSUE THREAD

**Issue by JustinYeoh93** [gruntwork-io/terragrunt#2481]
I'm trying to exclude a directory when I run terragrunt apply. But from what I've been trying

The command `terragrunt run-all apply --terragrunt-exclude-dir us-west-1` is to run everything except the directory in us-west-1.
But as the pre-apply output below shows, it is still applying us-west-1.

```
➜  platform git:(master) tg run-all apply --terragrunt-exclude-dir us-west-1                                                                  
INFO[0000] The stack at /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform will be processed in the following order for command apply:
Group 1
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/kms
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/networking/vpc
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/vpn/ami
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/vpn/ip
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/vpn/key_pair
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/global/route53/public_hosted_zone
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/us-west-1/networking/vpc

Group 2
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/acm/public
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/vpn/security_group
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/global/route53/private_hosted_zone
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/us-east-1/acm/public
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/us-west-1/cluster/eks

Group 3
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/cluster/eks

Group 4
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/cluster/flux
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/rds
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/vpn/ec2

Group 5
- Module /Users/someuser/Projects/some-repo/iac/live/123456789012/some-repo/some-proj/test/platform/ap-northeast-1/vpn/openvpn
```

Any opinion on what I'm doing wrong would be much appreciated.

**Comment by denis256** [comment]
Hi,
was attempted to use `--terragrunt-exclude-dir **/us-west-1` or `--terragrunt-exclude-dir us-west-1/**` ?

**Comment by JustinYeoh93** [comment]
Hi there Denis,

Thank you very much for responding!

I've tried both your suggestions and it still takes the `us-west-1` into consideration.

**Comment by naresh-juniper** [comment]
@denis256 Any updates on this issue?

**Comment by bushong1** [comment]
I'm running into this same issue.  Best I can tell, globstar [`**`] is not something that works out of the box in golang.  Glob [`*`] will only work for 1 directory, as wildcard on paths will never include a slash.  

So in this example, you're trying to exclude `us-west-1`, but in the code it's looking for a module at path `us-west-1`.  There's no module at us-west-1, because the modules are `us-west-1/networking/vpc` and `us-west-1/cluster/eks`.  Further, you couldn't do `us-west-1/*` because that would only match one subdirectory.  You _could_ do `us-west-1/*/*`, but if you have future levels of subdirectories, they wouldn't be excluded.

So... the [very annoying] way around this would be:

```
terragrunt run-all apply --terragrunt-exclude-dir 'us-west-1/*' --terragrunt-exclude-dir 'us-west-1/*/*' --terragrunt-exclude-dir 'us-west-1/*/*/*' --terragrunt-exclude-dir 'us-west-1/*/*/*/*' # ... etc
```

**Comment by jonbackhaus-mt** [comment]
I'm seeing similar behavior with `terragrunt run-all init`. I have a monorepo of internal modules that looks like this: 

```sh
./aws-module-1
./aws-module-2
...
```

I'm setting the `TERRAGRUNT_EXCLUDE_DIR` variable as described above: 

```sh
export TERRAGRUNT_EXCLUDE_DIR='aws-module-1,aws-module-1/*,aws-module-1/*/*,aws-module-2,aws-module-2/*'
```

But when I execute the `run-all init` command, I see the following in my pipeline logs: 

```sh
msg=The stack at /builds/terraform-aws-modules will be processed in the following order for command init:
Group 1
- Module /builds/terraform-aws-modules/aws-module-1
- Module /builds/terraform-aws-modules/aws-module-2
- ...
```

Any ideas? I've also tried this with the CLI argument (`--terragrunt-exclude-dir`) but was getting errors with the `run-all init`.

**Comment by cpboyd** [comment]
It'd be nice if globstar was supported, or at least specifying a prefix as is desired in this case.

**Comment by manku211** [comment]
is this is solved im experiencing same error , I used glob star also

**Comment by foreignmeloman** [comment]
@yhakbar , @denis256  `--queue-exclude-dir` flag is pretty much unusable out of the box if you have a big nested structure of environments that you wish to skip during the execution. Have you considered making this flag working recursively or add a new one to do that?

**Comment by yhakbar** [comment]
@foreignmeloman I think "unusable" is a little strong here, don't you?

You can use a command like `find` and pipe the results in a `.terragrunt-excludes` file, and you'll be able to exclude a big nested structure of environments to skip (or use shell substitution to pass the results to `--queue-excludes-file`).

We're avoiding messing with the `--queue` flags in the short term, as we have a plan to replace a lot of them with [Filter Flags](https://github.com/gruntwork-io/terragrunt/issues/4060). If you have feedback on that design, your feedback is welcome!

**Comment by foreignmeloman** [comment]
@yhakbar thanks for the quick answer, and excuse me if my comment turned out to be sounding somewhat condescending. Indeed the filter flags proposal makes much more sense to me and seems like a much better CLI experience.
