### ISSUE TITLE
Need new get_aws_account_aliases() built-in function

### ISSUE THREAD

**Issue by dod38fr** [gruntwork-io/terragrunt#2483]
Hello

I'm using terragrunt in a company where the account alias is used to create the name of the tfstate bucket.

Currently, we are running an external `aws` command to list the accounts alias from `terragrunt.hcl`, but this is brittle.

To be able to get rid of this brittle code, I need a way to get the list of aliases with a builtin function. 

Could you add a new function similar to `get_aws_account_id` to get the list of account aliases ?

All the best

**Comment by dod38fr** [comment]
Note that an account can only have one alias at a time (see [doc](https://docs.aws.amazon.com/accounts/latest/reference/manage-acct-alias.html)). So I guess that the new function could be named `get_aws_account_alias` even if the underlying function is named [ListAccountAliases](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/iam#Client.ListAccountAliases)

**Comment by yhakbar** [comment]
This seems like a sensible request. I'll mark it as needs contribution, as it should be simple. This is not a top priority for maintainers, so someone from the community will have to take it on.

**Comment by wakeful** [comment]
hey @dod38fr 

I implemented the new function in #3607

**Comment by dod38fr** [comment]
> I implemented the new function in #3607

Thanks ! I'll use this asap.

All the best

**Comment by levkohimins** [comment]
Resolved in [v0.69.7](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.69.7) release.
