### ISSUE TITLE
Support for disabling generate blocks

### ISSUE THREAD

**Issue by szesch** [gruntwork-io/terragrunt#2496]
I have a use case where it would be helpful to disable generate blocks on a per environment basis. I work with a repository that contains dev environments that have their terraform source pointed to a local path and prod environments that have their source pointed to a git tag. I often run into a problem when adding a new generate block where the dev environments work as expected but the prod environment fail because a dependency has not yet been added to a prod release.

Ideally I would like to be able to introduce a new generate block to our dev environments first and have it disabled in prod using `local` vars per environment.

**Comment by ivankatliarchuk** [comment]
As I'm using `generate` all over in Terragrung config, this is definately an improvement.
You can consider following solution
```
generate "vault_resources" {
  path      = "_vault_resources.tf"
  if_exists = "overwrite_terragrunt"
  contents  = local.vault_enabled ? templatefile("${local.template_path}/vault_resources.tftpl", {}) : ""
}
```

One disadvantage, the empty file is created in cases when `local.vault_enabled == false`
