### ISSUE TITLE
remote_state block for gcs not adding labels to generated backend.tf file

### ISSUE THREAD

**Issue by slayer321** [gruntwork-io/terragrunt#2498]
Hii, I have a `remote_state`  block that I'm using inside the root terragrunt.hcl file and I want to add labels to the gcs and I'm using `gcs_bucket_labels` field inside the config field as mentioned in the [docs](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state) . 
After running the `terragrunt run-all init ...` command the backend.tf file is getting created. But the `gcs_bucket_labels` field that I passed i not getting added to the generated backend.tf file.
After checking the codebase I found below sentence [here](https://github.com/gruntwork-io/terragrunt/blob/2a87526a65043d33308be4897059b98789ad33e8/remote/remote_state_gcs.go#L40)
```
// These are settings that can appear in the remote_state config that are ONLY used by Terragrunt and NOT forwarded
// to the underlying Terraform backend configuration.
```
After reading this I makes sense that all the field that we have in `terragruntGCSOnlyConfigs` slice variable will not added to generated backend.tf file. What I don't understand it why this is the case . If it will not get added to the generated backend.tf file how will It get added to the gcs resouces on GCP ?

After I commented below two lines when I build the binary and tried running the init command it started adding the field in the generated backend.tf file
https://github.com/gruntwork-io/terragrunt/blob/2a87526a65043d33308be4897059b98789ad33e8/remote/remote_state_gcs.go#L145 https://github.com/gruntwork-io/terragrunt/blob/2a87526a65043d33308be4897059b98789ad33e8/remote/remote_state_gcs.go#L197
 
Can you let me know how can I add the labels to the generated backend.tf file without doing this hack or is there any other way to do it?

**Comment by findmyname666** [comment]
:+1: I encountered a similar issue e.g. I wasn't able to add the remote state labels in GCP.
