### ISSUE TITLE
Add ability to choose .terragrunt file path or specify options on command line

### ISSUE THREAD

**Issue by mildred** [gruntwork-io/terragrunt#25]
I am working on a special environment, and I would like the ability to choose a different `.terragrunt` file than the one on the current directory, or, even better, the ability to specify the options on the command line or environment variables. Currently, I'm automatically generating the `.terragrunt` file.

**Comment by brikis98** [comment]
It should be pretty straightforward to add a `--config` flag to specify a custom location for the `.terragrunt` file. That said, one of the main benefits of Terragrunt is that it provides fairly *transparent* remote state management. That is, you don't need to remember to run a specific command to connect to the right remote data store or to use a lock; you just run `terragrunt plan`, `terragrunt apply`, etc. and things "just work". If you have to remember to provide a `--config` flag every time pointing to the right location, it significantly increases the chances of making a mistake.

Could you describe your use case a bit more? Perhaps there is some alternative solution that does what you want while remaining fairly transparent.

**Comment by brikis98** [comment]
@mildred I haven't heard back in a while, so I'm going to close this for now. But let me know if this is something you want to discuss further and I can re-open the bug.

**Comment by mildred** [comment]
Sorry, I skipped the notification.

The use case is that we use terragrunt to automate infrastructure deployment. Previously we ran terragrunt in an AWS lambda, in which the filesystem is read only. The terraform files are bundled in the lambda and are in a read only directory. The terragrunt configuration must be generated on the fly because we don't want to hardcode the S3 bucket in the lambda.

The problem is that we cannot generate the terragrunt configuration because it is in a read only directory.

Currently, I work around this by going to a temporary directory where I write the `.terragrunt` file, and tell terraform to provision another directory.

**Comment by mildred** [comment]
I also implemented this : https://github.com/squarescale/terragrunt/commit/cbb4a4b74a067186d05e69446e40a2a068c468cc

**Comment by brikis98** [comment]
> The terraform files are bundled in the lambda and are in a read only directory. The terragrunt configuration must be generated on the fly because we don't want to hardcode the S3 bucket in the lambda.

If the terraform files are bundled in the lambda job, why isn't the `.terragrunt` file included too? After all, it should be in the same folder as the terraform files.

**Comment by mildred** [comment]
> If the terraform files are bundled in the lambda job, why isn't the .terragrunt file included too? After all, it should be in the same folder as the terraform files.

It is possible, but we may want to make the `.terragrunt` information dynamic depending on input variables. For example, we might want to use another AWS region. The terraform files are already fully generic. We already use variables on the terraform files to change how it behaves.

Ideally, if we could alter the .terragrunt content depending on external variables, we wouldn't need to generate the .terragrunt file on the fly.

**Comment by mildred** [comment]
> If the terraform files are bundled in the lambda job, why isn't the .terragrunt file included too? After all, it should be in the same folder as the terraform files.

It is not possible. The content of the .terragrunt file depends on external variables that are passed to the lambda.

Ideally, if we could alter the .terragrunt content depending on external variables, we wouldn't need to generate the .terragrunt file on the fly. The terraform files are already fully generic. We already use variables on the terraform files to change how it behaves.

Let me share with you the template we use to generate the terragrunt file:

		"# Configure Terragrunt to use DynamoDB for locking\n" +
		"dynamoDbLock = {\n" +
		"  stateFileId = \"customer-infra-" + request.CustomerName + "\"\n" +
		"}\n" +
		"\n" +
		"# Configure Terragrunt to automatically store tfstate files in an S3 bucket\n" +
		"remoteState = {\n" +
		"  backend = \"s3\"\n" +
		"  backendConfigs = {\n" +
		"    encrypt = \"true\"\n" +
		"    bucket = \"" + env.SqscTfstateBucket + "\"\n" +
		"    key = \"customer-infra-" + request.CustomerName + "-" + request.Environment + ".tfstate\"\n" +
		"    region = \"" + env.AWS_Region + "\"\n" +
		"  }\n" +
		"}\n"

**Comment by brikis98** [comment]
> The terraform files are already fully generic.

It seems like you're using Terraform in a somewhat non-standard way. Terraform is a declarative language, so typically, there is a one-to-one mapping between your Terraform files and what's actually deployed. For example, to deploy a single EC2 Instance to `us-east-1`, you'd put the following code in `main.tf`:

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_instance" "example" {
  ami = "ami-2d39803a"
  instance_type = "t2.micro"
}
```

If you wanted to deploy that code to `us-east-1` and `us-west-1`, the standard way to do that is NOT to run terraform twice on the same template, tweaking the `region` parameter in `provider.aws` each time, but to create two templates, one under `us-east-1/main.tf` and one under `us-west-1/main.tf`. 

To avoid having to copy/paste all the EC2 Instance code into each environment, you could define that code in a [module](https://www.terraform.io/docs/modules/usage.html) and reuse that module in both `us-east-1/main.tf` and `us-west-1/main.tf`. Of course, you'd also have a separate `.terragrunt` file in each folder. 

With this idiomatic and declarative approach, your Terraform templates actually represent the code deployed in production. On the other hand, if you just keep reusing the exact same templates by tweaking parameters and configuring different state files, then your code does NOT represent what's deployed, and you have to go digging through your AWS account and understand the full history of deployments to reason about what's actually running. Terraform's declarative nature is actually one of its biggest advantages, something I discuss more in depth [here](https://blog.gruntwork.io/why-we-use-terraform-and-not-chef-puppet-ansible-saltstack-or-cloudformation-7989dad2865c).

What exactly is your use case? Is there a reason you can't use the declarative approach with it?

**Comment by mildred** [comment]
Actually, we considered using modules, but going with variables is almost identical and best suited for our use case. Calling a module from within terraform is identical from calling terraform on the module with specific variables set. And we do the latter

Going into the module approach would require us to generate a very simple terraform file containing the variables we are currently putting on the command line. There is little added benefit. Especially considering we would be doing that in a throw away environment, and the code we would generate would be removed seconds later. Just boilerplate with no added benefit.

I don't consider what we are doing with variable going against terraform declarative way. The terraform code is not just declaring a static instance.

**Comment by brikis98** [comment]
Well, without knowing more about your use case, I'm in no position to evaluate the trade-offs of your approach. Perhaps being able to customize the location of the `.terragrunt` file would be useful to others, so if you want to submit a PR to add a command line option (e.g. `--config`), I'd be happy to merge it in. Thanks!

**Comment by mildred** [comment]
Thank you for considering this. Here is the PR.
