### ISSUE TITLE
Destroy all validates destroyed module

### ISSUE THREAD

**Issue by 76creates** [gruntwork-io/terragrunt#2500]
## Short
I have issues running `terragrunt run-all destroy` where TF is expecting variables from the module that is not even created, we can confirm this by checking the state file of the bad module which is empty.

## Detailed
When I run `terragrunt run-all destroy` my modules are separated into following groups:
```
Group 1
- Module /Users/gliga/Documents/git/grunt/twe/acm
- Module /Users/gliga/Documents/git/grunt/twe/efs
- Module /Users/gliga/Documents/git/grunt/twe/eks
- Module /Users/gliga/Documents/git/grunt/twe/rds

Group 2
- Module /Users/gliga/Documents/git/grunt/twe/route53

Group 3
- Module /Users/gliga/Documents/git/grunt/twe/vpc
```

When destroy function is started `rds` module from Group 1 returns following error:
```
╷
│ Error: Unsupported attribute
│ 
│   on main.tf line 37, in module "db":
│   37:   vpc_security_group_ids = [module.rds_sg.security_group_id]
│     ├────────────────
│     │ module.rds_sg is object with 2 attributes
│ 
│ This object does not have an attribute named "security_group_id".
```

Relevant lines on the module looks like this:
```
module "db" {
  depends_on = [
    module.rds_sg,
  ]
  source  = "terraform-aws-modules/rds-aurora/aws"
  version = "7.7.0"
  vpc_security_group_ids = [module.rds_sg.security_group_id]
  <redacted for readibility>
}

module "rds_sg" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "4.17.1"
  <redacted for readibility>
}
```
Further inspecting `terraform-aws-modules/security-group/aws` confirms that `security_group_id` is expected as the `output` variable.

State file is empty, `terragrunt state list` returns empty line.

As a consequence of this `terragrunt run-all destroy` wont finish execution and destroy rest of modules, I cant see why would it validate something like this when this module is destroyed.

## Expected
Terragrunt confirms that state file is empty, considers module destroyed, continues destroying other modules.

<hr>
Not sure how to proceed with this one, any help would be appreciated. I didn't try to reproduce it yet, so at the moment we can consider this one-off issue, tho I want to resolve it properly anyhow.

<hr>

## Update
I just changed `vpc_security_group_ids = [module.rds_sg.security_group_id]` to `vpc_security_group_ids = ["test"]` and ran destroy, and it ended up passing and destroying 3 outputs:

```Group 1
- Module /Users/gliga/Documents/git/grunt/twe/rds
 
WARNING: Are you sure you want to run 'terragrunt destroy' in each folder of the stack described above? There is no undo! (y/n) y

Changes to Outputs:
  - db_name = "trickest" -> null
  - db_port = 5432 -> null
  - db_user = (sensitive value)

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.

Destroy complete! Resources: 0 destroyed.
```

So this points out to issue where outputs that have not been destroyed are requiring modules and their dependant values to be validated for no reason.
Q: how can I manually destroy output values?

**Comment by levkohimins** [comment]
Hi @76creates ,

I didn't manage to repro the issue. This is most likely a terraform bug that has been fixed. 
I'm closing the issue, but if the issue still exists, feel free to re-open, we'll figure it out.
