### ISSUE TITLE
Github action to run terragrunt

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2506]
Implement Github Action which will allow execution of Terragrunt commands within actions:
 * automatically install required terragrunt and terraform versions
 * run terragrunt
 * collect outputs
 * load configurations from environment variables like log level, cli args, custom variables

**Comment by denis256** [comment]
Prototype implementation in:

https://github.com/denis256/tg-gh-action

https://github.com/denis256/tg-gh-action-examples

**Comment by brikis98** [comment]
We now have an official action in: https://github.com/gruntwork-io/terragrunt-action

@denis256 Can we close this ticket? Have we updated our docs to point to the official action?
