### ISSUE TITLE
Terragrunt does not override dependency blocks following _envcommon pattern

### ISSUE THREAD

**Issue by iancoralogix** [gruntwork-io/terragrunt#2510]
I have this block in my `_envcommon` for `eks-core-services` 

```
dependency "aurora" {
  config_path = "${get_terragrunt_dir()}/../../data-stores/aurora"

  mock_outputs = {
    primary_endpoint = "database"
    port             = 5432
  }
  mock_outputs_allowed_terraform_commands = ["validate", ]
}
```

I need to override this in my `eks-core-services/terragrunt.hcl` to point to a different location in my Reference Architecture, `config_path = "${get_terragrunt_dir()}/../../data-stores/aurora-legacy"`:

```
terraform {
  source = "${include.envcommon.locals.source_base_url}?ref=v0.91.0"
}

dependency "aurora" {
  config_path = "${get_terragrunt_dir()}/../../data-stores/aurora-legacy"

  mock_outputs = {
    primary_endpoint = "database"
    port             = 5432
  }
  mock_outputs_allowed_terraform_commands = ["validate", ]
}

# Include the root `terragrunt.hcl` configuration, which has settings common across all environments & components.
include "root" {
  path = find_in_parent_folders()
}

# Include the component configuration, which has settings that are common for the component across all environments
include "envcommon" {
  path = "${dirname(find_in_parent_folders())}/_envcommon/services/eks-core-services.hcl"
  # We want to reference the variables from the included config in this configuration, so we expose it.
  expose = true
}
```

However, this configuration does not work, and Terragrunt still searches for the original dependency.

**Comment by andreaadams11** [comment]
We're having the same issue, but only for a particular environment. Elsewhere the dependency override works fine. I haven't been able to determine what is different. Using terragrunt 0.32.3.

**Comment by Tomasz-Kluczkowski** [comment]
hit the same issue, the only way to override the dependency path is to use merge strategy = "deep" but then I get a lot of stuff that I don't want to get ...

**Comment by aryanchirania** [comment]
Hi @Tomasz-Kluczkowski, 
I am facing similar issue when trying to override `config_path` in the dependency block and while troubleshooting I found your merge_strategy sugesstion, but even after using merge_strategy as deep I am not able to override the config_path. 
Is there any specific version of terragrunt from which the override functionality was enabled with the deep merge strategy?

It will be very helpful if you can suggest something as I have a lot of use cases for this and currently as a workaround, I hvae to replicate the whole parent file just because of dependencies.

**Comment by aryanchirania** [comment]
@Tomasz-Kluczkowski Thanks for sharing the example. I figured out why I was getting the error even after using `merge_strategy = "deep`, I was using `expose = true` as well in the include block and it seems to be the case that if expose is set to true then terragrunt doesn't overrides the parent dependencies.

Have removed the expose pararmeter now and it is working as expected.

**Comment by ervinb** [comment]
Apparently the `dependency` block is getting a special treatment when using the `deep` merge strategy, where a `dependency` can be referenced in both directions: parent -> child, child -> parent.

I bet this is why `expose` isn't behaving as expected.

![image](https://github.com/gruntwork-io/terragrunt/assets/2212814/28eb2436-8b08-4bc3-9f45-c92cafc4f721)
