### ISSUE TITLE
Terragrunt fails to report useful error information.

### ISSUE THREAD

**Issue by reynoldsme** [gruntwork-io/terragrunt#2512]
In a number of situations terragrunt will output one to many errors that apply to specific dependencies of a modules without providing any context of what module was being operated on at the time of the issue.

In the following example a terragrunt module with 3 dependencies is in an odd state (the .terragrunt-cache directories need to be remove for one reason or another). Running `terragrunt init` produces the following output.

```
terragrunt init

Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.


ERRO[0016] exit status 1    
```

Ideally, terragrunt would produce usable contextual information about the issue encountered to help end users debug. In this particular situation, I would expect the name of each module to be printed, as well as the path to the module. Additionally `Please see the error message above.` suggests that some additional debugging information is being suppressed.

**Comment by denis256** [comment]
Hi,
looks like could help upgrade to v0.45.1 and use `--terragrunt-include-module-prefix` / `TERRAGRUNT_INCLUDE_MODULE_PREFIX=1` which should include to output module name

https://github.com/gruntwork-io/terragrunt/releases/tag/v0.45.1

**Comment by reynoldsme** [comment]
I had a call with a developer encountering the issue. I had them update terragrunt to `v0.45.2` and set `TERRAGRUNT_INCLUDE_MODULE_PREFIX=1` but the output we received was still:

```
terragrunt apply

Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.
```

Running `find ./ -type d -name “.terragrunt-cache” -exec rm -rf {} \;` from the root of our terragrunt repository did not change the behavior. However, running a shell script which refreshes AWS tokens and reconnects the user to the VPN DID fix the issue and allow running a normal plan/apply. The developer did not perform any git operations during the call.

So it is possible that this is caused by expired AWS tokens preventing reading the statefiles in s3, or bad network connectivity, or some combination of the two.

**Comment by Dhertz** [comment]
Could be similar to https://github.com/gruntwork-io/terragrunt/issues/2514 then, if the creds have expired

**Comment by denis256** [comment]
In https://github.com/gruntwork-io/terragrunt/releases/tag/v0.45.3 was added printing of module prefixes for simple commands too, I think also think that running terragrunt with `--terragrunt-log-level debug` may show on which terraform command it is failing
