### ISSUE TITLE
Terragrunt often and randomly needs the .terragrunt-cache directory manually removed.

### ISSUE THREAD

**Issue by reynoldsme** [gruntwork-io/terragrunt#2513]
Our developers often receive the following output when attempting to run a terragrunt plan , terragrunt apply, or terragrunt init.

```terragrunt init

Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.



Error: Initialization required. Please see the error message above.


ERRO[0016] exit status 1    
```
The only apparent solution is deleting all occurrences of `.terragrunt-cache` in the module structure. Ideally terragrunt would be able to detect that a `.terragrunt-cache` was in a bad state and be able to report more helpfully, or be able to avoid the initial situation from occurring.

**Comment by denis256** [comment]
Looks similar to https://github.com/gruntwork-io/terragrunt/issues/2512

**Comment by reynoldsme** [comment]
@denis256 This issue is intended to encapsulate a specific a specific situation that produces the rather unhelpful error message above. https://github.com/gruntwork-io/terragrunt/issues/2512 is intended to encapsulate the the more abstract general case where terragrunt has a tendency of producing non-optimal error messages when a number of different errors occur (at least without passing additional arguments).
