### ISSUE TITLE
Support AWS Aurora Severless v2

### ISSUE THREAD

**Issue by YLgearbox** [gruntwork-io/terragrunt#2520]
Hi guys,

The current Aurora module in [terraform-aws-service-catalog](https://github.com/gruntwork-io/terraform-aws-service-catalog) does not support serverless v2.

I created this [PR](https://github.com/gruntwork-io/terraform-aws-service-catalog/pull/1845) to update the upstream module and add relevant variables to support Aurora serverless v2.

The PR is ready for review.

**Comment by denis256** [comment]
Hi,
PR seems relevant to a different repository
