### ISSUE TITLE
New env-all command

### ISSUE THREAD

**Issue by qrevel** [gruntwork-io/terragrunt#253]
State Environments were released in terraform 0.9.0.
Before that, we needed to have [two separates folders](https://charity.wtf/2016/03/30/terraform-vpc-and-why-you-want-a-tfstate-file-per-env/) for prod and stage environment
IMO the prod/ and stage/ folders of a terraform folder structure can be merged to keep the code DRY. What do you think about this?
Are you planning to add a terragrunt env-all command to avoid using a custom script to change environment in all subdirectories?

**Comment by brikis98** [comment]
Personally, I'm not a fan of Terraform's state environments. Instead of being able to *see* that you have different environments in the code, you have to remember to run special commands to switch to those environments. To me, this seems more error prone and harder to understand.

What would an `env-all` command do?

**Comment by qrevel** [comment]
Hi @brikis98.
Thanks for the quick reply.

State environments maybe harder to understand but they're still helpfull if you want to avoid duplication.

It would change environment in all subdirectories:
```
# list all environments (it basically run terraform env list in all subdirectories)
terragrunt env-all list mydir

# select stage environment
terragrunt env-all select stage mydir

# create prod environment
terragrunt env-all new prod mydir

# delete test environment
terragrunt env-all delete test mydir
```
This feature would be nice to avoid human errors. Actually if I forgot to switch environment, i could modified the production web servers with the staging database.

Like `apply-all` command,  you can ask for confirmation before changing all environments inside subdirectories.

Terragrunt already automate a lot of work.
Hope someone will implement this nice feature.

Thanks

**Comment by brikis98** [comment]
Ah, I see. Seems like a handy feature. PRs welcome!

**Comment by brikis98** [comment]
Closing in favor of https://github.com/gruntwork-io/terragrunt/issues/492
