### ISSUE TITLE
terragrunt 'path_relative_to_include' issue

### ISSUE THREAD

**Issue by Stragavanza** [gruntwork-io/terragrunt#2534]
Hello.

I have an issue with terragrunt. After terragrunt plan or apply, at .terragrunt-cache _backend.tf contains this key:
key = "../../../../../home/username/something/layers/terraform.tfstate"
instead of 
key = layers/terraform.tfstate which is expected, because remote state and lock uses path_relative_to_include:
key = "${path_relative_to_include()}

It causes that when i run terragrunt plan or apply, it want to recreate all of resources regardless of whether it exists or not.

My environment: WSL 2 Ubuntu (22.04.2 LTS)

I reinstalled it, and tried with different versions.
I tried to run with terragrunt-log-level debug --terragrunt-debug.

If you need any further information, just comment, thank you very much

**Comment by denis256** [comment]
Hi,
I wanted to confirm key value is `key = "${path_relative_to_include()}/terraform.tfstate"` or `key = "${path_relative_to_include()}"` ?

https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#filling-in-remote-state-settings-with-terragrunt

**Comment by Stragavanza** [comment]
```
key = "${path_relative_to_include()}/terraform.tfstate}"
```

**Comment by denis256** [comment]
If will be used Terragrunt native Windows executable, the same issue happens?

**Comment by alvarogmj** [comment]
Seeing the same error in Mac, exactly the same code works OK in WSL. Tried with versions 0.43.2 and 0.48.0
