### ISSUE TITLE
add option to use system tflint instead of the embedded one

### ISSUE THREAD

**Issue by juljaeg** [gruntwork-io/terragrunt#2537]
We like to have consistent tflint versions for dedicated tflint calls and the indirect calls over terragrunt. The current behaviour always uses the embedded tflint version. I would like to propose to add a flag to not use the embedded version and instead just use the installed one.

My current workaround is to to a `run_cmd("--terragrunt-quiet", "which", "tflint")` so that the condition does not evaluate to `tflint`. Unfortunately this does not pass the inputs and var files then.

**Comment by denis256** [comment]
Hi,
Is the expectation here to be able to run a different executable in the tflint hook?
By default is invoked `tflint` command from path
https://github.com/gruntwork-io/terragrunt/blob/master/tflint/tflint.go#L43

**Comment by denis256** [comment]
Included in release: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.49.0

**Comment by juljaeg** [comment]
thats very cool :) Thank you 👍🏼
