### ISSUE TITLE
AWS S3 ACL changes blocking creating S3 buckets.

### ISSUE THREAD

**Issue by keyur-patel-imprivata** [gruntwork-io/terragrunt#2545]
We are utilizing this module to create our access-log buckets and with Recent AWS S3 changes , our IaC failing to create S3 buckets. As its not allowing to enable ACLs on S3. 

terragrunt module: https://github.com/gruntwork-io/terraform-aws-security/releases/tag/v0.67.9 
aws provider : v4.63.0 
TG Version: 0.38.7

│ Error: error creating S3 bucket ACL for bucket AccessControlListNotSupported: The bucket does not allow ACLs
│ 	status code: 400, request id: N41M1JZ69TCBPPXJ, host id: H1ECOelIGkCrNXmjfjTMw/7bazaAOTDHbmmeXd1oqoRPRGYZRYsQJlA7FaI425bz8vqcLw8r8EI=
│ 
│   with module.private_s3_bucket.aws_s3_bucket_acl.bucket[0],
│   on .terraform/modules/private_s3_bucket/modules/private-s3-bucket/main.tf line 51, in resource "aws_s3_bucket_acl" "bucket":
│   51: resource "aws_s3_bucket_acl" "bucket" {

**Comment by denis256** [comment]
Hi,
looks like the issue occurs during terraform execution, most probably this should be raised in https://github.com/gruntwork-io/terraform-aws-security/ repository

From `terraform-aws-securit` examples, I see were defined `bucket_ownership` for `private-s3-bucket`:
```
  bucket_ownership = "ObjectWriter"
```

https://github.com/gruntwork-io/terraform-aws-security/blob/main/examples/private-s3-bucket-with-replication/main.tf#L37

**Comment by keyur-patel-imprivata** [comment]
Thanks @denis256 ,
it seems this was raised in that repo https://github.com/gruntwork-io/terraform-aws-security/issues/771
