### ISSUE TITLE
Downloading git repositories over SSH does not respect SSH agent forwarding

### ISSUE THREAD

**Issue by jmgilman** [gruntwork-io/terragrunt#2546]
Given a URL like:

```
terraform {
  source = "git@github.com:my-repo/my-modules.git//modules/example"
}
```

And an SSH config like so:

```
Host myhost
  Hostname example.com
  User user
  ForwardAgent yes
  ```

During the initialization phase (when connected remotely), when the repository is being fetched, the underlying code ignores any forwarded SSH agent. Instead, it uses the SSH agent configured on the local machine. For clarity, this **is not** how the default git client behaves. I assume it's a bug in the underlying interfacing with git. 

The net result is I cannot fetch the external repository because the credentials are configured on my local SSH agent (not the remote one).

**Comment by levkoburburas** [comment]
@jmgilman, `terragrunt` uses a regular git command under the hood, thus there can't be any difference in behavior.

During testing, `terragrunt` running on a remote host was able to clone the source repo using credentials from the local host via ssh-agent.

**Comment by levkoburburas** [comment]
@jmgilman, please let me know if I missed something and the issue is not resolved.

**Comment by jmgilman** [comment]
Hi @levkoburburas,

Thanks, and sorry for the erroneous issue, but I found the culprit to be with the integrated vscode terminal. There are a bunch of existing issues with it not properly dealing with the ssh-agent. I'll close this out.
