### ISSUE TITLE
Terragrunt User Agent for API request

### ISSUE THREAD

**Issue by qrevel** [gruntwork-io/terragrunt#255]
It would be usefull for CloudTrail debugging.
I found a similar issue for [Terraform](https://github.com/hashicorp/terraform/issues/5020).

**Comment by brikis98** [comment]
Ah, that seems like a good idea. Terragrunt doesn't make too many API calls to AWS itself, but for the ones it does, we should add this. PRs welcome!

**Comment by denis256** [comment]
Improvement released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.14
