### ISSUE TITLE
No such function timecmp

### ISSUE THREAD

**Issue by gtmtech** [gruntwork-io/terragrunt#2560]
**Describe the bug**

I want to use the timecmp function which was available in terraform 1.3+

**To Reproduce**

```
terragrunt.hcl:

locals {
  foo = timecmp(timestamp(), timestamp())
}
```

**Expected behavior**

foo = 0

**Nice to have**

```
ERRO[0000]                                              
ERRO[0000] There is no function named "timecmp".
```

**Versions**
- Terragrunt version: 0.45.10
- Terraform version: 1.3.2

**Additional context**

timecmp is marked as available as of terraform 1.3 and above.

I think this means that terragrunt could use an update of the most recent terraform functions

**Comment by denis256** [comment]
Hi,
support for `timecmp` was added in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.45.13
