### ISSUE TITLE
Dependencies of dependencies not being respected in run-all group ordering

### ISSUE THREAD

**Issue by jlepere-everlaw** [gruntwork-io/terragrunt#2565]
**Describe the bug**

When calculating group ordering for `run-all` commands, dependencies of dependencies are not respected. The error manifests (at least how I experience it) as an outdated [output cache](https://github.com/gruntwork-io/terragrunt/blob/df9f8792c33920dece415c26edbd9e1415aca585/config/dependency.go#L137-L139).

**To Reproduce**
Consider the following module dependency graph.

![image](https://github.com/gruntwork-io/terragrunt/assets/51681265/a66fa3ec-c956-43f1-a9f1-a2f5034157bd)

When running a `terragrunt run-all` command against modules **A** and **C** (not **B**), **A** will **not** be processed before **C**. They'll be placed in the same group.

**Expected behavior**
Dependencies of dependencies should be respected in `run-all` group ordering. In the example above, **A** should be processed before **C**.

**Versions**
- Terragrunt version: v45.3
- Terraform version: v1.0.11
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 20.04

**Additional context**
It's probably worth considering whether targeting **A** and **C**, but not **B**, even makes sense since **B** is an explicit dependency of **C**. Internally within my organization we _might_ (edit: we were) be able rework some things to avoid this, but we have a fairly complex module graph. This seems like a reasonable bug nonetheless.

**Comment by levkoburburas** [comment]
@jlepere-everlaw, are you using [dependencies](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependencies) block? If so, could you please provide a simple configuration to reproduce this behavior?

**Comment by jlepere-everlaw** [comment]
> @jlepere-everlaw, are you using [dependencies](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependencies) block?

I'm using [dependency](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency) blocks.

> If so, could you please provide a simple configuration to reproduce this behavior?

I drastically simplified the example relative to my organization's configuration, so I don't off-hand. Let me see if I can whip something up real quick.

**Comment by jlepere-everlaw** [comment]
> > If so, could you please provide a simple configuration to reproduce this behavior?
> 
> I drastically simplified the example relative to my organization's configuration, so I don't off-hand. Let me see if I can whip something up real quick.

Alright, @levkoburburas, I was able to reproduce this with the following.

```
# terragrunt-issue-2565-example/A/
terraform {
  source = "./"
}

# terragrunt-issue-2565-example/B/
terraform {
  source = "./"
}
dependency "A" {
  config_path = "../A"
}

# terragrunt-issue-2565-example/C/
terraform {
  source = "./"
}
dependency "B" {
  config_path = "../B"
}

$ terragrunt run-all apply --terragrunt-working-dir terragrunt-issue-2565-example/ --terragrunt-strict-include --terragrunt-include-dir A --terragrunt-include-dir C
INFO[0000] The stack at terragrunt-issue-2565-example/ will be processed in the following order for command apply:
Group 1
- Module /home/jakelepere/everlaw/servers/terragrunt-issue-2565-example/A
- Module /home/jakelepere/everlaw/servers/terragrunt-issue-2565-example/C
```

**C** should be processed in a separate group after **A** because **C** implicitly depends on **A**.
