### ISSUE TITLE
When logging errors include the module being processed

### ISSUE THREAD

**Issue by alain-odea-sequence** [gruntwork-io/terragrunt#2566]
**Describe the solution you'd like**
When Terragrunt logs an error from an underlying command or tool like Terraform I would like it to enrich the log entry with the executing module (the path to the terragrunt.hcl being executed).

A better error log could look something like this (see the path to the executing terragrunt.hcl in the log entry):
```plain
[ecs-deploy-runner][2023-05-10T15:57:22+0000] [INFO] [infrastructure-deploy-script] 2023-05-10 15:57:22  "terragrunt plan" exited with code 1 (stage/ca-central-1/stage/data-stores/s3-data-analysis)
[ecs-deploy-runner][2023-05-10T15:57:22+0000] Error: Could not run "terragrunt plan". Error=╷
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ Error: Failed to load state: AccessDenied: Access Denied
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ 	status code: 403, request id: HTG67CNVKVS914TQ, host id: JWPorM+aYtr3gVh31wXuviaoRAVv/R88whdhbJxJ0XDwLsnvT9cX87V2jwb6W+x0l0EIUbKJ4X4=
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ 
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ 
[ecs-deploy-runner][2023-05-10T15:57:22+0000] ╵
[ecs-deploy-runner][2023-05-10T15:57:22+0000] time=2023-05-10T15:57:22Z level=error msg=exit status 1
```

In the case of a nested executed (like processing a dependency) the error should be attributed to the path of the dependency! It might be useful in that case to log that the dependency failed, but I think that is already occurring.

**Describe alternatives you've considered**
I do not think there is an alternative to this. Without it I end up trying to guess where the errors are coming from

**Additional context**
Here's an example of the Gruntwork Pipelines executing terragrunt in an ecs-deploy-runner and encountering an S3 error:
```plain
[ecs-deploy-runner][2023-05-10T15:57:07+0000] [INFO] [infrastructure-deploy-script] 2023-05-10 15:57:07  Running command "terragrunt plan -input=false"
[ecs-deploy-runner][2023-05-10T15:57:13+0000] ╷
[ecs-deploy-runner][2023-05-10T15:57:13+0000] │ Error: Failed to load state: AccessDenied: Access Denied
[ecs-deploy-runner][2023-05-10T15:57:13+0000] │ 	status code: 403, request id: HTG67CNVKVS914TQ, host id: JWPorM+aYtr3gVh31wXuviaoRAVv/R88whdhbJxJ0XDwLsnvT9cX87V2jwb6W+x0l0EIUbKJ4X4=
[ecs-deploy-runner][2023-05-10T15:57:13+0000] │ 
[ecs-deploy-runner][2023-05-10T15:57:13+0000] │ 
[ecs-deploy-runner][2023-05-10T15:57:13+0000] ╵
```

It later logs this which looks like an attempt at providing context:
```plain
[ecs-deploy-runner][2023-05-10T15:57:22+0000] [INFO] [infrastructure-deploy-script] 2023-05-10 15:57:22  "terragrunt plan" exited with code 1
[ecs-deploy-runner][2023-05-10T15:57:22+0000] Error: Could not run "terragrunt plan". Error=╷
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ Error: Failed to load state: AccessDenied: Access Denied
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ 	status code: 403, request id: HTG67CNVKVS914TQ, host id: JWPorM+aYtr3gVh31wXuviaoRAVv/R88whdhbJxJ0XDwLsnvT9cX87V2jwb6W+x0l0EIUbKJ4X4=
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ 
[ecs-deploy-runner][2023-05-10T15:57:22+0000] │ 
[ecs-deploy-runner][2023-05-10T15:57:22+0000] ╵
[ecs-deploy-runner][2023-05-10T15:57:22+0000] time=2023-05-10T15:57:22Z level=error msg=exit status 1
```

It is unclear from this error which module was being planned when the error occurred and which S3 bucket and key it was trying to access. Having terragrunt provide its best understanding of the context when logging this error might help in diagnosis. I realize that will likely not have the S3 bucket and key since Terraform doesn't surface those in its errors.

@josh-padnick

**Comment by josh-padnick** [comment]
@denis256: I spoke this morning with @alain-odea-sequence and this sounds like a solid quality-of-life improvements for Terragrunt users. Could you take a look when you get a chance?

**Comment by denis256** [comment]
Yes, looking into this one

**Comment by alain-odea-sequence** [comment]
Thank you @denis256! And thank you again @josh-padnick for prioritizing this for us!
