### ISSUE TITLE
state  & lock different AWS account from resources

### ISSUE THREAD

**Issue by jonathanozvision** [gruntwork-io/terragrunt#257]
Hi,

I need my state (s3) and lock table (Dynamo) to be saved in account A,
BUT the resources will be provisioned in another account.
I have read #48, I guess I just don't use it correctly.

this is by backend config:

terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket     = "BUCKET"
      key        = "ENVNAME/${path_relative_to_include()}/terraform.tfstate"
      region     = "us-east-1"
      encrypt    = true
      lock_table = "TABLE"
      profile    = "default"
    }
  }
}

how can I point TG to provision the actual resources in a different account?

**Comment by brikis98** [comment]
> how can I point TG to provision the actual resources in a different account?

You don't point Teragrunt to create the resources in a different account; you point *Terraform* to do it. For that, use the normal mechanisms, such as env vars.

**Comment by jonatanzafar59** [comment]
I figured it out. The "profile" section in terragrunt doesn't work if AWS_ACCESS_KEY and AWS_SECRET_KEY variables are defined. 
It does work with AWS_PROFILE.
