### ISSUE TITLE
Documentation improvements to keep environment configuration DRY

### ISSUE THREAD

**Issue by paulaustin-automutatio** [gruntwork-io/terragrunt#2573]
In my application I have multiple environments and within each environment potentially multiple instances of the same resource (e.g. database server). This resulted in the terragrunt.hcl files for the having to Repeat Yourself with config to pull in the various configuration from the environment and the source.

NOTE: I also kept the module version DRY by putting the version in a version.txt file for each instance.

```
- terragrunt.hcl
+ test
  - environment.tfvars
  + PostgreSQL
    + InstanceA
      - terragrunt.hcl
      - db.auto.tfvars
      - version.txt
```

This is the code that was repeated.

```
include "root" {
  path = find_in_parent_folders()
}

locals {
  sourceVersion = trimspace(file("${get_terragrunt_dir()}/version.txt"))
}

terraform {
  source = "git@github.com:my/my_modules.git//modules/PostgreSQL?ref=${local.sourceVersion}"

  extra_arguments "common_vars" {
    commands = get_terraform_commands_that_need_vars()

    required_var_files = [
      "${get_terragrunt_dir()}/../../environment.tfvars"
    ]
  }
}
```

I changed this by at the top level adding a module/PostreSQL/PostgreSQL.hcl file with the following.

```
locals {
  sourceVersion = trimspace(file("${get_terragrunt_dir()}/version.txt"))
}

terraform {
  source = "git@github.com:my/my_modules.git//modules/PostgreSQL?ref=${local.sourceVersion}"

  extra_arguments "common_vars" {
    commands = get_terraform_commands_that_need_vars()

    required_var_files = [
      "${get_terragrunt_dir()}/../../environment.tfvars"
    ]
  }
}
```

Then my terragrunt.hcl file in the instance becomes DRY

include "root" {
  path = find_in_parent_folders()
}

include "root" {
  path = "../../module/PostgreSQL/PostgreSQL.hcl"
}

If you think this is useful to share could you add this kind of example into the documentation?

**Comment by denis256** [comment]
Hello,
as a reference can be used example repositories:

- https://github.com/gruntwork-io/terragrunt-infrastructure-live-example
- https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example
