### ISSUE TITLE
Latest Release is missing assets

### ISSUE THREAD

**Issue by JustinJohnWilliams** [gruntwork-io/terragrunt#2575]
**Describe the bug**
Release [v0.45.14](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.45.14) does not contain the OS build assets

![image](https://github.com/gruntwork-io/terragrunt/assets/517113/392a83f9-4736-46a8-a42f-42f599a8a3e7)

**Comment by JustinJohnWilliams** [comment]
They're there now ✨. You all rock!

**Comment by denis256** [comment]
CICD jobs just finished execution...

![Screenshot 2023-05-18 at 20 20 04](https://github.com/gruntwork-io/terragrunt/assets/10694338/8476a417-6da5-479e-8f5e-e417b26ac836)

https://github.com/gruntwork-io/terragrunt/runs/13587437031
