### ISSUE TITLE
How to use the outputs of a remote state in the inputs of terragrunt.

### ISSUE THREAD

**Issue by luismenco** [gruntwork-io/terragrunt#2582]
Hello community, 
I am using a module in my terragrunt project, this module creates an ec2 instance, I am setting the inputs in my terragrunt file, one of the input is the vpc id, this vpc id already exists in aws and was created by another terraform project, I don have access to this project, but this project has a remote state file on s3, how can i use that output in my inputs?
this is a example of my code
`# set source for terraform config files
terraform {
  source = "../module/ec2"
}
#remote state
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    bucket         = "bucket"
    key            = "state1.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "table"
  }
}
inputs = {
  
  vpc_id        = "vpc-04086ad4443a92c65" i want get this value from a external remote state
 
}
`

**Comment by denis256** [comment]
Hi,
can be attempted to use `--terragrunt-fetch-dependency-output-from-state`

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-fetch-dependency-output-from-state
