### ISSUE TITLE
Feature: dont actually run terraform

### ISSUE THREAD

**Issue by gtmtech** [gruntwork-io/terragrunt#2590]
**Describe the solution you'd like**

Terragrunt is very useful as an orchestrator - so useful in fact that, I want to use it to orchestrate other things, not just terraform. I can do this with before_hook, and after_hook - so... is there any way of actually skipping running terraform as an optional attribute on the terraform block?

**Describe alternatives you've considered**

I looked for overriding the terraform binary to something else, but thats a bit hacky.

**Comment by denis256** [comment]
Hi, 
AFAIK, can be defined `terraform_binary` property to some dummy command, but it will still be hacky

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_binary

**Comment by yhakbar** [comment]
Take a look at this:
@gtmtech 

https://github.com/gruntwork-io/terragrunt/issues/3445

The proposed `exec` command should be the kind of thing you're looking for.
