### ISSUE TITLE
Merging multiple "generate" files

### ISSUE THREAD

**Issue by AliSajid** [gruntwork-io/terragrunt#2592]
**Describe the solution you'd like**
I am trying to build a rather complex infrastructure. This means that some submodules require different versions of the AWS provider. I am generating `provider.tf` using a `generate` block in the root `terragrunt.hcl`. I would like to be able to override or merge files in the submodules from the root modules.

** Example for Overriding **
In my root `terragrunt.hcl` I have the following generate block:

```hcl
generate "providers" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
    terraform {
        required_version = ">= 1.0.0"
        required_providers {
            aws = {
                source = "hashicorp/aws"
                version = "~> 5.1.0"
            }
    }
}

provider "aws" {
    region = "us-east-2"
}
```

However, a submodule needs `hashicorp/aws < 5.0.0`.

I would like to be able to add a merge block to only change that one section.

** Example of output merging **

Suppose I am generating a boilerplate `outputs.tf` file but want to have it augmented by a secondary output file. I would like that file to be mergable.

**Describe alternatives you've considered**

**Additional context**

**Comment by gtmtech** [comment]
We handle this by reverse-looking-up the versions in a parallel config file in the submodule - e.g. 

```
| - toplevel.hcl
| - default_versions.hcl
| - submodule1/
       | - terragrunt.hcl
       | - versions.hcl
```       

Then in terragrunt.hcl

```
include "toplevel" {
  path = find_in_parent_folders("toplevel.hcl")
}
```

Then in versions.hcl

```
locals {
  aws_version = "5.0.0"
}
```

Then in toplevel.hcl

```
locals {
  versionshcl = try(read_terragrunt_config("./versions.hcl"), read_terragrunt_config(find_in_parent_folders("default_versions.hcl")))
}

generate "providers" {
  path = "providers.tf"
  if_exists = "overwrite"
  contents = <<EOF
...
version = "~> ${local.versionshcl.locals.aws_version}"
```

Finally in default_versions.hcl

```
locals {
  aws_version = "5.1.0"
}
```

Hope this helps

**Comment by AliSajid** [comment]
Thank you. That's a little more complicated than what I was expecting but it does solve my problem. I can use the pattern in other places as well. :)
