### ISSUE TITLE
Dynamically create dependency blocks

### ISSUE THREAD

**Issue by gtmtech** [gruntwork-io/terragrunt#2593]
**Describe the solution you'd like**

I am fetching my dependencies from external commands for _reasons_. 

This works with `dependencies` block as I can inject into the paths attribute:

```
locals {
  dependencies = jsondecode(run_cmd("./get-dependencies.sh")) # returns e.g. '[ "module3", "module7" ]'
}

dependencies {
  paths = [ for d in local.dependencies: format("../%s", d) ]    
}
```

But I cannot do this for `dependency` block, because `dependency` is a block. I note from https://github.com/gruntwork-io/terragrunt/issues/1571 that it is said that it is not currently supported to generate dependency dynamically. 

I would like this ability natively supported

**Describe alternatives you've considered**

Searching for ways to achieve this. I thought of a hacky way to do it as follows:

- Create a null file called dep-null.hcl at the top
- Create dependency terragrunt snippets, dep-module1.hcl, dep-module2.hcl, dep-module3.hcl... at the top - each creating a dependency to a specific submodule e.g.

```
dependency "module1" {
  config_path = "../module1"
  mock_outputs = jsondecode(run_cmd("./get-dependency-mock-outputs.sh module1"))
}
```

- Create dynamic include blocks instead of dynamic dependency blocks as follows:

```
include "dep1" {
  path = contains(local.dependencies, "module1") ? find_in_parent_folders("dep-module1.hcl") : find_in_parent_folders("dep-null.hcl")
  expose = true
}

include "dep2" {
  path = contains(local.dependencies, "module2") ? find_in_parent_folders("dep-module2.hcl") : find_in_parent_folders("dep-null.hcl")
  expose = true
}

... etc...
```

Would work, but not exactly friendly or DRY

**Additional context**

**Comment by joaocc** [comment]
Hi. Would also love to have this, as otherwise it's not possible to have truly dynamic infrastructures, as dependencies end up being static, without resorting to some techniques like aggregating elements in a source module with multiple elements so it's only 1 dependency. Maybe this is difficult due to the impact on graph generation, but would be very useful nevertheless.

**Comment by kristijorgji** [comment]
Hi I would also love to have this.

My use case is this:
I am testing different architectures and want to export ssm vars based on the fact that some env variable is set.

If USE_ALB is set want to create and export load balancer vars, otherwise do something else.


```
terraform {
  source = "github.com/kristijorgji/terraform-aws-ssm-store?ref=v1.1.0"
}

// TODO include dynamically only if tobool(get_env("TG_USE_ALB", "false")) === true
dependency "alb" {
  config_path = "../alb/instance"
}

inputs = {
  kms_alias = "alias/aws/ssm"

  name_prefix = "/test"

  overwrite = true
  parameters = concat(
    [
      {
        name      = "dafsasdffds"
        value     = "dada"
        type      = "SecureString"
        overwrite = true
      },
    ],
    tobool(get_env("TG_USE_ALB", "false")) ? [
      {
        name  = "lb_https_listener_arn"
        value = element(dependency.alb.outputs.https_listener_arns, 0)
    }, ] : []
  )
}

```
