### ISSUE TITLE
Terragrunt does not allow `extra_arguments` block to have more than defined amount of args for `output` command

### ISSUE THREAD

**Issue by mschlin** [gruntwork-io/terragrunt#2594]
**Describe the bug**
When adding an `extra_arguments` block for the `output` command, you are only limited to 1 or 0 extra arguments in the `arguments` list. This is unexpected behavior, since:
1. There is no mention in the docs that the `arguments` in the `extra_arguments` block is limited to what that command can take.
2. I thought that since `extra_arguments` is a wrapper around the command I define, it would be "dumb" and naively pass arguments rather than do a check for arg length. (Maybe add a "naive" option for args?)

**To Reproduce**
Write 2 or more arguments in an extra_arguments block defined for an `output` command.

```hcl
// /.infrastructure/_base_modules/functionapp.hcl
extra_arguments "output_to_file" {
    commands = ["output"]
    arguments = [
      "-json", ">", "${get_terragrunt_dir()}/output.json"
    ]
  }
```

**Expected behavior**
Every `terragrunt output` command will have `-json > ${get_terragrunt_dir()}/output.json` appended to it, resulting in a json representation of the output being written to the same location as my terragrunt.hcl.

**Terminal Output:**
```
PS C:\Users\...\.infrastructure\ucd\stage\functionapp> terragrunt output
╷
│ Error: Unexpected argument
│ 
│ The output command expects exactly one argument with the name of an output
│ variable or no arguments to show all outputs.
╵

For more help on using this command, run:
  terraform output -help
time=2023-06-05T15:51:12-04:00 level=error msg=Terraform invocation failed in .../.terragrunt-cache/NnoSJU-vDNw4zh78HlGstAwsLY0/4q11Lo8ICXyP3UaqqZlcfOgh-Ok/.infrastructure/_base_modules/functionapp prefix=[...\.infrastructure\ucd\stage\functionapp]
time=2023-06-05T15:51:12-04:00 level=error msg=1 error occurred:
        * [.../.terragrunt-cache/NnoSJU-vDNw4zh78HlGstAwsLY0/4q11Lo8ICXyP3UaqqZlcfOgh-Ok/.infrastructure/_base_modules/functionapp] exit status 1
```

**Versions**
- Terragrunt version: v0.46.2
- Terraform version: v1.4.6
- Environment details: Windows 10

**Additional context**
I want the output of my terragrunt to be written to a file on every invocation of `terragrunt output`, so if someone knows a work around that would be awesome. Thank you!

**Comment by davoodharun** [comment]
I can confirm this behavior

**Comment by denis256** [comment]
Hi, 
output redirection ">" is a feature of the shell, not of terraform.

Most probably can be a defined hook that will invoke terraform in bash with output redirection:
```
  after_hook "output_to_file_hook" {
    commands     = ["output"]
    execute      = ["bash", "-c", "terraform output -json > ${get_terragrunt_dir()}/output.json"]
  }

```
