### ISSUE TITLE
Support for Terraform 1.5

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2606]
**Describe the solution you'd like**
Add support for running Terraform 1.5 in Terragrunt

Important points to consider:
* outputs fetching
* support for new arguments/commands
* new HCL functions

**Describe alternatives you've considered**
N/A

**Additional context**

https://github.com/hashicorp/terraform/releases/tag/v1.5.0

**Comment by modsaid** [comment]
More importantly,   how can we utilize the new "import existing resources" configuration
https://www.hashicorp.com/blog/terraform-1-5-brings-config-driven-import-and-checks#config-driven-import

This is super promising. but how can we utilize it through terragrunt and current hcl files?

**Comment by modsaid** [comment]
On a second thought, probably for "import existing resources"  specifically the modules them self should take possible references as an input and do the "import". internally...    it is probably not something to do on terragrunt level

**Comment by bt-macole** [comment]
current work around for this is using `generate`

```bash
└── example-role
    ├── import.hcl
    └── terragrunt.hcl
```

ex:
```hcl
generate "import" {
  path      = "import.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF

import {
    id = "example-role"
    to = aws_iam_role.this
}

EOF
}

```

terragrunt.hcl
```hcl
terraform {
  source = "git::ssh://git@github.com/EXAMPLE/infrastructure-modules.git//security/iam-role?ref=v1337
}

include "root" {
  path = find_in_parent_folders()
}

include "import" {
  path = find_in_parent_folders("import.hcl")
}

inputs = {
  name = "example-role"
}
```
