### ISSUE TITLE
terragrunt aws s3 backend access log issue

### ISSUE THREAD

**Issue by prasadm1983** [gruntwork-io/terragrunt#2607]
**Describe the bug**
while enabling access log setting  in s3 backend remote config its giving
(excluded: false, assume applied: false, dependencies: []), finished with an error: AccessControlListNotSupported: The bucket does not allow ACLs
**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
// paste code snippets here
```remote_state {
  backend = "s3"
  config = {
    encrypt        = true
    bucket         = "test-${lower(local.account_vars.locals.account_name)}-infrastructure-tf-"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = local.aws_region
    dynamodb_table = "infrastructure-live"
    accesslogging_bucket_name  = "prasad-s3-access-logs"
    accesslogging_target_prefix= "logs/"
  }


**Versions**
- Terragrunt version: v1.3.7
- Terraform version: v0.37.1
- Environment details (Ubuntu 20.04, Windows 10, etc.): mac bigsur

**Additional context**
Add any other context about the problem here.

**Comment by jgrant-sms** [comment]
What version of terragrunt are you using?

In April of 2023 AWS made a change to S3 disabling Access Control List by default. The version of terragrunt you are using may be from before that change.

https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-s3-security-best-practices-buckets-default/
