### ISSUE TITLE
Githubaction Terragrunt directory files changes display 

### ISSUE THREAD

**Issue by topeawolwo** [gruntwork-io/terragrunt#2610]
I am using  this Githubaction "uses: dorny/paths-filter@v2" and Terragrunt to execute steps in a workflow job only if some file in a subfolder is changed

``
 #Execute step in a workflow job only if some file in a subfolder is changed
- uses: dorny/paths-filter@v2
  id: filter
  with:
    base: ${{ github.base_ref }}
    working-directory: ${{ inputs.dir-root }}
    list-files: shell
    filters: |
      hcls:
        - added|modified: '${{ inputs.dir-root }}/**/terragrunt.hcl'
        - added|modified: '${{ inputs.dir-root }}/**/.terraform.lock.hcl'
        - '**/'
    token: ${{ secrets.GITHUB_TOKEN }}

- name: Changed HCL
  if: ${{ steps.filter.outputs.hcls == 'true' }}
  run: |
      echo ${{ steps.filter.outputs.hcls_files }}
- name: Extract unique changed directories
  id: oxygendir
  run: |
    res=()
    i=0
    for file in ${{ steps.filter.outputs.hcls_files }}
    do
     DIR="$(dirname "${file}")"
     res[i]=$DIR
     i=$((i+1))
    done
    sorted="$(printf "%s\n" "${res[@]}" | sort -u)"
    output=${sorted[*]//$'\n'/ }
    echo $output
    echo "::set-output name=changed_directories::$output"

``

The issue, is this on changing files in my directories Terrageunt plan and apply can not display the changed files

``
Terragrunt to 
 - name: Terragrunt Plan
  uses: mathiasvr/command-output@v1
  id: plan
  with:
    run: |
      for dir in ${{ steps.oxygendir.outputs.changed_directories }}
      do
        cd ${{github.workspace}}/$dir
        terragrunt plan -out=tfplan
        echo "::set-output name=tf_actions_plan_has_changes::true"
        echo "::set-output name=tf_actions_plan_output::$(cat tfplan)"
      done

``

just wondering why Terragrunt cant display files changes in my GithubAction

**Comment by denis256** [comment]
Hi,
I would suggest passing debug flags to see what is happening inside, but mentioned GH action is not supported by Gruntwork
