### ISSUE TITLE
  Terragrunt plan -out=tfplan not executing in GithubAction

### ISSUE THREAD

**Issue by topeawolwo** [gruntwork-io/terragrunt#2611]
my Terragrunt workflow
```
- name: Terragrunt Plan
  uses: mathiasvr/command-output@v2.0.0
  id: plan
  with:
      run: |
        for dir in ${{ steps.oxygendir.outputs.changed_directories }}
        do
          cd ${{github.workspace}}/$dir
          terragrunt plan -out=tfplan
          echo "::set-output name=tf_actions_plan_has_changes::true"
          echo "::set-output name=tf_actions_plan_output::$(cat tfplan)"
        done
```
  Terragrunt plan -out=tfplan is not executing in the GithubAction and cant see any changes

**Comment by denis256** [comment]
Hi,
GH action `mathiasvr/command-output@v2.0.0` is not supported by Gruntwork.io, if will appear any issues with execution of Terragrunt commands, I would suggest opening a separated bug and include debug outputs
