### ISSUE TITLE
'terragrunt (run-all) show -json planfile' very slow

### ISSUE THREAD

**Issue by gercograndia** [gruntwork-io/terragrunt#2612]
**Describe the bug**

We're using the `terragrunt show` command to inspect the planfile in order to automatically determine the drift and whether critical resources are being created.

However, we notice that the terragrunt version of the 'show' command is massively slower than the native `terraform show`.

For example some runs on the same (single) module:

- terragrunt run-all show --terragrunt-non-interactive  -json planfile  32.12s user 16.94s system 115% cpu 42.445 total
- terragrunt show --terragrunt-non-interactive  -json planfile  19.20s user 8.06s system 128% cpu 21.255 total
- terraform show -json planfile  0.56s user 0.11s system 123% cpu 0.543 total

> Note: we are using the run-all even in a single module as it allows us to use just one setting for TERRAGRUNT_SOURCE

The difference between the `run-all show` and regular `show` is explainable (although still quite a bit) as it needs to identify dependencies. Even though you would hope that when using the `--exclude-external-dependencies` this would be less than the roughly 10 seconds we're seeing now.

However, the terraform command is simply blindingly fast in comparison with the terragrunt counterpart, with a much bigger difference than I would expect.

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
> terragrunt run-all plan  --terragrunt-ignore-external-dependencie
> time terragrunt run-all show --terragrunt-non-interactive  -json planfile

> terragrunt plan
> time terragrunt show --terragrunt-non-interactive  -json planfile

# cd into the right .terragrunt-cache directory
> time terraform show -json planfile
```

**Expected behavior**
Way smaller differences.

**Versions**
- Terragrunt version: v0.45.15
- Terraform version: v.1.4.5
- MacBook Pro M2 Pro

**Additional context**

We are running the `terragrunt show` for each module one by one in a (sometimes large) project consisting of many modules, as when we are running the `terragrunt run-all show` we get lots of outputs but no option to find out to which module a particular output belongs. There might be ways, but we just didn't find them yet.

**Comment by denis256** [comment]
Hi,
first of all I wanted to clarify used CLI arguments, Terragrunt supports `--terragrunt-ignore-external-dependencies` CLI arg

Arguments like `--exclude-external-dependencies` or `--terragrunt-ignore-external-dependencie` aren't supported

References:
https://terragrunt.gruntwork.io/docs/reference/cli-options/#cli-options

Second, will be helpful to have a test repository where performance can be verified, from description is not clear how the repository is organized

**Comment by gercograndia** [comment]
Hi,

Apologies for the typos but the arguments are correct in reality.

Below the results (in seconds) per command:
- terragrunt run-all show --terragrunt-non-interactive --terragrunt-ignore-external-dependencies -json planfile => 36,91s
- terragrunt show -json planfile  => 28.73s
- terraform show -json planfile => 0.96s

Having a test repo will be difficult, I am able to make the repos we work on public although I can confirm I see the same behaviour across multiple repositories I'm working on. Of course there are dependencies to other modules (which have dependencies to other modules) but nothing out of the ordinary I would expect? Anyways, I have added the output of `terragrunt graph-dependencies` at the end.

Are you saying that you see more or less the same response times with `terragrunt show` as you see with `terraform show`? The difference is that vast in my environment that I'm really wondering what's going on.

If that's the case it would definitely be useful to sort of reproduce it in a different environment.

```
digraph {
	"project-dir/terragrunt/dlzs/data-platform/global/ad-groups" ;
	"project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/ad-groups" ;
	"project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/ad-groups" -> "project-dir/terragrunt/dlzs/data-platform/global/ad-groups";
	"project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/az-devops" ;
	"project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/az-devops" -> "project-dir/terragrunt/dlzs/data-platform/global/ad-groups";
	"project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/az-devops" -> "project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/ad-groups";
	"project-dir/terragrunt/dlzs/data-platform/sbx/base" ;
	"project-dir/terragrunt/dlzs/data-platform/sbx/base" -> "project-dir/terragrunt/dlzs/data-platform/sbx/central-dns";
	"project-dir/terragrunt/dlzs/data-platform/sbx/base" -> "project-dir/terragrunt/smz/run/monitor";
	"project-dir/terragrunt/dlzs/data-platform/sbx/central-dns" ;
	"project-dir/terragrunt/dlzs/data-platform/sbx/central-dns" -> "project-dir/terragrunt/dlzs/data-platform/sbx/networking";
	"project-dir/terragrunt/dlzs/data-platform/sbx/central-dns" -> "project-dir/terragrunt/smz/run/networking";
	"project-dir/terragrunt/dlzs/data-platform/sbx/networking" ;
	"project-dir/terragrunt/dlzs/data-platform/sbx/networking" -> "project-dir/terragrunt/smz/run/monitor";
	"project-dir/terragrunt/dlzs/data-platform/sbx/networking" -> "project-dir/terragrunt/smz/run/networking";
	"project-dir/terragrunt/dlzs/data-platform/sbx/runtimes" ;
	"project-dir/terragrunt/dlzs/data-platform/sbx/runtimes" -> "project-dir/terragrunt/smz/run/monitor";
	"project-dir/terragrunt/dlzs/data-platform/sbx/runtimes" -> "project-dir/terragrunt/smz/run/core";
	"project-dir/terragrunt/dlzs/data-platform/sbx/runtimes" -> "project-dir/terragrunt/dlzs/data-platform/sbx/central-dns";
	"project-dir/terragrunt/dlzs/data-platform/sbx/runtimes" -> "project-dir/terragrunt/dlzs/data-platform/sbx/base";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/base" ;
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/base" -> "project-dir/terragrunt/dlzs/data-platform/sbx/central-dns";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/base" -> "project-dir/terragrunt/smz/run/monitor";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" ;
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/smz/run/monitor";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/az-devops";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/dlzs/data-platform/global/substacks/edh-dataprocessing-env/ad-groups";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/dlzs/data-platform/sbx/central-dns";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/dlzs/data-platform/sbx/networking";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/base";
	"project-dir/terragrunt/dlzs/data-platform/sbx/substacks/edh-dataprocessing-env/dataproc" -> "project-dir/terragrunt/dlzs/data-platform/sbx/runtimes";
	"project-dir/terragrunt/smz/run/core" ;
	"project-dir/terragrunt/smz/run/core" -> "project-dir/terragrunt/smz/run/monitor";
	"project-dir/terragrunt/smz/run/core" -> "project-dir/terragrunt/smz/run/networking";
	"project-dir/terragrunt/smz/run/monitor" ;
	"project-dir/terragrunt/smz/run/networking" ;
	"project-dir/terragrunt/smz/run/networking" -> "project-dir/terragrunt/smz/run/monitor";
}
```

**Comment by gercograndia** [comment]
I did a test with going to the module at the head of of the dependency graph and this makes a huge difference.

Times were ranging between 0.4 seconds (native terraform) to a bit less than 2 seconds (terragrunt run-all). And the regular `terragrunt show` somewhere in between.

So clearly it is the dependencies that is slowing it down.

My assumption was, that with the planfile already present on disk, there would be no need for dependency parsing but apparently that is not the case.

Not sure this is an inevitability of how terragrunt works, or something that could be altered over time.

**Comment by denis256** [comment]
Hello,
during `run-all` Terragrunt builds dependencies tree and read outputs of identified dependencies each time so it is expected to be slower
Passing plan file helps in Terraform execution and doesn't speed up dependencies identification / outputs reading

**Comment by gercograndia** [comment]
I figured something like that, but:

1. The regular `terragrunt show` is also doing something in this regard, otherwise why would it take almost 30s in our regular projects. That is definitely not what I would expect.
2. I would have hoped that using `--terragrunt-ignore-external-dependencies` while being in a module directory (with no further modules in the tree) would have reduced that significantly. But alas.

I have hacked around a little and are using the native `terraform show` now (when possible), which reduces showing and analyzing the planfiles from more than hour in a large project, to a few minutes. Not nice, but the overhead is simply too large to ignore.

**Comment by tkflexys** [comment]
We ran into the same issue, in our CI setup we have a special variable called `TG_DISABLE_DEPENDENCIES` which we use to disable dependencies when running terragrunt/terraform commands that clearly don't need to have their dependencies checked, such is a case here as well.

For each of our project folders containing a `terragrunt.hcl` file with a `source block` we add the following block
```
include "dependencies" {
  path = tobool(get_env("TG_DISABLE_DEPENDENCIES", "false")) ? find_in_parent_folders("generators/noop.hcl") : "./dependencies.hcl"
}
```
noop.hcl is an empty file while dependencies.hcl would contain your standard dependency declaration
i.e
```
dependency "vpc" {
  config_path = "../vpc"
}
dependency "rds" {
  config_path = "../rds"
}
inputs = {
  vpc_id = dependency.vpc.outputs.vpc_id
  db_url = dependency.rds.outputs.db_url
}
```

This cuts the plan time for our envs from 50-100% when using `terragrunt show`
