### ISSUE TITLE
Terragrunt printout in Githubaction

### ISSUE THREAD

**Issue by topeawolwo** [gruntwork-io/terragrunt#2614]
In my Terragrunt ClI I can print out to stdout the Terragrunt Plan and Apply but having difficuly printing out in GithubAction.

In my environment with this folder structures, with Terragrunt files, I had made changes to the Terragrunt file and i want to print the changs in my githubActions 

```
account
 └ _global
 └ region
    └ _global
    └ environment
       └ resource
```

I want to print this Outputs: in my GithubAction

asg_name = tf-asg-00343cdb2415e9d5f20cda6620
asg_security_group_id = sg-d27df1a3
elb_dns_name = webserver-example-prod-1234567890.us-east-1.elb.amazonaws.com
elb_security_group_id = sg-fe62ee8f
url = http://webserver-example-prod-1234567890.us-east-1.elb.amazonaws.com:80

      - name: Terragrunt Plan
       
        id: plan
        with:
          run: |
            for dir in ${{ steps.dedupe.outputs.changed_directories }}
            do
              cd ${{github.workspace}}/$dir
              terragrunt plan -no-color
            done

**Comment by denis256** [comment]
Hi,
most probably can help `terragrunt output` or `terragrunt run-all output`
