### ISSUE TITLE
Files are not appropriately copied to the working dir

### ISSUE THREAD

**Issue by alexqrid** [gruntwork-io/terragrunt#2620]
**Describe the bug**
While trying to copy files to terragrunt.hcl directory using before hook, it is copied to the directory but not copied to the workdir(.terragrunt-cache).
I have the following dir structure:
```
.
├── infra
│   ├── common
│   │   ├── iam
│   │       ├── variables.tf
│           └── terragrunt.hcl
│   ├── prod
│   │   ├── iam
│   │       ├── terragrunt.hcl

```

<details><summary>infra/common/iam/terragrunt.hcl</summary>

```
...
terraform = {
  source = "my module ref on git"

  before_hook "copy_vars" {
    commands = ["init","plan","apply"]
    execute  = ["cp", "${dirname(find_in_parent_folders())}/common/iam/variables.tf", "${get_terragrunt_dir()}/variables.tf"]
  }
}
...
```
</details>

<details><summary>infra/prod/iam/terragrunt.hcl</summary>

```
include "iam" {
  path = "${dirname(find_in_parent_folders())}/common/iam/terragrunt.hcl"
}
```
</details>

During `terragrunt init` the file `infra/common/iam/variables.tf` is copied to `infra/prod/iam/`, but the file is not copied to the `infra/prod/iam/.terragrunt-cache/...` and `terragrunt plan` fails as a result.
Seems like a bug, because I expect that all files in `infra/prod/iam/` should be copied to `infra/prod/iam/.terragrunt-cache/...`
**Expected behavior**
All files from module directory are copied to the working directory, i.e. .terragrunt-cache/<path_to_downloaded_module/

**Versions**
- Terragrunt version: `v0.47.0`
- Terraform version: `v1.4.4`
- Environment details: Debian 11

**Comment by denis256** [comment]
Hi,
`get_terragrunt_dir()` will return the directory where `terragrunt.hcl` is located
For the hook, "working" directory is already set to `.terragrunt-cache`, so can be used "." target where to copy files:

```
terraform {
  source = "."
  before_hook "copy_vars" {
    commands = ["init","plan","apply"]
    execute  = ["cp", "${dirname(find_in_parent_folders())}/common/iam/variables.tf", "."]
  }
}

```

Simplified example in: https://github.com/denis256/terragrunt-tests/tree/master/issue-2620

References:
https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_terragrunt_dir

**Comment by alexqrid** [comment]
@denis256 Thanks, suggested solution works! 
But shouldn't terragrunt copy all files from directory where `terragrunt.hcl` is located to the "working" directory `.terragrunt-cache` except "hidden" files:
> By default, Terragrunt excludes hidden files and folders during the copy step

**Comment by denis256** [comment]
Yes, 
the copy is performed
From your example, I see that `variables.tf` is in `common/iam` which is outside of `prod/iam` and not included in the copy
