### ISSUE TITLE
Terragrunt tries to execute run_cmd before applying extra_arguments block

### ISSUE THREAD

**Issue by mitter91** [gruntwork-io/terragrunt#2621]
**Describe the bug**
We're using vault to keep secrets, and getting them with vault cli
so in terragrunt inputs it looks like run_cmd("--terragrunt-quiet", "vault", "kv", "get", etc.)
i've tried to pass env var (VAULT_NAMESPACE) for that execution with extra_arguments block
and unfortunately terragrunt wants to to execute run_cmd() firstly, before extra_arguments block

**To Reproduce**
look to hcl

```hcl
terraform {
  extra_arguments "vault" {
    commands  = ["init", "plan", "apply", "destroy", "refresh"]
    arguments = []
    env_vars = {
      VAULT_NAMESPACE = "<namespace>"
    }
  }
}

inputs = {
  secret_data = run_cmd("--terragrunt-quiet", "vault", "kv", "get", "-mount=<some-mount>", "-field=<field>, "<path>")
}
```

**Expected behavior**
extra_arguments block applies before run_cmd commands

**Versions**
- Terragrunt version: v0.45.0
- Terraform version: v1.3.9

**Comment by denis256** [comment]
Hi,
`run_cmd` will be executed before invoking `terraform`, otherwise will not be known which inputs to pass to `terraform`

References
https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd
