### ISSUE TITLE
How to create resources in root module ?

### ISSUE THREAD

**Issue by CiucurDaniel** [gruntwork-io/terragrunt#2622]
If my understanding is correct, in Terragrunt, you will have 2 parts:
* modules
* root module / live (where Terragrunt is used)

In my case I have infrastructure in Azure, one env contains the following: 
* Kubernetes cluster, 
* PSQL server x 3, 
* VM x 1.

I do have modules for Kubernetes, for PSQL Server and for the VM. 

In my root module (without Terragrunt), I call the modules to create the resources but I also create some resources in the root module:

* a resource group for the environment which is used by all other resources in the env 
* a PrivateDNSZone which the 3 PSQL servers need for DNS records.

```hcl
# example root module for dev
# main.tf

# NOTICE this is created here in root
resource "azurerm_resource_group" "environment-rg" {
  name     = "dev-rg"
  location = "West US"
}

module "kubernetes" {
some_var = "some_value"
}

# NOTICE this is created here in root
resource "azurerm_private_dns_zone" "dns" {
  name                = "mydomain.com"
  resource_group_name = azurerm_resource_group.environment-rg
}

module "psql_1" {
some_var = "some_value"
}

module "psql_2" {
some_var = "some_value"
}

module "psql_3" {
some_var = "some_value"
}

module "vm" {
some_var = "some_value"
}

```
Creating a module for a Resource group or PrivateDNSZone alone makes no sense as they have 2-3 fields to be configured.

```hcl
# a module to create just this resource simply looks like overkill for me

resource "azurerm_resource_group" "example" {
  name     = "testResourceGroup1"
  location = "West US"

  tags = {
    environment = "Production"
  }
}
```

This brings in my question regarding what can we do in root module with Terragrunt, because so far I see it only calling reusable modules. I do understand the points where it helps which is the reason I look forward to introduce it, but I do not see how the scenario that I have can be handled. 

**In Terragrunt are you able to create resources in the root module (live) ?**
**Should you? If not how to handle scenarios as above?**

**Comment by tkflexys** [comment]
Wouldn't you use a `generate` block in this case to create those small resources without encapsulating them in a module ? 

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate
