### ISSUE TITLE
 destination path 'alx-pre_course' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by Sahlaouisouhayla** [gruntwork-io/terragrunt#2626]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
// paste code snippets here
```

**Expected behavior**

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version:
- Terraform version:
- Environment details (Ubuntu 20.04, Windows 10, etc.):

**Additional context**

**Comment by denis256** [comment]
Closing issue since the description is missing, please open issues with a clear description
