### ISSUE TITLE
Remote backend config from multiple backend.conf files

### ISSUE THREAD

**Issue by sevagh** [gruntwork-io/terragrunt#263]
Hello,

I have a bunch of Terraform configs structured something like this:

```
├── backend.conf (shared)
├── cluster-1
│   ├── backend.conf
│   ├── terraform.tfvars
└── cluster-2
    ├── backend.conf
    ├── terraform.tfvars
```

I initialize each of these with `terraform init --backend-config=./backend.conf --backend-config=../backend.conf`. The root `backend.conf` contains the meat of it (s3 bucket name, DynamoDB lock table name), and the sub-files have different `key` values to distinguish the stacks.

Is there any way this translates to Terragrunt?

I.e.:

```hcl
terragrunt = {
  remote_state {
    backend = "s3"
    config { "${get_tfvars_dir()}/../backend.conf" }
    config { "backend.conf" }
  }
}
```
(this doesn't work, just a contrived example)

I also tried:
```hcl
extra_arguments "custom_vars" {
      commands = [
        "init",
      ]

      arguments = [
        "-backend-config=${get_tfvars_dir()}/../backend.conf",
        "-backend-config=backend.conf"
      ]
    }
```
This didn't help me either.

Any suggestions?

Thanks

**Comment by sevagh** [comment]
I'm reading through this now which seems relevant: https://github.com/gruntwork-io/terragrunt/issues/26

**Comment by brikis98** [comment]
The support for passing files to `-backend-config` is fairly new to Terraform and not yet supported by Terragrunt. In fact, there are a bunch of changes that came out with Terraform 0.10.0 that we are trying to figure out how to support in Terragrunt. See #261 for the discussion.

**Comment by sevagh** [comment]
Thanks for the update. Meanwhile is there a reason this doesn't work?

```
extra_arguments "custom_vars" {
      commands = [
        "init",
      ]

      arguments = [
        "-backend-config=${get_tfvars_dir()}/../backend.conf",
        "-backend-config=backend.conf"
      ]
    }```

If `extra_vars` were applied to `terraform init` (and I'm not sure why it's not being applied - is `init` a special case?) it's still a compelling reason for our organization to use Terragrunt and avoid typing `terraform init -backend-config=../backend.conf -backend-config=../../backend.conf` each time.

**Comment by brikis98** [comment]
Since Terragrunt calls `init` for you, it doesn't currently let you call it yourself. Changing this behavior is what we're discussing in #261.

**Comment by sevagh** [comment]
I think I can close this now. Feel free to re-open if it's still relevant.
