### ISSUE TITLE
Cannot run terragrunt plan with same -out path twice

### ISSUE THREAD

**Issue by iomarcovalente** [gruntwork-io/terragrunt#2632]
**Describe the bug**
Running `terragrunt plan -out="/tmp/tgplan.tf"` twice from the same folder, results in an infinite loop error. 

**To Reproduce**
create a valid terragrunt folder and run `terragrunt plan -out="/tmp/tgplan.tf"` twice

**Expected behavior**
The plan to be overwritten

**Nice to have**
Terminal output of creating the plan successfully:
```
ζ ls                                                                                                                                                                      [34829c0] 
dev            terragrunt.hcl
# M1: ~/Documents/git/aws/infra/kms <feature/issue-334/terraform-restructure ✘ [*?]>                                       (14:22:08)  
ζ terragrunt plan -out="$(pwd)/tgplan.tf"                                                                                                                                 [34829c0] 
module.kms_ebs.module.kms.data.aws_caller_identity.current: Reading...
module.account_context.data.aws_region.current: Reading...
module.kms_rds[0].module.kms.data.aws_caller_identity.current: Reading...
module.kms_sns.module.kms.data.aws_caller_identity.current: Reading...
module.kms_ebs.data.aws_region.current: Reading...
module.kms_rds[0].data.aws_region.current: Reading...
module.kms_sns.module.kms.data.aws_partition.current: Reading...
(...)
long plan output here
(...)
    }

╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on ../../../modules/aws/kms/versions.tf line 12, in terraform:
│   12:   experiments = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or
│ patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub
│ issue to discuss it.
│ 
│ (and 2 more similar warnings elsewhere)
╵

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: /Users/user01/Documents/git/aws/infra/kms/tgplan.tf

To perform exactly these actions, run the following command to apply:
    terraform apply "/Users/user01/Documents/git/aws/infra/kms/tgplan.tf"
Releasing state lock. This may take a few moments...
# M1: ~/Documents/git/aws/infra/kms <feature/issue-334/terraform-restructure ✘ [*?]>                                       (14:22:21)  
ζ ls                                                                                                                                                                      [34829c0] 
dev            terragrunt.hcl tgplan.tf
```

If I run again `terragrunt plan -out="$(pwd)/tgplan.tf"` (or `terragrunt plan` alone for that matter), I get this:
![Screenshot 2023-07-06 at 14 25 29](https://github.com/gruntwork-io/terragrunt/assets/12092106/b9329c58-b106-48e1-a056-ca247ac621cd)

as if it is trying to do something with the binary file

**Versions**
- Terragrunt version: `terragrunt version v0.46.3`
- Terraform version: `Terraform v1.2.9`
- Environment details (Ubuntu 20.04, Windows 10, etc.):  M1 Ventura 13.4

**Additional context**
Doesn't matter if I try to change the path, no matter what I enter I get the same error

**Comment by denis256** [comment]
Hi,
looks suspicious that the plan is saved in a file with `.tf` extension - terraform will try to load and apply all .tf files...

From Terraform documentation https://developer.hashicorp.com/terraform/cli/commands/plan :

> **Do not** name the file with a suffix that Terraform recognizes as another file format; if you use a .tf suffix then Terraform will try to interpret the file as a configuration source file, which will then cause syntax errors for subsequent commands.

I would suggest first to try different extension, like `.plan`
