### ISSUE TITLE
Terragrunt Hangs Waiting for User Input in CI if the Remote State Backend S3 Bucket is Not Accessible

### ISSUE THREAD

**Issue by X-Guardian** [gruntwork-io/terragrunt#2633]
**Describe the bug**

When using an AWS S3 remote state backend and running Terragrunt within a non-interactive CI process, if the S3 bucket is not accessible for some reason (wrong credentials/permissions, doesn't exist yet etc) the Terragrunt process will hang waiting for user input that can never be given, with the message:

```
Remote state S3 bucket <BucketName> does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
```

**Expected behavior**

Terragrunt should either detect that it is running within a CI environment (normally env var `CI` is set) or have another CLI option to not prompt to create the bucket, but just fail.

**Versions**

- Terragrunt version: v0.46.1
- Terraform version: v1.4.6

**Comment by denis256** [comment]
Hi,
Terragrunt was running with `--terragrunt-non-interactive` option?

**Comment by luizandrends** [comment]
Same problem here, we're currently running an atlantis pipeline, and the plan check just freezes because terragrunt still waits to press Y in the console. 

+1

**Comment by luizandrends** [comment]
hi @denis256, how are you doing? If we pass the --terragrunt-non-interactive flag, I get an error saying the bucket already exists, we previously have created the buckets in all AWS accounts.

**Comment by tkflexys** [comment]
Ran into something similar where in CI terragrunt would inconsistently prompt me when running destroy and hang, no combination of flags worked i.e `--terragrunt-non-interactive` or `--terragrunt-ignore-external-dependencies` even when set in environment variable format

```
Module /tmp/build/ee04e91f/terragrunt/clients/client/environments/dev/components/component depends on module /tmp/build/ee04e91f/terragrunt/client/bamboo/environments/dev/components/project, which is an external dependency outside of the current working directory. Should Terragrunt run this external dependency? Warning, if you say 'yes', Terragrunt will make changes in /tmp/build/ee04e91f/terragrunt/clients/client/environments/dev/components/project as well! (y/n) 
```


Ended up going with this hack 

```
echo "n" | terragrunt destroy . . .
```

**Comment by denis256** [comment]
I will look into

**Comment by denis256** [comment]
Added new CLI argument/environment variable in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.48.4

**Comment by X-Guardian** [comment]
Thanks for this @denis256. I think the description for the new `terragrunt-fail-on-state-bucket-creation` argument is not quite right though. It is currently:

> When this flag is set, Terragrunt will wait for execution if it is required to create the remote state bucket.

Where it should be something like:

> When this flag is set, Terragrunt will fail and exit if it is required to create the remote state bucket.
