### ISSUE TITLE
gob: encoded unsigned integer out of range error

### ISSUE THREAD

**Issue by jeffPOG** [gruntwork-io/terragrunt#2636]
I am currently trying to run a terraform project and I have been getting this weird output message anytime I do anything with terragrunt. For example

**To Reproduce**
When I run `terragrunt validate` on any of my terragrunt files I get the following:

```
    ERRO[0000] 1 error occurred:
        * error downloading 'file:///home/vagrant/iac/terraform': gob: encoded unsigned integer out of range
```
I'm not certain what the cause of this could be considering I am not running a golang application or file at all. 

While troubleshooting I did a `df -h` anf got the following:

 
```
    Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 4.0M     0  4.0M   0% /dev
tmpfs                    2.0G   84K  2.0G   1% /dev/shm
tmpfs                    781M  8.9M  772M   2% /run
/dev/mapper/fedora-root  125G   20G  106G  16% /
/dev/loop0               119M  119M     0 100% /var/lib/snapd/snap/core/15511
/dev/sda2                960M  243M  718M  26% /boot
/dev/loop1               119M  119M     0 100% /var/lib/snapd/snap/core/15419
/dev/loop2                37M   37M     0 100% /var/lib/snapd/snap/terragrunt/16
tmpfs                    391M   20K  391M   1% /run/user/1000
vagrant                  477G  198G  279G  42% /vagrant
```
majority of what I'm doing is under `/vagrant` but I wonder if the other filesystems that at capacity have anything to do with that.

**Versions**
- Terragrunt version: v0.48.1
- Terraform version: v1.5.3
- Linux: fedora .37

**Comment by denis256** [comment]
Hi,
can be shared full execution log with `--terragrunt-log-level debug` argument?
