### ISSUE TITLE
Generation of terraform files by terragrunt behaving differently in specific circumstance

### ISSUE THREAD

**Issue by hydridity** [gruntwork-io/terragrunt#2637]
Versions:
```
Terraform v1.5.2
on linux_amd64

terragrunt version v0.47.0
```

I've been working with this structure
```
.
├── dev-01
│   └── terragrunt.hcl
├── prod-01
│   └── terragrunt.hcl
├── test-01
│   └── terragrunt.hcl
├── module
│   ├── service-account-data.tf
│   ├── test.tf
│   └── variable.tf
└── terragrunt.hcl
```

Content of root terragrunt.hcl file:
```
remote_state {
    backend = "http"
    generate = {
        path = "backend.tf"
        if_exists = "overwrite_terragrunt"
    }
    config = {
        address = "gitlab.example.com/${path_relative_to_include()}-unit"
        lock_address = "gitlab.example.com/${path_relative_to_include()}-unit/lock"
        unlock_address = "gitlab.example.com/${path_relative_to_include()}-unit/lock"
        lock_method = "POST"
        unlock_method = "DELETE"
        retry_wait_min = 5
    }
}

generate "provider" {
    path = "provider.tf"
    if_exists = "overwrite_terragrunt"
    contents = <<EOF
    provider "kubernetes" {
        insecure = true
        host = "https://${path_relative_to_include()}.example.com"
        token = "${run_cmd("${get_parent_terragrunt_dir("root")}/token/custom_k8s_login.script")}"
    }
    EOF
}

skip = true
```

Content of terragrunt.hcl file in every environment:
```
include "root" {
  path = find_in_parent_folders()
}
```

### First circumstance

At this point if i run `terragrunt run-all plan` or `terragrunt run-all init -reconfigure -backend-config="username=[nice username]" -backend-config=password=[REDACTED]` at the root, nothing happens.
So let's cd into the dev-01 folder and run:
`terragrunt init -reconfigure -backend-config="username=[nice username]" -backend-config=password=[REDACTED]`

Terragrunt has generated backend.tf and provider.tf   and properly filled all the variables defined in generate block and remote state

The folder structure at this point looks:
```
.
├── dev-01
│   ├── backend.tf
│   ├── provider.tf
│   ├── .terraform
│   │   ├── providers
│   │   │   └── registry.terraform.io / hashicorp / kubernetes / 2.22.0 / linux_amd64 / terraform-provider-kubernetes_v2.22.0_x5 
│   │   └── terraform.tfstate
│   ├── .terraform.lock.hcl
│   └── terragrunt.hcl
├── prod-01
│   └── terragrunt.hcl
├── test-01
│   └── terragrunt.hcl
├── module
│   ├── service-account-data.tf
│   ├── test.tf
│   └── variable.tf
└── terragrunt.hcl
```

We can go back to root and do `terragrunt run-all plan`, terragrunt will execute plan for this specific dev-01 folder, no other folder

### Circumstance 2

If we begin on the green field again - meaning the artifacts from previous example were removed, uninitialized,no cache folder and all the folders /  sub modules have only terragrunt.hcl file in them
But this time the content of every submodule terragrunt.hcl file is:
 ```
 include "root" {
  path = find_in_parent_folders()
}

terraform {
  source = "../module"
}
```

In the root if I execute: `terragrunt run-all init -reconfigure -backend-config="username=[nice username]" -backend-config=password=[REDACTED]`

Terragrunt initializes every folder and generated content is structured in:

```
.
├─ dev-01
│   ├── .terraform.lock.hcl
│   ├── .terragrunt-cache
│   │   └── Vn0DcbOoNEPSCtqIesOPMAlEQLE
│   │       └── e0BzW-Gao3lSbvfPpEyE9n2O504
│   │           ├── backend.tf
│   │           ├── provider.tf
│   │           ├── service-account-data.tf
│   │           ├── .terraform
│   │           │   └── registry.terraform.io / hashicorp / kubernetes / 2.22.0 / linux_amd64 / terraform-provider-kubernetes_v2.22.0_x5
│   │           │   └── terraform.tfstate
│   │           ├── .terraform.lock.hcl
│   │           ├── terragrunt.hcl
│   │           ├── .terragrunt-init-required
│   │           ├── .terragrunt-module-manifest
│   │           ├── .terragrunt-source-manifest
│   │           ├── .terragrunt-source-version
│   │           ├── test.tf
│   │           └── variable.tf
│   └── terragrunt.hcl
├── prod-01
│   ├── .terraform.lock.hcl
│   ├── .terragrunt-cache
│   │   └── wMufjO8aAtdI9gZvbbkIIfHZprI
│   │       └── e0BzW-Gao3lSbvfPpEyE9n2O504
│   │           ├── backend.tf
│   │           ├── provider.tf
│   │           ├── service-account-data.tf
│   │           ├── .terraform
│   │           │   └── registry.terraform.io / hashicorp / kubernetes / 2.22.0 / linux_amd64 / terraform-provider-kubernetes_v2.22.0_x5
│   │           │   └── terraform.tfstate
│   │           ├── .terraform.lock.hcl
│   │           ├── terragrunt.hcl
│   │           ├── .terragrunt-init-required
│   │           ├── .terragrunt-module-manifest
│   │           ├── .terragrunt-source-manifest
│   │           ├── .terragrunt-source-version
│   │           ├── test.tf
│   │           └── variable.tf
│   └── terragrunt.hcl
├── test-01
│   ├── .terraform.lock.hcl
│   ├── .terragrunt-cache
│   │   └── DLCkqhsrqr55-DhTkMXvF8Ez9i4
│   │       └── e0BzW-Gao3lSbvfPpEyE9n2O504
│   │           ├── backend.tf
│   │           ├── provider.tf
│   │           ├── service-account-data.tf
│   │           ├── .terraform
│   │           │   └── registry.terraform.io / hashicorp / kubernetes / 2.22.0 / linux_amd64 / terraform-provider-kubernetes_v2.22.0_x5
│   │           │   └── terraform.tfstate
│   │           ├── .terraform.lock.hcl
│   │           ├── terragrunt.hcl
│   │           ├── .terragrunt-init-required
│   │           ├── .terragrunt-module-manifest
│   │           ├── .terragrunt-source-manifest
│   │           ├── .terragrunt-source-version
│   │           ├── test.tf
│   │           └── variable.tf
│   └── terragrunt.hcl
```

Files generated in example 1, are now located inside .terragrunt-cache, instead of working directory of submodule like in the example 1

I haven't been able to find anything related to this behavior in the terragrunt documentation.
I have git repository configured to ignore .terragrunt and .terragrunt-cache.
**Which of those patterns is the "right" one ? 
Should I expect terragrunt to generate provider.tf and backend.tf in the working directory for submodules and commit them to git after generation, or should the git repository contain only terragrunt.hcl files, and let terragrunt generate and store those files in the cache folder for every runtime environment (local, CI/CD runners ...)?**

What I'm trying to achieve using this structure is that I'll be configuring service in different stages (dev, test, prod), all stages will have most things common, but test might have unique resources that are not present in prod or dev.

For example:
When configuring Hashicorp Vault using terraform, I'll have vault in each stage, all stages will have common settings for KV Engine, auth backend for OIDC, **some** common ACL policies stored in the module folder, included in that terraform block via source
And then test will have some unique ACL policies, different from prod

**I assume that for the unique ones, I can create them as regular terraform files inside each environement folder/submodule.
Or do I completely misunderstood terraform block, and should use dependencies instead ?**

**Comment by denis256** [comment]
Hi,
it depends if `terraform.source` block is defined - to have consistent behavior can be defined:
```
...
terraform {
  ...
  source = "."
}
...
```

and will be created `.terragrunt-cache` directory in case 1

**Comment by thnee** [comment]
I am not OP, but thanks for that, it works great.

Nice to finally have a solution for something that has been bothering me for years. :) I guess this was always possible?
