### ISSUE TITLE
Missing required GCS remote state configuration prefix

### ISSUE THREAD

**Issue by alexey-pelykh** [gruntwork-io/terragrunt#2651]
**Describe the bug**
```
Missing required GCS remote state configuration prefix
```

is thrown for a GCS configuration argument that is optional upstream.

**To Reproduce**

Try to apply the following configuration

```hcl
remote_state {
  backend = "gcs"

  generate = {
    path = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    project  = "my-project"
    bucket   = "terraform-state"
    location = "US-CENTRAL1"
  }
}
```

**Expected behavior**
[`prefix`](https://developer.hashicorp.com/terraform/language/settings/backends/gcs#prefix) is optional, therefore no error should occur.

**Versions**
- Terragrunt version: `terragrunt version v0.48.5`
- Terraform version: `Terraform v1.5.4`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `Darwin Alexeys-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64`

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.10
