### ISSUE TITLE
Impact of New HashiCorp License Announcement

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terragrunt#2658]
Gruntwork co-founder here. We've just learned that [HashiCorp will be adopting a Business Source License](https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license) on all its products going forward. We're reviewing the implications of this in https://github.com/orgs/gruntwork-io/discussions/759.

**Comment by josh-padnick** [comment]
Relevant discussion: https://github.com/gruntwork-io/terragrunt/issues/2662

**Comment by josh-padnick** [comment]
Update: We've published an initial blog post on this at https://gruntwork-community.slack.com/archives/CHH9Y3Z62/p1692041532364679.

**Comment by michelzanini** [comment]
> Update: We've published an initial blog post on this at https://gruntwork-community.slack.com/archives/CHH9Y3Z62/p1692041532364679.

I cant seem to open that in Slack, would tou be able to copy that here or provide another link?

Thanks.

**Comment by josh-padnick** [comment]
Ah, that was my bad. Link fixed now. Sorry about that!

**Comment by josh-padnick** [comment]
**Update: Gruntwork supports a vendor-neutral, community-driven, truly open source Terraform, which we are pledging support to as part of [OpenTF](https://opentf.org/).** 

Going forward, Terragrunt will support OpenTF. If HashiCorp reverts their license change, we'll re-evaluate the best approach for the Terragrunt community.

See also our recent blog post: [The future of Terraform must be open](https://blog.gruntwork.io/the-future-of-terraform-must-be-open-ab0b9ba65bca)
