### ISSUE TITLE
Latest Release Missing Binaries

### ISSUE THREAD

**Issue by ryan-royals** [gruntwork-io/terragrunt#2666]
**Describe the bug**
Latest release 0.50.0 has no binaries on the GH Releases Page under Assets.
Can we confirm if this was intentional?

**Comment by menahemo** [comment]
Yeah I am also facing the same issue.

`tgenv install latest
[0;32m[INFO] Installing Terragrunt v0.50.0[0;39m
[0;32m[INFO] Downloading release tarball from [https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.0/terragrunt_linux_amd64[0;39m](https://github.com/gruntwork-io/terragrunt/releases/download/v0.50.0/terragrunt_linux_amd64%1B[0;39m)
curl: (22) The requested URL returned error: 404

tgenv: tgenv-install: [0;31m[ERROR] Tarball download failed[0;39m`

**Comment by denis256** [comment]
Hello,
yes, it is an issue with the CICD pipeline, looking to fix it

**Comment by no-vac** [comment]
missing binaries again for 0.50.1
