### ISSUE TITLE
.terragrunt-null-vars.auto.tfvars.json created for no reason

### ISSUE THREAD

**Issue by grimm26** [gruntwork-io/terragrunt#2669]
**Describe the bug**
.terragrunt-null-vars.auto.tfvars.json is created containing `{}` for no reason.

**To Reproduce**
Use terragrunt with no input blocks.

**Expected behavior**
Don't create this useless file.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: v0.50.1
- Terraform version: 1.5.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): ubuntu 22.04

**Comment by Yunsang-Jeong** [comment]
I have the same problem on mac(darwin_arm64).
- Terraform v1.5.2
- Terragrunt 0.50.3

**Comment by ellisonc** [comment]
I suspect there's an issue in the logic added during this PR: [Null Fix](https://github.com/gruntwork-io/terragrunt/pull/2663) @denis256 do you have time to take a look?
