### ISSUE TITLE
[Feature Request] Provide way to check whether terragrunt is called by terragrunt

### ISSUE THREAD

**Issue by juljaeg** [gruntwork-io/terragrunt#2674]
**Describe the solution you'd like**

I'd like to have a function or variable enabling me to distinguish whether the current terragrunt execution was initiated by another terragrunt run. This is e.g. the scenario when you reference another directory containing a terragrunt.hcl in a dependency block. A way to handle those scenarios would be beneficial when e.g. another state would need be addressed when fetching outputs using the dependency block.

**Describe alternatives you've considered**

We distinguish states partly by using environment variables where we would have 60+ directories (each environment) for 30+ teams. This does work quite well except when a dependency block is used and a state file should be referenced which is not addressable using the environment variables.

We evaluated mirroring the state address components in the directory structure, but yielded this will become unmaintainable with growing number of teams and environments. Where also environments come and go which would mean deleting directories across 30+ teams.

**Additional context**

I see two possible ways to address this:

1. Have a function e.g. `is_silent_run_by_terragrunt` which enables me to detect this scenario. Optionally this may be extended to also contain the operation e.g. `output` to further distinguish. Of course scenarios like run-all make this a bit hard to define when this function will return what value as run-all also runs terragrunt in a subdirectory.
2. Being able to attach environment variables in the dependency block which can be read in the other terragrunt configuration using `get_env`. This solution seems a bit more flexible to me.

What do you think?

**Comment by denis256** [comment]
Hello,
Normally, Terragrunt does not invoke Terragrunt again (unless it's invoked through the `run_cmd` feature). 
Most probably, the intention is to determine if the HCL file is included from another location.

**Comment by juljaeg** [comment]
Hi, thanks for the response. 😄 Not sure whether it is really calling terragrunt internally. When the path used in a dependeny block in a configuration (root hcl) contains also a terragrunt.hcl (sibling hcl): how is it handled to get the outputs? Does it read the sibling hcl natively and process it?

I am assuming parent and sibling hcl's generate a different state backend configuration. If it does that, I agree. What I mean is: there is no technical include represented using a include block. Just a dependency block.

**Comment by hypervtechnics** [comment]
> Most probably, the intention is to determine if the HCL file is included from another location.

The more I think of it, I think by included you mean the dependency block path attribute. If this would be covered as well it would be quite nice because that would also cover scenarios where optimization takes place (saw some in the code).

**Comment by juljaeg** [comment]
@denis256 Can we support in the further process somehow? Do we need to supply a RFC (design?)? We can also help by implementing.

**Comment by juljaeg** [comment]
I drafted something at https://github.com/gruntwork-io/terragrunt/pull/2759 but could not get some parts to work. Sorry for the rough code :D
