### ISSUE TITLE
How does Terragrunt provider locking work

### ISSUE THREAD

**Issue by dlewis152** [gruntwork-io/terragrunt#2675]
**Describe the bug**
We are having issues with provider locking between our local machines and our remote docker container that runs on circleci. This is more a request for advice how the Terragrunt provider locking works, and trying to isolate this down to terragrunt or terraform, and most likely where our setup is incorrect. 

I am a little confused as to where, the various things are downloaded too and cached. 

**To Reproduce**
I have a terragrunt module which consists of the hcl file as well as the .terraform.lock.hcl.

```
infra/vpc/terragurnt.hcl
infra/vpc/.terraform.lock.hcl
```

I generated the lock file by running 

```
terragrunt providers lock \
    -platform=windows_amd64 \
    -platform=darwin_amd64 \
    -platform=linux_amd64 \
    -platform=linux_arm64
```

so it should be cross platform compatible. These files are committed to source control. 

I can run `terragrunt plan`, `terragrunt apply`, `terragrunt init` etc locally without issue. 

We run all apply commands on a circleci machine. 

The commands run are: 

`terragrunt init --upgrade  --terragrunt-download-dir /root/.terragrunt_cache;`

`terragrunt apply -auto-approve  --terragrunt-download-dir /root/.terragrunt_cache;`

When this is run we get an error

```
Error: Required plugins are not installed
│ 
│ The installed provider plugins are not consistent with the packages
│ selected in the dependency lock file:
│   - registry.terraform.io/hashicorp/null: there is no package for registry.terraform.io/hashicorp/null 3.2.1 cached in .terraform/providers
│ 
│ Terraform uses external plugins to integrate with a variety of different
│ infrastructure services. To download the plugins required for this
│ configuration, run:
│   terraform init
```

On our circleci, we have  `os.environ["TF_PLUGIN_CACHE_DIR"] = os.path.abspath('./.plugins')` set and the ` .terragrunt_cache` is persistent through the circleci runs. 

I'd have expected the providers to be downloaded into the `.terragrunt_cache` directory according to https://developer.hashicorp.com/terraform/cli/config/config-file#provider-plugin-cache but it look  like it's in `.terraform/providers` according to the error message above. 

**Expected behavior**
Terragrunt commands run successfully on all machines. 

**Versions**
- Terragrunt version: 0.48.1
- Terraform version: 1.5.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): Local Mac Ventura, remote Ubuntu 22.04

**Comment by denis256** [comment]
Hi,
was attempted to define hooks to lock providers to specific OS?

Reference:

https://github.com/gruntwork-io/terragrunt/issues/2584#issuecomment-1569022915

**Comment by dlewis152** [comment]
Thanks for that, looks like it's the same issue. 

I'm still a bit confused as to how it all works. Am I right in saying there are two terraform.lock.hcl files, one which is in source control, and one in the .terragrunt-cache. 

If I run any commands on the remote before committing the lock file, it will have it's own set of hashes, and could be running different versions. Then when I commit the lock file beside the .hcl files, the two lock files basically conflict? 

I would have thought running 

```
terragrunt providers lock \
    -platform=windows_amd64 \
    -platform=darwin_amd64 \
    -platform=linux_amd64 \
    -platform=linux_arm64
```

should make it cross-platform compatible.

**Comment by dlewis152** [comment]
Removing `os.environ["TF_PLUGIN_CACHE_DIR"] = os.path.abspath('./.plugins')` fixed the issue
