### ISSUE TITLE
Show sub-directory name in logs when running on multiple directories at once

### ISSUE THREAD

**Issue by daftkid** [gruntwork-io/terragrunt#2677]
**Describe the solution you'd like**
If I run `terragrunt run-all` within the directory with sub-directories (layers), terragrunt show logs all together and it's hard to understand which layer a particular log belongs to. For example, I have 10 sub-directories, run `terragrunt run-all plan`, and only one directory shows some diff, there are no ways to understand which directory actually has some drift (well, I can see the list of resources and their names in the plan output, but that's not a very convenient way to determine which directory is drifted).

I'd like to have some option to show directory names for each log entry generated by terragrunt.

I was not able to find any options to show me logs in the way I need, thus I created this feature request

**Describe alternatives you've considered**

**Additional context**

**Comment by denis256** [comment]
Hi,
was attempted to use `--terragrunt-include-module-prefix`? 

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-module-prefix

**Comment by daftkid** [comment]
> Hi, was attempted to use `--terragrunt-include-module-prefix`?
> 
> https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-module-prefix

Hi, did not see this option for some reason...
Yeah, it did the trick but now output is kind of a mess, EACH line is prepended with the full path to the directory, even each plan line. Any chances to get it grouped? I mean, for example, show the directory path only for the first line of the plan output.
