### ISSUE TITLE
embedded tflint doesn't pick --config (nor --terragrunt-external-tflint) if .tflint.hcl not where expected

### ISSUE THREAD

**Issue by joaocc** [gruntwork-io/terragrunt#2678]
**Describe the bug**
According to the documentation, we should be able to specify an .tflint.hcl file via "tflint --config".

However, with embedded tflint, this will never work: RunTflintWithOpts (https://github.com/gruntwork-io/terragrunt/blob/master/tflint/tflint.go#L31) starts by trying to find ".tflint.hcl", and it aborts if it can't.

**Expected behavior**
RunTflintWithOpts should first parse "--terragrunt-external-tflint".
If it is specified, the recursive search in parent folders should be skipped.

Also, "--config" from CLI is ignored. It should be detected and, if present, the recursive search in parent folders should be skipped.
Currently, "--config" is always passed with the detected file, which means the ones specified in the hook are simply ignored.

**Versions**
- Terragrunt version: v0.50.4 and before

**Additional context**
May be the underlying cause of https://github.com/gruntwork-io/terragrunt/issues/2471

**Comment by denis256** [comment]
Added handling of `--config` parameter in release https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.8
