### ISSUE TITLE
Terragrunt (0.50.6) does not handle Service Account impersonation in GCP, defaulting to the caller Service account

### ISSUE THREAD

**Issue by dsiguero** [gruntwork-io/terragrunt#2680]
**Describe the bug**
Terragrunt doesn't target the right GCP Service account when using Service Account impersonation.

```
Remote state GCS bucket ProjectPrivBucket does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) time=2023-08-22T11:06:51Z level=error msg=Error: Error in function call
[...]
time=2023-08-22T11:06:51Z level=error msg=Call to function "read_terragrunt_config" failed: googleapi: Error 403: SA-Caller@ProjectCaller.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist)., forbidden.
```

`SA-Caller` Service account should not be used, as there is an impersonated Service account in the environment/workspace (correctly used by `gcloud` commands).

**To Reproduce**
1. Create `SA-Caller` in `ProjectCaller`.
2. Create `SA-Priv` in `ProjectPriv`. Give it the Editor role.
3. Give `SA-Caller` the `roles/iam.serviceAccountTokenCreator` role on `SA-Priv`.
4. Auth into `ProjectCaller`, using the `SA-Caller` SA and the Github action `google-github-actions/auth@v1` setting `export_environment_variables` to `false`.
5. Run the following commands (in the Github action workflow):
```
# credentials_file_path is an output from `google-github-actions/auth@v1`
gcloud auth login --cred-file=${{ steps.auth.outputs.credentials_file_path }} --update-adc
gcloud config set auth/impersonate_service_account "SA-Priv@ProjectPriv.iam.gserviceaccount.com"
export GOOGLE_IMPERSONATE_SERVICE_ACCOUNT="SA-Priv@ProjectPriv.iam.gserviceaccount.com"
gcloud config set project ProjectPriv
          
gcloud alpha storage ls
echo "n" | terragrunt run-all init
```

**Expected behavior**
`gcloud alpha storage ls` and `terragrunt run-all init` should not fail.

The former should display a list of all the buckets in `ProjectPriv` (as it does) without requiring any extra gcloud flags, such as `--impersonate-service-account` or `--project`.

The latter should target `ProjectPriv` using the `SA-Priv` Service account (impersonated) and run `init` against all folders/stacks/components.

**Nice to have**
`gcloud config list` output:
```
[auth]
Your active configuration is: [default]
impersonate_service_account = SA-Priv@ProjectPriv.iam.gserviceaccount.com
[core]
account = SA-Caller@ProjectCaller.iam.gserviceaccount.com
disable_usage_reporting = True
project = ProjectPriv
```

**Versions**
- Terragrunt version: `0.50.6`
- Terraform version: `1.3.5`
- Environment details: Github actions runner, `ubuntu-latest`

**Additional context**
Looking at a recent PR (#2679) it seems like `impersonate_service_account` might be required as part of the `remote_state` block for the `gcs` backend. 

Is that the case? If so, Terragrunt is able to retrieve the right Google credentials from the workspace, how come it can't get the details about the impersonated SA, and they have to be explicitly passed to the remote state?

Is this a Terraform limitation? I can see [TF gcs backend docs](https://developer.hashicorp.com/terraform/language/settings/backends/gcs#impersonate_service_account) mention `impersonate_service_account` as well as 2 extra environment variables: `GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT` and `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT`. But Terragrunt still fails even when setting the `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT` env var, which is meant to be equivalent to setting `impersonate_service_account`?

**Comment by denis256** [comment]
Hello,
mentioned issue is happening in Terragrunt version 0.50.5?

**Comment by dsiguero** [comment]
Hi @denis256,

It's happening in both `0.50.6` and `0.50.5` (just verified that). Also in `0.46.2` which was the version I was running before upgrading to `0.50.6` (to take advantage of the new impersonation fixes).

**Comment by levkohimins** [comment]
This issue was mistakenly mentioned in the pull request #2697. In fact, the issue is not resolved, so reopen.

**Comment by boekkooi-lengoo** [comment]
For anyone finding this setting `disable_init` to `true` in [remote_state](https://github.com/gruntwork-io/terragrunt/blob/409185b47fb759180ba466a7f5d24b6118654ae1/docs/_docs/04_reference/config-blocks-and-attributes.md#remote_state) seems to resolve this issue.

**Comment by choznerol** [comment]
> <i> I can see [TF gcs backend docs](https://developer.hashicorp.com/terraform/language/settings/backends/gcs#impersonate_service_account) mention impersonate_service_account as well as 2 extra environment variables: `GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT` and `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT`. </i>

I tried all three approaches, and surprisingly only `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT` worked for me.

No effect with `impersonate_service_account` either or `GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT`:
```console
$ TF_LOG=trace GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT=mysa@myproject.iam.gserviceaccount.com terragrunt run-all plan`
17:14:44.452 INFO   [us-west1/gar] terraform: TF_LOG: provider.terraform-provider-google_v5.3.0_x5: ... 
  ... Terraform is using this identity: myaccount@myorg.com: ... 
  ... tf_req_id=0bcb6714-30c7-460e-8caf-193531b854f0 tf_rpc=ConfigureProvider tf_provider_addr=registry.terraform.io/hashicorp/google @module=google tf_mux_provider=*proto5server.Server @caller=github.com/hashicorp/terraform-provider-google/google/fwtransport/framework_config.go:1507 timestamp=2024-11-05T17:14:44.452+0800
```

Working with `GOOGLE_IMPERSONATE_SERVICE_ACCOUNT`:
```console
$ TF_LOG=trace GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=mysa@myproject.iam.gserviceaccount.com terragrunt run-all plan`
17:15:08.689 INFO   [us-west1/gar] terraform: TF_LOG: provider.terraform-provider-google_v5.3.0_x5: ...
  ... Terraform is configured with service account impersonation, original identity: myaccount@myorg.com, impersonated identity: mysa@myproject.iam.gserviceaccount.com: ...
  ... @caller=github.com/hashicorp/terraform-provider-google/google/fwtransport/framework_config.go:1523 @module=google tf_mux_provider=*proto5server.Server tf_req_id=5097150e-78b2-18af-fcdd-4e760510ea87 tf_rpc=ConfigureProvider tf_provider_addr=registry.terraform.io/hashicorp/google timestamp=2024-11-05T17:15:08.689+0800
```

<details><summary> versions: </summary>

terragrunt: 0.68.4
terraform: v1.2.7 (darwin_arm64)

</details>

Both envvar will probably work if you use Terraform >= 1.5.0. See https://github.com/hashicorp/terraform/commit/05ff3c3278ab55aba9250819dc41161078ac2d74#diff-30809c63712017e2f6010d7ca024c82251b4fa328ef39901587c1d8fd38e5290L116
