### ISSUE TITLE
Terragrunt combine plan.json file

### ISSUE THREAD

**Issue by vinodkumar4b9** [gruntwork-io/terragrunt#2681]
**Describe the bug**
If you look at the repo structure regarding the url https://github.com/NanditaSahu03/terragrunt-dependencies-and-terraform-checks/tree/main, It has four modules ec2, iam, security group, iam instance profile. 

**To Reproduce**
When i clone the above repository and run Terragrunt run-all plan -out tf.json it actually creates a tf.plan in terragrunt-cache in the respective module.

**Expected behavior**
When i clone the above repository and run Terragrunt run-all plan -out tf.json it actually creates a tf.plan in terragrunt-cache in the respective module.

**Nice to have**
Is there a way that I can generate a combine plan-all output file so that all the four modules can be incorporated into single tf.json file ?

**Comment by denis256** [comment]
Hello,
AFAIK, can be used hooks to copy plan file in the right location, but combining files usually don't lead to something meaningful for future use

https://terragrunt.gruntwork.io/docs/features/hooks/

**Comment by vinodkumar4b9** [comment]
Hi @denis256 ,

I just want to combine all plan files to run only checkov scan , not to perform Terragrunt apply using the combined plan. Is there any way where we can get this done ?

**Comment by denis256** [comment]
Hi,
I was thinking about using jq/find to combine files... 
Like:
```
 find . -name 'plan.json' -exec cat {} \; | jq -s '.' > combined.json
```
