### ISSUE TITLE
`terragrunt output-module-groups` fails if not run from a Terragrunt module

### ISSUE THREAD

**Issue by Mike-Nahmias** [gruntwork-io/terragrunt#2685]
**Describe the bug**
The description of `output-module-groups` says:

> This will recursively search the current working directory for any folders that contain Terragrunt modules and build the dependency graph based on dependency and dependencies blocks.

However, if I run `terragrunt output-module-groups` from the root of my repo, the command fails. I do not have a terragrunt.hcl at root, as all Terragrunt modules are organized within my repo. Here's an example of my layout:

```
- root
  - aws
    - aws.hcl (shared config for all AWS Terragrunt modules)
    - commercial
      - account1
        - terragrunt.hcl
        - test.tfvars
      - account2
        - terragrunt.hcl
        - test.tfvars
        - submodule
          - terragrunt.hcl
          - test.tfvars
  - azure
    - azure.hcl (shared config for all Azure Terragrunt modules)
    - ...
```

Here's the error I'm getting:
```
$ terragrunt output-module-groups
ERRO[0000] Error reading file at path /terragrunt_test/terragrunt.hcl: open /terragrunt_test/terragrunt.hcl: no such file or directory
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**To Reproduce**
Attempt to run `terragrunt output-module-groups` from a a directory that contains Terragrunt modules in subfolders, but is not a Terragrunt module itself.

**Expected behavior**
I would expect this command to recursively search the current directory for all Terragrunt modules and build the dependency graph, even if there is no terragrunt.hcl in the current dir.

**Workaround**
As a workaround, you can create an empty terragrunt.hcl in the root directory to get it to recursively search for all Terragrunt modules.

**Versions**
- Terragrunt version: v0.50.6
- Terraform version: v1.5.4
- Environment details (Ubuntu 20.04, Windows 10, etc.): Rocky Linux 8

**Comment by ehab-eb** [comment]
I'm also running into this bug (or misdocumentation?) with the latest terragrunt version (0.51.6)

**Comment by denis256** [comment]
Included in release: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.52.6
