### ISSUE TITLE
Expand the set of built-in functions

### ISSUE THREAD

**Issue by levkohimins** [gruntwork-io/terragrunt#2687]
According to [ticket](https://gruntwork.zendesk.com/agent/tickets/110393), we need to add two new built-in functions:
1. `get_cache_dir()` - returns path to terragurnt cache directory
2. `get_terraform_output()` - returns terraform output, which can later be passed to the script in hooks

**Comment by mirconstantin** [comment]
Please prioritise this issue as i tis important to add this feature request. Also, ensure that you are going to communicate the release number of terrarrunt application which will support get_cache_dir() and get_terraform_output() which will be passed to the script from the hooks.

**Comment by levkohimins** [comment]
@mirconstantin We will do our best to make the development of these built-in functions as fast as possible. As soon as we're done, I'll be sure to let you know the version containing these improvements.

**Comment by levkohimins** [comment]
After analyzing the issue, it became clear that this functionality is not needed. I close the question.
