### ISSUE TITLE
Add OpenTofu support

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#2690]
**Describe the solution you'd like**
[As recently announced](https://opentofu.org/blog/the-opentofu-fork-is-now-available), the OpenTofu fork should drop soon. We should make sure that Terragrunt supports it out of the box. 

Here's an idea for an initial implementation: anywhere Terragrunt calls out to the `terraform` binary, we should update it to check for the `terraform` binary first; if that's not found, then try the `tofu` binary; and if that's not found, show an error (as we do today). Whatever we pick, we should mention in the debug log.

**Describe alternatives you've considered**
In theory, you can already use OpenTofu by using the [`terraform_binary`  config](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_binary) or `--terragrunt-tfpath` CLI flag or `TERRAGRUNT_TFPATH` env var, but those all require extra steps, whereas I'd like OpenTofu to "just work" with Terragrunt. 

**Additional context**
OpenTofu should work as a "drop in" replacement for Terraform, so in theory, no other changes should be necessary. However, we should run our tests to make sure once the `tofu` binary is available for testing. One place where OpenTofu will differ is `stdout` and `stderr` output will say OpenTofu instead of Terraform; if Terragrunt is parsing that log output anywhere, we'll need to update the code accordingly.

This is just the initial implementation in the sense that it should be backward compatible. In the future, we can reverse the lookup order, and perhaps even drop support for `terraform`, but those would be significant breaking changes (especially the latter), so we'd want to see how things go with OpenTofu and what the community wants first.

**Note on registry usage**
HashiCorp recently did an update (one that was totally unannounced, BTW) to its [Registry terms](https://registry.terraform.io/terms) to say:

> You may download providers, modules, policy libraries and/or other Services or Content from this website solely for use with, or in support of, HashiCorp Terraform.

Terragrunt uses go-getter to download modules specified in the `source` URL, and it's possible that URL points to the Terraform Registry. For now, Terragrunt only works with Terraform, so that is still inline with the terms. If we add support for OpenTofu, then in theory, anyone using Terragrunt with OpenTofu might be violating the registry terms.

Possible solutions:

1. Cheapest/fastest: If we detect a registry `source` URL and `tofu` as the binary, give the user a warning.
2. Better solution: If we detect a registry `source` URL and `tofu` as the binary, automatically use OpenTofu's registry (coming soon) instead of HashiCorp's.

**Comment by skyzyx** [comment]
From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by skyzyx** [comment]
Came across this comment last night.

https://www.linkedin.com/feed/update/urn:li:ugcPost:7102220371797389313?commentUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7102220371797389313%2C7102263805740503040%29&replyUrn=urn%3Ali%3Acomment%3A%28ugcPost%3A7102220371797389313%2C7102264759957213184%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287102263805740503040%2Curn%3Ali%3AugcPost%3A7102220371797389313%29&dashReplyUrn=urn%3Ali%3Afsd_comment%3A%287102264759957213184%2Curn%3Ali%3AugcPost%3A7102220371797389313%29

**Comment by brikis98** [comment]
I just updated the issue description with:


**Note on registry usage**
HashiCorp recently did an update (one that was totally unannounced, BTW) to its [Registry terms](https://registry.terraform.io/terms) to say:

> You may download providers, modules, policy libraries and/or other Services or Content from this website solely for use with, or in support of, HashiCorp Terraform.

Terragrunt uses go-getter to download modules specified in the `source` URL, and it's possible that URL points to the Terraform Registry. For now, Terragrunt only works with Terraform, so that is still inline with the terms. If we add support for OpenTF, then in theory, anyone using Terragrunt with OpenTF might be violating the registry terms.

Possible solutions:

1. Cheapest/fastest: If we detect a registry `source` URL and `opentf` as the binary, give the user a warning.
2. Better solution: If we detect a registry `source` URL and `opentf` as the binary, automatically use OpenTF's registry (coming soon) instead of HashiCorp's.

**Comment by brikis98** [comment]
> From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])
> 
> From a process perspective:
> 
> 1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

Yup. Until otherwise announced, we should support both platforms equally.

> 2. Will testing be performed with code targeting both platforms?

Yes, we should test both platforms. 

> 3. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

Probably, but hard to say until we know what that functionality is. I think we'll have to decide on a case by case basis, with input from the community.

**Comment by skyzyx** [comment]
Your response is greatly appreciated.

This whole situation has created uncertainty at a time when we could really do without it. My company leverages several open-source and SaaS offerings in the Terraform ecosystem, and I've been reaching out across the ecosystem to understand where everyone is on this topic, and identifying what we need to watch out for.

Hoping for the very best from this whole situation, but planning ahead for the absolute worst.

**Comment by RobertKosten** [comment]
I've been using the unofficial dev snap [OpenTF v1.6.0-dev](https://github.com/jnsgruk/opentf-snap), but even with `--terragrunt-tfpath` set to `/snap/bin/opentf` I get an error: `Unable to parse Terraform version output: OpenTF v1.6.0-dev on linux_amd64`. I'd say parsing that was *bound* to be brittle :-P

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.52.0
