### ISSUE TITLE
Help with interpolation

### ISSUE THREAD

**Issue by citrusoft** [gruntwork-io/terragrunt#2692]
Here is the error...
**$ terragrunt plan
ERRO[0000] /Users/TAHV/git/aws-lz-iam/gen-tfc/terragrunt.hcl:83,32-46: Invalid template interpolation value; Cannot include the given value in a string template: string required., and 3 other diagnostic(s) 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1**

So I am trying to create AWS IAM users and their policies across accounts and am having difficulty finding a technique aligned with terragrunt features.
In terragrunt.hcl.locals, I build a data-structure that looks like this...
`
  - user_specs_by_acct                  = {
      - "012345678901" = {
          - name       = "Dev-Account1"
          - user_specs = {
              - "test_resources/012345678901/service-accounts/SVC-DEV-Ops.yaml" = {
                  - ManagedPolicyArns = [
                      - "arn:aws:iam::aws:policy/SecurityAudit",
                    ]
                  - Name              = "DEV-Ops"
                  - Statement         = [
                      - {
                          - Action   = [
                              - "s3:*",
                            ]
                          - Effect   = "Allow"
                          - Resource = [
                              - "arn:aws:s3:::audit-backup",
                              - "arn:aws:s3:::audit-backup/*",
                            ]
                          - Sid      = "AllS3Actions"
                        },
                    ]
                }
            }
        }
      - "123456789012" = {
          - name       = "Dev-Account2"
          - user_specs = {
              - "test_resources/123456789012/service-accounts/SVC-Auditor.yaml" = {
                  - ManagedPolicyArns = [
                      - "arn:aws:iam::aws:policy/SecurityAudit",
                    ]
                  - Name              = "SVC-PROD-Auditor"
                }
            }
        }...
   }
`

AND, I am trying to create user, attach inline policies...
I am failing to figure out how to populate the variable, aws_iam_user_policy.policy, below.
Specifically, as you can see above, "Statement" is an array of maps, however, policy requires a string.
And my coded solution is in ERROR.
`
generate "service-accounts" {
  path      = "service-accounts.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
%{for number, account in local.user_specs_by_acct}
%{for file, spec in account.user_specs}
resource "aws_iam_user" "user-${spec.Name}" {
  provider = aws.${account.name}
  name     = "${spec.Name}"
  permissions_boundary  = aws_iam_policy.perms-boundary-policy-${account.name}.arn
}
resource "aws_iam_user_policy" "policy-inline-${spec.Name}" {
  provider = aws.${account.name}
  name     = "policy-inline-${spec.Name}"

  policy   = {
    "Version" : "2012-10-17",
    "Statement" : jsonencode(${spec.Statement})
  }
  user     = "${spec.Name}"
}
...
`
I don't understand;  What am I doing wrong?
Can someone suggest solution(s) to convert that "Statement" list into a JSON string ?
Thank you.

**Comment by denis256** [comment]
Hello,
will be helpful to provide an example of failing to resolve variable
