### ISSUE TITLE
terragrunt-use-partial-parse-config-cache breaks dependency outputs in some cases

### ISSUE THREAD

**Issue by fullykubed** [gruntwork-io/terragrunt#2693]
**Describe the bug**
 `--terragrunt-use-partial-parse-config-cache` results in outputs not being found in state files.

**To Reproduce**

Example terragrunt module where this fails unexpectedly [here](https://github.com/Panfactum/panfactum/blob/main/environments/development/us-east-2/kube_ingress_controllers/terragrunt.hcl).

Starting with no `.terragrunt-cache`.

Run `terragrunt apply --input=false -auto-approve -compact-warnings --terragrunt-non-interactive --terragrunt-include-external-dependencies --terragrunt-fetch-dependency-output-from-state --terragrunt-use-partial-parse-config-cache`

Results in

```
time=2023-08-30T17:16:58Z level=error msg=/home/runner/_work/panfactum/panfactum/environments/development/us-east-2/panfactum_primary_api_deployment/terragrunt.hcl:51,47-55: Unsupported attribute; This object does not have an attribute named "nat_ips"
```

The statefile does have that output. Simply removing `--terragrunt-use-partial-parse-config-cache` allows command to execute successfully as expected.

**Expected behavior**
The command should have the same behavior regardless of the presence of  `--terragrunt-use-partial-parse-config-cache` .

**Versions**
- Terragrunt version: `v0.48.6`
- Terraform version: `v1.3.7`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `linux_amd64` 

**Additional context**
My best guess is that the import structure of my project results in the wrong state file being pulled. A bit weird since I structured it mostly similar to the [example repo](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example).

**Comment by raanand-dig** [comment]
also notice it

**Comment by raanand-dig** [comment]
any update?

**Comment by fullykubed** [comment]
Not stale

**Comment by Orbsynated** [comment]
Happening to us aswell on s3 backend.

**Comment by RafaelWO** [comment]
This could be related to https://github.com/gruntwork-io/terragrunt/issues/4123, which was fixed in https://github.com/gruntwork-io/terragrunt/pull/5538.
