### ISSUE TITLE
Adressing a Gitlab Terraform module

### ISSUE THREAD

**Issue by ar19517** [gruntwork-io/terragrunt#2694]
**Describe the bug**
We want to switch to the Gitlab Terraform modules Registry. 
Adressing the modules in a .tf file via
```
module "test" {
  source  = "gitlab.mydomain.de/repo/test/all"
  version = "0.0.2"
}
```
works fine, but the terragrunt configuration via terragrunt.hcl 
```
terraform {
  source = "trf://gitlab.mydomain.de/repo/test/all//?version=0.0.2"
}
```
fails with
```
ERRO[0011] 1 error occurred:
        * error downloading 'tfr://gitlab.mydomain.de/repo/test/all?version=0.0.2': Error downloading module from https://gitlab.mydomain.de/api/v4/packages/terraform/modules/v1/repo/test/all/0.0.2/download: error receiving HTTP data

ERRO[0011] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
Both is started on the same machine.

**Versions**
- Terragrunt version: 0.50.9
- Terraform version: 1.5.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 20.04

**Comment by denis256** [comment]
Hi,
wanted to clarify if is used `tfr:///` schema, since in description is mentioned `...source = "trf://...`

Reference:
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform

**Comment by ar19517** [comment]
Hi,
`tfr:///` is a shortcut for `tfr://registry.terraform.io/`. I have to use the domain of the gitlab server. So I use `tfr://gitlab.mydomain.de/`

**Comment by ar19517** [comment]
Terragrunt does not use the .terraformrc settings. The TG_TF_REGISTRY_TOKEN variable has to be used.
