### ISSUE TITLE
TERRAGRUNT_FETCH_DEPENDENCY_OUTPUT_FROM_STATE updates wrong option in code

### ISSUE THREAD

**Issue by dctrwatson** [gruntwork-io/terragrunt#2696]
**Describe the bug**
The `TERRAGRUNT_FETCH_DEPENDENCY_OUTPUT_FROM_STATE` / `--terragrunt-fetch-dependency-output-from-state` flag updates `opts.UsePartialParseConfigCache` instead of `FetchDependencyOutputFromState`

**To Reproduce**

Set `TERRAGRUNT_FETCH_DEPENDENCY_OUTPUT_FROM_STATE=1` and start seeing cache hit/miss debug logs.

**Expected behavior**

Flag enables the right feature.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: 0.50.9
- Terraform version: v1.5.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 22.04

**Additional context**

https://github.com/gruntwork-io/terragrunt/blob/7d4c2b3cb9e79727d1da93af87466a519003b38e/cli/commands/flags.go#L200-L205

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.50.12
