### ISSUE TITLE
The ".terragrunt-source-manifest" file breaks uploading files to s3 bucket

### ISSUE THREAD

**Issue by ahmedatgithub** [gruntwork-io/terragrunt#2705]
**Describe the bug**
The file ".terragrunt-source-manifest" essentially corrupts the content in my code.
I am using the terraform function "fileset" to upload a whole tree of files onto s3 bucket for a website but the addition of this extraneous file into each directory breaks the whole system. 
The tree of content is in a subdirectory of my TF code.

You can't ignore it with any .ignore nor can you exclude it using standard terraform/terragrunt code that I know of.

1. The file should not get uploaded as it's not related to the site.
2. It breaks the regex below to determine the content type since it has no file extension.

**To Reproduce**
Here is my code snippet:
```tf
variable "type_map" {
  default = {
    "html" = "text/html"
    "js" = "application/javascript"
    "json" = "application/json"
    "css" = "text/css"
    "txt" = "text/plain"
  }
}
resource "aws_s3_object" "s3_content" {
  for_each = fileset(var.s3_content_dir, "**")
  bucket = var.s3_content_bucket
  key = each.value
  source = "${var.s3_content_dir}/${each.value}"
  etag = filemd5("${var.s3_content_dir}/${each.value}")
  content_type = var.type_map[regex(".*\\.([a-z0-9]+)$", each.value).0]
}
```
and here is the hcl part referencing the var "s3_content_dir":

```hcl
inputs = {
  ....
  s3_content_dir    = "../../../src/app/out"
  s3_content_bucket = dependency.myinfra.outputs.mybucket
}
```

**Expected behavior**
the file should not exist. I know probably terragrunt is using it to manage its' cache content, but that seems like a bad decision.

**Nice to have**
- some flag to exclude certain folders from the presence of this file
- a ways to exclude certain patterns in the TF function , but I know that's a TF issue not terragrunt.
- any other workaround that I'm not aware of. (other than zipping the directory beforehand and uploading it to another s3 bucket, having a poly repo is crucial here).

**Versions**
- Terragrunt version: terragrunt version v0.45.11
- Terraform version: Terraform v1.4.6 on darwin_arm64
- Environment details : Mac or Ubuntu Docker image

**Additional context**

**Comment by Tony-Proum** [comment]
Hello,
Same issue. Why is this file generated and is there a workaround to avoid having this file pushed in a bucket ?

**Comment by nekodojo** [comment]
I have the same issue, looks like not planned, but can someone enter a workaround before closing? thanks
