### ISSUE TITLE
Library of before/after/error hooks

### ISSUE THREAD

**Issue by JeanFred** [gruntwork-io/terragrunt#2706]
**Describe the solution you'd like**
I have several Terragrunt repositories. Most of them have the same Terragrunt before/after hooks (two hooks to send an event to our observability platform, three hooks around locks as described in #2689, etc.). 

My repositories already share some build code (Dockerfile, pre-commit-hooks, linter configuration etc.) via a git submodule.

I would like to also centralize these hooks.

**Describe alternatives you've considered**

I have attempted to use `read_terragrunt_config` on a HCL file containing the hooks but that fails. [1]

[1] Example:
```
terraform {
  before_hook "test" {
    commands = ["plan"]
    execute  = ["echo", "plan"]
  }
}
```
→  `This value is null, so it does not have any attributes.`

**Additional context**
This somewhat ties into the multi-include RFC (#1025), but that’s a specific use-case that I did not see mentioned before, so I thought I would share it.

**Comment by denis256** [comment]
Hello,
was considered an approach to include hooks from a parent file?

```
include "hooks" {
  path = find_in_parent_folders("hooks.hcl")
}
```
or include from a common directory:
```
include "hooks" {
  path = find_in_parent_folders("${get_repo_root()}/common-module/hooks.hcl")
}
```

References
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#include

**Comment by JeanFred** [comment]
Thank you for the answer!
> Hello, was considered an approach to include hooks from […] a common directory:
> 
> ```
> include "hooks" {
>   path = "${get_repo_root()}/common-module/hooks.hcl"
> }
> ```

yes, I did try that (sorry I should have mentioned it) ; it fails with `Only one level of includes is allowed.`, as I am using a structure similar to the [Example infrastructure-live for Terragrunt](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example)
> `/environments/prod/layer/terragrunt.hcl includes /environments/terragrunt.hcl, which itself includes /common-folder/hooks.hcl. Only one level of includes is allowed.`

I want to keep my 'leaf' terragrunt.hcl files as DRY as possible, so I would not want to add the hooks sourcing in them, but only in my top-level terragrunt file

I also tried to source the hooks from the leaf terragrunt files ; it actually does work. I thought it did not because I was hitting an error, but that’s because my hooks use `locals` values defined in the top-level terragrunt file (see #2689), and that fails with `Attempt to get attribute from null value; This value is null, so it does not have any attributes.`

**Comment by denis256** [comment]
Yes, at this point, it will require to include `hooks.hcl` in each file explicitly

**Comment by JeanFred** [comment]
I have just discovered [in the docs](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate) that 
> `generate` can also be set as an attribute. This is useful if you want to set generate dynamically.

if something like that was possible with hooks, this would solve the problem.
