### ISSUE TITLE
Unable to Run Terragrunt plans with Symantec Installed

### ISSUE THREAD

**Issue by csmith-partech** [gruntwork-io/terragrunt#2710]
**Describe the bug**
Hello,

We are unable to run our Terragrunt plans to build Azure resources with Symantec Endpoint Protection installed. The Windows 11 computers blue screen with a System Service exception error, while the Windows 10 machines simply freeze and then reboot with no blue screen code. This started after installing the August updates from Microsoft.

Running the plan without Symantec Endpoint Protection installed allows the plan to run with no issues. This behaviour exists on both the RU7 and RU8 releases of Symantec Endpoint Protection.

We had been able to run the plans with no issues for years until these issues started popping up. 

**To Reproduce**
Simply attempt to run a plan to build Azure resources and the computer bluescreens

```hcl
// paste code snippets here
```

**Expected behavior**

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terraform version: 1.5.4
- Terragrunt version: v0.50.12
- Environment details (Ubuntu 20.04, Windows 10, etc.): Windows 11

**Additional context**

**Comment by csmith-partech** [comment]
Hello,

Where can I forward the debug logs to? I'd rather not post them on a public forum.

**Comment by denis256** [comment]
Hi,
please forward to `support@gruntwork.io` and reference GitHub issue
