### ISSUE TITLE
terragrunt fails to get the outputs from dependency

### ISSUE THREAD

**Issue by srinathjamboju92** [gruntwork-io/terragrunt#2714]
**Describe the bug**
I'm seeing a problem with terragrunt not being able to get the outputs from modules that needs to be passed as inputs to dependent modules.

Below is the list of resources that are being attempted to create. Please note that this problem happens when terragrunt tries to create both parent and dependent resources for the first time.

**To Reproduce**
Create two directories vpc and eks cluster.
Ensure eks reads the outputs from vpc.

In eks.hcl:

```hcl
dependencies {
  paths = ["../vpc"]
}

dependency "vpc" {
  config_path                             = "../vpc"
  mock_outputs_merge_strategy_with_state  = "shallow"
  mock_outputs_allowed_terraform_commands = ["validate", "init", "plan"]
  mock_outputs                            = {
    vpc_id = "vpc-123456"
  }
}
```

**Expected behavior**
when run-all apply is executed, terragrunt builds the below segregated modules where the apply runs on each folder separately.

Group 1

- test/vpc

Group2

- test/eks_cluster

When apply runs inside vpc, it outputs attributes like vpc_id, private_subnets into state file immediately. And the expected behaviour from terragrunt when ran in eks_cluster, it should fetch the outputs from state to be assigned to eks_cluster. But this never happens, instead the outputs are fetched in all the directories at once and stored in json inside each directory. This way, run-all apply for the first time never works for dependent modules.

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: v0.50.16
- Terraform version: v1.5.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Mac

**Additional context**
I already ready most of the GitHub pages and the below links, none of them could solve the problem of run-all apply at first time when terraform state is empty.

This link explains about unapplied dependency, but doesn't explain that it can or cannot pass outputs to dependent modules while applying for the first time.

- https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#dependencies-between-modules

The comment here explicitly says, when run-all apply is made, outputs from vpc is written to state and they are used for dependent modules at the same time, but that never worked for me with above config.

- https://github.com/gruntwork-io/terragrunt/issues/720#issuecomment-497888756

There is one more workaround, this is again for run-all plan, never expected to be used for apply, as I need real outputs for apply.

- https://github.com/gruntwork-io/terragrunt/issues/940#issuecomment-610108712

**NOTE:** If I remove apply I know that the mock_outputs are not considered for run-all apply or apply commands, but when did so, I get the error that the outputs are not present in the parent module. And when apply is used, terragrunt never looks at state to get the outputs generated in the dependent module to use instead.

Raised a similar bug here https://github.com/orgs/gruntwork-io/discussions/768

**Below is the error log from the terminal output:**

```
test/eks_cluster has finished with an error: Cannot process module Module test/eks_cluster (excluded: false, assume applied: false, dependencies: [test/vpc]) because one of its dependencies, finished with an error: test/vpc/terragrunt.hcl is a dependency of test/eks_cluster/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.  prefix=[test/eks_cluster] 
```

**Comment by jmreicha** [comment]
Just ran into this one. We're you able to find a workaround or other info @srinathjamboju92?

**Comment by denis256** [comment]
Hi, 
my attempts to reproduce didn't succeed, each time I got real output data:
https://github.com/denis256/terragrunt-tests/tree/master/issue-2714
https://gist.github.com/denis256/17554e70f91dfa3ca5f780467bf8b45b

can be shared example of where the issue happens?

**Comment by jmreicha** [comment]
I think I found my issue. I was only setting the mock output for the “plan” command, added the other commands and everytistarted working as expected.
