### ISSUE TITLE
inputs cannot read locals variable

### ISSUE THREAD

**Issue by antyung148** [gruntwork-io/terragrunt#2718]
**Describe the bug**

cant read local.aws_project_name but local.env works

```
locals {
  env = "${get_env("ENV")}"
  aws_project_name = "${yamldecode(file("./var/${get_env("ENV")}.tfvars"))}"
}

inputs = {
  aws_vpc_subnet_a_id = dependency.vpc_main.outputs.aws_subnet_public_output[format("%s-%s-default-public-a", local.aws_project_name, local.env)].id
}
```

**To Reproduce**
// ./var/prod.tfvars
```
aws_project_name = "myproject"
```

// ./terragrunt.hcl

```
include "root" {
  path = find_in_parent_folders()
}
locals {
  env = "${get_env("ENV")}"
  aws_project_name = "${yamldecode(file("./var/${get_env("ENV")}.tfvars"))}"
}
dependency "vpc_main" {
  config_path = "../vpc"
  mock_outputs = {
    aws_subnet_public_output = {
      "${local.aws_project_name}-${local.env}-default-public-a" = {
        "id" = "subnet-00000000000000000"
    }
  }
  mock_outputs_merge_with_state = true
  mock_outputs_allowed_terraform_commands = ["init", "refresh", "validate", "plan", "fmt"]
}
inputs = {
  aws_vpc_subnet_a_id = dependency.vpc_main.outputs.aws_subnet_public_output[format("%s-%s-default-public-a", local.aws_project_name, local.env)].id
}
```

**Expected behavior**
works if I hard code `[format("myproject-%s-default-public-a", local.env)].id`

**Versions**
- Terragrunt version: `terragrunt version v0.43.0`
- Terraform version: `Terraform v1.5.2`
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS 12.5.1

**Additional context**
thanks

**Comment by denis256** [comment]
Hi,
I tried to reproduce the same issue in my [own repository](https://github.com/denis256/terragrunt-tests/tree/master/issue-2718), seems to work fine

Any idea how to make the issue to occur?

https://github.com/denis256/terragrunt-tests/tree/master/issue-2718
