### ISSUE TITLE
Terragrunt rebranding

### ISSUE THREAD

**Issue by ansromanov** [gruntwork-io/terragrunt#2727]
Yesterday, the Linux Foundation announced the formation of [OpenTofu](http://opentofu.org/).
As far as I understand, Terragrunt will not support Terraform versions after 1.5.5 and will switch to OpenTofu.

So, are there any plans to rename `Terragrunt` itself, for example to `Tofugrunt`, which makes a strong association with OpenTofu, not Terraform?

**Comment by tkflexys** [comment]
Where did you read about Terragrunt dropping support for Terraform after version 1.5.5

**Comment by ansromanov** [comment]
This is officially stated in https://blog.gruntwork.io/the-future-of-terraform-must-be-open-ab0b9ba65bca

**Comment by brikis98** [comment]
There is an issue for adding support for OpenTofu: https://github.com/gruntwork-io/terratest/issues/1333

**Comment by juozasget** [comment]
@brikis98 Could you clarify if `terragrunt` will continue to support future Terraform versions?

The blog post that @ansromanov mentioned is talking about the situation in the context of Gruntwork and it's customers. I imagine there are other projects using `terragrunt` w/o Gruntwork services.

Also `terragrunt` documentation already lists 1.6.x as supported.
![Screenshot 2023-11-13 at 17 54 03](https://github.com/gruntwork-io/terragrunt/assets/32190964/5282af36-1474-48ee-92d8-1684dfa36a59)

**Comment by kvendingoldo** [comment]
btw. we can add this mapping for [tenv](https://github.com/tofuutils/tenv). How do you think, is it a good idea?
