### ISSUE TITLE
Expected way to tflint modules without a delivery repo? 

### ISSUE THREAD

**Issue by rtizzy** [gruntwork-io/terragrunt#2729]
Not sure if I'm holding this the wrong way. 

It's clear how one would be able to utilize `tflint` from the module repos via `terragrunt` for example, using `after_hooks` for `validate`.

What isn't clear is this: 

If I'm making module level changes, how can these be linted and validated before merging them in? 

I've been unable to find any reasonable way to accomplish this if I'm also defining provider versions in `delivery`. 

Should I simply start managing provider versions at the module level instead?

**Comment by denis256** [comment]
Hi,
was considered to use hooks on `validate` command which is executed in pre-commit hooks?
or run `validate` in CICD as a required step before merging the branch?

**Comment by rtizzy** [comment]
@denis256 The modules themselves are intended to be used with terragrunt. 

The idea I had was to utilize a single TF validate and tflint using `terragrunt` from modules. 

Is there anyway to do that?
