### ISSUE TITLE
Enable more dynamic source attribute

### ISSUE THREAD

**Issue by thnee** [gruntwork-io/terragrunt#273]
Certainly the idea of versioning the modules in a separate git repo is great. But while developing it quickly becomes a hassle to specify a different source for every module. Also, the support for specifying a source is not really fully complete, as the `--terragrunt-source` argument "is not used with the `apply-all`, `destroy-all`, `output-all` and `plan-all` commands", effectively preventing testing of these vital commands during development.

Would it be a good idea to add an argument like `--terragrunt-source-prefix` or `--terragrunt-source-root`, with corresponding environment variable, so that users can set the source once during the development process, and not have to change it all the time?

**Comment by brikis98** [comment]
A `--terragrunt-source-root` command line param and corresponding env var (`TERRAGRUNT_SOURCE_ROOT`) sounds like a great idea! PR very welcome :)

**Comment by jmahowald** [comment]
Would the thinking be that you would replace everything before the // which indicates a subdirectory of a git repo?
