### ISSUE TITLE
Track code quality

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2732]
**Describe the solution you'd like**
Integrate tools to track code quality and flag any deviations  

**Describe alternatives you've considered**
Considered linters:

https://golangci-lint.run/

https://github.com/alecthomas/gometalinter

https://www.jetbrains.com/qodana/

**Additional context**
N/A

**Comment by maunzCache** [comment]
I really like that idea. Would you suggest that as a quality gateway for pullrequests or should this be run locally/on build time?
