### ISSUE TITLE
feat: Add support for all the assume-role attributes in the S3 remote state block

### ISSUE THREAD

**Issue by asvinours** [gruntwork-io/terragrunt#2744]
**Describe the solution you'd like**

Add support for extra assume-role attributes for S3 remote_state backend.

Right now it looks like terragrunt supports `role_arn`, `external_id`  and `session_name` but not the session duration, the session policy nor the session tags attributes.

terraform s3 backend documentation: https://developer.hashicorp.com/terraform/language/settings/backends/s3#assume-role-configuration

**Describe alternatives you've considered**

One alternative is to not use the terragrunt `remote_state` block and use a `generate` block and generate a terraform file for the backend configuration. Although doing this takes away the automatic deployment of the S3 bucket and dynamoDB table.

**Comment by wand2016** [comment]
https://github.com/hashicorp/terraform/releases/tag/v1.6.0

> The S3 backend has a number of significant changes to its configuration format in this release, intended to match with recent changes in the hashicorp/aws provider:

Terraform released v1.6.0 three hours after this issue was opened, and it includes BC breaks.

**Comment by fe-ax** [comment]
Additionally, `assume_role_with_web_identity` is not supported either. I am currently working around this by generating a `~/.aws/config` file.
