### ISSUE TITLE
Terraform 1.6

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2747]
**Describe the solution you'd like**
Validate support for Terraform 1.6 in Terragrunt

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/hashicorp/terraform/releases/tag/v1.6.0

https://www.hashicorp.com/blog/terraform-1-6-adds-a-test-framework-for-enhanced-code-validation

https://developer.hashicorp.com/terraform/language/upgrade-guides

**Comment by mgerlach** [comment]
With terraform 1.6.0, terragrunt (0.52.0) init fails with this message:

> -10-06T09:08:57Z level=error msg=Unable to parse Terraform version output: [command]/home/runner/work/_temp/99eb66ee-b605-4d22-9ab8-d97d2c74e871/terraform-bin --version
Terraform v1.6.0
on linux_amd64

**Comment by ognjengrubac-tomtom** [comment]
It seems to be failing with terraform 1.5.7 as well.

**Comment by mgerlach** [comment]
Ok, will try to verify, it may be a tg bug introduced in 0.52.0

**Comment by mgerlach** [comment]
> It seems to be failing with terraform 1.5.7 as well.

Can't confirm on MacOSX (M1). For me, terragrunt 0.52.1 works with terraform 1.5.7

**Comment by bdorplatt** [comment]
1.6.0 added support for Terraform "projects" Would it be possible to add support for this in Terragrunt?
 https://developer.hashicorp.com/terraform/cli/cloud/settings#project
Currently, we generate a backend like below but can't find a way to plug in the project without error.

generate "backend" {
  path      = "backend.tf"
  if_exists = "skip"
  contents  = <<EOF
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "XXXXXX"
    workspaces {
      name = "azure-${local.tenant}-${local.region_abbr}-${local.subscription}-${local.application}-${replace(path_relative_to_include(), "/", "-")}"
    }
   }
  }
EOF
}

**Comment by mgerlach** [comment]
terrgrunt init works with tg 0.52.1 and tf 1.6.1 on Mac M1, but not on linux_amd64 (GitHub worker)

**Comment by boekkooi-lengoo** [comment]
I just got this error in Github Actions using `hashicorp/setup-terraform@v2`. When setting `terraform_wrapper: false` the error go's away. 
So my guess is that somehow the [wrapper](https://github.com/hashicorp/setup-terraform/tree/main/wrapper) is messing something up.

**Comment by MaoChhaya** [comment]
terragrunt init works after upgrading version to 0.52.3 with terraform v1.6.1 on Ubuntu 22.04.

**Comment by mgerlach** [comment]
Update: It does work with setting `terraform_wrapper: false` for `hashicorp/setup-terraform@v2` action. Still not sure I want to add that config in all repos...

**Comment by denis256** [comment]
Not all Terragrunt tests are passing with Terraform 1.6, so far found issue https://github.com/hashicorp/terraform/issues/34066 which sometimes appear on projects

**Comment by lorengordon** [comment]
@denis256 The issues from #34066 should be fixed as of Terraform 1.6.2.

**Comment by ognjengrubac-tomtom** [comment]
Hi, I don't see this is fixed. Could someone take a look?
![image](https://github.com/gruntwork-io/terragrunt/assets/108531371/516ef3f8-6a4f-45f8-8170-31dbf6a01958)

**Comment by mgerlach** [comment]
> Hi, I don't see this is fixed. Could someone take a look? I use both latest terraform and terragrunt. ![image](https://private-user-images.githubusercontent.com/108531371/289524679-516ef3f8-6a4f-45f8-8170-31dbf6a01958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDM1MDQsIm5iZiI6MTcwMjMwMzIwNCwicGF0aCI6Ii8xMDg1MzEzNzEvMjg5NTI0Njc5LTUxNmVmM2Y4LTZhNGYtNDVmOC04MTcwLTMxZGJmNmEwMTk1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNDAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjc4NWQwZWIwN2MyOTZiOThhNzc5YmMxYTYzMjliODdlNDU5OGU5MzQ5M2Q1MjcwZmM5Y2ZjMmQ2NGI4NDA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3lqI37Ku_jg88nMzSnd53krufrtlhZ2oVF4jH0s2a4U)

Is that GitHub Actions? Can you check how you setup terraform? We had to switch to hashicorp/setup-terraform@v3 (used to use v2)

**Comment by ognjengrubac-tomtom** [comment]
Thanks, @mgerlach ! It works with hashicorp/setup-terraform@v3.
