### ISSUE TITLE
Terragrunt destroy ask me to apply each modules of my tree

### ISSUE THREAD

**Issue by CorentinRegnier** [gruntwork-io/terragrunt#2748]
**Describe the bug**
When i run `terragrunt destroy` on a specific module it ask me to apply each external dependency since Terragrunt `0.51.9`, reproductible version `0.52.0`.
It ask to apply external modules, not linked to my main module where i try to destroy.

![image](https://github.com/gruntwork-io/terragrunt/assets/20766555/2dc4ccf6-c118-41d1-9af0-28be86716977)

**To Reproduce**
Run this command : 
```bash
 terragrunt destroy
```

Here is config of specific module : 

```hcl
terraform {
  source = "git::ssh://git@somesource//mymodule?ref=mytag"
}

include {
  path = find_in_parent_folders()
}

locals {
  common_vars = merge(
    yamldecode(
      file("${find_in_parent_folders("common.yaml")}"),
    )
  )
}

inputs = {
  mydepoutput= dependency.mydep.outputs.myoutput
}

dependency "mydep" {
  config_path = "../mydep"
}

```

**Expected behavior**
When i run a `terragrunt destroy` don't ask me to apply other modules of IaC.

**Versions**
- Terragrunt version: `0.51.9`
- Terraform version: `1.5.7`
- Environment details (Ubuntu 20.04, Windows 10, etc.): Windows 11 - WSL2 - `Ubuntu 22.04.3 LTS` 
Tried on Debian 12 on other machine (Win11 WSL2 too)

**Additional context**
Looks like it try to apply all modules of IaC

**Comment by sekot** [comment]
me too

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.52.1

**Comment by CorentinRegnier** [comment]
Thanks a lot, you rock @denis256
