### ISSUE TITLE
terragrunt doesn't work with S3 backends which have skip_credentials_validation = true

### ISSUE THREAD

**Issue by gregorycuellar** [gruntwork-io/terragrunt#2750]
**Describe the bug**
Since #2739 , terragrunt doesn't work with S3 backends which have skip_credentials_validation = true
First init works, but following plans ou applies fail with an error

```
ERRO[0000] RequestError: send request failed
caused by: Post "https://sts.fr-par.amazonaws.com/": dial tcp: lookup sts.fr-par.amazonaws.com: no such host 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
```

No error occurs in terragrunt 0.51.7 and previous versions

Can I propose a PR to fix this ?

**To Reproduce**
Declare a S3 backend with skip_credentials_validation = true ( by example with scaleway )

```hcl
remote_state {
  backend = "s3"

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    encrypt        = false
    endpoint       = "https://s3.fr-par.scw.cloud"
    region         = "fr-par"
    bucket         = "terraform-states"
    key            = "${path_relative_to_include()}.tfstate"

    # All S3-specific validations are skipped:
    skip_region_validation             = true
    skip_credentials_validation        = true
    skip_metadata_api_check            = true
    skip_bucket_ssencryption           = true
    skip_bucket_root_access            = true
    skip_bucket_enforced_tls           = true
    skip_bucket_public_access_blocking = true
  }
}
```

Produced TF :
```tf
terraform {
  backend "s3" {
    bucket                      = "terraform-states"
    encrypt                     = false
    endpoint                    = "https://s3.fr-par.scw.cloud"
    key                         = "test.tfstate"
    region                      = "fr-par"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
  }
}
```

**Expected behavior**

Like in versions previous to 0.51.8, No error should occur, terragrunt should skip AWS session validation

**Nice to have**
- [X] Terminal output
- [x] Screenshots

**Versions**
- Terragrunt version: >= 0.51.8 ( tested on 0.51.8, 0.51.9, 0.52.0, all are failing )
- Terraform version: 1.5.7 ( not relevant )
- Environment details (Ubuntu 20.04, Windows 10, etc.): macos ( not relevant )

**Additional context**

**Comment by Snakebott** [comment]
I'm getting the same error. In this case, the first init works. For repeated init to work, you need to delete the cache

```
ERRO[0000] 1 error occurred:
	* RequestError: send request failed
caused by: Post "https://sts.ru-central1.amazonaws.com/": dial tcp: lookup sts.ru-central1.amazonaws.com on 198.19.248.200:53: no such host
```

**Comment by denis256** [comment]
Added handling of `skip_credentials_validation` in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.52.2
