### ISSUE TITLE
Duplicate provider check causes regression for valid use case.

### ISSUE THREAD

**Issue by eballetbaz** [gruntwork-io/terragrunt#2751]
**Describe the bug**

New check added in ticket #2280 (pull #2281) is causing some regressions for valid use cases.
Indeed there are case where terraform needs to access multiple regions: for exemple mixing standard resources with Cloudfront resources which are hosted on one specific region only.
In this case "alias" is used on the provider.

**To Reproduce**

```hcl
generate "provider" {
  path      = "providers.tf"
  contents = <<EOF
provider "aws" {
  region  = "eu-west-1"
}

provider "aws" {
  alias   = "us-east-1"
  region  = "us-east-1"
}
EOF
}
```

**Expected behavior**
Duplicate providers do not block process

**Versions**
- Terragrunt version: 0.52.1
- Terraform version: 1.5.7

**Additional context**
This was working until version 0.51.4 included

**Comment by vi2co** [comment]
+1 to fix this bug

**Comment by vi2co** [comment]
From the Terragrunt [documentation](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate), the expected behavior is to take into the account `if_exists` attribute and if it's set to the `overwrite_terragrunt`: overwrite the existing file if it was generated by terragrunt; otherwise, error.

**Comment by denis256** [comment]
> ```terraform
> generate "provider"
> ```

Hello,
why can't be defined blocks with different names?
```
generate "provider" {
...
}
generate "provider2" {
...
}
```

**Comment by denis256** [comment]
> From the Terragrunt [documentation](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate), the expected behavior is to take into the account `if_exists` attribute and if it's set to the `overwrite_terragrunt`: overwrite the existing file if it was generated by terragrunt; otherwise, error.

From Terragrunt documentation: `each block needs a name to differentiate between the other blocks.` - having the same name for `generate` block will lead to errors.

**Comment by vi2co** [comment]
> Hello, why can't be defined blocks with different names?
> 
> ```
> generate "provider" {
> ...
> }
> generate "provider2" {
> ...
> }
> ```
> 
> I tried to reproduce the issue with the provided code snippet, shows the error:
> 
> ```
> terragrunt.hcl:1,21-21: Missing required argument; The argument "if_exists" is required, but no definition was found. 
> ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
> ```
> 
> If I add missing `if_exists`, `terragrunt apply` is working fine Example in: https://github.com/denis256/terragrunt-tests/tree/master/issue-2751

@denis256 
Thanks, it works!
