### ISSUE TITLE
Improper capture/replace of stderr

### ISSUE THREAD

**Issue by jmahowald** [gruntwork-io/terragrunt#276]
If I have problems in my modules/configuration, at least in the case of missing required variables, the error messages from terraform are supressed.

For example (apologize for not producing a reproducible code snippet), I would see 

`
Get: file:///private/var/folders/py/53d6y8k92jbgb2jkc1s8dj_m0000gq/T/terragrunt/jhLEm6G9BFQZChjt3JTNM3SXeNQ/Znsq9mYTrQritolBQQbzPqt51Kw/modules/cluster
[terragrunt] [/Users/josh.mahowald/workspace/terraform/live/dev/basevpc] 2017/08/30 12:54:18 Module /Users/josh.mahowald/workspace/terraform/live/dev/basevpc has finished with an error: exit status 1
`

Only by going to the temporarily created folder and running terraform plan in there did I get the real error message from terraform

`Error getting plugins: module root: 1 error(s) occurred:

* module 'network': unknown variable referenced: 'aws_region'. define it with 'variable' blocks
`
Not sure if this is just an edge case for me, this is my first day with terragrunt

**Comment by jmahowald** [comment]
I created a test case for this in a pull request https://github.com/gruntwork-io/terragrunt/pull/277.  To be more specific, it is an issue with terragrunt plan-all generally for errors.  terragrunt plan has the expected behavior.

**Comment by brikis98** [comment]
Fixed by #277.
