### ISSUE TITLE
output-module-groups does not generate destroy order or support terragrunt cli options

### ISSUE THREAD

**Issue by bt-macole** [gruntwork-io/terragrunt#2768]
**Describe the solution you'd like**
output-module-groups does not generate the proper destroy order if passed in the destroy command

it also does not support options like`--terragrunt-modules-that-include`

it would be great if these features were supported so output-module-groups ran exactly like run-all in terms of forming a stack.

**Describe alternatives you've considered**
Writing a new command to handle these features

**Comment by denis256** [comment]
Included in release: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.52.6
