### ISSUE TITLE
Clearer error when neither terraform nor opentofu is installed

### ISSUE THREAD

**Issue by Patricol** [gruntwork-io/terragrunt#2776]
**Describe the solution you'd like**
With the recent addition of opentofu support, running terragrunt (tested with `terragrunt output`) with neither opentofu nor terraform installed outputs

> ERRO[0000] exec: "tofu": executable file not found in $PATH 
> ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1

I imagine this should give a message that explains the need to install one of the two options.

Tested on `terragrunt version 0.53.0`.

Edit: didn't realize opentofu was a full fork when making this issue.

**Comment by imtaji** [comment]
Hey, did you find the solution?

**Comment by jsokol89** [comment]
Ran into the same issue.
Turns one my `terraform` binary was broken, and it seems as if when terragrunt can't find `terraform`, it then tries `tofu` - and given it's the last thing it tires, the error message states `tofu` not found.

Fixing my `terraform` binary has resolved the issue. `tofu`-free solution :)
