### ISSUE TITLE
Only one level of includes is allowed

### ISSUE THREAD

**Issue by raphaeldeletoille** [gruntwork-io/terragrunt#2778]
**Describe the bug**
With latest version (0.53.0) it seems that terragrunt only accept one level of includes. 

We have terragrunt.hcl in root and in each module subfolder. It seems when we run a terragrunt run-all plan the first run works as intended and generate cache. If we want to run terragrunt run-all plan again the terragrunt.hcl present in cache call the terragrunt.hcl in module subfolder and this one call the terragrunt.hcl in root but it fail as only one level of includes is allowed so we can not run multiple terragrunt run-all plan without cleaning cache. 

'[...]/deployment/terragrunt/bootstrap/agents/.terragrunt-cache/[unique-cache-id]/[cache-subfolder]/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of [...]/deployment/terragrunt/bootstrap. Underlying error: [...]/deployment/terragrunt/bootstrap/agents/.terragrunt-cache/[unique-cache-id]/[cache-subfolder]/terragrunt.hcl includes [...]/deployment/terragrunt/bootstrap/agents/terragrunt.hcl, which itself includes [...]/deployment/terragrunt/bootstrap/agents/terragrunt.hcl. Only one level of includes is allowed.

**To Reproduce**

We use in our terragrunt.hcl located in our module subfolder. 

 include "root" {
  path = find_in_parent_folders()
}

FYI when we use the version 0.50.14 we can run multiple plan without any issue, i do not know exactly from which version our issue appear but it persist on the latest 0.53.0 (and i do not see anything in changelog related to that)

```hcl
// paste code snippets here
```

**Expected behavior**
Accept multiple include (i guess it is the case for the version 0.50.14 as it works fine)

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: 0.53.0
- Terraform version: 1.5.7
- Environment details (Ubuntu 20.04, Windows 10, etc.): Win10

**Additional context**

**Comment by Khayoann2** [comment]
@denis256 Do you have an idea about the issue ?
