### ISSUE TITLE
`terragrunt run-all apply -destroy` destroys components in the order of apply

### ISSUE THREAD

**Issue by aaj-synth** [gruntwork-io/terragrunt#2789]
**Describe the bug**
Terraform supports destruction of infrastructure by passing `-destroy` flag with apply. However for terragrunt, passing `-destroy` alongwith `run-all apply` does not work as expected and the destroy graph of resources is not correct.

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.
- Create resources using `terragrunt run-all apply`
- Destroy resources using `terragrunt run-all apply -destroy`
- The order of destroy is invalid

**Expected behavior**
`run-all apply -destroy` should destroy resources in the order of `run-all destroy`

**Versions**
- Terragrunt version: `0.53.1`
- Terraform version: `1.6.3`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `Amazon Linux release 2023 (Amazon Linux) x86_64`

**Comment by levkohimins** [comment]
Hi @aaj-synth,
Retrieved from the terraform [docs](https://developer.hashicorp.com/terraform/cli/commands/destroy#usage)
> Usage: terraform destroy [options]
This command is just a convenience alias for the following command:
terraform apply -destroy

Terragrunt doesn't recognize the `-destroy` flag with `apply` comman, therefore does not take into account the order in which modules should be destroyed.  Is there any reason why you cannot use `terragrunt destroy ...`?
