### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by albenakoteva** [gruntwork-io/terragrunt#2794]
**Describe the bug**
With latest version (0.53.3) it seems that terragrunt is not able to complete any of the run-all commands more than once with the same cache.

I have a root directory with multiple subdirectories representing different environments and modules for deployment. Each subdirectory contains a terragrunt.hcl file, like this:
-live
--db_to_deltalake
---all_purpose_cluster
----terragrunt.hcl
---mssql
----terragrunt.hcl
---oracle
----terragrunt.hcl

When I run a terragrunt run-all plan the first run works as intended and generates cache. If I want to run terragrunt run-all plan again or run another command (for ex. terragrunt run-all apply or terragrunt run-all destroy) the command fails with the following error:
time=2023-11-15T18:07:29+02:00 level=error msg=Error processing module at 
[...]/live/db_to_deltalake/mssql/.terragrunt-cache/49rvKcmzroHbYFyuIsDxTOzlmag/all_purpose_cluster/terragrunt.hcl'. 
How this module was found: dependency of module at 
'[...]/Terragrunt/live/db_to_deltalake/mssql/.terragrunt-cache/49rvKcmzroHbYFyuIsDxTOzlmag/Up1v2-e2eN7_VINYorWqZObDNvk'. 
Underlying error: Error reading file at path 
[...]/Terragrunt/live/db_to_deltalake/mssql/.terragrunt-cache/49rvKcmzroHbYFyuIsDxTOzlmag/all_purpose_cluster/terragrunt.hcl: open 
[...]/Terragrunt/live/db_to_deltalake/mssql/.terragrunt-cache/49rvKcmzroHbYFyuIsDxTOzlmag/all_purpose_cluster/terragrunt.hcl: The system cannot find the path specified.
time=2023-11-15T18:07:29+02:00 level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1

**To Reproduce**
Run in sequence the following commands:

terragrunt run-all plan
terragrunt run-all apply

or

terragrunt run-all apply
terragrunt run-all destroy

FYI: When I downgraded the version of Terragrunt to v0.50.14, the commands work as expected. I decided to choose exactly this version to downgrade as reading bug #2778. It seems they are related.

```hcl
// paste code snippets here
```

**Expected behavior**
To be able to execute run-all commands in a sequence using the same cache.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: v0.53.2
- Terraform version: v1.6.4
- Environment details (Ubuntu 20.04, Windows 10, etc.): Windows 11

**Additional context**

**Comment by rgouyet** [comment]
I get the same issue

**Comment by deBFM** [comment]
This bug appeared first in `v0.50.15`

**Comment by abhivijay89** [comment]
Any updates on this? Issue is still present on the latest version (as of today): `v0.54.8`

**Comment by denis256** [comment]
Hello,
will be helpful to share an example repository where the issue happens,
I tried to reproduce in https://github.com/denis256/terragrunt-tests/tree/master/issue-2794 but all `run-all` commands pass without errors

**Comment by deBFM** [comment]
Hello @denis256,

I've set up a repository to demonstrate the issue we're encountering, which mirrors a simplified version of our production code. You can find the repository here: https://github.com/deBFM/terragrunt-issue-2794.
Within this repository, I've outlined the steps necessary to reproduce the issue.

Thank you for looking into this issue.

**Comment by denis256** [comment]
Hi,
will take a look on Windows, tests on Ubuntu 22.04 worked without any issue

**Comment by denis256** [comment]
Happens on windows environment
![image](https://github.com/gruntwork-io/terragrunt/assets/10694338/853830f3-e306-4dbf-bd80-429b39443d0d)

**Comment by denis256** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.17

**Comment by deBFM** [comment]
@denis256 
I can confirm that the bug has been fixed.

Thank you very much!
