### ISSUE TITLE
Ensure all dependency outputs are mocked.

### ISSUE THREAD

**Issue by jlepere-everlaw** [gruntwork-io/terragrunt#2795]
**Describe the solution you'd like**
For my organizations configuration, I've found that mocking each dependency output is almost always necessary to facilitate workflows between modules with terragrunt. It's very easy to miss adding such dependencies, leading to continuous errors. It would be helpful for us if there was a way to validate that each dependency output used had a mocked value. It would be great if this could be checked statically, but even something like (or an extension of) [`validate-inputs`](https://terragrunt.gruntwork.io/docs/reference/cli-options/#validate-inputs) would be nice.

**Describe alternatives you've considered**
We've consider writing a custom tool to parse `terragrunt.hcl` to statically analyze dependency output usages and mocked values, but that can get a bit complicated given outputs usages isn't always straightforward (e.g sometimes we reference them from with a loop).

We've also considered running some non-mutating command against a dummy stack without any configuration deployed and ensuring that there are no errors. Because no dependencies would have state, this would verify that each dependency output used had a mocked output defined. Maybe this isn't a terrible solution? It might just be nice to have a simpler way to verify this.

**Additional context**
n/a

**Comment by yuklia** [comment]
any news ?
