### ISSUE TITLE
Unexpected rename function get_terraform_commands_that_need_input

### ISSUE THREAD

**Issue by FedotovIlya** [gruntwork-io/terragrunt#2797]
**Describe the bug**
Unexpected rename function `get_terraform_commands_that_need_input`

**To Reproduce**
Try to run any code with functions `get_terraform_commands_that_need_input`

```hcl
extra_arguments "disable_input" {
    commands  = get_terraform_commands_that_need_input()
    arguments = ["-input=false"]
  }
```
**output**
ERRO[0009] /Users/ilya/work/terraform-aws/terragrunt.hcl:17,17-55: Call to unknown function; There is no function named "get_terraform_commands_that_need_input". Did you mean "get_terraform_commands_that_need_inputa"?, and 1 other diagnostic(s) 
ERRO[0009] Unable to determine underlying exit code, so Terragrunt will exit with error code 1

**Versions**
- Terragrunt version: v0.53.4

**Additional context**
problem place in code: https://github.com/gruntwork-io/terragrunt/blob/c4dcbf1d385ce525fa9113298cb7f370885d99cd/config/config_helpers.go#L56
PR with error: https://github.com/gruntwork-io/terragrunt/pull/2791

**Comment by denis256** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.53.5
