### ISSUE TITLE
TF1.6 Missing assume_role struct for RemoteStateConfigS3

### ISSUE THREAD

**Issue by sylwit** [gruntwork-io/terragrunt#2798]
**Describe the bug**
Terraform 1.6 has deprecated top level arguments for a new `assume_role` argument for the remote s3 backend configuration

https://developer.hashicorp.com/terraform/language/settings/backends/s3#assume-role-configuration
`The preferred way is to use the argument assume_role, the other, which is deprecated, is with arguments at the top level.`

**To Reproduce**

Update this code
```hcl
remote_state {
  backend = "s3"
  config  = {
    ...
    role_name = "arn:aws:iam::123456789:role/Terraform
  }
```
with

```hcl
remote_state {
  backend = "s3"
  config  = {
    ...
    assume_role = {
        role_name = "arn:aws:iam::123456789:role/Terraform
    }
  }
```
and run `TF_LOG=debug terragrunt plan`. You'll see the role is not assumed

**Expected behavior**
The role should be assumed

**Versions**
- Terragrunt version: 0.53.4
- Terraform version: 1.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): mac, debian

**Additional context**
Looks like the struct RemoteStateConfigS3  https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L83 is missing the assume_role block

and the value here https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L107 can now come from the block or from the deprecated argument. 

Here is a PR https://github.com/gruntwork-io/terragrunt/pull/2800

**Comment by denis256** [comment]
Released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.53.6
