### ISSUE TITLE
render-json does not work anymore (since 0.51.9)

### ISSUE THREAD

**Issue by BenjaminHerbert** [gruntwork-io/terragrunt#2809]
**Describe the bug**

We upgraded terragrunt and can not run `terragrunt render-json` anymore. It seems that the evaluation phase does not finish (or just takes a very long time). 

It seems that terragrunt jumps all the way up to the _git_-repository root and somehow includes all the environments we have defined.

I tracked it down to the latest working version: 0.51.8. From 0.51.9 it is broken. Diff: [0.51.8 to 0.51.9](https://github.com/gruntwork-io/terragrunt/compare/v0.51.8...v0.51.9).

Our structure is as follows

- /
  - terraform/
    - module1
    - module2
  - terragrunt/
    - dev/
      - common.hcl
      - module1/terragrunt.hcl
      - module2/terragrunt.hcl
    - staging/
      - common.hcl
      - module1/terragrunt.hcl
      - module2/terragrunt.hcl
    - prod/
       - common.hcl
       - module1/terragrunt.hcl
       - module2/terragrunt.hcl 

**To Reproduce**

`terragrunt render-json`

**Expected behavior**

The json should be rendered below a second, it should not jump into other env.

**Versions**
- Terragrunt version: 0.53.6 (since 0.51.9)
- Terraform version: v.1.5.7
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS 14.1.1 (23B81)

**Additional context**

One interesting observation: if I rename the `.git` folder in the `/` directory of the project, it works as expected and produces a json file very quickly.

**Comment by ChandlerSwift** [comment]
I'm seeing the same behavior, which I can confirm appears to have been introduced in https://github.com/gruntwork-io/terragrunt/commit/1a80dba8786bdca1e157530c153066e5cfdd4a52. For my setup, it does finish, but is definitely quite a bit slower than previously. I built 1a80dba8786bdca1e157530c153066e5cfdd4a52 and its parent 7878f26b74387c99c44efefaec6e36703a72a303, and it looks like that commit made `render-json` take >150x as long as it did previously.

```
% hyperfine "terragrunt-7878f26b render-json" "terragrunt-1a80dba8 render-json"
Benchmark 1: terragrunt-7878f26b render-json
  Time (mean ± σ):     123.4 ms ±   5.5 ms    [User: 117.2 ms, System: 49.2 ms]
  Range (min … max):   112.9 ms … 133.3 ms    22 runs
 
Benchmark 2: terragrunt-1a80dba8 render-json
  Time (mean ± σ):     21.374 s ±  2.517 s    [User: 27.189 s, System: 2.907 s]
  Range (min … max):   16.031 s … 25.013 s    10 runs
 
Summary
  terragrunt-7878f26b render-json ran
  173.24 ± 21.79 times faster than terragrunt-1a80dba8 render-json
```

**Comment by ChandlerSwift** [comment]
Ah, and, notably, the output is unchanged!
```
% time terragrunt-1a80dba8 render-json > 1a80dba8.json
terragrunt-1a80dba8 render-json > 1a80dba8.json  24.92s user 2.57s system 143% cpu 19.150 total
% time terragrunt-7878f26b render-json > 7878f26b.json
terragrunt-7878f26b render-json > 7878f26b.json  0.15s user 0.04s system 134% cpu 0.144 total
% sha256sum *json
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  1a80dba8.json
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  7878f26b.json
```

@denis256 at least for the time being, would you accept a PR reverting the commit that introduced the performance regression, given that it doesn't actually appear to change the output?

**Comment by denis256** [comment]
Flag to improve performance added in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.56.2

**Comment by ChandlerSwift** [comment]
Looks great. Thanks!
