### ISSUE TITLE
RemoteStateConfigS3 assume_role  suddenly broken at 0.53.8

### ISSUE THREAD

**Issue by chrisduong** [gruntwork-io/terragrunt#2813]
**Describe the bug**

When I use `assume_role` for Remote State Config S3, the generated code contains the wrong config

```
 Error: Incorrect attribute value type
│ 
│   on backend.tf line 4, in terraform:
│    4:     assume_role    = "{role_arn=\"arn:aws:iam::1111111111:role/sysops\"}"
│ 
│ Inappropriate value for attribute "assume_role": object required.
```

This feature is still working with the older version: `0.53.6`, fixed in this issue https://github.com/gruntwork-io/terragrunt/issues/2798

**Expected behavior**

It should generate code as below

```hcl
assume_role    = {
  role_arn = "arn:aws:iam::1111111111:role/sysops"
}
```

**Versions**
- Terragrunt version: 0.53.8
- Terraform version: 1.6.4
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS 14.1.1

**Comment by denis256** [comment]
Hello,
which is `terragrunt.hcl` used to generate state configuration?

**Comment by chrisduong** [comment]
Hi this is my config

```
remote_state {
  backend = "s3"
  config = {
    encrypt        = true
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "eu-west-1"
    dynamodb_table = "terraform-locks"

    bucket = "terraform-state"
    assume_role = {
      role_arn = "arn:aws:iam::11111111:role/admin"
    }


    skip_bucket_root_access = true
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

**Comment by lstn** [comment]
Having the exact same issue in 0.54.4, with the configuration in the root `terragrunt.hcl`.

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.6
