### ISSUE TITLE
Terragrunt cannot replace its module manifest file

### ISSUE THREAD

**Issue by cveld** [gruntwork-io/terragrunt#2824]
**Describe the bug**
Always when I run terragrunt - at least on Windows - I get the following errors:

`time=2023-12-03T16:26:01+01:00 level=warning msg=Error removing manifest file C:\Temp\terragrunt\xorohWddmXaMc1ao72SlEPQHYJI\gaiew1IE5fQeG2UpFH42XBj327M\.terragrunt-module-manifest: remove C:\Temp\terragrunt\xorohWddmXaMc1ao72SlEPQHYJI\gaiew1IE5fQeG2UpFH42XBj327M\.terragrunt-module-manifest: The process cannot access the file because it is being used by another process.`

Interestingly they don't seem to be blocking.

**To Reproduce**
I have set up a simple terragrunt layout here:
https://github.com/cveld/terraform-tester/tree/main/Repros/Terragrunt-module-manifest-in-use

**Expected behavior**
The error should not occur.

**Versions**
- Terragrunt version: v0.53.6
- Terraform version: v1.6.3
- Environment details (Ubuntu 20.04, Windows 10, etc.): Version	10.0.22621 Build 22621

**Comment by ben-qr** [comment]
I'm seeing the same issue - also doesn't appear to be blocking

**Comment by skkc2** [comment]
i'm getting the same issue but it's blocking can't do terragrunt init plan apply anything

**Comment by dbain-texada** [comment]
I also get this behavior, non-blocking for me, just curious as to why it's happening.

**Comment by denis256** [comment]
Hi, I think this was fixed a while ago, it is still happening on the last version?

**Comment by eballetbaz** [comment]
Hi,
I had the same issue, after upgrading to release v0.55.1 the problem disappear

Note: I think this is a duplicate of #2864

**Comment by denis256** [comment]
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/2864
