### ISSUE TITLE
Remote execution c ontextg

### ISSUE THREAD

**Issue by dmead** [gruntwork-io/terragrunt#2825]
Hi,

In my org, we have a requirement that we can't run terraform from out laptops. Most of the remote system that providers would talk to don't have routing to our laptops for security reasons. 

We've taken to a process where you have to push to git, then checkout your changes in a container running on the development k8s cluster. Obviously this is a lot of steps for a development cycle, so we'd like to cut it down.

My request is for some mechanism (or guidance) to copy and execute a module in a remote context. We have automation in place to establish a container in k8s where terraform can be run. What we're looking for is some way to prepend the terraform command with `kubectl exec <pod>`. We could theoretically write a hook that would sync the cache directory up to the remote system with a `kubectl cp`, but we have no way to alter how terragrunt is calling it's underlying terraform

we've thought about using rsync or something, but we feel that this is better folded into the idea of a terragrunt module.

**Comment by gqrlt1207** [comment]
I think you can use 'terraform' to run 'helm chart' which will deploy the resources in k8s. 
terragrunt--> wrap the terraform---> helm chart---> k8s.

**Comment by denis256** [comment]
Hello,
I was thinking about some base image with most of the dependencies already installed, including terraform modules

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-download-dir
https://terragrunt.gruntwork.io/docs/features/caching/
