### ISSUE TITLE
Terragrunt does not take all terragrunt.hcl file in parent directories into consideration 

### ISSUE THREAD

**Issue by sudhirpandey** [gruntwork-io/terragrunt#2827]
**Describe the bug**

I am just trying to follow the doc https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/#keep-your-terragrunt-architecture-dry , so we can keep Configs DRY but has not been sucessful so far,
my directory sturcture is like
.
├── _env
│   └── sandbox.hcl
├── common-vars.yaml
├── sandbox
│   ├── norwayeast
│   │   └── network
│   │       └── terragrunt.hcl
│   └── terragrunt.hcl
└── terragrunt.hcl

the context of root terragrunt.hcl is ( so that we can keep provider block DRY) 
```
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "azurerm" {
  features {}
}
EOF
}
```

then contents of sanbox/terragrunt.hcl is ( so that we can keep backed block DRY) 
```
generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
  backend "azurerm" {
    resource_group_name  = "somename-test-rsg"
    storage_account_name = "sanboxsomestorageacc"
    container_name       = "tfstate"
    key            = "${path_relative_to_include()}/terraform.tfstate"
  }
}
EOF
}
```

on _env/sandbox.hcl ( we have sandbox specfic settinsgs) 
```
locals{
    context = yamldecode(file(find_in_parent_folders("common-vars.yaml")))
    environment="sandbox"
    tags = {
        costAllocation = local.context.costallocation
        environment = local.environment
    }
}

inputs = {
  environment   = local.environment
  tags                = local.tags
  prefix              = local.context.prefix
}
```

on sandbox/norwayeast/network/terragrunt.hcl file we have environment specifc things
```
include "root" {
  path = find_in_parent_folders()
}


include "env" {
  path   = "${get_terragrunt_dir()}/../../../_env/sandbox.hcl"
  expose = true
}


terraform {
  source = "../../../../network"
}

inputs = {
  location_name       =  "norwayeast" 
  management_cidr     = "192.168.0.0/24"
  node_subnet_cidr    = "192.168.1.0/24"
}

```
But when we run terragrunt , the backend.tf is populated in terrafrom cache directory.  but provider.tf  is not populated in terrafrom cache directory ,As result terrafrom plan fails as it lacks provider block

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.
After createting the folder structure like above , try running `terragrunt run-all plan`  , it fails
`

**Expected behavior**
It should have created the provider.tf file in cache directory and the terraform plan should have been sucessful

**Command Line STDOUT**
```
❯ terragrunt run-all plan
INFO[0000] The stack at /tmp/terragrunttest/azure will be processed in the following order for command plan:
Group 1
- Module /tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network


Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.
╵
time=2023-12-06T19:05:08+01:00 level=error msg=terraform invocation failed in /tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE prefix=[/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network]
ERRO[0003] Module /tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network has finished with an error: 1 error occurred:
	* [/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE] exit status 1
  prefix=[/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network]
INFO[0003] ╷
│ Error: Insufficient features blocks
│
│   on <empty> line 0:
│   (source code not available)
│
│ At least 1 "features" blocks are required.
╵
time=2023-12-06T19:05:08+01:00 level=error msg=terraform invocation failed in /tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE prefix=[/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network]
ERRO[0003] 1 error occurred:
	* [/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE] exit status 1
```

**terrafrom cache directory**
Upon looking into cached directory `/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE`

```
 tree /tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE
/tmp/terragrunttest/azure/terragrunt/sandbox/norwayeast/network/.terragrunt-cache/pERU_MCN0vgJIFPrSMxJ8PhSdgA/bgpBUGNzl4CbCggFL3JxGLM14wE
├── backend.tf
├── local.configs.tf
├── local.nsg.tf
├── local.routetable.tf
├── local.subnet.tf
├── main.tf
├── terragrunt.hcl
└── variable.tf
```

**Versions**
terragrunt version v0.53.8
Terraform v1.5.4
osx: 14.1.1

Note. If i move the genereate block for provider in this `sanbox/terragrunt.hcl` file then it works.
So only the `terragrunt.hcl` in the root is not taken into consideration. is there any command line args i can use to see which files and blocks are taken into consideration when i run terragrunt.

**Comment by denis256** [comment]
Hello,
`find_in_parent_folders()` will find the first `terragrunt.hcl` file...

as a workaround can be used different file names...

```
include "backend" {
  path = find_in_parent_folders("backend.hcl")
}

include "provider" {
  path = find_in_parent_folders("provider.hcl")
}
```

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders
