### ISSUE TITLE
Scaffold with PAT github tokens

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2835]
**Describe the solution you'd like**
Add support for handling personal access tokens in scaffolding private repos

**Describe alternatives you've considered**

It works now, but user need to pass token in url like:
```
terragrunt scaffold git::https://denis256@$GITHUB_OAUTH_TOKEN@github.com/denis256/terragrunt-tests-private.git//scaffold/default-template
```

**Additional context**

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#types-of-personal-access-tokens

**Comment by jmreicha** [comment]
I am kicking the tire now on the `scaffold` command and am liking it a lot so far. Does this mean there is not currently another way of scaffolding a private repo outside of passing the token in the URL?

**Comment by denis256** [comment]
Well, cloning through GIT+SSH is also working

**Comment by jmreicha** [comment]
Ah yep, just tried it. Good to know!
