### ISSUE TITLE
Unable to reference local variable in child from parent include

### ISSUE THREAD

**Issue by nwalter82** [gruntwork-io/terragrunt#2841]
**Describe the bug**
I am trying to use a local value defined in a child terragrunt.hcl file as part of a dependency block in a parent include.  When doing so I receive: 
`Attempt to get attribute from null value; This value is null, so it does not have any attributes., and 1 other diagnostic(s)` 

Basically I have two TF modules, one contains an application and the other contains a core VPC config for AWS.  The core VPC config is only suppose to be instantiated once but the app could be pointed to that same VPC and have multiple instantiations with different parameters or environments.

Sample Directory Structure:

App
 terragrunt.hcl (dependency to "VPC" defined here)
 -- ENV1
       terragrunt.hcl (dependency variables defined using outputs)
       eg. `dependency.vpc.outputs.database_host`
 -- ENV2
       terragrunt.hcl (dependency variables defined using outputs)
 

VPC
  terragrunt.hcl
  -- ROOTENV
       terragrunt.hcl

// paste code snippets here
 in root APP terragrunt.hcl i have:
```
 include "root" {
  path = find_in_parent_folders()
}


 dependency "vpc" {
  config_path = "${get_repo_root()}/VPC/${local.vpc_environment}"
}
```
 
 in ENV1/ENV2 i have:
`   locals {
  vpc_environment = "ROOTENV"
}`

**Expected behavior**
Should retrieve the value defined in the child locals.

**Comment by denis256** [comment]
Hello,
AFAIK locals from the child aren't available during resolution, however can be used workaround through `read_terragrunt_config` to parse the HCL file and fetch values

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_terragrunt_config

https://github.com/denis256/terragrunt-tests/tree/master/issue-2812
