### ISSUE TITLE
Add custom actions before delete a resource

### ISSUE THREAD

**Issue by javierporronluzid** [gruntwork-io/terragrunt#2844]
**Describe the solution you'd like**
The "Before Hooks" feature enables the execution of custom actions when commands like "terragrunt destroy" or "terragrunt apply" are run. However, it does not activate when "terragrunt apply" forces a resource replacement by deleting the old resource and creating a new one. For instance:
I wish to change the name of my DB resource in Azure. When applying these changes, the resource will be deleted and recreated with the new name, leading to the loss of all data.
It would be extremely beneficial to have the ability to detect the impending "destroy" action, execute a custom action (such as a backup), then proceed to destroy the resource and add the new ones.
This feature would identify when the plan intends to add, change, or destroy a resource.
An example configuration might look like:
```
terraform {
  before_hook "before_hook" {
    commands     = ["apply"]
    if_destroy   = true 
    execute      = ["echo", "Running Terraform"]
  }
}
```

**Comment by denis256** [comment]
Hm, will be challenging to detect from Terragrunt what will happen on Terraform side - simple update or destroy
