### ISSUE TITLE
Enforce workflows with Terragrunt

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terragrunt#285]
We've encountered many clients who want to standardize a "local Terraform workflow" to ensure maximum infrastructure stability. For example:

- "Always run `terraform plan` before `terraform apply`."
- "Make sure you apply a module version in a non-prod environment before you apply it in prod."

These workflows will vary from team to team and there will be situations when you want to deviate from the workflow, but perhaps it would be useful to allow `terraform.tfvars` file to declare the Terragrunt workflows you want to enforce. Terragrunt could then keep track of your "session" and ensure that you're abiding by all workflows. If you deviate, it could error out with the specific workflow you violated.

Users could then use a flag like `--override` this.

**Comment by grimm26** [comment]
I think the trick is to track that a plan has been run on the current set of changes about to be applied.  Perhaps the lock table could be overloaded to track if a plan has been run on the configs for a state file along with an checksum of the combined configs?  Or terragrunt could use an additional table to track this.

**Comment by brikis98** [comment]
This is something Terraform is working on natively, at least in terms of requiring plan: https://www.terraform.io/docs/commands/apply.html#auto-approve-true. It's currently "auto approve" by default, but they will flip that in the future.

**Comment by brikis98** [comment]
Closing in favor of #412.
