### ISSUE TITLE
0.54.7 - Terragrunt does not copy terraform files to temporary folder (causing Error: Insufficient features blocks)

### ISSUE THREAD

**Issue by si-te** [gruntwork-io/terragrunt#2859]
**Describe the bug**
In Version 0.54.7, terragrunt sometimes does not properly copy over the source terraform files to the temporary folder before executing terraform. In the temp folder, there are only the auto-generated files of terragrunt present, but not the actual terraform module that should be executed. This is causing an error during terraform execution:

```
│ Error: Insufficient features blocks
│ 
│   on <empty> line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
╵
ERRO[0015] terraform invocation failed in /.../.terragrunt-cache/JfUlXd3zAH6bUkZ5tMY9fTxo_Xg/Ee0SFduIxZ9bDEC-6oKL4gYnPz8  prefix=[/...] 
```

The generated folder looks like this:
<img width="373" alt="Screenshot 2023-12-19 at 10 20 23" src="https://github.com/gruntwork-io/terragrunt/assets/92753650/6f5897e7-bf06-4706-8f1a-04372dcbb625">

The same code works fine on Terragrunt 0.53.8. 

Terragrunt was invoked by `terragrunt --terragrunt-non-interactive --terragrunt-working-dir terragrunt/dev/apps run-all apply`

**Expected behavior**
The code should execture without error.

**Versions**
- Terragrunt version: 0.54.7 (it works fine on 0.53.8)
- Terraform version: Terraform v1.6.6
- Environment details: darwin_arm64

**Comment by denis256** [comment]
Hi,
can be shared example repository where this issue happens?

**Comment by si-te** [comment]
Unfortunately, this is a proprietary repository. I checked, the issue occurs regardless of whether TERRAGRUNT_SOURCE_UPDATE is set to true/false.
