### ISSUE TITLE
Proposed enhancement for stitching together multiple modules

### ISSUE THREAD

**Issue by jmahowald** [gruntwork-io/terragrunt#286]
Since trying terragrunt a couple of weeks ago, I've completed abandoned by attempt to normalize terraform and remote state management.

It consisted of a poorly written [Go CLI tool](https://github.com/jmahowald/formterra), some yaml templates and overly clever/stupid Makefile rules

This processed templates whose main purpose was to allow me to more quickly and consistently stitch together various terraform modules, along with use of remote state.

* [Sample Template](https://github.com/jmahowald/terraform-ecs-lab/blob/master/templates/basevpc.yml)
* [Sample Makefile](https://github.com/jmahowald/terraform-ecs-lab/blob/master/Makefile
)

This is all to say that the one thing that I think I got right (and I'm far from certain that is the case) was this concept of saying a lot of times a terraform "layer" mostly consists of modules that need to be wired together (e.g. line up outputs and inputs) along with remote state.

I'm trying to figure out whether it makes sense to try to figure out a way to bring in something similar into terragrunt,  (and using the conventions of your current syntax).

Is this idea worth pursuing?

**Comment by brikis98** [comment]
> This is all to say that the one thing that I think I got right (and I'm far from certain that is the case) was this concept of saying a lot of times a terraform "layer" mostly consists of modules that need to be wired together (e.g. line up outputs and inputs) along with remote state.

Can you give an example of what you had in mind and how that would look as part of Terragrunt? I browsed through the CLI tool and makefile/template and am not entirely following what functionality you are thinking of. Thanks!

**Comment by jmahowald** [comment]
The thinking is that a terraform file could be generated that simply composes existing remote states and modules

```hcl
terragrunt = {
  terraform {
    data {
        name = "amis"
        backend = "s3"
        config {
           bucket     = "${get_env("TF_VAR_remote_state_bucket","UNKNKOWN!!!")}"
           key        = "basevpc/terraform.tfstate"
           region     = "${get_env("TF_VAR_remote_state_bucket_region", "us-east-1")}"
        }
    }
    module {
        name = "sshkey"
        source = "github.com/jmahowald/terraform-aws-vpc//modules/keys/keygen"
        inputs {
            vars = ["key_name"]
        }
    }
    module {
        name = "keypair"
        source = "github.com/jmahowald/terraform-aws-vpc//modules/keys/awskey"
        inputs  {
            module_in {
              name = "sshkey" 
              vars = ["public_key"]
            }
        }
    }
    module {
        name = "vpc"
        source = "github.com/jmahowald/terraform-aws-vpc//modules/network" 
        inputs {
            data {
              name = "amis"
              vars = ["nat_image_id:bastion_ami"]    
            }
            vars = ["num_azs", "environment"] 
            module_in {
                name = "keypair"
                vars = ["keypair_name:key_name"]
            }      
        }
        output_vars = ["vpc_id", "public_subnet_ids", "bastion_ip"] 
    }
    module {
        name = "ecs"
        source = "github.com/jmahowald/terraform-ecs-modules//cluster" 
        inputs  {
            module_in {
              name = "vpc" 
              vars = ["vpc_id",
                      "public_subnet_ids:elb_subnet_ids",
                      "private_subnet_ids:asg_subnet_ids"
                      ]
            }
            data {
                name = "amis" 
                vars = ["ecs_ami:ami"]
            }
        }
        output_vars = ["ecs_cluster_id", "public_listener_arn"] 
    }
  }
}
```

**Comment by jmahowald** [comment]
Well you articulated my concern on why the approach is questionable from a dsl perspective.  Maybe I was just targeting an audience of one.  That being said I had wanted to make it be interactive and have smart guesses.  Other parts of that for Terri tool found outputs of modules and required vs optional inputs.  Do you see value in something generating that boilerplate by lining up obvious inputs and outputs?

**Comment by brikis98** [comment]
I think that would be an awesome addition to an IDE while coding in Terraform. Essentially, you get auto-complete based on the inputs and outputs of the modules you're using. As a standalone code generator or part of Terragrunt, I struggle to think of where or how I'd use it. Was there some specific use case you had in mind?

**Comment by jmahowald** [comment]
I think most people either underutilize modularity/building generic abilities or over do it.  I’m in the latter camp probably.  In general I find myself using many of the same building blocks for different situations, and by default wanted to type less.  I’m more than fine deferring to the guy who actually wrote the book on getting up and running with Terraform.  Let’s close this, and if I come up with an actual justification, I can make a new issue and reference this. Thanks for your time and insights.




people m over do it o

**Comment by brikis98** [comment]
Well, I agree that the way modules are chained together could be improved in Terraform. I'd especially love the ability to have "types": e.g., this module takes a `DatabaseUrl` as an input, and this module produces a `DatabaseUrl` as an output, so they can be chained together, whereas this other output is a `SecurityGroupId` and cannot be chained together. 

Anyways, new ideas are always welcome :)
