### ISSUE TITLE
Terragrunt Error removing manifest file

### ISSUE THREAD

**Issue by skkc2** [gruntwork-io/terragrunt#2864]
**Terragrunt Error removing manifest file**
I'm constantly getting the error removing .\terragrunt-module-manifest manifest file cannot run anything Terragrunt init, plan, apply, destroy nothing works.

![Screenshot 2023-12-21 121936](https://github.com/gruntwork-io/terragrunt/assets/103419632/a2397ecd-8a15-4b9f-a63b-23a82500deae)

Note : it was working fine till yesterday, my credentials are correct and terraform works fine.

**Expected behavior**
No error is expected.

**Versions**
- Terragrunt version: v0.53.8
- Terraform version: v1.6.5

**Comment by denis256** [comment]
Hi,
the issue still happen after the removal of .terragrunt-cache directory? and re-run of jobs?

**Comment by thisispaulsmith** [comment]
Problem for me too. Clear of files, still get the same error

**Comment by Tranquillo1811** [comment]
> Hi, the issue still happen after the removal of .terragrunt-cache directory? and re-run of jobs?

The first run (after deletion) is ok, bit any consecutive run then shows the error again...

**Comment by denis256** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.15

**Comment by Tranquillo1811** [comment]
Thanks you very much for solving this... User experience is so much better now. without these nasty error messages in the output!
