### ISSUE TITLE
find_in_parent_folders does not support subfolders since 0.54.9

### ISSUE THREAD

**Issue by PhilLavoie** [gruntwork-io/terragrunt#2865]
**Describe the bug**
Something like: `find_in_parent_folders("_subdir/the-file.hcl")` used to work, now it doesn't. I believe it's related to that [change](https://github.com/gruntwork-io/terragrunt/commit/88f2b0ce767136bb456781eaa23999be12bf0341#diff-d0e688afecdbfec53abb13588320250af9d176a63d0a6d3c7344f5be4f529218R495).

Reverting to 0.54.8 fixed it for me.

**To Reproduce**
Simply use a directory in your `find_in_parent_folders`, such as below:

```hcl
include "datadog" {
  path = find_in_parent_folders("_providers/datadog.hcl")
}
```

**Expected behavior**
It should go up the tree and find a match. For example, given the above block and the following tree:
```
root/
  _providers/
    datadog.hcl
  my-stuff/
    terragrunt.hcl
```

I expect terragrunt to resolve the include to `root/_providers/datadog.hcl`

**Nice to have**
- [x] Terminal output

```
ERRO[0000] ...: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFound: Could not find a _providers/datadog.hcl in any of the parent folders of ... Cause: Traversed all the way to the root.., and 1 other diagnostic(s) 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 

```

- [ ] Screenshots

**Versions**
- Terragrunt version: 0.54.9
- Terraform version: Irrelevant
- Environment details (Ubuntu 20.04, Windows 10, etc.): Irrelevant

**Additional context**
Works with 0.54.8

**Comment by levkohimins** [comment]
Sorry for the inconvenience caused. Resolved in [v0.54.10](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.10).
