### ISSUE TITLE
Unable to Configure Terragrunt with Non-Default AWS Profile

### ISSUE THREAD

**Issue by kubegurus** [gruntwork-io/terragrunt#2867]
**Description**

I'm encountering issues setting up Terragrunt to use a non-default AWS profile for assuming an IAM role when deploying infrastructure. I've followed the steps outlined in the documentation and the provided assistance, but I'm still facing challenges.

**Problem:**

Issue: Unable to configure Terragrunt to use a non-default AWS profile for IAM role assumption.
Symptoms: Getting "Error finding AWS credentials" when running Terragrunt commands with the specified non-default profile.

```
provider "aws" {
  region  = "eu-west-1"
  profile = "none-default"
  assume_role {
    role_arn = "arn:aws:iam::ACCOUNT_ID:role/RoleName" 
  }
}
```

When I setup the default profile with the same access key and secret key of "none-default" everything works fine. Do you have idea how can I fix this behavior? 

Thanks for any help!

**Comment by denis256** [comment]
Hi,
was configured "iam_role" in terragrunt.hcl? or it was set only in TF files?

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#iam_role

**Comment by kubegurus** [comment]
@denis256 yes, that’s the end result that resides in the cache
