### ISSUE TITLE
before_hook not running before

### ISSUE THREAD

**Issue by MattKitmanLabs** [gruntwork-io/terragrunt#2872]
**Describe the bug**
If I run `aws-vault exec sandbox-poweruser -- chamber exec datadog -- terragrunt plan` but my state files are all kept in production, terragrunt prompts me to create a new bucket in sandbox, then if I hit yes it creates a random bucket in sandbox and then runs the before_hook script to check that I'm attempting to run against production and tells me I'm in the wrong account. whoops too late you went and made a random bucket in sandbox.

What's going on here? It seems impossible to get the before hook to actually run before.

```bash
aws-vault exec sandbox-poweruser -- chamber exec datadog -- terragrunt plan
Remote state S3 bucket test-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) y
INFO[0016] Executing hook: terraform_account_check       prefix=[...]
!! Environment / Account mismatch !! please use:
aws-vault exec production-<engineers|poweruser> -- chamber exec datadog -- terragrunt <init|plan|apply|output|destroy>
ERRO[0016] Error running hook terraform_account_check with message: [...] exit status 1  prefix=[...]
ERRO[0016] Errors encountered running before_hooks. Not running 'terraform'.  prefix=[...]
ERRO[0016] 1 error occurred:
	* [...] exit status 1
```

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: 0.54.4
- Terraform version: 1.6.6

**Additional context**

**Comment by denis256** [comment]
Hi,
`before_hook` hook is executed before the execution of `terragrunt` command not terragrunt itself.
To run custom commands/scripts can be attempted to use `run_cmd` function.

https://terragrunt.gruntwork.io/docs/features/hooks/
https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd

**Comment by MattKitmanLabs** [comment]
@denis256,

First let me thank you for the rapid response and useful info, but I also found this `disable_init = true` seems to stop terragrunt creating any buckets.

**Comment by MattKitmanLabs** [comment]
Scrap that, with `disable_init = true` terragrunt seems to have a hard time creating new modules.
