### ISSUE TITLE
Sharing files between modules

### ISSUE THREAD

**Issue by thnee** [gruntwork-io/terragrunt#288]
I am hoping that this is just a question, and I have overlooked the answer, otherwise I guess it is an enhancement suggestion =)

Wonder if it is possible to somehow share a single file so that it can be used in multiple modules?

Assuming one is using the pattern of breaking out all modules into a separate repo, they get cloned somewhere under /tmp, so relative paths seems to be out of the question.

The docs about interpolation says:

> Terragrunt built-in functions only work within a `terragrunt = { ... }` block. Terraform does NOT process interpolations in .tfvars files

So it seems there is no way to pass a runtime-calculated absolute path as a variable value to a module? Since variables must be placed outside the `terragrunt` block?

Is there some other way to achieve this?

My specific use case is that I have written a generic `user_data.sh` script that I am using like this:

```
data "template_file" "user_data" {
  template = "${file("user_data.sh")}"
  vars = {
    playbook = "rabbitmq"
  }
}
```

But as of now, the only way I can see is to copy this file into each module where I want to use it.

**Comment by brikis98** [comment]
Why do you need to copy the file? Couldn't each module reference the file?

```hcl
data "template_file" "user_data" {
  template = "${file("${path.module}/../shared-files/user-data.sh")}"
}
```

See also the note about using double-slashes in the [remote config docs](https://github.com/gruntwork-io/terragrunt#remote-terraform-configurations).

**Comment by thnee** [comment]
Thanks for the reply. I guess your suggestion is based on having the `shared-files` dir in the modules-repo, not in the live-repo?

I think I was trying to have in the live-repo. But I guess this works just as well, thanks!

Not sure how the double-slashes relates to this? I thought they only applied to the `source` in the `terraform` block.

**Comment by brikis98** [comment]
Yes, put the shared file in the modules repo. 

If you're using that modules repo with the remote configurations (with a `source` URL in the Terragrunt config), the double-slash allows you to use relative paths. Without it, the relative paths won't work correctly.
