### ISSUE TITLE
Bump aws-sdk-go to >= v1.47.11

### ISSUE THREAD

**Issue by imishchuk-carbon** [gruntwork-io/terragrunt#2882]
Hello, team.

**Describe the solution you'd like**
I'd like `aws-sdk-go` to be bumped to at least [v1.47.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.11) so that it supports new-ish credentials chain introduced with [EKS Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html)

Currently we are using terragrunt version 

```
$ terragrunt --version
terragrunt version v0.54.12
```

and during execution of following code

```
aws_account_id = lookup(jsondecode(get_env("TF_VAR_aws_account_ids", "{}")), local.workspace, get_aws_account_id())
```

I get the following error

```
ERRO[0000] Error: Error in function call

ERRO[0000]   on /home/runner/_work/ec2-runner/ec2-runner/terragrunt.hcl line 7, in locals:
ERRO[0000]    7:   aws_account_id       = lookup(jsondecode(get_env("TF_VAR_aws_account_ids", "{}")), local.workspace, get_aws_account_id())
ERRO[0000]
ERRO[0000] Call to function "get_aws_account_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.

ERRO[0000] Encountered error while evaluating locals in file /home/runner/_work/ec2-runner/ec2-runner/terragrunt.hcl
ERRO[0000] /home/runner/_work/ec2-runner/ec2-runner/terragrunt.hcl:7,103-122: Error in function call; Call to function "get_aws_account_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

even though I can fetch creds by running

```
$ aws sts get-caller-identity --no-cli-pager
{
    "UserId": "AROAWOWMFQSCMZGF4MNLA:eks-alpha-eks-runner-3b4e4766-2af7-4bf6-952c-bc36f7a8413a",
    "Account": "************",
    "Arn": "arn:aws:sts::************:assumed-role/GitHubDeployerRole/eks-alpha-eks-runner-3b4e4766-2af7-4bf6-952c-bc36f7a8413a"
}
```

**Describe alternatives you've considered**
I can work around this issue by using defined `TF_VAR_aws_account_ids` so that code does not fallback to `get_aws_account_id()`

Thank you.

**Comment by imishchuk-carbon** [comment]
Hm, I ensured that `TF_VAR_aws_account_ids` is populated, yet for some reason terragrunt still tries to execute `get_aws_account_id()`.

Replaced `get_aws_account_id()` with dummy value and code executed correctly, without outputting `dummy`, i.e. confirming that code extracts value from `TF_VAR_aws_account_ids`

**Comment by denis256** [comment]
Hello,
upgraded SDK version in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.13 , please check if it is fixing authentification issues

**Comment by imishchuk-carbon** [comment]
Hey, @denis256 
Thank you, now it works fine.
Have a nice day.
