### ISSUE TITLE
Add information about Terraform provider plugin caching

### ISSUE THREAD

**Issue by dataviruset** [gruntwork-io/terragrunt#2892]
**Background**
On every Terragrunt plan/apply, it will download the provider plugins over and over again (not sure if this is a bug in itself), consuming several hundred megabytes on every Terragrunt run, but after enabling the `plugin_cache_dir` it stops doing so.

**Suggested solution**
In the caching [section](https://terragrunt.gruntwork.io/docs/features/caching/) of the website I think there should be a page where people are reminded to configure Terraform's provider plugin [caching](https://developer.hashicorp.com/terraform/cli/config/config-file#configuration-file-syntax). Specifically to create a `plugin_cache_dir` and add it to `~/.terraformrc` as it's very useful when working with multiple Terragrunt folders that depend on each other and have some shared dependencies like the AWS provider plugin.

**Comment by levkohimins** [comment]
Unfortunately, this will not work properly with `run-all` commands, [Why Terraform’s built-in provider caching doesn’t work](https://terragrunt.gruntwork.io/docs/features/provider-cache/#why-terraforms-built-in-provider-caching-doesnt-work).

**Comment by dataviruset** [comment]
Seems Terragrunt has implemented its own provider caching! 🎉 https://github.com/gruntwork-io/terragrunt/pull/3001
I'm gonna try it out.

**Comment by brikis98** [comment]
Yes indeed. Please try out Terragrunt's new provider caching feature: https://terragrunt.gruntwork.io/docs/features/provider-cache/.

There is more work to do, but that's captured in https://github.com/gruntwork-io/terragrunt/issues/2920, so closing in favor of that issue.
