### ISSUE TITLE
read_tfvars_file fails when reading file without any variables and with just comments

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [gruntwork-io/terragrunt#2894]
**Describe the bug**
read_tfvars_file fails when reading empty file or without any variables, just with comments starting with # character

Terragrunt fails with error:
```
Call to function "read_tfvars_file" failed: Recovering panic while parsing '/some/file/path/file.tfvars'. Got error of type 'string': unknown type implementation.
```

**To Reproduce**
I'm reading tfvars file without any variables, only comment:
file.tfvars:
```
# comment line 1
# comment line 2
```

```hcl
locals {
  cluster_common_config_path       = "some/file/path/file.tfvvars"
  cluster_config_vars = merge(
    fileexists(local.cluster_common_config_path) ? jsondecode(read_tfvars_file(local.cluster_common_config_path)) : tomap({})
  )
}
```

**Expected behavior**
read_tfvars_file should return empty map.

**Versions**
- Terragrunt version: v0.54.7
- Terraform version: v1.5.7
- Environment details (Ubuntu 22.04):

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.54.19

**Comment by MichalKoziorowski-TomTom** [comment]
Thank you :)
