### ISSUE TITLE
ref in terraform source gets truncated if containing slash

### ISSUE THREAD

**Issue by 180254** [gruntwork-io/terragrunt#2897]
**Describe the bug**
Using a git branch name containing a forward slash as ref in the terraform source results in the branch name being truncated at the slash.

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
terraform {
  source = "github.com/company-internal/some-repo.git//azure/component?ref=team/ABC-1234-component"
}
```

terminal output is:

>  ERRO[0093] Module /home/user/Desktop/dev/some-project/kubernetes/terragrunt/cpk/component has finished with an error: downloading source url git::https://github.com/company-internal/some-repo.git?ref=team
1 error occurred:
	* error downloading 'https://github.com/company-internal/some-repo.git?ref=team': /usr/bin/git exited with 1: error: pathspec 'team' did not match any file(s) known to git
  prefix=[/home/user/Desktop/dev/some-project/kubernetes/terragrunt/cpk/component] 

Equivalent that works:
```hcl
terraform {
  source = "git::https://github.com/company-internal/some-repo.git//azure/component?ref=team/ABC-1234-component"
}
```

Both source values works when ref does not contain a slash.

**Expected behavior**
 Terragrunt using the correct and complete ref.

**Nice to have**
- [X] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: terragrunt version v0.54.18
- Terraform version: Terraform v1.5.7 on linux_amd64
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 22.04.3 LTS

**Additional context**
Similar bug that has already been fixed: https://github.com/gruntwork-io/terragrunt/issues/2595
It described the same type of problem, just with a different example.

**Comment by denis256** [comment]
Seems to happen only for "short" source urls,
is handled correctly when specified: `source = "git::git@github.com:...`
