### ISSUE TITLE
Use role_arn in S3 backend

### ISSUE THREAD

**Issue by qrevel** [gruntwork-io/terragrunt#290]
Hi,

I'm using cross-account roles with clients.
I can assume a role with terraform s3 backend config but terragrunt seems to ignore the [role_arn ](https://www.terraform.io/docs/backends/types/s3.html#role_arn) parameter.

**Comment by brikis98** [comment]
Ah, you're right. Looks like Terragrunt supports these settings: https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L17-L24. But the S3 backend now supports quite a few more: https://www.terraform.io/docs/backends/types/s3.html#configuration-variables. PRs very welcome!

**Comment by brikis98** [comment]
BTW, as a workaround, you can assume an IAM role using env vars plus the AWS CLI. You call [assume-role](http://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html) and set the returned `AccessKeyId`, `SecretAccessKey`, and `SessionToken` as the env vars `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`, respectively. Both Terraform and Terragrunt would pick those up automatically.

**Comment by qrevel** [comment]
That's what I'm doing actually but it's a bit overwhelming.
I'm not a go developer (yet) so I hope someone will find the time to do it :)

**Comment by adampie** [comment]
@qrevel I'm having a look at this as well, need it for cross-account buckets using assume roles. Will do a PR if I get it working.
