### ISSUE TITLE
[Dynamic configuration] - manage hundreds of accounts

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#2902]
**Describe the solution you'd like**
I need to catch up on the features available in Terragrunt. 

Please let me know if a particular feature exists and provide guidance if possible

**Describe alternatives you've considered**
Need manage hundreds of accounts, 

```
├── aws
│   ├── _envcommon
│   │   ├── README.md
│   │   └── app-1.hcl # with default values
│   │   └── app-2.hcl # with default values
│   │   └── app-3.hcl # with default values
│   ├── modules
│   │   └── app-module-1
│   │       └── main.tf
│   │   └── app-module-2
│   │       └── main.tf
│   │   └── app-module-3
│   │       └── main.tf
│   ├── terragrunt.hcl
│   ├── account-1
│   │   ├── account.hcl
│   │   └── ap-southeast-2
│   │       ├── app-1
│   │       │   └── terragrunt.hcl
│   ├── account-2
│   │   ├── account.hcl
│   │   └── ap-southeast-2
│   │       ├── app-1
│   │       │   └── terragrunt.hcl
│   │       ├── app-2
│   │       │   └── terragrunt.hcl
│   ├── account-3
│   │   ├── account.hcl
│   │   └── ap-southeast-2
│   │       ├── app-2
│   │       │   └── terragrunt.hcl
│   │       ├── app-3
│   │       │   └── terragrunt.hcl
│   │       └── region.hcl
...
```

So in above sample, if I need manage 100 accounts, I need repeat the part of `account-XXX` hundred times.

```
# depends on the applications will be deployed to account xxx
│   ├── account-XXX
│   │   ├── account.hcl
│   │   └── ap-southeast-2
│   │       ├── app-1
│   │       │   └── terragrunt.hcl
│   │       ├── app-2
│   │       │   └── terragrunt.hcl
│   │       ├── app-3
│   │       │   └── terragrunt.hcl
│   │       └── region.hcl
```

 The only differences between them are two files:
 
 * account.hcl # which includes the account id 
 * terragrunt.hcl # which includes the variables input
 
 How can I manage hundreds of accounts with a template I can reference and copy from and only update with `account.hcl` and input part of `terragrunt.hcl`? So I don't have to repeat the codes?
 
**Additional context**
[Design diagram](https://excalidraw.com/#json=XCpRVv6yVgiPvrgYbSJiE,6e_nt_mSt7jWsBztMyrYAA)

![Untitled-2024-01-20-1555](https://github.com/gruntwork-io/terragrunt/assets/8954908/23aee54c-d963-4b8c-b582-87b599351dd2)

**Comment by yhakbar** [comment]
Hey @ozbillwang , 

It sounds like you're looking to leverage [find_in_parent_folders](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders). That will let you build out the hierarchy of configurations, as the `terragrunt.hcl` files can `include` the `account.hcl` and `region.hcl` files found in parent folders. 

If you are looking for a solution to minimize the work required to stamp out the `terragrunt.hcl` configurations that leverage those includes, you can look to utilize [boilerplate](https://github.com/gruntwork-io/boilerplate) to automate that process in a script.

**Comment by ozbillwang** [comment]
nice, seems [boilerplate](https://github.com/gruntwork-io/boilerplate) is similar to j2. I will take a try.
