### ISSUE TITLE
Logging output during terragrunt output makes some scripting difficult

### ISSUE THREAD

**Issue by jmahowald** [gruntwork-io/terragrunt#291]
in the past, I'd have a command like

` ecs-cli compose service up --cluster  $(terraform output cluster_name)`

This doesn't work as well with terragrunt, as the actual stdout of that command is

``
 echo $cluster_name
[0m[1mCopying configuration[0m from "file:///Users/josh/workspace/backpackhealth/backpackinfra"...[0m [0m[1mTerraform initialized in an empty directory![0m The directory has no Terraform configuration files. You may begin working with Terraform immediately by creating Terraform configuration files.[0m dev-green-ecs
``

**Comment by brikis98** [comment]
Please check if the latest version of Terragrunt fixes this issue for you: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.13.2

**Comment by jmahowald** [comment]
Yup.  Thanks!
