### ISSUE TITLE
Terragrunt graph command

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2911]
**Describe the solution you'd like**
Will be helpful if Terragrunt could handle modules dependency graph and run Terraform commands only on dependent modules

Example having bellow dependencies:

![dependency-graph](https://github.com/gruntwork-io/terragrunt/assets/10694338/31b67edf-0bcf-406f-9a88-d7ed0e47caf7)

* If I run `graph apply` on `eks`, will be applied `eks` and all dependent modules: service-1, service-2....

* If I run `graph destroy` in `eks` will be destroyed first "top" modules "service-4", "service-3-v3"... and in the end only `eks`, not dependent modules like "lambda" will not be affected.

* If I run `graph apply` in `service-3` directory, then will be applied "service-3" and dependent modules - "service-4", "service-3-v2", "service-3-v3"

**Describe alternatives you've considered**
Tried to use `run-all` but it is handling only modules in current directory and destroy not related modules like "lambda"

**Additional context**
N/A

**Comment by josh-padnick** [comment]
Could you clarify what you mean by a "related" module? For example, in the graph above, it looks like the lambda tree and eks tree are completely independent.

Also, what kind of behavior are you thinking for when `terragrunt graph apply` is run in a folder with multiple subfolders, each of which has a `terragrunt.hcl` file?

**Comment by motatoes** [comment]
Hello Terragrunt community. I think you should consider this feature for terragrunt, in the absence of an ordered apply, and detection of modified stacks the community has resorted to solutions such as terragrunt-atlantis-config (https://github.com/transcend-io/terragrunt-atlantis-config) and similar in digger to parse terragrunt.hcl directory structure and figure out the dependencies, then run them in the right order. terragrunt-atlantis-config however is a no longer maintained project and has lots of bugs, edgecase

Effectively its a very strong requirement for any large terragrunt project running in cicd pipelines, a native solution that is also exposable to other CICD tools would be a much better solution IMHO, as opposed to `run-all` which doesn't cut it when it comes to larger terragrunt projects

**Comment by denis256** [comment]
The example directory structure is like this:
```
├── eks
│   ├── main.tf
│   └── terragrunt.hcl
├── lambda
│   ├── main.tf
│   └── terragrunt.hcl
└── services
    ├── eks-service-1
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-2
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-2-v2
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-3
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-3-v2
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-3-v3
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-4
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── eks-service-5
    │   ├── main.tf
    │   └── terragrunt.hcl
    ├── lambda-service-1
    │   ├── main.tf
    │   └── terragrunt.hcl
    └── lambda-service-2
        ├── main.tf
        └── terragrunt.hcl
```

> Could you clarify what you mean by a "related" module? For example, in the graph above, it looks like the lambda tree and eks tree are completely independent.

"related" modules are ones with "dependency" pointing to "eks"
```
dependency "eks" {
  config_path = "../../eks"
}
```

The "Lambda" case is more to show that these dependencies will be ignored during `graph` on "eks".

> Also, what kind of behavior are you thinking for when `terragrunt graph apply` is run in a folder with multiple subfolders, each of which has a terragrunt.hcl file?

I think as in other cases, should be created graph of dependent modules from the current directory, and executed respective commands.

For example, having this structure:
```
./ecs/
├── ecs-1
│   ├── main.tf
│   └── terragrunt.hcl
├── ecs-2
│   ├── ecs-2-v2
│   │   ├── main.tf
│   │   └── terragrunt.hcl
│   ├── main.tf
│   └── terragrunt.hcl
├── main.tf
├── terragrunt.hcl
└── vpc
    ├── main.tf
    └── terragrunt.hcl 
```
where all ecs-* modules have a dependency to parent terragrunt.hcl and vpc/terragrunt.hcl don't have a dependency on parent ecs/terragrunt.hcl.

If I will do `run-all`, it will apply/destroy `vpc` directory too - which in some cases may not be helpful... for example if I changed something in common in parent for ecs modules.

If I will run `graph apply` will be applied only "ecs-*" modules(since they have dependency pn parent)
```
$ terragrunt graph apply
INFO[0000] The stack at ecs will be processed in the following order for command apply:
Group 1
- Module ecs

Group 2
- Module ecs/ecs-1
- Module ecs/ecs-2
- Module ecs/ecs-2/ecs-2-v2

$ terragrunt graph destroy
Group 1
- Module ecs/ecs-1
- Module ecs/ecs-2
- Module ecs/ecs-2/ecs-2-v2

Group 2
- Module ecs
```

**Comment by motatoes** [comment]
In addition to the suggestion of applying commands mentioned by OP it would be great to have a lower level command to expose the entire graph, helpful for debugging and external CICD integrations, for example:

```
$ terragrunt graph list

```
Module eks
- depends on: []

Module services/eks-service1
- depends on: [eks]

Module services/eks-service2
- depends on: [eks]

Module services/eks-service3
- depends on: [services/eks-service1, services/eks-service2]

Module services/eks-service4
- depends on: [services/eks-service3]

Module services/eks-service5
- depends on: [services/eks-service2, eks]

Module services/eks-service3-v2
- depends on: [services/eks-service3]

Module services/eks-service3-v3
- depends on: [services/eks-service3-v2]

Module lambda
- depends on: []

Module services/lambda-service1
- depends on: [lambda]

Module services/lambda-service2
- depends on: [lambda]

```
# list all modules in toplogical sorted order which will represent the right order of applying
$ terragrunt graph toposort

eks
services/eks1-service1
services/eks-service2
services/eks-service3
services/eks-service5
services/eks-service4
services/eks-service3-v2
services/eks-service3-v3
lambda
services/lambda-service1
services/lambda-service2
```

**Comment by denis256** [comment]
Initial release of graph command is included in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.0
