### ISSUE TITLE
Terragrunt Module Support

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#2913]
**Describe the solution you'd like**
First-class, native module system for Terragrunt to allow for reproducible, versioned and upgrade-able Terragrunt configurations.

**Describe alternatives you've considered**
- Using [Terragrunt includes](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#include): Only work in the local filesystem and can be problematic when renaming (if you rename the thing you include everywhere, you also have to update the `terragrunt.hcl` files everywhere.
- Merging multiple [read_terragrunt_config](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#read_terragrunt_config) calls: Same problems includes have.

**Additional context**
As it currently stands, there's no standard way of having something akin to a Terraform/Tofu module for Terragrunt. The same reasons having those available are advantageous apply to having Terragrunt modules. The same go-getter logic would serve to allow for shared Terragrunt configurations to be referenced locally or remotely and merged into local `terragrunt.hcl` configurations.

This feature request will tie into another feature request for expanded monorepo tooling in Terragrunt that I'll write up soon.

**Comment by josh-padnick** [comment]
@yhakbar Could you share a brief pseudocode mockup of how a Terragrunt module might be represented?

**Comment by yhakbar** [comment]
@josh-padnick 

Sure thing! I've been writing this up between things throughout the day, but probably have been commenting it in pieces rather than all at once, given the current length.

One way this could be implemented is to add a new `module.hcl` (or `mod.hcl`, `terragrunt.mod.hcl`, etc) file that can be optionally included in folders that contain `terragrunt.hcl` files. This file would define metadata about the Terragrunt module that is present in the folder, and any modules that it relates to. An optional `terragrunt-workspace.yml` file located at the root of the repository could help with module discovery and ignores (a la [pnpm workspaces](https://pnpm.io/workspaces)).

## Current Approach to Keeping Code DRY

Currently trying to keep Terragrunt code DRY frequently results in a directory structure like the following:

```bash
❯ tree
.
├── _shared
│   └── services
│       └── example.hcl
├── live
│   ├── dev
│   │   ├── environment.hcl
│   │   └── services
│   │       └── example
│   │           └── terragrunt.hcl
│   └── prod
│       ├── environment.hcl
│       └── services
│           └── example
│               └── terragrunt.hcl
└── terragrunt.hcl
```

Where the root `terragrunt.hcl` has the configurations common to all Terragrunt configurations in the repo, usually including logic for things like:
- provider configurations
- remote state configurations
- globally accessible inputs
- global `terraform` configurations like including a `-lock-timeout` configuration
- providing location in the filesystem from which to derive a `path_relative_to_include()` for state.

The `_shared/services/example.hcl` would define all the configurations shared amongst all `example` services, regardless of environment.

The `environment.hcl` would define all the configurations shared amongst all resources in a given environment.

The leaf `terragrunt.hcl` files would do the work of stitching together all the configurations in a way that works like so:

```hcl
include "root" {
    path = find_in_parent_folders()
}

include "example" {
    path = "${get_repo_root()}/_shared/services/example.hcl"
}

locals {
    environment = read_terragrunt_config(find_in_parent_folders("environment.hcl")).inputs
}

inputs = merge(
    local.environment,
    {
        // Inputs specific to this terragrunt.hcl file.
    }
)
```

## Problems With Current Approach to Keeping Code DRY

One of the problems with this approach is that all of the configurations have to exist in the same version on the same filesystem to work. There's no way (that I know of) to reference remote configurations for how an `example` service works for example. 

Additionally, if an organization has many repos that provision `example` services across different environments, they have to use codegen or copy + paste to setup the logic for an `example` service in each repo. In addition, the configuration for the leaf `terragrunt.hcl` files will be copy + paste duplicates of each other each time, unless there's some logic that's specific to a given environment, etc.

This system can also be brittle, as adjustments to the root `terragrunt.hcl` file necessarily change the configurations for all leaf nodes at the same time, given that they all inherit configurations from it. Similarly, changing the configurations for the `example` service necessarily updates the configurations for all environments at the same time, within a given repository. Manual work or external tooling has to be used to safely propagate the change across environments instead of applying it everywhere at once (if that's even desired). If multiple repositories copy + paste the `example` service configurations, this problem expands as work has to be done to propagate the changes safely across repos as well.

Renaming folders/files are also problematic due to this, as renaming a folder changes the path from the root `terragrunt.hcl` to the leaf `terragrunt.hcl` file, requiring manual state manipulation to avoid recreating resources. Renaming the `example` service folder can also cause problems, as all the references to that shared module become invalidated. If no `terragrunt` operations are run in those folders, it might not even be immediately obvious that a problem has occurred.

## Why Modules Would Help

Consider the following directory structure:

```bash
❯ tree
.
├── _shared
│   ├── backends
│   │   └── s3
│   │       ├── module.hcl
│   │       └── terragrunt.hcl
│   ├── providers
│   │   └── aws
│   │       ├── module.hcl
│   │       └── terragrunt.hcl
│   └── services
│       └── example
│           ├── module.hcl
│           └── terragrunt.hcl
└── live
    ├── dev
    │   ├── environment.hcl
    │   └── services
    │       ├── category.hcl
    │       └── example
    │           └── module.hcl
    └── prod
        ├── module.hcl
        └── services
            └── example
                └── module.hcl
```

This structure allows for a cleaner distinction of where core Terragrunt configurations are being defined and where logic is being done to relate different Terragrunt configurations to each other. Each `module.hcl` file indicates that either a piece of re-usable Terragrunt configuration is being defined in that directory as a module, and defining any modules it uses.

 As a consequence, code re-use in Terragrunt could look more like this:

```hcl
# live/dev/services/example/module.hcl
module {
    name = "example"
    path = "live/${locals.environment}/${locals.category}/${module.name}"
}

locals {
    environment = read_terragrunt_config(find_in_parent_folders("environment.hcl")).inputs.environment
    category = read_terragrunt_config(find_in_parent_folders("category.hcl")).inputs.category
}

dependencies = {
    "backend": "backends/s3",
    "provider": "providers/aws",
    "example: "services/example",
}
```

The module defined in `live/dev/services/example/module.hcl` would be able to depend on configurations for things like the backend, the provider and the shared configuration for the example service without relying on fixed file system paths or filenames. Under the hood, those dependencies would likely just be `include`s discovered via the module system using the `path` value in their `module.hcl` files.

This is what the `_shared/backends/s3/module.hcl` file would look like:

```hcl
# _shared/backends/s3/module.hcl
module {
    name = "s3"
    path = "backends"
    description = "Defines the backend configurations for the S3 backend, following best practices in our organization."
}
```

The fact that the path is `backends` and the name is `s3` is what would allow for it to be discovered for use as a dependency in the local repository regardless of where it's located.

Those configurations could also be located in different repos if the right-hand side supported go-getter style references like the following:

```hcl
dependencies = {
    "backend": "git@github.com/acme/terragrunt-modules//backends/s3?ref=v0.0.1",
}
``` 

Within the `terragrunt.hcl` file for the `s3` `backend` module, minimal configurations like the following could be used:

```hcl
locals {
    environment = read_terragrunt_config(find_in_parent_folders("environment.hcl")).inputs.environment
    category = read_terragrunt_config(find_in_parent_folders("category.hcl")).inputs.category
    key = "live/${locals.environment}/${locals.category}/${parent.module.name}/terraform.tfstate"
}

remote_state {
  backend = "s3"
  config = {
    key            = local.key
    bucket         = "example-bucket"
    region         = "us-east-1"
    dynamodb_table = "tf-locks"
    encrypt        = true
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

This allows for the state configuration to be stored in a dynamic fashion that doesn't rely on the file system path remaining static. This would allow for file renames to occur without issue and state would not have to be moved unless desired.

I have gone on too long with this comment, so I will pause here and see if anything that I've shared so far is desirable.

**Comment by yhakbar** [comment]
The framing of this proposed solution is derived from a working prototype in a private repo that I have leveraging [pnpm](https://pnpm.io/) and [turborepo](https://turbo.build/repo) that results in weird (but working) `terragrunt.hcl` files that look like this:

```hcl
include "lambda_api" {
  path = "./node_modules/@tg/lambda-lb/main.hcl"
  merge_strategy = "deep"
}

include "provider" {
  path = "./node_modules/@tg/regions/us-east-1/provider.hcl"
  merge_strategy = "deep"
}

include "state" {
  path = "./node_modules/@tg/accounts/tcs/state.hcl"
  merge_strategy = "deep"
}

include "dns" {
  path = "./node_modules/@tg/accounts/tcs/dns.hcl"
  merge_strategy = "deep"
}

locals {
  product        = read_terragrunt_config(find_in_parent_folders("product.hcl")).inputs
  environment = read_terragrunt_config(find_in_parent_folders("environment.hcl")).inputs
}

inputs = merge(
  local.product,
  local.environment,
  {
    name = "monorepo-api"

    filename = "./node_modules/api/target/lambda/api/bootstrap.zip"
    handler  = "bootstrap.handler"
    runtime  = "provided.al2"

    architectures = ["arm64"]

    payload_format_version = "2.0"

    timeout = 5
  }
)
```

As the prototype is a lot to dive into in a comment or issue, I'm happy to share it in a screen share if interested.
