### ISSUE TITLE
Can I upgrade terraform version and terragrunt version after Terraform change to the MPL v2 license

### ISSUE THREAD

**Issue by wangzhihaocom** [gruntwork-io/terragrunt#2914]
After Terraform changed to the MPL v2 license, We see your post a blog here
https://blog.gruntwork.io/the-impact-of-the-hashicorp-license-change-on-gruntwork-customers-5fcd096ba86a

So that we did not upgrade to the latest version for both Terraform and Terragrunt.
We are just wondering that we cannot upgrade the Terraform and Terragrunt versions forever. Or Is there a furniture plan on this 

1. We would like to get some confirmation from you. Or any update?

2. Should We change to use OpenTofu instead of Terrafrom?
3. Can we continues to use Terraform in the future

Thanks so much

**Comment by denis256** [comment]
Hi,
so far, we have a compatibility page: https://terragrunt.gruntwork.io/docs/getting-started/supported-versions/ which lists supported versions of OpenTofu, Terraform.

**Comment by wangzhihaocom** [comment]
@denis256 Thanks for your update

1. Should We change to use OpenTofu instead of Terrafrom in the future?

2. Can we continue to use Terraform in the future?

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by denis256** [comment]
https://github.com/gruntwork-io/terragrunt/issues/3037#issuecomment-2040554530
