### ISSUE TITLE
Create Terragrunt `ops` subcommand

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#2916]
**Describe the solution you'd like**
Terragrunt performs some actions that are useful operational procedures that don't need to be a part of the configuration syntax or to be run during normal usage of Terragrunt.

An example of this is remote state creation. During an apply, Terragrunt will attempt to create remote state before proceeding with other activity. This can be surprising if folks haven't given their CI permissions to create state resources and get errors that they don't have permissions to create buckets in the account, etc.

Having an `ops` subcommand would allow for operations like:

```bash
terragrunt ops state create
```

To do the pre-hook that is currently run explicitly. This can be a good way to make it easy to setup state resources without doing it in a way that is surprising to folks.

Down the line, this would open the door for some convenient mechanisms like:

```bash
terragrunt ops state mv 'old/path/to/folder' 'new/path/to/file'
```

And Terragrunt could handle performing the state migration that's usually involved with renaming the folder containing a `terragrunt.hcl` file (assuming the user is using the file path to the `terragrunt.hcl` file to determine the path in state). 

**Describe alternatives you've considered**
- Running `terragrunt init` as a separate step before running `terragrunt plan/apply`: This is not supposed to be necessary and is still not obviously creating state resources.
- Running `terragrunt state pull > /tmp/state.tfstate && cd ../new/path/to/file && terragrunt state push /tmp/state.tfstate`: This is something that can be automated by Terragrunt, and would be a common activity for users if they do enough Terragrunt.

**Additional context**
This relates to [this old issue](https://github.com/gruntwork-io/terragrunt/issues/2209) discussing the drawbacks to having state resources auto-generated.

**Comment by josh-padnick** [comment]
This is a neat idea. I'm always a fan of taking "magic" (like automatic S3 bucket creation) explicit and configurable.

Does `terragrunt ops` really just concern operations on state files -- in which case we could call it `terragrunt state` --, or do you see it as more general in nature?

**Comment by yhakbar** [comment]
I would hesitate to call it `terragrunt state`, as that would collide with the Terraform/Tofu [state subcommand](https://developer.hashicorp.com/terraform/cli/commands/state).

I think putting this kind of logic behind a subcommand that is unlikely to collide with TF functionality makes it easier to flesh it out without double-checking each time if TF has that subcommand. If all of this type of thing is done behind an `ops` subcommand, then worst case scenario we would have to introduce a `--use-tf-ops` flag if they introduce it as a subcommand.
