### ISSUE TITLE
non interactive for bucket create, confirm  "y" automatically

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#2925]
**Describe the solution you'd like**

When run `terragrunt plan`, get this

> Remote state S3 bucket `xxxx-terraform-state` does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)

Are there any parameter with `terragrunt plan` to confirm "y" automatically?

I run it in pipeline, and need non interactive for bucket create.

![image](https://uploads.linear.app/bf05a48c-6664-435c-bf53-fcd1740f6ed1/6e880b10-3dec-439e-a3e4-0717120c68eb/1120ac51-ce35-432b-b2a3-f2ba696d7fde?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JmMDVhNDhjLTY2NjQtNDM1Yy1iZjUzLWZjZDE3NDBmNmVkMS82ZTg4MGIxMC0zZGVjLTQzOWUtYTNlNC0wNzE3MTIwYzY4ZWIvMTEyMGFjNTEtY2UzNS00MzJiLWIyYTMtZjJiYTY5NmQ3ZmRlIiwiaWF0IjoxNzA2ODExNTQ2LCJleHAiOjMzMjc3MzcxNTQ2fQ.GotaPH9w9CL29Tfn7sx0-VSAp28KMk3mJNUXSt2ylIg)

**Comment by yhakbar** [comment]
@ozbillwang , are you using [--terragrunt-non-interactive](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-non-interactive)?

**Comment by denis256** [comment]
Hi,
also if state bucket already exists and you don't want to update it, can be used `--terragrunt-disable-bucket-update`

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-disable-bucket-update

**Comment by ozbillwang** [comment]
Thanks, @yhakbar  & @denis256 

it works.
