### ISSUE TITLE
Improve HCL formatting to work with stdin and stdout

### ISSUE THREAD

**Issue by denis256** [gruntwork-io/terragrunt#2926]
**Describe the solution you'd like**
Improve Terragrunt `hclfmt` command to work with stdin and stdout to make Terragrunt easier to integrate into auto-formatting invocations from IDEs

**Describe alternatives you've considered**
Used script which read stdin, save in a temp file, format file, write to stdout...

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/orgs/gruntwork-io/discussions/801)

**Comment by chinyongcy** [comment]
Need this to work with zed as well

**Comment by caseycs** [comment]
In the meantime simple wrapper bash script can help: https://gist.github.com/caseycs/8a1d528b7072d9d7e20bde54b01b27a8

**Comment by chinyongcy** [comment]
> In the meantime simple wrapper bash script can help: 
> 
> 
> 
> ```shell
> 
> #!/bin/sh
> 
> # wrapper to format hcl passed via stdin
> 
> # user for for VSCcode Custom Local Formatters extension (https://marketplace.visualstudio.com/items?itemName=jkillian.custom-local-formatters)
> 
> # or any other editor relying on stdin/stdout for formatting, like Zed
> 
> # relevant issues:
> 
> # * https://github.com/gruntwork-io/terragrunt/issues/1037
> 
> # * https://github.com/gruntwork-io/terragrunt/issues/2926
> 
> TMPFILE=$(mktemp)
> 
> cat - > $TMPFILE
> 
> terragrunt hclfmt --terragrunt-hclfmt-file $TMPFILE
> 
> cat $TMPFILE
> 
> rm $TMPFILE
> 
> ```
> 
> 
> 
> 
> 
> 

This is perfect, thank you!
