### ISSUE TITLE
terragrunt backend issue

### ISSUE THREAD

**Issue by veeraragavan52jtb** [gruntwork-io/terragrunt#2928]
I have a same issue, we have the remote state configured, and when we run the pipeline we get below error.

locals {
client_name = "$(client_name)"
client_short = "$(client_short)"
location = "$(location)"
Bucket_subscription_id = "$(SUBSCRIPTION_ID)" # Storage Account Subscription
Bucket_Tenant_id = "$(TENANT_ID)" # Storage Account Tenant
resource_group_name = "$(terraformstoragerg)"
storage_account_name = "$(terraformstorageaccount)"
container_name = lower("terraform-${local.client_short}")

temp_env                = upper(split("/","${path_relative_to_include("root")}")[0])
}

remote_state {
backend = "azurerm"
config = {
resource_group_name = local.resource_group_name
storage_account_name = local.storage_account_name
container_name = local.container_name
key = lower("${path_relative_to_include()}-terraform.tfstate")
subscription_id = local.Bucket_subscription_id
tenant_id = local.Bucket_Tenant_id
}
}

Error:

time=2024-02-05T10:18:47Z level=error msg=Found remote_state settings in C:/agent/_work/1/s/environment/terragrunt.hcl but no backend block in the Terraform code in C:/agent/_work/1/s/environment. You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

terraform {
backend "azurerm" {}
}

When I add the Terraform backend, I get it is not expected here.

time=2024-02-05T14:48:24Z level=error msg=C:/agent/_work/1/s/environment/terragrunt.hcl:28,3-10: Unsupported block type; Blocks of type "backend" are not expected here.
time=2024-02-05T14:48:24Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1

I'm not sure, where it is getting wrong.

**Comment by denis256** [comment]
Hi,
it is not clear where `terraform` was added, it should be added in `tf` file

Simplified example in:
https://github.com/denis256/terragrunt-tests/tree/master/issue-2928
