### ISSUE TITLE
Terragrunt says it has destroyed but the resource remains active in AWS

### ISSUE THREAD

**Issue by manumaan** [gruntwork-io/terragrunt#2932]
**Describe the bug**
I used terragrunt run-all destroy to tear down infra. 
The output shows all the expected resources to be teared down, and then shows that it has destroyed it. 
But when i look in AWS the resource still remains. (aws-instance terragrunt-instance in this example)

```hcl
[// paste code snippets here](https://github.com/manumaan/my-terragrunt-demo/tree/main)
```

**Expected behavior**
Resources noted as destroyed should be destroyed.

**Nice to have**
Terminal output:
Terraform will perform the following actions:

  # aws_instance.instance will be destroyed
  - resource "aws_instance" "instance" {
      - ami                                  = "ami-090fa75af13c156b4" -> null
      - arn                                  = "arn:aws:ec2:us-east-1:644107485976:instance/i-0e52f516cebac372b" -> null
      - associate_public_ip_address          = true -> null
      - availability_zone                    = "us-east-1d" -> null
      - cpu_core_count                       = 1 -> null
      - cpu_threads_per_core                 = 1 -> null
      - disable_api_stop                     = false -> null
      - disable_api_termination              = false -> null
      - ebs_optimized                        = false -> null
      - get_password_data                    = false -> null
      - hibernation                          = false -> null
      - id                                   = "i-0e52f516cebac372b" -> null
      - instance_initiated_shutdown_behavior = "stop" -> null
      - instance_state                       = "running" -> null
      - instance_type                        = "t2.micro" -> null
      - ipv6_address_count                   = 0 -> null
      - ipv6_addresses                       = [] -> null
      - monitoring                           = false -> null
      - placement_partition_number           = 0 -> null
      - primary_network_interface_id         = "eni-07cd7907d40cb8ccb" -> null
      - private_dns                          = "ip-172-31-22-144.ec2.internal" -> null
      - private_ip                           = "172.31.22.144" -> null
      - public_dns                           = "ec2-3-91-154-226.compute-1.amazonaws.com" -> null
      - public_ip                            = "3.91.154.226" -> null
      - secondary_private_ips                = [] -> null
      - security_groups                      = [
          - "default",
        ] -> null
      - source_dest_check                    = true -> null
      - subnet_id                            = "subnet-025ef16cd7acb42c2" -> null
      - tags                                 = {
          - "Name"        = "dev-instance"
          - "account_tag" = "dev-account"
          - "region_tag"  = "us-east-1-region"
        } -> null
      - tags_all                             = {
          - "Name"        = "dev-instance"
          - "account_tag" = "dev-account"
          - "region_tag"  = "us-east-1-region"
        } -> null
      - tenancy                              = "default" -> null
      - user_data_replace_on_change          = false -> null
      - vpc_security_group_ids               = [
          - "sg-040f3d62e47b9a29f",
        ] -> null

      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      - cpu_options {
          - core_count       = 1 -> null
          - threads_per_core = 1 -> null
        }

      - credit_specification {
          - cpu_credits = "standard" -> null
        }

      - enclave_options {
          - enabled = false -> null
        }

      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_protocol_ipv6          = "disabled" -> null
          - http_put_response_hop_limit = 1 -> null
          - http_tokens                 = "optional" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }

      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/xvda" -> null
          - encrypted             = false -> null
          - iops                  = 100 -> null
          - tags                  = {} -> null
          - throughput            = 0 -> null
          - volume_id             = "vol-03a8ada3ab1d7ac82" -> null
          - volume_size           = 8 -> null
          - volume_type           = "gp2" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
aws_s3_bucket_public_access_block.demo_bucket_public_access_block: Destroying... [id=tf-grunt-project-dev-demo-bucket20240206101432378400000001]
aws_instance.instance: Destroying... [id=i-083fce4a54fbfd48c]
aws_instance.instance: Destroying... [id=i-0e52f516cebac372b]
aws_s3_bucket_public_access_block.demo_bucket_public_access_block: Destruction complete after 0s
aws_s3_bucket.demo_bucket: Destroying... [id=tf-grunt-project-dev-demo-bucket20240206101432378400000001]
aws_s3_bucket.demo_bucket: Destruction complete after 0s

Destroy complete! Resources: 2 destroyed.
aws_instance.instance: Still destroying... [id=i-083fce4a54fbfd48c, 10s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 10s elapsed]
aws_instance.instance: Still destroying... [id=i-083fce4a54fbfd48c, 20s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 20s elapsed]
aws_instance.instance: Destruction complete after 30s

Destroy complete! Resources: 1 destroyed.
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 30s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 40s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 50s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 1m0s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 1m10s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 1m20s elapsed]
aws_instance.instance: Still destroying... [id=i-0e52f516cebac372b, 1m30s elapsed]
aws_instance.instance: Destruction complete after 1m30s

**Versions**
terragrunt version v0.55.1
Terraform v1.7.2
- Environment details Mac OS X 14.2 M1 Chip

**Additional context**

**Comment by denis256** [comment]
Hello,

It would be helpful to have a repository where this issue occurs. Additionally, I would like to point out that the destruction of resources is not performed by Terragrunt, but by Terraform. There might be an issue with the Terraform code used to destroy resources.
