### ISSUE TITLE
Can't use both terraform source + include

### ISSUE THREAD

**Issue by davidbornitz** [gruntwork-io/terragrunt#2933]
**Describe the bug**
When using both an include block and a terraform remote block in terragrunt.hcl results in the include block being ignored

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

A parent terragrunt.hcl contains blocks to generate backend.tf and provider.tf.  These work when running terragrunt from the parent directory.

```hcl
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket = "mybucket"

    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "app-state"
  }
}
```
Child directory contains:
```hcl
include "root" {
  path   = "/absolute/path/to/parent/terragrunt.hcl"
}

terraform {
  source = "git::https://github.com/foo/myrepo.git?ref=v0.0.1"
}
```

The behavior I get is consistent with no state file existing.  I can also see that no new provider.tf or backend.tf are created in the child directory. If I remove either the `include` block or the `terraform` block, either will work.  Won't work together though.

**Expected behavior**
I expect Terragrunt to pull the configuration files at "git::https://github.com/foo/myrepo.git?ref=v0.0.1", then also generate the provider.tf and backend.tf files as defined in the parent terragrunt.hcl

**Versions**
- Terragrunt version: v0.55.0
- Terraform version: v1.6.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): mac osx

**Additional Context**
New to Terragrunt, maybe there is a different way I should achieve this?

**Comment by denis256** [comment]
Hi,
it is not clear for me where generated `backend.tf` should be, by default, it is in `.terragrunt-cache`

```
$ terragrunt apply
$ find . -name "backend.tf"
./.terragrunt-cache/J8FhtZ1-QGJJTendjUbxnf9S30E/SnMEXfZEvz37We0nU3Gh7JoDfRI/modules/test-file/backend.tf
```

https://github.com/denis256/terragrunt-tests/blob/master/issue-2933/app/terragrunt.hcl

**Comment by davidbornitz** [comment]
I have two directories:
/project/ <- parent directory
/project/terragrunt-test <-child directory

I do see the backend.tf being created in the .terragrunt-cache location now that you pointed it out.  But my expectation is that it would be created in the same child directory where I'm running terragrunt.  That's where it's created if I run terragrunt without the `terraform` block.

Moreover, when `terragrunt plan` and `terragrunt apply` is run from the child directory, it is not including anything from here: `./.terragrunt-cache/J8FhtZ1-QGJJTendjUbxnf9S30E/SnMEXfZEvz37We0nU3Gh7JoDfRI/modules/test-file/backend.tf` 

This is successful but seems so wrong:
```
terragrunt init
cd ./.terragrunt-cache/J8FhtZ1-QGJJTendjUbxnf9S30E/SnMEXfZEvz37We0nU3Gh7JoDfRI/modules/test-file/
terragrunt plan
terragrunt apply
```

**Comment by davidbornitz** [comment]
Thank you!  You were right - I had an issue with the Terraform files from the remote repo.  After fixing that, issue is resolved and behaves as expected.
