### ISSUE TITLE
`find_in_parent_folders` throws errors and warnings in some cases when used from a dependency

### ISSUE THREAD

**Issue by Heldroe** [gruntwork-io/terragrunt#2941]
**Describe the bug**
`find_in_parent_folders` used in dependencies throws errors and warnings. It seems that in dependencies, instead of being searched from the dependency, `find_in_parent_folders` is searching from the current project instead and throws errors.

This appeared in 0.55.2 and does not appear in 0.55.1.

The project still works but error messages appear which pollute the output:

```
ERRO[0000] Error: Error in function call

ERRO[0000]   on /<REDACTED>/foo/test/terragrunt.hcl line 4, in include "foo":
ERRO[0000]    4: include "foo" { path = find_in_parent_folders("foo.hcl") }
ERRO[0000]
ERRO[0000] Call to function "find_in_parent_folders" failed:
ParentFileNotFoundError: Could not find a foo.hcl in any
of the parent folders of
/<REDACTED>/bar/terragrunt.hcl.
Cause: Traversed all the way to the root..

ERRO[0000] Error: Unsuitable value type

ERRO[0000]   on /<REDACTED>/foo/test/terragrunt.hcl line 4, in include "foo":
ERRO[0000]    4: include "foo" { path = find_in_parent_folders("foo.hcl") }
ERRO[0000]
ERRO[0000] Unsuitable value: value must be known

WARN[0000] Error reading partial config  for dependency foo: /<REDACTED>/foo/test/terragrunt.hcl:4,24-47: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFoundError: Could not find a foo.hcl in any of the parent folders of /<REDACTED>/foo/test/terragrunt.hcl. Cause: Traversed all the way to the root.., and 1 other diagnostic(s)
```

**To Reproduce**
You need the following tree:
* `foo/`
  * `test/`
    * `terragrunt.hcl`
  * `foo.hcl`
* `bar/`
  * `terragrunt.hcl`

`foo/test/terragrunt.hcl`:
```hcl
include "foo" {
  path = find_in_parent_folders("foo.hcl")
}
```

`bar/terragrunt.hcl`:
```hcl
dependency "foo" {
  config_path = find_in_parent_folders("foo/test")
}
```

**Expected behavior**
Planning the `bar/` project should work without any warnings or errors.

**Versions**
- Terragrunt version: 0.55.2
- Terraform version: 1.3.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS 14.1.1 (23B81)

**Additional context**
Works in 0.55.1

**Comment by perplexa** [comment]
I am having a similar problem with `get_original_terragrunt_dir` now, which always returns the terragrunt.hcl from the calling directory, rather than from the terragrunt.hcl that includes the statement.

It breaks all sorts of dependencies that have different nesting levels than the current terragrunt.hcl.

I suspect the breaking change was introduced in https://github.com/gruntwork-io/terragrunt/commit/8af1118c2c0703f4a1e7fd81c72a8027beac307f

**Comment by denis256** [comment]
Will take a look for a fix, most probably it is caused by HCL parsing code which looks for `skip` flag in files

**Comment by denis256** [comment]
Same issue happens on 0.55.1
```
❯ terragrunt apply
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.55.1
ERRO[0000] Error: Error in function call
      
ERRO[0000]   on /projects/gruntwork/terragrunt-tests/issue-2941/foo/test/terragrunt.hcl line 2, in include "foo": 
ERRO[0000]    2:   path = find_in_parent_folders("foo.hcl") 
ERRO[0000]                                              
ERRO[0000] Call to function "find_in_parent_folders" failed: ParentFileNotFoundError: Could not find a foo.hcl in any of the parent folders of /projects/gruntwork/terragrunt-tests/issue-2941/foo/test/terragrunt.hcl. Cause: Traversed all the
way to the root..
 
ERRO[0000] Error: Unsuitable value type
       
ERRO[0000]   on /projects/gruntwork/terragrunt-tests/issue-2941/foo/test/terragrunt.hcl line 2, in include "foo": 
ERRO[0000]    2:   path = find_in_parent_folders("foo.hcl") 
ERRO[0000]                                              
ERRO[0000] Unsuitable value: value must be known
       
ERRO[0000] /projects/gruntwork/terragrunt-tests/issue-2941/foo/test/terragrunt.hcl:2,10-33: Error in function call; Call to function "find_in_parent_folders" failed: ParentFileNotFoundError: Could not find a foo.hcl in any of the parent folders of /projects/gruntwork/terragrunt-tests/issue-2941/foo/test/terragrunt.hcl. Cause: Traversed all the way to the root.., and 1 other diagnostic(s) 
ERRO[0000] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
```

**Comment by denis256** [comment]
I suspect the issue was fixed as part of https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.4  at least in my tests it does not occurring now

Please confirm from your side

**Comment by seanmacisaac** [comment]
I had this yesterday evening using 0.55.4, found this issue and downgraded to 0.55.1, and it worked.  We have dependencies that use find_in_partent_folders as described in this issue.

**Comment by denis256** [comment]
Additional fix included since: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.6

**Comment by 2xburnt** [comment]
same problem in 0.67.4 find_in_parent_folders searches the path relative to the current *.hcl file not the originating terragrunt.hcl

**Comment by ErezWeiss** [comment]
same here - did you solve it?

**Comment by masonhuemmer** [comment]
same issue
