### ISSUE TITLE
Add support for scaffolding local modules/repos

### ISSUE THREAD

**Issue by jmreicha** [gruntwork-io/terragrunt#2943]
**Describe the solution you'd like**

Add support to the `scaffold` command to create scaffolding from a local repository, without needing to specify a remote URL.

**Describe alternatives you've considered**

I have looked through issues, but haven't found this specific use case/issue described.

**Additional context**

Working through building a new module I have found myself in a situation where I'd like to scaffold out what I have built, iterate, throw it away, and start over. So far, I have only been able to make this work by pushing to a branch and referencing that way, it works but the ergonomics with that approach are a bit cumbersome.

It would be awesome if there was some way to use `--terragrunt-source` since it already exists to pass in the local module, something like `terragrunt scaffold --terragrunt-source /path/to/module`.

**Comment by denis256** [comment]
Hi,
local path is also supported, it is required to pass "//" to reference module to be used

Example with local path:
```
cd /tmp
mkdir project1
cd project1/
git clone git@github.com:denis256/terragrunt-tests.git
mkdir experiment1
cd experiment1/
terragrunt scaffold /tmp/project1/terragrunt-tests/scaffold//default-template
cat terragrunt.hcl
```

**Comment by jmreicha** [comment]
Ok, I must have missed this. I will give it a try and report back 👍

**Comment by jmreicha** [comment]
Seems to work as you mentioned, I will close this one out. Is there any interest in a pull request to the docs with an example?
