### ISSUE TITLE
get_env() doesn't interpolate paths correctly

### ISSUE THREAD

**Issue by chapati23** [gruntwork-io/terragrunt#295]
I can't seem to use `get_env` in my `terraform.tfvars` when configuring `aws_shared_credentials_file`. Always get the following error which indicates that the interpolation doesn't work:

![image](https://user-images.githubusercontent.com/117495/30541757-aae135e6-9c4a-11e7-8368-e04c47597113.png)

### Works
```tf
# terraform.tfvars
aws_shared_credentials_file = "/Users/my-name/.aws/credentials"
```

### Doesn't work
```tf
# terraform.tfvars
aws_shared_credentials_file = "/Users/${get_env("USER", "my-name")}/.aws/credentials"
```
(`echo $USER` correctly returns "my-name" on macOS 10.12.6)

any ideas?

**Comment by brikis98** [comment]
Where are you using `get_env`? Can you post the full snippet? Also, what version of Terragrunt?

**Comment by chapati23** [comment]
sure @brikis98, version is `v0.13.2` and it's in a `terraform.tfvars`:

```
# ---------------------------------------------------------------------------------------------------------------------
# TERRAGRUNT CONFIGURATION
# This is the configuration for Terragrunt, a thin wrapper for Terraform that supports locking and enforces best
# practices: https://github.com/gruntwork-io/terragrunt
# ---------------------------------------------------------------------------------------------------------------------

terragrunt = {
  # Terragrunt will copy the Terraform configurations specified by the source parameter, along with any files in the
  # working directory, into a temporary folder, and execute your Terraform commands in that folder.
  terraform {
    source = "git::ssh://git@git.example.io/infrastructure/infrastructure-modules.git//route53/cluster-subdomains?ref=v0.0.8"
  }

  dependencies {
    paths = ["../cluster-hosted-zone"]
  }

  # Include all settings from the root terraform.tfvars file
  include = {
    path = "${find_in_parent_folders()}"
  }
}

# ---------------------------------------------------------------------------------------------------------------------
# MODULE PARAMETERS
# These are the variables we have to pass in to use the module specified in the terragrunt configuration above
# ---------------------------------------------------------------------------------------------------------------------

aws_region = "eu-west-1"
aws_shared_credentials_file = "/Users/${get_env("USER", "my-name")}/.aws/credentials"
subdomain = "styleguide.my-domain.io"
```

**Comment by brikis98** [comment]
Ah, yea, that's a common mistake: Terragrunt's interpolation helpers *only* work within the `terragrunt = { ... }` block.

**Comment by chapati23** [comment]
ah, shoot. must have overread that.
so there's no way for dynamic values outside the `terragrunt` block?

**Comment by brikis98** [comment]
Currently, no. Supporting this would require rewriting your `terraform.tfvars` file and other non-trivial considerations. I'm not against it, but it's a pretty large change.

**Comment by chapati23** [comment]
gotcha. not directly on-topic, but related question: how do you handle aws credentials then? if i check this in as is then it won't work for any other dev because of my hardcoded username.

**Comment by brikis98** [comment]
Use env vars: `AWS_ACCESS_KEY_ID`, `AWS_PROFILE`, etc.

**Comment by chapati23** [comment]
👍 thanks
