### ISSUE TITLE
EKS cluster deployment : Connection timed out error

### ISSUE THREAD

**Issue by RagunathAnbarasu** [gruntwork-io/terragrunt#2953]
**Describe the bug**
I have http_proxy, https_proxy, no_proxy, HTTP_PROXY, HTTPS_PROXY, NO_PROXY environment variables set in my ubuntu machine to access internet (corporate proxy)
I am using terraform-aws-eks **v0.35.2** to deploy my eks cluster(1.27).

The deployment is stuck after couple minutes and errors out with **connection timed out** error.

**To Reproduce**
Set the following proxy variables in your environment
1. http_proxy
2. https_proxy
3. no_proxy
4. HTTP_PROXY
5. HTTPS_PROXY
6. NO_PROXY

Use  terraform-aws-eks **v0.35.2** to deploy an eks cluster 

**Expected behavior**
Terragrunt should deploy eks cluster without connection timeout error even with the proxy setup.

**Nice to have**
- [x] Screenshots
![image](https://github.com/gruntwork-io/terraform-aws-eks/assets/44649428/444a173b-1913-47ea-a177-819c3f6e833d)

**Additional context**

It works in a no proxy environment. But most of our machines need the proxy.

**Comment by denis256** [comment]
Looks like env variables aren't passed to subsequent terraform call, or unset during execution

**Comment by RagunathAnbarasu** [comment]
> Looks like env variables aren't passed to subsequent terraform call, or unset during execution

I have set it to ~/.bashrc . I believe they are being called in every shell invocation. Its also visible only for eks cluster deployment where kubergrunt is also being used within the module.

Is there any way to make sure both terragrunt and kubergrunt uses the proxy environment variables that are set?
