### ISSUE TITLE
Question - run-all apply and optional module

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [gruntwork-io/terragrunt#2954]
I think it's not possible now but correct me if I'm wrong.

I'm using now terragrunt in following way:
```
terragrunt run-all --terragrunt-strict-include ... --terragrunt-include-dir=some_dir/*
```

Would it be possible in such usage to make some of the modules inside `some_dir` optional or deployment dependant on some local. Currently I have configuration of my modules inside tfvar file which is changed for different deployments. 
I know that I could add --terragrunt-exclude-dir... but I don't want to add logic of parsing the same tfvar that is used to configure modules file to just extract if I want or not to deploy optional module.

**Comment by denis256** [comment]
Hi,
I think can be used `skip` property in dependencies HCL

Example: https://github.com/denis256/terragrunt-tests/tree/master/issue-2954

https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#skip
