### ISSUE TITLE
separate repos and module-module data sharing

### ISSUE THREAD

**Issue by mbolek** [gruntwork-io/terragrunt#297]
Hi, I've got a following scenario (which I think is sort of a 'typical' scenario) and can't get it to work:
2 repos - terraform-live and terraform-modules (as suggested), they look like this:
terraform-modules:
.
├── app
│   ├── main.tf
│   ├── outputs.tf
│   └── vars.tf
├── db
│   ├── main.tf
│   ├── outputs.tf
│   └── vars.tf
├── ecr
│   ├── main.tf
│   ├── outputs.tf
│   └── vars.tf
├── jenkins
│   ├── main.tf
│   ├── outputs.tf
│   └── vars.tf
└── vpc
    ├── main.tf
    ├── outputs.tf
    └── vars.tf
and terraform-live:
.
├── demo
│   ├── app
│   │   └── terraform.tfvars
│   ├── db
│   │   └── terraform.tfvars
│   └── vpc
│       └── terraform.tfvars
├── dev
│   ├── app
│   │   └── terraform.tfvars
│   ├── db
│   │   └── terraform.tfvars
│   └── vpc
│       └── terraform.tfvars
├── global
│   ├── ecr
│   │   └── terraform.tfvars
│   ├── jenkins
│   │   └── terraform.tfvars
│   └── vpc
│       └── terraform.tfvars
├── terraform.tfvars
└── test
    ├── app
    │   └── terraform.tfvars
    ├── db
    │   └── terraform.tfvars
    └── vpc
        └── terraform.tfvars

So this far everything looks fine and if I simply run in any single terrragrunt plan it works. 
The issue is when I try to get some data from another module - jenkins should create an EC2 Instance but it needs some data from the vpc module, and it bails out on. The error is: is no such a module 'vpc'. So the question is, how should one connect all of the suggestions with separate live/modules repos with some inter-module variable/data usage? I haven't found an issue like this. Most of examples that use data from other modules aren't split like this and have all the modules invocations in one file. Could you shed some more light on this kind of scenario?

**Comment by brikis98** [comment]
Use a [terraform_remote_state data source](https://www.terraform.io/docs/providers/terraform/d/remote_state.html).

**Comment by mbolek** [comment]
Thanks, will have a look at it

**Comment by AdamHansrod** [comment]
I'm having I believe similar issue, with terragrunt managing the remote state backend config (in my case an s3 bucket) in a terraform.tfvars file, and the module being sourced from another folder/project.

@brikis98  Could you provide an example of what that ec2 instance module data source would look like when you said to use data source ? 
Or can you help answer how to ensure that the remote state data source backend config is 'dependency injected' into the EC2 instance module to avoid the module knowing directly about the backend config?

**Comment by brikis98** [comment]
Here's an example of a "web service" module that depends on a DB deployed by another module and using `terraform_remote_state` to share data between them: https://github.com/brikis98/terraform-up-and-running-code/blob/master/code/terraform/06-terraform-team/modules/services/webserver-cluster/main.tf#L145-L153

The backend config params are all variables, so you can "inject" them to some extent to keep things DRY.

**Comment by dscowan** [comment]
This seems like a pretty common use case that should be more easily solved by terragrunt.  The most common use case I see is a module that creates a vpc and then another module that deploys ec2 instances and needs the vpc.  It would be nice to have a best practice example of this.

**Comment by dscowan** [comment]
Another issue with the terraform_remote_state approach is that a terragrunt plan-all fails due to the data not yet existing.

**Comment by mbolek** [comment]
> This seems like a pretty common use case that should be more easily solved by terragrunt. The most common use case I see is a module that creates a vpc and then another module that deploys ec2 instances and needs the vpc. It would be nice to have a best practice example of this.

Well, generally this is exactly my case. I was really impressed with terragrunt's idea of having a separate tfstate file per module but it proved problematic when data sharing is needed. Of course there is a possibility to use remote_state but it means a lot of outputs to be exported and then maintained.
I have done a mix - I have a tfstate file per environment and use only a fraction of remote_state. There is terraform-modules repo that wraps modules from terraform registry, and then there is terraform-live with branch per environment that uses my modules with variables from terraform.tfvars. It is quite ok and fun.
Definitely not the best solution but it works :)

**Comment by brikis98** [comment]
> This seems like a pretty common use case that should be more easily solved by terragrunt. The most common use case I see is a module that creates a vpc and then another module that deploys ec2 instances and needs the vpc. It would be nice to have a best practice example of this.

What sort of solution do you envision?

**Comment by dscowan** [comment]
The solution I envision would be some mechanism that links outputs between modules.  That is instrumented by terragrunt and works like terraform variable input output works.  The big problem I see is with terraform_remote_state it makes it hard to compose modules into terraform units outside of terragrunt.  Also the issue with terraform_remote_state not working in the plan state is a pretty big problem in my opinion.

**Comment by brikis98** [comment]
> The solution I envision would be some mechanism that links outputs between modules. That is instrumented by terragrunt and works like terraform variable input output works.

Try to spell out in concrete detail how that would work. 

For example, one idea is if module A depends on module B, then Terragrunt applies module B, reads in all of its output variables, and sets them using `-var` flags on module A. This is probably doable, but it has quite a few potential gotchas. First, module A has to expose input variables for everything it needs from module B. Second, if you're *already* setting some of those input variables for module A (e.g., via `default` or a `terraform.tfvars` file), then we have to somehow avoid overriding those. 

> Also the issue with terraform_remote_state not working in the plan state is a pretty big problem in my opinion.

Again, try to spell out concretely how you would solve this. 

For example, if module A depends on a public IP address output from module B, there is no way to provide a value that IP until module B is actually applied. So what value could you provide so that `plan` works for module A? An empty string? A random string? Obviously, any value of this sort is potentially going to lead to errors in the `plan` command anyway.

**Comment by dscowan** [comment]
I am fairly new to terraform and terragrunt.  I quickly ran into wanting to DRY my env modules and so then started trying to use existing modules I had that passed variables via a top level main.tf with everything sharing the same state.  I then had to grok to find out how to do the module level variable sharing using terragrunt.  I really only found bits and pieces in issues logged here.  Maybe a better example or documentation is whats needed.  The best concrete example I can give is this

modules
    vpc
        vpc.tf - output vpc_id for use in other modules, 
                    also would like to use aws_region var from root.vars below
    web
        web.tf - requires vpc_id 

live
    root.vars - defines aws_region and env name
    terraform.tfvars - would like to reference aws_region and env_name in s3 key
    vpc
        terraform.tfvars 
    web
        terraform.tfvars  - this has a dependency on vpc

I do like your suggestion of variable passing based on dependency.  My web module already had input variables defined for vpc_id so I think that is a fair requirement to require dependent modules to define input variables.  As far as what to provide for the dependent module this already works as you describe in terraform alone.  In my pre terragrunt module/web.tf I have

variable "vpc_id" {}

In main.tf  I have

module "web" {
  source           = "./modules/web"
  vpc_id           = "${module.vpc.vpc_id}"
}

so I think what you describe with using dependencies and defining input variables as blank in the modules would work well.  Then the modules could be used either from within terragrunt or terraform with little to no changes.

**Comment by andrewCluey** [comment]
Hi, I also have a query regarding remote_state, specifically the reuse of outputs across modules. As suggested I'm using an S3 backend for my state files, all works fine.

I have been able to get data from the VPC module remote_state using the "terraform_remote_state" data block in other (dependent) modules. All works fine when I need to grab attributes direct from the state file. 

The problem occurs when I try to grab any custom outputs that I defined in the VPC module. As an example, I have outputs specified in the VPC module to list the IDs of the public and private subnets that have been created. These display fine when I run my VPC module, and also when I run terragrunt output (or terragrunt show for that matter).

However, when I run the plan form my ec2 module I get the following error:
"
aws_instance.app_server: 1 error(s) occurred:

* aws_instance.app_server: Resource 'data.terraform_remote_state.vpc' does not have attribute 'private_subnet_id' for variable 'data.terraform_remote_state.vpc.private_subnet_id'

"
It's not the end if the world, I could work around this if it comes to that but using the state file and outputs seemed like a neater solution than applying multiple tags that I can filter on.

Thanks in advance for any help,
Andy

**Comment by brikis98** [comment]
> I have been able to get data from the VPC module remote_state using the "terraform_remote_state" data block in other (dependent) modules. All works fine when I need to grab attributes direct from the state file.

> The problem occurs when I try to grab any custom outputs that I defined in the VPC module. 

The state file stores your outputs, so I'm not clear on the distinction here. What attributes are you getting from the state file if not outputs?

**Comment by andrewCluey** [comment]
Sorry, this is my cock-up. I looked into it again (properly this time, like I should have done originally) and the variable I was using, to specify the bucket name, was passing through the wrong value and so was digging in the wrong place!

Looks a lot happier now. What threw me was that some attributes were coming back (which seemed valid) but this was obviously just some random data that had been buried in this old bucket.

Thanks for the speedy response too.

**Comment by brikis98** [comment]
Closing in favor of #418.
