### ISSUE TITLE
`mock_outputs` always used w/ `terragrunt destroy`

### ISSUE THREAD

**Issue by mhulscher** [gruntwork-io/terragrunt#2971]
**Describe the bug**
Since the new releases of last week, instead of using actual dependency outputs, `mock_outputs` is always being used in `terragrunt destroy`.

`mock_outputs` is set, but `skip_outputs` is not.

```
Error: expected "url" to have a host, got https://

  with provider["registry.terraform.io/grafana/grafana"],
  on grafana.tf line 2, in provider "grafana":
   2:   url = "https://${var.grafana_admin_fqdn}"
```

```
dependency "grafana" {
  config_path = "../grafana"

  mock_outputs = {
    grafana_admin_fqdn = ""
  }

  mock_outputs_merge_strategy_with_state  = "shallow"
  mock_outputs_allowed_terraform_commands = ["init", "plan", "validate", "destroy"]
}

inputs = {
  grafana_admin_fqdn = dependency.grafana.outputs.grafana_admin_fqdn
}
```

**Expected behavior**
When running `terragrunt destroy`, actual dependency outputs should be used instead of mock values.

**Versions**
- Terragrunt version: 0.55.9
- Terraform version: 1.5.7

**Additional context**
This used to work correctly until [v0.55.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.4)

**Comment by denis256** [comment]
Hi,
noticed that `destroy` is listed in `mock_outputs_allowed_terraform_commands = ["init", "plan", "validate", "destroy"]` , it still happens if `destroy` is removed from `mock_outputs_allowed_terraform_commands`?

**Comment by mhulscher** [comment]
@denis256 unfortunately it does not. Then I am given the following error:

```
ERRO[0000] /foo/grafana/terragrunt.hcl is a dependency of /foo/fixtures/terragrunt.hcl but detected no outputs. Either the target module has not been applied yet, or the module has no outputs. If this is expected, set the skip_outputs flag to true on the dependency block.
```

However, the dependecy *is* in fact already applied.

**Comment by denis256** [comment]
Hi,
I tried a similar setup, mocks aren't used, is used real value:
```
❯ terragrunt destroy
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.55.10

Changes to Outputs:
  - output_url = "https://real-url-here.com" -> null

```

End to end example:
https://github.com/denis256/terragrunt-tests/tree/master/issue-2971

Will be helpful to have repo/code sample where the issue happens.

**Comment by mhulscher** [comment]
@denis256 I apologize, I should have included the fact that this goes wrong with plans that have a dependency on a plan, which has a dependency on another plan. So if the dependency tree looks like `plan1 => plan2 => plan3` , it goes wrong w/ `plan3` . If you can't reproduce it, I can perhaps create some code to reproduce.

In the mean time we have reverted to terragrunt-version 0.55.3 and this fixes the issue.

**Comment by AlexShku** [comment]
I've spent half a day with plan-all destroy not working! 
thank you @mcalhoun!

**Comment by denis256** [comment]
@mhulscher will be helpful to share an example repo/code where the issue happens, so far my tests in https://github.com/denis256/terragrunt-tests/tree/master/issue-2971 with 3 level dependencies didn't highlighted the issue

**Comment by mhulscher** [comment]
Closing as this has been fixed by https://github.com/gruntwork-io/terragrunt/pull/3071
