### ISSUE TITLE
TG hook not working w/ terragrunt v0.46.0+

### ISSUE THREAD

**Issue by TJTEJASMALADHKAR** [gruntwork-io/terragrunt#2973]
TG Hooks are causing this error which was working fine till the terragrunt v0.45.0
Causing 
![Capture](https://github.com/gruntwork-io/terragrunt/assets/94542623/9d939211-9df1-4fec-b870-fdf715c8f9de)

**Expected behavior**
TG hooks runs properly using terragrunt v0.46.0+.

**Versions**
- Terragrunt version: v0.46.0+
- Environment details (Ubuntu 20.04, Windows 10, etc.):

**Comment by denis256** [comment]
Hi,
can be shared example repo/source code where this issue happens

**Comment by TJTEJASMALADHKAR** [comment]
Hi @denis256, 
I didn't get you
