### ISSUE TITLE
[BUG] Call to function `read_terragrunt_config` failed. Attempt to get attribute from null value

### ISSUE THREAD

**Issue by kinseii** [gruntwork-io/terragrunt#2974]
**Describe the bug**
I have multiple terragrunt modules, one references the local variables of another module via the `read_terragrunt_config` function. When I try to execute `terragrunt plan` on the module, the dependent module gives an error: `Attempt to get attribute from null value`.

More logs here:
```
ERRO[0011] Error: Attempt to get attribute from null value

ERRO[0011]   on /home/kinsei/********/***************/*******-prod/aks-us-1/logging-tf-module-k8s-manifests-os-k8s-secret-azure-storage-account-credentials-os-snapshots/terragrunt.hcl line 32:
ERRO[0011]   32:       NAMESPACE                  = include.deps.inputs.NAMESPACE
ERRO[0011]
ERRO[0011] This value is null, so it does not have any attributes.

ERRO[0011] Error: Attempt to get attribute from null value

ERRO[0011]   on /home/kinsei/********/***************/*******-prod/aks-us-1/logging-tf-module-k8s-manifests-os-k8s-secret-azure-storage-account-credentials-os-snapshots/terragrunt.hcl line 34:
ERRO[0011]   34:       AZURE_STORAGE_ACCOUNT_KEY  = include.deps.inputs.AZURE_STORAGE_ACCOUNT_KEY
ERRO[0011]
ERRO[0011] This value is null, so it does not have any attributes.

ERRO[0011] Error: Error in function call

ERRO[0011]   on /home/kinsei/********/***************/*******-prod/aks-us-1/logging-tf-module-k8s-manifests-os-cluster/terragrunt.hcl line 32, in locals:
ERRO[0011]   32:   k8s_secret_name_az_sa_os_snapsht = read_terragrunt_config("../logging-tf-module-k8s-manifests-os-k8s-secret-azure-storage-account-credentials-os-snapshots")
ERRO[0011]
ERRO[0011] Call to function "read_terragrunt_config" failed: /home/kinsei/********/***************/*******-prod/aks-us-1/logging-tf-module-k8s-manifests-os-k8s-secret-azure-storage-account-credentials-os-snapshots/terragrunt.hcl:32,55-65: Attempt to get attribute from null value; This value is null, so it does not have any attributes., and 1 other diagnostic(s).

ERRO[0011] Could not convert include to the execution ctx to evaluate additional locals in file /home/kinsei/********/***************/*******-dev/aks-us-1/logging-tf-module-k8s-manifests-ot-k8s-secret-jaeger-credentials/terragrunt.hcl
ERRO[0011] /home/kinsei/********/***************/*******-prod/aks-us-1/logging-tf-module-k8s-manifests-os-cluster/terragrunt.hcl:32,38-61: Error in function call; Call to function "read_terragrunt_config" failed: /home/kinsei/********/***************/*******-prod/aks-us-1/logging-tf-module-k8s-manifests-os-k8s-secret-azure-storage-account-credentials-os-snapshots/terragrunt.hcl:32,55-65: Attempt to get attribute from null value; This value is null, so it does not have any attributes., and 1 other diagnostic(s).
ERRO[0011] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**To Reproduce**
1. A module has a reference to a value in another module:
```
locals {
  k8s_secret_name_az_sa_os_snapsht = read_terragrunt_config("../logging-tf-module-k8s-manifests-os-k8s-secret-azure-storage-account-credentials-os-snapshots")
}
```

2.  In the same module, I refer to a local variable as follows:
```
inputs = merge(yamldecode(file(find_in_parent_folders("cluster.yaml"))), {
...
      K8S_SECRET_NAME_AZ_SA_OS_SNAPSHT = local.k8s_secret_name_az_sa_os_snapsht.locals.name
...
    })
  }
})
```

**Expected behavior**
When running terragrunt plan in a dependent module, the `read_terragrunt_config` function should return a value.

**Versions**
- Terragrunt version: 0.55.10
- Terraform version: 1.5.3
- Environment details: Windows 11 + WSL 2

**Additional context**
By selection method I determined that the maximum working version of terragrunt: 0.52.7.
With the terragrunt 0.52.7 version, the `terragrunt plan` command is proceeding as it should, without any errors.

[upd. 28 Feb 2024]:
- 0.54.15 version still works as it should.
- 0.54.16 version gives the error described in Issue.

**Comment by kinseii** [comment]
> Hi, I was wondering if this can be an issue with a relative path, can be attempted to use `${get_repo_root()}` to reference path to file? or use absolute path?
> 
> https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_repo_root

Yes, that's right, we use the `get_repo_root` function. What could be the problem?

**Comment by kinseii** [comment]
I realized I didn't run enough tests with terragrunt versions, today I made the tests more in-depth and this is what I got:
- 0.54.15 version still works as it should.
- 0.54.16 version gives the error described in Issue.

**Comment by jtackaberry** [comment]
I opened #3036 but as I continue to explore that one I feel like these two issues have the same root cause.

In any case, over in #3036 I provide an example repository with the smallest/simplest test case I could muster to reproduce this (and another) error message.
