### ISSUE TITLE
Terragrunt is caching module only instead of whole repository

### ISSUE THREAD

**Issue by arazdolski** [gruntwork-io/terragrunt#2977]
**Describe the bug**
After upgrading from v0.50.17 to v0.55.10 we faced issues with nested modules in terragrunt. During `terragrunt init` run terragrunt returns two Unreadable module directory errors: `Unable to evaluate directory symlink: lstat ../../../_modules: no such file or directory` and `The directory  could not be read for module "module_a" at main.tf:10`. It turned out that terragrunt is caching module defined in .hcl only and this module has a nested module (module_a) located in _modules which is present in cache (.terragrunt-cache)

```
time=2024-02-29T16:24:42+02:00 level=info msg=Downloading Terraform configurations from file:///Users/user1/terraform/_modules/_envcommon/module_b into /Users/user1/terraform/s3/.terragrunt-cache/-RJtNjJ1wSFdhjkhfast3/yW1uDTCDCPufLB42oVwgPJJNAOE
```

**To Reproduce**

1. Create a module in _modules directory (module_a)
2. Create another module (module_b) in `_modules/_envcommon/module_b` and define module_a in it
```hcl
module "cluster" {
  source = "../../../_modules/module_a"
}
```
3. Create module_b.hcl in `_modules/_envcommon` with a source to module_b
```hcl
terraform {
  source = "${get_path_to_repo_root()}/_modules/_envcommon/module_b"
}
```
4. Create terragrunt.hcl in the s3 directory and include module
 ```hcl
include "module_b" {
  path = "${get_path_to_repo_root()}/_modules/_envcommon/module_b.hcl"
}
```

module_b has module_a inside (nested module). 

As a result, terragrunt will create a `.terragrunt-cache/smth` directory with only module_b content, and ../../../_modules/module_a won't be found since it doesn't exist in the cache. 

Also, I couldn’t find in releases in what terragrunt version this caching change was made

**Expected behavior**
Terragrunt will cache the whole repository and module 

**Versions**
- Terragrunt version: 0.55.10
- Terraform version: 1.6.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS 14.2.1

**Comment by arazdolski** [comment]
I'm not sure if it's a bug or a feature. If it's a feature, then please guide me on how to force terragrunt to cache the whole repository

**Comment by denis256** [comment]
Hi,
from description aren't clear a couple of steps:
* where should be created `module_b.hcl` file? 
* `4. Define module in .hcl` where should be this file created? another separated module

**Comment by arazdolski** [comment]
Hi,
I have updated the description. I hope it's clear now

**Comment by arazdolski** [comment]
Found a problem, I needed to add `/` in module_b.hcl due to the change in [v0.51.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.51.1)
