### ISSUE TITLE
scaffold not working

### ISSUE THREAD

**Issue by jamesboydell** [gruntwork-io/terragrunt#2979]
**Describe the bug**
Can't seem to get the scaffolding feature to work. I'm trying the examples and they always error. The last example, with the external template, will "complete" if I drop the "git@" from the beginning of the module URL, however it looks like it's copying the external-template.txt and terragrunt.hcl files. My impression is that the scaffolding feature will build a terragrunt.hcl file with a block terraform and input blocks pre-filled (default boilderplate template). 

When the error happens part of the console if cleared and you can't read all the error outputs. 

**To Reproduce**
In an empty directory, run `terragrunt scaffold github.com/gruntwork-io/terragrunt-infrastructure-modules-example//mysql`

**Expected behavior**
Expect terragrunt.hcl file with the rough contents as shown in the example. 

**Nice to have**
![image](https://github.com/gruntwork-io/terragrunt/assets/11381640/11470680-0b3e-4536-becf-323aeb6317c8)

**Versions**
- Terragrunt version: v0.55.9
- Terraform version: v1.5.7 on windows_amd64
- Environment details (Ubuntu 20.04, Windows 10, etc.): Windows 11 Enterprise 22H2

**Additional context**

**Comment by denis256** [comment]
Taking a look

**Comment by denis256** [comment]
Happens on my Windows environment too in Cygwin shell, looking why

**Comment by jamesboydell** [comment]
This also happens in Powershell and Command Prompt.

**Comment by denis256** [comment]
Yes, will prepare a fix soon

**Comment by denis256** [comment]
Included fix in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.55.12
