### ISSUE TITLE
creating multiple instances of modules in a single environment?

### ISSUE THREAD

**Issue by iaingray** [gruntwork-io/terragrunt#298]
How do I instantiate multiple instances of a resource with the recommended setup of having a live repo and a modules repo?

For example, if I wanted to set up multiple Amazon SNS topics in my prod environment.  Would I need a create a module which took the topic names as an array in the .tfvars folder, so that each module gets created once and only once for each environment?

**Comment by brikis98** [comment]
> For example, if I wanted to set up multiple Amazon SNS topics in my prod environment. Would I need a create a module which took the topic names as an array in the .tfvars folder, so that each module gets created once and only once for each environment?

Yup, exactly. If you didn't want to copy/paste the list of topic names, you could hard-code the names of the topics in the module, but parameterize each name with a single input variable `var.env_name`, which is the name of the environment you're deploying into.

**Comment by iaingray** [comment]
Thank you - that works!
