### ISSUE TITLE
Scaffold command doesn't handle "https" in a URL correctly, and also doesn't handle errors correctly

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#2987]
**Describe the bug**

1. The `scaffold` command can handle `github.com` URLs, but not `https://github.com` URLs. 
2. When the `scaffold` command fails to handle a URL, it logs a warning, but then proceeds with code generation anyway, so you end up with a largely empty `terragrunt.hcl`.

**To Reproduce**

```hcl
terragrunt scaffold https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example//modules/s3-bucket
```

In the logs, you'll briefly see:

```
WARN[0000] Failed to parse url https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket
WARN[0000] Failed to parse module url https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket
fatal: remote error:
 gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket is not a valid repository name
Visit https://support.github.com/ for help
WARN[0001] Failed to find last release tag for https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket
```

Then the screen is cleared and you get:

```
INFO[0001] Scaffolding a new Terragrunt module https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/tree/master/modules/s3-bucket to /tmp/test-scaffolding
INFO[0001] Running boilerplate generation to /tmp/test-scaffolding
```

And you then end up with a `terragrunt.hcl` where none of the required or optional input variables have been filled in.

**Expected behavior**

1. If `scaffold` can't process a URL, it should show an error and exit.
2. That said, since users are likely to copy/paste URLs from their browser, we should probably make URLs with the `https://` prefix work. FWIW, I believe the `catalog` command _does_ handle the "https://" prefix OK, so perhaps we can reuse the code from there?

**Versions**
- Terragrunt version: v0.55.13

**Comment by brikis98** [comment]
@levkohimins Could you take a look at this one?

**Comment by levkohimins** [comment]
Sure, I'll take a look. Thanks for the detailed description.
