### ISSUE TITLE
Destroy command should automatically warn about dependencies

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#299]
Terragrunt allows you to specify modules you depend via [`dependency`](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#dependency) or via . When a user runs `terraform destroy`, we should automatically find modules that depend on the current module, and warn the user that destroying the current one may cause issues for the others. 

I believe this would work as follows:

1. Use `git rev-parse --show-toplevel` to find the root folder in the Git repo. If it fails, either because this isn't a Git repo or `git` isn't installed, see if the current module has an `include` block, and use the path within as the root folder. If there's on `include` block, perhaps log a warning that no checks can be done.

1. Go into the root folder and find all Terragrunt modules within that folder.

1. Scan the `dependency` and `dependencies` block of each of those modules.

1. If any modules list the current module as a dependency, warn the user that deleting the current module may cause problems for those other modules and prompt for a yes/no confirmation to proceed. Skip this confirmation if the user specifies the `--terragrunt-non-interactive` flag.

**Comment by cstavro** [comment]
In non-interactive mode I'd like to see this fail with a non-zero exit code unless you provide another switch that explicitly permits the forced behaviour.

**Comment by brikis98** [comment]
Hm, that would be quite backwards incompatible with current behavior, but it's probably the correct thing to do from a technical perspective... Not sure the best way to go on that one.

**Comment by brikis98** [comment]
@denis256 could you look into this one?

**Comment by yorinasub17** [comment]
This was implemented in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.33.0
