### ISSUE TITLE
include_in_copy does not work for parent dirs of source

### ISSUE THREAD

**Issue by norman-zon** [gruntwork-io/terragrunt#2994]
**Describe the bug**
I want to copy a file from a parent directory of the `terraform.source` into the cache dir automatically.

This is my directory structure:
```bash
.
├── environments
│   └── prod
│       └── terragrunt.hcl
├── metadata.json
└── terraform
    └── main.tf
```

`metadata.json` is not strictly tied to the terraform code, as it is used for automation etc too. Therefore I would like to keep it in the projects dir, one level above the terraform code. Yet the I want to use the metadata in terraform too, using `jsondecode(file("${path.module}/metadata.json"))`, so it has to be in the terraform scratch folder.

I thought this could be achieved by using `include_in_copy` like this:

```hcl
terraform {
  source = "../../terraform//."
  include_in_copy = ["../../metadata.json"]
}
```

But this does not work, see debug output below.

Or is this just not the intended purpose of `include_in_copy` and I should use a `generate {}` block for this purpose?

**To Reproduce**

 - Setup minimal example described above
- run `terragrunt init`

**Expected behavior**

I expect the file specified in `include_in_copy = ["../../metadata.json"]` to be copied into the terraform scratch folder.

**Nice to have**

Debug output:

```bash
❯ terragrunt init --terragrunt-log-level debug
DEBU[0000] Terragrunt Version: 0.55.13
DEBU[0000] Did not find any locals block: skipping evaluation.
DEBU[0000] Running command: terraform --version          prefix=[/Users/MY-USER/work/project-metadata/environments/prod]
DEBU[0000] terraform version: 1.6.3
DEBU[0000] Reading Terragrunt config file at /Users/MY-USER/work/project-metadata/environments/prod/terragrunt.hcl
DEBU[0000] Did not find any locals block: skipping evaluation.
DEBU[0000] Did not find any locals block: skipping evaluation.
INFO[0000] Downloading Terraform configurations from file:///Users/MY-USER/work/project-metadata/terraform into /Users/MY-USER/work/project-metadata/environments/prod/.terragrunt-cache/kDwz5t3ytQahD1jxoriMt_2I2gY/Sq9iio2mDauT3gPKS7HrOFTn3L0
DEBU[0000] Copying files from /Users/MY-USER/work/project-metadata/environments/prod into /Users/MY-USER/work/project-metadata/environments/prod/.terragrunt-cache/kDwz5t3ytQahD1jxoriMt_2I2gY/Sq9iio2mDauT3gPKS7HrOFTn3L0
DEBU[0000] Setting working directory to /Users/MY-USER/work/project-metadata/environments/prod/.terragrunt-cache/kDwz5t3ytQahD1jxoriMt_2I2gY/Sq9iio2mDauT3gPKS7HrOFTn3L0
DEBU[0000] Running command: terraform init               prefix=[/Users/MY-USER/work/project-metadata/environments/prod]

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!
```

I expected to see something like `copying terraform files, applying include_in_copy....`.

**Versions**
- Terragrunt version: 0.55.13
- Terraform version: 1.6.3
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS

**Comment by denis256** [comment]
Hi,
`include_in_copy` works from "current directory" it will not include files from parent directories, you can try to use terragrunt hooks or `run_cmd` to copy files from the parent directory to current directory

https://terragrunt.gruntwork.io/docs/features/hooks/
https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd

**Comment by norman-zon** [comment]
Thanks @denis256. I just wondered if this was by design, or really a bug.

In the end I went with 

```hcl

generate "metadata" {
  path              = "_metadata.json"
  if_exists         = "overwrite_terragrunt" # same as overwrite with disable_signature
  disable_signature = true                   # not valid JSON with signature
  contents          = file("../..//metadata.json")
}
```
