### ISSUE TITLE
Handling relative paths in modules

### ISSUE THREAD

**Issue by iaingray** [gruntwork-io/terragrunt#300]
I'm trying to reference a module via relative path from another module:

```
module "test_sns" {
    source = "../../components/sns/"
    topic_name = "test_name"
    display_name = "foo"
  }

```
I'm using the recommended setup of separate live and modules repositories.

However, when I run:

`terragrunt plan --terragrunt-source ~/Development/terraform/terragrunt-infrastructure-modules/aws/shared-services/sns/`

I get an error:

```
Downloading modules...
Get: file:///var/folders/xb/h_ytxhmx7kn7qh_ytgdh73140000gn/T/terragrunt/components/sns
Error downloading modules: Error loading modules: error downloading 'file:///var/folders/xb/h_ytxhmx7kn7qh_ytgdh73140000gn/T/terragrunt/components/sns': source path error: stat /var/folders/xb/h_ytxhmx7kn7qh_ytgdh73140000gn/T/terragrunt/components/sns: no such file or directory
```
How do I get the paths to resolve?

**Comment by brikis98** [comment]
Use a double-slash (`//`): https://github.com/gruntwork-io/terragrunt#working-locally

**Comment by iaingray** [comment]
Thank you!  I didn't spot that in the docs. That works perfectly.
