### ISSUE TITLE
Wrong order of stack execution when running apply with `-destroy`

### ISSUE THREAD

**Issue by dunefro** [gruntwork-io/terragrunt#3007]
**Describe the bug**
- I have three modules, namely `A`, `B` and `C`. 
- Order of execution is `A` -> `B` -> `C` when running `terragrunt run-all apply`
- Order of destroy is `C` -> `B` -> `A` when running `terragrunt run-all destroy`
- Order of `terragrunt run-all apply -destroy` is coming as `A` -> `B` -> `C` which is incorrect.

**To Reproduce**
Create more than one dependent modules, execute them  and then try to destroy using `terragrunt run-all apply -destroy` command.

**Expected behavior**
`terragrunt apply -destroy` should take the behaviour of `destroy` sub command and not the `apply`

**Versions**
- Terragrunt version: 0.53.0
- Terraform version: 1.6.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): darwin_arm64

**Comment by levkohimins** [comment]
Resolved in [v0.56.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.56.5) release.
