### ISSUE TITLE
`skip` not respected if `dependency` block is included

### ISSUE THREAD

**Issue by marsskop** [gruntwork-io/terragrunt#3013]
Two modules, one depends on the other and `dependency` block is included. A minor change to setup of the [issue 2935](https://github.com/gruntwork-io/terragrunt/issues/2935).

**To Reproduce**
Setup:
```
.
├── first
│   ├── dependency.hcl
│   └── terragrunt.hcl
├── module
│   └── main.tf
└── second
    └── terragrunt.hcl
```
`module/main.tf` just to have a most basic module with input/output vars
```
terraform {
  required_providers {
    random = {}
  }
}

variable "input" {
  type = string
  default = "abc"
}

resource "random_string" "random" {
  length           = 1 
  special          = false
}

locals {
  trimmed = length(var.input) > 3 ? substr(var.input, 0, 3) : var.input
}

output "random_output" {
  value = random_string.random + local.trimmed
}
```
`first/terragrunt.hcl` that is being skipped:
```
skip = true

terraform {
  source = "../module"
}

inputs = {
  input = "first"
}
```
and `first/dependency.hcl`, configured for reusability:
```
dependency "first" {
  config_path = "../first"

  mock_outputs_allowed_terraform_commands = ["init", "destroy", "validate"]
  mock_outputs_merge_strategy_with_state  = "deep_map_only"
  mock_outputs = {
    random_output = ""
  }
}
```

`second/terragrunt.hcl` depends on first via `include` block, but is also being skipped:
```
skip = true

terraform {
  source = "../module"
}

include "first" {
  path = "../first/dependency.hcl"
}

inputs = {
  input = include.first.outputs.random_output
}
```

**Expected behavior**
Both modules are being skipped without any errors, but on `terragrunt run-all init` i see:
```
ERRO[0000] Module .../second has finished with an error: Could not parse output from terragrunt config .../first/terragrunt.hcl. Underlying error: unexpected end of JSON input  prefix=[.../second]
```
As per the fix in [MR 2938](https://github.com/gruntwork-io/terragrunt/pull/2938), I would expect that both modules are skipped. Is that one of the limitations of `include` block?

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: 0.55.16
- Terraform version: 1.4.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): macOS Sonoma 14.2.1, Linux RHEL 9.3

**Additional context**
If the dependency is declared without the`include` block, both modules are skipped.
If input in `second/terragrunt.hcl` is declared through the dependency (`input = dependency.first.outputs.random_output`), the error is the same.

**Comment by tweiss-mdm** [comment]
anyone else hitting this bug ?
