### ISSUE TITLE
 AccessDenied: Access Denied if disable_bucket_update false

### ISSUE THREAD

**Issue by 3-commerce** [gruntwork-io/terragrunt#3016]
**Describe the bug**
Upgrading terragrunt from 0.35.5 to 0.55.18

**To Reproduce**

1. Update terragrunt.hcl contains terraform and terragrunt version contraint. Terrafrom version from 0.13.5 to 1.7.5 and Terragrunt version from 0.35.5 to 0.55.18
2. Paste AWS access and secret key into my terminal (AWSAdministratorAccess)
3. run `terragrunt init`
4. And then i got this error
```hcl
% terragrunt init
INFO[0002] Downloading Terraform configurations from git::ssh://git@github.com/repo_name/terraform-modules-repo.git?ref=v1.0.0 into /pc/test-repo/.terragrunt-cache/EbaMibgqB-upOVLXUihR8VpIEnI/5cEf1krsalpJ-QJ0bgDAPcoioe8 
ERRO[0007] AccessDenied: Access Denied
        status code: 403, request id: X79EFQBB4QT, host id: WhW+EBavDKPn3zop7O9OknrtegO9+A00cYumw6Ymhtt1Oy1ZirO1CWhkQ665ty8Ky64= 
ERRO[0007] Unable to determine underlying exit code, so Terragrunt will exit with error code 1 
```
5. If i add `disable_bucket_update=true` on remote_state backend S3, i can terragrunt init and apply.

```hcl

remote_state {
  backend = "s3"
  config = {
    encrypt = true
    bucket = "my-terraform-states"
    key    = "account/01234567899/state.tfstate"
    region = "ap-southeast-1"
    disable_bucket_update = false
  }

  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
```

**Expected behavior**
I am able to terragrunt init and then terragrunt plan & apply

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: 0.55.18
- Terraform version: 1.7.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Mac 14.4

**Additional context**
So, i want to upgrade my my terraform and terragrunt and suddenly after doing terragrunt init, i got error 403. Event the access is binded with AWSAdministratorAccess. So, what exactly disable_bucket_update is ? Does it change the current formate terraform state ?

**Comment by denis256** [comment]
Hi,
setting `disable_bucket_update` will prevent terragrunt to set a couple of settings like versioning, encryption, block public access
Most probably AWS doesn't have some permissions, try running with `--terragrunt-log-level debug` to see at which step it is failing.

**Comment by 3-commerce** [comment]
alright, sorry for late response. I test it right now

**Comment by 3-commerce** [comment]
```
DEBU[0006] Generated file .terragrunt-cache/VUbaMibihRLX8VEgqB-upOpIEnI/5c0bgDAPcoikrsalpJ-QJoe8/backend.tf.  prefix=[/blabla/repo_name] 
DEBU[0006] Initializing remote state for the s3 backend  prefix=[/blabla/repo_name] 
DEBU[0006] Verifying AWS S3 Bucket Versioning blabla-bucket  prefix=[/blabla/repo_name] 
DEBU[0006] Checking if SSE is enabled for AWS S3 bucket blabla-bucket  prefix=[/blabla/repo_name] 
DEBU[0007] Error checking if SSE is enabled for AWS S3 bucket blabla-bucket: AccessDenied: Access Denied
        status code: 403, request id: DJZPXF1REW02AJ57, host id: 9IPiopahSSSSIa5+aDEGJlnY4u8M4XW8RQO0K0OeK4gCSrIG/pl6n3CS+WGMHS9D7q5w5z/gznk=  prefix=[/blabla/repo_name] 
ERRO[0007] AccessDenied: Access Denied
        status code: 403, request id: DJZPXF1REW02AJ57, host id: 9IPiopahSSSSIa5+aDEGJlnY4u8M4XW8RQO0K0OeK4gCSrIG/pl6n3CS+WGMHS9D7q5w5z/gznk= 
ERRO[0007] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

I think the main cause is Error checking if SSE is enabled for AWS S3 bucket blabla-bucket: AccessDenied: Access Denied
