### ISSUE TITLE
Update Compatibility Table of Terraform Versions.

### ISSUE THREAD

**Issue by nuryupin-kr** [gruntwork-io/terragrunt#3037]
Seem like [version table](https://terragrunt.gruntwork.io/docs/getting-started/supported-versions/#supported-terraform-versions) hasn't been updated for some time. I assume Terraform 1.7.x is supported by Terragrunt 0.55.xx, but would like for it to be clearer and more explicit.

**Comment by kansberry-kr** [comment]
Since .56 was just released, I would like the capability chart to be updated for this version.

**Comment by denis256** [comment]
The Terragrunt project will allow users to use any version of Terraform or OpenTofu. 
Gruntwork will sponsor contributors to support all versions of OpenTofu and ensure Terragrunt takes maximum advantage of new features in OpenTofu.

**Comment by ZachGoldberg** [comment]
Thanks for writing in about this and for the reminder that the version table is out of date, we'll make a note to get that updated shortly!
