### ISSUE TITLE
How to structure repo without repeating terragrunt code?

### ISSUE THREAD

**Issue by i2sarroyo** [gruntwork-io/terragrunt#3051]
Hi all,

First of all thank you for the awesome work. I've been struggling with my Terragrunt repo organization. All examples that I see are organized like this

```
├── production
│ ├── app
│ │ └── terragrunt.hcl
│ ├── mysql
│ │ └── terragrunt.hcl
│ └── vpc
│ └── terragrunt.hcl
├── staging
│ ├── app
│ │ └── terragrunt.hcl
│ ├── mysql
│ │ └── terragrunt.hcl
│ └── vpc
│ └── terragrunt.hcl
├── development
│ ├── app
│ │ └── terragrunt.hcl
│ ├── mysql
│ │ └── terragrunt.hcl
│ └── vpc
│ └── terragrunt.hcl
```

But I don't see it DRY as it is repeating all module declarations again and again. I manage a repository with more than 20 clients which have the same modules deployed (in most of the cases) my idea was to try to make an approach were I defined just one single structure with the module declarations, and then load the client values from variable files.

I changed the structure from above to something like the next

```
├── live
│ ├── app
│ │ └── terragrunt.hcl
│ ├── mysql
│ │ └── terragrunt.hcl
│ └── vpc
│ │ └── terragrunt.hcl
├── clients
│ ├── terragrunt.hcl
│ ├── client1
│ │ └── vars.hcl
│ │ └── terragrunt.hcl
│ ├── clientX
│ │ └── vars.hcl
│ │ └── terragrunt.hcl
```

I was not able to load live folder from client folders. I've tested with a symlink for live folder inside each client but I was not able to pass the vars.hcl to the modules as the "include" declarations in Terragrunt files are not working propertly with the find_in_parent_folders function.

Is there any way to load the live module structure from the specific client folder so I don't need to repeat the same module structure on each client folder?

Thank you again!

**Comment by denis256** [comment]
Hi,
some ideas can be collected from: 
https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example
https://github.com/gruntwork-io/terragrunt-infrastructure-live-example

**Comment by i2sarroyo** [comment]
Hi @denis256,

Thank you for the links. Most of my current terragrunt structure came up from your live example repo but I find out the same problem.

All my modules are separated in different repos. So I don't need to be worry about its Terraform content in the Terragrunt project, just applying the correct git tag for each module declaration on the clients folder. My problem remains with the live example. As you suggest, I will have something similar as the environment splitting that you have in the live-example but with different clients (we don't manage different environment per client) 

In the live-example you have declared the mysql module three times, one per environment. The three files mostly have the same content on each (except prod where you declare some inputs) As I will have more than 20 clients, I would like to avoid creating the same module declaration on each client folder as right now we declare more than 15 modules per client.

Most of the problems I have are with folder disposition as Terragrunt is looking for child folders and my module declaration structure is at the same level as the client/environment folder level, not inside the environments/clients (like the second example I put in the first comment)  As I said I tested with symlinks but I was not able to pass the vars and locals from client folder to live folder as "find_in_parent_folders" won't work as espected because they are not under client/envs folder.

I don't know if right now is possible to call to parent folders and read the vars/locals from it.

```
├── live
│ ├── app
│ │ └── terragrunt.hcl
│ ├── mysql
│ │ └── terragrunt.hcl
│ └── vpc
│ │ └── terragrunt.hcl
├── clients
│ ├── terragrunt.hcl <- provider/state config for all clients
│ ├── client1
│ │ └── vars.hcl
│ │ └── terragrunt.hcl <- live folder call and pass vars/locals to live folder
│ ├── clientX
│ │ └── vars.hcl
│ │ └── terragrunt.hcl
```

Thank you again for the time and the support.
