### ISSUE TITLE
Terragrunt Provider Cache: "host registry.terraform.io does not provide a modules service"

### ISSUE THREAD

**Issue by straub** [gruntwork-io/terragrunt#3065]
**Describe the bug**
When running with the Terragrunt Provider Cache enabled (via `TERRAGRUNT_PROVIDER_CACHE=1`), my configuration is unable to pull remote modules during `terragrunt init`, failing with the following error:

```
$ TERRAGRUNT_PROVIDER_CACHE=1 terragrunt init
INFO[0000] Terragrunt Cache server is listening on 127.0.0.1:57479
INFO[0000] Start Terragrunt Cache server
INFO[0001] Downloading Terraform configurations from file:///Users/DSTRAUB/Projects/[...] into /Users/DSTRAUB/.terragrunt-cache/[...]
- single_cluster in single
╷
│ Error: Error accessing remote module registry
│ 
│ Failed to retrieve available versions for module "ecs" (single/main.tf:7)
│ from registry.terraform.io: host registry.terraform.io does not provide a
│ modules service.
╵

ERRO[0194] terraform invocation failed in /Users/DSTRAUB/.terragrunt-cache/[...]  prefix=[/Users/DSTRAUB/Projects/[...]]
INFO[0194] Shutting down Terragrunt Cache server...
INFO[0194] Terragrunt Cache server stopped
ERRO[0194] 1 error occurred:
	* [/Users/DSTRAUB/.terragrunt-cache/[...]] exit status 1

```

<img width="591" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/2117884/85efc1b5-8c1b-4f59-906d-0e2394d42ca3">

**To Reproduce**

Run `TERRAGRUNT_PROVIDER_CACHE=1 terragrunt init` in a configuration containing a remote module, e.g.

```hcl
module "ecs" {
  source  = "terraform-aws-modules/ecs/aws//modules/cluster"
  version = "5.11.0"

  cluster_name = "test"

  fargate_capacity_providers = {
    FARGATE = {}
  }
}
```

The `.terraform` directory must also be clean. If the module was downloaded before enabling `TERRAGRUNT_PROVIDER_CACHE=1`, the issue does not occur, because Terraform doesn't attempt to download the module.

**Expected behavior**
I expect `terragrunt init` to download the remote module successfully. Perhaps the Terragrunt Provider Cache server can pass through modules from the hosts?

**Nice to have**
- [x] Terminal output
- [x] Screenshots

**Versions**
- Terragrunt version: 0.56.5
- Terraform version: 1.7.5
- Environment details: observed on MacOS 14.4 and Debian 12.5

**Additional context**

**Comment by mikesplain** [comment]
This looks like a duplicate of https://github.com/gruntwork-io/terragrunt/issues/3050? This was fixed for us via https://github.com/gruntwork-io/terragrunt/pull/3057 in 0.57.1

**Comment by straub** [comment]
I think you're right! Not sure how I missed that issue come through.

I confirmed that 0.57.1 solves this issue for me; I'll close this out. Thank you!
