### ISSUE TITLE
Reusing locals in the tree

### ISSUE THREAD

**Issue by pritho** [gruntwork-io/terragrunt#3066]
**Describe the solution you'd like**
Having a older structure like this:
```shell
├── dev
│   ├── stage.hcl
│   └── app1
│       └── bucket
│           └── terragrunt.hcl
├── qual
│   ├── stage.hcl
│   └── app1
│       └── bucket
│           └── terragrunt.hcl
├── global.hcl
└── terragrunt.hcl
```

I end up having this redundant code in every single terragrunt.hcl file:

```hcl
locals {
  stage_vars          = read_terragrunt_config(find_in_parent_folders("stage.hcl"))
  resource_group_name = local.stage_vars.locals.resource_group_name
  stage_name = local.stage_vars.locals.stage_name
}
```
I would like to define said code once in the root terragrunt.hcl file

**Describe alternatives you've considered**
[The docs regarding globally-defined-locals](https://terragrunt.gruntwork.io/docs/features/locals/#including-globally-defined-locals) also is more or less the same and doesn't help.

**Additional context**
Is there already WIP where I could maybe participate? 
Or did I miss a specific feature solving my use-case?

**Comment by denis256** [comment]
Hi,
can be used include with `merge_strategy = "deep"`

```
# dev/app1/terragrunt.hcl
include "root" {
  path = find_in_parent_folders()
  merge_strategy = "deep"
}

# parent terragrunt.hcl

locals {
  stage_vars          = read_terragrunt_config(find_in_parent_folders("stage.hcl"))
  resource_group_name = local.stage_vars.locals.resource_group_name
  stage_name = local.stage_vars.locals.stage_name
}

```

Simplified example in: https://github.com/denis256/terragrunt-tests/tree/master/reuse-locals

**Comment by pritho** [comment]
perfect, thanks so much.
I created a documentation PR for this: https://github.com/gruntwork-io/terragrunt/pull/3070
