### ISSUE TITLE
TF_PLUGIN_CACHE_DIR conflicts with terragrunt-provider-cache-dir

### ISSUE THREAD

**Issue by jgournet** [gruntwork-io/terragrunt#3068]
**Describe the bug**
The new terragrunt cache does not work if TF_PLUGIN_CACHE_DIR is set.

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
export TF_PLUGIN_CACHE_DIR=/tmp/some_dir

terragrunt run-all plan --terragrunt-provider-cache

INFO[0000] Terragrunt Cache server is listening on 127.0.0.1:41633 
INFO[0000] Start Terragrunt Cache server
[...]
time=2024-04-17T13:41:08+10:00 level=info msg=Executing hook: provider_cache prefix=[/home/user/1/terraform-infrastructure/account-123] 
mkdir: cannot create directory ‘/eu-west-2’: Permission denied
time=2024-04-17T13:41:08+10:00 level=error msg=Error running hook provider_cache with message: [/home/user/1/terraform-infrastructure/account-123/.terragrunt-cache/0fK4SCob1IAaucSrunKJyHPWS44/goKD5XcJkhR-H2Gm3a3BkAmDkQY] exit status 1 prefix=[/home/user/1/terraform-infrastructure/account-123] 
time=2024-04-17T13:41:08+10:00 level=error msg=Errors encountered running before_hooks. Not running 'terraform'. prefix=[/home/user/1/terraform-infrastructure/account-123]  
INFO[0015] Shutting down Terragrunt Cache server...     
INFO[0015] Terragrunt Cache server stopped
[...]
```

**Expected output**
The above is working fine if I do "UNSET TF_PLUGIN_CACHE_DIR"

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt version: v0.57.2
- Terraform version: v1.5.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): ubuntu 22.04

**Additional context**
We have both some old terraform code and new terragrunt architecture. Because of this, all employees have TF_PLUGIN_CACHE_DIR set as part of their terminals.
Because of this, we cannot easily use terragrunt cache.

Note: sorry if the ticket lacks code/examples - I'm hoping it's easy enough to reproduce for everybody.
If not, let me know, and I will provide more info if necessary.

**Comment by levkohimins** [comment]
Hi @jgournet, 

I couldn't repro the issue. Based on your log, the issue is in the hook.

```
time=2024-04-17T13:41:08+10:00 level=info msg=Executing hook: provider_cache prefix=[/home/user/1/terraform-infrastructure/account-123] 
mkdir: cannot create directory ‘/eu-west-2’: Permission denied
```

**Comment by jgournet** [comment]
Arg ... obviously !
sorry about that ...
Thank you
