### ISSUE TITLE
Propagate Parent Span ID in OpenTelemetry Tracing

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#3095]
**Describe the solution you'd like**
When OpenTelemetry tracing is enabled in Terragrunt, read an optional environment variable that allows for the trace to be started in the [context of a parent span ID](https://opentelemetry.io/docs/concepts/context-propagation/).

This will allow users to leverage Terragrunt tracing in a context where the process calling Terragrunt is already being traced as part of a span, and the Terragrunt execution can be interpreted as being part the parent span.

Someone using Prometheus or Grafana should be able to look at exported traces from a process that calls Terragrunt, and see the nested Terragrunt span as part of the parent span.

If there is already a standard for the naming convention of environment variables used by OpenTelemetry for this kind of thing, leverage that naming convention for this.

**Comment by denis256** [comment]
Parent span handling added in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.57.10
