### ISSUE TITLE
Broken tfplan.json if --terragrunt-include-module-prefix is used

### ISSUE THREAD

**Issue by ignatenkobrain** [gruntwork-io/terragrunt#3102]
## Describe the bug

Combination of `--terragrunt-include-module-prefix` and `--terragrunt-json-out-dir …` results in JSON file being invalid because module prefix is being included inside of JSON.

```json
[/home/brain/Projects/gooddata/iac/ns1/zones/getgooddata.info/zone] {"format_version":"1.2","terraform_version":"1.8.1",…
```

## Expected behavior

JSON file should be valid and not having any module prefix.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.57.8
- OpenTofu/Terraform version: 1.8.1
- Environment details (Ubuntu 20.04, Windows 10, etc.): Fedora 39

**Comment by denis256** [comment]
Included fix in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.58.2
