### ISSUE TITLE
Since v0.56.4, `touch terragrunt.hcl` causes `init` to run despite no other changes (possibly introduced by provider cache option)

### ISSUE THREAD

**Issue by lorengordon** [gruntwork-io/terragrunt#3121]
## Describe the bug

`init` is running every time I `touch` the terragrunt config, even though nothing has actually changed.

## Steps To Reproduce

1. Install terragrunt v0.56.3
2. Run `plan`
3. `touch terragrunt.hcl`
4. Run `plan`.
5. See `init` **does not** run on the second plan
6. Install terragrunt v0.56.4
7. `touch terragrunt.hcl`
8. Run `plan`
9. See `init` runs despite no changes needing init to run
10. Repeat with terragrunt v0.58.3 to confirm problem still on latest version

## Expected behavior

`init` should not run unless it needs to.

## Versions

- Terragrunt version: v0.56.4-v0.58.3
- OpenTofu/Terraform version: Terraform 1.5.6
- Environment details (Ubuntu 20.04, Windows 10, etc.): WSL/Ubuntu 22.04

## Additional context

v0.56.4 introduced the [Terragrunt Provider Cache](https://github.com/gruntwork-io/terragrunt/pull/3001), so that's my first suspect for this new behavior...

**Comment by levkohimins** [comment]
Hi @lorengordon, 
I tried to reproduce the issue but was unable to. I used the latest release [v0.58.10](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.58.10) on MacOS.

**Comment by lorengordon** [comment]
Actually where I first encountered this, I wasn't even using an `include` block with a parent config. It was all just baked into the one terragrunt.hcl.

**Comment by levkohimins** [comment]
Hi @lorengordon, thanks for the example, I was finally able to reproduce the issue. I will let you know once the issue is fixed.

**Comment by lorengordon** [comment]
Tested 0.58.12 and can confirm the problem is resolved! Thanks @levkohimins!
