### ISSUE TITLE
Support `--help` flag

### ISSUE THREAD

**Issue by kevinburke** [gruntwork-io/terragrunt#314]
One of `terragrunt plan -h`, `terragrunt plan --help`, `terragrunt help plan` should print help text about the command and the options it takes.

In particular I am trying to determine if I can plan the files in a directory without having it as my working directory, e.g. `terragrunt plan /path/to/directory` instead of `cd /path/to/directory && terragrunt plan`.

**Comment by brikis98** [comment]
What do you see when you run `terragrunt plan --help` now?

**Comment by kevinburke** [comment]
It just proceeds with a plan, e.g. if I run plan in a directory without terraform.tfvars it exits because it couldn't find the config file, or it proceeds trying to clone modules, etc.

**Comment by brikis98** [comment]
Hm, definitely a bug. PRs are very welcome.

**Comment by jckuester** [comment]
Here is a little fix: https://github.com/gruntwork-io/terragrunt/pull/473

**Comment by brikis98** [comment]
Fixed by #473. Thank you @jckuester!
