### ISSUE TITLE
Seeing checksum failed when installing latest terragrunt v0.58.7 release on github codespaces devcontainer

### ISSUE THREAD

**Issue by qubitron** [gruntwork-io/terragrunt#3143]
## Describe the bug

When building the github codespace for [this repo](https://github.com/azure-samples/agent-openai-python-prompty) we're seeing a checksum failure when installing terragrunt on the latest package release:
```
15.21 Downloading Terragrunt...
16.25 sha256sum: WARNING: 1 computed checksum did NOT match
16.25 sha256sum: terragrunt_SHA256SUMS: no file was verified
16.25 terragrunt_linux_amd64: FAILED
16.25 ERROR: Feature "Terraform, tflint, and TFGrunt" (ghcr.io/devcontainers/features/terraform) failed to install! Look at the documentation at ********/devcontainers/features/tree/main/src/terraform for help troubleshooting this error.
------
```

This just started happening for us a couple hours ago when the latest terragrunt package was released. We [pinned the repo](https://github.com/Azure-Samples/agent-openai-python-prompty/commit/5bf660c9f58d6d39b380ca0831d96fd7d7f17a5b) to use v0.58.6 and that worked around the issue but we'd like to unpin it.

## Steps To Reproduce

You can try creating a new codespace on [this repo](https://github.com/azure-samples/agent-openai-python-prompty) to observe the behavior.

Or, on a 64-bit debian 12 linux machine, here's a minimal repro of the issue:
```
curl -sSL -o terragrunt_SHA256SUMS https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/SHA256SUMS
curl -sSL -o terragrunt_linux_amd64 https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/terragrunt_linux_amd64
sha256sum --ignore-missing -c terragrunt_SHA256SUMS
```

Output
```
terragrunt_linux_amd64: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
sha256sum: terragrunt_SHA256SUMS: no file was verified
```

## Expected behavior

Checksum for package passes

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.58.7
- OpenTofu/Terraform version: 1.8.3
- Environment details (Ubuntu 20.04, Windows 10, etc.): Debian 12 (bookworm)

## Additional context

The definition for the devcontainer image being built is [here](https://github.com/Azure-Samples/agent-openai-python-prompty/blob/main/.devcontainer/devcontainer.json), it uses the terragrunt devcontainer feature defined [here](https://github.com/devcontainers/features/tree/main/src/terraform).

**Comment by denis256** [comment]
Hi,
checksums match, example:

```
#!/bin/bash

set -x

curl -sSL -o terragrunt_SHA256SUMS https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/SHA256SUMS
curl -sSL -o terragrunt_linux_amd64 https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/terragrunt_linux_amd64
sha256sum --ignore-missing -c terragrunt_SHA256SUMS
```


```
./script.sh 
+ curl -sSL -o terragrunt_SHA256SUMS https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/SHA256SUMS
+ curl -sSL -o terragrunt_linux_amd64 https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.7/terragrunt_linux_amd64
+ sha256sum --ignore-missing -c terragrunt_SHA256SUMS
terragrunt_linux_amd64: OK

```
