### ISSUE TITLE
TERRAGRUNT_DOWNLOAD setting is ignored for any dependent modules

### ISSUE THREAD

**Issue by levkohimins** [gruntwork-io/terragrunt#3156]
## Describe the bug

Starting with v0.57.3 the `TERRAGRUNT_DOWNLOAD` setting is ignored for any dependent modules. This causes the `.terragrunt-cache` directory to be created in the same directory as the dependent module's source rather than the location I specify in the env var `TERRAGRUNT_DOWNLOAD`.

## Versions

- Terragrunt version: 0.57.3

## Related links

- https://github.com/gruntwork-io/terragrunt/issues/3028#issuecomment-2121158017

**Comment by 1azunna** [comment]
This is now affecting the latest terragrunt version

**Comment by levkohimins** [comment]
@1azunna, please provide an example to repro the issue.

**Comment by 1azunna** [comment]
@levkohimins  I tested the `0.67.6` version and version `0.58.10` and i'm getting the same behaviour. 
Here is my root `terragrunt.hcl`

```
....
## Centralise plugin caching
terraform {
  before_hook "before_cache" {
    commands     = [get_terraform_command()]
    execute      = ["mkdir", "-p", abspath("${get_repo_root()}/.terraform/plugins")]
  }

  before_hook "workspace" {
    commands = ["plan", "state", "apply", "destroy", "refresh", "output"]
    execute  = [abspath("${get_repo_root()}/scripts/terragrunt-hook-workspace.sh"), local.workspace]
  }

  after_hook "destroy" {
    commands = ["destroy"]
    execute  = [abspath("${get_repo_root()}/scripts/terragrunt-hook-destroy.sh"), local.workspace]
  }

  extra_arguments "terragrunt_plugins" {
    commands = [get_terraform_command()]
    env_vars = {
      TF_PLUGIN_CACHE_DIR = abspath("${get_repo_root()}/.terraform/plugins")
    }
  }
}
download_dir = abspath("${get_repo_root()}/.terragrunt-cache")
```
Then i have a resource `terragrunt.hcl` with this setup

```
dependency "vpc" {
  config_path = "../network"
  mock_outputs = {
    network_self_link = "https://www.googleapis.com/compute/v1/projects/project-name/global/networks/vpc-name"
  }

  mock_outputs_allowed_terraform_commands = ["plan"]
  mock_outputs_merge_strategy_with_state = "shallow"
}
```
The folder structure is as follows

```
root
     |_ folder
        |_ subfolder
           |_ resource_1 
           |        terragrunt.hcl
           |_ resource_2
                   terragrunt.hcl
   terragrunt.hcl
```
     
I have attached both log files belo:
[v0.58.10.log](https://github.com/user-attachments/files/17020286/v0.58.10.log)
[v0.67.6.log](https://github.com/user-attachments/files/17020287/v0.67.6.log)

**Comment by 1azunna** [comment]
@levkohimins From the log we can see the output
```
18:16:38.849 DEBUG  [../network] Setting dependency working directory to ../network/.terragrunt-cache/946556418
18:16:38.850 DEBUG  [../network] Generated file ../network/.terragrunt-cache/946556418/backend.tf.
18:16:38.850 DEBUG  [../network] Generated remote state configuration in working dir ../network/.terragrunt-cache/946556418
18:16:38.850 DEBUG  [../network] Copying lock file from ../network/.terraform.lock.hcl to ../network/.terragrunt-cache/946556418
```

I believe it is meant to use the `download_dir` path but instead tries to create a `.terragrunt-cache` folder in the resource folder.
