### ISSUE TITLE
Terragrunt Provider Cache with multiple platforms

### ISSUE THREAD

**Issue by levkohimins** [gruntwork-io/terragrunt#3163]
## Describe the bug

The current implementation of Terragrunt Provider Cache creates a cache only for the platform on which it runs. We need to improve it to be able create cache with lock file for multiple platforms. Something like 
`terraform providers lock -platform=linux_amd64 -platform=darwin_arm64`

## Versions

- Terragrunt version: v0.58.10:

## Additional context

https://github.com/gruntwork-io/terragrunt/issues/2920#issuecomment-2109327569

**Comment by tomaaron** [comment]
I just wanted to add that there are a few workarounds mentioned in #1527 which are basically deleting the cache or add the multi platform lock part by part. All these workarounds are suboptimal because they further increase bandwidth usage, especially when working with multiple `terragrunt.hcl`.

**Comment by levkohimins** [comment]
Hi @tomaaron, Thanks for your involvement with this issue, I'm working on this issue and also noticed that `auto-init` shouldn't be triggered with `providers lock` command. I'll let you know once the solution is ready.

**Comment by levkohimins** [comment]
Resolved in [v0.58.14](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.58.14) release.

**Comment by levkohimins** [comment]
Hi @tomaaron, the command below now uses Terragrunt Cache Server to create the lock file.

```
terragrunt run-all providers lock -platform=linux_amd64 -platform=darwin_arm64 --terragrunt-provider-cache --terragrunt-no-auto-init
```

**Comment by tomaaron** [comment]
Thanks for the super quick implementation. Happy to test it tomorrow and let you know how it works :)

**Comment by tomaaron** [comment]
Works! Thank you.
