### ISSUE TITLE
Inadvertent switch to OpenTofu when terraform has been the default binary to look for

### ISSUE THREAD

**Issue by Shocktrooper** [gruntwork-io/terragrunt#3168]
## Describe the bug

Previously we have been running terraform instead of using OpenTofu with version constraints of >=1.8.0 .  As of our last pipeline runs on Monday it appears that the `alpine/terragrunt:latest` image is trying to use OpenTofu by default.  This is a change from the previous behavior and breaks our version constraints because as of right now OpenTofu is on 1.7.1 and Terraform is on 1.8.4.  Looking through the past weeks release notes this was not an apparent change

## Steps To Reproduce

Run a terraform plan with the latest `alpine/terragrunt:latest` image and set a version constraint of terraform being `>=1.8.0`

```hcl
terraform {
  required_version = ">= 1.8.0"
  required_providers {}
}
```

## Expected behavior

For people that are using the `alpine/terragrunt` image the default behavior should probably stay the same and use terraform unless otherwise configured.  Spinoff images should be created not utilizing the latest tag for those that need OpenTofu.  This should ensure backwards compatibility for anyone using the latest tag of the docker image.  (It appears that the dockerhub repo has spinoff images already.)

### Console output
```
$ cd terraform
$ terragrunt plan
Initializing the backend...
Successfully configured the backend "s3"! OpenTofu will automatically
use this backend unless the backend configuration changes.
Initializing modules...
- 123 in modules/123
Downloading 123/aws 1.1.0 for 123.LambdaAuthorizer...
- 123 in .terraform/modules/123.LambdaAuthorizer
╷
│ Error: Unsupported OpenTofu Core version
│ 
│   on provider.tf line 3, in terraform:
│    3:   required_version = ">= 1.8.0"
│ 
│ This configuration does not support OpenTofu version 1.7.1. To proceed,
│ either choose another supported OpenTofu version or update this version
│ constraint. Version constraints are normally set for good reason, so
│ updating the constraint may lead to other errors or unexpected behavior.
╵
╷
│ Error: Unsupported OpenTofu Core version
│ 
│   on .terraform/modules/prh-messaging.LambdaAuthorizer/provider.tf line 2, in terraform:
│    2:   required_version = ">= 1.8.0"
│ 
│ Module module.123.module.LambdaAuthorizer (from
│ 123/aws) does not support OpenTofu
│ version 1.7.1. To proceed, either choose another supported OpenTofu version
│ or update this version constraint. Version constraints are normally set for
│ good reason, so updating the constraint may lead to other errors or
│ unexpected behavior.

```

## Versions

- Terragrunt version: 0.58.10
- OpenTofu/Terraform version: terraform: 1.8.4, Tofu: N/A
- Environment details: directly in the alpine/terragrunt image on a GitLab runner

**Comment by denis256** [comment]
Hello,
I think the issue can be fixed by defining `TERRAGRUNT_TFPATH`, however, mentioned docker image is not maintained in this repository.

References:
https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_binary
https://github.com/alpine-docker/terragrunt

**Comment by ozbillwang** [comment]
> Hello,
> 
> I think the issue can be fixed by defining `TERRAGRUNT_TFPATH`, however, mentioned docker image is not maintained in this repository.
> 
> 
> 
> References:
> 
> https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform_binary
> 
> https://github.com/alpine-docker/terragrunt

TERRAFORM_TFPATH is misleading.

could we have a new as "TERRAGRUNT_OTFPATH" as well?

could we have a switch/argument  directly on terragrunt command? 

such as "terragrunt --otf", or "terragrunt --tf"

**Comment by ozbillwang** [comment]
another question, 

I have installed both `terraform` and `tofu` command lines in my enviroment, 

why it always goes with OpenTofu , not Terraform cli? I don't set `TERRAGRUNT_TFPATH` in my environment at all. 

What's the logic at backend?

**Comment by KurtLehnardt** [comment]
I've been getting this error lately too, I run `terragrunt plan` and it says my opentofu provider is incompatible with my platform. 
I checked my installed packages with `brew list` and saw I still had opentofu installed even though I don't use it. 
uninstalling opentofu with `brew uninstall opentofu` and then running `brew update && brew upgrade`, deleting my terraform caches and re-running a plan worked.
