### ISSUE TITLE
Add Extra Debug Logging to Help When Users Use `sops_decrypt_file` 

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#3171]
## Describe the bug

When the `sops_decrypt_file` function fails due to a lack of permissions in KMS, Terragrunt returns an error like the following:

```
Call to function "sops_decrypt_file" failed: Error getting data key: 0
successful groups required, got 0.
```

Forwarding this error message directly from sops doesn't help users troubleshoot the root cause of the issue.

## Steps To Reproduce

Encrypt a file with sops and KMS, then attempt to decrypt it using `sops_decrypt_file` in a local.

## Expected behavior

When `sops_decrypt_file` returns a status code of 1, output some helpful debug logging for users that gives them hints they should investigate their usage of `sops`.

Indicating that `sops` might have failed due to a failure to access a key, and a recommendation that they try to run `sops` directly might help.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version:
- OpenTofu/Terraform version:
- Environment details (Ubuntu 20.04, Windows 10, etc.):

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.58.13

**Comment by JeanFred** [comment]
That was basically what I had in mind with #3064
