### ISSUE TITLE
goroutine fatal error: concurrent map writes

### ISSUE THREAD

**Issue by putarpuar** [gruntwork-io/terragrunt#3177]
## Describe the bug

I have added TERRAGRUNT_PROVIDER_CACHE=1 infront of the terragrunt run-all plan command. But sometimes I get "fatal error: concurrent map writes". I attached the complete log to this report. 
I configured this in my .terraformrc file, not sure if this is relevant: 
```
plugin_cache_dir = "/home/vscode/.terraform.d/plugin-cache"
plugin_cache_may_break_dependency_lock_file = true
```
And some envs.
```
TERRAGRUNT_DOWNLOAD=/tmp/terragrunt-cache
TERRAGRUNT_PARALLELISM=20
TERRAGRUNT_USE_PARTIAL_PARSE_CONFIG_CACHE=true
TF_INPUT=false
TF_PLUGIN_CACHE_PATH=~/.terraform.d/plugin-cache
```

## Steps To Reproduce

I can't reproduce it. I happens around every second time I  run the plan over around 30 modules. 

## Expected behavior

A understandable error, if I did something wrong :) 

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.58.12
- OpenTofu/Terraform version: 1.4.7
- Environment details (Ubuntu 20.04, Windows 10, etc.): linux amd64 in a linux devcontainer

## Additional context

I hope here is the log file :-) 
[terragrunt.txt](https://github.com/user-attachments/files/15534339/terragrunt.txt)

**Comment by putarpuar** [comment]
Thank you so much for the fix :-*

**Comment by denis256** [comment]
Included in: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.60.1

**Comment by Tomasz-Kluczkowski** [comment]
I am still getting it in `0.69.1` when running in gitlab pipelines (linux, base image is debian 12.8)

```
fatal error: concurrent map writes
goroutine 81 [running]:
github.com/gruntwork-io/terragrunt/options.(*TerragruntOptions).AppendReadFile(0xc000bf3c08, {0xc000168fa0, 0x4a}, {0xc00171e0c0, 0x50})
	/home/circleci/project/options/options.go:751 +0x1ec
github.com/gruntwork-io/terragrunt/config.ParseTerragruntConfig(0xc0005a3780, {0xc000168fa0?, 0xc00013b071?}, 0x0)
	/home/circleci/project/config/config_helpers.go:646 +0x199
github.com/gruntwork-io/terragrunt/config.createTerragruntEvalContext.readTerragruntConfigAsFuncImpl.func6({0xc0003c51a0, 0x1, 0x21dc0e0?}, {{0xc0012ed360?, 0xc001647b70?}})
```
