### ISSUE TITLE
Using `--terragrunt-working-dir` makes `--terragrunt-json-out-dir` not properly place output files in a relative heirarchy

### ISSUE THREAD

**Issue by trogers-medasync** [gruntwork-io/terragrunt#3190]
## Describe the bug

When you use `terragrunt run-all plan` with `--terragrunt-json-out-dir` set and a different directory set as the working directory with  `--terragrunt-working-dir` it continuously overwrites a single tfplan.json instead of placing them into directories based on the structure of the working directory.

## Expected behavior

That the plan files get created in separate directories that mirror the relative directory structure from the working directory.

## Versions

- Terragrunt version: v0.58.14
- OpenTofu/Terraform version: Terraform v1.8.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Pop!OS 22.04

**Comment by levkohimins** [comment]
Hey @trogers-medasync, 
I understand your desire, but I'm not sure that it will be intuitively clear to other users, since in any program where you need to specify the path to the directory using a flag, the path is always relative to the working directory of the shell.

**Comment by levkohimins** [comment]
No news is good news. If you find problems feel free to open a new issue or reopen this one.

**Comment by trogers-medasync** [comment]
Sorry, I missed your initial comment.

I'm not asking for the `--terragrunt-json-out-dir` param to be relative from the directory specified in the `--terragrunt-working-dir`. The [documentation](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#saving-terraform-plan-output) shows that the output will be placed in directories based on the directory structure of the terragrunt files. That works fine as long as you don't specify a `--terragrunt-working-dir`. With that parameter specified, the plan outputs all get placed directly in the folder specified by the ``--terragrunt-json-out-dir` param and is continuously overwritten so you end up with 1 plan output file of whichever terragrunt stack updated last.

For example, given this directory structure:

```
/
  tg/
    app1/
      terragrunt.hcl
    app2/
      terragrunt.hcl
```

If I run `terragrunt run-all plan --terragrunt-json-out-dir ../plan_out` from `/tg`, `/plan_out` will look like this:

```
/
  plan_out/
    app1/
      tfplan.json
    app2/
      tfplan.json
```

as expected. However, if I specify `--terragrunt-working-dir` (i.e I ran `terragrunt run-all plan --terragrunt-working-dir ./tg --terragrunt-json-out-dir ./plan_out` from root) I'll get this output:

```
/
  /plan_out
    tfplan.json
```

and that `tfplan.json` will be for whichever stack finished planning last.

It's not too big of an issue since you can just first `cd`ing into the working directory you want and then specifying the out dir from there, and it seems like a bug. If that behavior is intentional, I think it should be documented because it definitely caught me by surprise.

**Comment by Mjb141** [comment]
@levkohimins This has just caught me by surprise. Using `--terragrunt-working-dir` (context: path is provided by matrix variables in Gitlab CICD) and `--terragrunt-json-out-dir` results in whichever plan was last created, as they all override each other. 

I expected the original behaviour of plans being created in a directory hierarchy inside the `terragrunt-json-our-dir` value directory (or as an alternative created in the directory's `.terragrunt-cache`).
