### ISSUE TITLE
`--terragrunt-tf-logs-to-json` logs are out-of-order

### ISSUE THREAD

**Issue by antoinedeschenes** [gruntwork-io/terragrunt#3207]
## Describe the bug

Terraform logs appear out-of-order when `--terragrunt-tf-logs-to-json` flag is enabled, but not in every cases. I can successfully reproduce with the below code:

## Steps To Reproduce

1. Create following files

```hcl
==> main.tf <==
variable "foo" {
  default = ""
}
 
resource "null_resource" "foo" {
  count = 2
 
  lifecycle {
    precondition {
      condition = var.foo == "foo"
      error_message = "invalid variable value"
    }
  }
}
 
data "google_compute_image" "image" {
  count = 2
 
  family = "debian-12"
  project = "debian-cloud"
 
  depends_on = [
    data.google_compute_image.image
  ]
}
 
==> terraform.tfvars <==
value1 = "1"
value2 = "2"
value3 = "3"
value4 = "4"
 
==> terragrunt.hcl <==
terraform {
  source = "."
}
```

2. Execute terragrunt plan:

```shell
terragrunt plan --terragrunt-json-log --terragrunt-tf-logs-to-json 2>&1  | jq .msg -r
```

## Expected behavior

I would expect logs to appear in order, as when the `--terragrunt-json-log --terragrunt-tf-logs-to-json` flags aren't set. Running the command with GOMAXPROCS=1 seems to work around the bug.

```shell
GOMAXPROCS=1 terragrunt plan --terragrunt-json-log --terragrunt-tf-logs-to-json 2>&1 | jq .msg -r
```

## Nice to haves

Logs appear in a different order after every runs. See screenshots:
<img width="648" alt="Screenshot 2024-06-14 at 12 08 35" src="[https://github.com/gruntwork-io/terragrunt/assets/6216119/04b37524-360d-4805-83e6-a9591757ffa0](https://github.com/gruntwork-io/terragrunt/assets/6216119/04b37524-360d-4805-83e6-a9591757ffa0)">
<img width="707" alt="Screenshot 2024-06-14 at 12 08 20" src="[https://github.com/gruntwork-io/terragrunt/assets/6216119/da50a949-6ec5-4f32-b03c-b1cdd8867718](https://github.com/gruntwork-io/terragrunt/assets/6216119/da50a949-6ec5-4f32-b03c-b1cdd8867718)">

## Versions

* Terragrunt version: `terragrunt version v0.59.3`
* OpenTofu/Terraform version: `Terraform v1.6.6`
* Environment details (Ubuntu 20.04, Windows 10, etc.): `darwin_amd64, macOS Somona 14.5 (23F79)`

## Additional context

I tried recompiling Terragrunt, switching the `logrus` format to `time.RFC3339Nano` to use jq to sort lines by timestamp, but the timestamps are also output out-of-order.

Output seems correct with `GOMAXPROCS=1` set on the terragrunt process.

Setting GOMAXPROCS for Terraform only doesn't change the output ordering.

```hcl
terraform {
  source = "."
  extra_arguments "default" {
    commands = ["plan"]
    env_vars = {
      GOMAXPROCS = "1"
    }
  }
}
```

**Comment by antoinedeschenes** [comment]
Ok, it looks like it's stdout and stderr being mixed as they aren't using the same logger. I *have* to split log outputs by level to get a clean output.

**Comment by wakeful** [comment]
maybe I don't understand your initial message but the `null_resource` and `data google_compute_image` resources are independent of each other, the underlying execution engine will schedule each of them to run in a **goroutine** and there is no guarantee on the order they will be finish, when you set the `GOMAXPROCS` you are allowing only one of them to be schedule at a given time.

**Comment by antoinedeschenes** [comment]
> maybe I don't understand your initial message but the `null_resource` and `data google_compute_image` resources are independent of each other, the underlying execution engine will schedule each of them to run in a **goroutine** and there is no guarantee on the order they will be finish, when you set the `GOMAXPROCS` you are allowing only one of them to be schedule at a given time.

Hi again, the output is out-of-order unless I run **terragrunt** using `GOMAXPROCS=1`. Any `GOMAXPROCS` value on the `terraform` process won't change the resulting output.

I investigated further after posting and it looks like this is related to the usage of [separate writers for stdout and stderr](https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd.go#L120-L129).
