### ISSUE TITLE
When get_aws_account_id() is used it is very slow

### ISSUE THREAD

**Issue by chinyongcy** [gruntwork-io/terragrunt#3210]
## Describe the bug

Very interesting problem I have come across...

My development machine I am using Mac (M1 Pro MacOS 14 - MacOS 15). I don't have any issues with it.
However, when I try to do on my CI. It either fails or runs very slowly.

My initial terragrunt config will contain something like this

```hcl
"arn:aws:iam::${get_aws_account_id()}:root"
```

Command ran:
terragrunt run init -backend=false -reconfigure
\-> I plan to do terragrunt validate afterwards.

On Mac:

* This works fine and i can validate

On Alpine Linux v3.20 Container:

* It will throw error messsage
  ` Error in function call; Call to function "get_aws_account_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.`

So.. in order to workaround that,
I rewrote my code to :

```hcl
locals {
   aws_account_id = get_env("ROLE_ARN", "") != "" ? get_aws_account_id() : "012345678901"
}

and then reference it later by ${local.aws_account_id}
```

Now this works fine on both CI and my Mac.
To complete a validate check on my environment when doing a run-all init and validate. On my Mac it takes about 3 to 5 mins. Still acceptable. However, on my CI machine, it took almost an hour, which is unbearable.

When doing a run all, I think it will build the dependencies graph.
So I did the following test on my CI machine.
While using `aws_account_id = get_env("ROLE_ARN", "") != "" ? get_aws_account_id() : "012345678901"`

```
time terragrunt graph-dependencies
real	2m 7.40s
user	0m 2.73s
sys	0m 0.21s
```

Next, I ran, which replace all instances of "get_aws_account_id()" and use a hardcoded value first for the test.

```
find . -type f -exec grep -l 'get_env("ROLE_ARN", "") != "" ? get_aws_account_id() : "012345
678901"' {} \; -exec sed -i 's/get_env("ROLE_ARN", "") != "" ? get_aws_account_id() : "012345678901"/012345678901/g' {} \;

# Result
time terragrunt graph-dependencies
real	0m 2.02s
user	0m 2.67s
sys	0m 0.17s
```

It's about 60x difference.
I have not even reached the plan or apply stage yet. Just doing a graph dependencies or init.
On my mac the difference, the result is negligible, but slightly faster.

I am not sure if there is anything wrong or something that I didn't install my in container.

## Versions

* Terragrunt version: 0.58.3/0.59.4 (also tried it on the latest)
* OpenTofu/Terraform version: NA
* Environment details (Ubuntu 20.04, Windows 10, etc.): Alpine Linux v3.20

## Additional context

The following is my dockerfile for my container

```Dockerfile
# Builder Python Version
ARG PYTHON_IMAGE_BUILDER_VERSION=3.10
# Alpine Version
ARG ALPINE_VERSION=3.20
 
FROM python:${PYTHON_IMAGE_BUILDER_VERSION}-alpine${ALPINE_VERSION} AS builder
# Dependencies Version
ARG AWS_CLI_VERSION=2.15.62
ARG TF_VERSION=1.8.4
ARG TF_LINT_VERSION=0.51.1
ARG TG_VERSION=0.58.3
 
RUN apk add --no-cache \
    ca-certificates \
    curl \
    git \
    unzip \
    groff \
    build-base \
    libffi-dev \
    cmake \
    jq
 
 
# AWS CLI
RUN git clone --single-branch --depth 1 -b ${AWS_CLI_VERSION} https://github.com/aws/aws-cli.git
WORKDIR /aws-cli
RUN ./configure --with-install-type=portable-exe --with-download-deps
RUN make
RUN make install
 
# reduce image size: remove autocomplete and examples
RUN rm -rf \
    /usr/local/lib/aws-cli/aws_completer \
    /usr/local/lib/aws-cli/awscli/data/ac.index \
    /usr/local/lib/aws-cli/awscli/examples
RUN find /usr/local/lib/aws-cli/awscli/data -name completions-1*.json -delete
RUN find /usr/local/lib/aws-cli/awscli/botocore/data -name examples-1.json -delete
RUN (cd /usr/local/lib/aws-cli; for a in *.so*; do test -f /lib/$a && rm $a; done)
 
# Install Terraform
RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then ARCHITECTURE=amd64; elif [ "${TARGETPLATFORM}" = "linux/arm64" ]; then ARCHITECTURE=arm64; else ARCHITECTURE=amd64; fi ;\
  if [ "${TF_VERSION}" = "latest" ]; then \
    VERSION="$( curl -LsS https://releases.hashicorp.com/terraform/ | grep -Eo '/[.0-9]+/' | grep -Eo '[.0-9]+' | sort -V | tail -1 )" ;\
  else \
    VERSION="${TF_VERSION}" ;\
  fi ;\
  for i in {1..5}; do curl -LsS \
    https://releases.hashicorp.com/terraform/${VERSION}/terraform_${VERSION}_linux_${ARCHITECTURE}.zip -o ./terraform.zip \
    && break || sleep 15; done ;\
  unzip ./terraform.zip ;\
  rm -f ./terraform.zip ;\
  chmod +x ./terraform ;\
  mv ./terraform /usr/bin/terraform
 
# Install Terragrunt
RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then ARCHITECTURE=amd64; elif [ "${TARGETPLATFORM}" = "linux/arm64" ]; then ARCHITECTURE=arm64; else ARCHITECTURE=amd64; fi ;\
  if [ "${TG_VERSION}" = "latest" ]; then \
    VERSION="$( curl -LsS https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest | jq -r .name )" ;\
  else \
    VERSION="v${TG_VERSION}" ;\
  fi ;\
  for i in {1..5}; do curl -LsS \
    https://github.com/gruntwork-io/terragrunt/releases/download/${VERSION}/terragrunt_linux_${ARCHITECTURE} -o /usr/bin/terragrunt \
    && break || sleep 15; done ;\
  chmod +x /usr/bin/terragrunt
 
# Install TF Lint
RUN if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then ARCHITECTURE=amd64; elif [ "${TARGETPLATFORM}" = "linux/arm64" ]; then ARCHITECTURE=arm64; else ARCHITECTURE=amd64; fi ;\
  if [ "${TF_LINT_VERSION}" = "latest" ]; then \
    VERSION="$( curl -LsS https://api.github.com/repos/terraform-linters/tflint/releases/latest | jq -r .name )" ;\
  else \
    VERSION="v${TF_LINT_VERSION}" ;\
  fi ;\
  for i in {1..5}; do curl -LsS \
    https://github.com/terraform-linters/tflint/releases/download/${VERSION}/tflint_linux_${ARCHITECTURE}.zip -o ./tflint.zip \
    && break || sleep 15; done ;\
   unzip ./tflint.zip ;\
   rm -f ./tflint.zip ;\
   chmod +x ./tflint ;\
   mv ./tflint /usr/bin/tflint
 
 
FROM python:${PYTHON_IMAGE_BUILDER_VERSION}-alpine${ALPINE_VERSION}
ARG TARGETPLATFORM="linux/amd64"
 
# Copy AWS CLI from Builder
COPY --from=builder /usr/local/lib/aws-cli/ /usr/local/lib/aws-cli/
COPY --from=builder /usr/bin/terragrunt /usr/bin/terraform /usr/bin/tflint /usr/bin/
RUN ln -s /usr/local/lib/aws-cli/aws /usr/local/bin/aws
 
# Update package and install necessary packages
RUN apk update && \
    apk add --no-cache \
    bash \
    busybox \
    git
 
# Install Python Dependencies
RUN pip3 install gitpython
 
# Cleanup
RUN rm -rf /var/cache/apk/* \
    /tmp/* \
    /root/.cache
 
CMD ["/bin/bash"]
 
```

**Comment by ZachGoldberg** [comment]
@chinyongcy At first glance it doesn't look like you're embedding any AWS credentials into your container at build time (which is best practice, so that's good!)  

Can you confirm you are adding your AWS credentials to your docker container at runtime?  (Similar to here - https://repost.aws/questions/QUENxOlpTyRKuW_PlAr0GvoQ/getting-aws-credentials-into-a-docker-container-without-hardcoding-it)

**Comment by chinyongcy** [comment]
> @chinyongcy At first glance it doesn't look like you're embedding any AWS credentials into your container at build time (which is best practice, so that's good!)
> 
> Can you confirm you are adding your AWS credentials to your docker container at runtime? (Similar to here - https://repost.aws/questions/QUENxOlpTyRKuW_PlAr0GvoQ/getting-aws-credentials-into-a-docker-container-without-hardcoding-it)

I have no issue with AWS credentials.
In my gitlab CI, only protected branch will have access to the AWS credentials, this part works perfectly I am able to deploy.
But on non protected branch it will not have the credentials.

I am running the following, which just do a simple validation check on the target environment.
```hcl
    - terragrunt run-all init -backend=false -reconfigure -input=false --terragrunt-working-dir $INFRA_DIR
    - terragrunt run-all validate --terragrunt-no-auto-init --terragrunt-working-dir $INFRA_DIR
    - terragrunt run-all validate-inputs --terragrunt-no-auto-init --terragrunt-working-dir $INFRA_DIR
```
At this stage, I do not want the stage to be able to reach to AWS first until the merge is complete and then it will trigger another pipeline that does the deployment to AWS which has the credentials as well.

So on my local development machine (Mac), where I don't have AWS credentials.
I can use "get_aws_acount_id()", and the validation will take 3 mins to 5 mins top and it won't throw an error 
`Error in function call; Call to function "get_aws_account_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.` 
which is great, I can do the validation without accessing AWS.
I am able to do terragrunt output-module-groups or terragrunt graph-dependencies to see the dependencies.
And it takes like 2 seconds to generate it which is still fine.

However on my CI.
Before my workaround of doing this
`aws_account_id = get_env("ROLE_ARN", "") != "" ? get_aws_account_id() : "012345678901"`
It will throw the above error message, which has a very different behavior in my development machine.

But even after my workaround, no more error message. 
The CI is taking 2mins to do `terragrunt graph-dependencies` as compared to 2 seconds on my local development machine.
and almost an hour to do the `terragrunt run-all validate` as compared to 3 to 5 mins on my local development machine.

**Comment by ZachGoldberg** [comment]
@chinyongcy I want to be 100% certain that the difference in timing you are seeing is not due to the presence (or lack there of) of AWS credentials.  The `get_aws_account_id` function DOES make an API call to AWS to determine the account ID, so if the credentials are missing I can see that causing delays/errors.

From your report thus far I'm not seeing any indication of a terragrunt bug, any chance you can create a minimal test case with repro steps?

**Comment by chinyongcy** [comment]
> @chinyongcy I want to be 100% certain that the difference in timing you are seeing is not due to the presence (or lack there of) of AWS credentials. The `get_aws_account_id` function DOES make [an API call](https://github.com/gruntwork-io/terragrunt/blob/master/aws_helper/config.go#L284) to AWS to determine the account ID, so if the credentials are missing I can see that causing delays/errors.
> 
> From your report thus far I'm not seeing any indication of a terragrunt bug, any chance you can create a minimal test case with repro steps?

Hi Zach,
Sorry for the late response, have manage to run the test and document the findings, hope the below helps. Apologies for being too quick to say it is a Terragrunt bug, but based on finding, it felt like one. Hopefully the testing scenario below will reveal this very interesting issue.

Below is the testing that I have done:
```
# My Directory
.
├── modules
│   ├── compute
│   ├── network
│   └── services
├── prd
│   ├── compute
│   ├── env.hcl
│   ├── network
│   └── services
├── terragrunt.hcl
```
I still have other env other than prd, but for the tests I am going to do, we will just be focusing on prd.


# Test Constants:
## Command
> All the tests will run the following command unless specified

Will cd into prd before running any of the command.
```
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE TERRAGRUNT_IAM_ROLE && \
time terragrunt graph-dependencies
```
### Explanation
Explanation: Just want to ensure that I don't have any AWS credentials in my system during the test
```
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE TERRAGRUNT_IAM_ROLE.
```
Explanation: Just want to use something that don't require an init to speed up the testing
```
time terragrunt graph-dependencies
```
## Machines
Linux Container for my CI:
	- OS: Alpine Linux 3.20
	- Terragrunt Version: v0.59.
	-  Refer to the above comment for Dockerfile (Except that I have upgrade the Terragrunt version to v0.59.4)
	- Will refer this to Linux later on

Mac Development Machine: 
	- OS: Mac OS 15.0 Beta (24A5264n) [M1 Pro 16"]
	- Terragrunt Version: v0.59.4
	- Understand that I am running on a beta version, but previously when I was on the latest Mac OS 14.0, It behaves the same.
	- Will refer this to Mac later on

# Issue 1: Inconsistent behavior between Mac device vs Linux Container when using get_aws_account_id()


## Test Scenario
### .env file
```
locals {
	aws_account_id =  get_aws_account_id()
}
```
> I think the rest of the code doesn't really matter (do let me know if you need the full hcl.
> The rest of the modules that requires the account id will reference this.
by doing 
```
locals {
	aws_account_id =  read_terragrunt_config(find_in_parent_folders("env.hcl")).locals.aws_account_id
}
# then in my input, I will use "local.aws_account_id" to reference
```


### Result:
#### Mac OS:
> Command ran successfully, with no issue
```
<Showing me the digraph>
terragrunt graph-dependencies  3.47s user 0.30s system 8% cpu 42.465 total
```

#### Linux:
> Command failed with the following error message
```
ERRO[0012] Error: Error in function call
       prefix=[<truncated>/prd/compute/ebs_volume]
ERRO[0012]   on <truncated>/prd/env.hcl line 32, in locals:  prefix=[<truncated>/prd/compute/ebs_volume]
ERRO[0012]   32:   aws_account_id = get_aws_account_id()  prefix=[<truncated>/prd/compute/ebs_volume]
ERRO[0012]                                               prefix=[<truncated>/prd/compute/ebs_volume]
ERRO[0012] Call to function "get_aws_account_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?):
NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.
  prefix=[<truncated>/prd/compute/ebs_volume]
ERRO[0012] Error processing module at '<truncated>/prd/compute/ebs_volume/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of <truncated>/prd. Underlying error: <truncated>/prd/env.hcl:32,20-39: Error in function call; Call to function "get_aws_account_id" failed: Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors.
ERRO[0012] Unable to determine underlying exit code, so Terragrunt will exit with error code 1
ERRO[0012] Suggested fixes:
Missing AWS credentials. Provide credentials to proceed.

real	0m12.574s
user	0m0.035s
sys	0m0.035s
```

Findings:
Yes, I do remember that. you said get_aws_account_id function does make an API Call to determine the account ID.
So, what I am trying to understand is on my Mac, able to run it without error, While on the Linux it is throwing me an error. I wouldn't say this is a big issue, just that this error caught me by surprise in Linux during the CI. There is an inconsistent behavior here.


# Issue 2 - Workaround, but it takes very long

## Test Scenario 1:
### .env file
``` 
locals {
	aws_account_id = get_env("AWS_ACCESS_KEY_ID", "") == "" ? "012345678901" : get_aws_account_id()
}
```
Explanation:
My use case is to do terragrunt validate without having able to connect to aws.
I am not really a programmer per say, but I am thinking by doing the above, 
if get_env fails to get "AWS_ACCESS_KEY_ID" then it will return ""
If it is "" it will return a dummy account_id for the validation to run with "012345678901" without evaluating to get_aws_account_id() thus won't make the api call thus won't throw the error in the above scenario.
However, if AWS_ACCESS_KEY_ID exists in the environment variables, then it evaluates to use get_aws_account_id() then making the api call.
Not sure if this is the behaviour, just assuming for now.


### Result 
#### Mac:
> Command ran successfully, with no issue. 
```
<Showing me the digraph>
terragrunt graph-dependencies  3.57s user 0.27s system 8% cpu 43.214 total
```
##### Linux:
> Command ran successfully, but takes way too much time than expected, I repeated the test and get around the same result
```
<Showing me the digraph>
real	36m0.898s
user	0m4.009s
sys	0m0.786s
```
Findings:
Here Linux is taking very slow for this task. Understand that my CI runner processing power might not be as strong, but this doesn't make any sense to me taking 36 minutes to run just a graph-dependencies.

## Test Scenario 2: Hardcoding it directly
### .env file
```
locals {
	aws_account_id = "012345678901"
}
```
Explanation:
Just for testing the speed difference, even though both scenarios 1 and 2 will use the same dummy value. But without the "if" logic there, it runs faster.

### Result 
#### Mac:
> Command ran successfully, with no issue.  Also realized on mac it takes 1 second longer to complete. 
```
<Showing me the digraph>
terragrunt graph-dependencies  2.27s user 0.11s system 148% cpu 1.609 total
```
#### Linux:
> Command ran successfully, with no issue. 
```
<Showing me the digraph>
real	0m2.313s
user	0m3.153s
sys	0m0.180s
```


Findings:
This tells me that in scenario 1, even with the if condition, in both system, 
even if `get_env("AWS_ACCESS_KEY_ID", "") == ""`, it will still try to evaluate get_aws_account_id(), causing the increase in run time. 

Could it be possible some libraries are missing in my CI container? 

## Workaround
### .env file
```
locals {
	aws_account_id = get_env("AWS_ACCOUNT_ID", "012345678901")
}
```
Explanation:
So in my CI Stage, before running any commands when I am deploying,
I will have to run the following command:
`export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)`
In those stages, where I just need to run validate, I don't have to run this command.

### Result
#### Mac:
> Command ran successfully, with no issue.
```
<Showing me the digraph>
terragrunt graph-dependencies  2.23s user 0.11s system 148% cpu 1.580 total
```

#### Linux:
> Command ran successfully, with no issue and now this is normal.
```
<Showing me the digraph>
real	0m2.495s
user	0m3.201s
sys	0m0.241s
```

Finding:
In this workaround the run time around the same within margin of error on both systems. This runs fine.
Both takes around the same time. ~2 second.


Do let me know what else is needed for the test! Thank you so much Zach for the time!

**Comment by ZachGoldberg** [comment]
@denis256 Can you confirm if `get_aws_account_id()` is called as part of parsing, and thus would be called regardless of the value of the ternary in this example?

```
locals {
  account_id = some_boolean_value ? 1234 : get_aws_account_id()
}
```

@chinyongcy  - Thanks for this detailed writeup!  I want to clarify one other thing on AWS Auth -- the GoLang SDK uses the [default credential chain](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#:~:text=When%20you%20initialize%20a%20new,returns%20credentials%20without%20an%20error.) to look up AWS credentials, which includes the environmental variables but also a shared configuratin file (such as `~/.aws/credentials`).  Can you confirm if your Mac has such a file present and is perhaps using that despite your efforts to unset the values?

**Comment by chinyongcy** [comment]
> @denis256 Can you confirm if `get_aws_account_id()` is called as part of parsing, and thus would be called regardless of the value of the ternary in this example?
> 
> ```
> locals {
>   account_id = some_boolean_value ? 1234 : get_aws_account_id()
> }
> ```
> 
> @chinyongcy - Thanks for this detailed writeup! I want to clarify one other thing on AWS Auth -- the GoLang SDK uses the [default credential chain](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#:~:text=When%20you%20initialize%20a%20new,returns%20credentials%20without%20an%20error.) to look up AWS credentials, which includes the environmental variables but also a shared configuration file (such as `~/.aws/credentials`). Can you confirm if your Mac has such a file present and is perhaps using that despite your efforts to unset the values?

@ZachGoldberg ah yes, I missed this out.
You're right.
i did a rm -rf ~/.aws/credentials on my Mac.
then i run the same command with Mac.

# Issue 1/Test Scenario env.hcl file
```
locals {
  aws_account_id = get_aws_account_id()
}
```
Now it is throwing me the error as well. Sorry for the oversight. There is no inconsistency in the behavior between different system.
This is due to  ~/.aws/credentials as you have mentioned.

Next 
# Issue 2/Test Scenario 1 env.hcl file
```
locals {
	aws_account_id = get_env("AWS_ACCESS_KEY_ID", "") == "" ? "012345678901" : get_aws_account_id()
}
```
Now it takes longer, up to 2mins+ to complete
```
terragrunt graph-dependencies  4.77s user 0.97s system 4% cpu 2:04.79 total
```

So left with timing issue, next let me try and also ensure aws-cli it running on the same version and then report back.

**Comment by chinyongcy** [comment]
Now on both machine: aws-cli=2.16.10 

On Mac is still taking around 2mins
```
terragrunt graph-dependencies  4.20s user 0.95s system 4% cpu 2:02.28 total
```

On Linux, 5 mins has passed since I last run.
So I believe it is going to take very long time as well, aws-cli version doesn't fix the time needed to run on Alpine Linux.
I would say this issue where it is taking very long to validate lies with how aws-cli work in Linux, issue is with aws-cli side. 

I guess what's left is the confirmation of how Terragrunt evaluate in a ternary. Not sure if this is consider a bug or a behaviour. For now, I will use the workaround first. 

Thank you very much @ZachGoldberg . Is it okay to close this?

**Comment by denis256** [comment]
>@denis256 Can you confirm if get_aws_account_id() is called as part of parsing, and thus would be called regardless of the value of the ternary in this example?
> locals {
>  account_id = some_boolean_value ? 1234 : get_aws_account_id()
> }


Yes, AFAIK, this is how HCL evaluation works, first are evaluated functions, and then branches.
At some point this was fixed but it is not working in all cases.

References:
https://github.com/hashicorp/terraform/issues/15605#issuecomment-598461303

**Comment by ZachGoldberg** [comment]
Thanks Denis!

Hi @chinyongcy I'm glad we've got a valid workaround!  I'll go ahead and close this out for now.
