### ISSUE TITLE
--terragrunt-non-interactive does not appear to work without one of the run-all commands

### ISSUE THREAD

**Issue by jevon71-work** [gruntwork-io/terragrunt#3215]
## Describe the bug

The documentation of the CLI switches describes this option `--terragrunt-non-interactive`, which allows automation to ignore prompts.  However, it appears despite the documentation, that it is only used when using the `run-all` (and the other -all) command.

## Steps To Reproduce

```hcl
// paste code snippets here
terragrunt apply --terragrunt-non-interactive
```

## Expected behavior

Not to be prompted to apply, or the documenation to explain that this switch only applies to the run-all command

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.58.10
- OpenTofu/Terraform version: 1.8.4
- Environment details (Ubuntu 20.04, Windows 10, etc.): All

## Additional context

Clarification request most likely.

**Comment by denis256** [comment]
Hi,
`--terragrunt-non-interactive` documentation specifies cases when it is used:

> This will default the answer for all prompts to `yes` except for the listed cases below.

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-non-interactive

Most probably you are looking for setup like:
```
terragrunt apply -auto-approve --terragrunt-non-interactive 
```
