### ISSUE TITLE
Terragrunt version: 'v0.59.5' causes BlobNotFound error

### ISSUE THREAD

**Issue by correalenon** [gruntwork-io/terragrunt#3220]
## Describe the bug

This error was previously seen in version v0.59.0 and was resolved. It appears it has been re-released in version 0.59.5. In that broken version the version was missing the complied binaries.

[#3195](https://github.com/gruntwork-io/terragrunt/issues/3195)

## Steps To Reproduce

Our code:
```hcl
LATEST_URL=$(curl -sL  https://api.github.com/repos/gruntwork-io/terragrunt/releases  | jq -r '.[0].assets[].browser_download_url' | egrep 'linux.*amd64' | tail -1)
curl -sL ${LATEST_URL} > /usr/local/bin/terragrunt
chmod u+x /usr/local/bin/terragrunt
terragrunt --version
```

Result:
```hcl
 /usr/local/bin/terragrunt: line 1: syntax error near unexpected token `<'
/usr/local/bin/terragrunt: line 1: `﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.'
```

## Expected behavior

The pipeline should be able to download and run terragrunt and cannot.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.59.5

**Comment by M0NsTeRRR** [comment]
Got the same issue in a github action

**Comment by yhakbar** [comment]
Thanks for reporting this! Re-running the build.

**Comment by sachin-kumar10** [comment]
<img width="1138" alt="Terragrunt Error Screenshot" src="https://github.com/gruntwork-io/terragrunt/assets/102659542/d27d3aeb-0c67-4e2a-847a-e9fe59832650">

**Comment by yhakbar** [comment]
This was resolved by re-running the build.

We're not sure why this happens specifically for amd64 asset uploads. The upload goes through just fine, but the underlying Azure blob storage shows the asset as missing. We'll be adding some automated checks to at least detect when this happens, but it's definitely bizarre.
