### ISSUE TITLE
v0.59.2 release broke sops integration with azure vault 

### ISSUE THREAD

**Issue by tsolodov** [gruntwork-io/terragrunt#3228]
## Describe the bug
v0.59.2 updated Azure SDK library, looks suspicious.

[v0.59.1](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.59.1) works fine.

What happens: 
When you run `terragrunt plan`, it stuck for 5 minutes and later prints error:
```
* error decrypting key: [error decrypting key https://xxxxxxx.vault.azure.net/keys/sops/yyyy: [failed to decrypt sops data key with Azure Key Vault key 'https://xxxxxxxvault.azure.net/keys/sops/yyyy': DefaultAzureCredential authentication failed. failed to acquire a token.
Attempted credentials:
	EnvironmentCredential: missing environment variable AZURE_TENANT_ID
	WorkloadIdentityCredential: no client ID specified. Check pod configuration or set ClientID in the options
	ManagedIdentityCredential authentication failed. ManagedIdentityCredential authentication failed. authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 404 Not Found
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
		 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>

--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
```

I saw child process that obtains token, this commands works fine.
```
/usr/bin/az account get-access-token -o json --resource https://vault.azure.net
```
Running it manually works. ^ 

I did try to set `AZURE_TENANT_ID` ENV var, did not help. 

## Steps To Reproduce

1. Terragrunt is executed on AWS VM.
2. Encrypt file using azure vault. 
3. Use Azure Service Principal auth with password:
`az login --service-principal  --tenant xxxx --password xxxx --username yyy`

4. Use sops file encrypted with azure vault.
```hcl
yamldecode(sops_decrypt_file(find_in_parent_folders("secrets.yaml")))
```

## Expected behavior

terragrunt `sops_decrypt_file` should work with azure vault using service principal secret-based auth.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.59.5
- OpenTofu/Terraform version: v1.x.x
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 20.04,

**Comment by tsolodov** [comment]
wait, I just found a solution. With new SDK terragrunt news these ENV vars:
```
export AZURE_TENANT_ID="<active_directory_tenant_id>"
export AZURE_CLIENT_ID="<service_principal_appid>"
export AZURE_CLIENT_CERTIFICATE_PATH="<azure_client_certificate_path>"
```

https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication-service-principal?tabs=azure-cli#option-1-authenticate-with-a-secret

**Comment by tsolodov** [comment]
I can confirm it works now, please update release notes for 59.2. It's a breaking change.

**Comment by denis256** [comment]
Updated release notes
