### ISSUE TITLE
Quick start example fails

### ISSUE THREAD

**Issue by james64** [gruntwork-io/terragrunt#3230]
## Describe the bug

[Quick start](https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#example) example from home page fails when run per instructions. AWS provider version is not specified but vpc module version is. It's old version of `3.5.0` is incompatible with latest aws provider. `enable_classiclink` property is not supported anymore.

## Steps To Reproduce

Follow quick start example.

## Expected behavior

`terragrunt apply` should not fail like this.

## Nice to haves

Terminal output:
```
│ Error: Unsupported argument
│
│   on main.tf line 32, in resource "aws_vpc" "this":
│   32:   enable_classiclink               = var.enable_classiclink
│
│ An argument named "enable_classiclink" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 33, in resource "aws_vpc" "this":
│   33:   enable_classiclink_dns_support   = var.enable_classiclink_dns_support
│
│ An argument named "enable_classiclink_dns_support" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 1306, in resource "aws_default_vpc" "this":
│ 1306:   enable_classiclink   = var.default_vpc_enable_classiclink
│
│ An argument named "enable_classiclink" is not expected here.
╵
```

## Versions

- Terragrunt version: 0.52.0
- OpenTofu/Terraform version: Terraform v1.8.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): ubuntu 24.04

**Comment by yhakbar** [comment]
Thanks for reporting this @james64 !
