### ISSUE TITLE
`run_cmd` in locals breaks the `graph-dependencies` output

### ISSUE THREAD

**Issue by bernardhalas** [gruntwork-io/terragrunt#3235]
## Describe the bug

Hello,

Recently while attempting to upgrade Terragrunt from 0.45.11 to 0.59.4 we noticed an issue with the `graph-dependency` command. This command generates a text representation of the dependency graph, which is then plotted by graphviz tools. However, we've noticed it started becoming cluttered with other outputs, that break the graphviz processing. 

## Steps To Reproduce

```hcl
$ cat first/terragrunt.hcl
locals {
 a = run_cmd("/usr/bin/echo", "foobar")
}

terraform {
 source = "../module"
}

inputs = {
 input = "abcdef"
}
```
And then executed this way:

```hcl
$ terragrunt graph-dependencies
foobar
digraph {
       "first" ;
}
```
As you can see, `foobar` in the outputs of the command is breaking the functionality of graph-dependencies.

## Expected behavior

The output of the `run_cmd` command doesn't appear on STDOUT.

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.59.4
- OpenTofu/Terraform version: N/A
- Environment details (Ubuntu 20.04, Windows 10, etc.): Linux OS (OpenSUSE and Ubuntu)

**Comment by denis256** [comment]
Hi,
In some cases, the output of run_cmd can be useful to see. If it isn't necessary, you can use the `--terragrunt-quiet` flag.

https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd

**Comment by bernardhalas** [comment]
Thank you for the quick response, that solves it.
