### ISSUE TITLE
Auto-answer "no", opposite of "--terragrunt-non-interactive"

### ISSUE THREAD

**Issue by pavelpulec** [gruntwork-io/terragrunt#3240]
### Summary

I like the option `--terragrunt-non-interactive` but it automatically answers "yes" to all prompts. I would welcome a very same option but that would anwer "no" to all prompts.

### Motivation

I was run Terragrunt safely in CI/CD. Using `--terragrunt-non-interactive` in `terragrunt plan` can update S3 buckets for example when there is any change.

### Proposal

Add a new option or parametrize the `--terragrunt-non-interactive` option with possibility to choose if prompts should be answered by "yes" or "no".

### Technical Details

The current behavior of `--terragrunt-non-interactive` can be untouched. This change can be backward compatible.

### Press Release

The option "--terragrunt-non-interactive" can be used with a parameter y/yes or n/no to safely run Terragrunt in automated environments.

### Support Level

- [ ] I have Terragrunt Enterprise Support
- [ ] I am a paying Gruntwork customer

**Comment by yhakbar** [comment]
Sorry it's taken me so long to get back to you @pavelpulec .

Do you know of any other tools that follow this pattern? I've only ever seen tools introduce `--yes/-y` style flags for other tools and want to make sure we're not accidentally introducing an anti-pattern here.

I'm trying to understand why something like the following is not appealing:

```bash
terragrunt run-all plan </dev/null
```

As the default behavior is already that the value will be set to no, you're just looking to close stdin.

Is there a scenario where the workaround above wouldn't meet your needs?

**Comment by pavelpulec** [comment]
> Sorry it's taken me so long to get back to you @pavelpulec .
> 
> Do you know of any other tools that follow this pattern? I've only ever seen tools introduce `--yes/-y` style flags for other tools and want to make sure we're not accidentally introducing an anti-pattern here.

I have seen the very same flags in other tools. It could be this way or by adding the parameter to `--terragrunt-non-interactive` what to response automatically.

It's also interesting that the `-input=false` doesn't help in this case and the process is hanging. But it probably doesn't apply to all types of inputs that Terragrunt/Terraform/OpenTofu can request.

> 
> I'm trying to understand why something like the following is not appealing:
> 
> ```shell
> terragrunt run-all plan </dev/null
> ```
> 
> As the default behavior is already that the value will be set to no, you're just looking to close stdin.
> 
> Is there a scenario where the workaround above wouldn't meet your needs?

Yes, I think this can work in my situation. Thanks for the advice.

**Comment by yhakbar** [comment]
It seems like this is a usable workaround for now.

I'll close this RFC as rejected, but please feel free to re-open if you find an edge case where the workaround doesn't suffice.
