### ISSUE TITLE
sops_decrypt_file does not use the correct AWS endpoint when using EKS pod identities

### ISSUE THREAD

**Issue by ryanrf** [gruntwork-io/terragrunt#3246]
## Describe the bug

Apologies if this is a duplicate, but I didn't see anything related when searching. The latest release of Terragrunt uses [sops 3.8.1](https://github.com/gruntwork-io/terragrunt/blob/32963721deb7c992d95846271f75b3e121126056/go.mod#L61), which is using an earlier version of the aws-sdk-go-v2 which doesn't yet [support the different endpoint used by EKS pod identities](https://github.com/aws/aws-sdk-go-v2/blob/main/credentials/CHANGELOG.md#v1160-2023-11-14) for authenticating with AWS. Because of this it's not possible to use the `sops_decrypt_file` function with sops using a KMS key within an EKS pod using pod identities, until the sops go module is updated to at least [3.9.0](https://github.com/getsops/sops/blob/19259529106022b62f758956c04f025c832a1f11/go.mod#L15)

## Steps To Reproduce
Use an [EKS pod identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) attached to a container and attempt to run a Terragrunt hcl file with `sops_decrypt_file`. There will be an error similar to

```shell
    - | could not load AWS config: invalid endpoint host,
      | "169.254.170.23", only loopback hosts are allowed
```

Another, and possibly simpler, reproduction of this issue is running a pod with an EKS pod identity attached then grabbing the 3.8.1 version of sops (the compiled binary, not the go module) and the 3.9.0 version of sops. With the 3.8.1 version you'll see the error from above, with the 3.9.0 version you'll see the decrypted version of the file. Just a reminder, this is only an issue when using KMS as the sops go module will use the older AWS sdk for accessing KMS.

## Expected behavior

`sops_decrypt_file` should be able to decrypt a sops encrypted file (encrypted with a KMS key).

## Versions

- Terragrunt version:
- OpenTofu/Terraform version: terragrunt version v0.59.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): in EKS pod "Alpine Linux v3.20"

## Additional context

I'm not sure if this is as simple as upgrading the sops go module used, but if I can help or test anything just let me know.

**Comment by denis256** [comment]
Upgraded Sops in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.64.0
