### ISSUE TITLE
`--terragrunt-out-dir` does not work when running `run-all plan` in a leaf directory

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#3253]
## Describe the bug

When running a `run-all plan` with `--terragrunt-out-dir` in a leaf directory, a strange filesystem permissions error pops up that is difficult to debug.

Terragrunt should either throw a clear error explaining why this is happening, or gracefully handle the behavior.

Note that this is a strange edge case, as most users should just use `terragrunt plan` instead of `terragrunt run-all plan` in a scenario such as this, but most users expect `run-all plan` to work just like `plan` within a leaf directory.

There's likely some logic that doesn't work right for reproducing the relative paths to `terragrunt.hcl` files in the `--terragrunt-out-dir` directory when run at a leaf directory.

## Steps To Reproduce

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```bash
terragrunt run-all plan --terragrunt-out-dir test
```

## Nice to haves

- [x] Terminal output
- [x] Screenshots

```
│ Error: Failed to write plan file
│
│ The plan file could not be written: open
│ github-actions-openid-connect-provider/tfplan.tfplan: no such file or
│ directory.
```

<img width="467" alt="image" src="https://github.com/gruntwork-io/terragrunt/assets/11247449/f8f23190-1022-41ba-b8d5-c12677fefa71">

## Versions

- Terragrunt version: v0.60.0
- OpenTofu version: v1.6.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): GHA Ubuntu Latest and MacOS

**Comment by FNSdev** [comment]
Hello,

I am having the same issue when running from a root directory (`env-1`), e.g.

```
├── env-1
│   ├── module-1
│   │   ├── terragrunt.hcl
│   │   └── vars.yaml
│   ├── module-2
│   │   ├── terragrunt.hcl
│   │   └── vars.yaml
└── terragrunt.hcl
```

`-> % terragrunt run-all plan --terragrunt-out-dir ./tfplan`

```
│ Error: Failed to write plan file
│ 
│ The plan file could not be written: open tfplan/module-1/tfplan.tfplan:
│ no such file or directory.
```

**Comment by vixus0** [comment]
To add to this, I get completely different behaviour if I use `--terragrunt-working-dir` with a relative path instead of an absolute path.

For example:

```
# create live/test1/terragrunt.hcl
# create live/test2/terragrunt.hcl

terragrunt run-all plan --terragrunt-working-dir live --terragrunt-out-dir /tmp/plan
```

Both plans get written to `/tmp/plan/tfplan.tfplan`.

If I instead run:

```
terragrunt run-all plan --terragrunt-working-dir "$PWD/live" --terragrunt-out-dir /tmp/plan
```

I get:
- `/tmp/plan/test1/tfplan.tfplan`
- `/tmp/plan/test2/tfplan.tfplan`

I would expect the same output for both commands.

**Comment by shaqualcheg** [comment]
> Results in both plans being written to `/tmp/plan/tfplan.tfplan`.

same for me, except one thing: if i use absolute path for workdir, terragrunt not found .hcl files

I fixed problem by adding extra_argutments for plan and apply terraform command

`
extra_arguments "set_tf_plan_out" {
    commands     = ["plan"]
    arguments      = ["-out", "${get_repo_root()}/.terraform/terragrunt_plans/${basename(get_original_terragrunt_dir())}.tfplan"]
  }

  extra_arguments "set_tf_plan" {
       commands  = ["apply"]
       arguments = ["${get_repo_root()}/.terraform/terragrunt_plans/${basename(get_original_terragrunt_dir())}.tfplan"]
  }
`


and removing TERRAGRUNT_OUT_DIR, but i wanna use run-all function without such workaround

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.68.6
