### ISSUE TITLE
Not able to pass inputs as array  to Terraform

### ISSUE THREAD

**Issue by Ashraf1991** [gruntwork-io/terragrunt#3256]
## Describe the bug

Using the below code, I am able to pass object id as array in terraform but not able to pass from Terragrunt input file and I have the following error .

cloud - Azure , service -  Key vault

Main.tf:
dynamic "access_policy" {
for_each = toset(flatten([
for policy in var.access_policies : [
for object_id in policy.object_id : {
object_id = object_id
secret_permissions = policy.secret_permissions
key_permissions = policy.key_permissions
}
]
]))

content {
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id          = access_policy.value.object_id
  secret_permissions = access_policy.value.secret_permissions
  key_permissions    = access_policy.value.key_permissions
}
}

variable "access_policies" {
type = set(object({
object_id = set(string),
secret_permissions = set(string),
key_permissions = set(string)
}))

terragrunt.hcl :
inputs = {
access_policies = [
{ object_id = ["xyz", "abc"], secret_permissions = ["Get", "Set"], key_permissions = ["Get"] }
{ object_id = include.env.locals.env_vars.locals.object_id, secret_permissions = ["Get"], key_permissions = ["Get"] }
]
}

env.hcl:
locals
{   object_id = toset (["3db"])  }

current error:
Planning failed. Terraform encountered an error while generating this plan.
350│ Error: Invalid value for input variable
351│
352│ on variables.tf line 28:
353│ 28: variable "access_policies" {
354│
355│ Unsuitable value for var.access_policies set using the
356│ TF_VAR_access_policies environment variable: element 0: attribute
357│ "object_id": string required.

I have not defined TF_VAR_access_policies anywhere in my code..

## Expected behavior

To Pass array value from input file of terragrunt to terraform .

**Comment by denis256** [comment]
Hi,

The description does not specify which versions of Terragrunt, Terraform, or the operating system are being used. Additionally, the attached code is difficult to read because it is not properly formatted.

Based on the information that I could parse, I have prepared an example, which you can find here: https://github.com/denis256/terragrunt-tests/tree/master/issue-3256  - it passes array as inputs from Terragrunt to OpenTofu, OpenTofu save inputs to JSON files.

Used versions:
OpenTofu v1.7.0
Terragrunt v0.61.1

**Comment by yhakbar** [comment]
Hey @Ashraf1991 

This issue has gone stale, so we're closing it out. Please feel free to re-open if you have a reproducible example.

For future awareness: Adding information like the versions of Terragrunt, Terraform and OS help us to make sure we can reproduce the bug that you encountered to develop a fix if there's a problem. Formatting code using back-ticks (```) around your code helps us read the code so that we can be sure we're reproducing it correctly.

Thanks for reporting the issue!
