### ISSUE TITLE
Caching STS Credentials with IAM Role

### ISSUE THREAD

**Issue by qrevel** [gruntwork-io/terragrunt#326]
Hi,

First of all, the support of IAM Role is really usefull.
I'm currently on a very low internet connection and it seems that each time I execute a command, terragrunt ask for new credentials.
Is it possible to cache credentials given by the first sts assume-role?
Therefore we only update credentials when needed.

Thanks

**Comment by brikis98** [comment]
> I'm currently on a very low internet connection and it seems that each time I execute a command, terragrunt ask for new credentials.

I'm having trouble understanding what a slow internet connection has to do with credentials. Where does Terragrunt ask for credentials? How are you currently providing your credentials (env var, profile, IAM role, etc)?

**Comment by qrevel** [comment]
I'm providing an IAM Role as a credentials, Terragrunt then assume the role as expected:
```
[terragrunt] 2017/10/21 12:02:06 Assuming IAM role arn:aws:iam::XXX:role/Administrators
```
The problem is this step takes a long time (5s) to complete on every terragrunt command.
I suppose it's my internet connection but it maybe something else.

**Comment by brikis98** [comment]
Ah, I see. Yes, if your Internet is slow, assuming an IAM role will take some time. There is no obvious & secure way for Terragrunt to cache those credentials. The best you can do is to install the AWS CLI, call [aws sts assume-role](http://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html), and set the credentials you get back as environment variables. Those creds are good for ~1 hour and Terragrunt/Terraform will use them automatically.

**Comment by FernandoMiguel** [comment]
>  Those creds are good for ~1 hour 
unless you are using MFA, which makes them only 5 min :D  

I would recommend aws-vault over aws cli since it does manage roles much easier and tokens arent saved in clear text

**Comment by brikis98** [comment]
> unless you are using MFA, which makes them only 5 min

No, I'm pretty sure it's still 1 hour, even with MFA.

> I would recommend aws-vault over aws cli since it does manage roles much easier and tokens arent saved in clear text

AFAIK, aws-vault calls assume role for every single command, so it'll be no faster than asking Terragrunt to assume that role. That said, yes, aws-vault is a good tool for secret storage.

**Comment by FernandoMiguel** [comment]
i use mfa on all my accounts, and daily on aws cli and terraform.
it's sadly (?) much less than one hour :(

**Comment by brikis98** [comment]
We use MFA for all accounts too. It's always been an hour for us. See the `--duration-seconds` parameter here: http://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html

**Comment by FernandoMiguel** [comment]
thanks for pointing out that resource, will have a look.
will be useful for when deploying RDS which always times out with terraform/terragrunt :D

**Comment by brikis98** [comment]
I believe the original question has been answered, so closing
