### ISSUE TITLE
Improve Context When Logging For State Bucket Updates

### ISSUE THREAD

**Issue by chipbell4** [gruntwork-io/terragrunt#3273]
### Summary

When terragrunt checks state S3 bucket and finds an issue, it'll log a message and prompt the user (this happens [here](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L500)). However, the prompt indicates that terragrunt is about to modify that bucket, but it doesn't communicate what it's about to do. I think this would be helpful for users before a bucket's settings are (potentially permanently) modified.

It appears that the variable `bucketUpdatesRequired` has all the information needed, but it just needs to be logged, perhaps with the bucket it's about to modify.

### Motivation

As I set up new projects, I'm paranoid that I'm getting ready to modify the _wrong_ bucket. Why _else_ would terragrunt prompt me all of a sudden about a bucket that I _thought_ I had used before. This would provide a small sanity check when setting up projects.

### Proposal

Update the state bucket prompt [here](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L500) to inform the user which bucket is about to be modified and what about the bucket is about to modified.

### Technical Details

Add a new function onto `S3BucketUpdatesRequired` that logs general "facts" about it. Something ala:

```go
func (s S3BucketUpdatesRequired) String() string {
    // Do stuff
    return ""
}
```

### Press Release

We've improved logging for state bucket setup. Now, before updating a state bucket, we provide a list of what we're about to change before we prompt you. This will allow you to see what's about to change on the bucket first.

### Drawbacks

This would create more code to maintain, and it'd be difficult to unit test.

### Alternatives

A quick update to that `fmt.Sprintf` to include a `%+v` is faster but less user-friendly.

### Migration Strategy

No migrating needed.

### Unresolved Questions

No unresolved questions.

### Support Level

- [ ] I have Terragrunt Enterprise Support
- [ ] I am a paying Gruntwork customer

**Comment by chipbell4** [comment]
Ah, I just now see that it is being logged and I overlooked it in the output!

**Comment by yhakbar** [comment]
Thanks for the RFC, even if it was short lived, @chipbell4 !
