### ISSUE TITLE
CLI argument`--terragrunt-include-dir` includes all folders if the pattern does not match since version `0.50.1`

### ISSUE THREAD

**Issue by Cakasim** [gruntwork-io/terragrunt#3274]
## Describe the bug

A run of `terragrunt run-all apply --terragrunt-include-dir "does-not-exist-*"` leads to apply of all folders in the current directory. Especially dangerous when running in the CI and you upgraded from 0.50.0 to any later version!

The weird behaviour of this was introduced with this PR: https://github.com/gruntwork-io/terragrunt/pull/2664

IMO this is a breaking change but was added as a patch increment.

## Steps To Reproduce

- Create a folder with multiple subfolders that contain `terragrunt.hcl` files.
- Head to the folder and execute the above mentioned command, make sure the include pattern you specify does not match.
- You should see that it selects all folders for the execution plan.

I confirmed in my local tests that it is not related to glob matching, so any non existing folder in the include should work to reproduce the problem.

## Expected behavior

- After executing the above command and no folder is matching the specified include pattern, I expect an empty execution and nothing to happen.
- The argument `--terragrunt-include-dir` should work like a whitelist (which it did before version 0.50.1)

## Nice to haves

A screenshot of a CLI session to reproduce:
<img width="1338" alt="Screenshot 2024-07-18 at 13 00 21" src="https://github.com/user-attachments/assets/6f640c01-5817-40c7-8e67-c2c285f5054c">

## Versions
- Terragrunt version: 0.50.0

**Comment by yhakbar** [comment]
That definitely is a bug! We'll look to get it fixed!

**Comment by yhakbar** [comment]
Resolved in [v0.63.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.63.4).
