### ISSUE TITLE
Using provider caching with existing `.terraformrc` having `provider_installation` block defined.

### ISSUE THREAD

**Issue by nuryupin-kr** [gruntwork-io/terragrunt#3287]
@levkohimins

Since the [original issue](https://github.com/gruntwork-io/terragrunt/issues/3278) is now closed I created this one for visibility.

Unfortunately, v0.63.3 didn't fix our issue. Still seems like `network_mirror` is not respected. The error says that it's trying to call default terraform registry to install providers instead of pulling it from jFrog as configured in our .terraform.rc file.

![image](https://github.com/user-attachments/assets/822c69fb-e3e3-4509-b185-3b5a11a83b13)

**Comment by levkohimins** [comment]
Hey @nuryupin-kr, thanks for the feedback. In this time, I used your example for integration test, it should work now for sure.

**Comment by nuryupin-kr** [comment]
I wonder if us setting `TF_CLI_CONFIG_FILE` env var to point to our `.terraformrc` file prior to running any Terragrunt has to do with it failing for us. As far as I understand Terragrunt should merge our `.terraformrc` with configuration of its own and then set `TF_CLI_CONFIG_FILE` to point to the new merged configuration, am I correct?

NOTE that when I remove our `.terraformrc` and not setting `TF_CLI_CONFIG_FILE`, Terragrunt is able to pull providers from default `registry.terraform.io`, but it fails to discover provider that we pre-download manually to `terrgrunt-hcl-working-dir/terraform.d/plugins/`. Seems like Terragrunt doesn't look at that location where Terraform does.

Please, let me know what other info can I provide for context to understand the problem better.

**Comment by levkohimins** [comment]
@nuryupin-kr.

> I wonder if us setting TF_CLI_CONFIG_FILE env var to point to our .terraformrc file prior to running any Terragrunt has to do with it failing for us. As far as I understand Terragrunt should merge our .terraformrc with configuration of its own and then set TF_CLI_CONFIG_FILE to point to the new merged configuration, am I correct?

Yeah, correct, this is how it works. 

> NOTE that when I remove our .terraformrc and not setting TF_CLI_CONFIG_FILE, Terragrunt is able to pull providers from default registry.terraform.io, but it fails to discover provider that we pre-download manually to terrgrunt-hcl-working-dir/terraform.d/plugins/. Seems like Terragrunt doesn't look at that location where Terraform does as part of their [implied local mirrors directories](https://developer.hashicorp.com/terraform/cli/config/config-file#implied-local-mirror-directories).

I found a bug with `include` and `exclude` directives when try to use your example, I have fixed and the release will be out soon.

> Also, since we are executing Terraform/Terragrunt exclusively in the Github Workflows, we are setting credentials to our jfrog registry using the following line in the workflow: TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}. Terraform knows how to extract the part after TF_TOKEN_ so it's authenticating us to our registry without having to run terraform login command due to the process being non-interactive. In my attempts to fix our issue I just discovered that if I supplied myorg_jfrog_io to TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES env var, I get the following error:

I can't say for sure right now. it may work, since we use http proxy and it must transmit all headers with the request. Need to check.

**Comment by levkohimins** [comment]
@nuryupin-kr, could you try [v0.63.6](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.63.6) release?

**Comment by nuryupin-kr** [comment]
@levkohimins 
Just tried it with v0.63.6
![image](https://github.com/user-attachments/assets/b90b633d-e94f-47b6-ab09-e7a2b1b6be22)

## Without `.terraformrc`:
Works for all the providers except for pre-downloaded provider. Terragrunt still attempts to look for it in the `registry.terraform.io` instead of `terrgrunt-hcl-working-dir/terraform.d/plugins/`.
![image](https://github.com/user-attachments/assets/637fc92e-eb2d-4419-b752-48536a6b8e14)

## With `.terraformrc`:
![image](https://github.com/user-attachments/assets/7b1e5302-35d9-4a8c-9363-1784017168eb)
Terragrunt still tries to pull providers from `registry.terraform.io` ignoring config from `network_mirror` block.
> I've also tried to move `.terraformrc` file to a default directory `$HOME/.terraformrc` to avoid setting `TF_CLI_CONFIG_FILE` env var. However both times got same error which means the env var is not a problem.

## With `.terraformrc` + setting `TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES=myorg.jfrog.io`:
Fails to pass through credentials from setting `TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}`
![image](https://github.com/user-attachments/assets/8b988d59-998f-460d-a9f9-8b39e1c5d6c9)
> Is there an alternative way to specify credential?


## Additional Context:
Env vars we set for terragrunt:
`TERRAGRUNT_NON_INTERACTIVE: true`
`TERRAGRUNT_INCLUDE_EXTERNAL_DEPENDENCIES: true`
`TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES=myorg.jfrog.io` - tried it on and off

for terraform:
`TF_CLI_CONFIG_FILE: path/to/our/.terraformrc`
`TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}`
`TF_IN_AUTOMATION: true` probably not needed

Full Terragrunt Command:
`terragrunt run-all plan -lock-timeout=30m -out=tf_plan --terragrunt-provider-cache`

**Comment by nuryupin-kr** [comment]
I'm going to try running with `TERRAGRUNT_LOG_LEVEL: debug` and see if I can get more specific error information

**Comment by nuryupin-kr** [comment]
Also just to make it clear - without setting `--terragrunt-provider-cache` flag, everything is working.

**Comment by nuryupin-kr** [comment]
I've also just tried to use `cat` to read `TF_CLI_CONFIG_FILE` after Terragrunt fails, but it appears that env var is not set in the next step, which is odd :/

**Comment by levkohimins** [comment]
I really cannot understand why it is not working on your environment. I tested locally three provider installing methods together and it worked as expected. Could you provide a full log with running env var `TERRAGRUNT_LOG_LEVEL=trace` as well as `.terraformrc` ?

> Fails to pass through credentials from setting TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}
Is there an alternative way to specify credential?

At the moment no, but we are implementing so that TF_TOKEN_* works

> So maybe our problem is that Terragrunt can't pick up those credentials? Also, I'm not sure if I should use TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES in our case at all since we already have it configured in our .terraformrc

Yes, you need to specify in `TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES` all the provider registry names that you cache. This is most likely the reason why network_mirror does not work, for example: 
```
--terragrunt-provider-cache-registry-names example.com --terragrunt-provider-cache-registry-names registry.opentofu.org --terragrunt-provider-cache-registry-names registry.terraform.io
```

**Comment by nuryupin-kr** [comment]
When I provide `TERRAGRUNT_PROVIDER_CACHE_REGISTRY_NAMES` for our jfrog, I get this:
![image](https://github.com/user-attachments/assets/8b988d59-998f-460d-a9f9-8b39e1c5d6c9)
Since we are running in non-interactive mode in the Github Actions pipeline, I cannot use `terraform login`. Instead, I have to use `TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}`. Is there any other way to pass in credentials so that Terragrunt can recognize it?

**Comment by levkohimins** [comment]
@nuryupin-kr,
> Since we are running in non-interactive mode in the Github Actions pipeline, I cannot use terraform login. Instead, I have to use TF_TOKEN_myorg_jfrog_io: ${{secrets.JFROG_API_KEY}}. But since it is currently not supported, is there any other way to pass in credentials so that Terragrunt can recognize it?

The current implementation of Terragrunt's provider cache does not allow to specify any credentials,  some requests it proxies, but when downloading assets it creates a request from scratch without any credentials. Please create a new issue with a request to add authentication to the Terragrunt provider cache to avoid messing up the `.terraformrc` issue with credentials.
