### ISSUE TITLE
Question about provider using locals when the local value is from SSM

### ISSUE THREAD

**Issue by SamuelMolling** [gruntwork-io/terragrunt#3322]
## Describe the bug

I have a code that works fine to apply resources. However, when it comes to destroying, it doesn't work well. The problem is that my provider is set up like this:

provider "azuread" {
client_id = local.client_id
client_secret = local.client_secret
tenant_id = local.tenant_id
}

And when I try to run a destroy using Atlantis Pipeline, it gives the following error:

│ Error: Reference to undeclared local value
│
│ on provider.tf line 5, in provider "azuread":
│ 5: tenant_id = local.tenant_id
│
│ A local value with the name "tenant_id" has not been declared.

How can I make this work? Has anyone had this issue?

## Steps To Reproduce

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
locals {
  security_account_id = "XPTO"
  client_id           = data.aws_ssm_parameter.client_id.value
  client_secret       = data.aws_ssm_parameter.client_secret.value
  tenant_id           = data.aws_ssm_parameter.tenant_id.value

  index_app_roles = length(data.azuread_service_principal.this.app_roles) - 1
}

resource "azuread_group" "this" {
  for_each         = toset(var.display_names)
  display_name     = each.value
  security_enabled = true
}

resource "azuread_app_role_assignment" "this" {
  for_each            = toset(var.display_names)
  app_role_id         = data.azuread_service_principal.this.app_roles[local.index_app_roles].id
  principal_object_id = azuread_group.this[each.key].object_id
  resource_object_id  = data.azuread_service_principal.this.object_id
}
```

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version:
- OpenTofu/Terraform version:
- Environment details (Ubuntu 20.04, Windows 10, etc.):

**Comment by yhakbar** [comment]
Hey @SamuelMolling ,

Unfortunately, this is not enough information to address your issue. I don't see any Terragrunt code, the version of Terragrunt you're using or the Terragrunt command you're running.

I'm going to close out this issue for now, but feel free to re-open the issue with this information when you have it. That will help us tackle how to help you get this working in Terragrunt.
