### ISSUE TITLE
Moving Beyond Terraform 1.5.x

### ISSUE THREAD

**Issue by nuryupin-kr** [gruntwork-io/terragrunt#3326]
### Summary

Due to the licensing change in Terraform v1.6 (MPL 2.0 to BSL), our team was hesitant to update beyond Terraform v1.5.7, since we weren't sure if Terragrunt will work with newer versions. We are finally looking to update to 1.9.x to take advantage of long awaited cross-variable validation. However, we still have a few questions:

1. Once Terregrunt supports a version of Terraform i.e. v1.9.0, is there any chance that support could be revoked?
2. Is Terragrunt planning to completely move away from Terraform to OpenTofu at some point in the future?
3. If 2 is true, will Terragrunt provide a path to switch to OpenTofu no matter what version of TF is being used?

### Motivation

n/a

### Proposal

n/a

### Technical Details

n/a

### Press Release

n/a

### Support Level

- [ ] I have Terragrunt Enterprise Support
- [ ] I am a paying Gruntwork customer

**Comment by denis256** [comment]
Hi,
Terragrunt already supports OpenTofu, I think some insights on what can happen in the future can be collected from: https://github.com/gruntwork-io/terragrunt/issues/2662

Compatibility table is also available on: https://terragrunt.gruntwork.io/docs/getting-started/supported-versions/

**Comment by nuryupin-kr** [comment]
Hi @denis256 
After reading through the linked issue and a few other Gruntwork blog articles created around the time of license change I get an impression that Terragrunt team was NOT going to support Terraform versions after 1.5.7. Yet it's not the case so far since you guys have been supporting all later versions of TF judging by the compatibility table and release notes of Terragrunt.
I guess my questions 2 and 3 still remain.

From what I understand so far - as long as we stay with Terraform versions that are already announced to be supported by Terragrunt, there will not be any issues. Is that correct?

Thank You!

**Comment by yhakbar** [comment]
Hey @nuryupin-kr ,

To answer your questions:
1. For the foreseeable future, once Terragrunt has announced official support for a version of OpenTofu/Terraform on a given version of Terragrunt, we will endeavor to maintain that support.
2. Terragrunt does not have any plans to abandon Terraform support. We make no guarantees about the compatibility of Terragrunt with BSL Terraform features, however. Take special note of `Note 1` at the bottom of the compatibility matrix linked above by @denis256 .
3. I'm not sure I understand this question. Terraform and OpenTofu are upgrading with their own version numbers, forked from the same MPL Terraform origin. If you're asking whether you'll be able to use OpenTofu with Terragrunt in the future, that is a very good bet. OpenTofu is managed by the Linux Foundation, and is committed to having it be available for public use for a very long time.

Generally speaking, Terragrunt is an orchestrator for OpenTofu/Terraform. New features in those tools are usually transparent to the experience of using Terragrunt, especially when it doesn't change the API of the binary (the arguments and flags that the binary accepts).

**Comment by nuryupin-kr** [comment]
@yhakbar I know the issue is closed, but I was curious if you could give an example of BSL feature by Terraform that already exists?

**Comment by yhakbar** [comment]
Sorry, @nuryupin-kr , I haven't really followed the project too much since they made the switch to BSL. I would look at the tag linked in the release where they announce the feature and check the LICENSE file.
