### ISSUE TITLE
Use a more permanent cache directory

### ISSUE THREAD

**Issue by kevinburke** [gruntwork-io/terragrunt#334]
Terragrunt calls `os.TempDir` to allocate a temporary directory for downloading local files. However, this is vulnerable to getting cleaned up by the operating system at any time.

The purpose of the temp dir is to operate as a local cache and speed up operations.

A directory like `$HOME/Library/Caches` (on Mac), `$XDG_CACHE_HOME/terragrunt` (if specified), or `$HOME/.terragrunt` may be more appropriate, and less vulnerable to getting cleaned up.

In addition, Terragrunt cannot detect if the cache is corrupt. It would be good to check whether the cache is corrupt and trigger a remove/redownload, or at the very least report a helpful error, instead of exiting with an unhelpful error.

**Comment by brikis98** [comment]
This is a great idea!
