### ISSUE TITLE
The terragrunt-fetch-dependency-output-from-state flag does not work with dependencies that were not yet applied

### ISSUE THREAD

**Issue by rodrigorfk** [gruntwork-io/terragrunt#3349]
## Describe the bug

If you enable the `--terragrunt-fetch-dependency-output-from-state` feature flag and runs a `terragrunt init` on a module that depends on a `dependency` that was not yet applied, terragrunt will fail with the error below, even if you are using `mock_outputs`:

```
time=2024-08-19T06:40:37Z level=error msg=NoSuchKey: The specified key does not exist.
	status code: 404, request id: R3RDR225V4A0512Z, host id: M+UdBiL0noKh/gVht5UpFyKkvY/Sh1tXlX/yIZ9qXabDNCA7ovrKkT35o7biYWUhksJSHaArhgg=
````

![image](https://github.com/user-attachments/assets/750b0689-10a4-4109-af6c-c06ccdd6674f)

## Steps To Reproduce

You can actually reproduce it from the `TestTerragruntOutputFromRemoteState` integration test here:
https://github.com/gruntwork-io/terragrunt/blob/9accf247dba7b380a69fcc482994f06844441da4/test/integration_test.go#L5299

If you try to run `terragrunt init` in the `app2` folder, without having applied `app1` or `app3` before, terragrunt will fail with the error above.

## Expected behavior

The `--terragrunt-fetch-dependency-output-from-state` feature flag should provide feature parity as the "native" terraform output behaviour, and fallback to mock outputs if the dependency was not applied yet.

## Nice to haves

- [x] Terminal output
- [x] Screenshots

## Versions

- Terragrunt version: v0.66.8
- OpenTofu/Terraform version: tf 1.5.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Mac 14.5

**Comment by yhakbar** [comment]
Thanks for being so thorough, @rodrigorfk . 

Creating the issue, showing how to reproduce and adding the PR to address it really goes a long way towards getting this fixed faster.
