### ISSUE TITLE
'usgovernment' is misspelled in the following error: Error: unable to locate metadata for environment "badinput" from the built in `public`, `usgoverment`, `china` and no custom metadata host has been specified 

### ISSUE THREAD

**Issue by manwithaplandy** [gruntwork-io/terragrunt#3356]
## Describe the bug

In a remote_state block for an azurerm backend, one of the options is to specify an environment. The options for environment are china, usgovernment, and public. When a string that doesn't match one of those is entered, it produces the following error:

```Error: unable to locate metadata for environment "badinput" from the built in `public`, `usgoverment`, `china` and no custom metadata host has been specified```

In the above error, 'usgoverment' is misspelled, which may confuse users trying to troubleshoot issues with their environment.

## Steps To Reproduce

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
remote_state {
  backend = "azurerm"
  config = {
    resource_group_name   = "my-resource-group"
    storage_account_name  = "mystorageaccount"
    container_name        = "tfstate"
    key                   = "${path_relative_to_include()}/terraform.tfstate"

    # Here is the option in question
    environment           = "badinput"   # or another Azure cloud environment
  }
}
```

## Expected behavior

The error message should read as follows:
```Error: unable to locate metadata for environment "badinput" from the built in `public`, `usgovernment`, `china` and no custom metadata host has been specified```

## Nice to haves

- [ ] Terminal output
- [x] Screenshots

## Versions

- Terragrunt version: 0.66.9
- OpenTofu/Terraform version: Terraform 1.9.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Ubuntu 20.04 on WSL on Windows 11

## Additional context

![Screenshot of terminal error](https://github.com/user-attachments/assets/e9c69f8c-27b4-469e-b2bf-e205bbdaa137)

Thanks for all the awesome work you guys do

**Comment by manwithaplandy** [comment]
So it is. I will have to open a PR there. Thanks!

**Comment by denis256** [comment]
Proposed fix in:
https://github.com/hashicorp/go-azure-helpers/pull/241

Once it will be merged, will update the dependencies
