### ISSUE TITLE
Directly Forward Logs for `state` commands

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#3377]
Take note of the following issue:

              This is quite the change, is there no way to make it an env var so it can be disabled across all terragrunt commands instead of one every command?

The following no longer works - `terragrunt state pull > state.json` as the log is not valid json.

On top of that now my terminal is full of `14:30:56.137 STDOUT terraform: ` which really adds very little.

_Originally posted by @tide-jamiegwatkin in https://github.com/gruntwork-io/terragrunt/issues/3367#issuecomment-2326538645_

`terragrunt state` commands should directly forward their stdout, just like `terragrunt output`.

**Comment by levkohimins** [comment]
Resolved in [v0.67.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.5) release.
