### ISSUE TITLE
Some Terraform errors are not  displayed when running `terragrunt plan`

### ISSUE THREAD

**Issue by HenriBlacksmith** [gruntwork-io/terragrunt#3382]
## Describe the bug

When running `terragrunt plan` and having authentication errors, the errors returned by Terraform are not displayed in Terragrunt output.

## Steps To Reproduce

I used the following piece of code to compare Terragrunt and Terraform errors with my code:

```shell
terragrunt plan --terragrunt-log-level debug --terragrunt-debug || true
cd ${TERRAGRUNT_WORKING_DIR}/.terragrunt-cache
cd $(ls -d ./* | head -n 1)
cd $(ls -d ./* | head -n 1)
terraform plan
```

Terragrunt output:

```
11:06:25.132 STDOUT terraform: Planning failed. Terraform encountered an error while generating this plan.
11:06:25.132 STDOUT terraform: 
11:06:25.249 ERROR  terraform invocation failed in {REDACTED}/.terragrunt-cache/{REDACTED} error=[/builds/{REDACTED}/.terragrunt-cache/{REDACTED}] exit status 1
11:06:25.250 ERROR  1 error occurred:
	* [{REDACTED}/.terragrunt-cache/{REDACTED}] exit status 1
```

Terraform output:

```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: building client: unable to obtain access token: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700213: No matching federated identity record found for presented assertion subject 'project_path:{REDACTED}'. Please note that the matching is done using a case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://learn.microsoft.com/entra/workload-id/workload-identity-federation {REDACTED}}
│ 
│   with provider["registry.terraform.io/hashicorp/azuread"],
│   on providers.tf line 1, in provider "azuread":
│    1: provider "azuread" {
│ 
╵
╷
│ Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700213: No matching federated identity record found for presented assertion subject 'project_path:{REDACTED}'. Please note that the matching is done using a case-sensitive comparison. Check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://learn.microsoft.com/entra/workload-id/workload-identity-federation {REDACTED}"}
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 5, in provider "azurerm":
│    5: provider "azurerm" {
│ 
╵
```

## Expected behavior

The full Terraform output must be present in Terragrunt output

## Nice to haves

- [ ] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: 0.67.1
- OpenTofu/Terraform version: Terraform 1.9.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Docker image alpine/terragrunt:1.9.5, see: https://hub.docker.com/layers/alpine/terragrunt/1.9.5/images/sha256-41a36dac2c44083a6c594caad48834e44880c4c11c2f5e5a9ce1d51556683cf3?context=explore

**Comment by HenriBlacksmith** [comment]
A quick update, it looks to be specific to some errors (maybe it is due to the format or it is because is is an error happening during provider authentication)

**Comment by ohmer** [comment]
Looks like a duplicate of #3376.

**Comment by HenriBlacksmith** [comment]
> Looks like a duplicate of #3376. 

Looks similar yes, though I do not have the broken pipe message (I also saw it in other cases).

**Comment by DmytroRomantsovM** [comment]
Experience the same issue (the error message not being printed) during the usage of [`postconditions` on data sources](https://developer.hashicorp.com/terraform/language/v1.5.x/expressions/custom-conditions#error-messages). The error is specified in the `error_message` field, but is not printed.

**Comment by yhakbar** [comment]
Do you have a way to reproduce this issue?
