### ISSUE TITLE
Directly Forward Logs for `version` command

### ISSUE THREAD

**Issue by yhakbar** [gruntwork-io/terragrunt#3390]
## Describe the bug

Automatically enable `terragrunt-forward-tf-stdout` for `version` command.

Users might programmatically parse the output of the command, and it's not super helpful here.

## Steps To Reproduce

Run `terragrunt version`:

```bash
$ terragrunt version 2>/dev/null
16:54:03.619 STDOUT tofu: OpenTofu v1.6.2
16:54:03.619 STDOUT tofu: on darwin_arm64
16:54:03.619 STDOUT tofu: + provider registry.opentofu.org/hashicorp/aws v5.57.0
16:54:03.619 STDOUT tofu: + provider registry.opentofu.org/hashicorp/helm v2.5.1
16:54:03.619 STDOUT tofu: + provider registry.opentofu.org/hashicorp/tls v4.0.5
```

## Expected behavior

Log enrichment doesn't happen for the `version` command, just like it doesn't for the `output` command.

## Nice to haves

- [x] Terminal output
- [ ] Screenshots

## Versions

- Terragrunt version: v0.67.3
- OpenTofu version: v1.6.2
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS 14.5

**Comment by levkohimins** [comment]
Resolved in [v0.67.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.5) release.
