### ISSUE TITLE
Unable to download terraform modules from Jfrog artifactory private registry using tfr or https

### ISSUE THREAD

**Issue by nveeramn** [gruntwork-io/terragrunt#3403]
## Describe the bug

Terragrunt fails to download a Terraform module from a JFrog Artifactory private registry, resulting in an HTTP error. The error occurs when attempting to download the module using the tfr:// or https protocol

## Steps To Reproduce

```hcl
terraform {
  source = "tfr://<your_artifactory_domain>/artifactory/aws/mymod?version=1.0.0"
}
```
```INFO[0000] Downloading Terraform configurations from tfr://<your_artifactory_domain>/artifactory/aws/mymod?version=1.0.0
ERRO[0000] downloading source url tfr://<your_artifactory_domain>/artifactory/aws/mymod?version=1.0.0
1 error occurred:
* error downloading 'tfr://<your_artifactory_domain>/artifactory/aws/mymod?version=1.0.0': Error downloading module from https://<your_artifactory_domain>/artifactory/api/terraform/v1/modules/artifactory/aws/mymod/1.0.0/download: error receiving HTTP data
```

also tried using https but doesnt seem to like the credentials and throws 401 error

```hcl
terraform {
  source = "https://<your_artifactory_domain>/artifactory/aws/mymod?version=1.0.0"
}
```
Seeing 401 error. Tried setting up `TG_TF_REGISTRY_TOKEN` but couldnt find any luck, also made sure that the same creds works with curl

## Expected behavior

Terragrunt should successfully download the specified module from the Artifactory registry without encountering HTTP errors.

**Comment by aron-muon** [comment]
this can be done right now with both protocols -

The easiest way:
(This should use your credentials from `terraform login <ARTIFACTORY_HOST>`)
```hcl
terraform {
  source  = "https://<ARTIFACTORY_HOST>/artifactory/<TERRAFORM_REPO>/<NAMESPACE>/<MODULE>/<PROVIDER>/<VERSION>.zip"
}
```

The slightly harder way:
(This requires setting the variables)
```
TG_TF_DEFAULT_REGISTRY_HOST=<ARTIFACTORY_HOST> \
TG_TF_REGISTRY_TOKEN=<TOKEN> \
terragrunt init
```
```hcl
terraform {
  source  = "tfr:///<TERRAFORM_REPO>__<NAMESPACE>/<MODULE>/<PROVIDER>?version=<VERSION>"
}
```

**Comment by aron-muon** [comment]
Please advise that this showcases a real issue - where when using the `tfr` protocol, I expect my Terraform credentials at `~/.terraform.d/credentials.tfrc.json` to be used, or my `TF_TOKEN_app_terraform_com=` to be used.

**Comment by aron-muon** [comment]
looks like https://github.com/gruntwork-io/terragrunt/issues/1771#issuecomment-2964364580

solves this now, version [v0.81.5](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.81.5) lets us rely on `terraform login` commands to access private Artifactory registries!
