### ISSUE TITLE
forward terraform graph command

### ISSUE THREAD

**Issue by m-ronchi** [gruntwork-io/terragrunt#3404]
## Describe the bug

`terraform graph` is a command for showing dependencies between resources

`terragrunt graph` is a different command

there is no way (or docs are incomplete) to make terragrunt forward the graph command to terraform

## Steps To Reproduce

`terragrunt ??? graph`

## Expected behavior

terragrunt runs the `terraform graph` command

**Comment by denis256** [comment]
I think this one will be fixed with CLI interface redesign

**Comment by yhakbar** [comment]
For context, @m-ronchi , we have an interface redesign that is currently in internal review. Once we finish with that review, I'll be publishing it as a public RFC for community feedback. It will directly address this issue.

If you're looking for a workaround in the short-term, navigate to the relevant `.terragrunt-cache/x/y` directory that's created when you run `terragrunt init`, and use `tofu`/`terraform` graph there.

**Comment by yhakbar** [comment]
@m-ronchi , please take a look at #3445 , and see if that provides the type of user experience with Terragrunt that would have mitigated this issue, in your opinion.

**Comment by yhakbar** [comment]
Closing issue, as it will be addressed indirectly as part of the CLI Redesign, and there's a workaround for now.
