### ISSUE TITLE
handle empty string env vars more gracefully

### ISSUE THREAD

**Issue by wyardley** [gruntwork-io/terragrunt#3407]
## Describe the bug
When certain environment variables are set to an empty string (or something that's not parseable as a boolean), Terragrunt raises a message about `strconv.ParseBool` failing.

## Steps To Reproduce
1. Set `TERRAGRUNT_FORWARD_TF_STDOUT=""` or `TERRAGRUNT_DISABLE_LOG_FORMATTING=""`
1. Run any terragrunt command

## Expected behavior
Terragrunt either considers empty string the same as unset, or considers the variable set. IMO the former is more intuitive, but I can understand why Gruntworks might not like to do it that way; it seems also valid to only allow "true"  / "false" etc, just maybe should throw a more user-friendly error message, like
```
Invalid value for TERRAGRUNT_DISABLE_LOG_FORMATTING; must be one of true / false.
```

## Nice to haves
- [x] Terminal output
```shell
% export TERRAGRUNT_FORWARD_TF_STDOUT=""
% tg plan                               
11:39:22.441 ERROR  error parse: strconv.ParseBool: parsing "": invalid syntax
11:39:22.441 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
% export TERRAGRUNT_DISABLE_LOG_FORMATTING=oogabooga
% tg plan                                           
11:42:36.429 ERROR  error parse: strconv.ParseBool: parsing "oogabooga": invalid syntax
11:42:36.429 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

## Versions

- Terragrunt version: `terragrunt version 0.67.5`
- OpenTofu/Terraform version: `OpenTofu v1.8.2`
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS

## Additional context
Unsetting the var completely does resolve the issue
#3367

**Comment by levkohimins** [comment]
@wyardley, Thanks. Resolved in the [v0.67.8](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.8) release.
