### ISSUE TITLE
--terragrunt-log-disable hides terraform errors

### ISSUE THREAD

**Issue by grimm26** [gruntwork-io/terragrunt#3410]
## Describe the bug

Using `--terragrunt-log-disable` to attempt to make terragrunt output look like pre 0.67.0, I find that it eats terraform errors.

## Steps To Reproduce

Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```hcl
❯ tf planm
Terraform has no command named "planm". Did you mean "plan"?

To see all of Terraform's top-level commands, run:
  terraform -help

❯ tf plan -foo
╷
│ Error: Failed to parse command-line flags
│ 
│ flag provided but not defined: -foo
╵

For more help on using this command, run:
  terraform plan -help
❯ tg planm
16:40:54.882 ERROR  Terraform has no command named "planm". To see all of Terraform's top-level commands, run: terraform -help
16:40:54.882 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
❯ tg planm --terragrunt-log-disable
❯ tg planm -foo
16:41:12.001 ERROR  Terraform has no command named "planm". To see all of Terraform's top-level commands, run: terraform -help
16:41:12.001 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
❯ tg planm -foo --terragrunt-log-disable
  /tmp/mk
```

## Expected behavior

Don't eat terraform errors.

## Versions

- Terragrunt version: 0.67.6
- OpenTofu/Terraform version: 1.9.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): Mint 22

**Comment by yhakbar** [comment]
@grimm26 ,

I can see where the confusion is coming from, but you're not actually seeing a Terraform error there. You're seeing a Terragrunt error that prevents you from incorrectly running `tofu`/`terraform` commands that don't exist:

https://github.com/gruntwork-io/terragrunt/blob/db3e671c82265557df0b7f7cd56b4b800ae9dd8f/cli/commands/terraform/command.go#L38

If you want to verify that, you can turn off that protection:

```bash
$ terragrunt --terragrunt-disable-command-validation --terragrunt-log-disable planm
OpenTofu has no command named "planm". Did you mean "plan"?

To see all of OpenTofu's top-level commands, run:
  tofu -help
```

```bash
$ terragrunt --terragrunt-disable-command-validation --terragrunt-log-disable plan -foo

Initializing the backend...

Initializing provider plugins...

OpenTofu has been successfully initialized!

You may now begin working with OpenTofu. Try running "tofu plan" to see
any changes that are required for your infrastructure. All OpenTofu commands
should now work.

If you ever set or change modules or backend configuration for OpenTofu,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Failed to parse command-line flags
│
│ flag provided but not defined: -foo
╵

For more help on using this command, run:
  tofu plan -help
```

**Comment by bernard-drb** [comment]
> I see, but I find it very counterintuitive how much trouble it is to just maintain the pre 0.67.0 output format.

I was wondering the same thing and discovered that there is a way:

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-format

setting this to `bare`

**Comment by bernecg** [comment]
@grimm26 

I was wondering the same thing and discovered that there is a way:

https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-format

setting this to `bare`
