### ISSUE TITLE
Terragrunt keeps adding latest version of of provider from opentofu registry and ignore terraform version constraint

### ISSUE THREAD

**Issue by nguyen-vo** [gruntwork-io/terragrunt#3437]
## Describe the bug

I have my repository set up to support multiple environments using multiple folder and have a single terragrunt.hcl file at the root level. In that file I define the provider constraint to be `~>5.28` using the required_provider block from terraform.
```
generate "provider" {
  path      = "provider_override.tf"
  if_exists = "overwrite_terragrunt"
  
  contents  = <<EOF
    terraform {
      required_providers {
        google = {
          source  = "hashicorp/google"
          version = "~>5.28"
        }
      }
    }
    provider "google" {
      project = "${local.project_id}"
      region  = "${local.region_location}"
    }
  EOF
}
```
Upon running plan command locally, I notice the .terraform.lock.hcl keep getting updates with with the latest version of the provider from opentofu. I got to learn that terragrunt use opentofu as default if it is available. However, I don't have opentofu installed on my machine. I also set the TERRAGRUNT_TFPATH to point to terraform, but no luck

Here is an example of my lock file
![code](https://github.com/user-attachments/assets/2fa0a7a1-077f-4810-8e7d-2f4bf50e63e6)

## Expected behavior
- Expect the lock file to only contains provider from terraform
- OR the opentofu version must follow the terraform constraints 

## Nice to haves

- [x] Terminal output from plan command
```
terragrunt run-all plan --terragrunt-working-dir infrastructures/eu/acc/org-common/cloud-run-service/automated-test-controller
eu-north
Module:                  /Users/nguyenvo/Desktop/Randstad/DigitalGlue-squad3/transcoder-shared-infrastructures/infrastructures/eu/acc/org-common/cloud-run-service/automated-test-controller
External dependency:     /Users/nguyenvo/Desktop/Randstad/DigitalGlue-squad3/transcoder-shared-infrastructures/infrastructures/eu/acc/org-common/service-accounts
Should Terragrunt apply the external dependency? (y/n) n
INFO[0002] The stack at infrastructures/eu/acc/org-common/cloud-run-service/automated-test-controller will be processed in the following order for command plan:
Group 1
- Module /Users/nguyenvo/Desktop/Randstad/DigitalGlue-squad3/transcoder-shared-infrastructures/infrastructures/eu/acc/org-common/cloud-run-service/automated-test-controller
 

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of registry.opentofu.org/hashicorp/google from the dependency lock file
- Reusing previous version of registry.opentofu.org/hashicorp/google-beta from the dependency lock file
- Reusing previous version of hashicorp/google from the dependency lock file
- Reusing previous version of hashicorp/google-beta from the dependency lock file
- Using previously-installed registry.opentofu.org/hashicorp/google v6.4.0
- Using previously-installed registry.opentofu.org/hashicorp/google-beta v6.4.0
- Using previously-installed hashicorp/google v5.44.1
- Using previously-installed hashicorp/google-beta v6.4.0

Terraform has been successfully initialized!
```

## Versions

- Terragrunt version: 0.55.3
- Terraform version:
- Environment details (Ubuntu 20.04, Windows 10, etc.): Mac Montery v12.6.4

**Comment by nguyen-vo** [comment]
Maybe this is not the bug. What I am trying to do is to get opentofu to align with the version constraint. It keeps download the latest version of opentofu which sometimes causes our CI pipeline to fail

**Comment by nguyen-vo** [comment]
I figured out the issue. Someone from our team has opentofu set up and by default Terragrunt uses opentofu. When they run plan command, it updates the state with opentofu provider. This causes the subsequence runs to use opentofu

To address this issue I did the following

```bash
# I am using google but your can change it to your prefer prover
terragrunt replace-provider 'registry.opentofu.org/hashicorp/google' 'registry.terraform.io/hashicorp/google' --terragrunt-working-dir path/to/the/target/folder
# answer yes when prompted
# after the provider is updated in the TF state, reinit the state
terragrunt init --terragrunt-working-dir path/to/the/target/folder
# your lock file should be update 
```

**Comment by 0xdnL** [comment]
This happened to me, I was the one that hat accidentally used opentofu and applied it to state.

For future reference, if you have `tofu` next to `terraform` on your system you need to specify `terreform` explicitly via [terragrunt-tfpath](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-tfpath )

You can also set this dynamically in `terragrunt.hcl`

```hlc
terraform_binary = run_cmd("which", "terraform")
```
