### ISSUE TITLE
Can't run `console` command in non-interactive mode

### ISSUE THREAD

**Issue by loganmauzaize-finalcad** [gruntwork-io/terragrunt#3450]
## Describe the bug

When running `console` command by with here-string `<<<"..."`  or piping, I got:

```plain
20:27:38.823 ERROR  terraform invocation failed in ../../../../../../../../.terragrunt/cache/Leqa2IMQH6ppKA2AettZV71a2v8/59DgVZSVN8iHBz2IdPQ6vpph3YU/demo
20:27:38.823 ERROR  error resizing pty: inappropriate ioctl for device
20:27:38.823 ERROR  1 error occurred:
        * inappropriate ioctl for device


20:27:38.823 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

## Steps To Reproduce

```shell
echo 'local.application' | terragrunt console
```

```shell
terragrunt console <<<'local.application'
```

## Expected behavior

Run Terraform command successfully.

## Nice to haves

- [ ] Terminal output

```plain
20:27:38.823 ERROR  terraform invocation failed in ../../../../../../../../.terragrunt/cache/Leqa2IMQH6ppKA2AettZV71a2v8/59DgVZSVN8iHBz2IdPQ6vpph3YU/demo
20:27:38.823 ERROR  error resizing pty: inappropriate ioctl for device
20:27:38.823 ERROR  1 error occurred:
        * inappropriate ioctl for device


20:27:38.823 ERROR  Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

- [ ] Screenshots

## Versions

- Terragrunt version:
   - `0.52.0` (our current version)
   - `0.67.15` (current version)
- OpenTofu/Terraform version: `1.5.7`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `WSL Ubuntu 22.04`

## Additional context

Any way to just disable pty/tty support?

**Comment by denis256** [comment]
Hi,
Does the same issue occur when `--terragrunt-non-interactive` is added?

```
echo 'local.application' | terragrunt console --terragrunt-non-interactive
```

**Comment by loganmauzaize-finalcad** [comment]
> Does the same issue occur when --terragrunt-non-interactive is added?

Tested with both `0.52.0` and `0.67.15`, same result

**Comment by denis256** [comment]
Added fix for this in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.67.16

**Comment by loganmauzaize-finalcad** [comment]
Thanks, I will give it a try in coming hours :)

**Comment by loganmauzaize-finalcad** [comment]
It works! Thank you very much for reactivity.
