### ISSUE TITLE
Support for Terraform `import` blocks

### ISSUE THREAD

**Issue by olivermeyer** [gruntwork-io/terragrunt#3477]
## Describe the enhancement

Terraform supports `import` blocks as a way of importing existing resources into the state without running commands manually. For example, the following block will import the EC2 instance with id `i-abcd1234` to `aws_instance.example` in the state:
```
import {
  to = aws_instance.example
  id = "i-abcd1234"
}
```
For further details, see the Terraform [docs](https://developer.hashicorp.com/terraform/language/v1.10.x/import).

It would be great if Terragrunt supported these blocks, since running import commands manually is inherently risky.

Note that this is different from the Terragrunt `import` blocks described [here](https://terragrunt.gruntwork.io/docs/rfc/imports/#import-block-hierarchical-variables-included-across-multiple-terragrunthcl-files).

## Additional context

Alternatives: run the import commands manually

**Comment by yhakbar** [comment]
Hey @olivermeyer ,

It supports it today! Terragrunt will respect any `.tf` files placed next to a `terragrunt.hcl` file, so if you want to use the same syntax to import resources, you can just place the HCL `import` block you referenced above in an `imports.tf` file right next to your `terragrunt.hcl`.

**Comment by olivermeyer** [comment]
> Hey @olivermeyer ,
> 
> It supports it today! Terragrunt will respect any `.tf` files placed next to a `terragrunt.hcl` file, so if you want to use the same syntax to import resources, you can just place the HCL `import` block you referenced above in an `imports.tf` file right next to your `terragrunt.hcl`.

Hi @yhakbar, thanks for the quick reply and apologies from my side - for some reason I couldn't get it to work and since I couldn't find it mentioned in the documentation, I assumed it wasn't supported. I'll take another shot at it :-)
