### ISSUE TITLE
Init root configuration even if it doesn't contains source

### ISSUE THREAD

**Issue by loganmzz** [gruntwork-io/terragrunt#3482]
## Describe the bug

Root module is generally used as include and don't contains source to refer to a Terraform module/project. As stated in documentation for example: https://terragrunt.gruntwork.io/docs/features/keep-your-terragrunt-architecture-dry/#keep-your-terragrunt-architecture-dry.

And no Terraform command is supposed to be executed against it as it don't refer to any Terraform module/project.

## Steps To Reproduce

1. Create a Terragrunt root module (defining backend, providers, generates, etc.)
2. Execute `terragrunt init` from root

Files are generated and backend is initialized!

Same with `run-all` which includes the root Terragrunt configuration!

## Expected behavior

Running non-`run-all` commands should end in error like if it were no Terragrunt configuration or more specific error due to lack of Terraform module/project to run.

Running `run-all` commands should just ignore root Terragrunt configuration.

## Nice to haves

N/A

## Versions

- Terragrunt version: `0.68.1`
- OpenTofu/Terraform version: `1.9.7`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `WSL2 - Ubuntu 22.04`

## Additional context

Only tested `init` command. Shoud check behavior with other ones.

**Comment by denis256** [comment]
Hi,
=
Yes, running `terragrunt init` will attempt to use the `terragrunt.hcl` from the current directory, as there are cases where users may run Terragrunt directly from the working directory.

Regarding the case with `run-all`, it's unclear how this is being invoked. Typically, Terragrunt doesn't operate from a parent directory unless it contains `.tf` files or a defined `terraform` block. Providing an example repository could be helpful to better diagnose this scenario.


I've created a simplified example in https://github.com/denis256/terragrunt-tests/tree/master/issue-3482, which demonstrates that the generate command only executes in child directories:

```
$ terragrunt run-all apply
14:31:42.029 INFO   The stack at . will be processed in the following order for command apply:
Group 1
- Module ./prod
- Module ./qa
- Module ./stage

...

$ find . -name "example_backend.txt"
./prod/example_backend.txt
./qa/example_backend.txt
./stage/example_backend.txt
```

**Comment by loganmzz** [comment]
I will try it again but may be first "feature" has caused the second issue:

1. I may have accidently run non-`run-all` command from stack root, which has generated some TF files (as requested by root Terragrunt configuration)
2. Then, as there are TF files, Terragrunt have included the root

**Comment by loganmzz** [comment]
@denis256 Yeps I confirm the scenario.

Is there any way to prevent execution of root?

**Comment by yhakbar** [comment]
@loganmzz , take a look at [terragrunt-exclude-dir](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-exclude-dir).

**Comment by loganmzz** [comment]
@yhakbar this is not part of Terragrunt configuration file. I would like to prevent root configuration being executed as a standalone, while it is just an empty shell / template.

**Comment by yhakbar** [comment]
@loganmzz , If you want to make it so that the root configuration file is ignored by `run-all` commands without changing how you invoke Terragrunt, you can just call it something other than `terragrunt.hcl`.

e.g. `root-terragrunt.hcl`

Just make sure you also update your `include`s accordingly.

e.g.

```hcl
include "root" {
  path   = find_in_parent_folders("root-terragrunt.hcl")
  expose = true
}
```

**Comment by loganmzz** [comment]
@yhakbar Thank you! A lot to edit but search+replace is your (my) best friend :)
