### ISSUE TITLE
Terraform/Tofu output buffered with `run-all --terragrunt-forward-tf-stdout`

### ISSUE THREAD

**Issue by mhulscher** [gruntwork-io/terragrunt#3499]
## Describe the bug

Running `run-all` with `--terragrunt-forward-tf-stdout` no longer streams terraform/tofu output. Instead, it seems that all output is buffered and only printed after the command finishes.

## Steps To Reproduce

Something like `terragrunt run-all init -upgrade --terragrunt-forward-tf-stdout` already reproduces this.

## Versions

- Terragrunt version: `0.68.4`
- OpenTofu/Terraform version: `OpenTofu v1.8.3`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `Ubuntu`

## Additional context

N/A

**Comment by yhakbar** [comment]
This is not a bug, but intended behavior.

Without buffering, users can't really understand what's happening in different units when they `run-all`.

**Comment by Dakumo** [comment]
for me that is still a valid request... 
we have long running terragrunt / terraform pipelines... 
max runtime about 30 minutes... 
if I don't see any output I consider them to be broken...
