### ISSUE TITLE
terragrunt should create s3 bucket, if it is not present

### ISSUE THREAD

**Issue by antonbabenko** [gruntwork-io/terragrunt#35]
Similar to how it verifies existence of dynamodb lock table and create it if it does not exist.

I think it should create versioned S3 bucket (default, `acl=private`) when `remote_state` section is defined.

**Comment by brikis98** [comment]
We discussed this before and the only reason we didn't do it is that S3 is only one of the remote state backends supported. We may have to think through what to do for the [other types of backends](https://www.terraform.io/docs/state/remote/index.html), such consul, google cloud storage, etcd, and so on. 

That said, I think we could implement these on a one-by-one basis, so I'd gladly welcome a PR that created the S3 bucket automatically with versioning and proper ACLs.
