### ISSUE TITLE
Multiple terraform modules in terragrunt configuration

### ISSUE THREAD

**Issue by ramakanta89** [gruntwork-io/terragrunt#350]
Is there a way to use multiple modules from git inside terragrunt configuration i.e in terraform.tfvars file. This is a single template for my use case as below.

terragrunt = {
  terraform {
    source= "git::/link/to/repo/vpc.git"
    source= "git::/link/to/repo/subnet.git"
  }
}

**Comment by brikis98** [comment]
No, not really. Your best bet is to create a module that uses `vpc` and `subnet` under the hood and use Terragrunt with that. See #343 for more discussion.
