### ISSUE TITLE
How can i know the path to the temporary folder ?

### ISSUE THREAD

**Issue by ofer-velich** [gruntwork-io/terragrunt#352]
When i run terraform all modules are been downloaded in to a temporary folder,
How can i know the path to the temporary folder that the source module will be download to ? 
Or control it using the cli ?

Thanks

**Comment by brikis98** [comment]
Why do you need to know it? That is, what is your use case?

Depending on what you're doing, one of the [interpolation functions](https://github.com/gruntwork-io/terragrunt#interpolation-syntax) may be what you need.

**Comment by ofer-velich** [comment]
i wish to render .jinja terraform templates in the temporary folder,  after the init phase
but actually i found that if i work with a local modules repository, and  I render the .jinja files in the temporary folder (after the init phase), issuing "terrgrunt plan" will fail and ask me to re run init
so i kind of stuck :)

**Comment by brikis98** [comment]
Ah, I see. 

There isn't really support for anything like that at the moment. I'm open to ideas tough.

**Comment by tomdavidson** [comment]
If the temp dir is a known and fixed location could it be a security vulnerability -Especially for those using shared ci runners and laptops. I would like to know I can attempt to clean up after the CI job.

FYI http://www.linuxsecurity.com/content/view/115462/151/

**Comment by conorgil** [comment]
I have been working with terragrunt for a while now and find that I often jump into the temp directory while debugging more complex setups. I can see exactly which files are in there, manually run terraform if trying to determine whether a bug is in terragrunt or terraform, etc.

I currently copy/paste the temp dir from the terragrunt stdout logs.

It is an edge case and just for convenience, but would be helpful to have a command like `terragrunt --terragrunt-tmp-dir`, which just outputs the path to the temp dir and nothing else.

If we like this idea, then I propose updating the labels on this issue to indicate a feature request and help wanted.

**Comment by brikis98** [comment]
The download dir is already configurable:

```
   terragrunt-download-dir                  The path where to download Terraform code. Default is .terragrunt-cache in the working directory.
```

However, the path within the download dir is not. A PR to make that configurable is probably OK, though it depends how much complexity it adds to the code...

**Comment by conorgil** [comment]
I was thinking that `--terragrunt-tmp-dir` would output the entire path to the download dir, including the `--terragrunt-download-dir` and the path within the download dir. That way, for testing I can easily do
```
$> cd $(terragrunt --terragrunt-tmp-dir)
$> ... other stuff ...
```

Also, another use-case that I just thought of for why this is useful is testing `before_hook` and `after_hook`. I might want to just pop into that directory and manually run a script called by an `after_hook` to see what silly thing I am doing wrong that makes it fail when called from terragrunt without waiting for everything else that terragrunt does when executed. It is an edge case, but I have done it before and it was useful.

**Comment by brikis98** [comment]
Would https://github.com/gruntwork-io/terragrunt/pull/586 solve some of these use cases?

**Comment by conorgil** [comment]
@brikis98 yup, that would be great. I left comments in #586, so I'll close this out.

**Comment by brikis98** [comment]
Please give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.18.5 a shot!
