### ISSUE TITLE
Expose CheckDependentModules as configurable flag / Destroy in big repos takes a very long time

### ISSUE THREAD

**Issue by kbcz1989** [gruntwork-io/terragrunt#3526]
## Describe the enhancement

CheckDependentModules should be configurable.

## Additional context

Destroy in some cases, like in big repositories, takes a very long time, even an hour or more, where it previously ran in a minute. Often there is no reason to check for dependent modules so this should be at least configurable, if it's true by default.

I don't think there would be any negative implications with this change, as if not explicitly set, the behavior would remain the same as it is now.

It started with version #299, v0.33.0 and introduction of CheckDependentModules.
Workaroud since then was to run `terragrunt apply -destroy` instead of `terragrunt destroy`.

Since #3011, v0.56.5, the only remaining workaround, afaik is `terragrunt plan -destroy -out outfile`.

Regarding level of effort, it's probably low.

- [x] Changes required.
- [x] Implications of the feature.
- [x] Alternatives considered.
- [x] Level of effort.

## RFC Not Needed

- [x] I have evaluated the complexity of this enhancement, and I believe it does not require an RFC.

**Comment by yhakbar** [comment]
Released in [v0.68.8](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.68.8)
