### ISSUE TITLE
order of 'all' cmds?

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#353]
Hello, does the all cmds such as apply-all process found plans in the alpha numerical order?

**Comment by josh-padnick** [comment]
No, Terragrunt looks for a `dependencies` property in your `terraform.tfvars` file that explicitly declares a given Terraform Configuration's dependencies. See more info in the [docs](https://github.com/gruntwork-io/terragrunt#dependencies-between-modules).

**Comment by tomdavidson** [comment]
Thank you for the quick response. Im aware of the dependency feature (very nice) but this question is about peers and not dependencies.

What is the order of processing if I have 10 plans that do not depend on each other?

**Comment by josh-padnick** [comment]
Ah, thanks for the clarification. In that case, any "peers" or modules that don't depend on each other will execute in parallel!

**Comment by tomdavidson** [comment]
Great, thank you.
