### ISSUE TITLE
cache and ci

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#354]
I am implementing terragrunt for ci (after wasting a bunch of time not using it :D ) and could use a clarification on caching.  Does terragrunt use terraform's plugin cache? If not, can I pass my prime the cache bash script through terragrunt to seed  terragrunt's cache?

```yml
    - "~/.terraform.d/plugin-cache"
    - "~/.terragrunt"
```

**Comment by josh-padnick** [comment]
I'm not sure I understood the last part of your question, but to answer the first part, Terragrunt performs all its major operations by making a Terraform command. If you look carefully in the Terragrunt log output, you'll see the specific Terraform commands being run.

For the cache in particular, Terraform gets with either the `terraform init` or `terraform get` commands. Terragrunt calls `terraform init` as part of its initial run. 

Terragrunt works by first copying the Terraform module specified in the `source` property of the `terraform.tfvars` file to a tmp folder and then copies the `terraform.tfvars` file to that same tmp folder. Then, from that folder, it runs all the Terraform commands. Therefore, subsequent runs of Terragrunt will rely on the Terraform cache stored in the tmp folder. 

If you ever wanted to refresh your tmp folder (and thereby refresh the Terraform cache), you can always pass in the `--terragrunt-source-update` property.

**Comment by tomdavidson** [comment]
Thanks for the quick reply and help.  If I understand correctly, I prob should not cache the terragrunt cache between ci jobs, but let terragrunt copy just want it needs (starting clean) from the terraform cache?

> I'm not sure I understood the last part of your question

I have a script that terraform gets all the found terraform modules so I can pre-download all the needed plugins and modules. Sounds like there is no compatibility issues.

**Comment by brikis98** [comment]
Terraform's plugin cache should work just fine with Terragrunt.

You could also cache Terragrunt's cache folder, but we typically don't recommend it in CI. Terragrunt's cache is useful in dev to speed up commands, but in CI, you want to be sure you're starting with a fresh, reproducible environment where possible.

**Comment by tomdavidson** [comment]
Thank you @josh-padnick and @brikis98  for helping me figure out a good practice to do ci caching with terragrunt.
