### ISSUE TITLE
rename terragrunt option `RenderJSONithMetadata` to `RenderJSONWithMetadata` (with a `W`)

### ISSUE THREAD

**Issue by ceschae** [gruntwork-io/terragrunt#3578]
## Describe the bug

The [terragrunt options field](https://github.com/gruntwork-io/terragrunt/blob/d8adfda9e8c6e012816d8c7638416e68e1b37245/options/options.go#L284) `RenderJSONithMetadata` has a small typo in it, it should be `RenderJSONWithMetadata` (with a `W`). 

## Steps To Reproduce

since it's a typo, there's no reproduction steps to follow

## Expected behavior

i'd expect `With` to be spelled with a `W`

## Nice to haves

- [ ] Terminal output: n/a
- [ ] Screenshots: n/a

## Versions

- Terragrunt version: v0.67.7
- OpenTofu/Terraform version: n/a
- Environment details (Ubuntu 20.04, Windows 10, etc.): n/a

## Additional context

n/a

**Comment by yhakbar** [comment]
We'll look to cut a release including this fix sometime today or tomorrow.
