### ISSUE TITLE
Terragrunt tests are not properly cleaning up S3 buckets after themselves

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#358]
The automated tests for Terragrunt leave behind a bunch of buckets with names like `terragrunt-test-bucket-wdst9m`. We need to clean those up!

**Comment by mcalhoun** [comment]
I cleaned up the buckets for now using ``for bucket in `aws s3api list-buckets | jq -r '.Buckets[] | .Name' | grep terragrunt-test-bucket`; do aws s3api delete-bucket --bucket $bucket; done``

**Comment by brikis98** [comment]
Ah, nice!

**Comment by mcalhoun** [comment]
I can confirm that 1 s3 bucket is being left over after each build. The odd thing, is I can find no mention of the bucket in the test logs? :\

For example, after deleting all test buckets, then running [530](https://circleci.com/gh/gruntwork-io/terragrunt/530), the bucket `terragrunt-test-bucket-zoqtdj` exists. I can find no occurrence of `zoqtdj` anywhere in the logs.

**Comment by brikis98** [comment]
I see it in the logs:

```
[terragrunt] [/tmp/terragrunt-test677907025/fixture-download/local-with-missing-backend] 2017/11/09 18:32:27 [terragrunt] [/tmp/terragrunt-test677907025/fixture-download/local-with-missing-backend]  Remote state S3 bucket terragrunt-test-bucket-zoqtdj does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
[terragrunt] [/tmp/terragrunt-test677907025/fixture-download/local-with-missing-backend] 2017/11/09 18:32:27 
[terragrunt] [/tmp/terragrunt-test677907025/fixture-download/local-with-missing-backend] 2017/11/09 18:32:27 The non-interactive flag is set to true, so assuming 'yes' for all prompts
[terragrunt] [/tmp/terragrunt-test677907025/fixture-download/local-with-missing-backend] 2017/11/09 18:32:27 Creating S3 bucket terragrunt-test-bucket-zoqtdj
[te
```
