### ISSUE TITLE
working directory exclude or glob?

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#359]
Hello my current project structure has several parent folders at root that I want to have different lifecycles and that do not necessarily have terragrunt dependencies. Examples include "tf_modules" that when appropriate my move out of repo to a catalog and "prerequisites"  that sets up base dns, iam user, and policies (previously set up remote backend, but Im switching to terragrunt for it),

I can reorg so each independent lifecycle is nested in a directory to use "--terragrunt-working-dir" but before I do, I want to make sure there is no globbing or exclude options.

For validate-all I might do all but for plan-all I might want to --exclude modules/  ?

**Comment by brikis98** [comment]
Sounds like a similar question to #355. Is that the same idea? If so, then no, it's not currently supported, but would be good to add.

**Comment by tomdavidson** [comment]
Yes, #355 is it. Ill respond there. Thanks.
