### ISSUE TITLE
Got `Could not encode version for local source` error

### ISSUE THREAD

**Issue by kamontat** [gruntwork-io/terragrunt#3590]
## Describe the bug

I got the warning message log from below code.
I would like to check what is the underly error message cause this warning logs.

https://github.com/gruntwork-io/terragrunt/blob/88a99ad600bcec233fd5b71ecb0c757e12e2184a/terraform/source.go#L93

## Steps To Reproduce

1. Create libs and apps directory
2. Create simple module in libs directory
3. Create simple apps with terragrunt.hcl from below

```hcl
include "root" {
  path   = find_in_parent_folders()
  expose = true
}
terraform {
  source = "${path_relative_from_include()}/libs/aws-s3"
}
```

## Expected behavior

No warning logs.

## Nice to haves

- [X] Terminal output
- [X] Screenshots

![CleanShot 2024-11-22 at 12 43 22](https://github.com/user-attachments/assets/eb46a522-7cdd-4b3c-8958-ea318c952609)

## Versions

- Terragrunt version: v0.68.17
- OpenTofu version: v1.8.5
- Environment details (Ubuntu 20.04, Windows 10, etc.): MacOS 15.1.1

**Comment by yhakbar** [comment]
Hey @kamontat ,

I wasn't able to reproduce this issue when looking at [the test fixture used for local sources](https://github.com/gruntwork-io/terragrunt/blob/main/test/fixtures/download/local/terragrunt.hcl).

Would you be willing to create a public repository under your username (something like `kamontat/terragrunt-fixtures`) with an example fixture that I can reproduce this on?

**Comment by kamontat** [comment]
I was able to resolve this issue by delete all caching (both providers and modules).

I was upgraded Opentofu from v1.7 to v1.8 when the warning occurred but after I deleted all cache, the warning is gone. Thank you for your help
