### ISSUE TITLE
fatal error: systemstack called from unexpected goroutine

### ISSUE THREAD

**Issue by antonbabenko** [gruntwork-io/terragrunt#36]
I get this error once in a while:

```
fatal error: systemstack called from unexpected goroutine
...
### same line repeated 500+ times ###
...
fatal error: systemstack called from unexpected goroutine
./terraform.sh: line 210: 23108 Segmentation fault: 11  terragrunt get $LAYER_WORK_DIR
```

Rerun of the same command helps.

Here is nice stack trace to review - https://gist.github.com/antonbabenko/87bfdd7c070146d49d1021be424458d4

**Comment by brikis98** [comment]
Hm, strange. Please post the stack trace when you have it so we can track this down!

**Comment by antonbabenko** [comment]
Added link to stack trace to description

**Comment by brikis98** [comment]
Wow, bizarre. If I'm reading your stacktrace correctly, it points to [this line in dynamo_lock_item.go](https://github.com/gruntwork-io/terragrunt/blob/master/locks/dynamodb/dynamo_lock_item.go#L114):

```go
output, err := stsconn.GetCallerIdentity(&sts.GetCallerIdentityInput{})
```

Browsing the stacktrace, it looks like a potential bug in the AWS Go SDK or even the underlying Go HTTP libraries it's using to make API calls.

**Comment by antonbabenko** [comment]
New day, new [crash log](https://gist.github.com/antonbabenko/87bfdd7c070146d49d1021be424458d4#file-crash-log-3-10-2016). Maybe you will see anything strange in that one. Rerun works fine.

**Comment by josh-padnick** [comment]
I independently verified it's the same `GetCallerIdentity()` function that caused the panic and it seems to be happening when the HTTP request itself is sent, so I'm in agreement with Jim that this is most likely an issue witht he AWS Go SDK.

That being said, I notice that we are on a [relatively old release](https://github.com/aws/aws-sdk-go/commit/665c623d7f3e0ee276596b006655ba4dbe0565b0) of the AWS SDK, so I'll update to the latest commit and issue a new release. Once that happens, can you let us know if this happens again?

Thanks for reporting this!

**Comment by antonbabenko** [comment]
@josh-padnick I will be glad to try it out and report as soon as I hit it again.

**Comment by brikis98** [comment]
@antonbabenko I just released a new version of terragrunt with all dependencies updated: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.1.1. It'll take a few minutes for the build to run, after which new binaries should show up in that release. Please give them a shot when you have a chance and let us know if you're still seeing this bug. Thanks!

**Comment by antonbabenko** [comment]
Build failed - https://circleci.com/gh/gruntwork-io/terragrunt/114

**Comment by brikis98** [comment]
Sorry about that, looks like GitHub was briefly down. I just reran the build and it passed: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.1.1

**Comment by antonbabenko** [comment]
Thanks guys. I have [installed it](https://github.com/antonbabenko/homebrew-tap/blob/master/Formula/terragrunt.rb) and will be using it. Closing this issue now, will open new issue if problem persists.
