### ISSUE TITLE
Test failures on master

### ISSUE THREAD

**Issue by kevinburkeotto** [gruntwork-io/terragrunt#362]
I'm getting the following error when running this test:

```
$ go test -count=1 github.com/gruntwork-io/terragrunt/config
[terragrunt] [config_test] 2017/11/09 15:43:51 extra_arguments 'overrideArgs' from child overriding parent
--- FAIL: TestResolveTerragruntInterpolation (0.00s)
    --- FAIL: TestResolveTerragruntInterpolation/${find_in_parent_folders()}#01 (0.00s)
        Error Trace:    config_helpers_test.go:343
    	Error:      	An error is expected but got nil.
--- FAIL: TestResolveTerragruntConfigString (0.00s)
    --- FAIL: TestResolveTerragruntConfigString/${find_in_parent_folders()}#01 (0.00s)
        Error Trace:    config_helpers_test.go:475
    	Error:      	An error is expected but got nil.
--- FAIL: TestFindInParentFolders (0.00s)
    --- FAIL: TestFindInParentFolders/../test/fixture-parent-folders/no-terragrunt-in-root/child/sub-child/terraform.tfvars (0.00s)
        Error Trace:    config_helpers_test.go:204
    	Error:      	An error is expected but got nil.
FAIL
FAIL	github.com/gruntwork-io/terragrunt/config	0.015s
```

Haven't investigated it at all, so can't tell you what the problem is.

**Comment by brikis98** [comment]
Hmph, the tests _just_ passed in CircleCi, so there must be some bug in the test code that is triggered by environmental differences :-\

**Comment by kevinburkeotto** [comment]
The first test that's failing is this one:

```
		{
			"${find_in_parent_folders()}",
			nil,
			options.TerragruntOptions{TerragruntConfigPath: "../test/fixture-parent-folders/no-terragrunt-in-root/child/sub-child/" + DefaultTerragruntConfigPath, NonInteractive: true},
			"",
			ParentFileNotFound{},
		},
```

This is what it finds (successfully):

```
$ go test -count=1 github.com/gruntwork-io/terragrunt/config -run TestResolveTerragruntInterpolation
matches [${find_in_parent_folders()} find_in_parent_folders ]
currentDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders/no-terragrunt-in-root/child
previousDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders/no-terragrunt-in-root/child/sub-child
currentDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders/no-terragrunt-in-root
previousDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders/no-terragrunt-in-root/child
currentDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders
previousDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders/no-terragrunt-in-root
currentDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test
previousDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test/fixture-parent-folders
currentDir /Users/kevin/src/github.com/gruntwork-io/terragrunt
previousDir /Users/kevin/src/github.com/gruntwork-io/terragrunt/test
currentDir /Users/kevin/src/github.com/gruntwork-io
previousDir /Users/kevin/src/github.com/gruntwork-io/terragrunt
currentDir /Users/kevin/src/github.com
previousDir /Users/kevin/src/github.com/gruntwork-io
currentDir /Users/kevin/src
previousDir /Users/kevin/src/github.com
currentDir /Users/kevin
previousDir /Users/kevin/src
actual out: "../../../../../../../../../.terragrunt"
```

**Comment by brikis98** [comment]
Ohhh... Is it possible you just happen to have a `.terragrunt` file in some parent folder of where Terragrunt is checked out? If so, the test may unintentionally be finding it :)

**Comment by kevinburkeotto** [comment]
I have a `.terragrunt` file in /Users/kevin and a source code checkout in `/Users/kevin/src/github.com/gruntwork-io/terragrunt`, which seems like it's a pretty common occurrence?

**Comment by brikis98** [comment]
Indeed. Looks like that test needs to copy the code into some tmp folder or other location where the root won't contain a `.terragrunt` or `terraform.tfvars` file.

**Comment by kevinburkeotto** [comment]
I am not sure it's the best solution, as that still leaves open the possibility of recursing to a parent folder that contains a `.terragrunt` directory. I don't think tests should rely at all on the state of the contents of folders above them in the directory hierarchy.

**Comment by brikis98** [comment]
Ah, there is a simpler alternative.

Right now, the `find_in_parent_folders` helper traverses up the directory tree, up to `MAX_PARENT_FOLDERS_TO_CHECK` folders. This is a constant, but we could make it a variable defined in `TerragruntOptions`. We can then set it to a low number at test time to ensure it doesn't go beyond the fixtures folder.

**Comment by kevinburkeotto** [comment]
> This is a constant, but we could make it a variable defined in TerragruntOptions

This would make the tests fail in a different way, they currently check for ParentFileNotFound, but they'd need to check for CheckedTooManyParentFolders instead.

**Comment by brikis98** [comment]
True. I think it's totally fine to return `ParentFileNotFound` there and add a `Cause` field to it that, there, get set to "too many parent folders".

**Comment by kevinburkeotto** [comment]
another workaround would be to respect my XDG_CACHE_HOME setting (see https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html for details) or to write to `~/Library/Caches`, neither of which are parents of my source code directory

**Comment by brikis98** [comment]
I think any folder we happen to use has a chance of having some `.terragrunt` or `terraform.tfvars` file above it. It seems like improving the error handling is a more robust fix.
