### ISSUE TITLE
$TF_INPUT for automation

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#363]
Terraform looks to the env var TF_INPUT  as an automation feature.  Terragrunt has a similar feature but with a CLI flag, --terragrunt-non-interactive (Terrafrom also as -input).

Can Terragrunt also look to TF_INPUT? The advantage of using the environment rather then the config file for this is that with the same files local, I can be interactive but in my CI jobs I can be non-interactive.

**Comment by brikis98** [comment]
Ah, that's a good idea. Should be pretty straightforward to have Terragrunt read in the `TF_INPUT` env var in addition to the `--terragrunt-non-interactive` flag.

**Comment by tomdavidson** [comment]
Are we looking at [cli/args.go#L85](https://github.com/gruntwork-io/terragrunt/blob/5e18856f70be91989c53397f00655c96d2bf052b/cli/args.go#L85) ?

`opts.NonInteractive = parseBooleanArg(args, OPT_NON_INTERACTIVE, os.Getenv("TF_INPUT") == "false")`

**Comment by brikis98** [comment]
Yup, that's the place. Note that the semantics for Terraform and Terragrunt are reversed: with Terragrunt, setting `NonInteractive` to `true` disables input, whereas with Terraform, setting `TF_INPUT` to `false` disables input.

**Comment by tomdavidson** [comment]
thanks updated my comment so it does not not confuse
