### ISSUE TITLE
STDOUT for destroy operations unexpectedly is logged at DEBUG level

### ISSUE THREAD

**Issue by Kab1r** [gruntwork-io/terragrunt#3631]
## Describe the bug

Running `terragrunt destroy` from a module that includes a parent causes destroy logs to go to DEBUG log level instead of stdout.

## Steps To Reproduce

```
# Setup Directory
cd (mktemp -d)
mkdir terragrunt-destroy-log-bug
cd terragrunt-destroy-log-bug

# Setup Terragrunt Files
touch terragrunt.hcl
mkdir example
echo 'include {
  path = find_in_parent_folders()
}' > example/terragrunt.hcl
echo 'resource "null_resource" "example" {}' > example/example.tf

# Apply
cd example
terragrunt apply  -auto-approve

# Destroy
terragrunt destroy # No messages on stdout
terragrunt destroy --terragrunt-log-level debug # Messages appear
```

## Expected behavior

Destroy logs should go to stdout.

## Nice to haves

- [x] Terminal output
- [x] Screenshots

Terminal Recording of Bug:

![terragrunt-destroy-log-bug-2 cast](https://github.com/user-attachments/assets/0d654899-d626-4735-82ed-331b21cf206f)

## Versions

- Terragrunt version: `0.69.7`
- OpenTofu/Terraform version: `v1.8.6`
- Environment details (Ubuntu 20.04, Windows 10, etc.): `MacOS Sonoma 14.7.1 (23H222)`
## Additional context

N/A

**Comment by yhakbar** [comment]
Thanks for reporting this, @Kab1r . We'll take a look at this soon and get back to you.
