### ISSUE TITLE
missing vars from included file

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#365]
My live plan is not including variables from the included terraform.tfvars file. Do I misunderstand how the include it is suppose to work?

root/
  --pq/terraform.tfvars
  --terraform.tfvars

In the pq file is have:
```hcl
terragrunt = {
  include {
    path = "${find_in_parent_folders()}"
  }

  terraform {
    source = "../tf_modules/k8s/pq"
  }
}

```
and in the root file I have
```hcl
terragrunt = {
  remote_state {
  ...
 }
}

names = {
  "prefix" = "devops-k8s"
}

dns = {
  "base_zone" = "k8s.domain.com"
}
```

If I add the names and dns maps to the pq file then all is is well (except it is wet).

**Comment by brikis98** [comment]
`include` currently only includes the `terragrunt = { ... }` configuration. Including configs from the parent `.tfvars` file is an interesting idea worth thinking through. See #132 for related discussion.

**Comment by tomdavidson** [comment]
@brikis98 thanks a ton for helping me get started with terragrunt.
I thought #132 was about interpolation but I'm starting to understand the "tg theory" better and am happy to do a pr on the readme to help this be more explicit for the next new user - unless it is just me :)

**Comment by brikis98** [comment]
Yes, #132 is about interpolation, but underneath, it's the same general question: how to re-use variables across various `.tfvars` files.

PR to clarify this in the README is very welcome.
