### ISSUE TITLE
Log custom format placeholder "%tf-command-args" documented but not available

### ISSUE THREAD

**Issue by atheiman** [gruntwork-io/terragrunt#3675]
I am loving the new log formatting for `run-all` commands since recently upgrading. I tried customizing the log format using `--terragrunt-log-custom-format` and I noticed `%tf-command-args` is a documented placeholder but not available to use.

```
$ terragrunt --version
terragrunt version v0.69.13
$ terragrunt run-all init --terragrunt-log-custom-format "%time() %tf-command-args() %msg"
11:16:56.600 <tab>f-command-args() Initializing the backend...
...
```

Looks like the log formatter is just processing `%t` off the front of `%tf-command-args`. But `%tf-path` is working as expected, and it begins with `%t`. So I tried specifying `%wrong` to do a little more debugging:

```
$ terragrunt run-all init --terragrunt-log-custom-format "%wrong"
```

`ERROR flag --terragrunt-log-custom-format, invalid placeholder name "wrong", available values: interval,time,level,msg,prefix,tf-path`

Looks like `%tf-command-args` is not an accepted log format placeholder.

Unfortunately I dont know enough go to fix the issue, but I do see `tf-command-args is at least attempted to be registered here: https://github.com/gruntwork-io/terragrunt/blob/485ee371710c9da4b606a606f88147acae48c758/pkg/log/format/placeholders/field.go#L11

But here it doesnt see `tf-command-args` as registered in the rendered error message: https://github.com/gruntwork-io/terragrunt/blob/485ee371710c9da4b606a606f88147acae48c758/pkg/log/format/placeholders/placeholder.go#L208

**Comment by yhakbar** [comment]
Fix released in [v0.70.2](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.70.2).
