### ISSUE TITLE
misunderstanding  required_var_files

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#368]
I am trying to do things the terragrunt way but am struggling fully understanding (and am taking notes from my newbie/fresh perspective to share in the README.md). Rightly now I am not able to share configuration (tfvars) and do not quite understand how terragrunt solves this better than symlinks. 

From the project root, I run `terragrunt plan --terragrunt-working-dir config/pq` - so I am only looking at the pq/ and not the nested prod/ and stage/ configs right now.

The vars in config/common.tfvars are not available for config/pq. If I explicitly add the two vars to the config/pq/terrafrom.tfvars, the plan works just fine.

Three are three elements in required_var_files = [], but that is jsut for this issue, I have been trying just one at a time

```
config/
├── common.tfvars
├── pq
│   └── terraform.tfvars
├── prod
│   ├── hactar
│   │   ├── main.tf
│   │   └── terraform.tfvars
│   └── roosta
│       ├── main.tf
│       └── terraform.tfvars
├── stage
│   ├── aws
│   │   └── terraform.tfvars
│   └── vmw
│       └── terraform.tfvars
└── terraform.tfvars
```

config/pq/terrafrom.tfvars:
```hcl
terragrunt = {

  include {
    path = "${find_in_parent_folders()}"
  }

  terraform {
    source = "${get_tfvars_dir()}/../../tf_modules/k8s/pq"
  }
}
```

config/common.tfvars:
```hcl
names = {
  "prefix" = "devops-k8s"
}

dns = {
  "base_zone" = "k8s.domain.com"
}
```

config/terraform.tfvars:
```hcl
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket         = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
      key            = "${path_relative_to_include()}/terraform.tfstate"
      region         = "${get_env("TF_VAR_REGION", "us-west-2")}"
      encrypt        = true
      dynamodb_table = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
    }
 }

  extra_arguments "common_vars" {
    commands = ["${get_terraform_commands_that_need_vars()}"]

    required_var_files = [
      "../common.tfvars",
      "${find_in_parent_folders("common.tfvars")}",
      "${path_relative_to_include()}/../common.tfvars}"
    ]
  }
}
```

**Comment by brikis98** [comment]
Can you paste the log output?

**Comment by tomdavidson** [comment]
For sure and thank you for looking at this:

$ terragrunt plan --terragrunt-working-dir config/pq
[terragrunt] [config/pq] 2017/11/11 20:07:30 Running command: terraform --version
[terragrunt] 2017/11/11 20:07:30 Reading Terragrunt config file at config/pq/terraform.tfvars
[terragrunt] 2017/11/11 20:07:31 WARNING: no double-slash (//) found in source URL /home/tom/Projects/devops-k8s/config/pq/../../tf_modules/k8s/pq. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2017/11/11 20:07:31 Cleaning up existing *.tf files in /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/5pCiUqyGC0mBgS6gs2vfJTH0zlw
[terragrunt] 2017/11/11 20:07:31 Downloading Terraform configurations from file:///home/tom/Projects/devops-k8s/tf_modules/k8s/pq into /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/5pCiUqyGC0mBgS6gs2vfJTH0zlw using terraform init
[terragrunt] [config/pq] 2017/11/11 20:07:31 Backend s3 has not changed.
[terragrunt] [config/pq] 2017/11/11 20:07:31 Running command: terraform init -backend-config=region=us-west-2 -backend-config=encrypt=true -backend-config=dynamodb_table=devops-k8s-exp-us-west-2-032474939542 -backend-config=bucket=devops-k8s-exp-us-west-2-032474939542 -backend-config=key=pq/terraform.tfstate -from-module=file:///home/tom/Projects/devops-k8s/tf_modules/k8s/pq /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/5pCiUqyGC0mBgS6gs2vfJTH0zlw
Copying configuration from "file:///home/tom/Projects/devops-k8s/tf_modules/k8s/pq"...

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2017/11/11 20:07:34 Copying files from config/pq into /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/5pCiUqyGC0mBgS6gs2vfJTH0zlw
[terragrunt] 2017/11/11 20:07:34 Setting working directory to /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/5pCiUqyGC0mBgS6gs2vfJTH0zlw
[terragrunt] 2017/11/11 20:07:34 Backend s3 has not changed.
[terragrunt] 2017/11/11 20:07:34 Running command: terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.parent: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.template_file.trust_policy: Refreshing state...
data.template_file.iam_policy: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.aws_route53_zone.parent: 1 error(s) occurred:

* data.aws_route53_zone.parent: data.aws_route53_zone.parent: Either name or zone_id must be set


[terragrunt] 2017/11/11 20:07:38 *exec.ExitError exit status 1
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/shell/run_shell_cmd.go:58 (0x463c0f)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/shell/run_shell_cmd.go:21 (0x46367b)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:264 (0x45cb4c)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:223 (0x45c6c4)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:196 (0x45c5b0)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:177 (0x45c29c)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:502 (0x49c5e4)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:268 (0x49a31d)
/home/ubuntu/.go_workspace/src/github.com/gruntwork-io/terragrunt/main.go:20 (0x4010c4)
/usr/local/go/src/runtime/proc.go:183 (0x42a864)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x458e51)

**Comment by brikis98** [comment]
> Error: Error refreshing state: 1 error(s) occurred:
>
> data.aws_route53_zone.parent: 1 error(s) occurred:
> 
> data.aws_route53_zone.parent: data.aws_route53_zone.parent: Either name or zone_id must be set

What does the code look like for the `aws_route53` data source? Are you setting the `name` or `zone_id` param?

**Comment by brikis98** [comment]
Ohhhh, never mind, it's simpler. You need to put the `extra_arguments` block into a `terraform` block in `config/terraform.tfvars`:

```hcl
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket         = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
      key            = "${path_relative_to_include()}/terraform.tfstate"
      region         = "${get_env("TF_VAR_REGION", "us-west-2")}"
      encrypt        = true
      dynamodb_table = "devops-k8s-${get_env("TF_VAR_ENV", "exp")}-${get_env("TF_VAR_PRIMARY_REGION", "us-west-2")}-${get_aws_account_id()}"
    }
  }

  terraform {
    extra_arguments "common_vars" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      required_var_files = [
        "../common.tfvars",
        "${find_in_parent_folders("common.tfvars")}",
        "${path_relative_to_include()}/../common.tfvars}"
      ]
    }  
  }
}
```

**Comment by tomdavidson** [comment]
Thanks @brikis98  

The plan works fine when I define the two vars next to the plan rather than in included  root/terraform.tfvars (k8s/pq module computes the parent zone from the var.base_zone). 

After correcting the syntax (terraform block) I still am having trouble:

Requiring ` "${find_in_parent_folders("common.tfvars")}"`  errors as though the file is not found, but error message does not reference the requried_var_file:
```
[terragrunt] 2017/11/12 23:29:24 Running command: terraform plan -var-file=../terraform.tfvars
invalid value "../terraform.tfvars" for flag -var-file: Error reading ../terraform.tfvars: open ../terraform.tfvars: no such file or directory
Usage: terraform plan [options] [DIR-OR-PLAN]
```

Requiring `"${get_tfvars_dir()}/../common.tfvars"` doesn't error on the command but does not find the assigned values:

```
[terragrunt] 2017/11/12 23:34:36 Running command: terraform plan -var-file=/home/tom/Projects/incontact/devops-k8s/config/pq/../common.tfvars
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.aws_route53_zone.parent: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.template_file.iam_policy: Refreshing state...
data.template_file.trust_policy: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.aws_route53_zone.parent: 1 error(s) occurred:

* data.aws_route53_zone.parent: data.aws_route53_zone.parent: no matching Route53Zone found
```

The pq module is a submodule of k8s that shares a config.tf via symlink with sibling submodules. config.tf is just locals that do things such as:

```hcl
  dns_defaults = {
    prefix      = ""
    base_zone   = "${lookup(var.dns, "base_zone", "")}"
    hostname    = "${join(".", slice(local.dns_split, 0, 1))}"
    parent_zone = "${join(".", slice(local.dns_split, 1, length(local.dns_split)))}"
  }

  dns_split = "${split(".", lookup(var.dns, "base_zone", ""))}"

  dns = "${merge(local.dns_defaults, var.dns)}"
```

I have my terragrunt experiment in public at https://gitlab.com/tom.davidson/devops-k8s/tree/ci-tg-plan/ but the module looks like:
 
tf_modules/k8s/
├── aws
│   └── main.tf
├── config.tf
├── in.tf
├── pq
│   ├── config.tf -> ../config.tf
│   ├── in.tf -> ../in.tf
│   ├── io.tf
│   ├── main.tf
│   └── policy.json
└── vsphere

https://gitlab.com/tom.davidson/devops-k8s/tree/ci-tg-plan/

**Comment by brikis98** [comment]
> terraform plan -var-file=/home/tom/Projects/incontact/devops-k8s/config/pq/../common.tfvars

Looks like Terragrunt is passing your `.tfvars` file to Terraform, so that part is working correctly.

```
data.aws_route53_zone.parent: data.aws_route53_zone.parent: no matching Route53Zone found
```

This is a different error. It implies that it can't find the Route 53 hosted zone you specified. Check the domain name you are using in the search (e.g., you typically need a trailing dot).

**Comment by tomdavidson** [comment]
Aaaah  my placeholder domain (k8s.domain.com) needed changed back. I have the terraform block (this was clearly the issue), the correct base_zone value (sorry), but still not there:

"${find_in_parent_folders("test.tfvars")}" does not work. It looks like a relative path - relative to what? The same works for the include, just not the required vars. "${get_parent_tfvars_dir()}/test.tfvars"  works fine for required vars - im not getting something.

```sh
[terragrunt] 2017/11/13 23:13:25 Running command: terraform plan -var-file=../test.tfvars
invalid value "../test.tfvars" for flag -var-file: Error reading ../test.tfvars:open ../test.tfvars: no such file or directory
```

```hcl
  terraform {
    extra_arguments "common_vars" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      required_var_files = [
        "${find_in_parent_folders("test.tfvars")}"
      ]
    }
  }
```

```sh
.
├── common.tfvars
├── pq
│   └── terraform.tfvars
├── prod
│   ├── hactar
│   │   ├── main.tf
│   │   └── terraform.tfvars
│   └── roosta
│       ├── main.tf
│       └── terraform.tfvars
├── stage
│   ├── aws
│   │   └── terraform.tfvars
│   └── vmw
│       └── terraform.tfvars
├── terraform.tfvars
└── test.tfvars
```

**Comment by josh-padnick** [comment]
@tomdavidson I believe you're pretty close! In your top-level `terraform.tfvars` file, try:

```
required_var_files = [
      "${get_tfvars_dir()}/${find_in_parent_folders("test.tfvars", "skip-test-if-does-not-exist")}"
   ]
}
```

Remember that this gets included verbatim into your "leaf" `terraform.tfvars` and is evaluated only in your leaf `terraform.tfvars` file. The leaf `terraform.tfvars` file should just have:

```
include = {
   path = "${find_in_parent_folders()}"
}
```

**Comment by tomdavidson** [comment]
@josh-padnick thanks. You solution satisfies what I am after, but why is get_tfvars_dir() needed in the path? Doesn't find_in_partent_folders() return a viable the path?

**Comment by brikis98** [comment]
> Doesn't find_in_partent_folders() return a viable the path?

It currently returns a relative path. When you use `source` with Terragrunt, your code is copied to a tmp folder, so the relative path doesn't work, and needs to be made absolute. 

Perhaps `find_in_partent_folders()` needs to be made absolute too. I'm not sure; would require digging through use cases to see what impact that would have.

**Comment by tomdavidson** [comment]
The relative path in the include is fine because that file is fetched before the cop? 

Everything on the right side a source '//' is copied to the temp folder so symlinks do not break as long as they are on the right side?

**Comment by brikis98** [comment]
> The relative path in the include is fine because that file is fetched before the cop?

Yup.

> Everything on the right side a source '//' is copied to the temp folder so symlinks do not break as long as they are on the right side?

Yes, everything to the right of `//` is copied. That is so relative paths worked. I haven't tried symlinks, so I'm not positive if those work or not.

**Comment by tomdavidson** [comment]
My module has submodels that share some locals via symlinks -  ill open in issue if it doesn't work :)

Thanks again @brikis98 and @josh-padnick

**Comment by tomdavidson** [comment]
`terragrunt validate-all --terragrunt-working-dir config/` fails because the `config/terraform.tfvars` requried_var_files:

```hcl
required_var_files = [
      "${get_tfvars_dir()}/${find_in_parent_folders("common.tfvars")}"
   ]
```

I am using required rather than optional and I do not have a error default because the plans in config/ should fail if they can not find common.fvars - is this not the "recommended" practice?

```
config
├── common.tfvars
├── pq
│   └── terraform.tfvars
├── prod
│   ├── hactar
│   │   ├── main.tf
│   │   └── terraform.tfvars
│   └── roosta
│       ├── main.tf
│       └── terraform.tfvars
├── stage
│   ├── aws
│   │   └── terraform.tfvars
│   ├── stage.tfvars
│   └── vmw
│       └── terraform.tfvars
└── terraform.tfvars
```

**Comment by brikis98** [comment]
Why does that command fail for you? What's the actual error you're getting?

**Comment by tomdavidson** [comment]
This is not blocking, the simple work around is not to use validate-all, but validate on each individual subconfig. I could also make the common.tfvars optional rather than required, but I want it to fail if the file is not found when applying the subconfigs.

 ```sh
$ terragrunt validate-all --terragrunt-working-dir config/[terragrunt] [config] 2017/11/16 11:12:12 Running command: terraform --version
[terragrunt] 2017/11/16 11:12:12 Error processing module at '/home/tom/Projects/incontact/devops-k8s/config/terraform.tfvars'. How this module was found: Terragrunt config file found in a subdirectory of config/. Underlying error: Could not find a common.tfvars in any of the parent folders of/home/tom/Projects/incontact/devops-k8s/config/terraform.tfvars. Cause: Traversed all the way to the root.
[terragrunt] 2017/11/16 11:12:12 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

ps no prob with the symlinks ... just need to make sure the '//' in your source path is correct

**Comment by yorinasub17** [comment]
Closing as stale. Please reopen if this is still an issue in the latest versions!
