### ISSUE TITLE
terragrunt plan should respect -detailed-exitcode

### ISSUE THREAD

**Issue by antonbabenko** [gruntwork-io/terragrunt#37]
`terraform plan -detailed-exitcode` may return 0, 1, 2. [Official documentation](https://www.terraform.io/docs/commands/plan.html#_detailed_exitcode)

`terragrunt plan -detailed-exitcode` currently return 0 or 1.

**Comment by brikis98** [comment]
Ah, good catch.

**Comment by cultavix** [comment]
Any update on this?

**Comment by brikis98** [comment]
@cultavix We haven't had a chance to take a crack at it. Anyone interested in submitting a PR?

Easiest solution is probably to have the `checkForErrorsAndExit` method in [main.go](https://github.com/gruntwork-io/terragrunt/blob/master/main.go) check if the error is of some new type `ErrorWithExitCode` and if it is, call `os.Exit` with that code. After that, all you'd have to do is update the `RunShellCommand` method in [run_shell_cmd.go](https://github.com/gruntwork-io/terragrunt/blob/master/shell/run_shell_cmd.go) to capture the exit code when there is an error and return an `ErrorWithExitCode` struct.

**Comment by asobrien** [comment]
I took a stab at this with PR #98. `checkForErrorsAndExit` will exit with the underlying error code in the case of an error. I can confirm that this exits with exit code = 2, as expected, when `terragrunt plan -detailed-exitcode` is called and there are diffs.
