### ISSUE TITLE
version manager and installer

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#370]
I created a [Terragrunt plugin](https://gitlab.com/td7x/asdf/terragrunt) for [asdf-vm](https://github.com/asdf-vm/asdf) and have an opened [PR](https://github.com/asdf-vm/asdf-plugins/pull/19) to register it.

asdf gives osx and linux users (ci jobs) a 'universal' path to managing tool versions. Anyone care to test it out? especially osx users? Here is a quicky, but read the asdf README.md too. Once the asdf-plugin PR is approved, the git urls will not be needed:

```sh
$ asdf plugin-add terragrunt https://gitlab.com/td7x/asdf/terragrunt
$ asdf list-all terragrunt
$ asdf install terragrunt 0.8.13
$ cd test-dir
$ printf "terraform 0.10.0\nterragrunt 0.13.0\n" > .tool-versions
$ asdf install
$ echo terraform version && echo terragrunt --version
$ cd ..
$ echo terraform version && echo terragrunt --version
```

**Comment by tomdavidson** [comment]
The asdf plugin repo maintainers are not very responsive - quite a few waiting prs, including this one. Could we add this to the install instructions or wait for it to be installable without the url?

**Comment by brikis98** [comment]
How does it work before the maintainers merge it?

**Comment by tomdavidson** [comment]
The asdf-plugin maintainers only maintain the repository and not the plugins so its just a matter of convenience and discovery.

Installing the terragrunt plugin currently requires the git url:
```sh
$ asdf plugin-add terragrunt https://gitlab.com/td7x/asdf/terragrunt
```

But once its merged  then it can be installed by name:
```sh
$ asdf plugin-add terragrunt 
```

I like to use it with transform because it keeps my terraform version in sync with the proejct - it does not read the HCL files but the projects's terraform ( and other tool ) versions are listed in the project's .tool-versions file (more than just and installer).

Its not a big deal, I was jsut doing some house keeping with open issues and wondering if I should close this ore do a PR on the README.md ...

**Comment by brikis98** [comment]
Ah, gotcha. Sure, adding that to the README sounds great. Thx!
