### ISSUE TITLE
No way to set specific tags on specific resources when using gruntworks modules

### ISSUE THREAD

**Issue by sgendler-stem** [gruntwork-io/terragrunt#372]
Kops wants a KubernetesCluster tag on certain resources, which allows it to know which resources are available to the cluster.  However, gruntworks modules often create a number of resources without providing any way to override things like tags. For example, I can instantiate an app vpc using that module, but if I set the tags passed to that module, then pretty much every single resource gets tagged with the KubernetesCluster tag - public subnets, private subnets, internet gategways, nat gateways, the vpc itself, etc.  At best, that gets really confusing because the kubernetes-specific tag is there on every resource, regardless of whether it gets used by kops, and at worst it is catastrophic because kops may attempt to use public_subnets instead of private ones due to the incorrect tagging.  

It seems like merging the module-wide custom tags with resource-specific custom tags would be a very useful extension of the existing modules without breaking any kind of backward compatibility.  I don't believe aws-cli or terraform provides a way to add tags to a particular resource after it has been created, which is the only other way I can think of to apply the tag just to specific resources.  If I'm incorrect about that, I can certainly extract ids/names from the gruntworks modules in the outputs of my templates and feed them to a template which adds the necessary tags.  

Any other suggestions for solving this problem?  If not, can I give you a pull request that adds resource-specific overrides in a backwards-compatible manner?  I don't really want to get into the habit of just cloning your modules in order to make minor changes, since I lose the ability to easily pick up updates if I do that.

**Comment by brikis98** [comment]
A PR for our modules that gives you more fine-grained control over tagging sounds great!

That said, any reason you opened this issue in the Terragrunt repo? :)

**Comment by sgendler-stem** [comment]
I guess I was thinking of it as a Gruntworks library issue rather than an
issue for any particular module, and I didn't really put that much thought
into it.  My brain just translated 'the whole library' to be 'terragrunt'

On Wed, Nov 15, 2017 at 12:56 PM, Yevgeniy Brikman <notifications@github.com

**Comment by brikis98** [comment]
Heh, alright. Well, please feel free to open a PR in module-vpc or any other relevant repos that you need to support more granular tags. Thanks!
