### ISSUE TITLE
have --terragrunt-source work with absolute path

### ISSUE THREAD

**Issue by ebarault** [gruntwork-io/terragrunt#380]
I'm moving away my terraform modules away from the terragrungt config in a separate rep, and was playing with the `--terragrunt-source` option.

`terragrunt apply --terragrunt-source ../../../modules//app`

I noted that this feature is currently built to use relative path for local modules, which quickly ends in  `../../../../../modules_root//module_x` and related hits an misses.

Wouldn't that be more natural to use absolute path?

This is a development option, on my laptop I know where the module_root is, probably in a separate repo, or at the root of my project.
Then it's easy to crawl in the module_root to target the right module without having to nest `../` blocks depending on where i am in the project folders :
`/path/to/module_root//module_x`

Of course I guess the other way around is to execute terragrunt commands from the project's root and use `--terragrunt-working-dir` option.

Thoughts?

**Comment by brikis98** [comment]
> I'm moving away my terraform modules away from the terragrungt config in a separate rep

How come?

> I noted that this feature is currently built to use relative path for local modules

Have you tried using an absolute path with it? Do you get some sort of error?

**Comment by ebarault** [comment]
Nevermind @brikis98, it happens to work just fine... 

My previous attempts were trying with `--terragrunt-working-dir "~./path/to/modules//a/module"` and after replacing with `--terragrunt-working-dir "/absolute/path/to/modules//a/module"` it worked.

Sorry for the noise.
