### ISSUE TITLE
Terragrunt + terraform_remote_state

### ISSUE THREAD

**Issue by cyrus-mc** [gruntwork-io/terragrunt#385]
How does terragrunt integrate with terraform_remote_state? 

Prior to trying to implement terragrunt I had a block of code as such:

``
/*
  Setup the AWS provider
*/
provider "aws" {
  profile = "apps-nprod"
  region  = "${var.region}"
}

terraform {
  backend "s3" {
}

data "terraform_remote_state" "networking" {
  backend = "s3"
  config {
    bucket  = "com-dat-terraform"
    region  = "${var.region}"
    key     = "apps-nprod/networking/terraform.tfstate"
    profile = "apps-nprod"
  }
}

module "trucker-api-02" {
  source       = "/Users/code/terraform/modules/trucker-stack"
  stack_number = 2
  environment  = "dev"
  key_name     = ""

  subnet_id = "${data.terraform_remote_state.networking.prvt_subnet_id}"

}
``

As you can see, I set the subnets for the module based off a value from a remote state. 

When migrating to terragrunt my first attempt was to move the data "terraform_remote_state" into the module itself and not expose the subnet_id. However the limitation here is that as I move this stack around (different envs and accounts) I need to supply different parameters for the bucket, region, key and profile that data "terraform_remote_state" requires. Ideally I would like to be able to specify the data resource much like I do the remote_state resource within the terragrunt block.

**Comment by brikis98** [comment]
>However the limitation here is that as I move this stack around (different envs and accounts) I need to supply different parameters for the bucket, region, key and profile that data "terraform_remote_state" requires.

That's exactly what you do. Just turn those parameters into variables:

```hcl
data "terraform_remote_state" "networking" {
  backend = "s3"
  config {
    bucket = "${var.remote_state_bucket}"
    region = "${var.region}"
    key = "${var.remote_state_key}"
    profile = "${var.remote_state_profile}"
  }
}
```

You can have an `accounts.tfvars` or `environment.tfvars` that defines these variables for every account/environment and you can include that file in all Terragrunt modules using [extra_arguments](https://github.com/gruntwork-io/terragrunt#keep-your-cli-flags-dry).

**Comment by cyrus-mc** [comment]
@brikis98 

That is what I am going to attempt to do. Just need to work out my directory structure as using path_relative_to_include and for the remote state and that has to match for the terraform_remote_state buckets and keys.

Thanks

**Comment by hertzsprung** [comment]
> ```terraform
> data "terraform_remote_state" "networking" {
>   backend = "s3"
>   config {
>     bucket = "${var.remote_state_bucket}"
>     region = "${var.region}"
>     key = "${var.remote_state_key}"
>     profile = "${var.remote_state_profile}"
>   }
> }
> ```
Note the missing '=' in `config = { ... }`, in case anyone else is implementing from GitHub issue comments :slightly_smiling_face:
