### ISSUE TITLE
apply-all does not set auto-approve parameter

### ISSUE THREAD

**Issue by dewang** [gruntwork-io/terragrunt#386]
As of Terraform v0.11, the default behaviour for `terraform apply` is to show the plan and wait for approval. When using `apply-all` this results in the script waiting for input for every module that you want to deploy.

**Comment by brikis98** [comment]
Well, `apply-all` just runs `apply` in every directory, so it inherits whatever behavior Terraform has for `apply`. If you want it to be fully non-interactive, can't you just run `terragrunt apply-all -auto-approve`?

**Comment by dewang** [comment]
Interesting, I didn't think the parameter would be passed through. The stack sets `-input=false` https://github.com/gruntwork-io/terragrunt/blob/bc8bae6f1c771f5a5a38953a4bc041521c984940/configstack/stack.go#L73 so I assumed the `-auto-approve` would have to be passed the same way.
I can't imagine that anyone using `apply-all` would _not_ want it to be fully non-interactive.

Having said all that, I have to say a massive thanks for terragrunt and also your blog posts. They've really helped me get set up with terraform.

**Comment by brikis98** [comment]
> Interesting, I didn't think the parameter would be passed through. The stack sets -input=false

I believe the `setTerraformCommand` method [appends your CLI args to the passed-in command](https://github.com/gruntwork-io/terragrunt/blob/bc8bae6f1c771f5a5a38953a4bc041521c984940/configstack/stack.go#L114-L118), so it *should* work. Try it out and let me know!

> Having said all that, I have to say a massive thanks for terragrunt and also your blog posts. They've really helped me get set up with terraform.

Thanks :)

**Comment by ebarault** [comment]
Just faced the same problem and tested vanilla terraform option `-auto-approve` : it does work 👍 

That being said it really make the `--terragrunt-non-interactive` flag confusing since terraform v0.11.

Shouldn't the '-auto-approve` as well as `-force` options be added as well when using `--terragrung-non-interactive` ?

**Comment by brikis98** [comment]
> Shouldn't the -auto-approve as well as -force options be added as well when using --terragrung-non-interactive ?

I could go either way on this one, but *probably* setting `-auto-approve` to `true` would be following "principle of least surprise."

What is `-force`?

**Comment by ebarault** [comment]
`-force`: [cli option for **destroy**](https://www.terraform.io/docs/commands/destroy.html)

"If -force is set, then the destroy confirmation will not be shown"

**Comment by brikis98** [comment]
Ah, I see. Give how destructive `destroy` is, I'd rather NOT include `-force`. It may be a mild annoyance for users, but easily solved by adding that parameter in; the opposite situation, where you didn't realize `-force` would be included automatically would be much worse!

**Comment by ebarault** [comment]
agreed

2017-12-05 17:22 GMT+01:00 Yevgeniy Brikman <notifications@github.com>:

**Comment by robinbowes** [comment]
Another vote for adding `-auto-approve` when using `apply-all`. Without it, you end up with the terraform prompts getting lost when terragrunt runs multiple instances in parallel. It really makes no sense not to have `-auto-approve` with `apply-all` even when not using `--terragrunt-non-interactive`

**Comment by brikis98** [comment]
> Without it, you end up with the terraform prompts getting lost when terragrunt runs multiple instances in parallel.

Ah, yea, that's a good point. 

I'd welcome a PR to add this.

**Comment by mhumeSF** [comment]
PR created
https://github.com/gruntwork-io/terragrunt/pull/407

**Comment by brikis98** [comment]
Fixed by @mhumeSF in #407. Thx!

**Comment by brikis98** [comment]
New binaries will be here soon: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.14.0

**Comment by robinbowes** [comment]
Good job @mhumeSF

**Comment by phosphre** [comment]
Odd, I'm now on v0.14.9 and I just ran tg as above, only to get unexpectedly challenged:

```
$ **terragrunt apply-all -auto-approve**
[terragrunt] [/Path/to/terraform/environments/qa/eu-west-1] 2018/06/04 09:44:00 Running command: terraform --version
[terragrunt] 2018/06/04 09:44:00 Module /Path/to/terraform/environments/qa/eu-west-1 does not have an associated terraform configuration and will be skipped.
[terragrunt] 2018/06/04 09:44:00 Stack at /Path/to/terraform/environments/qa/eu-west-1:
  => Module /Path/to/terraform/environments/qa/eu-west-1/consul (dependencies: [])
  => Module /Path/to/terraform/environments/qa/eu-west-1/vpc (dependencies: [])
[terragrunt] 2018/06/04 09:44:00 [terragrunt]  **Are you sure you want to run 'terragrunt apply' in each folder of the stack described above? (y/n)**
^C
```

Is this still outstanding?
