### ISSUE TITLE
temporary credentials expiring while holding state lock = BAD

### ISSUE THREAD

**Issue by sgendler-stem** [gruntwork-io/terragrunt#396]
If using a federated user via 3rd party auth provider, users always work with temporary credentials.  It isn't just possible, but actually fairly likely, that credentials will expire while holding the state lock.  If they expire between updating state from the s3 bucket and finishing applying changes, you'll get partial resources deployed AND a permanently locked state lock. But given that it takes a while to update state from S3, I have found that it tends to expire while updating local state from remote, but that still leaves the lock locked. It would be very good, if such a capability exists, to check whether credentials are going to expire within x minutes and don't allow terragrunt to start running a command.  X can probably be the same value as the lock timeout flag, or it could be explicitly set in the config.  But having had this happen to me twice in just the first day since I started using terraform via federated user, it definitely needs some kind of protection.  

I'm pretty sure I saw somewhere that you can actually access the credential expiration time within a policy condition, so it may just be possible to deny access to anything if a credential doesn't have at least x minutes of life left, but it seems like it would be more flexible to implement that limit in terragrunt, so that different modules could be configured with different expiration limits, given the vast difference between application time for various modules - Elasticsearch takes 20 minutes, other modules take less than a minute.

**Comment by brikis98** [comment]
Shouldn't you file this bug against Terraform, not Terragrunt, since it's Terraform that does locking?

**Comment by sgendler-stem** [comment]
Yeah.  I'm not sure what I was thinking, actually.  Must have been tired.

**Comment by sgendler-stem** [comment]
Actually, I think I was thinking that, along with the MFA condition stuff in the iam_policies module, someone might want to think about adding a condition on credential validity expiration, too, in order to defend against unexpected loss of access in the midst of an apply or while holding the lock.

**Comment by brikis98** [comment]
Not sure you can have a policy that does that, as expired credentials will prob be rejected by AWS before it checks any policy. So I'd recommend opening this bug with Terraform!
