### ISSUE TITLE
How do I build terragrunt locally?

### ISSUE THREAD

**Issue by robinbowes** [gruntwork-io/terragrunt#398]
I'd like to do some debugging/hacking on terragrunt but can't see how I might build it locally.

Is this possible?

R.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt#developing-terragrunt

**Comment by robinbowes** [comment]
I get this error, which is clearly missing dependencies, but I don't know how to resolve:

```
  go run main.go plan
main.go:4:2: cannot find package "github.com/gruntwork-io/terragrunt/cli" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/gruntwork-io/terragrunt/cli (from $GOROOT)
	/Users/robin/Workspace/golang/src/github.com/gruntwork-io/terragrunt/cli (from $GOPATH)
main.go:5:2: cannot find package "github.com/gruntwork-io/terragrunt/errors" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/gruntwork-io/terragrunt/errors (from $GOROOT)
	/Users/robin/Workspace/golang/src/github.com/gruntwork-io/terragrunt/errors (from $GOPATH)
main.go:6:2: cannot find package "github.com/gruntwork-io/terragrunt/shell" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/gruntwork-io/terragrunt/shell (from $GOROOT)
	/Users/robin/Workspace/golang/src/github.com/gruntwork-io/terragrunt/shell (from $GOPATH)
main.go:7:2: cannot find package "github.com/gruntwork-io/terragrunt/util" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/gruntwork-io/terragrunt/util (from $GOROOT)
	/Users/robin/Workspace/golang/src/github.com/gruntwork-io/terragrunt/util (from $GOPATH)
```

**Comment by brikis98** [comment]
Did you run `glide install`?

**Comment by robinbowes** [comment]
Nope, it wasn't clear I needed to do that, but even having done  so I get the same error output.

**Comment by robinbowes** [comment]
(I'm new to go development, in case it wasn't obvious...)

**Comment by brikis98** [comment]
No worries, I appreciate the effort :)

Have you used Go before? Are you familiar with `GOPATH`?

**Comment by robinbowes** [comment]
I am aware that GOPATH must be set, and mine is set to: `/Users/robin/Workspace/golang`

I have terragrunt checked out to `/Users/robin/Workspace/terragrunt`

It seems that `glide install` is not installing the gruntwork libraries into `vendor/`:

```
  glide list
[WARN]	Package github.com/gruntwork-io/terragrunt/cli is not installed
[INFO]	Not found in vendor/: github.com/gruntwork-io/terragrunt/cli (1)
[WARN]	Package github.com/gruntwork-io/terragrunt/errors is not installed
[INFO]	Not found in vendor/: github.com/gruntwork-io/terragrunt/errors (1)
[WARN]	Package github.com/gruntwork-io/terragrunt/shell is not installed
[INFO]	Not found in vendor/: github.com/gruntwork-io/terragrunt/shell (1)
[WARN]	Package github.com/gruntwork-io/terragrunt/util is not installed
[INFO]	Not found in vendor/: github.com/gruntwork-io/terragrunt/util (1)
...
```

**Comment by robinbowes** [comment]
OK, I think I'm good - I needed to checkout this repo into `$GOPATH/src/github.com/gruntwork-io/terragrunt`. I can now build terragrunt.

**Comment by robinbowes** [comment]
I spoke too soon...

I can run `go build` or `go install` to create a new terragrunt binary, but it doesn't seem to contain the changes I've made to `configstack/stack.go`.

Do I need to do something special to get my changes to be included?

**Comment by brikis98** [comment]
Can you do `go run main.go` now?

**Comment by brikis98** [comment]
Also, check where you're running terragrunt from after `go build`. You might be picking it up from your default `PATH`, rather than where `go build` puts it, in which case you're just running an officially published version.

**Comment by robinbowes** [comment]
It's now working - might have been a stale hashed location.
