### ISSUE TITLE
Terragrunt destroy modules when deleted on Github

### ISSUE THREAD

**Issue by marcuswl345** [gruntwork-io/terragrunt#399]
Hi,

I'm very new to terraform and terragrunt.

When you deploy via terragrunt(with backend as local) state files are stored in a random under the .terragrunt folder. Can we change it so that terragrunt stores the state files where the terraform.tfstate files are located at?

I want to mirror how terraform stores the state files locally

Thank you

**Comment by brikis98** [comment]
>  I want to make it so that when a module/environment/folder is deleted from Github, it deletes the corresponding AWS environment. 

I'm not sure this workflow makes sense with Terraform. If you delete the code, then you can't run `terraform destroy`, as without that code, Terraform won't know what to destroy!

> When my pipeline triggers it pulls down the state files and places them into their corresponding folders.

Terraform does not download state files to disk (at least as over version 0.10.x or so); it only keeps them in memory. So again, it's not clear how this workflow is going to work.

**Comment by marcuswl345** [comment]
Hi @brikis98 

I have changed my question to reflect what I'm trying to do

**Comment by brikis98** [comment]
Can you use the [path](https://www.terraform.io/docs/backends/types/local.html#path) parameter with [get_tfvars_dir()](https://github.com/gruntwork-io/terragrunt#get_tfvars_dir)?

**Comment by marcuswl345** [comment]
That works. 

Thanks @brikis98
