### ISSUE TITLE
What strategies are people using to display human friendly terragrunt plan-all output ?

### ISSUE THREAD

**Issue by DGillespie** [gruntwork-io/terragrunt#400]
I'm thinking of running terraform plan-all from vsts and am a bit worried that the plan output can get messy if multiple modules have pending state modifications. The plans run concurrently and the output is interleaved. Another option is to run it with the option **-out $(pwd)/tfplan** (notice the $(pwd) otherwise the plan ends up in whatever working directory terragrunt uses in ~/.terragrunt/X/Y/). But even if i do this, i now have a bunch of tfplans, but no real way to display what's inside of them. I'd like to show what's inside of tfplans for approval in a manual step in vsts, as a first step towards CD.

I did not post this in Terraform, but if you think this is more appropriate there and off topic here, i'll move my post.

**Comment by brikis98** [comment]
Unfortunately, the output formatting for the `xxx-all` commands is not great, so `plan-all` needs some work before it's truly useful. Closing in favor of #74 and #78, to consolidate the discussion there.
