### ISSUE TITLE
--terragrunt-source doesn't work for terragrunt *-all commands

### ISSUE THREAD

**Issue by john-mcgowan-wowza** [gruntwork-io/terragrunt#406]
I'm not sure if this is something that should work or not. 

After messing around a lot and finally getting to the point where I can iterate quickly by using a `--terragrunt-source` cli param on my `terragrunt plan` and `apply` commands I ran into a stumbling block.

When I try to move up out of the directory with the module reference and run a `terragrunt plan-all` with a `--terragrunt-source` cli param that is identical to what I was running from with the module directory i get all kinds of errors.

I found that it was pretty tricky to come up with just the right value for `--terragrunt-source`  So now I'm wondering if it's even possible for me to do what I'm trying to do.

Can you run a `terragrunt plan-all` with `--terragrunt-source` so that ALL of the terragrunt module rules get their source from disk instead of git?

**Comment by brikis98** [comment]
Yes, that should be possible as of [v0.13.13](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.13.13). You typically set the `--terragrunt-source` param to the root of your modules directory when running the `xxx-all` commands. Terragrunt will parse the `source` parameter and use the part after the double-slash as a relative path to navigate to the relevant folder you specify via the `--terragrunt-source` param.

What errors are you seeing?

**Comment by john-mcgowan-wowza** [comment]
> What errors are you seeing?

General errors that would be caused by total failure to load the module.  Like for instance a missing backend declaration (which is defined in backend.tf) in my module.

Let me see if I can explain in more detail how my environment is setup.

I use `-tg` as a suffix for my "live" repo
```
infrastructure-tg
└── environments
    ├── global.tfvars
    ├── prod
    │   ├── environment.tfvars
    │   └── module1
    │       └── terraform.tfvars
    ├── qa
    │   ├── environment.tfvars
    │   ├── module2
    │   │   └── terraform.tfvars
    │   └── module1
    │       └── terraform.tfvars
    └── terraform.tfvars
```

And my `-modules` repo looks like this

```
infrastructure-tf
└── modules
    ├── module1
    │   ├── main.tf
    │   ├── s3-backend.tf
    │   └── variables.tf
    └── module2
        ├── main.tf
        ├── s3-backend.tf
        └── variables.tf
```

in the -tg repo the terragrunt/terraform/source looks like this...

```
source = "git::https://githostname/infrastructure-tf.git//modules/module1?ref=0.0.11"
```

I was able to use the --terragrunt-source cli param while inside of the module1 directory like this...

```
terragrunt plan --terragrunt-source /Users/username/Desktop/source/infrastructure-tf//modules/module1/
```

And it does just what I want it to do.  I can make changes to the -tf repo without commiting/tagging/pushing and updating the -tg repo.

But if I move up to a higher directory and try to run plan-all with the same value for terragrunt-source it doesn't work.  Like I said, it's as if it's just not loading the module at all.

I apologize for any typos above... the actual names of things have been obfuscated...  :)

**Comment by brikis98** [comment]
> But if I move up to a higher directory and try to run plan-all with the same value for terragrunt-source it doesn't work.

For the `xxx-all` commands, it shouldn't be the *same* value. It should be set to the root of your modules repo: 

```
terragrunt plan-all --terragrunt-source /Users/username/Desktop/source/infrastructure-tf
```

**Comment by john-mcgowan-wowza** [comment]
Thanks

Initially I was trying to do this with multiple environments using the same module.  I was able to successfully get plan-all to run from one directory up (for an entire environment) and higher for all environments using your suggestion.

Followup Question

Am I right in assuming that if I have a -live repo that references multiple modules from more than one module repo that I would NOT be able to use --terragrunt-source?

**Comment by john-mcgowan-wowza** [comment]
Another question.

I'm currious as to why the less specific path for `--terragrunt-source` doesn't work at the deeper level.  It's a little frustrating that our workflow will have to account for different levels of local development 

Thanks again.

**Comment by brikis98** [comment]
> Am I right in assuming that if I have a -live repo that references multiple modules from more than one module repo that I would NOT be able to use --terragrunt-source?

Correct. We don't currently have a way to support that.

> I'm currious as to why the less specific path for --terragrunt-source doesn't work at the deeper level. It's a little frustrating that our workflow will have to account for different levels of local development

That's a fair question. When we originally built Terragrunt, the *only* thing supported by `--terragrunt-source` was specifying the full path to the exact module you want to use. Later on, we added the ability to point to the module root for the `xxx-all` commands. I suppose it would make sense to allow you to use the module root with individual modules as well, but I never thought of it! PRs for that are welcome, though it would be nice to find a way to keep the behavior backwards compatible.
