### ISSUE TITLE
Working with multiple accounts

### ISSUE THREAD

**Issue by cfir** [gruntwork-io/terragrunt#413]
Hi,

I am trying to find a way to manage all remote state  (S3, Dynamo)of multiple accountd from my default profile in one account. and use  --terragrunt-iam-role to mange infrastructure in multiple accounts.

is there a way?

**Comment by brikis98** [comment]
First, I'll say that managing all the state/locks in one account is not recommended. Typically, the reason you use multiple accounts in the first place is isolation: that is, if you break something or someone breaks into one account, you want to reduce the odds that it can have any effect on the other accounts. By putting all the state in a single account, including any secrets stored in that state, you are reducing the isolation guarantees.

That said, if you really want to do it, there are two options:

1. Create the S3 bucket and DynamoDB table in one account, and then add IAM permissions that allow the IAM role you're using in other accounts to write to that bucket and table. 
1. In the s3 backend configuration, you can specify a [profile](https://www.terraform.io/docs/backends/types/s3.html#profile) or [role_arn](https://www.terraform.io/docs/backends/types/s3.html#role_arn) to use specifically for remote state + locking.

**Comment by cfir** [comment]
Understood tnx
