### ISSUE TITLE
terragrunt plan -refresh=true vs. terragrunt plan -refresh=false

### ISSUE THREAD

**Issue by boldandbusted** [gruntwork-io/terragrunt#414]
I don't know if this is a local issue, but I see dramatic differences in the plan output when I pass '-refresh=false' to  terragrunt plan.

Example, with -refresh=true (the default):

```
  + aws_iam_role_policy.[REDACTED]
      id:                                    <computed>
      name:                                  "[REDACTED]"
      policy:                                "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"s [REDACTED] }\n  ]\n}"
      role:                                  "${aws_iam_role.instance.id}"
```

vs.

```
  + aws_iam_role_policy.[REDACTED]
      id:                                                       <computed>
      name:                                                     "[REDACTED]
      policy:                                                   "${data.aws_iam_policy_document[REDACTED].json}"
      role:                                                     "${aws_iam_role.instance.id}"
```

and, I see data.* resources (used in the policies above) nicely broken out tabularly with '-refresh=false', but they are not shown when '-refresh=true', with " <= data.aws_iam_policy_document.logs_s3-write-only  [...]"

```
❯ terragrunt --version
terragrunt version v0.13.21
```
```
❯ terraform --version
Terraform v0.11.3
+ provider.aws v1.1.0
```

This is a cosmetic bug, but would be helpful to see the output nicely parsed and presented without disabling refresh. Thanks! Happy to provide more context.

**Comment by brikis98** [comment]
Hm, I'm not sure how Terragrunt would have an effect on this. Does it happen if you run `terraform` directly?

**Comment by boldandbusted** [comment]
@brikis98 Ah-ha! It happens with just bare terraform. So, I guess it is an upstream bug. Sorry about the noise. :/ Please close at will.

**Comment by brikis98** [comment]
No worries. Thanks for checking :)
