### ISSUE TITLE
Using Output from differnt module

### ISSUE THREAD

**Issue by cfir** [gruntwork-io/terragrunt#415]
Hi,

I did 2 environments live and module,

Module- 
     - network
     - components
     - general

live 
   qa |
        - component
                 - terraform.tfvars
        - general
                 - terraform.tfvars
        - network
                 - terraform.tfvars

I  am trying to get output from network to components and I am getting error because its different tfstate.

any advice?

**Comment by brikis98** [comment]
Use [terraform_remote_state](https://www.terraform.io/docs/providers/terraform/d/remote_state.html).
