### ISSUE TITLE
Terragrunt not applying any changes, even from new

### ISSUE THREAD

**Issue by hope4sun** [gruntwork-io/terragrunt#421]
Got a small issue, putting it down to user error at the moment =o, but been through this so many times and cannot see the what the issue is, I've created a folder structure the same as depicted in the https://github.com/gruntwork-io/terragrunt-infrastructure-live-example, so I have :

```
───terragrunt-infrastructure-live-example
    └────non-prod
    │            account.tfvars
    │            terraform.tfvars
    │
    └───us-east-1
        └───dev
            └───vpc
                    main.tf
                    terraform.tfvars
```

**account.tfvars**
```
tfstate_global_bucket        = "terragrunt-state-neph-non-prod"
tfstate_global_bucket_region = "eu-west-1"
```

**terraform.fvars**
```
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      encrypt        = true
      bucket         = "terragrunt-state-neph-non-prod"
      key            = "${path_relative_to_include()}/terraform.tfstate"
      region         = "eu-west-1"
      dynamodb_table = "terraform-locks"
    }
  }

  terraform {
    extra_arguments "bucket" {
      commands = ["${get_terraform_commands_that_need_vars()}"]
      optional_var_files = [
          "${get_tfvars_dir()}/${find_in_parent_folders("account.tfvars", "ignore")}"
      ]
    }
  }
}

```
**main.tf**
```
terraform {
  backend "s3" {}
}
```

**terraform.tfvars**
```
terragrunt = {
  terraform {
   source = "git::https://nephology.visualstudio.com/_git/Terraform%20Registry//vpc?ref=v1.0.0"
  }
}

 name = "Test VPC"
 cidr = "10.0.0.0/24"
```

The repo that this is pointing to, contains main.tf, vars.tf and outputs.tf from the Terraform Registry AWS  VPC (https://github.com/terraform-aws-modules/terraform-aws-vpc), Everything initialises ok but when I run Terragrunt plan-all from the Dev folder I get the following below, any help would be appreciated.

```
PS C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev> terragrunt plan-all
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev] 2018/02/26 07:56:22 Running command: terraform --version
[terragrunt] 2018/02/26 07:56:22 Stack at C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev:
  => Module C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev/vpc (dependencies: [])
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Module C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev/vpc must wait for 0 dependencies to finish
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Running module C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev/vpc now
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Reading Terragrunt config file at C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev/vpc/terraform.tfvars
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Terraform files in C:/Windows/Temp/terragrunt/hT3U9te49-oXHuEZzE7jBWByssQ/kzhRqx15LQydE1eYu3cUqCohybU/vpc are up to date. Will not download again.
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Copying files from C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc into C:/Windows/Temp/terragrunt/hT3U9te49-oXHuEZzE7jBWByssQ/kzhRqx15LQydE1eYu3cUqCohybU/vpc
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Setting working directory to C:/Windows/Temp/terragrunt/hT3U9te49-oXHuEZzE7jBWByssQ/kzhRqx15LQydE1eYu3cUqCohybU/vpc
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Backend s3 has not changed.
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:22 Running command: terraform plan -var-file=C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev/vpc/../../../account.tfvars
Acquiring state lock. This may take a few moments...
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
Releasing state lock. This may take a few moments...
[terragrunt] [C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev\vpc] 2018/02/26 07:56:28 Module C:/Users/Nephology/Documents/Terraform/terragrunt-infrastructure-live-example/non-prod/us-east-1/dev/vpc has finished successfully!
PS C:\Users\Nephology\Documents\Terraform\terragrunt-infrastructure-live-example\non-prod\us-east-1\dev>


```

**Comment by brikis98** [comment]
I'm a bit confused by the `main.tf` and `terraform.tfvars` under `us-east-1/dev/vpc`. The `main.tf` most likely should not be there. If it is, it will be copied into the tmp folder where `git::https://nephology.visualstudio.com/_git/Terraform%20Registry//vpc?ref=v1.0.0` is downloaded... Which will overwrite the original one that was there.

**Comment by josh-padnick** [comment]
This is a common issue, but I think the problem is that:

1. `main.tf` shouldn't be in the infra-live repo. The idea behind infra-live is that it's 100% versioned references to Terraform modules. That means it's all `terraform.tfvars` and `x.tfvars` files.

1. The `terraform.backend` block you've got in the `main.tf` should actually go in the `main.tf` of the module you're calling. We generally recommend a structure where code in the infra-live repo calls Terraform modules in the infra-modules repo, and code in the .

   That means, you'll need to fork the Terraform module you're referencing and add that block there. Better yet, create your other repo, infra-modules, which wraps the registry module. This way, you can put the `terraform.backend` block in there, and make a versioned reference to _that_ module. 

It can be a bit annoying to have 3 layers of calls, but we found that makes your infra the most maintainable long-term.

**Comment by josh-padnick** [comment]
Ah, race condition!

**Comment by hope4sun** [comment]
Ah thanks Yevgeniy and Josh, I must have read that Terragrunt read me so many times and just completely misread the section 

Filling in remote state settings with Terragrunt

To fill in the settings via Terragrunt, create a terraform.tfvars file in the root folder and in each of the Terraform modules:

├── terraform.tfvars
├── backend-app
│   ├── main.tf
│   └── terraform.tfvars
├── frontend-app
│   ├── main.tf
│   └── terraform.tfvars
├── mysql
│   ├── main.tf
│   └── terraform.tfvars
└── vpc
    ├── main.tf
    └── terraforrm


And of course when I was looking at the 
terragrunt-infrastructure-modules-example I didn’t see the config there, but makes total sense now about the main.tf overwriting the module =o

Stepping away from the problem it’s looks so obvious now, I really appreciate the guidance guys. 

Maybe worth an example in one of the repos at some point?
