### ISSUE TITLE
terragrunt does not use correct terraform version with asdf

### ISSUE THREAD

**Issue by tomdavidson** [gruntwork-io/terragrunt#423]
Incompatibility with version managers such as asdf. Some version managers use a version file placed in the project directory to "route" to the desired version. This is a great feature for terraform because one can jack their statefile by accidently using the incorrect version of terraform.  

Terragrunt copies the plan files into a temp dir  - but does not take the entire project's folder and thus leaves behind the version file.

In my case my project looks something like:

```
config/
--prod
--stage
src/
--mod1
--mod2
.tool-versions
```
When I am in the project root, the .tools-version file is found by asdf and the correct version of terraform is used. But terragrunt does not use the project root so the .tools-version file is ignored.

```sh
fred:~/Projects//devops-k8s$ TF_VAR_env=common terragrunt version --terragrunt-working-dir config/pq
[terragrunt] [config/pq] 2018/02/26 14:50:32 Running command: terraform --version
[terragrunt] 2018/02/26 14:50:33 Reading Terragrunt config file at config/pq/terraform.tfvars
[terragrunt] 2018/02/26 14:50:33 Cleaning up existing *.tf files in /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/Yt2vWexoGC1PpWmvq6SoZsknXjg
[terragrunt] 2018/02/26 14:50:33 Downloading Terraform configurations from file:///home/tom/Projects//devops-k8s/src into /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/Yt2vWexoGC1PpWmvq6SoZsknXjg using terraform init
[terragrunt] [config/pq] 2018/02/26 14:50:33 Backend s3 has not changed.
[terragrunt] [config/pq] 2018/02/26 14:50:34 Running command: terraform init -backend-config=encrypt=true -backend-config=key=tf-state/pq/terraform.tfstate -backend-config=region=us-west-2 -backend-config=bucket=devops-k8s-common-us-west-2-032474939542 -backend-config=dynamodb_table=devops-k8s-common-us-west-2-032474939542 -from-module=file:///home/tom/Projects//devops-k8s/src /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/Yt2vWexoGC1PpWmvq6SoZsknXjg
Copying configuration from "file:///home/tom/Projects//devops-k8s/src"...
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
[terragrunt] 2018/02/26 14:50:34 Copying files from config/pq into /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/Yt2vWexoGC1PpWmvq6SoZsknXjg/k8s/pq
[terragrunt] 2018/02/26 14:50:34 Setting working directory to /home/tom/.terragrunt/ua7-EfzAII6G9YWWzccOuwVZQds/Yt2vWexoGC1PpWmvq6SoZsknXjg/k8s/pq
[terragrunt] 2018/02/26 14:50:34 Running command: terraform version
**Terraform v0.11.2**
+ provider.aws v1.7.1
+ provider.template v1.0.0

Your version of Terraform is out of date! The latest version
is 0.11.3. You can update by downloading from www.terraform.io/downloads.html
fred:~/Projects//devops-k8s$ terraform version
**Terraform v0.10.8**

fred:~$ terraform version
**Terraform v0.11.2**
```

A work around could be to keep a .tools-version file into other folders so when terragrunt invokes terraform the expected version is used. 

_What folder does terragrunt execute terraform from ie where should I put the duplicate version file?_

It's the configs' folder right, not the source? such as `config\prod\.tool-versions`

**Comment by brikis98** [comment]
I'm probably missing something obvious, but it seems that `terraform --version` and `terragrunt --version` our outputting the same version (`v0.11.2`)? What behavior were you expecting?

**Comment by tomdavidson** [comment]
@brikis98 thank you for the super quick reply and I apologize for the op which I hope I have now fixed and answered your question.

**Comment by brikis98** [comment]
Ah, thanks for the clearer description. When you use the "remote configurations" functionality (i.e., by specifying `source = ...` in your Terragrunt config), Terragrunt: 

1. Copies the source into a temp folder
1. Copies files from the current working directory into that temp folder
1. Runs Terraform in that temp folder. 

The catch is that in step (2), [Terragrunt skips hidden files and folders](https://github.com/gruntwork-io/terragrunt/blob/b4776bf948c43c76c1b7886fa314d61da973b663/util/file.go#L146). 

Perhaps a good fix would be some sort of `include` / `exclude` setting that supports globs...

**Comment by tomdavidson** [comment]
Shoot, so my suggested workaround does not work at all and I already jacked one state file today. How are other terragrunt users managing terraform versions with multiple devs?

**Comment by brikis98** [comment]
We set a [required_version](https://www.terraform.io/docs/configuration/terraform.html#example) in all of our code.

**Comment by tomdavidson** [comment]
ahh just let the plan fail with terraform's check and dont worry about auto finding the right version.

What do you think of terragrunt passing in environment variables to the shell it executes terraform with? I am not thinking of a different case than this one and I would rather include the .files as you mentioned before.

```hcl
terragrunt = {
  env = {
      ASDF_TERRAFORM_VERSION = 0.10.8
  }
}
```

**Comment by brikis98** [comment]
> What do you think of terragrunt passing in environment variables to the shell it executes terraform with? 

https://github.com/gruntwork-io/terragrunt/issues/319

**Comment by brikis98** [comment]
Closing in favor of https://github.com/gruntwork-io/terragrunt/issues/394
