### ISSUE TITLE
"--terragrunt-non-interactive" doesnt work with terragrunt version v0.13.23

### ISSUE THREAD

**Issue by divakardevops** [gruntwork-io/terragrunt#427]
--terragrunt-non-interactive doesnt work with terragrunt version v0.13.23.

Below are the tried commands

`terragrunt apply --terragrunt-source <source path> --terragrunt-non-interactive`

`terragrunt apply --terragrunt-source <source path> --terragrunt-non-interactive=true`

`terragrunt apply --terragrunt-non-interactive --terragrunt-source <source path> `

`terragrunt apply --terragrunt-non-interactive=true --terragrunt-source <source path> `

Also tried by setting environment variable

`export TF_INPUT=false`

or 

`export TF_INPUT=0`

**Comment by brikis98** [comment]
Could you paste your log output?

**Comment by divakardevops** [comment]
I set the `TERRAGRUNT_DEBUG=true` and executed the command. Below is the output i received.

Note: We have Terraform v0.11.3

`[terragrunt] [/var/opt/hid/codecommit/deployment/terraform/tfs/environments/development/sismanager/environment-variables] 2018/03/02 05:56:23 Running command: terraform --version
[terragrunt] 2018/03/02 05:56:23 Reading Terragrunt config file at /var/opt/hid/codecommit/deployment/terraform/tfs/environments/development/sismanager/environment-variables/terraform.tfvars
[terragrunt] 2018/03/02 05:56:23 WARNING: no double-slash (//) found in source URL /var/opt/hid/codecommit/deployment/terraform/tfs/environments/modules/sismanager/environment-variables/. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2018/03/02 05:56:23 Cleaning up existing *.tf files in /home/ec2-user/.terragrunt/h08LaXBtSd-vu6PMOryC-pf4lfs/nvRpG2g-KOwoe4xnUrgzPtN5_fc
[terragrunt] 2018/03/02 05:56:23 Downloading Terraform configurations from file:///var/opt/hid/codecommit/deployment/terraform/tfs/environments/modules/sismanager/environment-variables into /home/ec2-user/.terragrunt/h08LaXBtSd-vu6PMOryC-pf4lfs/nvRpG2g-KOwoe4xnUrgzPtN5_fc using terraform init
[terragrunt] [/var/opt/hid/codecommit/deployment/terraform/tfs/environments/development/sismanager/environment-variables] 2018/03/02 05:56:23 Backend s3 has not changed.
[terragrunt] [/var/opt/hid/codecommit/deployment/terraform/tfs/environments/development/sismanager/environment-variables] 2018/03/02 05:56:23 Running command: terraform init -backend-config=region=us-east-1 -backend-config=encrypt=true -backend-config=dynamodb_table=tfstatedevlock_t -backend-config=profile=tftest -backend-config=bucket=sisp-dev-tfstate -backend-config=key=sismanager/environment-variables/terraform.tfstate -from-module=file:///var/opt/hid/codecommit/deployment/terraform/tfs/environments/modules/sismanager/environment-variables /home/ec2-user/.terragrunt/h08LaXBtSd-vu6PMOryC-pf4lfs/nvRpG2g-KOwoe4xnUrgzPtN5_fc
Copying configuration from "file:///var/opt/hid/codecommit/deployment/terraform/tfs/environments/modules/sismanager/environment-variables"...

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 1.10"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[terragrunt] 2018/03/02 05:56:24 Copying files from /var/opt/hid/codecommit/deployment/terraform/tfs/environments/development/sismanager/environment-variables into /home/ec2-user/.terragrunt/h08LaXBtSd-vu6PMOryC-pf4lfs/nvRpG2g-KOwoe4xnUrgzPtN5_fc
[terragrunt] 2018/03/02 05:56:24 Setting working directory to /home/ec2-user/.terragrunt/h08LaXBtSd-vu6PMOryC-pf4lfs/nvRpG2g-KOwoe4xnUrgzPtN5_fc
[terragrunt] 2018/03/02 05:56:24 Backend s3 has not changed.
[terragrunt] 2018/03/02 05:56:24 Running command: terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + aws_ssm_parameter.customer_ssm1
      id:        <computed>
      arn:       <computed>
      name:      "/application/sismanager/dev/1.0/FTRESS_DOMAIN_URL"
      overwrite: "true"
      type:      "SecureString"
      value:     <sensitive>


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: echo ^C[terragrunt] 2018/03/02 05:57:44 Forward signal interrupt to terraform`

**Comment by brikis98** [comment]
> Do you want to perform these actions?
> Terraform will perform the actions described above.
> Only 'yes' will be accepted to approve.

Ah, this is a new interactive check in Terraform 0.11. 

The original intent of the `--terragrunt-non-interactive` flag was to prevent *Terragrunt* from showing any interactive prompts (e.g., "Should I create this S3 bucket for you?"). We never thought about also disabling *Terraform's* interactive prompts.

I can see advantages to doing so, in that you have a single, simple flag to use, and disadvantages, in that Terraform's interactive prompts are designed to prevent painful, irreversible errors (e.g., `terragrunt destroy` also does an interactive check). FWIW, you can disable Terraform's checks with the `-auto-approve` flag and, given the potentially destructive nature of Terraform changes, I'm tempted to keep it that way so the user has to very explicitly skip these sorts of checks...

**Comment by divakardevops** [comment]
Thanks for the option `-auto-approve`. Can you please add the same in `README.md`. So it will help others. One issue i noticed is if i provide `-auto-approve`, then from next time it is executing with normal apply command `terragrunt apply --terragrunt-source /var/opt/hid/codecommit/deployment/terraform/tfs/environments/modules/sismanager/environment-variables`. How to get back to previous check state of terraform (the state executed without `-auto-approve`)?

**Comment by brikis98** [comment]
> Can you please add the same in README.md. So it will help others.

Good idea. Are you up for a quick PR? :)

> if i provide -auto-approve, then from next time it is executing with normal apply command terragrunt apply --terragrunt-source /var/opt/hid/codecommit/deployment/terraform/tfs/environments/modules/sismanager/environment-variables. How to get back to previous check state of terraform ( I mean the check state when command executed without -auto-approve?

Not sure I understand. Are you saying you ran:

```
terragrunt apply -auto-approve
```

And it applied automatically... And then you ran:

```
terragrunt apply
```

And it applied automatically again??

**Comment by divakardevops** [comment]
@brikis98  Thanks for accepting my suggestions. Created pull request https://github.com/gruntwork-io/terragrunt/pull/429 as you asked

And yes, you understood correctly. First i ran with -auto-approve and it applied. Then i ran without -auto-approve and it applied without asking for confirmation from terraform. So i am not sure whether this is due to terraform or terragrunt.

**Comment by brikis98** [comment]
> And yes, you understood correctly. First i ran with -auto-approve and it applied. Then i ran without -auto-approve and it applied without asking for confirmation from terraform. So i am not sure whether this is due to terraform or terragrunt.

I've never seen that before and am not sure what would cause it...

**Comment by brikis98** [comment]
If you can paste the full list of commands + log output, that might help to debug.

**Comment by divakardevops** [comment]
Sure. Will try to reproduce the usecase and update in few days.
