### ISSUE TITLE
plan files left behind in temp directories

### ISSUE THREAD

**Issue by ThisGuyCodes** [gruntwork-io/terragrunt#428]
I guess this is a feature request?

When I run terragrunt on a directory who's terraform.tfvars file contains a `source` directive:
```hcl
terragrunt = {
  terraform {
    source = "something"
  }
}
```

It first copies things out to a temp directory: this is known and expected behavior.

*However*, when this is used with `plan`, and an `-out=filename` is specified, this plan file generated is left in this temp folder. While the temp directory is output by terragrunt so I can go get it manually, this is difficult/laborious to build tooling around (particularly with `plan-all`).

It would be awesome if any generated plan file were copied/moved back to the original source directory :)

Or maybe there's another way to accomplish this? Some machine-parseable output of terragrunt with locations mayhaps? The main problem is it's inconsistent: if a terragrunt managed directory *doesn't* have a `source` directive, then the plan file is right there in the original directory, otherwise it's in the generated temp directory.

**Comment by brikis98** [comment]
I'm guessing this is because you are specifying a relative path for `-out`. Could you just use an absolute path? E.g., `-out=$(pwd)/filename`?

**Comment by ThisGuyCodes** [comment]
won't that result in all my plan files overwriting each other?

**Comment by brikis98** [comment]
It would behave no differently than if you used Terraform directly. If you specify the same filename for each file, then yes, of course they will overwrite each other. If you specify a different filename, then they won't.

**Comment by ThisGuyCodes** [comment]
so then specifying an absolute path won't give me access to all the plan files

**Comment by brikis98** [comment]
Not sure I follow. 

If you specify an absolute path, you can put the plan file wherever you want. For example, you can use `pwd` to put it into the director where your `.tfvars` files are, so it doesn't end up in a tmp folder:

```
$ cd ~/source/my-fancy-module
$ terragrunt plan -out=$(pwd)/plan-file-foo

(There will now be a plan file in ~/source/my-fancy-module/plan-file-foo)
```

Or you can use an arbitrary absolute path to put it wherever you want:

```
$ terragrunt plan -out=/foo/bar/plan-file-foo

(There will now be a plan file in /foo/bar/plan-file-foo)
```

You can then `apply` those plan files at a later time:

```
$ terraform apply ~/source/my-fancy-module/plan-file-foo
$ terraform apply /foo/bar/plan-file-foo
```

What's missing?

**Comment by ThisGuyCodes** [comment]
the part I'm trying to highlight is the usage of `plan-all`, if I `plan-all -out=$(pwd)/this.plan` then `pwd` is evaluated before `plan-all` and all the plan files overwrite each other

**Comment by brikis98** [comment]
Ah, I didn't realize you were referring to `plan-all` rather than `plan`. Thanks for clarifying.

In that case, using `pwd` would not work. Your best bet may be to try using [get_tfvars_dir](https://github.com/gruntwork-io/terragrunt#get_tfvars_dir) with [extra_arguments](https://github.com/gruntwork-io/terragrunt#keep-your-cli-flags-dry) for the `plan` and `plan-all` command, adding an arg along the lines of `-out=${get_tfvars_dir()}/myplan`.

**Comment by ThisGuyCodes** [comment]
excellent! I'd still love it if there was a way to do this from the command line: but since I can put it in my parent tfvars and inherit this solves the problem for my workflow
