### ISSUE TITLE
integration_test.go should generate the S3 bucket at runtime

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#43]
Currently, the bucket is hard-coded to an S3 bucket in the Gruntwork AWS account. This means no contributors can run the test without making (non-obvious) changes locally.

To fix this issue, the test should be updated to:
- Create a randomly named S3 Bucket
- Generate a new .terragrunt file with the new S3 Bucket Name
- Run the test
- Delete all files in the S3 Bucket
- Delete the S3 Bucket

**Comment by josh-padnick** [comment]
In the meantime, here's how you can manually validate the tests. I would make these changes locally but do *not* commit them:
- Update the [.terragrunt file](https://github.com/gruntwork-io/terragrunt/blob/master/test/fixture/.terragrunt#L17-L19) to specify an S3 Bucket you do have access to.
- Update the [const values](https://github.com/gruntwork-io/terragrunt/blob/master/test/integration_test.go#L19-L20) in `integration_test.go` with your S3 Bucket name and region.

If the tests pass, submit your PR, our CI job's tests should pass with the S3 bucket name as listed, and then we can merge.

**Comment by brikis98** [comment]
Fixed via #55.
