### ISSUE TITLE
[Question] Terragrunt not finding security group when applying security group rule

### ISSUE THREAD

**Issue by hawkesnc** [gruntwork-io/terragrunt#430]
Hi all,

When trying to run ```terragrunt plan-all``` in a security group folder, I run into an error saying: 
```* aws_security_group_rule.security_group_rule_self: Resource 'data.terraform_remote_state.security_group' does not have attribute 'security_group_id' for variable 'data.terraform_remote_state.security_group.security_group_id'```

Couple things to note:
- AWS
- I am using terraform_remote_state (S3 bucket)
- VPC has already been created
- Base and Rule are pulling their respective modules from a separate module repository
- Base Module is: ```resource aws_security_group```
- Rule Module is: ```resource aws_security_group_rule```
- My folder structure is as follows:

security_groups
|_ base
|_ rule

In the rule, I have also set a dependency that requires the base:
```
  dependencies {
    paths = [
      "../base"]
  }
```

In reference to outputting the variable into the root, I do have it:
```
output "security_group_id" {
  value = "${aws_security_group.security_group.id}"
}
```

I'm running the ```terragrunt plan-all``` in the 'security_groups' folder so it **should** plan the security group first and then the rule. 

Understandably, the error is because the security group does not yet exist in the S3 bucket. If I were to apply the security group base first, it does work.

If I were to do this with terraform normally, it would know that you need to apply the security group first before applying the rule. 

How do I make it so ```terragrunt plan-all``` will KNOW that the security group has to be created before the rule is applied even though the state is remote?

Is this an issue with remote_state or perhaps I'm misunderstanding how ```terragrunt plan-all``` works?

**Comment by brikis98** [comment]
`plan-all` only runs `terraform plan`. If some dependencies are not applied yet, the `plan` will fail. The `plan-all` command won't apply those for you, as that would obviously not be what's expected!

If you search the issues, we've had a discussion about an "interactive" `plan-all` command (or perhaps it needs another name?) that shows the plans for modules that are "leaves" (have all dependencies already applied), prompts you to `apply` them, and if successful, shows `plan` for the next set of modules, and so on. However, that's not currently implemented.

**Comment by hawkesnc** [comment]
@brikis98 thanks! That makes a lot more sense now. Basically it does an independent ```terraform plan``` on each folder and it's up to Terraform to determine the dependencies. 

I think my issue might also be more closely linked to: https://github.com/hashicorp/terraform/issues/12316
