### ISSUE TITLE
terragrunt plan-all with dependencies and terraform_remote_state

### ISSUE THREAD

**Issue by kristofferahl** [gruntwork-io/terragrunt#436]
Let's say we have the following modules:

- *modules/vpc*
- *modules/ecs*

If ecs module has a dependency on the vpc module you can specify a "dependecies" block to let terragrunt know in what order to execute them. Works fine so far. However...

If as suggested in issue #116 and #297, you use terraform_remote_state to get hold of vpc id from the vpc module, plan-all and apply-all will fail as the vpc module is yet to be created.

```bash
Error: Error running plan: 1 error(s) occurred:

* module.ecs_cluster.var.vpc_id: Resource 'data.terraform_remote_state.vpc' does not have attribute 'vpc_id' for variable 'data.terraform_remote_state.vpc.vpc_id'
```

If I apply only the vpc module first and then run plan-all, it works...

Am I doing something wrong here or is this simply not possible with terragrunt?

**Comment by brikis98** [comment]
Heh, see #435: two bugs on the same issue just minutes apart :)

See https://github.com/gruntwork-io/terragrunt/issues/435#issuecomment-372693578 for my response.
