### ISSUE TITLE
--terragrunt-source with multiple Terraform repos

### ISSUE THREAD

**Issue by jgiles** [gruntwork-io/terragrunt#444]
We re-use some Terraform modules wholesale directly from Terragrunt. By this I mean that we reference the same module directly in the `source` property of multiple tfvars files.

Within a particular Terragrunt repository in the style of https://github.com/gruntwork-io/terragrunt-infrastructure-live-example, we reference modules from multiple different repositories.

The trouble is that `--terragrunt-source` (invaluable for development) seems to replace *all* Terraform repo references with the designated location. That means that if you `apply-all` a set of modules that reference different repositories and use `--terragrunt-source`, you will get a mysterious error no matter what value you use:

```
Module <module> has finished with an error: Found remote_state settings in <module>/terraform.tfvars but no backend block in the Terraform code in /Users/joshuagiles/.terragrunt/epNnxeUeOdlhEvsmV-_VOwKd8eo/WF1Hr_gd9zZgsEpZFZfn_hiQBws/<module>. You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

terraform {
  backend "s3" {}
}
```

which is Terragrunt's way of saying it can't find any module code for <module> in that `--terragrunt-source`.

I would like to be able to specify either:

1. A list of values in `--terragrunt-source`, with each module resolving to the first source that contains a matching module and falling back to the original in the tfvars otherwise.
1. A map of source repos to local sources.

The second is more precise, but the first is probably much easier/more convenient.

**Comment by brikis98** [comment]
> Module <module> has finished with an error: Found remote_state settings in <module>/terraform.tfvars but no backend block in the Terraform code in /Users/joshuagiles/.terragrunt/epNnxeUeOdlhEvsmV-_VOwKd8eo/WF1Hr_gd9zZgsEpZFZfn_hiQBws/<module>. You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

Doh. This is an attempt at helping you avoid a frustrating & silent bug... But clearly it's covering up the _real_ issue, which is the module you want doesn't actually exist. We should have a separate bug to clean this up.

> A list of values in --terragrunt-source, with each module resolving to the first source that contains a matching module and falling back to the original in the tfvars otherwise.

This strikes me as potentially error prone.

> A map of source repos to local sources.

This feels like the right approach, but I can't think of a UX for it that wouldn't be clunky/verbose/frustrating.

Thought experiment: could we parse the `source` URLs to automatically figure it out?

Example:

```hcl
terragrunt = {
  terraform {
    source = "git::git@github.com:foo/repo1.git//bar"
  }
}
```

I imagine `repo1.git` would be checked out into a folder called `repo1` somewhere on your hard drive. If you had another `.tfvars` with `repo2.git`, that would presumably be checked out into a `repo2` folder on your computer. If all these folders were under a common parent folder, Terragrunt could figure it out, and you'd only need to point `--terragrunt-source` at that one parent folder...

**Comment by jgiles** [comment]
Pointing at a parent directory and saying all repos must live there would work.

It's a little inconvenient - it means you need to check out all the repos you are referencing locally (even third-party ones), and further to have them checked out in the same directory (I at least often have things checked out in an `organization/repo` structure).

But the UX here is tough, and doing a file-layout-based approach is probably more user-friendly than an arcane configuration spec. This approach will be unambiguous up until people have two Git repos with the same name, and when that happens the problem will be obvious rather than Terragrunt silently doing the wrong thing (which could happen in the list-of-sources approach).

So... would you want to put this in a new flag `--terragrunt-source-parent`, or just overload the behavior of the `--terragrunt-source` flag?

**Comment by brikis98** [comment]
> So... would you want to put this in a new flag --terragrunt-source-parent, or just overload the behavior of the --terragrunt-source flag?

Hm, good question.

Right now, the `--terragrunt-source` has two meanings:

1. When used with `xxx-all` (e.g., `apply-all`) commands, `--terragrunt-source` is assumed to be the parent folder of all the modules. Terragrunt parses the portion of the `source` URL that's after the double-slash and uses that as the relative path within `--terragrunt-source`.

1. When used with "normal" commands (e.g., `apply`), `--terragrunt-source` is assumed to be the actual path to where the module lives.

Perhaps we should just assume behavior (1) for all cases?

**Comment by brikis98** [comment]
Oh, sorry, just reread the description and remember the case described here is a third possibility where we want to point to the parent folder of the *repos* rather than the modules. `--terragrunt-source-parent` would certainly cover that, but feels a bit inelegant. 

I wonder if we could try an approach where `--terragrunt-source` starts at the current folder and sees if the name of that folder matches the folder name in the `source` param. If it does, we're done. If not, navigate down into the child folders and repeat the process?

**Comment by brikis98** [comment]
I think this is fixed via [`--terragrunt-source-map`](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-source-map).
