### ISSUE TITLE
pwd() interpolation helper

### ISSUE THREAD

**Issue by ebarault** [gruntwork-io/terragrunt#452]
hi,

Following the additions of hooks in terragrunt, I'm looking for a way to use the absolute location where the hooks are executed to manage substitutions of vars inside a *.tfvars file located right inside terragrunt's tmp dir.

Something like a `pwd()` helper.
Also, it might not be as easy to implement as given my understanding of terragrunt sequences, interpolations are resolved before copying files in the tmp dir?

How would you solve this?

**Comment by ebarault** [comment]
arff, in fact it won't work as all `*.tfvars` files are parsed by terragrunt before the hooks take place, so any modification i perform on files in the tmp dir by hooks are not used by terraform

**Comment by brikis98** [comment]
Agreed that a `get_working_dir()` helper would be useful.

> Also, it might not be as easy to implement as given my understanding of terragrunt sequences, interpolations are resolved before copying files in the tmp dir?

Yes, though we probably know what the tmp dir will be already.

**Comment by levkohimins** [comment]
Resolved in [v0.53.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.53.4) release.
