### ISSUE TITLE
Run hooks conditionally (based on OS type, for example)

### ISSUE THREAD

**Issue by antonbabenko** [gruntwork-io/terragrunt#463]
Using hooks in Terragrunt gives me almost all I can imagine, but I am looking for ways to be able to run them conditionally.

There are 2 use cases:
1. Run bash for Linux and PowerShell script for Windows (or even cygwin, which has different commands comparing to Linux)
2. Be able to enable or disable hook if Terraform variable or environment variable is set

Any ideas or workarounds?

**Comment by brikis98** [comment]
> Run bash for Linux and PowerShell script for Windows (or even cygwin, which has different commands comparing to Linux)

This use case makes a ton of sense, since the script itself can't do such a check, but Terragrunt could. A PR for this would be very welcome.

> Be able to enable or disable hook if Terraform variable or environment variable is set

Couldn't your script check for that env var and exit accordingly?

**Comment by brikis98** [comment]
This is now possible using conditionals and [`get_platform`](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#get_platform).

**Comment by ShabihZaidi** [comment]
@brikis98  Hey can you explain what do you mean by `conditionals`? I want to implement a `before_hook` based on an if condition but I couldn't find any way to do that.

**Comment by yorinasub17** [comment]
@ShabihZaidi you can do something like the following:

```hcl
    after_hook "copy_main_variables_on_windows" {
      # We shut off this hook by using an empty list here so that the hook is not triggered on any command when the running platform is not Windows.
      commands = get_platform() == "windows" ? ["init"] : []
      execute  = ["cp.bat", "main_variables.tf", "."]
    }

    after_hook "copy_main_variables_on_linux" {
      # We shut off this hook by using an empty list here so that the hook is not triggered on any command when the running platform is not Windows.
      commands = get_platform() != "windows" ? ["init"] : []
      execute  = ["cp.sh", "main_variables.tf", "."]
    }
```

**Comment by ShabihZaidi** [comment]
@yorinasub17 That was helpful. Thanks a lot! 👍
