### ISSUE TITLE
Pass env var to the `-var` but get error

### ISSUE THREAD

**Issue by mazzy89** [gruntwork-io/terragrunt#464]
I'm trying to pass an env variable to Terraform in this way:

```hcl
terraform {
    extra_arguments "custom_vars" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      arguments = [
        "-var",
        "aws_account_alias=${get_env("AWS_ACCOUNT_ALIAS")}",
      ]

      required_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("account.tfvars")}",
      ]
    }
  }
```

What I get as error is:

`[terragrunt] 2018/04/20 15:41:06 Invalid parameters. Expected syntax of the form '${get_env("env", "default")}', but got '"AWS_ACCOUNT_ALIAS"'`

Any idea of that?

**Comment by vas1468** [comment]
The answer is on your error message :) 
`Expected syntax of the form '${get_env("env", "default")}',`

You are missing the default.

So it should be like this if your AWS_ACCOUNT_ALIAS default is 'terraform' for example:

`terraform {
    extra_arguments "custom_vars" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      arguments = [
        "-var",
        "aws_account_alias=${get_env("AWS_ACCOUNT_ALIAS", "terraform")}",
      ]

      required_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("account.tfvars")}",
      ]
    }
  }`

**Comment by mazzy89** [comment]
so the DEFAULT is mandatory by design? Why?

**Comment by vas1468** [comment]
That's correct. 

Regarding the why , I am not a contributor. Just a dev soul with ops mind like you. :)

What is your case? why the default is a problem? answering that might help the contributors to see something that they have missed.

**Comment by brikis98** [comment]
Yes, DEFAULT is mandatory. You can set it to an empty string if you want.

**Comment by mazzy89** [comment]
I understand. Thank you all.
