### ISSUE TITLE
Terragrunt checks for S3 bucket before Token expiration

### ISSUE THREAD

**Issue by ddriddle** [gruntwork-io/terragrunt#476]
When I run `terragrunt plan` with an expired STS token I receive the following error message:
```
$ terragrunt plan
...
[terragrunt] [...] 2018/05/09 09:38:18 Initializing remote state for the s3 backend
[terragrunt] [...] 2018/05/09 09:38:18 [terragrunt] [...]  Remote state S3 bucket uiuc-tech-services-as-test does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
n
[terragrunt] 2018/05/09 09:38:21 ExpiredToken: The provided token has expired.
	status code: 400, request id: 63148D3B92835921, host id: U1iG0SOUCecHsMcvpd8KpvWtL3eZCF08kZX73xB9+w3yNmt9UYQJ2NMMXozjU+sOcrJzSasjniY=
[terragrunt] 2018/05/09 09:38:21 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
Of course I expect to receive an error message but I think it is a bug that Terragrunt first does a lookup for the s3 bucket before failing. Is there anyway to perform the s3 lookup after the ExpiredToken check?

BTW I am running Terragrunt on Mac OS X 10.11.6:
```
$ terragrunt --version
terragrunt version v0.14.7
```

**Comment by brikis98** [comment]
Terragrunt never explicitly checks the token. Making the API call to the S3 bucket is what triggers the token check error, and Terragrunt is just printing that error out for you after.

**Comment by ddriddle** [comment]
@brikis98 Why does Terragrunt prompt me to create an S3 bucket before displaying the error message? It seems the prompt should be suppressed on error.

**Comment by ddriddle** [comment]
Please note in the above example I answered No to the prompt then I received the error about an expired token.

**Comment by brikis98** [comment]
Ah, good point, looks like the error checking is not fine grained enough. It's trying to see if your S3 bucket exists, and if not, ask if you want to create it. However, the check is probably treating all errors as "S3 bucket doesn't exist", whereas some, such as token expired, should be treated differently.

**Comment by brikis98** [comment]
PRs to fix that welcome. Probably a matter of an extra if statement.

**Comment by denis256** [comment]
Fix released in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.51.8
