### ISSUE TITLE
Question: Use terragrunt with other providers (Vmware/google...)

### ISSUE THREAD

**Issue by goseeped** [gruntwork-io/terragrunt#480]
Can we use vmware/vcenter, opennevula or google clould  providers with terragrunt?

If that's the case how? where to place providers info? 

I failed to find information or code example! 

Thanks in advance

**Comment by goseeped** [comment]
Thanks for your quick response, 

So it is still possible to use the advantage of S3 backend for the state and lock and at the same time deploy on Vmware/google? there is not theoretical class there? 

Thanks,

**Comment by brikis98** [comment]
Your choice of `backend` and the `provider(s)` you use for resources are independent decisions. The most common thing is to use the same cloud for both (e.g., [S3 + AWS](https://www.terraform.io/docs/backends/types/s3.html), or [GCS + GCP](https://www.terraform.io/docs/backends/types/gcs.html)), but you can mix and match if you wish.

**Comment by brikis98** [comment]
No prob!
