### ISSUE TITLE
Tagging for DynamoDB table and S3 Bucket

### ISSUE THREAD

**Issue by BernhardBln** [gruntwork-io/terragrunt#487]
Wonderful that terragrunt creates the DynamoDB table and the S3 bucket for us, but it would be very cool if we could pass on some tags to add to both, as we have to tag all our resources and it's difficult to tag them later when they already exist.

Ideally it could look like this:

```
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket         = "my-terraform-state"
      key            = "${path_relative_to_include()}/terraform.tfstate"
      region         = "us-east-1"
      encrypt        = true
      dynamodb_table = "my-lock-table"

      s3_bucket_tags = {
            owner = "team a"
            name = "Terraform state storage"
      }

      dynamotable_tags = {
            owner = "team a"
            name = "Terraform lock table"
      }
    }
  }
}
```

You could use these two maps internally when creating bucket / table; I guess you need to filter them out though when passing them on to terraform?

**Comment by brikis98** [comment]
Neat idea. I'd be open to a PR that adds this! We may want to keep the tag configurations outside of the `config` block so we don't have to filter them.

**Comment by BernhardBln** [comment]
Haha, well, my first thought was "that'll be easy to add", the second "oh no it's go..." :P 

But I can give it a try. 

But where would you suggest to place the tags, @brikis98? To me it feels artificial to place them outside of remote_state (or even outside of config), that's why I thought filtering would make more sense?

**Comment by brikis98** [comment]
I'd probably put tags in `remote_state`, but not in `config`.

**Comment by BernhardBln** [comment]
Alright, so I will try with

```
terragrunt = {

  remote_state {

    backend = "s3"

    config {
      bucket         = "my-terraform-state"
      key            = "${path_relative_to_include()}/terraform.tfstate"
      region         = "us-east-1"
      encrypt        = true
      dynamodb_table = "my-lock-table"
    }

    s3_bucket_tags = {
          owner = "team a"
          name = "Terraform state storage"
    }

    dynamotable_tags = {
          owner = "team a"
          name = "Terraform lock table"
    }

  }
}
```

**Comment by brikis98** [comment]
Sounds good!

**Comment by BernhardBln** [comment]
Please take a look: https://github.com/gruntwork-io/terragrunt/pull/488

**Comment by BernhardBln** [comment]
Fixed, see https://github.com/gruntwork-io/terragrunt/releases/tag/v0.14.11
