### ISSUE TITLE
Terragrunt lock region selection ignores AWS_REGION environment variable

### ISSUE THREAD

**Issue by davidski** [gruntwork-io/terragrunt#49]
Following up from https://github.com/gruntwork-io/terragrunt/issues/48#issuecomment-260013994, the `lock` section of the `.terragrunt` config file allows the user to specify a region. Failing to specify a region uses a hard-coded default of `us-east-1`. The Go SDK supports the AWS standard AWS_REGION environment variable. Not honoring this setting violates the POLA. :wink:

Suggested order of priority:

1. region value from .terragrunt
2. AWS_REGION environment variable
3. Fall back us-east-1 region

Thanks for the great tool!

**Comment by brikis98** [comment]
Thanks for filing! Any interest in submitting a PR? It should be a pretty straightforward change.

**Comment by davidski** [comment]
I currently don't work with Go at all. :frowning_face: While it's on my To Do list, I'm hoping someone else picks this up before then.

**Comment by brikis98** [comment]
No worries! We'll see if we can get to this in the next week or two.

**Comment by kwilczynski** [comment]
This is a simple addition, but here is one question (more about the desired behaviour): given the `AWS_REGION` environment variable present, should it also override any other place where a region is concerned? For example...

The lock backend (e.g. DynamoDB) can take the desired region from the configuration, but when it goes to the remote state handling, then it works by a virtue of passing arguments to Terraform from the `config` section of the `backend` section in the configuration file (these are passed as-is as formatted key-value items). Should the `aws_region` be overridden here too?

**Comment by davidski** [comment]
Hey there, @kwilczynski. If I'm following this correctly, if the user enters a `remote_state:bucket:region` setting, that value (and not the environment value) should be used just as it is today. Manually coded values in a conf file should always override default environment variables.

**Comment by kwilczynski** [comment]
@davidski hi there! Sorry for not being clear enough, my bad. Although, you have answered my question, thank you!

**Comment by brikis98** [comment]
Since Terraform now natively supports locking, Terragrunt no longer has locking built in, so I think this issue can be closed.
