### ISSUE TITLE
How to upgrade Terraform provider plugins and modules

### ISSUE THREAD

**Issue by rafilkmp3** [gruntwork-io/terragrunt#490]
Hi, 

there is any way to make the terragrunt update the plugins and modules like i can do with ?
```
terraform init -upgrade
terraform get -update
```

but I would like to do like a get-all instead remove /home/user/.terragrunt to get the latest aws provider to all my modules

**Comment by brikis98** [comment]
You can certainly run `terragrunt get -update` or `terragrunt init -upgrade`. There is no `init-all` or `get-all` command currently though.

**Comment by JSC0DE** [comment]
A workaround could be to place this hook Inside your terragrunt.hcl file to run it each time you run terragrunt plan/plan-all or apply/apply-all

`terraform {
  // This runs before every apply or plan to download the lastest modules
  before_hook "update_mods" {
    commands = ["apply", "plan"]
    execute  = ["terraform", "get", "-update"]
  }
}`

Useful link https://terragrunt.gruntwork.io/docs/features/before-and-after-hooks/

**Comment by yorinasub17** [comment]
In addition to the workarounds mentioned above, we also now have [run-all](https://terragrunt.gruntwork.io/docs/reference/cli-options/#run-all) so you can run `terraform run-all init -upgrade`.

Closing as the question has been solved and stale. Please open a new issue if this is still relevant to you!

**Comment by DayoOyeyemi** [comment]
Hi all 
I get this Error: Failed to load state: unsupported checkable object kind "var" when i run terragrunt-run-all apply, this is stack specific as it was fine with other stacks, am using (terraform version  1.3.7 & terragrunt version 0.53.1) please help 

![state lock issue](https://github.com/gruntwork-io/terragrunt/assets/131254967/798a9348-dd9f-4251-a17d-b15ce5ed7d6a)
