### ISSUE TITLE
Add support for a generic xxx-all command

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#492]
Right now, Terragrunt allows you to execute a few specific Terraform commands—`plan`, `apply`, `destroy`, `output`—on "all" submodules. However, we often want to add another `xxx-all` command to the mix, and doing so manually each time is hard to maintain.

Perhaps what we need instead is to add support for a `--terragrunt-all` flag that takes the normal Terraform command you're running and applies it to all submodules. For example:

```
terragrunt apply --terragrunt-all
```

This would be equivalent to the current `terragrunt apply-all`. However, you could also use it with commands that are not yet supported and any commands that come out in the future:

```
terragrunt  get --terragrunt-all
```

The only gotcha is we'd probably need a way to specify the dependency "order." That is, for `apply-all`, dependencies are processed in one direction, but for `destroy-all`, they go in the other order. So probably we'd want an optional `--terragrunt-all-reverse` flag:

```
terragrunt apply --terragrunt-all
terragrunt destroy --terragrunt-all-reverse
```

**Comment by troylar** [comment]
@brikis98 Starting on this one  . . .

**Comment by collinstevens** [comment]
@troylar did you get anywhere with this?

**Comment by yorinasub17** [comment]
This is now implemented as `run-all` introduced in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.28.1
