### ISSUE TITLE
terragrunt's --assume-role option and sts token expiration in terraform (default one hour duration)

### ISSUE THREAD

**Issue by ebarault** [gruntwork-io/terragrunt#495]
Hi, 

Not a new subject but I regularly get caught by the default 1-hour sts token duration retrieved through the aws sts assume-role method called by terragrunt when running with the `--terragrunt-iam-role` option.

As I implement AWS multi-account setup, dedicating one account to aws iam users management and other accounts to segregate aws resources, i need to run terragrunt with the  `--terragrunt-iam-role`  option to jump in the right environments with temporary tokens.

The problem occurs when running very long terraform tasks such as restoring an rds aurora cluster from a backup which can easily take several hours.

I'm under the impression that terragrunt calls the assume-role method without specifying the `duration-seconds` param which enables to extend the default 1-hour duration up to 12 hours.

Then, passed 1 hour, terraform at some point fails with this error:
```
ExpiredToken: The provided token has expired
```

What would you think of letting terragrunt users specify the duration of sts tokens fetched by the `--terragrunt-iam-role` option to avoid breaching the token validity period?

---

**EDIT**: reviewing the code and the aws go provider, it seems that the default duration is set to 15 minutes, and I already am able to run with terragrunt terraform tasks longer than 15 minutes, so there might be something else already renewing the token, right?

---

**EDIT2**: instead of using the `--terragrunt-iam-role` option i manually endorsed the role using the `aws sts assume-role` function, setting the token duration to 4 hours, and all went flawlessly when using the terragrunt's option failed each time. So i think it validates my proposal :-)

**Comment by srhopkins** [comment]
> EDIT: reviewing the code and the aws go provider, it seems that the default duration is set to 15 minutes, and I already am able to run with terragrunt terraform tasks longer than 15 minutes, so there might be something else already renewing the token, right?

This could be the default duration set on the role https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_manage_modify.html#id_roles_modify_max-session
