### ISSUE TITLE
Terragrunt plan-all fails in case of dependencies

### ISSUE THREAD

**Issue by tdiwate** [gruntwork-io/terragrunt#496]
I have a vpc module and a security group module and the remote backend is configured in the root terraform.tfvars file.

The plan-all fails when I run terrgrunt plan-all for the first time as security group is dependent on vpc's id.
I understand why its failing, but I think it would be great if terragrunt identifies this dependency[which it already knows about in the dependencies field] and proceed with the plan instead of throwing 
```* aws_security_group.main_security_group: Resource 'data.terraform_remote_state.vpc' does not have attribute 'vpc_id' for variable 'data.terraform_remote_state.vpc.vpc_id' ```

**Comment by brikis98** [comment]
Duplicate of https://github.com/gruntwork-io/terragrunt/issues/435. 

> aws_security_group.main_security_group: Resource 'data.terraform_remote_state.vpc' does not have attribute 'vpc_id' for variable 'data.terraform_remote_state.vpc.vpc_id'

This isn't a Terragrunt error, but a Terraform error. If you have a dependency that hasn't been applied, there's no way for `plan` to succeed, as the data for that dependency doesn't exist!

**Comment by tdiwate** [comment]
sure, thanks for taking a look 👍
