### ISSUE TITLE
`dynamodb_table_tags` and `s3_bucket_tags` cause remote state to always reinitialize

### ISSUE THREAD

**Issue by tvald** [gruntwork-io/terragrunt#501]
#488 introduced the helpful fields `dynamodb_table_tags` and `s3_bucket_tags`. Unfortunately, they cause remote state to always reinitialize, since the fields that they set are not retained for comparison.

The log message is:
> Backend config has changed from map[bucket:my-bucket dynamodb_table:my-lock-table encrypt:true key:path/terraform.tfstate region:us-east-1] to map[dynamodb_table:my-lock-table s3_bucket_tags:[map[created_by:terragrunt name:Terraform remote state]] dynamodb_table_tags:[map[name:Terraform lock table created_by:terragrunt]] bucket:my-bucket key:path/terraform.tfstate region:us-east-1 encrypt:true]

For comparison, previous (as retrieved) and desired configuration:
```
map[bucket:my-bucket dynamodb_table:my-lock-table encrypt:true key:path/terraform.tfstate region:us-east-1]
map[bucket:my-bucket dynamodb_table:my-lock-table encrypt:true key:path/terraform.tfstate region:us-east-1 s3_bucket_tags:[map[created_by:terragrunt name:Terraform remote state]] dynamodb_table_tags:[map[name:Terraform lock table created_by:terragrunt]]]
```

For now, the workaround is to delete `dynamodb_table_tags` and `s3_bucket_tags` after first setting up remote state.

**Comment by brikis98** [comment]
Ah, good catch! Hopefully fixed in https://github.com/gruntwork-io/terragrunt/pull/502.

**Comment by brikis98** [comment]
New binaries should show up here soon: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.15.1
