### ISSUE TITLE
Locking on terraform refresh

### ISSUE THREAD

**Issue by marcoamorales** [gruntwork-io/terragrunt#51]
According to the [documentation](https://www.terraform.io/docs/commands/refresh.html):

> The terraform refresh command is used to reconcile the state Terraform knows about (via its state file) with the real-world infrastructure. This can be used to detect any drift from the last-known state, and to update the state file.
> 
> This does not modify infrastructure, but does modify the state file. If the state is changed, this may cause changes to occur during the next plan or apply.

If someone is running an apply with terragrunt, another user could run refresh and potentially write a broken state in s3.

**Comment by brikis98** [comment]
Ah, good catch. Is that a new command? Also, any interest in submitting a PR? This is probably a one-line change.

**Comment by marcoamorales** [comment]
@brikis98 sure thing, I've created a PR with the change 😄 , let me know if you have any feedback.
