### ISSUE TITLE
[question] Is there a definitive guide of Terragrunt to Terraform versions

### ISSUE THREAD

**Issue by jevon71-work** [gruntwork-io/terragrunt#510]
My company is using multiple versions of Terraform and it would be good to know which version of Terragrunt is best to use with a particular version of Terraform.  E.g. Terraform 0.8.x is best supported by Terragrunt 0.<something>.<something> etc.

Is this information documented somewhere already, or could it be added to the README?

**Comment by brikis98** [comment]
Good question. At the moment, the best we have is that the [release notes](https://github.com/gruntwork-io/terragrunt/releases) mention when we updated Terragrunt for some specific version of Terraform, but having to dig through all of that is painful, so we should definitely make it clearer in the README.

**Comment by brikis98** [comment]
We now have a compatibility table: https://terragrunt.gruntwork.io/docs/getting-started/supported-terraform-versions/
