### ISSUE TITLE
Write source modules to pwd

### ISSUE THREAD

**Issue by bendavies** [gruntwork-io/terragrunt#513]
It is often useful to have the source of the external modules in your IDE, for reading the docs, source completion etc...

It would be nice if terragrunt could optionally download source modules to `$(pwd)/.terragrunt` instead of `$HOME/.terragrunt`, to facilitate this.

**Comment by brikis98** [comment]
+1. This would make debugging much easier and make it clearer what's going on. I think it would also significantly simplify Terragrunt's caching logic, as there's no chance of overlap.
