### ISSUE TITLE
validate-all broken since v0.16.0

### ISSUE THREAD

**Issue by ldormoy** [gruntwork-io/terragrunt#517]
v0.16.0 creates a .terragrunt-cache directory.

When I run terragrunt validate-all, I get:
`10:51 $ terragrunt validate-all
[terragrunt] [/home/me/git/project/staging/eu-west-1/networking] 2018/07/10 10:51:50 Running command: terraform --version
[terragrunt] 2018/07/10 10:51:50 Error processing module at '/home/me/git/project/staging/eu-west-1/networking/.terragrunt-cache/K4mWZ7k7E85FwmjJeDdnsYYHZsQ/6PYnJZYoeYKyHmRAwweXnstOrvc/networking/terraform.tfvars'. How this module was found: Terragrunt config file found in a subdirectory of /home/me/git/project/staging/eu-west-1/networking. Underlying error: /home/me/git/project/staging/eu-west-1/networking/.terragrunt-cache/K4mWZ7k7E85FwmjJeDdnsYYHZsQ/6PYnJZYoeYKyHmRAwweXnstOrvc/networking/terraform.tfvars includes ../../../../terraform.tfvars, which itself includes ../../../../terraform.tfvars. Only one level of includes is allowed.
[terragrunt] 2018/07/10 10:51:50 Unable to determine underlying exit code, so Terragrunt will exit with error code 1`

Obviously the .terraform-cache subdirectory should be excluded.

**Comment by brikis98** [comment]
Ah, that's my bad. We run `plan-all` and `apply-all` in tests, so I'm not sure how that was missed! I'll try to get a fix out today. Thanks for reporting.

**Comment by brikis98** [comment]
Just pushed https://github.com/gruntwork-io/terragrunt/releases/tag/v0.16.1. New binaries should show up shortly. Let me know if that fixes the issue for you!

**Comment by ldormoy** [comment]
Nope, still happening.

I suppose your tests don't catch it because you delete the workspace/container between each run, so they never use the cache directory?

The first lines of plan-all:
```$ terragrunt plan-all
[terragrunt] [/home/me/git/project] 2018/07/10 15:54:43 Running command: terraform --version
[terragrunt] 2018/07/10 15:54:43 Module /home/me/git/project does not have an associated terraform configuration and will be skipped.
[terragrunt] 2018/07/10 15:54:43 Stack at /home/me/git/project:
  => Module /home/me/git/project/.terragrunt-cache/EJ89lfnC3wzv7EIMkTpcdLUdNrs/6PYnJZYoeYKyHmRAwweXnstOrvc/networking (dependencies: [])
  => Module /home/me/git/project/.terragrunt-cache/K4mWZ7k7E85FwmjJeDdnsYYHZsQ/6PYnJZYoeYKyHmRAwweXnstOrvc/networking (dependencies: [])
  => Module /home/me/git/project/dev/eu-west-1/networking (dependencies: [])
  => Module /home/me/git/project/staging/eu-west-1/networking (dependencies: [])
```

**Comment by brikis98** [comment]
Hm, that's perplexing. I'll look more into it tomorrow. Thx for the report.

**Comment by brikis98** [comment]
OK, let's try this one more time 😄 

https://github.com/gruntwork-io/terragrunt/releases/tag/v0.16.2

Binaries should be there in a few minutes.

**Comment by ldormoy** [comment]
Looks good now!

Thanks for the quick fixes @brikis98
