### ISSUE TITLE
New behavior of terragrunt-non-interactive option is still wrong

### ISSUE THREAD

**Issue by rnemec** [gruntwork-io/terragrunt#524]
Imagine having three modules:
* Common
* App1 (depends on Common)
* App2 (depends on Common)

I can run `terragrunt apply-all --terragrunt-non-interactive` at the root, or in the individual modules and all is well - the dependency info will guarantee that the shared module is setup when needed.

But when I'm trying to `destroy-all`, the old behavior (skip) was correct. It is **bad** to destroy Common when destroying App1, just because it is listed as a pre-req. This destroys the module Common that is still needed by the App2.

Probably the best thing to do would be changing the whole dependency login for apply vs destroy:
* in apply, offer applying in the module the current ones depend on
* in destroy, offer destroying modules that depend on current ones

That would be the best outcome - if I destroy Common, it would destroy App1 and App2, If I destroy App1, it will not touch App2 or Common.

Any thoughts or opinions appreciated.

**Comment by brikis98** [comment]
Good point. Destroy `Common` as the default option does seem like a bad idea. At the very least, I'd welcome a PR to update that confirmation dialog and invert it if the command being executed is `destroy` or `destroy-all`!

The second part of your suggestion sounds similar to #299, and I'd definitely welcome a PR for that.

**Comment by primeroz** [comment]
I am indeed having a very similar issue.

In general this changed the behavior from older version with no options to perform the same as before.

Running `destroy-all --terragrunt-non-interactive` meant that the dependencies modules were skipped
now it means that they will instead be destroyed.

We need an option to still skip dependencies, while performing a non-interactive ( always answer yes ) run

**Comment by brikis98** [comment]
As of https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.27, you now can use `--terragrunt-include-external-dependencies` or `--terragrunt-exclude-external-dependencies` to either automatically include all or exclude all dependencies without any prompt.
