### ISSUE TITLE
infrastructure modules and duplication

### ISSUE THREAD

**Issue by dtirer** [gruntwork-io/terragrunt#529]
After reading through the [best practices thread](https://github.com/gruntwork-io/terragrunt/issues/169) and looking through both the [live](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example) and [infrastructure modules](https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example) repos, my understanding is that the infrastructure modules should each represent a logical, domain-specific piece of your infrastructure -- ie backend-app, mysql.

However in my case, my application uses 3 different RDS instances.  My inclination is to make them 3 separate infrastructure modules so that i get isolated state for each.  However, to a large degree, the configurations between these 3 modules would be the same and there would therefore be a good deal of duplication

How might I handle something like this in Terragrunt?

**Comment by mcalhoun** [comment]
Hi @dtirer I think defining each of the 3 RDS instances in separate modules, then the application that consumes them as a 4th (with the concept of 3 inputs for DB URLs, etc) makes perfect sense to me. That's the way I'd handle it.

**Comment by dtirer** [comment]
@mcalhoun just to clarify, I would have something like below, where each one is an entirely isolated configuration:

```
### live infrastructure

staging/
    mysql1/
    mysql2/
    mysql3/
production/
    mysql1/
        terrafrom.tfvars
    mysql2/
        terrafrom.tfvars
    mysql3/
        terrafrom.tfvars

### infrastructure modules
infrastructure_modules/
    mysql1/
         vars.tf
         main.tf
         output.tf
    mysql2/
         vars.tf
         main.tf
         output.tf
    mysql3/
         vars.tf
         main.tf
         output.tf
```

or were you suggesting something different?

**Comment by mcalhoun** [comment]
In `infrastructure_modules`, if you can make your module generic enough that it applies to all 3 databases with just some parameter variance (input variables), then you could have just 1 module, but your `infrastructure_live` would still appear as you've described.

**Comment by dtirer** [comment]
@mcalhoun yeah, that's something I was considering.  Though I wasn't sure if that defeated the intention of the infrastructure_modules as described in the best practices.  It then couples all of those databases to some degree

**Comment by mcalhoun** [comment]
Nope, it isn't in conflict with the intention at all. If you can make a generic module that meets your needs with just a few parameter variations, then you should. The composition is then done in the `infrastructure-live` layer.

**Comment by alanmcg** [comment]
Not 100% sure if this is the same kind of issue I am having, but will add a comment here in the hope that it is!

I want to have a completely generic "vpc" module (for example), that I can configure with environment specific tfvars files. Right now, the only thing stopping me is that in the module definition I have to have the resource name, it can't be set via the environments tfvars file (if it will be used elsewhere in the module, such as setting security groups that is). 

For example, module:
```
resource "aws_vpc" "vpc" {
  cidr_block = "${var.cidr_block}"
  tags {
      Name = "${var.name}"
      Role = "${var.role}"
  }
}
```
I would like to set the resource name with something like "${var.name}" but then I can't use that in my subnet generation as follows:

`resource "aws_subnet" "private" {
  count = "${var.private_subnet_count}"

  vpc_id     = "${aws_vpc.vpc.id}" #how can the vpc name be generic and allow to create multiple of the same module?`

**Comment by brikis98** [comment]
What do you mean by "resource name"? Do you mean `resource "aws_vpc" "foo"` that the `foo` should be configurable? If so, why?

**Comment by alanmcg** [comment]
Sorry my comment wasn't very clear, probably because I'm still a little confused about how terragrunt should be used :).

If I take creating instances as an example, I want one module called "awsinstance" or something, and then be able to reuse that to create many similar instances, is that how things are supposed to work? From what I can see, it seems like I would create a different "module" for each instance almost (like a "bastion host" module and a "webserver module", but that can't be right as it would defeat the purpose right?

> Do you mean that in resource "aws_vpc" "foo"

Yeah, because otherwise I can only have one instance of "foo", isn't that the case?

**Comment by brikis98** [comment]
> If I take creating instances as an example, I want one module called "awsinstance" or something, and then be able to reuse that to create many similar instances, is that how things are supposed to work? 

Yes, that's the idea. One way to do it is to create a separate `terraform.tfvars` files, in separate folders, to deploy each of these instances. That way, the state is stored separately for each one. Each `.tfvars` file only defines the parameters that differ between these instances (e.g., name tags, instance types), so it's as DRY as you can get it.

> Yeah, because otherwise I can only have one instance of "foo", isn't that the case?

You don't rename Terraform resources like that... You may want to go through our [terraform guide](https://blog.gruntwork.io/a-comprehensive-guide-to-terraform-b3d32832baca) to become more familiar with the language before jumping into Terragrunt.

**Comment by alanmcg** [comment]
Excellent advice, thanks :)

**Comment by yorinasub17** [comment]
Closing as it looks like the original question has been answered. Please open a new issue if that is not the case, or if there are any follow up questions. Thanks.
