### ISSUE TITLE
Update the README.md to explicit the expected partition key in the dynamodb table

### ISSUE THREAD

**Issue by n-my** [gruntwork-io/terragrunt#53]
I've created the dynamodb table with Terraform and I've naively set the partition key as "state_file_id".
Terragrunt would not work because the expected partition key is `StateFileId`. 

Let's update the README.md to make that explicit

**Comment by brikis98** [comment]
Is there a reason you were creating the table manually? Terragrunt should do it for you automatically if the table doesn't already exist.

**Comment by n-my** [comment]
To be honest I just didn't see Terragrunt would create the table but I like the idea of having 100% of my AWS resources to be terraformed.

In the README.md I would just replace

`2. Try to write an item to the terragrunt_locks table with state_file_id equal to the id specified in your .terragrunt file.`

with

`2. Try to write an item to the terragrunt_locks table with StateFileId equal to the state_file_id specified in your .terragrunt file.`

**Comment by brikis98** [comment]
Sure. Would you like to submit a PR for that?

**Comment by n-my** [comment]
Sure, I have submitted it.

**Comment by brikis98** [comment]
Fixed via #58.
