### ISSUE TITLE
Clearer documentation and examples in README.md

### ISSUE THREAD

**Issue by max-rocket-internet** [gruntwork-io/terragrunt#530]
Hi,
I think it's quite hard to understand what problem terragrunt solves given what is in the README.

For example, in the [motivation](https://github.com/gruntwork-io/terragrunt#motivation) section, there is a folder structure detailed that would simply never be used in real life. It also states "You can reduce the amount of copy paste using Terraform modules" but I think this would be the default approach anyway.

Do you think it would be better to detail a typical Terraform codebase example that uses modules for `mysql`, `vpc` and `app` that are shared between all environments and then show how terragrunt improves on this?

**Comment by brikis98** [comment]
Improvements for docs, motivation, etc are always very welcome. Were you thinking of README changes or actual sample repos?

> For example, in the motivation section, there is a folder structure detailed that would simply never be used in real life.

Having seen it many times in real life, I respectfully disagree 😄

**Comment by max-rocket-internet** [comment]
Hi @brikis98 !

Yes, I was thinking in the README. The use-case should be clear there before getting into the sample repos. But clearly I am simply not understanding the use-case!

> Having seen it many times in real life, I respectfully disagree 😄

OK fair enough but is this would be, IMO, a poor approach from the start. Am I wrong?

Another example, isn't this exactly what a normal Terraform module does? Maybe this was written before Terraform could source modules from github?

> Terragrunt has the ability to download remote Terraform configurations. The idea is that you define the Terraform code for your infrastructure just once, in a single repo, called, for example, modules.....This repo contains typical Terraform code, with one difference: anything in your code that should be different between environments should be exposed as an input variable

A third example...

> If your modules have dependencies between them—for example, you can't deploy the backend-app until MySQL and redis are deployed—you'll need to express those dependencies in your Terragrunt configuration

In current Terraform, if the output from one module is used in another module, the dependency is automatically known. e.g. vpc module will go first because the `vpc_id` will be used in the `security_groups` in the other modules. Even if the modules aren't related by variables and outputs, you can use `depends_on` for modules now anyway. Right?

Sorry, I don't mean to be annoying, I was just really intrigued by this project at first but when I looked into the details I couldn't really understand some fundamental aspects 🙂

**Comment by brikis98** [comment]
> OK fair enough but is this would be, IMO, a poor approach from the start. Am I wrong? Another example, isn't this exactly what a normal Terraform module does? Maybe this was written before Terraform could source modules from github?

From the Terragrunt docs:

> You can reduce the amount of copy paste using Terraform modules, but even the code to instantiate a module and set up input variables, output variables, providers, and remote state can still create a lot of maintenance overhead.

Yes, modules (as in, those you put in your Terraform code with the `module` keyword) reduce copy and paste, and we strongly recommend using them (in fact, we built an entire [Infrastructure as Code Library](https://gruntwork.io/infrastructure-as-code-library/) of modules), but if you want to use the same module across multiple environments (dev, qa, stage, prod, etc), it still requires a TON of copy and paste and boilerplate in the form of input variables, output variables, provider configurations, backend configurations, and so on.

> In current Terraform, if the output from one module is used in another module, the dependency is automatically known. e.g. vpc module will go first because the vpc_id will be used in the security_groups in the other modules. Even if the modules aren't related by variables and outputs, you can use depends_on for modules now anyway. Right?

"Module" is, unfortunately, a VERY overloaded word with many meanings. In this case, I don't mean the modules you use with the `module` keyword, but rather, separate folders where you run `terragrunt apply`.

**Comment by max-rocket-internet** [comment]
OK cool.

>  if you want to use the same module across multiple environments (dev, qa, stage, prod, etc)

This, to use the same module across environments, is almost the main point of using Terraform modules IMO. Or at least I thought it was. To maintain consistency. e.g. I wouldn't have separate Aurora cluster modules for staging and production, that kind of defeats the point.

Even after testing the `terragrunt-infrastructure-live-example` I am having trouble seeing the problem solved by Terragrunt when compared to a modern (and considered) Terraform codebase. I guess being able to apply to multiple separate Terraform codebases ("terragrunt modules" as you put it) would be cool though.

Thanks for taking the time to reply, @brikis98 🙂

**Comment by josh-padnick** [comment]
@max-rocket-internet Thanks for sharing your thoughts. I've heard the feedback that it's not obvious what problems Terragrunt solves from others, too, and as @brikis98 said, we could probably do a better job of answering this. Perhaps re-open this issue in the hopes that someone takes a stab at improved docs?

**Comment by max-rocket-internet** [comment]
2 similar/related issues:
https://github.com/gruntwork-io/terragrunt/issues/491
https://github.com/gruntwork-io/terragrunt/issues/529

**Comment by brikis98** [comment]
> Use a different example in the motivation section because in my experience one would never have a vpc separate from the resources inside it. They would be together in the same Terraform codebase sharing a single AWS provider.

We don't generally recommend that. The VPC configuration is something you probably deploy once and barely touch for months after. However, the apps you run in that VPC you may deploy 10x per day. If both are in the same module, then you are putting your VPC at risk 10x per day of a silly typo or other minor error. That's why most Terraform projects split things up into separate folders.

For more info, see:

https://blog.gruntwork.io/how-to-manage-terraform-state-28f5697e68fa
https://charity.wtf/2016/03/30/terraform-vpc-and-why-you-want-a-tfstate-file-per-env/

**Comment by brikis98** [comment]
> Disambiguate the word module or simply just use a different name for "terragrunt module". If you are a new comer to this repo but already use Terraform, then module means only one thing. In saying that though, I don't know a proper name for a "directory with terraform files in it". In our group I use the word "Terraform codebase" but I don't know if it's correct.

Sadly, "module" doesn't mean "one thing" in Terraform. _Everything_ in Terraform is technically called a module. If folder `foo` contains a `.tf` file, then `foo` is a module, whether you run `apply` directly in `foo` (in which case, `foo` is called the "root mdoule"), or use the `module` keyword to load `foo` in some other file. So the terminology is, unfortunately, very overloaded and confusing.

I'm open to some new terminology if you have suggestions.

**Comment by robinbowes** [comment]
> separate folders where you run terragrunt apply.

We've settled on the term `target` for this.

**Comment by lorengordon** [comment]
> separate folders where you run terragrunt apply.

`root` could work as a term on its own also. And has the benefit of clarifying the relationship to terraform.

**Comment by sebkouba** [comment]
I'm fairly new to Terraform and trying to wrap my head around what's being discussed here. I've tried to come up with my own explanation. Is this correct / helpful?
--
There are three concepts:
1. Terraform Modules
2. Terragrunt Components
3. Live Directory where Terraform Components are invoked

## 1. Terraform Module
Terraform Modules the way they exist outside Terragrunt World. Each Module for each environment needs to be specified including values that differ between environments, but also everything they have in common. What environments have in common is copy pasted.

## 2. Component 
Take a Terraform Module and expose anything in your code that should be different between environments as an input variable.

It is still a Terrafrom Module but we have prepared it for Terragrunt by exposing variables.
```
### modules/mysql/vars.tf

variable "name" {
  description = "The name of the DB"
}

variable "instance_class" {
  description = "The instance class of the DB (e.g. db.t2.micro)"
}

...
```
[Source](https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/blob/master/mysql/vars.tf)

## 3. Live Directory
Specify the environment specific Component Variables. Only terraform.tfvars live here. Only Terragrunt can handle this file.
```
### live/prod/mysql/terraform.tfvars

terragrunt = {
  terraform {
    source = "git::git@github.com:gruntwork-io/terragrunt-infrastructure-modules-example.git//mysql?ref=v0.0.1"
  }
}

name           = "mysql_prod"
instance_class = "db.t2.medium"
```
[Source](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/master/prod/us-east-1/prod/mysql/terraform.tfvars)


This means there is no need to copy what now lives inside of our Components between environments! Terragrunt pulls in the Component and feeds it with the environment specifics that we provided in live. Without Terragrunt the Component Code would have to be copied into its respective folder inside our live directories.

**Comment by brikis98** [comment]
@sebkouba Yes, that sounds about right.

**Comment by brikis98** [comment]
Terragrunt has a dedicated website now for docs: https://terragrunt.gruntwork.io/
