### ISSUE TITLE
Remote states variables in terraform.tfvars not taken into account

### ISSUE THREAD

**Issue by openl4m4** [gruntwork-io/terragrunt#533]
Hello,

I'm trying to clean up some code using Terragrunt using two cool features on the documentation :
- Keep your Terraform code DRY
- Keep your remote state configuration DRY

My issue is that my backend variables are not found somehow and I need to get them in interactive mode. Could you help me on this please ? 

Here is my file layout : 
```
# Tree
├── modules
│   ├── kkre-db
│   │   ├── main.tf
│   │   ├── mysql.tf
│   │   ├── outputs.tf
│   │   ├── Readme.md
│   │   ├── redis.tf
│   │   ├── terraform.tfvars
│   │   └── variables.tf
│   └── terraform.tfvars
├── states
│   ├── kkre-preprod-db
│   │   └── terraform.tfvars
│   └── kkre-prod-db
```

And here is the content of my files 
```
# modules/terraform.tfvars
terragrunt = {
  remote_state {
        backend = "azurerm"
        config {
            storage_account_name = "xxxx"
            container_name       = "terraform-state"
            key                  = "${path_relative_to_include()}/terraform.tfstate"
        }
    }
}   

# modules/kkre-db/terraform.tfvars
terragrunt = {
  include {
    path = "${find_in_parent_folders()}"
  }  
}

# modules/kkre-db/main.tf
provider "azurerm" {
  version = "1.11"
}

terraform {
  backend "azurerm" {}
}


# states/kkre-preprod-db/terraform.tfvars
terragrunt = {
  terraform {
    source = "../../modules/kkre-db"
  }
}
```

Here is the actual problem : 

```
# Error
states/kkre-preprod-db> terragrunt init

[terragrunt] [/home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db] 2018/08/03 17:30:50 Running command: terraform --version
[terragrunt] 2018/08/03 17:30:50 Reading Terragrunt config file at /home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db/terraform.tfvars
[terragrunt] 2018/08/03 17:30:50 WARNING: no double-slash (//) found in source URL /home/kin/projets/kokore/deploy/terraform/modules/kkre-db. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2018/08/03 17:30:50 Downloading Terraform configurations from file:///home/kin/projets/kokore/deploy/terraform/modules/kkre-db into /home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db/.terragrunt-cache/VPyAg63mFfVKYJJ23g4otSCE-jw/jvinjfQFr4gIxHq2foJ8_Ii4KiM using terraform init
[terragrunt] [/home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db] 2018/08/03 17:30:50 Running command: terraform init -from-module=file:///home/kin/projets/kokore/deploy/terraform/modules/kkre-db /home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db/.terragrunt-cache/VPyAg63mFfVKYJJ23g4otSCE-jw/jvinjfQFr4gIxHq2foJ8_Ii4KiM
Copying configuration from "file:///home/kin/projets/kokore/deploy/terraform/modules/kkre-db"...

Initializing the backend...
container_name
  The container name.

  Enter a value: 
```

Thanks a lot for your help. 

Kieran

**Comment by jevon71-work** [comment]
I actually have the same problem.  I have implememted a workaround (by duplicating the information in the Terragrunt terraform.tfvars), but there is a way tp read the values from existing files that exist in my Terraform codebase.  I just have not worked out how to do that yet in my use case.

**Comment by brikis98** [comment]
Why do you have a `terraform.tfvars` in `modules/kkre-db`? That will end up being overridden by the `terraform.tfvars` in `states`.

**Comment by jevon71-work** [comment]
Actually my problem is not quite the same.  I will open my own separate issue, after I have tried to fix this myself.  My problem is that I am attempting to introduce Terragrunt into my organisation, that up to now have been using vanilla Terraform and have actively avoided Terraform "wrappers".  I have an engineer who is building a "wrapper" using direnv, which has the potential to get very complicated very quickly.  I am atttempting to provide a side-by-side comparison so that our engineers can make an informed decision - roll our own or use yours.  Our Terraform targets have terraform.tfvars files in them and I would like Terragrunt to read in the information in those, rather than having to re-create the information in the tfvars file in the Terragrunt repository.  I am reviewing the `optional_var_files` setting to see if that can provide what I need.

**Comment by openl4m4** [comment]
Hello Brikis,

The idea was to follow the documentation about multiple modules having a root terraform.tfvars and a child one to not duplicate code. For now I just have only one module kkre-db but it will grow in the near future. 

Regarding the one in the state states/kkre-preprod-db, I still need to get them to source these modules and to store their remote state in Azure Storage with a dynamic name so that preprod & prod won't collide. 

Any way to do that ? I though I have followed the documentation correctly ? 

Thanks.

**Comment by openl4m4** [comment]
Ok so just to let you know, I tried to simplify things and removed the two terraform.tfvars in modules and kept only one terraform.tfvars in states/kkre-preprod-db/terraform.tfvars. 


```
terragrunt = {
  terraform {

    source = "../../modules/kkre-db"

    remote_state {
      backend = "azurerm"
      config {
        storage_account_name = "terraformstatekkre"
        container_name       = "terraform-state"
        key                  = "kkre-preprod-db.tfstate"
      }
    }

  }
}

redis_capacity     = 1
redis_family       = "C"
redis_sku_name     = "Standard"
redis_shard_count  = 0
redis_maxmemory_reserved = 50
redis_maxmemory_delta = 50
```

The module is well imported but the remote state is not applied as the state stays locally. Do you have any clue why this isn't working ? This is a pretty simple configuration and seems to be the way to do it, the only differences in the examples I followed was the use of s3 instead of azurerm as a backend. 

Thanks a lot for your help. 

Kieran

**Comment by jevon71-work** [comment]
Have you got a declaration of your backend in your terraform code?

````
# main.tf
terraform {
  # The configuration for this backend will be filled in by Terragrunt
  backend "s3" {}
}
````

**Comment by brikis98** [comment]
You must have the `backend "azurerm" { }` config in your `.tf` files.

**Comment by openl4m4** [comment]
Ok so I put it back a in main.cf inside the module and now it's like values from the only terraform.tfvars I posted 4 post above, are not taken into account : 

```
~/projets/kokore/deploy/terraform/states/kkre-preprod-db> terragrunt plan            <11:51:25
[terragrunt] [/home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db] 2018/08/07 11:51:27 Running command: terraform --version
[terragrunt] 2018/08/07 11:51:27 Reading Terragrunt config file at /home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db/terraform.tfvars
[terragrunt] 2018/08/07 11:51:27 WARNING: no double-slash (//) found in source URL /home/kin/projets/kokore/deploy/terraform/modules/kkre-db. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2018/08/07 11:51:27 Downloading Terraform configurations from file:///home/kin/projets/kokore/deploy/terraform/modules/kkre-db into /home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db/.terragrunt-cache/VPyAg63mFfVKYJJ23g4otSCE-jw/jvinjfQFr4gIxHq2foJ8_Ii4KiM using terraform init
[terragrunt] [/home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db] 2018/08/07 11:51:27 Running command: terraform init -from-module=file:///home/kin/projets/kokore/deploy/terraform/modules/kkre-db /home/kin/projets/kokore/deploy/terraform/states/kkre-preprod-db/.terragrunt-cache/VPyAg63mFfVKYJJ23g4otSCE-jw/jvinjfQFr4gIxHq2foJ8_Ii4KiM
Copying configuration from "file:///home/kin/projets/kokore/deploy/terraform/modules/kkre-db"...

Initializing the backend...
container_name
  The container name.

  Enter a value: 

key
  The blob key.

  Enter a value: 

storage_account_name
  The name of the storage account.

  Enter a value: 
```

**Comment by openl4m4** [comment]
Sorry for that mistake, it's totally working now !

Thanks a lot gents.
