### ISSUE TITLE
Read tfvars files that live in Terraform "targets"

### ISSUE THREAD

**Issue by jevon71-work** [gruntwork-io/terragrunt#536]
I am attempting to introduce Terragrunt to my current company, since I used it at my previous company and it solves some use cases we have.  In order to do this transitionally, I would like to be able to take existing Terraform codebases which call modules and have existing `terraform.tfvars` and use those as Terragrunt modules (Terraform "targets").

I would really like to not have to repeat the definitions of the variables, which are in those tfvars files, so I want to reference them using the required_var_files or optional_var_files.  The Terraform code gets pulled into the `.terragrunt-cache` so it should be possible, but the names of the folders get randomized before the second double-slash of the source call:

````
terraform {
  source = "git::ssh://git@gitlab.et-scm.com/tio-rap-london/rap-terraformcontrol-datalighthouse.git//nonprod-298478629542/common?ref=UpgradeTerraformVersion"
}
````

I've tried `get_tfvars_dir` and `get_parent_tfvars_dir` but they both reference the Terragrunt path and not the downloaded Terraform source code.  Any ideas?

**Comment by jevon71-work** [comment]
Upon further investigation, it looks like the tfvars file in the Terraform directory never makes it to the `.terragrunt-cache` directory.  Might this be because it is called `terraform.tfvars`, so anything in it is ignored because the Terragrunt tfvars file has the same name?

**Comment by brikis98** [comment]
The way Terragrunt works with remote configurations is:

1. Clone the code in the `source` param into the `.terragrunt-cache` folder.
1. Copy the `terraform.tfvars` in the current folder into the `.terragrunt-cache` folder (so Terraform automatically uses the variables in it).
1. Run you `terraform xxx` command in the `.terragrunt-cache` folder.

Step (2) is the issue you're hitting, as both files are called `terraform.tfvars`.

**Comment by jevon71-work** [comment]
It is indeed - thanks for the quick answer.  I am going to look at the implications to users still running vanilla Terraform, if the Terragrunt users change the name of the Terraform `terraform.tfvars` file to something else and then create documentation before closing this issue down.

**Comment by jevon71-work** [comment]
Okay, I have done some more testing and I am now a little stumped.  First I tried to use a symlink to create a copy of the Terraform `terraform.tfvars` file called `terragrunt-target.tfvars`.  I then attempted to get Terragrunt to read this as an optional var file:

````
terragrunt = {
  # Terragrunt will copy the Terraform configurations specified by the source parameter, along with any files in the
  # working directory, into a temporary folder, and execute your Terraform commands in that folder.
  terraform {
    source = "git::ssh://git@gitlab.et-scm.com/tio-rap-london/rap-terraformcontrol-datalighthouse.git//nonprod-298478629542/common?ref=UpgradeAccountBootstrap"

    extra_arguments "conditional_vars" {
      commands = [
        "apply",
        "plan",
        "import",
        "push",
        "refresh",
      ]

      required_var_files = [
        "terraform.tfvars",
      ]

      optional_var_files = [
        "terragrunt-target.tfvars",
      ]
    }
  }
````
When that didn't work, I just copied the file.  When that didn't work, I removed the hyphen.  What's confusing me is now the file is pulled into `.terragrunt-cache` into the working directory with everything else.  Reading the get_tfvars_dir command, it seems I should not use this and just specifying the file name should work.  But every time I do plan, I get this line:

`[terragrunt] 2018/08/10 02:04:58 Skipping var-file terragrunt.tfvars as it does not exist`

I'm clearly missing a trick here - can someone let me know which trick?

**Comment by brikis98** [comment]
Can you explain what you're trying to do?

**Comment by jevon71-work** [comment]
I am trying to not have to duplicate variable declarations which are defined for users of vanilla Terraform in the `terraform.tfvars` file that live in the source.  For example:

````
#----------------------------------------------------------
# Bootstrap Variables
#----------------------------------------------------------
bootstrap_account_alias = "aws-agrm-authorpages"
````

Because I am unable to read in the tfvars file, I have to duplicate that information in the Terragrunt `terraform.tfvars` file.  It's okay if there is no way around this - I can document the process.  But it looked like it would be possible.

My current workaround is to duplicate the information in the Terragrunt tfvars file.

**Comment by brikis98** [comment]
Where did you add the symlink?

**Comment by brikis98** [comment]
Terragrunt uses `terraform init -from-module=xxx` to copy the code from the source code repository `xxx`. So if the symlink didn't work, it's either because it doesn't work with your repo, or with Terraform (you can run the command manually to investigate).

I'd expect it to work properly once it's the `.tfvars` file is alongside the rest of your `.tf` files in `.terragrunt-cache`. If it's not, there may be some issue with relative paths... I believe the reason it doesn't is a bug in this line of code: https://github.com/gruntwork-io/terragrunt/blob/916bdfc815a17da9903c24781ccafcdbcc59efda/cli/args.go#L131. Instead of `util.FileExists(file)` it should probably be prepending `file` with the working dir (the folder in `.terragrunt-cache`). Without it, it's instead looking in the folder where you ran Terragrunt, which is not right. 

A PR to fix that would be very welcome. Moreover, a PR to add a `"${get_working_dir()}"` helper to avoid this ambiguity in the future would also be very welcome!

**Comment by jevon71-work** [comment]
My "Go-Fu" is non-existent, so it will be a while before I can create a fix.  Short-term I will document a workaround and when I have time, will try to work on a fix.  I reckon someone will probably be able to fix this long before I can, though.  Guess it depends on how many other people have attempted to use Terragrunt in this fashion and come across this issue...

**Comment by yorinasub17** [comment]
This should now be fixed since the change to use `terragrunt.hcl` instead of `terraform.tfvars` for Terragrunt configuration. Please open a new issue if that is not the case, with a new reproducible example. Thanks!
