### ISSUE TITLE
terraform.tfvars plan is failing to reference internal modules

### ISSUE THREAD

**Issue by venkat51286** [gruntwork-io/terragrunt#537]
I am running terragrunt plan --terragrunt-source ~/terraform-aws-rds and getting the below errors for every output referenced using internal module. Here is the module code https://github.com/terraform-aws-modules/terraform-aws-rds

Error: output 'this_db_parameter_group_arn': reference to undefined module "db_parameter_group"                                                              
Error: output 'this_db_option_group_arn': reference to undefined module "db_option_group"                                                                  
Error: output 'this_db_instance_endpoint': reference to undefined module "db_instance"

when I use terraform paln by using source as the module, plan works fine.
"Plan: 6 to add, 0 to change, 0 to destroy."

I am new to terragrunt and please help me

**Comment by brikis98** [comment]
Can you share your Terraform code (`.tf` files) and Terragrunt configuration (`terraform.tfvars`)?

**Comment by venkat51286** [comment]
Hi Jim, Thanks for your reply.  This is the structure I have

[root@ip-x-x-x-x grunt]# tree
.
├── dev
│   ├── terraform.tfvars
│   └── us-east-2
│       ├── psdb
│       │   ├── main.tf
│       │   └── terraform.tfvars
│       └── psweb
│           └── terraform.tfvars
└── README.md

[root@ip-x-x-x-x grunt]# cat dev/terraform.tfvars
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      encrypt        = true
      bucket         = "xxxxxxxxx"
      key            = "${path_relative_to_include()}/terraform.tfstate"
      region         = "us-east-1"
      dynamodb_table = "terraform-state-lock-dynamo"
    }
  }
  # Configure root level variables that all resources can inherit
  terraform {
    extra_arguments "bucket" {
      commands = ["${get_terraform_commands_that_need_vars()}"]
      optional_var_files = [
          "${get_tfvars_dir()}/${find_in_parent_folders("account.tfvars", "ignore")}"
      ]
    }
  }
}

[root@ip-x-x-x-x psdb]# cat terraform.tfvars
terragrunt = {
  terraform {
    #source = "https://github.com/terraform-aws-modules/terraform-aws-rds.git"
    source = "github.com/terraform-aws-modules/terraform-aws-rds.git"
  }

  include = {
    path = "${find_in_parent_folders()}"
  }
}

identifier = "dev-db"

engine            = "mysql"
engine_version    = "5.7.19"
instance_class    = "db.t2.large"
allocated_storage = 5

name     = "dev-db"
username = "user"
password = "xxxxxxxxxx"
port     = "3306"

vpc_security_group_ids = ["sg-xxxxx"]

maintenance_window = "Mon:00:00-Mon:03:00"
backup_window      = "03:00-06:00"

# Enhanced Monitoring - see example for details on how to create the role
# by yourself, in case you don't want to create it automatically
monitoring_interval = "30"
monitoring_role_name = "dev-db-role"
create_monitoring_role = true

tags = {
  Owner       = "user"
  Environment = "dev"
  App         = "xxxx"
}

# DB subnet group
subnet_ids = ["subnet-xxxx", "subnet-xxxx", "subnet-xxxx"]

# DB parameter group
family = "mysql5.7"

# DB option group
major_engine_version = "5.7"

# Snapshot name upon DB deletion
final_snapshot_identifier = "dev-db"

parameters = [
  {
    name = "character_set_client"
    value = "utf8"
  },
  {
    name = "character_set_server"
    value = "utf8"
  }
]

options = [
  {
    option_name = "MARIADB_AUDIT_PLUGIN"

    option_settings = [
      {
        name  = "SERVER_AUDIT_EVENTS"
        value = "CONNECT"
      },
      {
        name  = "SERVER_AUDIT_FILE_ROTATIONS"
        value = "37"
      },
    ]
  },
]

[root@ip-x-x-x-x psdb]# cat main.tf
terraform {
  # The configuration for this backend will be filled in by Terragrunt
  backend "s3" {}
}

**Comment by brikis98** [comment]
The problem is that you have a `main.tf` in `psdb`. When you run Terragrunt, it:

1. Downloads the code from the `source` param into a folder in `.terragrunt-cache`.
1. Copies the code from your working directory, including `main.tf`, into the same folder in `.terragrunt-cache`. This probably overrides the `main.tf` that's in the RDS module, but leaves the `outputs.tf` behind, which now is left with broken references.

Try renaming `psdb/main.tf` to, say, `psdb/backend.tf`.

**Comment by venkat51286** [comment]
@brikis98 That worked like a charm. Thanks for detailed explanation. It killed my 2 days but learned lesson :)
