### ISSUE TITLE
Relay module output to use TF remote_state data source

### ISSUE THREAD

**Issue by giuppo** [gruntwork-io/terragrunt#538]
Hi, 

In order to use terraform_remote_state, [TF documentation](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) suggests to 'relay' the module variable, 

```hcl
module "app" {
  source = "..."
}

output "app_value" {
  value = "${module.app.value}"
}
```

However, if I use a module terragrunt-sytle

```hcl
terragrunt = {
  terraform {
    source = "git::git@github.com:foo/modules.git//app?ref=v0.0.3"
  }
}
```

How can the relaying be done? 
Thanks

**Comment by brikis98** [comment]
Not sure I understand the question. If `app` has an output, it will show up as an output when you specify it in `source`...

**Comment by giuppo** [comment]
I need to output a resource value V from the stack I am creating using a module,
as I then need to use V in another stack (using the remote_state data source).                                                                                                                        

TF documentation says that 
> Only the root level outputs from the remote state are accessible...
> you must thread the output through to a root output.

so TF recommends to do as in the first fragment above.

When I use the module in the terragrunt block, it is not clear to me how 
to get the module name (app above) to define the output, i.e. what to assign instead of `module.app.value`.

**Comment by brikis98** [comment]
If you have:

```hcl
module "app" {
  source = "/foo/bar/app"
}

output "app_value" {
  value = "${module.app.app_value}"
}
```

Then with the following Terragrunt configuration:

```hcl
terragrunt = {
  terraform {
    source = "/foo/bar/app"
  }
}
```

Any outputs in `/foo/bar/app`, including `app_value`, will be outputted and stored in state as you expect. There's nothing else to do there and no need to relay anything.

**Comment by giuppo** [comment]
Great, thanks! :+1:
