### ISSUE TITLE
after_hook on init command executes twice

### ISSUE THREAD

**Issue by lorengordon** [gruntwork-io/terragrunt#539]
I like to use an `after_hook` on `init` to further reduce code duplication, usually at least copying a common or backend .tf file into the tmp dir, but this setup ends up executing the hook twice... once after `init -from-module` retrieves the source, and again after `init` executes to initalize modules, the backend, and plugins.

I really only need the hook to execute after retrieving the source. It's not too big a deal if all I'm doing is copying a file like this, but I have other less common use cases where I'm doing something more (rendering the .tf file using jinja 😭 ), where the duplication really slows things down.

Not too sure on the best approach to avoid this, but could maybe create new command-types recognized by the hooks. Such as `init-from-module` and `init-configure` or somesuch, to identify the different steps.

**Comment by brikis98** [comment]
Ah, you're right, we do run `init` twice... PR to fix this is welcome! `init-from-module` and `init` does seem like a reasonable solution.

**Comment by lorengordon** [comment]
Done, see https://github.com/gruntwork-io/terragrunt/pull/540.
