### ISSUE TITLE
terragrunt apply-all destroy-all logs not easy to read

### ISSUE THREAD

**Issue by maratsh** [gruntwork-io/terragrunt#541]
terragrunt apply-all destroy-all logs not easy to read because of an output of different modules is mixing. It's really hard to understand which error connects to which module.

**Comment by brikis98** [comment]
Agreed completely. We have two issues about this already, so I'll close this as a duplicate, but PRs to improve this are very welcome.

https://github.com/gruntwork-io/terragrunt/issues/74
https://github.com/gruntwork-io/terragrunt/issues/78
