### ISSUE TITLE
terragrunt processes content that's commented out in terraform.tfvars

### ISSUE THREAD

**Issue by kristwaa** [gruntwork-io/terragrunt#544]
In a top-level _terraform.tfvars_ file I had a statement to include a file:
```
terragrunt = {
  terraform {
    extra_arguments "variables" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      require_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("account.tfvars")}"
      ]
    }
  }
}
```

During development I decided I didn't need that file, so I simply commented it out adding a _#_-character in front of the line:
`#"${get_tfvars_dir()}/${find_in_parent_folders("account.tfvars")}"`

When running terragrunt, I got this error after deleting the file:
> terragrunt plan
> [terragrunt] [snip] 2018/08/17 13:43:50 Running command: terraform --version
>[terragrunt] 2018/08/17 13:43:50 Reading Terragrunt config file at snip/terraform.tfvars
>[terragrunt] 2018/08/17 13:43:50 Could not find a account.tfvars in any of the parent folders of snip. Cause: Traversed all the way to the root.
>[terragrunt] 2018/08/17 13:43:50 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

Removing the comment in _terraform.tfvars_ made the error go away, the same did adding the file back. To double check this wasn't a caching issue, I changed the file name inside the comment, I also moved the _find_in_parent_folder_ function call (still commented out) around but it kept being executed.

I'm confused, shouldn't lines that are commented out with _\#_ be ignored by terragrunt? :)

**Comment by jevon71-work** [comment]
I saw this happen in my Terragrunt code too - solved the same way by removing the commented code altogether.  Didn't think too much about it at the time...

**Comment by brikis98** [comment]
It's a bug. Terragrunt uses a lame regex to parse interpolations, and the regex doesn't respect comments. When we upgrade to HCL2, this will probably be fixed automatically.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.0 moves Terragrunt to the HCL2 parser instead of hacky regex, so this should no longer be an issue.
