### ISSUE TITLE
how to pass tf_vars in terraform.tfvars

### ISSUE THREAD

**Issue by venkat51286** [gruntwork-io/terragrunt#546]
In my terraform.tfvars for a RDS DB, I have 
```
db_user = "xxxx"
db_password = "xxxx"
```
db_user and db_password are from module. 

I want to use AWS SSM to get sensitive data so doing

```
# cat dev-db.sh
export TF_VAR_user=`aws ssm get-parameter --name "user" --with-decryption --query Parameter.Value --output text`
export TF_VAR_password=`aws ssm get-parameter --name "password" --with-decryption --query Parameter.Value --output text`
```

when I use `db_user = ${var.user}` it is failing with 
`[terragrunt] 2018/08/20 21:26:54 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${var.user}, ${var.password}'`

I saw your comment from another github issue that no variable interpolation is allowed in terraform.tfvars file. So how to pass the tf_var variables into my .tfvars file ? please point me if you have any work around.

Thanks

**Comment by josh-padnick** [comment]
We use environment variables to set Terraform variable values that are considered secrets. For example, setting `TF_VAR_db_password` in your environment will do the trick.

**Comment by venkat51286** [comment]
Thanks @josh-padnick. That helped us. I am closing the ticket.
