### ISSUE TITLE
Import does not seem to accept variables in parent folders

### ISSUE THREAD

**Issue by bkoochin** [gruntwork-io/terragrunt#547]
It is entirely possible that this is user error, but I am not able to import existing AWS resources using Terragrunt version 0.16.7. 

When I attempt to use 'terragrunt import aws_lb.exterallb someARNhere" I get an error referring to a variable that is set in a parent folder.

Error: provider.aws: 1:3: unknown variable accessed: var.aws_role in:
${var.aws_role}

Using 'terragrunt plan' or 'terragrunt apply' works correctly and processes the provider file without issue so there does not appear to be a problem with the Terragrunt configuration in my terraform.tfvars file. Setting aws_role = something in the local.tfvars does not have any effect, but if I set a default value in the aws_role variable block in the module then Terragrunt picks it up.

Is this an issue that anyone else has run into? What am I doing wrong here? Thanks.

**Comment by brikis98** [comment]
Are you using `extra_arguments` somewhere? And only using those with `plan` and `apply`?

**Comment by bkoochin** [comment]
Yes, the import command was missing from the extra_arguments list. Thanks so much for your time!
