### ISSUE TITLE
proper way of referencing resources between modules

### ISSUE THREAD

**Issue by venkat51286** [gruntwork-io/terragrunt#549]
I have 2 modules called ps-db-cluster and ps-web. I have dependency SG that connects DB and EC2 instances. 
In ps-db-cluster module
```
resource "aws_security_group" "vpc_rds_security_group" {
  name = "vpc_rds_security_group"
  description = "The security group that should be used for the RDS cluster instances"
  vpc_id = "${data.aws_vpc.selected_vpc.id}"
  tags {
    Name = "${var.environment_name}-${var.app_name}"
  }
}

resource "aws_security_group_rule" "outbound-webserver-rule" {
  type = "egress"
  from_port = "3306"
  to_port   = "3306"
  protocol  = "tcp"
  // here I am referencing other module resoource
  source_security_group_id = "${module.ps-web.web_ec2_security_group_id}"
  security_group_id = "${aws_security_group.vpc_rds_security_group.id}"
}
```
I am already exporting the SG ID of web_ec2_security_group_id in ps-web module
```
cat ps-web/outputs.tf
output "web_ec2_security_group_id" {
  value = "${aws_security_group.web_ec2_security_group.id}"
}
```
When I am trying to do terraform plan in live repo, it is failing with these errors.
```
Error: resource 'aws_security_group_rule.outbound-webserver-rule' config: unknown module referenced: ps-web
Error: resource 'aws_security_group_rule.outbound-webserver-rule' config: reference to undefined module "ps-web"
```
I am trying to use output of one module in another and it is failing. What is the proper way of referencing each other. Any help appreciated.

Thanks

**Comment by brikis98** [comment]
Are you deploying `ps-db-cluster` and `ps-web` separately? i.e., via different folders and separate calls to `terragrunt apply`? If so, then you can't have direct dependencies between them (`${module.foo.bar}`). Instead, you have to use something like [terraform_remote_state](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) in your `ps-db-cluster` module to look up the state written by your `ps-web` module.

**Comment by venkat51286** [comment]
Thanks @brikis98. That exactly what I wanted and it fixed it :)
