### ISSUE TITLE
How to run recursive terraform plan/apply in order across multiple directories

### ISSUE THREAD

**Issue by venkat51286** [gruntwork-io/terragrunt#550]
@brikis98 Hi Jim, you are very helpful to me in various questions. First of all thanks for all your help. 
I have various modules in my live repo as 
web, rds, efs, vpc
Each directory will create resources from a separate module and I have to do terraform apply in each and every directory. I want to do CI/CD for my enire terraform code so it will go through each directory and do plan/apply. 
1) How to do terraform plan/apply from one command 
2) How to specify the resources order. Let's say I want to run VPC first, then RDS, then web etc. How to run terraform to follow the order.

Please let me know the best practice to achieve this. Thanks again!

PS: I follow your "terraform up & running" book. Is there any new version coming with recent terraform version updates.

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt#execute-terraform-commands-on-multiple-modules-at-once

**Comment by BTBP** [comment]
updated link from the one above: [https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/](url)
