### ISSUE TITLE
brew install terragrunt referencing old version

### ISSUE THREAD

**Issue by userhas404d** [gruntwork-io/terragrunt#551]
The [current bottle](https://github.com/Homebrew/homebrew-core/blob/master/Formula/terragrunt.rb) for terragrunt is still referencing version 0.16.6.

No issues with a manual upgrade so this is more of a request for added convenience.

**Comment by brikis98** [comment]
It looks like kind committers in the community have done all the work to keep HomeBrew updated (see [commit history](https://github.com/Homebrew/homebrew-core/commits/master/Formula/terragrunt.rb)). If you're up for a quick PR, it is a [pretty small change](https://github.com/Homebrew/homebrew-core/commit/796c35a62d2a818decef07e62d0682b2f76adc44#diff-e533973dd2b8594e912a57ff81f37b95)!

**Comment by userhas404d** [comment]
nice, [added](https://github.com/Homebrew/homebrew-core/pull/31568)!

**Comment by brikis98** [comment]
Wonderful, thank you!
