### ISSUE TITLE
Install on Windows using chocolatey

### ISSUE THREAD

**Issue by thedrow** [gruntwork-io/terragrunt#554]
Chocolatey is a package manager for powershell.
terragrunt is unfortunately not available there yet.

If anyone feels their up for the task, the [documentation ](https://chocolatey.org/docs/create-packages) explains how to create new packages and upload them pretty well.

**Comment by montross50** [comment]
https://chocolatey.org/packages/terragrunt this seems to be done.

**Comment by brikis98** [comment]
Nice find!
