### ISSUE TITLE
Terragrunt stops on debug

### ISSUE THREAD

**Issue by thoregilk** [gruntwork-io/terragrunt#562]
If tf_log_path is set, it stops with versioning.

[terragrunt] [C:\GitHub\terragrunt-azure\solution-partner-dev] 2018/09/06 19:59:56 Running command: terraform --version
[terragrunt] 2018/09/06 19:59:56 exit status 1

**Comment by brikis98** [comment]
Can you show the full set of commands you're running? And what version of Terragrunt? I'm not able to reproduce. In fact, setting `TF_LOG_PATH` seems to have no effect for me...

**Comment by thoregilk** [comment]
Sorry, I had forgot to update this issue since yesterday.

The error message got more clear as I tested directly with terraform. 
I had set tf_log_path to the folder, and not the filename

```
Couldn't setup log output: open c:\log: is a directory
```

**Comment by brikis98** [comment]
Ah, OK, thx for following up. Should this issue be closed then?
