### ISSUE TITLE
Terragrunt does not support current S3 remote state configuration options

### ISSUE THREAD

**Issue by fosrias** [gruntwork-io/terragrunt#565]
Here are the current terraform options: https://github.com/hashicorp/terraform/blob/v0.11.8/backend/remote-state/s3/backend.go

Here are the supported options in Terragrunt: https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L33-L42

Terragrunt exclude lots of options including the new (and very useful one) `force_path_style` that I personally need.

@brikis98 Am I missing something? If not, are you open to a PR to fix this?

**Comment by brikis98** [comment]
Are you hitting an actual bug or limitation because of this?

IIRC, the arguments we parse explicitly are for internal Terragrunt usage. When calling `terraform init` to configure a backend, we [parse config as a plain old map](https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state.go#L13) and pass _all_ the config args to Terraform. So, the design should accommodate new args being added without Terragrunt having to know about them, though of course it's possible there's a bug in the implementation!

**Comment by fosrias** [comment]
Well, if that is how it is supposed to work, then it appears there is a bug. I am trying to use this with an s3 compatible object store that does not support the bucket being the first subdomain, but rather a path for the bucket.

The following is my config:

```
terragrunt = {
  remote_state {
    backend = "s3"
    config {
      bucket   = "terraform-state"
      key      = "mwf/${path_relative_to_include()}/terraform.tfstate"
      region   = "us-phoenix-1"
      encrypt  = true
      endpoint = "https://something.example.com"
      
      shared_credentials_file     = "..."
      skip_region_validation      = true
      skip_credentials_validation = true
      skip_requesting_account_id  = true
      skip_get_ec2_platforms      = true
      skip_metadata_api_check     = true
      force_path_style            = true
    }
  }
```
If I configure this in a Terraform file, it all works fine for `terraform init`. However, for `terragrunt init` I first noticed the `shared_credentials_file` was ignored. So, I just used the aws default location even though this is not for AWS. Once I fixed that, I started trying to make requests and got this output:
```
$  terragrunt init
terragrunt init      
                                                                                                                                                   
[terragrunt] [/.../identity] 2018/09/12 11:51:07 Running command: terraform --version
[terragrunt] 2018/09/12 11:51:07 Reading Terragrunt config file at /.../identity/terraform.tfvars
[terragrunt] 2018/09/12 11:51:07 Initializing remote state for the s3 backend
[terragrunt] 2018/09/12 11:51:08 [terragrunt]  Remote state S3 bucket terraform-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
y
[terragrunt] 2018/09/12 11:51:12 Creating S3 bucket terraform-state
[terragrunt] 2018/09/12 11:51:13 RequestError: send request failed
caused by: Put https://something.example.com/: x509: certificate is valid for *.example.com, not terraform-state.something.example.com
[terragrunt] 2018/09/12 11:51:13 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```
So it is completely ignoring the `force_path_style` setting as well and adding the bucket as a subdomain. I can only assume that it is missing all of them from this. Again, if I configure this directly in terraform, it all works.

Others have mentioned they had to use `extra_arguments` and `-backend-config` to get around this. I have not got that approach working yet, but it seems the config above should work (in principle based on your comment).

**Comment by fosrias** [comment]
terragrunt version v0.16.7, BTW.

**Comment by fosrias** [comment]
And one more bit of info that might be relevant. This is using a third-party provider in the ~/.terraform.d/plugins directory.

**Comment by fosrias** [comment]
So, I don't think this can be solved on the terragrunt side as I suspect that the bucket URI structure for s3 compatible APIs is implemented in the non-aws s3 providers. Could be anything, right (I have not checked if there is a terraform standard for that though).

It seems to me that the only way that terragrunt can work with `force_path_style = true` in the absence of such a standard is that when that is set, terragrunt does not try to create or verify the bucket. It just passes the configuration on to terraform. 

So, I think this is probably more a limitation than a bug. Not sure the ramifications of terragrunt skipping its init calls to the remote bucket, but if that possible, could be an relatively straightforward fix. 

Any way to turn that off with some envar or config now to check?

**Comment by brikis98** [comment]
> [terragrunt] 2018/09/12 11:51:13 RequestError: send request failed
> caused by: Put https://terraform-state.something.example.com/: x509: certificate is valid for *.example.com, not terraform-state.something.example.com

This is a TLS cert error. Check your s3 endpoint.

> force_path_style

Isn't it [s3_force_path_style](https://www.vaultproject.io/docs/configuration/storage/s3.html#s3_force_path_style)?

> It appears that terragrunt is ignoring the force_path_style internally at the root of this problem.

You can see it's passing it to Terraform:

```
terraform init -backend-config=region=us-phoenix-1 -backend-config=encrypt=true -backend-config=endpoint=https://example.com -backend-config=skip_region_validation=true -backend-config=skip_credentials_validation=true -backend-config=force_path_style=true -backend-config=skip_requesting_account_id=true -backend-config=skip_get_ec2_platforms=true -backend-config=shared_credentials_file=... -backend-config=bucket=paasdevapics -backend-config=key=terraform-state/mwf/identity/terraform.tfstate -backend-config=skip_metadata_api_check=true
```

Perhaps the issue is that the param is called `s3_force_path_style`?

**Comment by fosrias** [comment]
That is a TLS cert error. But the reason it arises is that terragrunt prepends the bucket onto the endpoint URI no matter what in the calls it makes during `init`. The s3 compatible API does not support that as reflected in the cert because the "something" is a variable tenancy/namespace that is part of the endpoint. The problem is in terragrunt trying to create/verify the bucket as I understand it because it should not prepend the bucket on the endpoint when `force_path_style` is true.

The expected param is `force_path_style` per the schema: https://github.com/hashicorp/terraform/blob/v0.11.8/backend/remote-state/s3/backend.go#L195?

Terraform does load it to a struct from `force_path_style` as well:  https://github.com/hashicorp/terraform/blob/v0.11.8/backend/remote-state/s3/backend.go#L263

**Comment by fosrias** [comment]
So, the support for path style is in the AWS SDK, not the provider as I assumed above: https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

Is it possible that terrgrunt is not setting  the AWS config `S3ForcePathStyle` in the config that gets passed into the AWS S3 client?

**Comment by fosrias** [comment]
https://github.com/aws/aws-sdk-go/blob/master/aws/config.go#L126

**Comment by fosrias** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/pull/567 and https://github.com/gruntwork-io/terragrunt/pull/569.
