### ISSUE TITLE
v0.3.0 Missing Binaries

### ISSUE THREAD

**Issue by mechastorm** [gruntwork-io/terragrunt#57]
Hi,

Great work on the latest release! :) Really looking forward to trying out the aquire-lock function.

But this release does not seem to have any binaries to download from?
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.3.0

**Comment by brikis98** [comment]
Oh, good catch! Looks like there was some sort of transient build failure. Just re-ran the build and the binaries should be there now. Thanks for the heads up :)

**Comment by mechastorm** [comment]
Thanks!
