### ISSUE TITLE
get_parent_tfvars_dir not working

### ISSUE THREAD

**Issue by flmmartins** [gruntwork-io/terragrunt#587]
Hello All,

I've been upside down trying to fix this in several ways but somehow I cannot fetch the directory variables.

Here's my directory structure:
├── demo
│   ├── app-storage
│   │   ├── bucket_policy.json.tpl
│   │   ├── main.tf
│   │   └── terraform.tfvars
│   └── terraform.tfvars

Here is my demo/terraform.tfvars

```
terragrunt = {
  terraform {
    remote_state {
      backend "s3" {
        bucket = "xxxx"
        key = "${path_relative_to_include()}/terraform.tfstate"
        region = "eu-west-1"
        encrypt = true
        dynamodb_table = "xxx"
      }

      s3_bucket_tags {
        name = "Terraform State File"
        environment = "demo"
      }

      dynamodb_table_tags {
        name  = "Terraform Lock Table"
        environment = "demo"
      }
    }
  }
}

default_region = "eu-west-1"
environment = "demo" 
```

The last two lines are the variables used in demo/app-storage/main.tf:

```
provider "aws" {
  region = "${var.default_region}"
}
...

tags {
    Name = "{$var.user_bucket_name}"
    Environment = "${var.environment}"
  }

```

Now my demo/app-storage/terraform.tfvars is:

```
terragrunt = {
  include {
    path = "${find_in_parent_folders()}"
  }
   terraform {
    extra_arguments "env_vars" {
      commands = [
        "apply",
        "plan",
        "import",
        "push",
        "refresh"
      ]

      arguments = [
        "-var-file=${get_parent_tfvars_dir()}"
      ]
    }
  }
}
```

When I run $terragrunt plan-all

[terragrunt] 2018/10/15 10:59:36 Setting download directory for module /Users/fernanda/workspace/infra-k8s/aws/demo to /Users/fernanda/workspace/infra-k8s/aws/demo/.terragrunt-cache

[terragrunt] 2018/10/15 10:59:36 Module /Users/fernanda/workspace/infra-k8s/aws/demo does not have an associated terraform configuration and will be skipped.

[terragrunt] 2018/10/15 10:59:36 Setting download directory for module /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage to /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage/.terragrunt-cache

[terragrunt] 2018/10/15 10:59:36 Stack at /Users/fernanda/workspace/infra-k8s/aws:
  => Module /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage (dependencies: [])

[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage] 2018/10/15 10:59:36 Module /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage must wait for 0 dependencies to finish

[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage] 2018/10/15 10:59:36 Running module /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage now

[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage] 2018/10/15 10:59:36 Reading Terragrunt config file at /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage/terraform.tfvars

[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage] 2018/10/15 10:59:36 Running command: terraform plan -var-file=/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage

[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage] 2018/10/15 10:59:36 Module /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage has finished with an error: Hit multiple errors:
exit status 1

[terragrunt] 2018/10/15 10:59:36 Error with plan: invalid value "/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage" for flag -var-file: Error reading **/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage:** read /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage: is a directory

As you can see it's not reaching demo folder. How can I do that?

UPDATE:

Tried also with:

```
 arguments = [
        "-var-file=${get_tfvars_dir()}/${path_relative_from_include()}"
 ]

```
Also tried specifying the file terraform.tfvars 

```
arguments = [
        "-var-file=${get_parent_tfvars_dir()}/terraform.tfvars"
      ]

```

I was able to solve this by doing:
```

 arguments = [
        "-var-file=${get_tfvars_dir()}/../terraform.tfvars"
      ]
```

But as you can see I am not using the get_parent_tfvars_dir anymore which leads me to believe this is a bug

Versions are:
Terraform v0.11.8
terragrunt version v0.17.0

**Comment by flmmartins** [comment]
Tried also with:

```
 arguments = [
        "-var-file=${get_tfvars_dir()}/${path_relative_from_include()}"
 ]

```
Also tried specifying the file terraform.tfvars 

```
arguments = [
        "-var-file=${get_parent_tfvars_dir()}/terraform.tfvars"
      ]

```

I was able to solve this by doing:
```

 arguments = [
        "-var-file=${get_tfvars_dir()}/../terraform.tfvars"
      ]
```

But as you can see I am not using the get_parent_tfvars_dir anymore which leads me to believe this is a bug

Versions are:
Terraform v0.11.8
terragrunt version v0.17.0

**Comment by brikis98** [comment]
> "-var-file=${get_parent_tfvars_dir()}"

`-var-file` should point to a `.tfvars` *file*, whereas `get_parent_tfvars_dir()` will return a folder. That's why you see the error:

```
invalid value "/Users/fernanda/workspace/infra-k8s/aws/demo/app-storage" for flag -var-file: Error reading /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage: read /Users/fernanda/workspace/infra-k8s/aws/demo/app-storage: is a directory
```

> But as you can see I am not using the get_parent_tfvars_dir anymore which leads me to believe this is a bug

Yes, see #332.

**Comment by flmmartins** [comment]
After some time I was able to use variables file in an optimised from environment to subenvironment folder by doing:

/environment/terraform.tfvars:

```
terragrunt = {
  remote_state {
      backend = "s3"
      config {
        bucket = xxx
        key = "${path_relative_to_include()}/terraform.tfstate"
        region = "xxx"
        encrypt = true
        dynamodb_table = "xxxx"

        s3_bucket_tags {
          name = "Terraform State File"
          environment = "demo"
        }

        dynamodb_table_tags {
          name  = "Terraform Lock Table"
          environment = "demo"
        }
      }
  }

  # Configure root level variables that all resources can inherit
  terraform {
    extra_arguments "bucket" {
      commands = ["${get_terraform_commands_that_need_vars()}"]
      optional_var_files = [
          "${get_tfvars_dir()}/${find_in_parent_folders("env_vars.tfvars", "ignore")}"
      ]
    }
  }
}
```

That way my /environment/mymodule looks clear:

```
terragrunt = {
  include {
    path = "${find_in_parent_folders()}"
  }
  terraform {
    source ="${path_relative_from_include()}/../../modules//mymodule"
  }
}
```

But sometimes I feel the need to pass another variables from /environment/mymodule instead.

So in this case two variables sets will be used by modules:  The one inside /environment and the ones inside /enviroment

Is there a way I can pass two vars file? Can you show me an example?

**Comment by brikis98** [comment]
Have you tried adding another `extra_arguments` block in the child modules?

**Comment by flmmartins** [comment]
Well I want to try a top-down approach where the environments variables are inject by the environments themselves instead adding something to child modules. Given that I found an answer to this I will close this.
