### ISSUE TITLE
Terragrunt in Centos

### ISSUE THREAD

**Issue by muthurajr** [gruntwork-io/terragrunt#588]
I'm trying to execute terragrunt in a Centos container to bring AWS stack which is built from below snippet.

```
FROM centos:latest
RUN yum install -y curl unzip
RUN curl -O https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip \
    && unzip terraform_0.11.8_linux_amd64.zip \
    && mv terraform /usr/bin/terraform
RUN curl -O https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.0/terragrunt_linux_amd64 \
    && mv terragrunt_linux_amd64 /usr/local/bin/terragrunt \
    && chmod +x /usr/local/bin/terragrunt
```

Output
```
[root@7f7055edd444 governor]# terragrunt plan
/usr/local/bin/terragrunt: line 1: syntax error near unexpected token `<'
/usr/local/bin/terragrunt: line 1: `<html><body>You are being <a href="https://github-production-release-asset-2e65be.s3.amazonaws.com/59522149/08bab800-ca02-11e8-98d3-fb6135040004?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=**********%2F*********%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=*********&amp;X-Amz-Expires=300&amp;X-Amz-Signature=**********&amp;X-Amz-SignedHeaders=host&amp;actor_id=0&amp;response-content-disposition=attachment%3B%20filename%3Dterragrunt_linux_amd64&amp;response-content-type=application%2Foctet-stream">redirected</a>.</body></html>'
```
The problem doesn't seem to be with terragrunt as it works if we consider linuxbrew based install and some explicit package is missing.

Do we need to install any specific package in Centos to proceed?

**Comment by yuliyantsvetkov** [comment]
Hi there,

The problem clearly is that you are not downloading the binary of neither Terraform and Terragrunt in your Docker image (your error is for Terragrunt as you invoke it).

Change the `curl -O` command with `wget` and you are good to go.

**Comment by yuliyantsvetkov** [comment]
> I'm trying to execute terragrunt in a Centos container to bring AWS stack which is built from below snippet.
> 
> ```
> FROM centos:latest
> RUN yum install -y curl unzip
> RUN curl -O https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip \
>     && unzip terraform_0.11.8_linux_amd64.zip \
>     && mv terraform /usr/bin/terraform
> RUN curl -O https://github.com/gruntwork-io/terragrunt/releases/download/v0.17.0/terragrunt_linux_amd64 \
>     && mv terragrunt_linux_amd64 /usr/local/bin/terragrunt \
>     && chmod +x /usr/local/bin/terragrunt
> ```
> Output
> 
> ```
> [root@7f7055edd444 governor]# terragrunt plan
> /usr/local/bin/terragrunt: line 1: syntax error near unexpected token `<'
> /usr/local/bin/terragrunt: line 1: `<html><body>You are being <a href="https://github-production-release-asset-2e65be.s3.amazonaws.com/59522149/08bab800-ca02-11e8-98d3-fb6135040004?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=**********%2F*********%2Fus-east-1%2Fs3%2Faws4_request&amp;X-Amz-Date=*********&amp;X-Amz-Expires=300&amp;X-Amz-Signature=**********&amp;X-Amz-SignedHeaders=host&amp;actor_id=0&amp;response-content-disposition=attachment%3B%20filename%3Dterragrunt_linux_amd64&amp;response-content-type=application%2Foctet-stream">redirected</a>.</body></html>'
> ```
> The problem doesn't seem to be with terragrunt as it works if we consider linuxbrew based install and some explicit package is missing.
> 
> Do we need to install any specific package in Centos to proceed?

In your case `curl -O` downloads the HTML page of HTTPS permanent redirect. Change your `curl -O` command to `wget` in the Docker image file and your are good to go.

**Comment by muthurajr** [comment]
my bad, i was in the assumption terragrunt link point to a file and not https page. Thank you so much for the clarification!
