### ISSUE TITLE
apply/apply-all with a terraform plan file failing

### ISSUE THREAD

**Issue by mpkerr** [gruntwork-io/terragrunt#596]
In both 0.16.14 and 0.17.1 I am still seeing a problem with the terraform command including -var-file options, even though this problem is claimed to be fixed.

/terraform/environments/aws/v2/dev01/lambdas # terragrunt apply terraform.tfplan
[terragrunt] [/terraform/environments/aws/v2/dev01/lambdas] 2018/11/01 12:37:08 Running command: terraform --version
[terragrunt] 2018/11/01 12:37:08 Reading Terragrunt config file at /terraform/environments/aws/v2/dev01/lambdas/terraform.tfvars
[terragrunt] 2018/11/01 12:37:08 Cleaning up existing *.tf files in /terraform/environments/aws/v2/dev01/lambdas/.terragrunt-cache/R5HZXJFKs785Q9S0UG87QtUARt4/3IhwhmcCayDuuEU3jmhZ_J0CXZU
[terragrunt] 2018/11/01 12:37:08 Downloading Terraform configurations from file:///terraform/modules/aws into /terraform/environments/aws/v2/dev01/lambdas/.terragrunt-cache/R5HZXJFKs785Q9S0UG87QtUARt4/3IhwhmcCayDuuEU3jmhZ_J0CXZU using terraform init
[terragrunt] [/terraform/environments/aws/v2/dev01/lambdas] 2018/11/01 12:37:09 Running command: terraform init -backend-config=region=us-east-1 -backend-config=dynamodb_table=terraform_locks -backend-config=bucket=pix-terraform -backend-config=key=v2/dev01/lambdas/terraform.tfstate -lock-timeout=20m -get=false -get-plugins=false -backend=false -from-module=file:///terraform/modules/aws -no-color /terraform/environments/aws/v2/dev01/lambdas/.terragrunt-cache/R5HZXJFKs785Q9S0UG87QtUARt4/3IhwhmcCayDuuEU3jmhZ_J0CXZU
Copying configuration from "file:///terraform/modules/aws"...
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
[terragrunt] 2018/11/01 12:37:09 Copying files from /terraform/environments/aws/v2/dev01/lambdas into /terraform/environments/aws/v2/dev01/lambdas/.terragrunt-cache/R5HZXJFKs785Q9S0UG87QtUARt4/3IhwhmcCayDuuEU3jmhZ_J0CXZU/lambda
[terragrunt] 2018/11/01 12:37:09 Setting working directory to /terraform/environments/aws/v2/dev01/lambdas/.terragrunt-cache/R5HZXJFKs785Q9S0UG87QtUARt4/3IhwhmcCayDuuEU3jmhZ_J0CXZU/lambda
[terragrunt] 2018/11/01 12:37:09 Skipping var-file /terraform/environments/aws/v2/dev01/lambdas/../../common.tfvars as it does not exist
[terragrunt] 2018/11/01 12:37:09 Running command: terraform apply -lock-timeout=20m -var-file=/terraform/environments/aws/terraform.tfvars -var-file=/terraform/environments/aws/v2/dev01/lambdas/../common.tfvars -var-file=terraform.tfvars terraform.tfplan
You can't set variables with the '-var' or '-var-file' flag
when you're applying a plan file. The variables used when
the plan was created will be used. If you wish to use different
variable values, create a new plan file.
[terragrunt] 2018/11/01 12:37:09 Hit multiple errors:
exit status 1
/terraform/environments/aws/v2/dev01/lambdas # terragrunt --version
terragrunt version v0.16.14

**Comment by jamesgoodhouse** [comment]
any movement on this bug?

**Comment by yorinasub17** [comment]
There has been some movements on improving things, but there are still a few issues with using plan files as documented in https://github.com/gruntwork-io/terragrunt/issues/983. Will close this in favor of that ticket.
