### ISSUE TITLE
what command to do the per module oepration

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/terragrunt#601]
I have my module setup like this :

```
├── aws
│   ├── ami
│       ├── ...
│   │   ├── terraform.tfvars
│   │   └── ...
│   └── eks
│       ├── ...
│       ├── terraform.tfvars
│   │   └── ...
├── datadog
│   ├── ...
│   └── terraform.tfvars
├── pagerduty
│   ├── ...
│   └── terraform.tfvars
└── terraform.tfvars
```

How can I do per module operation on aws/ami only?

I am looking for something like `terragrunt destroy -module aws/ami`

**Comment by brikis98** [comment]
Not sure I fully follow the question, but it seems like you would just do this:

```
cd aws/ami
terragrunt destroy
```

**Comment by yuliyantsvetkov** [comment]
Hi Yevgeniy,

I think the guy was asking for the -target option of Terraform CLI.

The option is passed by terragrunt to terraform without any issues, and it is used like that (for example for EC2 instance):

terragrunt 'apply/plan/destroy' -target module.[name of the module].aws_instance.[name of the aws_instance resource]

Best regards,
Yuli
