### ISSUE TITLE
How to reconfigure plugins

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/terragrunt#605]
Recently, I have problem with aws provider as [v1.43.1](https://github.com/terraform-providers/terraform-provider-aws/issues/6416), I wonder if there is any command that I can use to reconfigure the plugins. 

```
Plugin reinitialization required. Please run "terraform init".
Reason: Could not satisfy plugin requirements.

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

1 error(s) occurred:

* provider.aws: no suitable version installed
  version requirements: "<= 1.42.0"
  versions installed: "1.43.1"

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints from each module, run "terraform providers".
```
Thanks!

**Comment by yorinasub17** [comment]
Hi @chenrui333 , you should be able to reinitialize the plugins by running `terragrunt init`.

**Comment by chenrui333** [comment]
yeah, I tried, but it does not work with the plugin. Is there any command option that I can use?

**Comment by yorinasub17** [comment]
Hmm that is odd. That should update the provider to the specified version. Can you paste in the output of `terragrunt init`?

**Comment by chenrui333** [comment]
yeah, not quite working.
```
$ terragrunt init
[terragrunt] [/Users/ruichen/mup/pro-infra-config] 2018/11/09 22:55:30 Running command: terraform --version
[terragrunt] 2018/11/09 22:55:30 Reading Terragrunt config file at /Users/ruichen/mup/pro-infra-config/terraform.tfvars
[terragrunt] 2018/11/09 22:55:30 Initializing remote state for the s3 backend
[terragrunt] 2018/11/09 22:55:31 Running command: terraform init -backend-config=dynamodb_table=com.meetup.pro.tf-lock-table -backend-config=bucket=com.meetup.pro.tf-states -backend-config=key=./terraform.tfstate -backend-config=region=us-east-1 -backend-config=encrypt=true
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
```

**Comment by yorinasub17** [comment]
Is that the root of your project, and you have subfolders from there with each defining a separate component ([the root folder in the `-all` command example](https://github.com/gruntwork-io/terragrunt#the-apply-all-destroy-all-output-all-and-plan-all-commands))?

The reason I ask is that unfortunately, `terragrunt init` is one of those commands where we don't have a `-all` version so if you are running it at the root of your live infrastructures, then it will not work. It needs to be run in each individual component.

So I see two things happening here:

1. Somehow [Auto-Init](https://github.com/gruntwork-io/terragrunt#auto-init) isn't detecting the provider change. This may be one of the cases we haven't handled yet.
2. We don't have a `-all` flavor of `init`, so you have to go into each subcomponent to make `terragrunt init` effective.

**Comment by chenrui333** [comment]
Yes, that is the root folder.

**Comment by chenrui333** [comment]
Going to the module folder and doing `terragrunt init` solving the problem. It may be good that we can have some provider version change detection mechanism.

**Comment by chenrui333** [comment]
Also, feel free to close the issue as it works for me now.

**Comment by yorinasub17** [comment]
Great to hear it is working now!

**Comment by yorinasub17** [comment]
FYI I filed https://github.com/gruntwork-io/terragrunt/issues/606 to track the AutoInit detection.
