### ISSUE TITLE
Tags not being applied to state bucket or dynamodb

### ISSUE THREAD

**Issue by flmmartins** [gruntwork-io/terragrunt#608]
So... I've been using terragrunt successfully so far but the tagging during the creation of the S3 bucket or Dynamo DB does not work. I am passing them with s3_bucket_tags and dynamodb_table_tags but nothing is happening:

```
terragrunt = {
  remote_state {
      backend = "s3"
      config {
        bucket = "xxxx"
        key = "${path_relative_to_include()}/terraform.tfstate"
        region = "xxx"
        encrypt = true
        dynamodb_table = "xxxx"

        s3_bucket_tags {
          name = "Terraform State File"
          environment = "demo"
        }

        dynamodb_table_tags {
          name  = "Terraform Lock Table"
          environment = "demo"
        }
      }
  }

```

Best,

**Comment by brikis98** [comment]
Are you using those with a bucket / table that already exist? It might only tag them when creating totally new ones... Also, which version of Terragrunt are you using?

**Comment by flmmartins** [comment]
I created from scratch.

Version v0.17.2

**Comment by brikis98** [comment]
Could you share the full log output from running Terragrunt when creating the bucket/table? It may give a hint as to what's happening.

**Comment by dennybaa** [comment]
@flmmartins Well same thing :( version `v0.17.1`

```
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:30 Running command: terraform --version
[terragrunt] 2019/01/08 08:50:30 Reading Terragrunt config file at /home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base/terraform.tfvars
[terragrunt] 2019/01/08 08:50:30 Cleaning up existing *.tf files in /home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base/.terragrunt-cache/Qu8Hzofe-Q9V6ujsY_jDG6UHGpY/I9XlZt3X-PGvA1zmcSVOCQ5Jbyk
[terragrunt] 2019/01/08 08:50:30 Downloading Terraform configurations from file:///home/fixuid/code/actionml/aws-govtribe/terraform/modules into /home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base/.terragrunt-cache/Qu8Hzofe-Q9V6ujsY_jDG6UHGpY/I9XlZt3X-PGvA1zmcSVOCQ5Jbyk using terraform init
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:32 Initializing remote state for the s3 backend
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:32 [terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base]  Remote state S3 bucket actionml-govtribe-terraform.s3 does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
y
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:37 Creating S3 bucket actionml-govtribe-terraform.s3
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:38 S3 bucket actionml-govtribe-terraform.s3 created.
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:38 No tags for S3 bucket given.
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:38 Enabling versioning on S3 bucket actionml-govtribe-terraform.s3
[terragrunt] [/home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base] 2019/01/08 08:50:41 Running command: terraform init -backend-config=bucket=actionml-govtribe-terraform.s3 -backend-config=key=dev/base/terraform.tfstate -backend-config=region=us-east-1 -backend-config=encrypt=true -backend-config=dynamodb_table=actionml-govtribe-terraform.lock -get=false -get-plugins=false -backend=false -from-module=file:///home/fixuid/code/actionml/aws-govtribe/terraform/modules -no-color /home/fixuid/code/actionml/aws-govtribe/terraform/live/dev/base/.terragrunt-cache/Qu8Hzofe-Q9V6ujsY_jDG6UHGpY/I9XlZt3X-PGvA1zmcSVOCQ5Jbyk
Copying configuration from "file:///home/fixuid/code/actionml/aws-govtribe/terraform/modules"...
Terraform initialized in an empty directory!
```

**Comment by dennybaa** [comment]
@brikis98 Sorry for the confusion :)
@flmmartins Works, as it occurs to check the encryption we have to check the properties of the actual `*.tfstate` file. And yes it's in the place.

**Comment by flmmartins** [comment]
> @brikis98 Sorry for the confusion :)
> @flmmartins Works, as it occurs to check the encryption we have to check the properties of the actual `*.tfstate` file. And yes it's in the place.

Hi Denny,

I still have the problem where despite putting on code my buckets are neither encrypted or tagged.
Can you elaborate on how you solve your problem? Did you do it manually and then terragrunt pick it up or what?

**Comment by dennybaa** [comment]
Hey @flmmartins ,
yes it works. `terragrunt apply` then find your tfstate file and check the properties: ![](http://pix.toile-libre.org/upload/original/1547745582.png)

terragrunt: v0.17.1
terraform: v0.11.10

**Comment by flmmartins** [comment]
@dennybaa I thought you've done something to achieve this....

I notice we have different versions though. I'm using:

Terragrunt version v0.17.2
Terraform v0.11.10

**Comment by flmmartins** [comment]
I double check again and the terraform.tfvars is encrypted!! I was looking in AWS bucket properties (ENTER BUCKET > PROPERTIES > check the AWS encryption tile) and it says it's no encrypted but if you go to terraform.tfvars object properties as you posted @dennybaa is encrypted.

Unfortunately the **tagging** is still not being applied @brikis98 

I just created a new bucket and dynamodb with tagging. The logs is bellow:
terragrunt apply
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:30 Running command: terraform --version
[terragrunt] 2019/02/06 09:11:30 Reading Terragrunt config file at /Users/fernanda/workspace/infra-k8s/aws/staging/dns/terraform.tfvars
[terragrunt] 2019/02/06 09:11:30 Cleaning up existing *.tf files in /Users/fernanda/workspace/infra-k8s/aws/staging/dns/.terragrunt-cache/DKxNHn3rLhQ4CqudqSJeKeUTWV8/cNtnLRD6R6jGY_B1OColbam8hEg
[terragrunt] 2019/02/06 09:11:30 Downloading Terraform configurations from file:///Users/fernanda/workspace/infra-k8s/aws/modules into /Users/fernanda/workspace/infra-k8s/aws/staging/dns/.terragrunt-cache/DKxNHn3rLhQ4CqudqSJeKeUTWV8/cNtnLRD6R6jGY_B1OColbam8hEg using terraform init
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:30 Backend config has changed from map[key:dns/terraform.tfstate region:eu-west-1 bucket:demo.terraform-state.bucket dynamodb_table:staging.terraform-state.table encrypt:%!s(bool=true)] to map[encrypt:%!s(bool=true) dynamodb_table:staging.terraform-state.table bucket:staging.terraform-state.bucket key:dns/terraform.tfstate region:eu-west-1]
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:30 Initializing remote state for the s3 backend
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:30 [terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns]  Remote state S3 bucket staging.terraform-state.bucket does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n)
y
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:35 Creating S3 bucket staging.terraform-state.bucket
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:36 S3 bucket staging.terraform-state.bucket created.
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:36 No tags for S3 bucket given.
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:36 Enabling versioning on S3 bucket staging.terraform-state.bucket
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:37 Lock table staging.terraform-state.table does not exist in DynamoDB. Will need to create it just this first time.
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:37 Creating table staging.terraform-state.table in DynamoDB
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:37 Table staging.terraform-state.table is not yet in active state. Will check again after 10s.
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:47 Success! Table staging.terraform-state.table is now in active state.
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:47 No tags for lock table given.
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:47 Running command: terraform init -backend-config=key=dns/terraform.tfstate -backend-config=region=eu-west-1 -backend-config=encrypt=true -backend-config=dynamodb_table=staging.terraform-state.table -backend-config=bucket=staging.terraform-state.bucket -get=false -get-plugins=false -backend=false -from-module=file:///Users/fernanda/workspace/infra-k8s/aws/modules -no-color /Users/fernanda/workspace/infra-k8s/aws/staging/dns/.terragrunt-cache/DKxNHn3rLhQ4CqudqSJeKeUTWV8/cNtnLRD6R6jGY_B1OColbam8hEg
Copying configuration from "file:///Users/fernanda/workspace/infra-k8s/aws/modules"...
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.

[terragrunt] 2019/02/06 09:11:47 Copying files from /Users/fernanda/workspace/infra-k8s/aws/staging/dns into /Users/fernanda/workspace/infra-k8s/aws/staging/dns/.terragrunt-cache/DKxNHn3rLhQ4CqudqSJeKeUTWV8/cNtnLRD6R6jGY_B1OColbam8hEg/dns
[terragrunt] 2019/02/06 09:11:47 Setting working directory to /Users/fernanda/workspace/infra-k8s/aws/staging/dns/.terragrunt-cache/DKxNHn3rLhQ4CqudqSJeKeUTWV8/cNtnLRD6R6jGY_B1OColbam8hEg/dns
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:47 Initializing remote state for the s3 backend
[terragrunt] [/Users/fernanda/workspace/infra-k8s/aws/staging/dns] 2019/02/06 09:11:47 Running command: terraform init -backend-config=key=dns/terraform.tfstate -backend-config=region=eu-west-1 -backend-config=encrypt=true -backend-config=dynamodb_table=staging.terraform-state.table -backend-config=bucket=staging.terraform-state.bucket

Initializing the backend...
Backend configuration changed!

Terraform has detected that the configuration specified for the backend
has changed. Terraform will now check for existing state in the backends.



**terraform.tfvars**
```
terragrunt = {
  remote_state {
      backend = "s3"
      config {
        bucket = "staging.terraform-state.bucket"
        key = "${path_relative_to_include()}/terraform.tfstate"
        region = "eu-west-1"
        encrypt = true
        dynamodb_table = "staging.terraform-state.table"

        s3_bucket_tags {
          name = "Terraform State File"
          environment = "staging"
        }

        dynamodb_table_tags {
          name  = "Terraform Lock Table"
          environment = "staging"
        }
      }
  }

  # Configure root level variables that all resources can inherit
  terraform {
    extra_arguments "bucket" {
      commands = ["${get_terraform_commands_that_need_vars()}"]
      optional_var_files = [
          "${get_tfvars_dir()}/${find_in_parent_folders("env_vars.tfvars", "ignore")}"
      ]
    }
  }
}


```

**Comment by ssklee** [comment]
@flmmartins I ran into the same problem earlier today, my tags just wouldn't be applied to the DynamoDB and S3, even when created from scratch. What solved the issue for me was to delete the `.terragrunt-cache` subdirectories which had existed before I added the tagging configurations to the terragrunt block. It seems that the configuration changes aren't updated when the cache exists.

**Comment by flmmartins** [comment]
> @flmmartins I ran into the same problem earlier today. My tags wouldn't be applied to the DynamoDB and S3, even when created from scratch.
> 
> What solved the issue for me was to delete the `.terragrunt-cache` subdirectories which had existed before I added the tagging configurations to the terragrunt block. It seems that these configuration changes are ignored when the cache already exists.
> 
> Possibly a bug?

Humm I don't remember if I had cached terragrunt folder at the time...
When I have the opportunity to create another state I will post info here

**Comment by flmmartins** [comment]
Okey.. I tested this and I had no caching I and the tagging worked. It's a bug indeed.....

**Comment by flmmartins** [comment]
Well.. I created yet another state and everythings is fine with version 18.3. If anyone has further issues can reopen this. =)

**Comment by KadenLNelson** [comment]
I just ran into this problem, clearing all the `.terragrunt-cache` folders worked for me 👍 Thanks @ssklee 

Terraform v0.12.18
terragrunt version v0.21.9
