### ISSUE TITLE
Feature Request init-all

### ISSUE THREAD

**Issue by flmmartins** [gruntwork-io/terragrunt#609]
Hello All,

I want to run a task that uses terragrunt plan-all and terragrunt apply-all in Jenkins but sometimes I need to **init** things by going inside /environment/component and doing **terragrunt ini**t.

Everytime I change a variable or rename modules  I need to go inside the /environment/component and do a terragrunt init. I've tried using plan-all to see if the auto init works but it doesn't. 

Is it possible to implement an init-all or something like?

My folder structure is:

├── demo
│   ├── app_storage
│   │   └── terraform.tfvars
│   ├── application
│   │   └── terraform.tfvars
│   ├── dns
│   │   └── terraform.tfvars
│   ├── env_vars.tfvars
│   └── terraform.tfvars

Thanks

**Comment by brikis98** [comment]
Closing in favor of two other potential ways to solve this:

https://github.com/gruntwork-io/terragrunt/issues/388
https://github.com/gruntwork-io/terragrunt/issues/492

**Comment by agrzegorczyk-leonsoftware** [comment]
We using this snippet to achieve init-all functionality:
```bash
find . -not -path '*/.terragrunt-cache/*' -type f -name terraform.tfvars -execdir terragrunt init \;
```

**Comment by mleuthold** [comment]
I'm using `terragrunt version v0.21.11` so this snippet changes from using terraform.tfvars to terragrunt.hcl. 
`find . -not -path '*/.terragrunt-cache/*' -type f -name terragrunt.hcl -execdir terragrunt init \;`

**Comment by Art3mK** [comment]
find will still exit 0, even if some execdir command will fail, so I modified previous snippet a bit: 

`find . -not -path '*/.terragrunt-cache/*' -type f -name terragrunt.hcl -printf '%h\n' | xargs -l -i sh -c 'cd {}; terragrunt init --terragrunt-non-interactive -input=false'`

**Comment by Art3mK** [comment]
probably even better solution:
`find "$PWD" -not -path '*/.terragrunt-cache/*' -type f -name terragrunt.hcl -printf 'cd "%h" && terragrunt init --terragrunt-non-interactive -input=false\n' | sh -ex`
