### ISSUE TITLE
Handling s3 custom policies using tfvars file

### ISSUE THREAD

**Issue by dfduarte** [gruntwork-io/terragrunt#612]
Hello there, I got a problem here (or at least I didn't get the solution at first):

I was trying to find out in the documentation or at Google, but I couldn't find a way to pass a custom policy file to be used by terragrunt and my main terraform module.

Let's say I got my terraform.tfvars file:

```
terragrunt = {
    include {
        path = "${find_in_parent_folders("terraform.tfvars")}"
    }
    terraform {
        source = "../../../../modules/bucket/custom"
    }
}

bucket_name          = "aaaa-bucket"
region               = "us-east-1"
application          = "aaaaaaaaaa"
application_group    = "aaaaaa"
department           = "aaaaa"
team                 = "aaaaaa"
team_email           = "aaaaaa@aaaaa.com"
incident_email       = "aaaaaaa@aaaaa.com"
compliance           = "None"
use_custom_policy    = true
zone_name            = "aaaaaacloud"
acl                  = ""
encryption_algorithm = "AES256"
custom_policy        = ""
```

My custom module has:

```
# Creates a bucket with a nongenerated name
resource "aws_s3_bucket_policy" "bucket_policy" {
  count  = "${var.use_custom_policy}"
  bucket = "${aws_s3_bucket.bucket.id}"
  policy = "${var.custom_policy}"
}

# Bucket creation
resource "aws_s3_bucket" "bucket" {
  bucket = "${var.bucket_name}"
  acl    = "${var.acl}"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "${var.encryption_algorithm}"
      }
    }
  }

  tags = "${local.s3_tags}"
}

```

The idea here is:

I need to create a new plain json file with a custom policy, save it inside the same dir as terraform.tfvars file, and reference it in the custom_policy to be used by my module at runtime, which is in another directory (as seen above).

So, that will be something like:

```
myterragrunt/
  terraform.tfvars
  mycustompolicy.json
../../.../bucket/custom
  main.tf
  variables.tf
  anythingelse.......tf
```

And I need to use my custom policy which is inside myterragrunt/

Is there a way to do so? I tried to render it inside terraform.tfvars file, but I got a lot of problems with terraform functions (like $file, which is not recognized by terragrunt). I even created a special module just for this bucket to handle this. It works, but that's not the desirable thing now.

Edit:

My current solution has to duplicate the whole module for the bucket, but passing the reference for the json file rendered. It worked, but it's ugly.

**Comment by brikis98** [comment]
The idea is that that your Terraform code (`.tf` files) implements all the logic and you use Terragrunt—and, for that matter, `.tfvars` files, which are actually a Terraform concept—to pass _simple_ arguments to that Terraform code to configure it differently in different environments. Those simple arguments should not include variables, interpolation, entire policy files, etc.

So, your best bet is to:

1. If there are a small number of possible policy files you want to support, then implement each one in your Terraform code (e.g., using `aws_iam_policy_document` data sources) and pass in a variable via `.tfvars` to select which policy gets used.

1. Define policy files in `.json` files and pass in the path to one such file via `.tfvars`. Your code then builds the path to the policy file dynamically: e.g., `file("${path.module}/policy-files/${var.policy_file_name}")`

**Comment by yorinasub17** [comment]
Closing as it looks like the original question has been answered. If this is still an issue, please open a new issue with an updated example compatible with the latest version of terragrunt. Thanks!
