### ISSUE TITLE
No colour output since release 0.17.0 on Windows x64

### ISSUE THREAD

**Issue by raras-dfds** [gruntwork-io/terragrunt#614]
It seems 0.17.x breaks colour output, and prints the escape sequences instead, at least on Windows x64. This worked as intended on 0.16.x.

**0.16.x:**
![terragrunt_0 16 x png](https://user-images.githubusercontent.com/40060690/49001233-68108b00-f15c-11e8-8232-b3e0efd30259.png)

**0.17.x:**
![terragrunt_0 17 x](https://user-images.githubusercontent.com/40060690/49001242-6fd02f80-f15c-11e8-8e8a-60ccf51f50b0.png)

**System:**
- Windows 10 Enterprise build 17134
- Terraform 0.11.7 and 0.11.10
- Terragrunt 0.16.10, 0.16.14, 0.17.0, 0.17.1, 0.17.2

**Comment by raras-dfds** [comment]
Of course, but alas, same on 0.17.3.

**Comment by lorengordon** [comment]
Color seems fine in powershell, is the problem limited to a cmd shell?

**Comment by raras-dfds** [comment]
Sorry, should have included in description - I'm using PowerShell Core 6.0.4.

**Comment by brikis98** [comment]
@lorengordon Are you on v0.17.3 and the color output is working on Windows?

I can confirm that on Mac, it works fine with v0.17.3. I don't have a Windows box to test with, so it may be a bit tricky to debug. Help/PRs/ideas are very welcome!

**Comment by lorengordon** [comment]
@brikis98 Yes indeed, terragrunt v0.17.3, terraform v0.11.10, Windows 10 1809 Build 17763.134, PowerShell 5 (I think, PowerShell versioning is a mess).

```
> terragrunt -version
terragrunt version v0.17.3

> terraform -version
Terraform v0.11.10

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by EdisonHarada** [comment]
In my powershell is not working.

Windows 10.0.17134 Build 17134


```
> terragrunt -version
terragrunt version v0.17.3

> terraform -version
Terraform v0.11.10

> $PSVersionTable

Name                                       Value
----                                           -----
PSVersion                                 5.1.17134.407
PSEdition                                  Desktop
PSCompatibleVersions             {1.0, 2.0, 3.0, 4.0...}
BuildVersion                             10.0.17134.407
CLRVersion                               4.0.30319.42000
WSManStackVersion                3.0
PSRemotingProtocolVersion    2.3
SerializationVersion                  1.1.0.1
```

**Comment by lorengordon** [comment]
Hmm, something has indeed changed... my workstation rebooted after installing some patches, and now I also just see the sequences in powershell rather than color output.

**Comment by lorengordon** [comment]
Ok, if I change to the temporary directory in the terragrunt cache, and run `terraform` directly, color output works fine in powershell. So I do think there is something about how terragrunt is processing the output now that is causing the problem...

**Comment by lorengordon** [comment]
Oi. Now that I've run terraform directly that one time and got color output, it seems it initialized something such that now color output works in terragrunt. 🤕 🤦‍♂️

**Comment by lorengordon** [comment]
> Now that I've run terraform directly that one time and got color output, it seems it initialized something such that now color output works in terragrunt.

Eh, that wasn't right either. Forgot I was using a wrapper around terragrunt that was itself initializing the color output (#pythonftw!).

**Comment by furqx** [comment]
Problems is always here with terragrunt v0.17.4, a workarround is known ?

Thanks !

**Comment by dsargent3220** [comment]
Just started using Terragrunt, great tool, but this is still really broken in Windows, both Powershell and the CMD prompt.
Any plans on fixing?  Terraform is fine.  
If we can't get the color coding to work, can we at least remove the horribly hard to read character encoding?

**Comment by yorinasub17** [comment]
Unfortunately, we're a bit buried to take on this any time soon. A workaround to disable colors would be to use `extra_arguments` to pass in `-no-color`.

**Comment by abstrask** [comment]
I created this issue under another account, and kinda forgot about it. Sorry.

I'm currently using:
- Terraform 0.12.24
- Terragrunt 0.23.2
- PowerShell Core 7.0.0
- Windows Terminal Preview 0.10

FWIW, I haven't had this issue for a looong time by now - several versions of all of the above from now. Have you other folks seen it on recent versions?

**Comment by brikis98** [comment]
Please try out https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.27!
