### ISSUE TITLE
How to organize some kind of resources in subdirectories

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/terragrunt#618]
Right now I have resources sitting in one level (one module), as the resource files in the module grow, I can imagine it would helpful to have the resource files sitting in the subdirectories grouped by different reasons.

For example, currently resource files layout is like below
```
.
├── resource1.tf
├── resource2.tf
├── resource2.tf
├── main.tf
└── terraform.tfvars
```

I want to transform into something like this

```
.
├── project1
│   ├── resource1.tf
│   ├── resource2.tf
├── project2
│   ├── resource3.tf
│   ├── resource4.tf
├── main.tf
└── terraform.tfvars
```

Let me know if this does make sense. Thanks!

**Comment by brikis98** [comment]
This sounds like more of a Terraform question than a Terragrunt question. See, for example, [Terraform Modules](https://www.terraform.io/docs/modules/usage.html), [How to create reusable infrastructure with Terraform modules](https://blog.gruntwork.io/how-to-create-reusable-infrastructure-with-terraform-modules-25526d65f73d), and [terragrunt-infrastructure-live-example](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example).

**Comment by brikis98** [comment]
State is managed by Terragrunt, it's managed by Terraform, which does it on a per-folder basis. If you're breaking up your infrastructure just to make the code easier to read and follow, then create a bunch of small Terraform modules, and use the `module` keyword to import them into a single module that ultimately gets deployed with one state file. If you're breaking up the infrastructure to isolate different environments or types of infrastructure from each other, then you'll want to isolate the state files too.

**Comment by chenrui333** [comment]
@brikis98 thanks for the response, I will need to think about a better way to structure my question

**Comment by yorinasub17** [comment]
Closing as this is primarily a Terraform question as opposed to Terragrunt. Please follow https://github.com/hashicorp/terraform/issues/26177. Thanks!
