### ISSUE TITLE
get_env() not recognizing environment vars set by extra_arguments

### ISSUE THREAD

**Issue by cnw004** [gruntwork-io/terragrunt#621]
When setting  env_vars inside of a extra_arguments block the environment variables that are set are not recognized by my remote_state block.

![image](https://user-images.githubusercontent.com/17993870/49966233-70531f00-feed-11e8-9226-8be31324c632.png)

These variables *are* set in the environment as seen by my before_hook that simply prints out the env:

![image](https://user-images.githubusercontent.com/17993870/49966173-4a2d7f00-feed-11e8-93a5-7d4d3cd98232.png)

The get_env() function in the remote_state block *should* be able to recognize the environment variables that I just set. Instead, it sees them as being blank and uses the default value.

**Comment by brikis98** [comment]
The `env_vars` in `extra_arguments` are only set as "extra arguments" for the Terraform command you're running (i.e., for `terraform apply`). They are not available to any other part of Terragrunt for now, including `get_env`, which happens while parsing your `.tfvars` file, potentially before `extra_arguments` are parsed...

**Comment by cnw004** [comment]
Ok, thats completely explains that behavior. Thank you for explaining that. It would be nice to have a way to set variables this way. It would be helpful to have the top level tfvars file be the only file that you have to change in order to redeploy a new or slightly modified set of resources. Essentially one place to store / change your "volatile" variables that can change from run to run
