### ISSUE TITLE
Why is terragrunt creating an instance for the root terragrunt file as well?

### ISSUE THREAD

**Issue by estein9825** [gruntwork-io/terragrunt#623]
I have my project set up as follows:
```
root
├── env
│   ├── dev
│       └── terraform.tfvars
│   ├── stage
│       └── terraform.tfvars]
│   ├── prod
│       └── terraform.tfvars
│   ├── terraform.tfvars
```

When I run `terragrunt plan-all` from the `env` directory, it runs the items beneath each of the folders, but it also runs the general env script as well. so in the case where it's requesting to create redis instances, I get one for dev, stage, and prod, but also one from env.  What am I doing wrong? Or is this expected behavior?

```
terragrunt version v0.17.3
```

env terraforms.tfvars:
```
terragrunt {
  terraform {
    version = "0.11.10"

    source = "${path_relative_from_include()}/../modules//data-storage/redis"
  }

  remote_state {
    backend = "s3"

    config {
      bucket         = "fama-terraform-remote-state"
      key            = "env/${path_relative_to_include()}/terraform.tfstate"
      region         = "us-west-2"
      encrypt        = true
      dynamodb_table = "fama-lock-table"

      s3_bucket_tags {
        owner = "FAMA"
        name  = "Terraform state storage"
      }

      dynamodb_table_tags {
        owner = "FAMA"
        name  = "Terraform lock table"
      }
    }
  }
}

name_suffix = "-tf2"
```

dev terraform.tfvars
```
terragrunt {
  terraform {
  }

  include {
    path = "${find_in_parent_folders()}"
  }
}

env = "dev"

name_suffix = "-tf"

redis_s3_key_loc = "vpcs/env/dev"

availability_zones = ["us-west-2a"]

number_cache_clusters = "1"

instance_type = "cache.r4.large"
```

stage terraforms.tfvars
```
terragrunt {
  terraform {
  }

  include {
    path = "${find_in_parent_folders()}"
  }
}

env = "stage"

name_suffix = "tf-stg1"

redis_s3_key_loc = "vpcs/env/stage"

availability_zones = ["us-west-2a", "us-west-2b", "us-west-2c"]

number_cache_clusters = "3"

instance_type = "cache.r4.large"
```

prod terraforms.tfvars
```
terragrunt {
  terraform {
  }

  include {
    path = "${find_in_parent_folders()}"
  }
}

env = "prod"

name_suffix = "-tf"

redis_s3_key_loc = "vpcs/env/prod"

instance_type = "cache.r4.large"

cluster_mode = [{
  num_node_groups         = 2
  replicas_per_node_group = 3
}]
```

Any help would be greatly appreciated.

**Comment by estein9825** [comment]
But then I have to duplicate the source value which is the same for all the children files.

**Comment by lorengordon** [comment]
Yep, very true. I end up in the same place. Just letting you know the current workaround. :)

**Comment by estein9825** [comment]
Good to know.  Thanks.

**Comment by estein9825** [comment]
Doesn't this go against the option in terragrunt regarding position from source: 
https://github.com/gruntwork-io/terragrunt#path_relative_from_include?

**Comment by brikis98** [comment]
As @lorengordon indicated, the `xxx-all` commands just run `xxx` in any subfolder with a `terragrunt {}` block... There's no good solution right now. Perhaps you can make `--terragrunt-exclude-dir` work to avoid this issue, but it might exclude all subfolders too...

**Comment by cbascom** [comment]
@brikis98 I am interested in putting together a PR to fix this as I am hitting it as well. I have two ideas on how to go about it, but would like to hear your thoughts.

1. During the parsing phase that currently just looks for the presence of the terragrunt { ... } block, we do one further level of parsing to process all interpolations. That will result in the path parameter for all include blocks being set correctly. As we walk all of the files that contain these terragrunt { ... } blocks, we keep track of which files have been included by other files. When the walk is complete, we remove all files that have been included by any other files. My question here is, is this safe? Is there ever a scenario where a terraform.tfvars is included but should also still be processed by *-all commands?

1. Add a new config parameter to the terragrunt { ... } block named included_file or something like that. When this is set to true, the current scan will ignore any files with included_file set to true in the terragrunt { ... } block.

Does either of these sound good to you or do you have any other ideas on how you would like to see this tackled?

**Comment by brikis98** [comment]
Not sure I follow. How is `include` relevant here?

I think the solution might be to update the parsing to look not only for a `terragrunt { ... }` block, but also check if (a) there is a `terraform { source = "..." }` block or (b) `.tf` files in the same folder as the `terraform.tfvars`. If neither of these are true, automatically skip the folder.

**Comment by cbascom** [comment]
Neither of those will address my scenario unfortunately. Here is my directory structure:
```bash
├── 12.1.4
│   └── terraform.tfvars
├── 13.1.0
│   └── terraform.tfvars
├── 14.0.0
│   └── terraform.tfvars
└── terraform.tfvars
```

In this scenario the top level terraform.tfvars has the `terraform { source = "..." }` block along with the `remote_state { ... }` block. All of the terraform.tfvars files in the sub-directories include that root terraform.tfvars using the `include { path = "${find_in_parent_folders()}" }` block. When I run terragrunt apply-all in that top level directory, I want just the sub-directories to actually get processed.

Option 1 that I proposed is saying that if we detect that top level terraform.tfvars file has been included by any of the terraform.tfvars files in the sub-directories, we ignore that top level terraform.tfvars file under the assumption that it does not define infrastructure itself.

Option 2 that I proposed gets rid of the assumption and allows the user to explicitly say that this particular terraform.tfvars file does not define infrastructure itself by setting a new variable to true. Admittedly I haven't come up with a very good name for this new variable yet though.

**Comment by brikis98** [comment]
> In this scenario the top level terraform.tfvars has the `terraform { source = "..." }` block

Oh, how come? What infra does that top-level file define? 

It strikes me as a slightly non-standard thing to do, as anything that then `include`s this top level `terraform.tfvars` file will also inherit its `source = ...` config. Granted, you can override it, but if you forget to, you'll end up deploying whatever module happened to be in there.

Also, I'm guessing this is not the case originally described in this issue, but @estein9825 can correct me if I'm wrong.

> Option 2 that I proposed gets rid of the assumption and allows the user to explicitly say that this particular terraform.tfvars file does not define infrastructure itself by setting a new variable to true.

Why build a mechanism to indicate this rather than just removing the `terraform { source = ... }` block from the top-level `terraform.tfvars`?

**Comment by cbascom** [comment]
> Oh, how come? What infra does that top-level file define?

It doesn't define any infrastructure, that is the point. It simply is being used to DRY up the config. In my case this means the `terraform { source = ... }` block and the `remote_state { ... }` block since I want those things to be the same for every sub-directory.

> Also, I'm guessing this is not the case originally described in this issue, but @estein9825 can correct me if I'm wrong.

Based on [this comment](https://github.com/gruntwork-io/terragrunt/issues/623#issuecomment-447657958) objecting to duplicating the `terraform { source = ... }` block in all children, I think it is pretty similar to my case, but hopefully we can get confirmation.

> Why build a mechanism to indicate this rather than just removing the `terraform { source = ... }` block from the top-level `terraform.tfvars`?

Because then my config isn't DRY. I want to define the `terraform { source = ... }` block in the top-level terraform.tfvars precisely because I want it to be the same in all the sub-directories and I will never override it. I can move it up if I really have to, but it creates a lot more work for me to update the version since I have this same structure for 30+ VMware ESX hosts which means I'm updating the version in close to 100 places doing it that way.

**Comment by brikis98** [comment]
> I have this same structure for 30+ VMware ESX hosts which means I'm updating the version in close to 100 places doing it that way.

Ah, so you're deploying 30+ separate copies of the exact same module? And you're using the top-level `terraform.tfvars` to be able to define which module once? If so, neat use case!

In that case, yes, merely checking for `source = "..."` is not enough. In that case, I think your option #2 makes the most sense. I think a `skip` parameter would be enough:

```hcl
terragrunt = {
  skip = true
}
```

When set to `true`, if you run `apply` or `apply-all` on the module (or any other command), it logs clearly that it's being skipped, and moves on without making any changes. That would provide a way to skip modules permanently (such as in your use case) and temporarily (e.g., when you want to run `apply-all` on a bunch of stuff, but skip one particular child module).

PR for that is welcome!

**Comment by brikis98** [comment]
#663 added support for `skip`.
