### ISSUE TITLE
Best Practice Question: "root" module naming convention?

### ISSUE THREAD

**Issue by jhoblitt** [gruntwork-io/terragrunt#630]
This question is about module naming conventions (repo or paths) when it is convenient to have a generic mod for the service and a separate "root" mod, which has provider configs/etc.  As an example, I have mods which use `kubernetes_*` resources that, in theory, should be deployable into any existing k8s cluster and it may be desirable to host multiple services within the same k8s cluster in different namespaces. Thus, these k8s mods need to be composable and not configure providers. 

However, the "root" module, as in what should be `source`d by terragrunt, typically needs to configure the k8s/aws/google/helm/etc. providers, standup a gke/eks/kops cluster, and use one or more service mods.  Is there any community consensus on the appropriate naming convention for mods that are intended to be used as the "root" mod?

If the "service" mod (as a git repo name) was `terraform-<service>` or `terraform-k8s-<service>`, what would be correct pattern for naming the "root" mod?

Perhaps something like:

- `terraform-root-<service>`
- `terraform-deploy-<service>`
- `deploy-<service>`

???

**Comment by brikis98** [comment]
Great question! We've been thinking about this and have not yet settled on a naming convention that we like. Including `root` in the name as you've indicated seems like one reasonable approach. Another is to have two subfolders, one called something like `modules`, which contains reusable/generic modules, and one called something like `environments` or `root` or `deployable` that defines the "root" modules that define `providers` and where you actually run `apply`.

**Comment by yorinasub17** [comment]
Closing as the original question has been answered. If there are any follow ups, please open a new issue. Thanks!
