### ISSUE TITLE
Destroy single instance

### ISSUE THREAD

**Issue by prandelicious** [gruntwork-io/terragrunt#634]
How do I destroy a single resource created with Terragrunt?

**Comment by brikis98** [comment]
Terragrunt is just a wrapper for Terraform. To destroy all resources with Terraform, you'd run `terraform destroy`, so with Terragrunt, you'd run `terragrunt destroy`. To destroy a single resource with Terraform, you'd run `terraform destroy -target=<RESOURCE>`, so with Terragrunt, you'd run `terragrunt destroy -target=<RESOURCE>`.

**Comment by yorinasub17** [comment]
Closing this as the question has been answered. If there are any follow ups, please open a new issue. Thanks!

**Comment by rsun-thoughtworks** [comment]
The target is the folder name, right?

**Comment by zatricky** [comment]
I arrived here from Google wanting to confirm the same information - so including the answer here in case someone else also arrives from a search query:

The target is the resource as shown by a state list. In my case I was able to get the full list of resources from the state list - then could remove specifically the one resource I wanted to remove:

    $ terragrunt state list
    [... many other entries ...]
    helm_release.app_name
    $ terragrunt destroy -target helm_release.app_name
