### ISSUE TITLE
Workaround for interpolation in terraform.tfvars

### ISSUE THREAD

**Issue by rfasouliotis** [gruntwork-io/terragrunt#635]
Hello,

I am trying to figure out what the best way to get around the limitation of not being able to do interpolation within the terraform.tfvars file. 

I have several modules for setting up a EKS cluster (AWS). Two of the modules I am using are terraform-aws-modules/terraform-aws-eks and terraform-aws-modules/terraform-aws-alb. My folder structure looks like this:

```
infrastructure/
├─ eks/      
│  ├── data.tf
│  ├── resources.tf
│  ├── variables.tf
│  ├── main.tf
├─ alb/      
│  ├── data.tf
│  ├── resources.tf
│  ├── variables.tf
│  ├── main.tf
```
And in a separate repo, I have my terragrunt files:

```
staging/
├─ eks/      
│  ├── terraform.tf
├─ alb/      
│  ├── terraform.tf
```

I run the alb setup, and then I want to create EC2 instances (worker nodes) using the EKS module. For that, the module takes a list of maps that define the number of groups of instances.

infrastructure/eks/data.tf:

```
data "aws_lb_target_group" "test" {
  ...
}
```

infrastructure/eks/main.tf:

```
#Provider Definition
provider "aws" {
  region = "${var.aws_region}"
  profile = "${var.aws_profile}"
  #version does not support interpolation
  version = "~> 1.52"
}

#Remote state storage configuration
terraform {
  # The configuration for this backend will be filled in by Terragrunt
  backend "s3" {}
}

#Modules
module "eks" {
  source                = "terraform-aws-modules/eks/aws"
  version               = "2.0.0"

  ... 
  vpc_id                = "${data.aws_vpc.vpc.id}"
  worker_group_count    = "${var.eks_worker_group_count}"
  worker_groups         = "${var.eks_worker_groups}"
  ...
  
}
```
staging/eks/terraform.tf

```
#Terragrunt definition

terragrunt = {
  terraform {
    source = "git::ssh://git@github.com/xxxx/infrastructure.git//eks?ref=setup-1"
  }

  include {
    path = "${find_in_parent_folders()}"
  }
}

#Module Variables

eks_worker_group_count      = 2

#Worker definitions
eks_worker_groups = [
  { "name"                  = "k8s-worker-kiam-green"
    "ami_id"                = "ami-0a0b913ef3249b655"
     ...
    "target_group_arns"     =  "${data.aws_lb_target_group.test.arn}"  <== DOESN'T WORK
  },
  {
    "name" = "k8s-worker-other-green"
    "ami_id" = "ami-0a0b913ef3249b655"
    ...
    "target_group_arns"     =  "${data.aws_lb_target_group.test.arn}" <== DOESN'T WORK
  },
```

What's the recommended method of doing this, since I am unable to dynamically pass the target_group_arn within the variable definitions?

**Comment by brikis98** [comment]
Probably the best solution for now is to create a wrapper module for EKS that takes in the list of work names and AMI IDs and fills in the target group ARNs when calling the underlying EKS module.

**Comment by rfasouliotis** [comment]
Thanks @brikis98. I ended up using a null_resource and doing a map merge inside that.

**Comment by bradleyess** [comment]
@rfasouliotis - I'm facing the same issue here. I would be interested to see a snippet of how you've solved this. 

@brikis98 - I'm not sure I completely understand how to implement a wrapper module. Would you care to share more information?

**Comment by rfasouliotis** [comment]
@bradleyess sure.. Just FYI, my solution is not the greatest in the sense that I can't selectively apply Target Group ARNs. They get applied to all worker groups which is not ideal but works for now. I think once v0.12 comes out this will work a lot more efficiently. See below for how I ended up doing it:

staging/eks/terraform.tf

``` terraform
#Terragrunt definition

terragrunt = {
  terraform {
    source = "git::ssh://git@github.com/xxxx/infrastructure.git//eks?ref=setup-1"
  }

  include {
    path = "${find_in_parent_folders()}"
  }
}

#Module Variables

eks_worker_group_count      = 2

#Worker definitions
eks_worker_groups = [
  { "name"                  = "k8s-worker-kiam-green"
    "ami_id"                = "ami-0a0b913ef3249b655"
     ...
    # "target_group_arns"     =  "${data.aws_lb_target_group.test.arn}"  <== REMOVED
  },
  {
    "name" = "k8s-worker-other-green"
    "ami_id" = "ami-0a0b913ef3249b655"
    ...
    # "target_group_arns"     =  "${data.aws_lb_target_group.test.arn}" <== REMOVED
  },
```
 infrastructure/eks/main.tf:

``` terraform
#Provider Definition
provider "aws" {
  region = "${var.aws_region}"
  profile = "${var.aws_profile}"
  #version does not support interpolation
  version = "~> 1.52"
}

#Remote state storage configuration
terraform {
  # The configuration for this backend will be filled in by Terragrunt
  backend "s3" {}
}

#Local definitions
locals {
  ...
  #trigger the addition of the ASG Target Group ARN
  new_worker_groups = ["${null_resource.new_worker_nodes.*.triggers}"]    <== ADDED
}

#Modules
module "eks" {
  source                = "terraform-aws-modules/eks/aws"
  version               = "2.0.0"

  ... 
  vpc_id                = "${data.aws_vpc.vpc.id}"
  worker_group_count    = "${var.eks_worker_group_count}"
  # worker_groups         = "${var.eks_worker_groups}" <== REMOVED
  worker_groups            = "${local.new_worker_groups}" <== ADDED
  ...
  
}
```

 infrastructure/eks/resource.tf:

``` terraform

resource "null_resource" "new_worker_nodes" {
  count = "${var.eks_worker_group_count}"

  triggers = "${merge(var.eks_worker_groups[count.index], map("target_group_arns","${data.aws_lb_target_group.test.arn}"))}"
}
```

Hope this helps!

**Comment by danehrlich1** [comment]
One way is to just use `sed`. Create some initial pre-config script. If executing via Docker you can just put the necessary commands in your `entrypoint.sh` file. 

I know it's...`sed`, but actually [Helm](https://helm.sh/) started out as just an advanced collection of sed scripts......

**Comment by brikis98** [comment]
Marking as closed, as I believe the question has been answered: pretend Terragrunt doesn't exist, do your interpolations in Terraform code, and then deploy that Terraform code with Terragrunt after.
