### ISSUE TITLE
s3_bucket_tags and dynamodb_table_tags causes HCL parsing issue

### ISSUE THREAD

**Issue by 141984** [gruntwork-io/terragrunt#638]
While running `terragrunt init` with remote_state config for S3 backend containing dynamodb_table_tags or s3_bucket_tags I am getting the following error:

Using terragrunt version v0.14.7 and Terraform v0.11.11

` [terragrunt] YYYY/MM/DD HH:MM:SS Running command: terraform init -backend-config=bucket=terraform-state -backend-config=key=./terraform.tfstate -backend-config=region=xx-xxxx-xx -backend-config=encrypt=true -backend-config=dynamodb_table=terraform-state-lock -backend-config=dynamodb_table_tags=[map[Department:Engineering]]
invalid value "dynamodb_table_tags=[map[Department:Engineering]]" for flag -backend-config: Cannot parse value for variable ("[map[Department:Engineering]]") as valid HCL: At 1:6: unexpected token while parsing list: IDENT`

**Comment by 141984** [comment]
Hey @yorinasub17 , Thanks for pointing it out. I hadn't realzsed that I was running an old version. :)

**Comment by yorinasub17** [comment]
Feel free to reopen if you still see the issue on the latest version!
