### ISSUE TITLE
how to config seperate aws credentials for s3 remote bucket and aws provider?

### ISSUE THREAD

**Issue by jhoblitt** [gruntwork-io/terragrunt#642]
I just ran into a scenario where I want to store terragrunt/terraform state in the same s3 bucket as the rest of our dev/prod envs but manage aws resources under a different account.  I'm a bit loath to have to config credentials on the aws provider itself. I tried setting a `profile` on the tg remote state config but tg is still trying to use the AWS_* env vars.  `shared_credentials_file` seems to be ignored as well.  Is there any way to achieve a credentials split?

```
  remote_state {
    backend = "s3"

    config {
      profile        = "terragrunt-dm"
      ...
```

**Comment by brikis98** [comment]
You could set the [profile](https://www.terraform.io/docs/backends/types/s3.html#profile) setting in your `remote_state` to a profile configured for that other account. Or, alternatively, an [IAM Role to assume](https://www.terraform.io/docs/backends/types/s3.html#role_arn) in the other account.

**Comment by JoshiiSinfield** [comment]
@jhoblitt & @brikis98 This sounds like the same issue as #616 ?
