### ISSUE TITLE
Support terraform v0.12

### ISSUE THREAD

**Issue by devtook** [gruntwork-io/terragrunt#653]
hello, 
 I use Terraform v0.12.0-alpha4 and Terragrunt v0.18.0 to test  old code, but there will be parsing errors.

```
terragrunt = {
  terraform = {
    source = "./vsphere"

    extra_arguments   "custom_vars"   {
      commands = ["plan", "refresh", "import", "destroy"]
      required_var_files = [
      ]
    }
  }
```

```
Error: Missing key/value separator
  on terraform.tfvars line 4:
   2:   terraform = {
   3:     source = "./vsphere"
   4:     extra_arguments "custom_vars"  {
Expected an equals sign ("=") to mark the beginning of the attribute value.`
```
V0.12 will be released,  is this a Terragrunt problem or my configuration is wrong?
https://www.hashicorp.com/blog/terraform-0-1-2-preview
https://www.hashicorp.com/blog/terraform-0-12-preview-first-class-expressions
Terraform  HCL has been greatly improved.

**Comment by arledesma** [comment]
This is covered in #466

**Comment by brikis98** [comment]
Correct, Terragrunt has not yet been updated to work with Terraform 0.12. Please track #466 for details.
