### ISSUE TITLE
Query Regarding Official Modules with Terragrunt

### ISSUE THREAD

**Issue by ijaveed** [gruntwork-io/terragrunt#654]
I currently use terragrunt with my own custom terraform code. I want to use some official modules from the terraform repos such as

module "security-group_example_complete" {
  source  = "terraform-aws-modules/security-group/aws//examples/complete"
  version = "2.13.0"
}

Is this possible ? as I have tried to follow the (code dry ) methodology I currently successfully use but it is not finding my variables?

**Comment by brikis98** [comment]
You have to set whatever variables that module expects:

```hcl
module "security-group_example_complete" {
  source = "terraform-aws-modules/security-group/aws//examples/complete"
  version = "2.13.0"

  foo = "bar"
}
```

If you need to expose those variables so they can be set by Terragrunt, you have to declare them:

```hcl
module "security-group_example_complete" {
  source = "terraform-aws-modules/security-group/aws//examples/complete"
  version = "2.13.0"

  foo = "${var.foo}"
}

variable "foo" {}
```

**Comment by ijaveed** [comment]
Thank you @brikis98
