### ISSUE TITLE
How to define module with terragrunt.

### ISSUE THREAD

**Issue by mcollins02** [gruntwork-io/terragrunt#656]
Hello I'm pretty new to terragrunt and am receiving the below error trying to create an outputs file.
Initializing the backend...

Error: output 'ec2-private-ip': unknown module referenced: test
Error: output 'ec2-private_dns': unknown module referenced: test
Error: output 'ec2-instance-id': unknown module referenced: test
Error: output 'ec2-instance-id': reference to undefined module "test"
Error: output 'ec2-private-ip': reference to undefined module "test"
Error: output 'ec2-private_dns': reference to undefined module "test"

I've tried defining the module with this but I'm guessing its wrong and can't seem to understand how to correct and what I'm doing wrong:

terragrunt = {
  terraform {
    module "test" {
      source = "modules/ec2-instances"
  }
}

**Comment by brikis98** [comment]
Please check the docs in the readme. There's no `module "..." { ... }` in Terragrunt. Just `terraform { source = "..." }`.

**Comment by mcollins02** [comment]
So what would the equivalent look like in terragrunt to this? Because I'm not seeing how thats done, or I'm missing something.

main.tf file

module "test" {
  source = "..."
}

Outputs file

#Load Balancer Public DNS
output "aws_elb_public_dns" {
    value = "${aws_elb.web.dns_name}"
}

outputs file that calls module

#Load Balancer Public DNS
output "elb_dns_name" {
  value = "${module.test.aws_elb_public_dns}"
}

**Comment by brikis98** [comment]
You put the Terraform code you wrote above into `.tf` files in some folder `foo`. You then set the `source = "..."` portion in your Terragrunt config to point to `foo`.

**Comment by brikis98** [comment]
There are tons of examples in the README, including example repos. Please check those out!

**Comment by mcollins02** [comment]
I see now, you don't thank you for the help!
