### ISSUE TITLE
[feature]The benefit of a log level feature for the terragrunt logs.

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#662]
Currently I use below command to hide `terragrunt` related logs, and only show `terraform` logs. It is useful when running in cicd pipeline, the logs are clean and we can focus

    terragrunt plan 2>&1 |grep -v "\[terragrunt\]"

Are there direct way in `terragrunt`?

similar feature in terraform, I can enable the debug logs as `TF_LOG=debug` only when I need do that.

But when use `plan-all`, i can't show properly which module it is currently working on.  So need this feature in `terragrunt` directly, show necessary logs only. 

Only if I need enable terragrunt debug logs, I can enable it with option, such as `TG_LOG=debug`

**Comment by brikis98** [comment]
You can now configure the log level in Terragrunt: https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-level

**Comment by ozbillwang** [comment]
Thanks a lot.
