### ISSUE TITLE
When migrating over to Terragrunt, state seems to be empty when it is not

### ISSUE THREAD

**Issue by Genert** [gruntwork-io/terragrunt#664]
Continuing from #661 .When I changed this:

```
terraform {
  required_version = "0.11.11"

  backend "s3" {
    region                  = "eu-west-1"
    bucket                  = "infra.terraform.state"
    key                     = "aws/test/global/terraform.tfstate"
    dynamodb_table          = "infra.terraform.state"
    shared_credentials_file = "~/.aws/credentials"
    profile                 = "terraform"
  }
}
```

To following within "terraforms.tfvars"

```
terragrunt {
  terraform {
    required_version = "0.11.11"

    source = "../../..//modules/environment-global"

    # The configuration for this backend will be filled in by Terragrunt
    backend "s3" {
      region                  = "eu-west-1"
      bucket                  = "infra.terraform.state"
      key                     = "aws/test/global/terraform.tfstate"
      dynamodb_table          = "infra.terraform.state"
      shared_credentials_file = "~/.aws/credentials"
      profile                 = "terraform"
    }
  }
}
```

Then planning, etc. works as expected. However, it wants to create all those resources because the state seems to empty, but it is not! I checked the S3 buckets, all the files are intact there, I cannot figure out whether it is even reading it from specified place?

Any figures?

**Comment by Genert** [comment]
Interesting, I changed the key to "aws/doesthiswork/global/terraform.tfstate"

And applied changes, then I checked S3, but such folder does not even exist in the S3.

When running apply again, no changes are present as expected, but then again, when such folder does not exist and state file is not also found within the bucket, where the heck is it getting the state?

**Comment by autero1** [comment]
You can check https://github.com/gruntwork-io/terragrunt#filling-in-remote-state-settings-with-terragrunt for configuration reference.

**Comment by Genert** [comment]
I did follow the configuration reference.

When changing to the following:
```
terragrunt {
  terraform {
    source = "../../..//modules/environment-global"

    # The configuration for this backend will be filled in by Terragrunt
    backend "s3" {}
  }

  remote_state {
    backend = "s3"

    config {
      region                  = "eu-west-1"
      bucket                  = "infra.terraform.state"
      key                     = "aws/test/global/terraform.tfstate"
      dynamodb_table          = "infra.terraform.state"
      shared_credentials_file = "~/.aws/credentials"
      profile                 = "terraform"

      s3_bucket_tags {
        owner = "terragrunt integration test"
        name  = "Terraform state storage"
      }

      dynamodb_table_tags {
        owner = "terragrunt integration test"
        name  = "Terraform lock table"
      }
    }
  }
}
```

Following error appears:
```
[terragrunt] 2019/02/28 11:29:50 *awserr.baseError Error finding AWS credentials in file '~/.aws/credentials' (did you set the correct file name and/or profile?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/errors/errors.go:26 (0x10eb8c3)
/private/tmp/terragrunt-20181221-18379-fddas8/terragrunt-0.17.4/src/github.com/gruntwork-io/terragrunt/aws_helper/config.go:73 (0x1426807)
```

**Comment by brikis98** [comment]
> # The configuration for this backend will be filled in by Terragrunt
> backend "s3" {}

This goes into your Terraform code (`.tf` files), not the Terragrunt config.

> Error finding AWS credentials in file '~/.aws/credentials' (did you set the correct file name and/or profile?): NoCredentialProviders: no valid providers in chain. Deprecated.

It says the file doesn't exist. Does it? Did you run `aws configure`?

**Comment by Genert** [comment]
Added the the terraform backend empty configuration to the module within the .tf file. Nope, still same result.

Yep, did run aws configure indeed, still same problem.

**Comment by brikis98** [comment]
The issue may just be that Terragrunt and the AWS Go SDK do not run your profile through bash expansion, so `~/.aws/credentials` is not converted to `<your home dir>/aws/credentials`, but remains the literal value `~/.aws/credentials`, which doesn't work.

**Comment by brikis98** [comment]
BTW, if you're just using your default credentials file, you don't need to specify it explicitly. It should be found automatically by all AWS Go SDK tools.

**Comment by Genert** [comment]
Indeed, the configuration path has to be as "<your home dir>/aws/credentials", and it works! Thank you!

Interestingly, when I made following change:
```golang
if config.RoleArn != "" {
    sess.Config.Credentials = stscreds.NewCredentials(sess, config.RoleArn)
} else if terragruntOptions.IamRole != "" {
    sess.Config.Credentials = stscreds.NewCredentials(sess, terragruntOptions.IamRole)
} else {
    // Added this
    // See - https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-profiles
    sess.Config.Credentials = credentials.NewSharedCredentials("", config.Profile)
}
```

Then it also worked fine when just using "~/.aws/credentials"
