### ISSUE TITLE
Terragrunt Does not create S3 bucket when plan-all using multiple modules

### ISSUE THREAD

**Issue by catdemian** [gruntwork-io/terragrunt#665]
Trying https://github.com/gruntwork-io/terragrunt-infrastructure-live-example

Found that 
`$terragrunt plan-all` 
Does not create S3.  As stated in [https://github.com/gruntwork-io/terragrunt/pull/55](url) Terragrunt should create the S3 bucket

In order to debug i uploaded the following execution output
[execution.log](https://github.com/gruntwork-io/terragrunt/files/2914603/execution.log)

**Comment by brikis98** [comment]
You ran `plan-all` in what folder?

**Comment by catdemian** [comment]
./terragrunt-infrastructure-live-example.git/non-prod/us-east-1/qa

**Comment by brikis98** [comment]
Did you change the bucket name in the `terraform.tfvars` in `non-prod` to something of your own?

**Comment by catdemian** [comment]
Yes, I did it to test the s3 creation. Take a look at the execution log file I attached to the issue. Terragrunt apply-all asks permition to create it in each module, but it doesn't allow to type the answer (Y). So at the end it fails.

**Comment by brikis98** [comment]
Try with `--terragrunt-non-interactive`

**Comment by catdemian** [comment]
That worked.

**Comment by yorinasub17** [comment]
Closing as the original question has been answered.
