### ISSUE TITLE
Support lists in variables terraform.tfvars

### ISSUE THREAD

**Issue by mcollins02** [gruntwork-io/terragrunt#666]
Is there a way to convert the variable in the terraform.tfvars file to be able to use lists?
I'm trying to keep my code dry but some ec2s will need more than one security group attached, as well as subnets. How is this accomplished considering the error below?

Error: variable instance-sg should be type string, got list

terraform.tfvars
instance-sg                = ["sgid1", "sgid2", "sgid3"]

main.tf
resource "aws_instance" "instance" {
  ami                    = "${var.ami}"
  instance_type          = "${var.instance_type}"
  count                  = "${var.instance_number}"
  key_name               = "mike-sandbox1"
  vpc_security_group_ids = ["${var.instance-sg}"]

**Comment by autero1** [comment]
Hi @mcollins02 . Using lists is perfectly ok. I believe the issue here is the module you're referencing in your `terraform.tfvars`. If you check your `vars.tf` for your module and set the `var.instance-sg` `type` to `list`, you should be ok. Something like this:

```
# vars.tf
...
variable "instance_sg_ids" {
  description = "A list of security group IDs to associate with"
  type = "list"
  default = []
}
...
```

**Comment by brikis98** [comment]
Marking as closed since the question was answered. Feel free to open a new issue if you're still struggling.
