### ISSUE TITLE
update brew package

### ISSUE THREAD

**Issue by shaharmor** [gruntwork-io/terragrunt#67]
Hi,

The brew package is still at v0.3.

Any chance to get it updated to the latest?

**Comment by shaharmor** [comment]
https://github.com/Homebrew/homebrew-core/pull/7565

**Comment by brikis98** [comment]
Ha, to be perfectly honest, I didn't know someone created a brew package. I'm very happy to see that and thankful for you taking the time to update it!

**Comment by shaharmor** [comment]
updated
