### ISSUE TITLE
can't do terragrunt apply after terragrunt init with terraform v0.12.0-beta1

### ISSUE THREAD

**Issue by balan2010** [gruntwork-io/terragrunt#672]
Hey All,

   I am new to terraform and terragrunt, so any guidance on this is much appreciated. Steps I follow is as follows

step 1: in the root directory, run terragrunt init
step 2: from the same directory, run terragrunt plan 

when I do this, I am getting 

`➜  prod git:(master) ✗ terragrunt plan
[terragrunt] [/mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod] 2019/03/08 11:53:39 Running command: terraform --version
[terragrunt] 2019/03/08 11:53:40 Reading Terragrunt config file at /mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod/terraform.tfvars
[terragrunt] 2019/03/08 11:53:40 WARNING: no double-slash (//) found in source URL /mnt/c/Users/nagarajan_b/Documents/repository/terraform/templates/gcp/infra-foundation. Relative paths in downloaded Terraform code may not work.
[terragrunt] 2019/03/08 11:53:40 Cleaning up existing *.tf files in /mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod/.terragrunt-cache/arl7NdJeAWc8n6jqx5xtGgBKjV0/Uz5ujJJe2PR0nb9nJ5U6UVlyHKY
[terragrunt] 2019/03/08 11:53:40 Downloading Terraform configurations from file:///mnt/c/Users/nagarajan_b/Documents/repository/terraform/templates/gcp/infra-foundation into /mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod/.terragrunt-cache/arl7NdJeAWc8n6jqx5xtGgBKjV0/Uz5ujJJe2PR0nb9nJ5U6UVlyHKY using terraform init
[terragrunt] [/mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod] 2019/03/08 11:53:40 Backend config has changed from map[project:gcp-asxtst-terraform region:australia-southeast1 bucket:balan-terraform-state-bucket credentials: encryption_key: path:<nil> prefix:infra/prod/foundation] to map[bucket:balan-terraform-state-bucket prefix:infra/prod/foundation project:gcp-asxtst-terraform region:australia-southeast1]
[terragrunt] [/mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod] 2019/03/08 11:53:40 Initializing remote state for the gcs backend
[terragrunt] [/mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod] 2019/03/08 11:53:40 Running command: terraform init -backend-config=bucket=balan-terraform-state-bucket -backend-config=prefix=infra/prod/foundation -backend-config=project=gcp-asxtst-terraform -backend-config=region=australia-southeast1 -get=false -get-plugins=false -backend=false -from-module=file:///mnt/c/Users/nagarajan_b/Documents/repository/terraform/templates/gcp/infra-foundation -no-color /mnt/c/Users/nagarajan_b/Documents/repository/terraform/projects/gcp/infra-foundation/live/prod/.terragrunt-cache/arl7NdJeAWc8n6jqx5xtGgBKjV0/Uz5ujJJe2PR0nb9nJ5U6UVlyHKY
Copying configuration from "file:///mnt/c/Users/nagarajan_b/Documents/repository/terraform/templates/gcp/infra-foundation"...

Error: Can't populate non-empty directory

The target directory
.terragrunt-cache/arl7NdJeAWc8n6jqx5xtGgBKjV0/Uz5ujJJe2PR0nb9nJ5U6UVlyHKY is
not empty, so it cannot be initialized with the -from-module=... option.

[terragrunt] 2019/03/08 11:53:40 Hit multiple errors:
exit status 11`

could see terragrunt is  trying to re-download module into .terragrunt-cache. 

What I expect to happen is terragrunt plan to use existing cache directory to do the plan like terraform init and terraform plan does

To work around that I had to delete .terraform-cache directory between terragrunt init and terragrunt plan. 

I am wondering whether I am missing something here

Terraform version: 0.12-beta1
Terragrunt version:  v0.18.1

**Comment by brikis98** [comment]
Terraform 0.12 is not yet supported.

**Comment by balan2010** [comment]
Thanks for the quick reply - but when I delete .terraform-cache directory - I am able to create resources on gcp, is this expected

**Comment by balan2010** [comment]
Just to give bit more info - I am able to create, plan and delete resources with terragrunt version v0.18.1 on terraform 0.12-beta1. 

Only thing that is not working is to use already initialized folder.

**Comment by DrFaust92** [comment]
If deleting the cache folder helps, try adding `--terragrunt-source-update` to your command until 0.12 is support as a workaround.

**Comment by ozbillwang** [comment]
@balan2010 

How you can successfull y run with `terraform init` with terraform 0.12 beta1?

I got below error, any hints for me?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13fa280]

goroutine 1 [running]:
github.com/hashicorp/hcl2/hcl/hclsyntax.(*Body).PartialContent(0x0, 0x382e420, 0xc0005923c0, 0x29f8900, 0xc00054a0b0, 0x0, 0x0, 0x0)
	/opt/gopath/pkg/mod/github.com/hashicorp/hcl2@v0.0.0-20190226234159-7e26f2f34612/hcl/hclsyntax/structure.go:135 +0x80
github.com/hashicorp/terraform/configs.sniffCoreVersionRequirements(0x29f8900, 0xc00054a000, 0xa, 0x29f8900, 0xc00054a000, 0xc0002d41d0, 0x1, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config.go:156 +0x121
github.com/hashicorp/terraform/configs.(*Parser).loadConfigFile(0xc0004ca040, 0xc000789720, 0xa, 0x0, 0x0, 0x1, 0x10, 0x5)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config.go:42 +0xdc
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigFile(0xc0004ca040, 0xc000789720, 0xa, 0x0, 0x0, 0x4, 0xc000013cc2)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config.go:22 +0x44
github.com/hashicorp/terraform/configs.(*Parser).loadFiles(0xc0004ca040, 0xc0006fb650, 0x1, 0x1, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config_dir.go:76 +0x349
github.com/hashicorp/terraform/configs.(*Parser).LoadConfigDir(0xc0004ca040, 0x26b3d2d, 0x1, 0x0, 0x1, 0x10000c000734ef0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/configs/parser_config_dir.go:36 +0x124
github.com/hashicorp/terraform/command.(*Meta).loadSingleModule(0xc000564000, 0x26b3d2d, 0x1, 0xc00002e000, 0x248fd00, 0x256fba0, 0x3e49160)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_config.go:112 +0x158
github.com/hashicorp/terraform/command.(*Meta).loadBackendConfig(0xc000564000, 0x26b3d2d, 0x1, 0x1009bd3, 0x248fd00, 0x256fba0, 0x1)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_config.go:174 +0x3f
github.com/hashicorp/terraform/command.(*Meta).backendConfig(0xc000564000, 0xc00053bf60, 0x0, 0xc000735218, 0x0, 0x0, 0x23ec540)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:292 +0x5d6
github.com/hashicorp/terraform/command.(*Meta).backendFromConfig(0xc000564000, 0xc00053bf60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:358 +0x6f
github.com/hashicorp/terraform/command.(*Meta).Backend(0xc000564000, 0x0, 0x0, 0xc000735700, 0x1, 0x1, 0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/command/meta_backend.go:85 +0x5d1
github.com/hashicorp/terraform/command.(*InitCommand).Run(0xc000564000, 0xc0000385d0, 0xa, 0xb, 0xc0002aa300)
	/opt/gopath/src/github.com/hashicorp/terraform/command/init.go:306 +0x1794
github.com/mitchellh/cli.(*CLI).Run(0xc00029b040, 0xc00029b040, 0xc00042dd20, 0x1)
	/opt/gopath/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x207
main.wrappedMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:223 +0xb37
main.realMain(0x0)
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:100 +0xb7
main.main()
	/opt/gopath/src/github.com/hashicorp/terraform/main.go:36 +0x2e



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by balan2010** [comment]
@ozbillwang Not sure what is happening there.  were you upgrade from 11.x to 12

**Comment by balan2010** [comment]
@DrFaust92 Thanks for that.. it's working now

**Comment by ozbillwang** [comment]
@balan2010 

I did another test, cd to the terraform code directly, I can run with `terraform12 init ....` command which I copy from the output of `terragrunt init`, without option of `-from-module=....`
