### ISSUE TITLE
cache refresh option/command

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [gruntwork-io/terragrunt#682]
What about implement some flag similar to terraform's `-update=true`? Removing on every change .terragrunt_cache is pretty hacky

 Additionally some refresh-all command could be handy

What do you think?

**Comment by brikis98** [comment]
What are you trying to achieve? What cache are you hoping to update?

**Comment by tomaszkrzyzanowski** [comment]
.terragrunt_cache - now when I apply some configuration and for example my colleague do some changes in terragrunt module code(code pulled by terragrunt from **source**) I have to remove .terragrunt_cache dir for update cache when I have set **ref** to **branch** 

In fact I'm able to use commit hashes or tags and TG will handle this cache, but Terraform for example have such command/option and I think it would be nice to handle this like Terraform

**Comment by brikis98** [comment]
And `--terragrunt-source-update` is not enough because it blows away the entire `.terragrunt-cache` folder rather than the one module you're testing?

**Comment by tomaszkrzyzanowski** [comment]
@brikis98 i'm suprised because read the docs some time ago and wasn't seen this option

Sorry for bothering, this option is exactly what I need

Thanks!
