### ISSUE TITLE
function interpolation in run_cmd is inconsistent

### ISSUE THREAD

**Issue by ThisGuyCodes** [gruntwork-io/terragrunt#684]
This was originally just an issue with functions not being interpolated for `run_cmd` all the time, but in making and MVP to demonstrate I also found a self-contradictory error message.

`terraform.tfvars`
```hcl
terragrunt = {
  extra_arguments "it dern borkedtouch" {
    commands = ["${get_terraform_commands_that_need_vars()}"]

    arguments = [
      "-var",
      "alone=${run_cmd("echo", "-n", "${get_tfvars_dir()}")}",
      "-var",
      "before=${run_cmd("echo", "-n", "something_before/${get_tfvars_dir()}")}",
      "-var",
      "after=${run_cmd("echo", "-n", "${get_tfvars_dir()}/something_after")}",
    ]
  }
}

```

`main.tf`
```hcl
```

aaaand the log:
```
.../test ❯❯❯ terragrunt plan
[terragrunt] [/.../test] 2019/03/19 18:39:09 Running command: terraform --version
[terragrunt] 2019/03/19 18:39:09 Reading Terragrunt config file at /.../test/terraform.tfvars
[terragrunt] 2019/03/19 18:39:09 Running command: echo -n /.../test
/.../test[terragrunt] 2019/03/19 18:39:09 run_cmd output: [/.../test]
[terragrunt] 2019/03/19 18:39:09 Running command: echo -n something_before/${get_tfvars_dir()}
something_before/${get_tfvars_dir()}[terragrunt] 2019/03/19 18:39:09 run_cmd output: [something_before/${get_tfvars_dir()}]
[terragrunt] 2019/03/19 18:39:09 Running command: echo -n ${get_tfvars_dir()}/something_after
${get_tfvars_dir()}/something_after[terragrunt] 2019/03/19 18:39:09 run_cmd output: [${get_tfvars_dir()}/something_after]
[terragrunt] 2019/03/19 18:39:09 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${get_tfvars_dir()}, ${get_tfvars_dir()}'
[terragrunt] 2019/03/19 18:39:09 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
.../test ❯❯❯
```

Two things of note (only one is personally causing me problems):
1. observe that "alone" interpolates fine (apologies for the sensored directories); however "before" and "after" do not interpolate before running the command:
```
Running command: echo -n /.../test
Running command: echo -n something_before/${get_tfvars_dir()}
Running command: echo -n ${get_tfvars_dir()}/something_after
```

2. That final error message seems self-contradictory:
```
Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${get_tfvars_dir()}, ${get_tfvars_dir()}'
```

the "but got" is a result of two outputs containing interpolation, if only one command is run it looks even more confusing:
```
[terragrunt] 2019/03/19 18:50:32 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${get_tfvars_dir()}'
```

**Comment by brikis98** [comment]
I suspect that this is due to Terragrunt using a half-assed regex to parse interpolations instead of a proper HCL parser. As a result, the doubly-nested interpolations are likely causing your error, along with a confusing error message:

```hcl
${run_cmd("echo", "-n", "something_before/${get_tfvars_dir()}")}
```

The nested `${get_tfvars_dir()}` is probably what's triggering the bug.

As part of the HCL 2.0 / Terraform 12.0 upgrade, we will also need to move to a proper HCL parser for handling interpolations.

**Comment by ThisGuyCodes** [comment]
With a few hours of work, I was able to figure out how to use https://github.com/hashicorp/hcl2 and wrote a functional parser (including a custom function) in ~40 lines of code.

I'd be down to make a first pass at converting to use hcl2 this weekend if that's a desired path. Rather importantly the hcl2 package is backwards compatible with hcl + hil.

Alternatively I could only swap out the interpolation with the hil package (https://github.com/hashicorp/hil). However then there'll have to be more work later for the .12 update, where HCL + HIL merge into HCL2.

I think this move could result in a pretty dramatic simplification of config management for Terragrunt. To that end I'm having difficulty following some of the config package logic: can someone point me in a direction? I'm particularly interested in how `include` is handled.

Here's the entire code if you're curious:
```Go
package main

import (
	"fmt"

	"github.com/hashicorp/hcl2/hcl"
	"github.com/zclconf/go-cty/cty"
	"github.com/zclconf/go-cty/cty/function"

	"github.com/hashicorp/hcl2/gohcl"
	"github.com/hashicorp/hcl2/hclparse"
)

func main() {
	parser := hclparse.NewParser()
	f, _ := parser.ParseHCL([]byte(`var = "${mk_string("first", "second")}"`), "main.tf")

	val := map[string]string{}

	mkString := function.Spec{
		Params: []function.Parameter{
			{Type: cty.String},
			{Type: cty.String},
		},
		Type: function.StaticReturnType(cty.String),
		Impl: func(args []cty.Value, retType cty.Type) (cty.Value, error) {
			one, two := args[0].AsString(), args[1].AsString()

			return cty.StringVal("ran with " + one + " and " + two), nil
		},
	}

	context := hcl.EvalContext{
		Functions: map[string]function.Function{
			"mk_string": function.New(&mkString),
		},
	}

	gohcl.DecodeBody(f.Body, &context, &val)

	fmt.Printf("%v", val["var"])
}
```

**Comment by brikis98** [comment]
> I'd be down to make a first pass at converting to use hcl2 this weekend if that's a desired path. Rather importantly the hcl2 package is backwards compatible with hcl + hil.

That would be amazing ❤️ 

> Alternatively I could only swap out the interpolation with the hil package (https://github.com/hashicorp/hil). However then there'll have to be more work later for the .12 update, where HCL + HIL merge into HCL2.

I think creating a branch that switches to HCL 2 makes the most sense, as Terraform 0.12 is already on beta1.

Make sure to read through https://github.com/gruntwork-io/terragrunt/issues/466 for a discussion of how we were thinking of the Terraform 0.12 upgrade.

> To that end I'm having difficulty following some of the config package logic: can someone point me in a direction? I'm particularly interested in how include is handled.

Poorly 😁 

We parse the included config if one is specified: https://github.com/gruntwork-io/terragrunt/blob/master/config/config.go#L310

We then manually merge it with the current config: https://github.com/gruntwork-io/terragrunt/blob/master/config/config.go#L339

**Comment by brikis98** [comment]
Terragrunt now uses the HCL2 parser, including its support for first-class expressions, instead of hacky regex, so this issue should be fixed. https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.0
