### ISSUE TITLE
Terragrunt fails to load some modules on Windows 10

### ISSUE THREAD

**Issue by Genert** [gruntwork-io/terragrunt#686]
There seems to be problem with path resolving on Windows 10.

When executing terragrunt plan for instance, the terraform initializing fails with following reason:

```
[terragrunt] [C:\Work\Go_code\src\go.fiizy.com\terraform\environments\test\global] 2019/03/20 13:41:12 Running command: terraform init -backend-config=region=eu-west-1 -backend-config=bucket=infra.terraform.state -backend-config=key=aws/test/global/terraform.tfstate -backend-config=dynamodb_table=infra.terraform.state -backend-config=shared_credentials_file=/root/.aws/credentials -backend-config=profile=terraform
[0m[1mInitializing modules...[0m
- module.billing
- module.cloudtrail
- module.iam
[31mError downloading modules: Error loading modules: module iam: Error reading .terraform\modules\4b0b7dab969c04043f693ad0a1216651\policy_ec2_container_service_read_only.tf: open .terraform\modules\4b0b7dab969c04043f693ad0a1216651\policy_ec2_container_service_read_only.tf: The system cannot find the path specified.[0m[0m
[terragrunt] 2019/03/20 13:41:12 Hit multiple errors:
exit status 1
```

Although the file does EXIST within terragrunt-cache folder.

Is there any difference on Windows vs UNIX how paths are resolved?

Latest and greatest Terraform and Terragrunt versions are used.

**Comment by Genert** [comment]
@brikis98

**Comment by lorengordon** [comment]
@Genert Might be related to long filepaths on Windows. See workaround using TERRAGRUNT_DOWNLOAD to shorten the paths... https://github.com/gruntwork-io/terragrunt/issues/581#issuecomment-460051767

**Comment by harrineiman** [comment]
Thanks a bunch for the workarounds - it was definitely a long file path issue, we got a bit further with the TERRAGRUNT_DOWNLOAD workaround (though still chanced upon too long paths in the end) but actually got stuff working via Ubuntu and WSL.

**Comment by Genert** [comment]
In case of similar error, the problem seems to be Windows platform specific.

Nothing much to do as side https://github.com/gruntwork-io/terragrunt/issues/581#issuecomment-460051767
