### ISSUE TITLE
Mismatch versions when downloading from Assets

### ISSUE THREAD

**Issue by sopta** [gruntwork-io/terragrunt#688]
Hi there,

I just download the newest version of `terragrunt_darwin_386` from release notes. It seems that the URL is correct: `/gruntworkio/terragrunt/releases/download/v0.18.3/terragrunt_darwin_386`

However, the CLI command `terragrunt --version` show me a different version.

![Screenshot 2019-04-05 15 08 42](https://user-images.githubusercontent.com/3351693/55629960-cc9bc080-57b4-11e9-99a8-9fb0d7b1e89e.png)

Desired version: `v0.18.3`
Real version: `v0.17.4`

Could you take a look whether the binary file is correct?

Have a nice weekend.

**Comment by brikis98** [comment]
I just tried the binaries for darwin_386, darwin_amd64, and linux_amd64, and all report `v0.18.3` as expected for the `--version` command.

Have you downloaded or installed Terragrunt some other way previously? Perhaps you have an older version in your `PATH`? Try `which terragrunt`.

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue, please open a new ticket. Thanks!
