### ISSUE TITLE
add shell completion

### ISSUE THREAD

**Issue by fawaf** [gruntwork-io/terragrunt#689]
add shell completion for bash, zsh, and probably other shells as well.

**Comment by mavogel** [comment]
If switching to `spf13/cobra` as CLI is an option I'd be easy to provide the completion out of the box: `rootCmd.GenBashCompletion(os.Stdout)`

@autero1 is this an option or too big for a change? On the other hand we could also quickly rebuild the structure of the `terragrunt` commands and generate the completion. The downside is that is has to be kept in sync with the code.

**Comment by yorinasub17** [comment]
`urfave/cli` supports [bash completion](https://github.com/urfave/cli#bash-completion), but I think we will need something custom regardless of the underlying CLI library for this to work intuitively because of the way `terragrunt` works. E.g if you take a look at [how the commands are implemented](https://github.com/gruntwork-io/terragrunt/blob/master/cli/cli_app.go#L163), we aren't defining them as direct commands in the cli struct. This is because we can't define all the available options for most of the commands, since they are passed through to `terraform`.

Additionally, we need to somehow merge the `terragrunt` completion with the `terraform` completions. Otherwise, you get completion for `terragrunt` specific commands like `plan-all`, but not for `terraform` commands that are not explicitly defined in `terragrunt`.

**Comment by hanjunlee** [comment]
I started [the project](https://github.com/hanjunlee/terragrunt-oh-my-zsh-plugin) `oh-my-zsh` plugin of `terragrunt`. I have complete about zsh completion for `terraform` subcommands, options and resources (especially when you type `-target` option). But  I haven't complete all the options of `terragrunt` yet (only complete subcommand). 

I hope it is helpful to who are using `oh-my-zsh`. Thanks.

**Comment by GergelyKalmar** [comment]
Until this is implemented one can just set up terragrunt to at least complete terraform commands in bash by adding this line to ``.bashrc`` or ``.bash_aliases``:

``complete -C ~/.bin/terraform terragrunt``

Of course with the appropriate path to the terraform binary.

It also works fine with aliases:

```
alias tg='terragrunt'
complete -C ~/.bin/terraform tg
```

**Comment by sobi3ch** [comment]
This didn't work for me. I've instead use this brute-force solution
In `.bashrc` or `.bash_aliases` add this:
```
complete -W "$(terragrunt | grep -A123 "COMMANDS" | head -n-7 | grep '^   ' | awk '{ print $1 }' | grep -v '*' | xargs)" terragrunt tg
```

**Comment by levkohimins** [comment]
Resolved in [v0.53.4](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.53.4) release.

How enable tab completion [docs](https://terragrunt.gruntwork.io/docs/getting-started/install/#enable-tab-completion).

**Comment by antspy** [comment]
Is there a way to specify the .bashrc file to use when calling `terragrunt --install-autocomplete`? 

I would like to add this to my dockerfile, but the final user of the OS is different than the root user who is installing everything, so I would like to specify an output .bashrc file explicitly. I guess I can just add `complete -C /usr/bin/terragrunt terragrunt` myself to the bashrc file, but it would be nice to have a solution that doesn't drift from the proper one.

**Comment by eggbean** [comment]
@antspy not tested this, but I reckon it could work.

    bash --rcfile /home/rcfile -i -c "terragrunt --install-autocomplete"

**Comment by antspy** [comment]
Thank you, I can try! :)

**Comment by foreignmeloman** [comment]
To anyone coming here to find a better solution than `complete -C ~/.bin/terraform terragrunt` here is my GNU bash completion script which also completes flags and even suggests file/directory completion for the flags that expect it. Additionally it allows for a functional aliases like `tg` with same set of completions ([Solution above](https://github.com/gruntwork-io/terragrunt/issues/689#issuecomment-629161874) didn't work for me).

The script was written using GNU utils, so mac users might not have such a good experience. This is still work in progress, so please report any related issues in my repo.

To install just place it into your `~/.local/share/bash_completion.d/` or source it in your RC file.

UPDATE: Now the script also suggests completion for the tofu/terraform shortcuts as well.

https://github.com/foreignmeloman/dotfiles/blob/master/pyinfra/files/bash_completion/terragrunt.sh
