### ISSUE TITLE
Terragrunt is now available in Azure Dev Ops/VSTS!

### ISSUE THREAD

**Issue by cdesewell** [gruntwork-io/terragrunt#695]
Hi all, not sure if this is the right place to post but terragrunt can now be installed to Windows build agents in Azure Dev Ops/VSTS.

https://marketplace.visualstudio.com/items?itemName=BigAvocado.Terragrunt

**Comment by brikis98** [comment]
Oh, cool, thanks!

This may be worth adding to the README if you have time.

**Comment by sergiomcalzada** [comment]
It would be better if @jabba2324 could transfer the "ownership" of the project to gruntwork. :)
