### ISSUE TITLE
Parallelism of terragrunt *-all commands

### ISSUE THREAD

**Issue by ondrejklucka** [gruntwork-io/terragrunt#698]
Hi

When running our infra (100s of modules), too many processes get spawned at once and we start hitting memory issues among others.

Is there a way to limit number of processes spawned when running terragrunt *-all commands?
Also, tried Terraform's `-parallelism=n`, but with no luck.

Best regards
Ondrej

**Comment by brikis98** [comment]
See https://github.com/gruntwork-io/terragrunt/pull/636.

**Comment by ondrejklucka** [comment]
Thanks @brikis98 for the quick reply.

We have tested #636 (as mentioned above, on large infra of 100s of modules) and it seems to be working as expected.
