### ISSUE TITLE
outputs from modules or remote state

### ISSUE THREAD

**Issue by jezzpashby** [gruntwork-io/terragrunt#706]
I can see lots of post on this but for the life of me, I cannot find an example of how to do this.  I appreciate that tfvars files cannot interpolate, so how exactly can I combine .tf files with remote state values with tfvars and terragrunt?  Ideally, I would like to just use outputs from other modules but doesn't seem possible to do so with Terragrunt?

I have tried the following to build a security group (already done)and then attach to new EC2 instance.

**terraform.tfvars**

```
terragrunt = {
  remote_state {
...
    }
  }

  # Include all settings from the root terraform.tfvars file
  include = {
    path = "${find_in_parent_folders("region.tfvars")}"
  }

  terraform {
    source = "terraform-aws-modules/terraform-aws-ec2-instance"

    extra_arguments "-var-file" {
      commands = ["${get_terraform_commands_that_need_vars()}"]

      optional_var_files = [
        "${get_tfvars_dir()}/${find_in_parent_folders("region.tfvars", "ignore")}",
      ]
    }
  }
}

...

vpc_security_group_ids = ["${data.terraform_remote_state.sec_grp.this_security_group_id}"]

```

**backend.tf**

```
terraform {
  backend "s3" {}
}

data "terraform_remote_state" "sec_grp" {
  backend = "s3"
  config {
    bucket = "bucket"
    key = "sec_grp.tfstate"
    region = "eu-west-1"
  }

}
```

With this, I get the following error 

> [terragrunt] 2019/05/16 12:53:27 Invalid interpolation syntax. Expected syntax of the form '${function_name()}', but got '${data.terraform_remote_state.sec_grp.this_security_group_id}'

Any help would be so awesome, thank you!

**Comment by brikis98** [comment]
Put the `terraform_remote_state` in your Terraform code (`.tf`), not your `.tfvars` files.

**Comment by yorinasub17** [comment]
Closing as stale. In addition to the comment above, there is also now `dependency` blocks, with an example [documented here](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules). If there are any follow up questions, please file a new issue. Thanks!
