### ISSUE TITLE
Feedback on the new spin-up and and tear-down commands.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/terragrunt#71]
I'm going to leave this as an open issue to report and collect feedback on `terragrunt spin-up` and `terragrunt tear-down`.

Overall, it's a joy to use! But was it Thoreau who warned that with each new technology we both gain and lose? With `spin-up` the gains are the ability to launch a lot of infra _fast_ while preserving terraform state isolation, and by extension the ability to launch a whole environment fast. These are wonderful wins. The loss is that I'm less aware of the details of each individual `terragrunt apply`.

For example, I had an issue where a git tag of one of my Terraform modules (module-security) was downloaded, but it was out of date. I'd needed to re-issue a git tag to fix a minor issue, but terraform won't automatically check for new versions of a git tag of an already downloaded module (which is reasonable behavior). If I hadn't manually inspected the results, I wouldn't have seen that in fact terraform was using an outdated module version.

It made me wonder if the `spin-up` paradigm demands a new level of guardrails. For example, should terragrunt do a `terraform get -update` on every module to be safe? Perhaps that's an option since there will be a performance hit with that.

Not sure, so just recording initial thoughts.

**Comment by josh-padnick** [comment]
Ran into another issue around `terraform get`. I expected terragrunt to automatically run `terraform get -update` when it detected no `.terraform` folder, but it failed to do so. While using `terragrunt spin-up` on a fresh folder (i.e. no `.terraform` folder), I got this:

```
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:11 Module /repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc must wait for 0 dependencies to finish
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:11 Running module /repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc now
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:11 Reading Terragrunt config file at /repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc/.terragrunt
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:11 Initializing remote state for the s3 backend
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:12 Configuring remote state for the s3 backend
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:12 Running command: terraform remote config -backend s3 -backend-config=key=mgmt/vpc/terraform.tfstate -backend-config=region=us-west-2 -backend-config=encrypt=true -backend-config=bucket=<redacted>-terraform-remote-state
Initialized blank state with remote state enabled!
Remote state configured and pulled.
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:13 Attempting to acquire lock for state file mgmt/vpc in DynamoDB
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:14 Attempting to create lock item for state file mgmt/vpc in DynamoDB table terragrunt_locks
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:15 Lock acquired!
[terragrunt] [/repos/gruntwork-clients/<redacted>/infrastructure-live/mgmt/vpc] 2016/12/12 18:57:15 Running command: terraform apply -input=false
Error downloading modules: module vpc: not found, may need to be downloaded using 'terraform get'
```

Running `terragrunt apply` directly from the folder led to this output:

```
terragrunt apply
[terragrunt] 2016/12/12 19:02:05 Reading Terragrunt config file at .terragrunt
[terragrunt] 2016/12/12 19:02:05 Running command: terraform get -update
```

So it works directly, but no with `spin-up`. I'll quickly check out the code to see if I can spot the issue.

**Comment by josh-padnick** [comment]
@brikis98 Looks like the issue starts at https://github.com/gruntwork-io/terragrunt/blob/0b44d4ed8def92ed961af97827a3564ebcc6ec03/cli/cli_app.go#L105-L109. Tracing that code through, it doesn't appear to ever call `terraform get -update`. I'm in a time crunch so I'll just manually do updates for now, but surprised this wasn't picked up in tests?

**Comment by brikis98** [comment]
Thanks for the feedback! Glad it's working well for you.

#73 should fix the issue with `terraform get`. 

#74 will make it a little bit easier to deal with all the log output by saving it to individual files (anyone out there looking for an easy PR to contribute?)

I'm open to other suggestions for guard rails we could add!

**Comment by josh-padnick** [comment]
+1 on #74. Validated #73 today with a client and works great. Heard other feedback today about doing linting with Terraform, but that goes outside the scope of Terragrunt today.

**Comment by josh-padnick** [comment]
General purpose issues are hard to track, so I'm going to close this issue and open one issue per thought.

**Comment by tamsky** [comment]
Is there a way to limit the number of concurrent fork/exec's of `terraform` during `spin-up` ?
This could make the output easier to read and parse (until #74) arrives.

**Comment by brikis98** [comment]
There's nothing built into the code to do that. Setting the `GOMAXPROCS` environment variable ([link](https://golang.org/pkg/runtime/)) to a lower number *might* help a bit, depending on how Go chooses to schedule goroutines on your OS.
