### ISSUE TITLE
Terragrunt not installing plugins

### ISSUE THREAD

**Issue by wblakecannon** [gruntwork-io/terragrunt#710]
I successfully ran `terraform init` and now when I go into a module and run `terragrunt init` I get the following error:

```
The following provider constraints are not met by the currently-installed
provider plugins:

* aws (any version)

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/darwin_amd64

Error: missing provider "aws"
```

I've tried adding `-get-plugins=true` to the command line after `terragrunt init` and still get the error.

It was my understanding that the plugins are installed during the `terraform init` command.

**Comment by yorinasub17** [comment]
Sorry for the delay in answering this. Can you share your folder structure, including `main.tf` for terraform modules and `terraform.tfvars` files for terragrunt configs?

`terraform init` and `terragrunt init` do different things (specifically, the folder where they download the providers are different), so it helps to know your folder structure.

**Comment by ischenkomari** [comment]
Also have the same, even more argument get-plugins doesn't overwrite:
Running command: terraform init -backend-config=bucket=bucket -backend-config=key=state/file.tfstate -backend-config=encrypt=true -backend-config=region=eu-west-1 -get-plugins=true -plugin-dir=/my/terraform/plugin/dir -get=false -get-plugins=false -backend=false -from-module=file:/module...

terragrunt {
    terraform {
        source = "${path_relative_from_include()}/../module"
        extra_arguments "init_args" {
      commands = [
        "init"
      ]

      arguments = [
        "-get-plugins=true",
        "-plugin-dir=/my/terraform/plugin/dir",
      ]
      }
    }
    remote_state {
        backend = "s3"
        config {
            region = "eu-west-1"
            bucket = ...
        }
    }
}

Folder structure:

├── working_dir
│   ├── extra.tf
│   └── terraform.tfvars
├── extra.tf
└── module
    ├── main.tf
    ├── outputs.tf
    └── variables.tf

**Comment by yorinasub17** [comment]
Ah it looks like we are always setting `-get-plugins=false`. This might be a regression from https://github.com/gruntwork-io/terragrunt/releases/tag/v0.16.6. @brikis98 do you know the context here for why we did this change, and what you mean by "These will all be handled in a later call to init instead"? I think that is what the issue is: there is some confusion on when the later call to init happens.

**Comment by brikis98** [comment]
We call `terraform init -from-module=xxx` to download code specified via the `source` param. Here, we want _just_ the code, and not any plugins, state, etc. Later, we call `terraform init` again to get the plugins, state, etc. See https://github.com/gruntwork-io/terragrunt#auto-init and https://github.com/gruntwork-io/terragrunt#extra_arguments-for-init.

**Comment by ischenkomari** [comment]
@yorinasub17 , you are right, it's confusion, and later in call` terraform init` as it should be

**Comment by yorinasub17** [comment]
Closing as stale. We have had a few enhancements since this post. I don't have clarity on whether this specific issue is resolved or not, but if this is still an issue in newer versions of terragrunt, please open a new issue with a reproducible example `terragrunt.hcl`. Thanks!
