### ISSUE TITLE
Terragrunt 0.18.6 and Terraform 0.12

### ISSUE THREAD

**Issue by KevDBG** [gruntwork-io/terragrunt#713]
Hello,

I tried to upgrade my terraform version to 0.12 and now i have many problems...

I think, there have bean significant changes in this new terraform version ... 

Examples of error:

```
Error: Missing key/value separator
  on terraform.tfvars line 14:
  10:
  11:
  12:
  14:     extra_arguments "common_var" {

Expected an equals sign ("=") to mark the beginning of the attribute value.
```

```
Error: Function calls not allowed

  on terraform.tfvars line 7:
   7:     path = "${find_in_parent_folders()}"

Functions may not be called here.
```

Do you plan to change and update terragrunt to handle these changes ?

Many thanks to the team !

**Comment by brikis98** [comment]
Discussion happening in #466. 0.12 upgrade is planned but not yet completed.
