### ISSUE TITLE
AWS S3 Backend with Explicit KMS key

### ISSUE THREAD

**Issue by DrFaust92** [gruntwork-io/terragrunt#715]
i couldn't find something in the docs about this, but can you specify a KMS key for S3 Backend encryption?

if not i would like to work on this.

**Comment by yorinasub17** [comment]
AFAIK, we don't have support for specifying the KMS key (the support for SSE config was added in https://github.com/gruntwork-io/terragrunt/pull/645). PR is very welcome!

**Comment by DrFaust92** [comment]
Will Try!

**Comment by yorinasub17** [comment]
Actually, I just realized that you might want to hold off until the update for terraform 12 is complete. We are about to do a major refactoring of how the config is handled.

You can track https://github.com/gruntwork-io/terragrunt/issues/466 for the progress on that.

**Comment by DrFaust92** [comment]
Thanks, will hold off for now.

**Comment by DrFaust92** [comment]
Still relevant?

**Comment by yorinasub17** [comment]
Yup this is still relevant. The tf12 update is now done so feel free to contribute!

**Comment by yorinasub17** [comment]
Implemented in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.38.1
