### ISSUE TITLE
how to reference a lambda file path in module?

### ISSUE THREAD

**Issue by wollerman** [gruntwork-io/terragrunt#716]
I am working on some migrations to terragrunt, and one of the differences that is popping up for me is the file path referencing in a module. I saw the section on [important-gotcha-working-with-relative-file-paths ](https://github.com/gruntwork-io/terragrunt#important-gotcha-working-with-relative-file-paths) but I'm not sure if it 100% solves my issue.

I have a module that defines some lambda functions like this:

```
data "archive_file" "my_lambda" {

  source_dir = "${path.module}/lambdas/my_lambda/"
  output_path = "${path.module}/files/my_lambda.zip"
  type = "zip"
}

resource "aws_lambda_function" "my_lambda" {
  function_name = "${var.env}-my_lambda"
  handler = "lambda_function.lambda_handler"
  role = "${aws_iam_role.cognito_lambda_exec.arn}"
  runtime = "python3.7"

  filename = "${path.module}/files/my_lambda.zip"
  source_code_hash  = "${data.archive_file.my_lambda.output_base64sha256}"
}
```

The issue is this path referencing is inside of the module. And the `terragrunt plan` output shows a difference in the `filename` because of the cache path:

```
~ aws_lambda_function.my_lambda
      filename:         "/path/to/dev/auth/files/my_lambda.zip" => "/path/to/dev/auth/.terragrunt-cache/uscEWNF84KnKEQjNJFwFFFImB2U/3thUgcaPQo2smLUsj9h01x1-TQk/modules/auth/files/my_lambda.zip"
      last_modified:    "2019-03-27T22:07:18.559+0000" => <computed>
```

If someone else runs this, the absolute path will obviously be different. It seems that using `path.module` isn't the correct approach here. So my question is how do I use the relative pathing *within* the module that terragrunt is running?

**Comment by yorinasub17** [comment]
Not sure if this is the best approach, but one way you can handle this is to use the terragrunt folder as the zip output folder. You can do this by exposing the lambda zip target folder as an input variable. Then, in the `tfvars` file, you can pass in the result of [`get_tfvars_dir`](https://github.com/gruntwork-io/terragrunt#get_tfvars_dir).

**Comment by wollerman** [comment]
Deos `get_tfvars_dir` work for module parameters? The [interpolation syntax](https://github.com/gruntwork-io/terragrunt#interpolation-syntax) documentation says 

> Note that Terragrunt built-in functions only work within a terragrunt = { ... } block.

**Comment by yorinasub17** [comment]
Ah that's right... Sorry about the misleading suggestion. Then in that case, I think the best approach is to use the temp directory so that it is consistent.

Given how terragrunt works, I am not sure it is possible to get relative paths working in a way such that the filenames are different.

**Comment by wollerman** [comment]
Can you elaborate? I'm not sure what you mean by "use the temp directory so that it is consistent"?

**Comment by yorinasub17** [comment]
I mean to use the temp directory of your operating system (`/tmp` for unix based systems). This is not ideal, but as long as the OS is consistent across your deployment pipelines, the filename will be consistent.

**Comment by wollerman** [comment]
What if I use an `extra_arguments` variable that resolves the directory and use that as my input variable? The only quirk with that is then every command for every module will use that variable (because I have terragrunt set up to run multiple modules at once).

e.g.
```
terragrunt = {

  # Configure Terragrunt to automatically store tfstate files in an S3 bucket
  remote_state {
    backend = "s3"

    config {
      # ...config here
    }
  }

  terraform {
     # Pass custom var files to Terraform
    extra_arguments "custom_vars" {
      commands = [
        "validate",
        "apply",
        "plan",
        "import",
        "push",
        "refresh"
      ]

      arguments = [
        "-var", "lambda_dir=get_tfvars_dir()/lambda_dir"
      ]
    }
  }

}
```

Is there a way to set an extra argument for only a specific child module?

**Comment by wollerman** [comment]
> I mean to use the temp directory of your operating system (`/tmp` for unix based systems). This is not ideal, but as long as the OS is consistent across your deployment pipelines, the filename will be consistent.

I see. Yes that isn't ideal.

**Comment by yorinasub17** [comment]
IIRC, I believe `extra_arguments` would work at the leaf level even if it is already defined at the top level, since you can define multiple `extra_arguments` block, it should be a merge as opposed to an override. I am not 100% sure though so I would suggest trying it out.

**Comment by wollerman** [comment]
Ah perfect! I missed that part of the docs. So using the arguments at the leaf level works. 

And actually using `get_tfvars_dir()` isn't exactly what I want. This causes the full path to be resolved
e.g. now the filename is `/Users/path/to/infrastructure/files/lambda.zip` as opposed to being in `/Users/path/to/infrastructure/.terragrunt-cache/somecache/files/lambda.zip` which isn't ideal because the full path will change.

I think just your first suggestion by itself of pulling out the path into a variable is the solution. So if I just add the `lambda_dir = "lambda_dir"` to the bottom of my `.tfvars` it becomes a relative path!

Thanks for your help @yorinasub17 !

**Comment by sauln** [comment]
Hi @wollerman  I know it's been a long time, but I was hoping you could provide a bit more details for what you mean by 
> So if I just add the lambda_dir = "lambda_dir" to the bottom of my .tfvars it becomes a relative path!

I'm struggling with this same problem now and am not following what your solution was.

Thank you!

**Comment by wollerman** [comment]
@sauln no worries. Took me a minute to remember what this thread was about, but I found the relevant bits.

Here's an example of something in a module:

```
data "archive_file" "my_lambda" {

  source_dir = "${path.module}/lambdas/my_lambda/"
  output_path = "${path.module}/files/my_lambda.zip"
  type = "zip"
}

resource "aws_lambda_function" "my_lambda" {
  function_name = "${var.env}-my_lambda"
  handler = "lambda_function.lambda_handler"
  role = "${aws_iam_role.cognito_lambda_exec.arn}"
  runtime = "python3.7"

  filename = "${var.zip_output_dir}/files/my_lambda.zip" // <----- specify root dir as a var
  source_code_hash  = "${data.archive_file.my_lambda.output_base64sha256}"
}
```

Then when going to use that module with terragrunt you would do something like this:
```
terraform {
  source = "my-source-id"
}

include {
  path = "${find_in_parent_folders()}"
}

// this variable is needed so that the module can correctly generate a zip
// and then later reference that zip in a relative manner. Otherwise the path
// becomes dependent on the particular `.terragrunt-cache` directory.
inputs = {
  zip_output_dir = "files"
}
```
