### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by ziggy42** [gruntwork-io/terragrunt#717]
Is [this](https://snapcraft.io/terragrunt) an official snap for this project? If not, do you think would be possible to add one?

**Comment by yorinasub17** [comment]
Unfortunately, we don't maintain official packages (apt, snap, brew, etc) at the moment. All the ones out there are maintained by the community, and we haven't gotten around to building up a pipeline to maintain official ones yet.

**Comment by maver1ck** [comment]
Have you thought about adding travis build to the repo to make snap package ?

**Comment by yorinasub17** [comment]
Closing as won't fix. We (Terragrunt maintainers) don't have the resources to support different packaging formats, but if someone from the community wants to maintain one, we'd be happy to link to it in the docs.
