### ISSUE TITLE
Error: Can't populate non-empty directory

### ISSUE THREAD

**Issue by mikeharrisonnz** [gruntwork-io/terragrunt#718]
terragrunt version v0.18.6

Terraform version Terraform v0.12.0

The target directory
.terragrunt-cache/tkAuoxYyBKOO-b1dnFIVpIobyCc/0c1uD6T9GiT55UkrwoBMvDMWD64 is
not empty, so it cannot be initialized with the -from-module=... option.

terragrunt] [/Users/mike/terragrunt-infrastructure-live/development/vpc] 2019/05/30 19:28:03 Running command: terraform --version
[terragrunt] 2019/05/30 19:28:03 Reading Terragrunt config file at /Users/mike/terragrunt-infrastructure-live/development/vpc/terraform.tfvars
[terragrunt] 2019/05/30 19:28:03 The --terragrunt-source-update flag is set, so deleting the temporary folder /Users/mike/terragrunt-infrastructure-live/development/vpc/.terragrunt-cache/tkAuoxYyBKOO-b1dnFIVpIobyCc/0c1uD6T9GiT55UkrwoBMvDMWD64 before downloading source.
[terragrunt] 2019/05/30 19:28:03 Downloading Terraform configurations from git::ssh://git@bitbucket.org/${name}/terragrunt-infrastructure-modules into /Users/mike/terragrunt-infrastructure-live/development/vpc/.terragrunt-cache/tkAuoxYyBKOO-b1dnFIVpIobyCc/0c1uD6T9GiT55UkrwoBMvDMWD64 using terraform init
[terragrunt] [/Users/mike/terragrunt-infrastructure-live/development/vpc] 2019/05/30 19:28:03 Initializing remote state for the s3 backend
[terragrunt] [/Users/mike/terragrunt-infrastructure-live/development/vpc] 2019/05/30 19:28:03 Running command: terraform init -backend-config=region=eu-west-1 -backend-config=profile=dev -backend-config=encrypt=true -backend-config=dynamodb_table=terraform-locks -backend-config=bucket={state-bucket}-env-state -backend-config=key=vpc/terraform.tfstate -get=false -get-plugins=false -backend=false -from-module=git::ssh://git@bitbucket.org/${name}/terragrunt-infrastructure-modules -no-color /Users/mike/terragrunt-infrastructure-live/development/vpc/.terragrunt-cache/tkAuoxYyBKOO-b1dnFIVpIobyCc/0c1uD6T9GiT55UkrwoBMvDMWD64

Copying configuration from "git::ssh://git@bitbucket.org/{name}/terragrunt-infrastructure-modules"...
Error: Can't populate non-empty directory

The target directory
.terragrunt-cache/tkAuoxYyBKOO-b1dnFIVpIobyCc/0c1uD6T9GiT55UkrwoBMvDMWD64 is
not empty, so it cannot be initialized with the -from-module=... option.

Troubleshooting steps
rm  -rf .terragrunt-cache/ 
find . -type d -name ".terragrunt-cache" -prune -exec rm -rf {} \;
Uninstalled Terragrunt & Terraform, removed all repos from the local machine.

Rolled back to previous Terragrunt Version.

**Comment by yorinasub17** [comment]
Hi sorry, Terragrunt has not yet been updated to be compatible with Terraform 0.12. We're working on it! Follow along in https://github.com/gruntwork-io/terragrunt/issues/466.

Closing as duplicate.
