### ISSUE TITLE
Dynamo Db Lock Table TTLs for locks

### ISSUE THREAD

**Issue by asaf-erlich** [gruntwork-io/terragrunt#721]
The problem that's being solved is that there are many reasons why a process running terraform might die in the middle. In my use case Jenkins workers die during master restart (a bad architecture, normally that isn't supposed to happen with Jenkins, but I don't want to get into that). This leaves locks in a locked state that someone has to take manual action to unlock. There are cleanup jobs that try to clean up left over AWS resources. It would be very nice if they retried hours later and the locks were simply gone. 

Dynamo db tables already offer a way to add a row / value with a TTL: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/time-to-live-ttl-how-to.html

It would be very nice if this could be just something that is configured. My suggestion is just to add a value for ttl inside the terragrunt config, like dynamodb_lock_ttl. From an implementation point of view if the value is not set for an existing table and it needs to be enabled this could be problematic. But terragrunt could just throw a warning that it only supports ttl for the newly created tables.

Thank you,
-Asaf

**Comment by asaf-erlich** [comment]
I'm actually not sure if dynamo db locks are a terraform or terragrunt controlled thing. Should this issue be created in terraform? Please let me know.

**Comment by yorinasub17** [comment]
Hi,

This is actually a limitation of `terraform` and not `terragrunt`. The locking is all done by terraform, so if it doesn't support the TTL, then we can't really expose it in `terragrunt`. I searched through the `terraform` repo and found [this issue](https://github.com/hashicorp/terraform/issues/15429) which appears to be the most relevant.

I am going to close this, but would suggest bumping that issue in the `terraform` repo to hear what they have to say about supporting this feature. Sorry I don't have any better news for you here...

**Comment by asaf-erlich** [comment]
Thank you @yorinasub17 I created a github issue in terraform: https://github.com/hashicorp/terraform/issues/21671
