### ISSUE TITLE
Terragrunt Console Garbles STDIN/STDOUT Streams

### ISSUE THREAD

**Issue by Tensho** [gruntwork-io/terragrunt#724]
I experience a strange behavior with **`terragrunt console`** command. When I try to run the next command:

    $ terragrunt console --terragrunt-source ...
    ...
    [terragrunt] 2019/06/04 13:35:06 Running command: terraform console
    Acquiring state lock. This may take a few moments...

    <Ctrl + C>

    Releasing state lock. This may take a few moments...

it looks like `terragrunt` hangs on **acquiring state lock forever**. However, if I change directory to `terragrunt` cache directory an try to run console manually through `terraform` CLI everything works as expected:

```
$ cd .terragrunt-cache/rXnIXItbUZO3QgycMk-_hiaL6ek/ZzjeLbJj6m48XPN-IEhSqTgSFCE
$ terraform console
Acquiring state lock. This may take a few moments...
> aws_route53_zone.this.zone_id
FAKE5JTM3YS01O
> exit
Releasing state lock. This may take a few moments...
```
All other `terragrunt` commands work as expected.
 
Later I found **`terragrunt console`** actually hides the console prompt and typed characters, but outputs results:
```
[terragrunt] 2019/06/04 13:35:06 Running command: terraform console
Acquiring state lock. This may take a few moments...

<hit Enter>
parse error at 1:3: expected expression but found ">"

<type 1>
1

<type aws_route53_zone.this.zone_id>
FAKE5JTM3YS01O
```
Seems like `terragrunt` garbles STDIN/STDOUT streams.

**Comment by Tensho** [comment]
Ah, I've just realized `terragrunt` hides the console prompt and typed characters, but outputs results:
```
[terragrunt] 2019/06/04 13:35:06 Running command: terraform console
Acquiring state lock. This may take a few moments...

<hit Enter>
parse error at 1:3: expected expression but found ">"

<type 1>
1

<type aws_route53_zone.this.zone_id>
FAKE5JTM3YS01O
```
Seems like `terragrunt` garbles STDIN/STDOUT streams.

**Comment by udondan** [comment]
Confirming this, observed the same behavior

**Comment by edjackson-wf** [comment]
It looks to me like the `>` prompt and keyboard input are just not echoed to the screen. While I can't see what I'm typing, the correct output is actually displayed if I enter a valid expression.

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.21.8. Binaries will show up shortly.

**Comment by Tensho** [comment]
@yorinasub17 You rock! Thank you!
