### ISSUE TITLE
Error downloading modules

### ISSUE THREAD

**Issue by abhijeetsingh26** [gruntwork-io/terragrunt#729]
Not sure if its the correct place to ask. I did look for a discussion forum, but did not any.

Here is the issue:

Initializing modules...

module.asg
Getting source "git::git@github.com:gruntwork-io/module-asg.git//modules/asg-rolling-deploy?ref=v0.6.24"
Error downloading modules: Error loading modules: error downloading 'ssh://git@github.com/gruntwork-io/module-asg.git?ref=v0.6.24': /usr/bin/git exited with 128: Cloning into '.terraform/modules/d7dc91a99408d1c9f2fd71251176ba6a'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Please help.

**Comment by brikis98** [comment]
`git::git@github.com:gruntwork-io/module-asg.git` is a private Git repo. Do you have access to it?

**Comment by abhinaba-chakraborty-by** [comment]
@brikis98 facing same issue when trying to run `terragrunt validate-all` in github actions of my private repo... 

My terragunt.hcl file looks like this:

```
terraform {
  source = "git::git@github.com:innovationnorway/terraform-azurerm-web-app-container.git?ref=v2.6.0"

  extra_arguments "custom_vars" {
    commands = get_terraform_commands_that_need_vars()

    arguments = [
      "-var-file=${get_terragrunt_dir()}/../regional.tfvars",
      "-var-file=${get_terragrunt_dir()}/../../environment.tfvars"
    ]
  }

}

include {
  path = find_in_parent_folders()
}


inputs = {

  name            = "appsvc-demo-app"
  container_type  = "docker"
  container_image = "alpine"
  always_on       = true
  https_only      = true
  plan = {
    sku_size = "S1"
  }

}
```

Getting the following error:

```
error downloading 'ssh://git@github.com/innovationnorway/terraform-azurerm-web-app-container.git?ref=v2.6.0': /usr/bin/git exited with 128: Cloning into '/home/runner/work/retail-eso-infra/retail-eso-infra/sandbox/eastus2/webapp-foodsvc/.terragrunt-cache/EQVzV5g-eBYxX9tLqPXwpgtin3Y/nVbvgOesvkok-P3th54kBomWdE8'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by yorinasub17** [comment]
Closing as stale. If this is still a concern, please open a new issue. Thanks!
