### ISSUE TITLE
failed to run mklink

### ISSUE THREAD

**Issue by mmclane** [gruntwork-io/terragrunt#733]
I just upgraded to terragrunt v0.19.0 this morning.  I am running Terraform v0.12.1.  I am running on Windows with Powershell.  I am trying to setup an example repo based on terragrunt to show to my team for possible adoption.  

When I run terragrunt init or terragrunt plan I get the following:

terragrunt init
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\prod\network] 2019/06/10 10:11:48 Running command: terraform --version
[terragrunt] 2019/06/10 10:11:48 Reading Terragrunt config file at C:/Users/matt.mclane/repos/llamasoft/terraform/environments/prod/network/terragrunt.hcl
[terragrunt] 2019/06/10 10:11:48 Downloading Terraform configurations from file://C:/Users/matt.mclane/repos/llamasoft/terraform/modules into C:/Users/matt.mclane/repos/llamasoft/terraform/environments/prod/network/.terragrunt-cache/j11A824preQo1pkd4TD25NjWlKs/5dESSr0bTp-_uymXIM66yNDT_Yo
[terragrunt] 2019/06/10 10:11:48 Hit multiple errors:
error downloading 'file://C:/Users/matt.mclane/repos/llamasoft/terraform/modules': failed to run mklink C:/Users/matt.mclane/repos/llamasoft/terraform/environments/prod/network/.terragrunt-cache/tmp-download-Ry4o94 C:\Users\matt.mclane\repos\llamasoft\terraform\modules: exit status 1 "Invalid switch - \"Users\".\r\n"
[terragrunt] 2019/06/10 10:11:48 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
All the paths seem correct.

**Comment by brikis98** [comment]
What's in `terragrunt.hcl`?

**Comment by mmclane** [comment]
Here is an example:

terraform {
  source = "../../../modules//network"
}

inputs = {
  env_name = "dev"
  region   = "us-west-2"
  vpc_cidr = "192.168.100.0/24"
}

**Comment by mmclane** [comment]
For what its worth, it works when I run terragrunt on Linux.

**Comment by brikis98** [comment]
Could you set the `TERRAGRUNT_DEBUG` env var to `true` so we might get a stack trace?

**Comment by mmclane** [comment]
I get the same result:

`
~\..\..\terraform\..\..\network git: master ≣ ❯ $env:TERRAGRUNT_DEBUG=true
~\..\..\terraform\..\..\network git: master ≣ ❯ tg plan
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/11 08:30:44 Running command: terraform --version
[terragrunt] 2019/06/11 08:30:44 Reading Terragrunt config file at C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network/terragrunt.hcl
[terragrunt] 2019/06/11 08:30:44 Downloading Terraform configurations from file://C:/Users/matt.mclane/repos/llamasoft/terraform/modules into C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network/.terragrunt-cache/EvQCp2RmwG2McT-j-KP4avBfktc/5dESSr0bTp-_uymXIM66yNDT_Yo
[terragrunt] 2019/06/11 08:30:44 Hit multiple errors:
error downloading 'file://C:/Users/matt.mclane/repos/llamasoft/terraform/modules': failed to run mklink C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network/.terragrunt-cache/tmp-download-YtsWeH C:\Users\matt.mclane\repos\llamasoft\terraform\modules: exit status 1 "Invalid switch - \"Users\".\r\n"
[terragrunt] 2019/06/11 08:30:44 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
`

**Comment by brikis98** [comment]
Hm, I think we're on an old version of `go-getter`... Newer versions have fixed symlink issue bugs on Windows: https://github.com/hashicorp/go-getter/pull/159

I'll submit a PR to update us... I may also try to switch to copying instead of symlinks in general as that may fix #736.

**Comment by mmclane** [comment]
Let me know if I can help test.

**Comment by brikis98** [comment]
I think this may be a bug in go-getter that hasn't been fixed, actually:

https://github.com/hashicorp/go-getter/pull/51
https://github.com/hashicorp/go-getter/issues/139

**Comment by brikis98** [comment]
@mmclane Any chance you have a go environment working on your Windows box? If so, could you checkout the `go-getter-update` branch to see if https://github.com/gruntwork-io/terragrunt/pull/739 fixes your issue?

Instead of running `terragrunt apply`, you can run `go run main.go apply` with the source code.

**Comment by mmclane** [comment]
Unfortunately I don't have that environment setup.  I tried to pull it down and run the following:
go run main.go plan --terragrunt-source C:\Users\matt.mclane\repos ... 

But I get all sorts of errors about missing packages

**Comment by ekini** [comment]
You can get Go>=1.12 and run
```
go mod init
go build
```
That should just work.

**Comment by brikis98** [comment]
Oh, neat, didn't know Terragrunt already worked with `go mod`. [Officially](https://github.com/gruntwork-io/terragrunt#developing-terragrunt), we are using `dep` until `go mod` is the de-facto tool in the next Go version, so you could also install `dep` and run `dep ensure` to download the dependencies. But if `go mod` works, that's probably the easiest route!

**Comment by brikis98** [comment]
Give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.1 a shot. New binaries should show up in a few minutes.

**Comment by mmclane** [comment]
Yep, that works.
