### ISSUE TITLE
Migration unexpected "terraform" block

### ISSUE THREAD

**Issue by stefansedich** [gruntwork-io/terragrunt#734]
Just doing a migration and have run straight into this issue, not sure what I am missing, I have the following structure:

dev/foo/terragrunt.hcl
```
include {
  path = "${find_in_parent_folders()}"
}

terraform {
  source = "./../../../../modules//foo"
}
```

dev/terragrunt.hcl
```
terraform {
  extra_arguments "global_vars" {
    commands = get_terraform_commands_that_need_vars()

    required_var_files = [
      "${get_parent_terragrunt_dir()}/terragrunt.hcl",
    ]
  }
}

remote_state {
  ...
}

inputs = {
  aws_region = "us-west-2"
  env        = "dev"
}
```

Which results in:

```
Error: Unexpected "terraform" block

  on /mnt/data/Development/test/dev/terragrunt.hcl line 1:
   1: terraform {

Blocks are not allowed here.
```

**Comment by brikis98** [comment]
Hm, weird, thx for reporting, I'll try to repro.

**Comment by stefansedich** [comment]
I missed out some detais from my full solution so hopefull it is not something else simple, thanks @brikis98 I can provide a more detailed example if the repro doesn't show the issue.

**Comment by brikis98** [comment]
Oh crap, I think what may be happening is Terraform is automatically loading `terragrunt.hcl` as if it's a Terraform file!

**Comment by stefansedich** [comment]
Ah right yes looking at the output, looks to be applying the top level terragrunt.hcl.

```
[terragrunt] 2019/06/10 10:41:39 Running command: terraform apply -var-file=/mnt/data/Development/test/dev/terragrunt.hcl
```

**Comment by brikis98** [comment]
Ohhhh, I see the issue:

```
    required_var_files = [
      "${get_parent_terragrunt_dir()}/terragrunt.hcl",
    ]
```

You can't pass `terragrunt.hcl` as a var file. Only `.tfvars` files can be far files.

**Comment by stefansedich** [comment]
Ah right, that makes sense now :).

How can I handle the case where I want inherited inputs in the way I did they previously? or will I need to move to a seperate tfvars file?

**Comment by brikis98** [comment]
If those inputs are defined in an `inputs = { ... }` block in the parent file, they will be inherited automatically.

**Comment by stefansedich** [comment]
Ah great, thanks @brikis98 I owe you a :beer:

**Comment by rverma-nikiai** [comment]
I am getting an exception like The argument "config" is required, but no definition was found., and 1 other diagnostic(s). In sub dir I have this
```
include {
  path = find_in_parent_folders()
}
```
While in root dir I have
```
remote_state {
  backend = "s3"
  config {
    bucket         = get_env("TF_BUCKET", "")
    key            = "${path_relative_to_include()}/terraform.tfstate}"
    region         = get_env("TF_BUCKET_REGION", "")
    encrypt        = true
    dynamodb_table = get_env("TF_DYNAMODB_TABLE", "")
    profile        = get_env("ASSUME_ROLE", "")
  }
}

terraform {
  extra_arguments "crud" {
    commands = [
      "apply",
      "destroy",
      "plan",
    ]

    arguments = [
      "-lock-timeout=1m",
      "-input=false",
    ]

    env_vars = {
      TF_VAR_aws_assume_role_arn = get_env("TF_VAR_aws_assume_role_arn", "")
      AWS_DEFAULT_REGION         = get_env("TF_VAR_region", "ap-south-1")
      TF_VAR_namespace           = get_env("TF_VAR_namespace", "niki")
    }
  }
}
```

**Comment by brikis98** [comment]
https://github.com/gruntwork-io/terragrunt/blob/master/_docs/migration_guides/upgrading_to_terragrunt_0.19.x.md#check-attributes-vs-blocks-usage

**Comment by brikis98** [comment]
@niki-bot Could you file a separate issue with the full details? i.e, Your Terragrunt config, what the state was before, what changes you're making, etc?
