### ISSUE TITLE
Terragrunt stopped copying symlinks from modules

### ISSUE THREAD

**Issue by ekini** [gruntwork-io/terragrunt#736]
In the comment https://github.com/gruntwork-io/terragrunt/blob/master/util/file.go#L153 it is said that `file.Glob` was chosen to support symlinks, but then https://github.com/gruntwork-io/terragrunt/commit/264812da348c2d977ec4e7ad93a89b53a25c8cec deliberately started skipping symlinks?

Is there a reasoning behind it?
We use it extensively to keep it DRY:
```
common
     |----- infra.tf (with the terraform backend block)
     |----- providers.tf (with common providers)
     |----- variables.tf (with common variables for all modules like aws_profile and aws_region)

module1
      |------ infra.tf -> ../common/infra.tf
      |------ vars_common.tf -> ../common/variables.tf
```

I'm using `terragrunt version v0.19.0`
After reverting the commit above everything works as expected.

**Comment by brikis98** [comment]
Symlinks cause infinite loops... We use `go-getter` now to download code into a temp folder before copying it into the desired download folder location. `go-getter` uses symlinks to "download" code from local file paths. Trying to copy the contents of a folder with symlinks gets really messy, as you could have a symlink nested in a folder structure that takes you back to the top of the folder structure, so you get in an infinite copy loop. 

Why do you use symlinks instead of, for example, Terraform modules?

**Comment by ekini** [comment]
Maybe I wasn't specific enough about what we have in the common folder.
Here is, for example, `variables.tf` in `common` folder.
```
variable "aws_region" {
  default = "ap-southeast-2"
}

variable "aws_profile" {
}

variable "project" {}

variable "environment" {}

locals {
  name = "${var.project}-${var.environment}"
}
```
So any module expects these variables to be present and set.

Another way to handle it without symlinks would be allowing several modules in `terragrunt.hcl` like so:
```
terraform {
  sources = ["git::module_1", "git::module_2"]
}
```
I'm not sure how to use plain terraform modules here.

**Comment by brikis98** [comment]
Oh, I see. So you're dynamically assembling Terraform code. 

You could use [hooks](https://github.com/gruntwork-io/terragrunt#before-and-after-hooks) to copy the files as a temporary workaround. Bringing back support for symlinks is also probably possible, but will be additional work to avoid infinite loops. Not sure on the best approach here, so feedback (and PRs!) welcome.

**Comment by ekini** [comment]
Hmm, I've had a look at the hooks, but there should be a function that returns the module download dir to make it work. Or I couldn't just find a way to know it.

**Comment by ekini** [comment]
I haven't experienced the issue with symlinks, but I think `go-getter` can copy files instead of creating symlinks like so: https://github.com/springload/terragrunt/commit/f1c6ed144c14da0b62787cb9ef3468fada036b1f

Though, enabling multiple sources would create many new possibilities, because terraform 0.12 still doesn't support `count` for modules. For example, we have a module for EC2 autoscaling group + ECS cluster, and want to have (optionally) ASG lifecycle hooks that drain container instances before shutting them down. The hooks functionality is implemented with multiple resources (a Lambda, etc...), and setting `count` for every resource is annoying.

And if `sources` can be merged with the included config, then I wouldn't even need to create the symlinks above but instead add "common" module in the root `terragrunt.hcl`.

How does it sound?

**Comment by lorengordon** [comment]
We use hooks for this extensively, works pretty well:

```
    after_hook "provider" {
      commands = ["init-from-module"]
      execute  = ["cp", "${get_tfvars_dir()}/../../provider.tf", "."]
    }
```

**Comment by brikis98** [comment]
See https://github.com/gruntwork-io/terragrunt#get_terragrunt_dir

**Comment by brikis98** [comment]
> I haven't experienced the issue with symlinks, but I think go-getter can copy files instead of creating symlinks like so: springload@f1c6ed1

Interesting find. Would need to update our `go-getter` dependency version, but that's probably cleaner than the current symlink + copy approach. PR welcome!

> Though, enabling multiple sources would create many new possibilities, because terraform 0.12 still doesn't support count for modules. For example, we have a module for EC2 autoscaling group + ECS cluster, and want to have (optionally) ASG lifecycle hooks that drain container instances before shutting them down. 

Wouldn't that require some sort of `count` or conditional logic support in Terragrunt itself?

**Comment by brikis98** [comment]
#739 is an attempt to switch to pure file copying. If it works, I can try to re-enable copying symlinks and see if that doesn't cause the infinite cycle issue again...

**Comment by brikis98** [comment]
OK, https://github.com/gruntwork-io/terragrunt/pull/739 now copies symlinks as before... If you have a go environment available, you can try to give it a shot by checking out the `go-getter-update` branch and instead of running the usual `terragrunt apply`, running `go run main.go apply`.

**Comment by ekini** [comment]
> > Oh, I see. So you're dynamically assembling Terraform code. .... You could use hooks to copy the files as a temporary workaround.
> 
> > Hmm, I've had a look at the hooks, but there should be a function that returns the module download dir to make it work. Or I couldn't just find a way to know it.
> 
> We use hooks for this extensively, works pretty well:
> 
> ```
>     after_hook "provider" {
>       commands = ["init-from-module"]
>       execute  = ["cp", "${get_tfvars_dir()}/../../provider.tf", "."]
>     }
> ```

Thanks! Although it gives the terragrunt directory where `terraform.tfvars`/`terragrunt.hcl` file is. That would require to have the boilerplate providers/common vars in every project.

What I wanted was a function that returns `/tmp/terragrunt/FJYHwCbdb_KvIpFI8R7iteSwr6A/hmVrtGOo97kXdv_e0cBng5r6DGA` for example (I have `TERRAGRUNT_DOWNLOAD=/tmp/terragrunt` to not worry about cleaning directories)



> OK, #739 now copies symlinks as before... If you have a go environment available, you can try to give it a shot by checking out the `go-getter-update` branch and instead of running the usual `terragrunt apply`, running `go run main.go apply`.

@brikis98 Thanks, it worked! Actually it's even better because previously I had to have
```
/some_source/terraform/terragrunt-modules//backups/
```
but now it's possible to just have
```
/some_source/terraform/terragrunt-modules/backups//
```
which makes more sense

**Comment by ekini** [comment]
> > Though, enabling multiple sources would create many new possibilities, because terraform 0.12 still doesn't support count for modules. For example, we have a module for EC2 autoscaling group + ECS cluster, and want to have (optionally) ASG lifecycle hooks that drain container instances before shutting them down.
> 
> Wouldn't that require some sort of `count` or conditional logic support in Terragrunt itself?

I'll create a separate proposal for that, so this issue can be closed 👍

**Comment by lorengordon** [comment]
> Thanks! Although it gives the terragrunt directory where terraform.tfvars/terragrunt.hcl file is. That would require to have the boilerplate providers/common vars in every project.

I'll typically put the truly common hooks in the terragrunt parent config. Then override them as needed per working directory. If you can do that, maybe this is DRY'er for you, using `get_parent_terragrunt_dir()`:

```
    after_hook "provider" {
      commands = ["init-from-module"]
      execute  = ["cp", "${get_parent_terragrunt_dir()}/provider.tf", "."]
    }
```

**Comment by brikis98** [comment]
Give https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.1 a shot. New binaries should show up in a few minutes.
