### ISSUE TITLE
Plan then init?

### ISSUE THREAD

**Issue by mmclane** [gruntwork-io/terragrunt#742]
I started working with terragrunt just the other day with v0.19.0.  What I have noticed a few things that are minor and I don't understand.

First, its rather verbose.  Is there a way to hide the output of what terragrunt is doing and only have it output what terraform is doing?  This would make cleaner output in my automation (project atlantis server).

More importantly, when I run a plan-all it seems to run terraform plan, then reinitalize the backend. For my current test repo I have the following structure:
/environements
  / dev
    /netowork
 /qa
    /network
...
If I run terragrunt plan-all at /dev it will run terraform plan in /environments/dev/network and then immediately run terraform init.  This seems backward to me and doesn't match what I see if I go into the child directory, /dev/network and run terragrunt plan.

Following is example output:

~\..\..\terraform\..\dev git: master ≣ ❯ tg plan-all
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev] 2019/06/12 08:35:08 Running command: terraform --version
[terragrunt] 2019/06/12 08:35:09 Module C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev does not have an associated terraform configuration and will be skipped.
[terragrunt] 2019/06/12 08:35:09 Stack at C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev:
  => Module C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network (excluded: false, dependencies: [])
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Module C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network must wait for 0 dependencies to finish
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Running module C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network now
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Reading Terragrunt config file at C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network/terragrunt.hcl
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Cleaning up contents of download folder C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/.terragrunt-cache/EvQCp2RmwG2McT-j-KP4avBfktc/5dESSr0bTp-_uymXIM66yNDT_Yo
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Downloading Terraform configurations from file://C:/Users/matt.mclane/repos/llamasoft/terraform/modules into C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/.terragrunt-cache/EvQCp2RmwG2McT-j-KP4avBfktc/5dESSr0bTp-_uymXIM66yNDT_Yo
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Copying files from C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network into C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/.terragrunt-cache/EvQCp2RmwG2McT-j-KP4avBfktc/5dESSr0bTp-_uymXIM66yNDT_Yo/network
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Setting working directory to C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/.terragrunt-cache/EvQCp2RmwG2McT-j-KP4avBfktc/5dESSr0bTp-_uymXIM66yNDT_Yo/network
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:10 Running command: terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_vpc.base: Refreshing state... [id=vpc-005b76e6860d6cc20]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
[terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:15 Module C:/Users/matt.mclane/repos/llamasoft/terraform/environments/dev/network has finished successfully!
[terragrunt] 2019/06/12 08:35:15 Error with plan: [terragrunt] [C:\Users\matt.mclane\repos\llamasoft\terraform\environments\dev\network] 2019/06/12 08:35:09 Running command: terraform init -backend-config=encrypt=true -backend-config=key=dev/network/terraform.tfstate -backend-config=region=us-east-1 -backend-config=bucket=llama-m3demo -backend-config=dynamodb_table=m3-lock-table

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.aws: version = "~> 2.14"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

**Comment by brikis98** [comment]
> First, its rather verbose. Is there a way to hide the output of what terragrunt is doing and only have it output what terraform is doing? This would make cleaner output in my automation (project atlantis server).

If you search, there have been issues filed to support different Terragrunt logging levels. We haven't had time to get to it, but PRs are welcome.

> More importantly, when I run a plan-all it seems to run terraform plan, then reinitalize the backend. For my current test repo I have the following structure:

Hm, I'm not sure what's happening there... Note that the timestamp on the `init` log messages is the same as that of the earlier `apply`, so most likely, the log output is in the wrong order?

**Comment by yorinasub17** [comment]
Closing as stale. If there is still an issue here, please open a new ticket. Thanks!

PS: [Terragrunt log levels have been implemented now](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-log-level).
