### ISSUE TITLE
Generate the backend tf file when running terragrunt to enable DRYer modules.

### ISSUE THREAD

**Issue by DanielChalk** [gruntwork-io/terragrunt#746]
I have quite a few sharable modules within my organisation and I would like to remove the need to include the backend configuration in those modules. Considering that the top level .hcl file has my backend configuration, I can't see why terragrunt couldn't generate the backend terraform file before running terraform init.

Could we make it optional by adding a `generate` property to the remote_state configuration block? 

For example:

```terraform-hcl
remote_state {
  backend  = "s3"
  generate = true
  config = { ... }
}
```

**Comment by brikis98** [comment]
If you can find a way to do this without massively complicating the implementation, I'm fine with it. But beware that code generation often leads to lots of small gotchas:

1. What filename should we generate it into? What if the file exists already?
1. If you remove `generate = true`, do we need to delete the generated file?
1. The `backend` configuration is supposed to go into a `terraform { ... }` block. What if the user already has a `terraform { ... }` block in their Terraform code (`.tf` files)? What if they have it in a module pulled in by their Terraform code?
1. Where do we write the file for users who are NOT using `source = ...` in their `terragrunt.hcl`? E.g., If they have `terragrunt.hcl` sitting next to `main.tf`, do we want to create a `generated.tf` into the same folder? Should the user check that file in? 

Those are a few off the top of my head. There are likely others.

**Comment by lorengordon** [comment]
I think this is basically supported now: https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate

**Comment by yorinasub17** [comment]
Closing as this has been implemented.
