### ISSUE TITLE
Terragrunt 0.19.6 breaks existing GCP config

### ISSUE THREAD

**Issue by mattford63** [gruntwork-io/terragrunt#767]
A working config on 0.19.5 now fails on 0.19.6 (likely due to GCP changes)

I have this as a parent

```
remote_state {
  backend = "gcs"
  config = {
    bucket = "project-factory-592341-tfstate"
    prefix = "${path_relative_to_include()}"
  }
}
```

And this as a child

```
include {
  path = find_in_parent_folders()
}
```

The error I see is

```
[terragrunt] 2019/06/28 14:11:13 Initializing remote state for the gcs backend
[terragrunt] 2019/06/28 14:11:13 Missing required GCS remote state configuration project
[terragrunt] 2019/06/28 14:11:13 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

Switching back to using 0.19.5 results in a successful execution?  Did I miss a config change?

**Comment by mattford63** [comment]
Ah, I was a bit hasty in reporting this, I see now that the project config attribute is required.

**Comment by mattford63** [comment]
Actually, is it sensible that project and location must now be specified even for externally created buckets?

**Comment by brikis98** [comment]
@robmorgan ^

**Comment by robmorgan** [comment]
> Actually, is it sensible that project and location must now be specified even for externally created buckets?

No, it's not really fair, to be honest. I'll start preparing a workaround.

**Comment by robmorgan** [comment]
My proposal: `project` and `location` will only be mandatory when creating a bucket.

**Comment by robmorgan** [comment]
Testing a new release, will likely ship it tomorrow.

**Comment by robmorgan** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.8
