### ISSUE TITLE
terraform fmt doesn't work on *.hcl files

### ISSUE THREAD

**Issue by heydonovan** [gruntwork-io/terragrunt#768]
terragrunt.hcl

```
inputs = {
  aws_region                   = "us-east-1"
  aws_profile                                 = "test-staging"
}
```

If I run `terragrunt fmt`, nothing changes. However, if I rename the file to `terragrunt.tf`, and then run `terragrunt fmt`, it works. How do other folks handle this?

**Comment by barryib** [comment]
Terraform can read from stdin

```shell
cat terragrunt.hcl | terraform fmt -
```

**Comment by mcalhoun** [comment]
I opened a PR to add this feature: https://github.com/hashicorp/terraform/pull/22092

**Comment by yorinasub17** [comment]
It looks like the PR in terraform won't be accepted, so opened https://github.com/gruntwork-io/terragrunt/pull/801 to pull in `hclfmt` as a terragrunt sub command.

**Comment by yorinasub17** [comment]
FYI https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.12 rolls out a new command `terragrunt hclfmt` that can be used to format the `terragrunt.hcl` files. Obviously not as great as having `terraform fmt` handle those, but probably a good workaround for now.

**Comment by ashemedai** [comment]
@brikis98 @yorinasub17 I have used that `hclfmt` feature and it does what it should. I think that tackles the use case that OP (implicitly) wanted. Issue can be closed in my opinion.

**Comment by yorinasub17** [comment]
With `terragrunt hclfmt` and with terraform community unlikely to merge our PR, going to close this.
