### ISSUE TITLE
Terragrunt & GCS credentials

### ISSUE THREAD

**Issue by ashald** [gruntwork-io/terragrunt#780]
We just tried to setup Terragrunt with GCS remote state using a configuration like:
```
remote_state {
 backend = "gcs"
 config = {
   bucket = "tf"
   credentials = "${path_relative_from_include()}/gcp-infra-services.json"
   prefix = "${path_relative_to_include()}/terraform.tfstate"
 }
}
```
and got an error from *Terragrunt* saying something about "Application Default Credentials" and a link to GCP docs (sorry for the vagueness, don't have that error in front of me right now). By reading the doc by the link we learned about env var `GOOGLE_APPLICATION_CREDENTIALS` and when we set it pointing to GCP credentials file it worked (the credentials file had all the permissions necessary).

To the best of our understanding, Terragrunt tries to verify if GCS bucket exists and create one if it doesn't. Also, it seems that the idea is that credentials Terragrunt would use will be different from credentials passed to the Terrraform backend for the purpose of "separation of concerns".

All of this is really great with the only exception that it doesn't work in our environment. :) 

The few questions that we have in mind that we weren't able to figure out from the docs are:
1) what are the alternatives to provide Terragrunt credentials to check/create GCS bucket?
2) if `GOOGLE_APPLICATION_CREDENTIALS` env var is the only one - could Terragrunt be smart and attempt to do that only if credentials set and just skip this otherwise?
3) lastly, is it possible to tell Terragrunt explicitly to not attempt to do that and just configure the Terraform backend as is?

In our case, we ended up with the following workaround instead but it would really be nice if we could use the `remote_state` instead:
```
terraform {
  extra_arguments "backend" {
    commands  = ["init"]

    arguments = [
      "-backend-config=credentials=${path_relative_from_include()}/gcp-infra-services.json",
      "-backend-config=bucket=tf",
      "-backend-config=prefix=${path_relative_to_include()}/terraform.tfstate",
    ]
  }
}
```

Thanks!

**Comment by autero1** [comment]
@robmorgan You worked with the GCS backend recently. Think you could check this out?

**Comment by autero1** [comment]
> and got an error from Terragrunt saying something about "Application Default Credentials" and a link to GCP docs (sorry for the vagueness, don't have that error in front of me right now). 
@ashald would be helpful if you could provide the detailed error message

**Comment by ashald** [comment]
@autero1 I’ll post it alter today. Frankly I’m not sure if it’s important at all as there seems to be a different problem: Terragrunt would need some kind of credentials even to check if GCS bucket exists (let alone create it) and as long as there is no way to disable this behavior some kind of an issue is inevitable if those credentials are not provided.

P.S.: Pardon me if my doc-reading skills are at fault but I wasn’t able to find anything in Terragrunt docs about authentication for gcs.

**Comment by yorinasub17** [comment]
We just introduced the ability to disable the auto initialization of the backend in [v0.19.7](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.7). Would this feature help with your use case? Here are the docs for it:

> Note: You can disable automatic remote state initialization by setting remote_state.disable_init, this will skip the automatic creation of remote state resources and will execute terraform init passing the backend=false option. This can be handy when running commands such as validate-all as part of a CI process where you do not want to initialize remote state.

**Comment by ashald** [comment]
The detailed error message I mentioned previously:
```
$ TERRAGRUNT_DEBUG=1 terragrunt plan-all
[terragrunt] [/home/user1/tg-gcp] 2019/07/10 20:25:32 Running command: terraform --version
[terragrunt] 2019/07/10 20:25:32 Setting download directory for module /home/user1/tg-gcp to /home/user1/tg-gcp/.terragrunt-cache
[terragrunt] 2019/07/10 20:25:32 Module /home/user1/tg-gcp does not have an associated terraform configuration and will be skipped.
[terragrunt] 2019/07/10 20:25:32 Setting download directory for module /home/user1/tg-gcp/prod/step001 to /home/user1/tg-gcp/prod/step001/.terragrunt-cache
[terragrunt] 2019/07/10 20:25:32 Stack at /home/user1/tg-gcp:
  => Module /home/user1/tg-gcp/prod/step001 (excluded: false, dependencies: [])
[terragrunt] [/home/user1/tg-gcp/prod/step001] 2019/07/10 20:25:32 Module /home/user1/tg-gcp/prod/step001 must wait for 0 dependencies to finish
[terragrunt] [/home/user1/tg-gcp/prod/step001] 2019/07/10 20:25:32 Running module /home/user1/tg-gcp/prod/step001 now
[terragrunt] [/home/user1/tg-gcp/prod/step001] 2019/07/10 20:25:32 Reading Terragrunt config file at /home/user1/tg-gcp/prod/step001/terragrunt.hcl
[terragrunt] [/home/user1/tg-gcp/prod/step001] 2019/07/10 20:25:32 Module /home/user1/tg-gcp/prod/step001 has finished with an error: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
[terragrunt] 2019/07/10 20:25:33 configstack.MultiError Encountered the following errors:
dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:179 (0xcbc094)
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:163 (0xcbbe56)
/go/src/github.com/gruntwork-io/terragrunt/configstack/running_module.go:62 (0xcbb21d)
/go/src/github.com/gruntwork-io/terragrunt/configstack/stack.go:42 (0xcbd687)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:670 (0xcc5e4a)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:622 (0xcc5911)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:227 (0xcc2cc5)
/go/src/github.com/gruntwork-io/terragrunt/cli/cli_app.go:210 (0xcc29e5)
/go/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:490 (0xc602e8)
/go/src/github.com/gruntwork-io/terragrunt/vendor/github.com/urfave/cli/app.go:264 (0xc5e55d)
/go/src/github.com/gruntwork-io/terragrunt/main.go:20 (0xccac84)
/usr/local/go/src/runtime/proc.go:201 (0x42c1b7)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x457fe1)

[terragrunt] 2019/07/10 20:25:33 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

**Comment by ashald** [comment]
@yorinasub17 with regards to:
> We just introduced the ability to disable the auto initialization of the backend in v0.19.7. Would this feature help with your use case?

This won't work for us. We don need to configure the remote backend. We just don't need Terragrunt to attempt to verify that such a bucket exists (and create it in case it doesn't). Or at least have a way to specify credentials for that via an explicit config field rather than just an environment variable. The best would be both: an option to disable it an option to pass credentials for that in case it's enabled.

**Comment by ashald** [comment]
Looking at https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_gcs.go#L387 I assume it was derived from https://godoc.org/cloud.google.com/go/storage#hdr-Creating_a_Client that explicitly tells:
> The client will use your default application credentials.

I'm not sure I understand reasoning for assuming that default application credentials would work for access/creating GCS buckets that store such important data as state files.

It appears that [it's possible to pass credentials explicitly via options](https://godoc.org/cloud.google.com/go/storage#NewClient) and there are quite a few option about how credentials can be passed: https://godoc.org/google.golang.org/api/option#ClientOption

I don't feel I'm in position to suggest a certain approach to take but it looks like `option.WithCredentialsFile` can be used with the same value as the one supplied in `credentials` field for the `gcs` backend on its own. Or maybe you'd prefer to have a separate config option for this.

**Comment by brikis98** [comment]
@robmorgan With S3, we read specific variables from the config about how to auth to the bucket: https://github.com/gruntwork-io/terragrunt/blob/master/remote/remote_state_s3.go#L112.

Could we do similar for GCS?

**Comment by ashald** [comment]
IMO that would be great! Any chances this can be implemented?

**Comment by robmorgan** [comment]
Hey guys on vacation at the moment. Will take a look in about 1-2 weeks.

**Comment by ashald** [comment]
Thanks for an update! No rush - just didn't want this to fall off the radar. I would've contributed this myself but I'm afraid there might be some design decisions involved that I don't have enough context for and it would be an order of magnitude more work this way.

**Comment by marko7460** [comment]
I have a similar problem with v0.19.7. My GCS configuration looks like this:
```hcl
remote_state {
  backend = "gcs"
  config = {
    prefix      = path_relative_to_include()
    credentials = "${get_terragrunt_dir()}/${find_in_parent_folders("credentials.json")}"
  }
}
terraform {
  extra_arguments "bucket" {
    commands = ["init"]
    arguments = [
      "-backend-config=${get_terragrunt_dir()}/${find_in_parent_folders("init.tfvars")}",
    ]
  }
  extra_arguments "creds" {
    commands = get_terraform_commands_that_need_vars()
    arguments = [
      "-var",
      "credentials=${get_terragrunt_dir()}/${find_in_parent_folders("credentials.json")}",
    ]
  }
}

inputs = {
  continent = "us"
  environment = "dev"
}
```

* `credentials.json` is the service account key necessary to run terraform.
* `init.tfvars` holds value for already created GCS bucket
  ```hcl
  bucket = "my-state-bucket"
  ```

When i run `terragrunt init` i keep getting
```[terragrunt] 2019/08/02 12:20:01 Initializing remote state for the gcs backend
[terragrunt] 2019/08/02 12:20:01 Missing required GCS remote state configuration project
[terragrunt] 2019/08/02 12:20:01 Unable to determine underlying exit code, so Terragrunt will exit with error code 1```

This code used to work perfectly in terragrunt 0.18.X with terraform 0.11.14.

**Comment by robmorgan** [comment]
Currently working on a new test case, hope to have a fix out later this week 👍

**Comment by ashald** [comment]
Sounds exciting! Thanks!

**Comment by robmorgan** [comment]
FYI - I have released https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.19 with @marko7460's fix.

**Comment by ashald** [comment]
@robmorgan thanks a lot!

**Comment by gituser963** [comment]
When I am trying to use terragrunt for backend gcs, I am facing the error like below:

Error: Error parsing credentials 'terragrunt-test/auth.json': invalid character 'e' in literal true (expecting 'r')

terragrunt-test is my folder name and auth.json is my service account credentials file.

I am unable to understand why it is showing like.

**Comment by brikis98** [comment]
Sounds like you have invalid JSON in the file? At any rate, please open a new issue to track this.
