### ISSUE TITLE
GCS bucket not being created

### ISSUE THREAD

**Issue by infa-bsurber** [gruntwork-io/terragrunt#784]
terragrunt version v0.18.7 and terraform version v0.11.14 (can't upgrade to 0.12 until the Vault provider supports it)

config files:
at env/terraform.tfvars
```
terragrunt = {
  remote_state {
    backend = "gcs"
    config {
      project = "<redacted>"
      bucket = "<redacted>"
      prefix = "${path_relative_to_include()}"
    }
  }
}
```
at env/region/terraform.tfvars
```
terragrunt {
  terraform {
    source = "${get_tfvars_dir()}/../../../../templates"
  }
  # include gcs bucket state storage configuration
  include {
    path = "../terraform.tfvars"
  }
}
```
I'm getting the following unexpected error: 
```
Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.
Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist   
```

This error is unexpected as terragrunt documentation indicates that the gcs bucket should get automatically created on the first run.

Any ideas? Bug? Misconfiguration?

**Comment by yorinasub17** [comment]
Hi, the GCS bucket auto creation was introduced in [v0.19.6](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.6). If you look at [the README for the version you are using](https://github.com/gruntwork-io/terragrunt/tree/v0.18.7), the GCS bucket creation isn't mentioned there.

**Comment by infa-bsurber** [comment]
Ah, makes sense, thanks for the quick response. I'll add a quick .tf file & use the terraform cli to handle bucket creation beforehand then.
