### ISSUE TITLE
Terragrunt release downloads returning 500 erro

### ISSUE THREAD

**Issue by yem583** [gruntwork-io/terragrunt#792]
Looks like the downloads are all returning 500 errors
![terragrunt500](https://user-images.githubusercontent.com/1097138/61646403-91e06a00-ac77-11e9-81e3-813c4f4783be.png)

https://github.com/gruntwork-io/terragrunt/releases/download/v0.19.8/terragrunt_windows_amd64.exe

**Comment by lorengordon** [comment]
GitHub status is reporting issues... https://www.githubstatus.com/

**Comment by yorinasub17** [comment]
Thanks for the report! Github is back up now and confirmed the releases page is working again, so going to close this.
