### ISSUE TITLE
S3 modules are not downloaded when sources added/changed

### ISSUE THREAD

**Issue by Glen-Moonpig** [gruntwork-io/terragrunt#793]
This is probably similar to #20 and #764, but those discussions are very focused on pulling from git so maybe a different issue.

If I run a terragrunt plan the modules referenced from S3 sources are downloaded fine. If I then use a new module source or change a module source then I get the following error because the modules are not updated:

```
Error: Module not installed

  on resources-route53.tf line 1:
   1: module "appx_domain" {

This module is not yet installed. Run "terraform init" to install all modules
required by this configuration.
```

I can work around this by manually deleting the cache so that the modules are pulled again from scratch, but it would be great if I didn't have to do this.

**Comment by brikis98** [comment]
Have you tried running `terragrunt init`?

**Comment by Glen-Moonpig** [comment]
I haven't, but I don't run terragrunt init under usual operation as terragrunt performs that action for me, so it seems like I shouldn't need to do it in this scenario too.

**Comment by brikis98** [comment]
Terragrunt does [auto-init](https://github.com/gruntwork-io/terragrunt#auto-init), but only in specific circumstances. As per https://github.com/gruntwork-io/terragrunt/issues/388, we have not yet implemented it to detect all possible scenarios and run `init` automatically for them. PR welcome. In the meantime, if you add a module or provider, or change the version of a module or provide, you'll need to run `terragrunt init` yourself.
