### ISSUE TITLE
Terragrunt creates a public s3 bucket

### ISSUE THREAD

**Issue by src386** [gruntwork-io/terragrunt#795]
- terragrunt version v0.19.6
- terraform v0.12.3

Steps to reproduce:

1. Define a s3 backend in terragrunt.hcl / main.tf
2. terragrunt init
3. Terragrunt offers to create the s3 bucket. Accept.
4. The bucket has public access

This seems like a dangerous default behavior. The bucket should be private.

```
[terragrunt] 2019/07/23 15:59:09 [terragrunt]  Remote state S3 bucket mys3bucket does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 
y
[terragrunt] 2019/07/23 15:59:12 Create S3 bucket mys3bucket
[terragrunt] 2019/07/23 15:59:12 Creating S3 bucket mys3bucket
[terragrunt] 2019/07/23 15:59:12 Waiting for bucket mys3bucket to be created
[terragrunt] 2019/07/23 15:59:13 S3 bucket mys3bucket created.
[terragrunt] 2019/07/23 15:59:13 No tags specified for bucket mys3bucket.
[terragrunt] 2019/07/23 15:59:13 Enabling versioning on S3 bucket mys3bucket
[terragrunt] 2019/07/23 15:59:13 Enabling bucket-wide SSE on AWS S3 bucket mys3bucket
[terragrunt] 2019/07/23 15:59:13 Granting WRITE and READ_ACP permissions to S3 Log Delivery (http://acs.amazonaws.com/groups/s3/LogDelivery) for bucket mys3bucket. This is required for access logging.
[terragrunt] 2019/07/23 15:59:13 Waiting for ACL bucket mys3bucket to have the updated ACL for access logging.
[terragrunt] 2019/07/23 15:59:14 Bucket mys3bucket now has the proper ACL permissions for access logging!
[terragrunt] 2019/07/23 15:59:14 Enabling bucket-wide Access Logging on AWS S3 bucket "mys3bucket" - using as TargetBucket "mys3bucket"
```

**Comment by brikis98** [comment]
Why do you think the bucket has public access?

**Comment by yorinasub17** [comment]
Looking into this, the permissions are set such that it allows public objects to be created, but that does not necessarily mean the objects are public. In fact, if you try to browse the bucket created by terragrunt from another AWS account, you will get an access denied error. Furthermore, the individual state files are stored as objects with individuals ACLs that ensure the objects the private, even if the bucket itself may allow objects to be stored as public.

So this isn't as bad as it sounds.

With that said, terragrunt should create the bucket such that it prohibits public objects (defense in depth). I will look into that later today.

**Comment by yorinasub17** [comment]
I dug through the ACLs of the bucket being created by terragrunt and confirmed that the bucket policy has no public ACLs set. The only thing it doesn't have is the "block all public access" flag turned on.

**Comment by src386** [comment]
Thank you all!
