### ISSUE TITLE
Terragrunt doesn't appear to respect SSH port

### ISSUE THREAD

**Issue by eoliphan** [gruntwork-io/terragrunt#800]
Hi, i'm using Terragrunt with Bitbucket server, which handles git/ssh on port 7999 by default.  When I set my terraform source as something like "git@bitbucket.xx.xx:7999/..." I'm getting 

```
ssh: connect to host bitbucket.xx.xx port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by brikis98** [comment]
This is likely not a Terragrunt issue, but an issue of how you're specifying `source` URLs. You probably want something like:

```
git::ssh://git@<DOMAIN>:<PORT>/<PATH>.git//<PATH>?ref=<VERSION>
```

e.g.:

```
git::ssh://git@bitbucket.your-company.com:7999/my-project/foo.git//my-module?ref=v0.0.1
```

**Comment by eoliphan** [comment]
Hi, thanks the format was incorrect, however after updating it, I'm still having the same problem

"git::ssh://git@bitbucket.xxx.com:7999/in/infrastructure-modules.git//auth-module?ref=1.0.0"

I think this is the issue
```
[terragrunt] 2019/07/25 12:29:55 Downloading Terraform configurations from git::ssh://git@bitbucket.xxx.com/7999/in/infrastructure-modules.git?ref=1.0.0 
```
it's treating the port as a path, any other ideas on what might be issue?  I've verified that I can clone  `ssh://git@bitbucket.xxx.com/7999/in/infrastructure-modules.git?ref=1.0.0 ` directly from the command line.  I tried that alone, plus the `git::` prefixing in the terragrunt.hcl but still get the same error

**Comment by brikis98** [comment]
Terragrunt uses [go-getter](https://github.com/hashicorp/go-getter) for all downloads. Perhaps browse their docs to see if we still have something wrong with the URL format?

**Comment by miguelaferreira** [comment]
I was having the same issue and found the solution in the go-getter docs.

the source that worked was in the form of `git::ssh://git@bitbucket.xxx.com:7999/foo/bar`

**Comment by todouu** [comment]
add ssh: is work for me, thanks miguelaferreira

**Comment by yorinasub17** [comment]
Closing as the original question has been answered. If there are any follow up issues, please file a new issue. Thanks!
