### ISSUE TITLE
plan-all issues with provider

### ISSUE THREAD

**Issue by mmclane** [gruntwork-io/terragrunt#803]
I have a file structure similar to the following:
- /Azure
-- hub
---- vnet
---- m3-test
---- atlantis

I use the following providers in the vnet module: 
- * provider.azuread: version = "~> 0.5"
- * provider.azurerm: version = "~> 1.32"
- * provider.random: version = "~> 2.1"
- * provider.vault: version = "~> 2.1"

If I run terragrunt plan (or terragrunt apply) in the /Azure/hub/vnet directory everything works as expected.  If however I run terragrunt plan-all (or apply-all) in the /Azure/hub directory I get the following error for the vnet module:

> Error: provider.random: no suitable version installed
> version requirements: "(any version)"
> versions installed: none

terragrunt init-all run at /Azure/hub gives me a terraform error: Terraform initialized in an empty directory!

Versions:
- Terraform v0.12.4
- Terragrunt v0.19.11

**Comment by mmclane** [comment]
So it seems that if I touch main.tf in the /Azure/hub directory, everything runs as expected.

**Comment by mmclane** [comment]
atlantis plan

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue, please provide your `terragrunt.hcl` as it is impossible to debug this issue without some visibility in to the `terragrunt.hcl` config. We can reopen this if there is a follow up. Thanks!
