### ISSUE TITLE
The option to set up terragrunt cache only

### ISSUE THREAD

**Issue by msfuko** [gruntwork-io/terragrunt#805]
Hi,

We have an use case that we wanna download the source modules into terragrunt cache before we really launch anything. (let's say, we don't have access to git during runtime.)

When we do a ` terragrunt init`, terragrunt will run 1) terraform init 2) check out the source if it needs to be downloaded (this is what we want) 3) check the remote state of the modules.

Are there any ways that we can bypass 1) initializing remote state for the s3 backend and 2) checking the remote state? (we don't wanna pass AWS credential during the cache setup)

I tried using `--terragrunt-config` to point to another root terragrunt.hcl file but no luck:
```
$ cat xxx/terragrunt.hcl 
remote_state {
  backend = "local"
  config = {
  }
}
```
It'll throw:

```
Found remote_state settings in xxx/terragrunt.hcl but no backend block in the Terraform code in xxxx. You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

terraform {
  backend "local" {}
}
```

Any hints would be appreciated. Thanks a lot!

**Comment by brikis98** [comment]
Try `terragrunt init -backend=false`

**Comment by msfuko** [comment]
Decided to use the modules locally instead of caching. close the issue. thanks!
