### ISSUE TITLE
Add 0.19upgrade command

### ISSUE THREAD

**Issue by brikis98** [gruntwork-io/terragrunt#806]
Upgrading to Terragrunt 0.19.x (so you can use Terraform 0.12.x) can be a lot of work, including converting many `terraform.tfvars` files to `terragrunt.hcl`. Terraform comes with a `0.12upgrade` command that updates `.tf` files to Terraform 0.12 syntax. It's not perfect, but saves a ton of work. 

We should add an analogous `0.19upgrade` command that updates `terraform.tfvars` to `terragrunt.hcl`. It doesn't need to be perfect, but if it can update all files recursively within a subfolder, and get them 95% of the way there, it would still be worth it.

If anyone is up for a PR to add this, we'd be more than grateful!

**Comment by yorinasub17** [comment]
Should the command be called `terragrunt 0.19upgrade`? Since it is really about upgrading to tg19 syntax as opposed to tf12.

**Comment by brikis98** [comment]
Oh, yea, good point! Will update the description.

**Comment by terozio** [comment]
This would be great when we have a fairly large footprint of tfvars files!

**Comment by brikis98** [comment]
I think the ship has sailed on this one. Closing!
