### ISSUE TITLE
Migration / Conversion from Terraform to Terragrunt & state?

### ISSUE THREAD

**Issue by sebkouba** [gruntwork-io/terragrunt#810]
I have a terraform project which I would like to "convert" into terragrunt code. How do I deal with the terraform state without destroying existing infrastructure?

Simply keeping the existing state bucket doesn't seem to work. When I extract the VPC code as terragrunt module and run "terragrunt plan", it wants to destroy everything that isn't the vpc. Is there a way to split it up manually?

I'd appreciate any tips you may have.

**Comment by ekini** [comment]
You can clear the state (backup the state file somewhere else, for example), and `terragrunt import` every resource you have https://www.terraform.io/docs/import/usage.html

**Comment by sebkouba** [comment]
Thanks ekini. I also had made a mistake in how to set the state in terragrunt (didn't use the "path_relative_to_include"). Looking at the state file I'm hoping to either get the ids to import out of it or maybe try to manually tear it apart. I still have a lot to learn...
