### ISSUE TITLE
pass the credentials stored in terraform.tfvars as argument in script called by before hook

### ISSUE THREAD

**Issue by AnjaliRajan24** [gruntwork-io/terragrunt#811]
Hi

Is there a workaround for the situation where I want to store my credentials in terraform.tfvars and use that as an argument in the ruby script I am executing in before hook terragrunt.hcl.

    terraform{
      before_hook "before_hook_1" {
        commands = ["apply", "delete"]
        execute = ["./sync_check.rb ${var.username} ${var.password}"]
    }

**Comment by brikis98** [comment]
Would [locals](https://github.com/gruntwork-io/terragrunt#locals) work for you?

Also, I wouldn't recommend storing credentials in a `.tfvars` or `.hcl` file or anywhere else in plain text...

**Comment by yorinasub17** [comment]
Closing as the stale and a workaround has been offered. If there are any follow up questions, please open a new issue. Thanks!
