### ISSUE TITLE
Question: Possible to pass vars directly to dependencies?

### ISSUE THREAD

**Issue by alkalinecoffee** [gruntwork-io/terragrunt#812]
Is it possible to call a dependency defined in a terragrunt file with variables defined in that file, instead of having the var file logic defined in the dependency's config?

Right now, it looks like a terragrunt config file:

```
terragrunt = {
  remote_state = {...}
  dependencies = {
    paths = ["${get_tfvars_dir()}../../../../../modules/security_groups"]
  }
  terraform {
    source = "git::https://mycompany.com/myteam/terraform-modules//asg"
    extra_arguments "all_configs" {
      optional_var_files = [
        "${get_tfvars_dir()}/../../region.tfvars",
      ]
    }
  }
}
```

Will simply call `terraform` on the `modules/security_groups` module with no extra options.

We're wondering if there's a way to pass the `optional_var_files` values to the `dependencies` defined here.  Otherwise, the dependencies referenced here will need to assume the folder structure of the var files in the main terragrunt config, which can prove brittle.

Thinking something like:

```
dependencies = {
  paths = [...]
  extra_arguments "configs" {
    optional_var_files = [
      "${get_tfvars_dir()}/../../region.tfvars"
    ]
  }
}
```

Or perhaps as a workaround for our particular problem, from within our dependency configuration,  is there a way to get the path of the file that called the dependency?  Neither `get_tfvars_dir()` or `path_relative_to_include()` help determine the caller's path when used in our dependency config.

**Comment by brikis98** [comment]
Not sure I understand the question. The `dependencies` block is solely used when running `xxx-all` commands (e.g., `apply-all`) to determine ordering. There's no "calling" a dependency from another dependency...

Could you explain your use case a bit more?

**Comment by alkalinecoffee** [comment]
Sure @brikis98.  Consider the following folder structure (we're still on TG v0.18) where we want to call a custom module that resides in its own `/modules` directory:

```
modules/
  security_groups/
    main.tf
    terraform.tfvars
prod/
  us-east-1/
    terraform.tfvars
  env.tfvars
global.tfvars
```

Below is our main terragrunt config for a region.  You can see in this file, we pass in the chain of var files based on the folder structure to stand up this region's infrastructure:

```
# /prod/us-east-1/terraform.tfvars
terragrunt = {

  dependencies {
    paths = ["${get_tfvars_dir()}/../../modules/security_groups"]
  }

  terraform {
    source = "..."

    extra_arguments "region" {
      optional_var_files = [
        "${get_tfvars_dir()}/../../global.tfvars",
        "${get_tfvars_dir()}/../env.tfvars",
        "${get_tfvars_dir()}/terraform.tfvars"
      ]
    }
  }

}
```

But we also have a custom, shared module in the root directory that we wish to call as a dependency, that lives in `/modules/security_groups`:

```
# /modules/security_groups/terraform.tfvars

terragrunt = {
  terraform {
    extra_arguments "security_groups" {

      # Here, we want to access the same var files that are set in the module
      # that depends this one, but this module has no way to reference them.
      
      optional_var_files = [
        "${get_tfvars_dir()}/../../global.tfvars", # these don't work
        "${get_tfvars_dir()}/../env.tfvars",
        "${get_tfvars_dir()}/terraform.tfvars"
      ]
    }
  }
}
```

The above module needs a bunch of region-specific configuration to build security groups: it can't do it on its own without duplicating configs.

Ideally, this security group module would have access the same var files as the main module in `/prod/us-east-1/terraform.tfvars`.  But since the security group module resides at the root directory, it has no idea about the folder structure of the region module nor its var files.

We're hoping that when terragrunt runs a dependency, there would be a way to pass var files (or maybe just an `extra_arguments` block) to that dependency, ie:

```
dependencies {
  paths = ["${get_tfvars_dir()}/../../modules/security_groups"]
  extra_arguments { ... }
}
```

Or perhaps, a function like `get_caller_tfvars_dir` that we can call from within a dependency to find the path from where it was called, ie

```
# /modules/security_groups/terraform.tfvars
optional_var_files = [
   "${get_caller_tfvars_dir()}/../../global.tfvars",
   "${get_caller_tfvars_dir()}/../env.tfvars",
   "${get_caller_tfvars_dir()}/terraform.tfvars"
]
```

Or am I just doing this all wrong??

**Comment by brikis98** [comment]
I don't follow why you have a `modules/xxx/terraform.tfvars`. Modules should be defined in Terraform code (`.tf` files), not Terragrunt `.tfvars` files. You deploy those Terraform modules by creating Terragrunt `.tfvars` files in the folder structure that represents your actual live environment: e.g., in folders under `prod/us-east-1/xxx`. Each of those `.tfvars` files specifies the variables/settings it needs and/or uses `include` to pull in common variables/settings from the root `.tfvars` file for that environment.

See https://github.com/gruntwork-io/terragrunt#keep-your-terraform-code-dry.

**Comment by alkalinecoffee** [comment]
Well, right, that's why I started this issue, and having TG config in `/modules` was just an example of one thing I tried to get dependencies working.  I realize the way I explained above is wrong, and I'm looking for a solution, hence the original question.

We may be talking past each other.  I'll try to explain another way.

Given this folder structure:

```
modules/
  security_groups/
    main.tf
prod/
  us-east-1/
    terraform.tfvars --> this points to an external module on github, etc
  env.tfvars
global.tfvars
```

This is a common folder structure we use across our environment.  But in this case, this particular application requires some extra terraform code to be applied when `/prod/us-east-1` is applied.

If the user creates files under `modules`, how can those modules be included into the terragrunt pipeline?  How can we ensure these modules are called when we run `terragrunt apply` from `/prod/us-east-1/`?

**Comment by brikis98** [comment]
`terragrunt apply` is equivalent to `terraform apply`. It is meant to be used with a single Terraform module. So one option is to solve it exactly the way you would if Terragrunt didn't exist: take whatever module `prod/us-east-1/terraform.tfvars` is deploying (the thing in the `source` parameter) and add to it the "extra terraform code under `/modules`" that you wished deployed each time `apply` is called. If the thing in the `source` parameter is an external module, then create a new module of your own that has this structure:

```hcl
module "external" {
  source = "<THE SOURCE URL IN GITHUB">
  ...
}

module "mine" {
  source = "../security_groups"
  ...
}
```

`terragrunt apply-all` will run `terragrunt apply` on every module it finds in the current folder or any of its children. So another option is to have a `prod/us-east-1/foo` and `prod/us-east-2/bar` and to always run `apply-all` in the `prod-us-east-1` folder to deploy them both together. See https://github.com/gruntwork-io/terragrunt#execute-terraform-commands-on-multiple-modules-at-once.

**Comment by alkalinecoffee** [comment]
Sorry for the delay in response.  We ended up creating a shared module and used symlinks in our terragrunt directories to point at this symlink, which terraform will honor.  We'll be looking at your suggestion as well.  Much appreciated!
