### ISSUE TITLE
get_tfvars_dir -> get_terragrunt_dir missing in documentation

### ISSUE THREAD

**Issue by jfreeland** [gruntwork-io/terragrunt#817]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.12.1 refers to https://github.com/gruntwork-io/terragrunt#get_tfvars_dir which doesn't exist, nor does the page mention it.  For completeness, it might be handy to mention that get_tfvars_dir was renamed?  It could potentially help someone else to mention that it was renamed as it could slow them down when upgrading and rewriting old terragrunt files.

**Comment by ekini** [comment]
You are probably trying to use a very old version of terragrunt. The function was added in `v0.12.1` and got renamed in `v0.19`.

It is mentioned in the migration guide https://github.com/gruntwork-io/terragrunt/blob/master/_docs/migration_guides/upgrading_to_terragrunt_0.19.x.md#rename-a-few-built-in-functions

Version 0.12.1 was released in 2017.

**Comment by yorinasub17** [comment]
As @ekini mentioned, the function was renamed in `v0.19` and documented as such in the migration guide, which is linked in the release notes.

In the future, if you want to see the docs for a particular version, you can click the tag link to browse the repository at that tag:

<img width="928" alt="Release_v0_12_1_·_gruntwork-io_terragrunt" src="https://user-images.githubusercontent.com/430092/62756239-d9167b00-ba2b-11e9-8438-f3eb4152675c.png">
