### ISSUE TITLE
Easier way to do dependencies

### ISSUE THREAD

**Issue by jamie3** [gruntwork-io/terragrunt#836]
I'm looking for guidance on how to setup dependencies on terragrunt. I know you can specify the dependencies in the terragrunt.hcl file however I found this to be very cumbersome and error prone.

```hcl
dependencies {
  paths = ["../vpc", "../mysql", "../redis"]
}
```

Is there a way to setup terragrunt with some kind of master file that tells it the order in which to apply changes? For example, consider the following folder structure:

```
infrastructure\app-backend
infrastructure\app-frontend
infrastructure\db
infrastructure\network
```

And the folder for terragrunt

```hcl
live\app\backend\terragrunt.hcl
live\app\frontend\terragrunt.hcl
live\db\terragrunt.hcl
live\network\terragrunt.hcl
live\terragrunt.hcl
```

I would like to apply terraform in the following order:

- network
- db
- app\backend
- app\frontend

It would be nice to simply explicitly tell terragrunt to execute in this order.

```hcl
terragrunt = {

   execution_order {
      "network",
      "db"
      "app\backend",
      "app\frontend",
   }
}
```

**Comment by yorinasub17** [comment]
Given the imperative nature of the actions, it seems like this would be better handled in a script. E.g (in bash):

```bash
terragrunt apply network
terragrunt apply db
terragrunt apply app/backend
terragrunt apply app/frontend
```

Any reason why that doesn't work for you?

**Comment by billwang-au** [comment]
But if we do this, how to plan it? We can't `terragrunt plan app/backend`, I got something like: 

```
Encountered the following errors:
Cannot process module Module xxx/db (excluded: false, dependencies: [xxx/vpc]) because one of its dependencies, Module xxx/db (excluded: false, dependencies: [xxx/vpc]), finished with an error: Hit multiple errors:
exit status 1
Hit multiple errors:
exit status 1
```

**Comment by yorinasub17** [comment]
Closing as stale. If there is still a follow up question here, please open a new issue. Thanks!

For posterity on the latest question, the imperative bash script is offered as an alternative to describing all the dependencies as explicit dependency links in each individual terragrunt configuration. If you are using `dependency` to pass the dependency outputs around (as described in [the docs](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules)) then `run-all apply` is superior. As far as the `plan` issue goes, please make sure to read through the [warning about run-all plan](https://terragrunt.gruntwork.io/docs/reference/cli-options/#run-all), which I believe is what is causing the issues.
