### ISSUE TITLE
terragrunt 0.19 input variables in hcl file have different precedence from terragrunt 0.18 

### ISSUE THREAD

**Issue by primeroz** [gruntwork-io/terragrunt#842]
in terragrunt 0.18 variables defined in the terraform.tfvars had the highest precedence in terms of value so they allowed overriding values set in any of the common tfvars file 

in terragrunt 0.19 the variables set in the input of terragrunt.hcl are exported as environment variables which means they have the lowest possible precedence and get overwritten by values in the common tfvars files 

see "https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence" 

Is this an expected behavior ? 

I ended up moving the variables into an override.tfvars in the same directory as terragrunt.hcl and add an "extra_arguments" section

**Comment by ekini** [comment]
It's a compelled behaviour because of https://github.com/hashicorp/terraform/issues/22004 and https://github.com/hashicorp/terraform/issues/19424

**Comment by ekini** [comment]
But actually, what was the precedence back in 0.11?
Because even if the variables were in `terraform.tfvars`, the would be overridden by files from `-var-file` https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence

And I think it was the case for 0.11 as well.

**Comment by primeroz** [comment]
I will do some more testing when I get back from holidays.

What you are saying make sense but I am fairly sure the precedence worked
on 0.11 as I the value in terraform.tfvars had an higher priority

**Comment by primeroz** [comment]
you are right, from the docs in 0.11 

```
Definition files passed using the -var-file flag will always be evaluated after those in the working directory
```

The different behaviour was due to a slight change in my directory structure.

Since there is nothing to be done here i will close this issue
