### ISSUE TITLE
State from old version is not beeing read

### ISSUE THREAD

**Issue by terjohan** [gruntwork-io/terragrunt#843]
Hi, I am not sure if this is a bug or just a common user error, but i have been reading a lot of issues and guides. I have been unable to see why my issue appears. 
versions:
terragrunt version v0.19.19
Terraform v0.12.6

Folder structure:
```
xxxxx
     |----> dev
                   | --> eu-north-1
     .             .                 |--> db-folder
     .             .                 .             |--> terragrunt.hcl
     .             .                 |----> network folder
     .             .                 .              |--> terragrunt.hcl
     .             terragrunt.hcl (config file)
```
When i was on the older version (pre-*.hcl) i had config file one level out (in xxxxx folder) but in the new structure i moved it inside environment. 

my config file is fairly simple:
```
remote_state {
  backend = "s3"

  config = {
    key = "shared/${path_relative_to_include()}/terraform.tfstate"
    bucket         = "xxxyyy-terraform-shared-state-${get_aws_account_id()}"
    region         = "eu-north-1"
    encrypt        = true
    dynamodb_table = "terragrunt-locks"
  }
}

terraform {
  extra_arguments "variables" {
    commands = get_terraform_commands_that_need_vars()
  }
}

inputs = {
  aws_region = "eu-north-1"

  aws_account = "xxxxxxxxxx"

  # Append the account id to the bucket name / prefix.
  remote_state_bucket = "xxxyyy-terraform-shared-state-xxxxxxxx"

}
```

my terragrunt.hcl in database is:
```
# Include all settings from the root terragrunt.hcl file
include {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../../../modules/shared/database/rds-common-postgres"
}

inputs = {
  additional_access_ip_list = []
}
```
aws_provider beeing used is currently 
```
provider "aws" {
  region  = "${var.aws_region}"
  version = "2.25.0"
}
```
this beeing run in previous version has generated the state file correctly placed in the s3 bucket addressed. When i run terragrunt plan with newest version it seems it does not read my state file in s3, and tells me that x new resources will be created.
Is there something missing or problematic with reading state files from older versions?

**Comment by brikis98** [comment]
> remote_state {
> backend = "s3"
>
>  config = {
>    key = "shared/${path_relative_to_include()}/terraform.tfstate"
 
If you're using `path_relative_to_include`, Terragrunt is calculating the `key` value for the state based on the relative path between the parent `terragrunt.hcl` and the child `terragrunt.hcl`.

>When i was on the older version (pre-*.hcl) i had config file one level out (in xxxxx folder) but in the new structure i moved it inside environment.

If you moved your root `terragrunt.hcl`, the relative path is different, so you're not finding your old state files.

**Comment by terjohan** [comment]
@brikis98 Thank you for your answer! i read a guide that stated you should have your config files under each environment, so i moved it. Moving it back made it function properly, but i need to extract environment specific variables.
