### ISSUE TITLE
PR requests and backporting to terragrunt V0.18.x, Refs #112

### ISSUE THREAD

**Issue by mattiarossi** [gruntwork-io/terragrunt#845]
Hi, I am working on a PR to implement the following:

-  honor the dynamodb_endpoint s3 parameter added in terraform v0.11 (https://www.terraform.io/docs/backends/types/s3.html#dynamodb_endpoint )

This would allow to use a custom Dynamodb endpoint for terragrunt as well.

Internally, we've branched the latest v0.18x tag and implemented and tested the changes there, but I am planning to create a PR against master. 
Would you be willing to backport this to the latest 0.18 train as well? I really don't like having diverging branches :)

**Comment by brikis98** [comment]
We unfortunately don't have the resources to maintain multiple releases at the moment 😢

**Comment by mattiarossi** [comment]
Understood.
I'll get on with a PR for 0.19 then, and that will be one more reason to move to the new terraform/terragrunt train :)

**Comment by mattiarossi** [comment]
.. and after having a thought about it (and working on a second fix to backport) I was wondering whether it would be an option to maintain separately a 0.18.x train.
Had a look at the CircleCI job definition, and it looks like it is using docker images pulled from a private repo. I see there is something analogous in dockerhub's gruntwork account, but am not sure. Is there a way to use these images or, in alternative, to get a Dockerfile so that I can rebuild them ?

**Comment by brikis98** [comment]
The Docker images don't have anything magical in them. It's a fairly standard Go app: https://github.com/gruntwork-io/terragrunt#developing-terragrunt

**Comment by mattiarossi** [comment]
Thanks,
I was going for something that already has the gruntwork-install script as well, the circleci image in your dockerhub account is more than enough.
I have been successful in running the build and deploy workflows, will add the integration and unit tests as soon as possible. The idea is to maintain a 0.18.x train with backported bugfixes for internal use and for whomever may need it

**Comment by yorinasub17** [comment]
Closing as the original question has been answered. If there are any follow ups, please open a new issue. Thanks!
