### ISSUE TITLE
terragrunt.hcl.json ?

### ISSUE THREAD

**Issue by maver1ck** [gruntwork-io/terragrunt#846]
Terraform (and HCL parser) support json input file.
Is it possible to use json as input to terragrunt ?

https://www.terraform.io/docs/configuration/syntax-json.html

**Comment by brikis98** [comment]
Not currently supported. What's the use case?

**Comment by maver1ck** [comment]
Automatic generation of hcl files by python script.
I prefer json dump than custom jinja templates.

**Comment by brikis98** [comment]
Gotcha. I'd be open to a PR for this if it doesn't blow up the complexity of config parsing.

**Comment by jakauppila** [comment]
I'd be interested in this as well as we may be looking at automating the creation of the `terragrunt.hcl` configuration.

After a little poking around, it looks like it might be a matter of adding some parsing of the Terragrunt configuration extension and utilizing `ParseJSON` from `hashicorp/hcl2` https://github.com/hashicorp/hcl2/blob/master/hclparse/parser.go#L74 at https://github.com/gruntwork-io/terragrunt/blob/master/config/config.go#L296 to read in the configuration ?

Would that be the right direction or is there more to consider?

**Comment by brikis98** [comment]
Possibly! `ParseJSON` returns an `*hcl.File`, so assuming it's the same format we'd get from the HCL parser, then that might work...

**Comment by jakauppila** [comment]
Threw together a super quick test at https://github.com/jakauppila/terragrunt/commit/b81197805401f2f2d8cc8ed7535af339edea7c0d and appears to be working fine.

How extensive should the JSON config tests be? Should they just mirror all of the HCL config tests?
