### ISSUE TITLE
Allow replication of state s3 buckets

### ISSUE THREAD

**Issue by dmattia** [gruntwork-io/terragrunt#859]
Cross-Region Replication is necessary for my team to achieve SOC2 compliance.

This entails adding a block such as:

```terraform
replication_configuration {
    role = module.tf_state_replica.role_arn

    rules {
      id     = "FullReplica"
      prefix = ""
      status = "Enabled"

      destination {
        bucket        = module.tf_state_replica.bucket_arn
        storage_class = "STANDARD_IA"
      }
    }
  }
```

to the s3 bucket and having another bucket created in a different region.

https://docs.aws.amazon.com/AmazonS3/latest/dev/crr.html

**Comment by dmattia** [comment]
As a current work around, I am creating the replica bucket in a module, having all other modules depend on that module, and then manually going into the aws console to update the replication settings of my state buckets

**Comment by brikis98** [comment]
Are you asking if the S3 bucket created by Auto Init in Terragrunt can configure replication for the bucket too? If so, that strikes me as a bit too advanced for Terragrunt's Auto Init. At that point, you're better off creating the S3 bucket in Terraform, initially with a local backend, and once the bucket works the way you want, switch that Terraform module and all your other modules to use the S3 bucket as a backend.

**Comment by dmattia** [comment]
That is what I was asking. Would this be something you would even be open to a PR for, or would you rather it not be in the project at all?

**Comment by brikis98** [comment]
As I said:

> If so, that strikes me as a bit too advanced for Terragrunt's Auto Init.

I think this would be better handled outside of Terragrunt.
