### ISSUE TITLE
Add Terragrunt Choco Installation to Docs

### ISSUE THREAD

**Issue by DrFaust92** [gruntwork-io/terragrunt#862]
Hi,

I added terragrunt as a package to [chocolatey](https://chocolatey.org) some time ago and thought it may be helpful to add this the the installation part of the README under Windows

the link to the package: https://chocolatey.org/packages/terragrunt

I can open the the PR myself just want to make sure its relevant.

**Comment by brikis98** [comment]
A PR sounds great, thanks!
