### ISSUE TITLE
S3 - Is checking permission `GetBucketVersioning` required?

### ISSUE THREAD

**Issue by jakauppila** [gruntwork-io/terragrunt#867]
It was a bit confusing when configuring Terragrunt under CI/CD and looking at the Terraform required [S3/DynamoDB IAM policies defined in the documentation](https://www.terraform.io/docs/backends/types/s3.html#s3-bucket-permissions) yet getting 403s in execution.

I feel like creating the bucket with versioning (and disabling it if the configuration is set) is fine, but always checking it on initialization seems unnecessary ?

I see a few options:

1. Remove the `GetBucketVersioning` check on initialization, required permissions now match Terraform documentation.
2. Setting `SkipBucketVersioning` within the S3 config also skips checking on initialization.
3. Leave as-is, it's my fault for not reading through the Terragrunt readme over again

---

`SkipBucketVersioning` skips enabling bucket versioning when Terragrunt creates a bucket at https://github.com/gruntwork-io/terragrunt/blob/272c78fe20a10e35a9ce4b8b591609dcc01283c3/remote/remote_state_s3.go#L365

But it doesn't prevent Terragrunt from checking if bucket versioning is enabled on intialization at https://github.com/gruntwork-io/terragrunt/blob/272c78fe20a10e35a9ce4b8b591609dcc01283c3/remote/remote_state_s3.go#L214

**Comment by brikis98** [comment]
If `SkipBucketVersioning`, Terragrunt should indeed skip the versioning check. PR to fix that is very welcome!
