### ISSUE TITLE
Allow to ignore dependency order when using Terragrunt plan-all

### ISSUE THREAD

**Issue by JeanFred** [gruntwork-io/terragrunt#868]
When using terragrunt `plan-all`, terragrunt will smartly run the plans according to the dependency tree, parallelizing as much as possible.
Additionally, when using `exclude-dir`, terragrunt will not run the downstream layers of the excluded layers.

This makes perfect sense for `apply-all` and `destroy-all`, however it should not really matter for `plan-all` since the state is not altered between the plans. 

This is a proposal to “Allow to ignore the dependency tree”, for these two purposes:
- to run all layers in parallel
- to run the downstream layers of excluded layers

Our use case is for testing on a CI server:
- running all layers in parallel would save a couple minutes.
- because reasons, we cannot plan some layers in CI (insufficient permissions), however we can plan other layers which depend on them.

(happy to split into two tickets if that’s better)

**Comment by brikis98** [comment]
That's a great point. PR to change this behavior is very welcome!

**Comment by JeanFred** [comment]
@brikis98 Thanks for the answer − I may try my hand at filing a PR for this :)

To clarify, what should the outcome be?
* the current default behaviour of `plan-all` is changed to ignore the tree
* a new flag/env var changes the behaviour of `plan-all` with both changes (all in parallel, still running dependencies of skipped layers)
* two different flag/env var changes the behaviour of `plan-all`

**Comment by brikis98** [comment]
It's possible some users will need `plan-all` to run in dependency order: e.g., perhaps they have before/after hooks that do something important and won't work if it's all in parallel.

So, a `--terragrunt-ignore-dependency-tree` flag is probably the right approach. Thx!

**Comment by JeanFred** [comment]
For clarity, I’ve split off the second part in #905. Closing this as resolved then!
