### ISSUE TITLE
Use resources from other enviroments

### ISSUE THREAD

**Issue by Cr4mble** [gruntwork-io/terragrunt#869]
I asked this question on Stackoverflow but didnt get an answer so i ask it here:
I want to use resources, in this case the output of the vpc module, in another environment. Goal is to reduce the costs for the customer with resources of stage and dev in the same vpc. Stage and dev have seperate ecs-cluster, asg, lc, different docker images in ecr etc but should be in the same vpc with the same load balancer and then a host header listener to forward to the specific target group. Both should use the same database and the same load balancer.

Requirement was to have n Customer each with stage, dev and prod environments. All Customer folders should contain the three environments.

My folder structure is:
├── Terraform
│   ├── Customer1
│   ├── Customer2
│   ├── Customer3
│   ├── Customer4
│   ├── Customer5
│   ├── Global
│   │   ├── iam
│   │   │   └── terragrunt.hcl
│   ├── README.md
│   └── Customer6
│       ├── non-prod
│       │   ├── eu-central-1
│       │   │   ├── dev
│       │   │   │   ├── cloudwatch
│       │   │   │   │   └── terragrunt.hcl
│       │   │   │   ├── ec2
│       │   │   │   │   └── terragrunt.hcl
│       │   │   │   ├── ecs
│       │   │   │   │   └── terragrunt.hcl
│       │   │   │   ├── lambda
│       │   │   │   │   └── terragrunt.hcl
│       │   │   │   ├── rds
│       │   │   │   │   └── terragrunt.hcl
│       │   │   │   ├── terragrunt.hcl
│       │   │   │   ├── vars.hcl
│       │   │   │   └── vpc
│       │   │   │       └── terragrunt.hcl
│       │   │   ├── region.hcl
│       │   │   └── stage
│       │   │       ├── cloudwatch
│       │   │       │   └── terragrunt.hcl
│       │   │       ├── ec2
│       │   │       │   └── terragrunt.hcl
│       │   │       ├── ecs
│       │   │       │   └── terragrunt.hcl
│       │   │       ├── lambda
│       │   │       │   └── terragrunt.hcl
│       │   │       ├── rds
│       │   │       │   └── terragrunt.hcl
│       │   │       ├── terragrunt.hcl
│       │   │       ├── vars.hcl
│       │   │       └── vpc
│       │   │           └── terragrunt.hcl
│       │   └── terragrunt.hcl
│       └── prod
│           └── eu-central-1
│               ├── prod
│               │   ├── cloudwatch
│               │   │   └── terragrunt.hcl
│               │   ├── ec2
│               │   │   └── terragrunt.hcl
│               │   ├── ecs
│               │   │   └── terragrunt.hcl
│               │   ├── lambda
│               │   │   └── terragrunt.hcl
│               │   ├── rds
│               │   │   └── terragrunt.hcl
│               │   ├── terragrunt.hcl
│               │   ├── vars.hcl
│               │   └── vpc
│               │       └── terragrunt.hcl
│               └── region.hcl
└── Modules
    ├── cloudwatch
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   └── Variables.tf
    ├── ec2
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   └── Variables.tf
    ├── ecs
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   └── Variables.tf
    ├── iam
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   └── Variables.tf
    ├── lambda
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   └── Variables.tf
    ├── rds
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   └── Variables.tf
    ├── vpc
    │   ├── Main.tf
    │   ├── Outputs.tf
    │   ├── Variables.tf
    └── vpc-stage
        ├── Main.tf
        ├── Outputs.tf
        └── Variables.tf

I've read about data terraform_remote_state but that's on module layer. For me it's not a good approach to do this in the module layer cause it's only for the stage enviroment. Is there a way to get the output from the remote state in the terragrunt.hcl in the stage folder from the dev environment to use this as input for the ec2 module?

I've used
`dependency "vpc" {
  config_path = "../vpc"
}`

and then
`vpc_id = dependency.vpc.outputs.vpc_id`

for the input of ec2 module but that's only if it's in the same enviroment.

Best regards.

**Comment by yorinasub17** [comment]
Assuming the dev and stage environments are in the same account (which it sounds like it is if it is in the same VPC), `dependency` blocks should work. AFAIK, this is the only limitation of `dependency`.

So there should be nothing preventing you from reading the stage environment vpc output using `dependency` blocks and using it in the dev environment. Are you seeing an error when you try that?

**Comment by Cr4mble** [comment]
Hi yorinasub17 and thank you for your reply. Yes that works totally fine. I thought that dependencies are only per enviroment. Didn't think about referencing the vpc of the other enviroment. Just so simply and effective but didn't see that.
Thanks
