### ISSUE TITLE
Add and maintain a CHANGELOG file

### ISSUE THREAD

**Issue by jecnua** [gruntwork-io/terragrunt#87]
Hi all,
This is an enhancement I suppose. :)
Today a new version of terragrunt is out and I was interested in reading about the changes but there is no CHANGELOG.md to check. It would help us users understand if there is any new functionality/breaking changes/bug fix that may impact us without checking the blog.

Thanks you,
F.

**Comment by josh-padnick** [comment]
Hey Fab!

We've thought about doing a CHANGELOG in the past, but our concern is that we'd forget to update it, so we make sure to include all "what's new" notes for each release, and you can see them on the [Releases Page](https://github.com/gruntwork-io/terragrunt/releases).

Do you feel a CHANGELOG would add additional value beyond this?

**Comment by jecnua** [comment]
Hi Josh,

sorry for the delay in writing this reply. I suppose is all a question of habits. When pulling a new repo or updating an existing one to a new version, that is what people usually do (checks the CHANGELOG). This is why I was surprised not to find one.
We can totally read the "what's new" note in the release, is just not what people expects to do ^^
Until the changes are small as they are now, I don't think is a problem. May be worth reconsidering the process when chages starts to pile up between releases.
I will close the ticket, thank you for considering this option. :)

F.

PS: Happy new year to all you guys at gruntwork-io :)

**Comment by josh-padnick** [comment]
Thanks for the input, Fab, and duly noted!
