### ISSUE TITLE
Is the source attribute mandatory ?

### ISSUE THREAD

**Issue by rgarrigue** [gruntwork-io/terragrunt#878]
Hi

I'm relying on hook to copy some files, like the empty s3 backend to be filed by terragrunt later on. 

My problem is, when I don't have a source field (because sometimes just a bit of terraform is good enough for testing stuff), I don't have my copy. Tried a whole lot of command, none seems to take effect. 

Is the source field mandatory ? Can't I just use terragrunt here and there for a bit of terraform without module ?

**Comment by brikis98** [comment]
`source` is not mandatory.

> My problem is, when I don't have a source field (because sometimes just a bit of terraform is good enough for testing stuff), I don't have my copy.

Can you share more of your code and the log output so we can understand what you mean?

**Comment by rgarrigue** [comment]
I've a parent terragrunt like this

```hcl
remote_state {
  backend = "s3"
  config = {
    bucket         = "terraform-states-it"
    dynamodb_table = "terraform-locks-it"
    encrypt        = true
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"

    # Make it faster by skipping something
    skip_credentials_validation = true
    skip_get_ec2_platforms      = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
  }
}

terraform {
  after_hook "copy_provider_resources" {
    commands = ["init-from-module"]
    execute  = ["cp", "${find_in_parent_folders("provider.tf")}", "."]
  }
}
```

The provider.tf is

```
terraform {
  backend "s3" {}
}

provider "aws" {
  allowed_account_ids = var.aws_allowed_accounts_ids
  region              = var.aws_region
  version             = "~> 2.29"
}
```

And for the example I created a test/ folder with `terragrunt.hcl`

```
include {
  path = find_in_parent_folders()
}
```

and a main.tf doing mostly nothing.

Here the plan command log

```
~/work/terraform-live/development/aws/eu-west-1/test (master ✘)✖✹✭ ᐅ terragrunt plan
[terragrunt] 2019/09/25 11:47:27 Reading Terragrunt config file at /home/remy/work/terraform-live/development/aws/eu-west-1/test/terragrunt.hcl
[terragrunt] [/home/remy/work/terraform-live/development/aws/eu-west-1/test] 2019/09/25 11:47:27 Running command: terraform --version
[terragrunt] 2019/09/25 11:47:27 Found remote_state settings in /home/remy/work/terraform-live/development/aws/eu-west-1/test/terragrunt.hcl but no backend block in the Terraform code in /home/remy/work/terraform-live/development/aws/eu-west-1/test. You must define a backend block (it can be empty!) in your Terraform code or your remote state settings will have no effect! It should look something like this:

terraform {
  backend "s3" {}
}
```

Reason is, the hook didn't execute : no `source` mean no `init-from-module`. So replacing command by `init` should do, right ? But same error. Tried other commands, none work. 

Maybe I missed something, but so far I can't use basic terraform, I must use a module. Maybe it's a better idea, but still I'ld like to have the option, just for testing stuff.

**Comment by lorengordon** [comment]
As a workaround, try `source = "."`

The `init-from-module` workflow is not triggered if there is no `source` argument. And the `init` workflow is incompatible (currently) with copying the provider definition.

Related issues:
* https://github.com/gruntwork-io/terragrunt/issues/749
* https://github.com/gruntwork-io/terragrunt/issues/785

**Comment by rgarrigue** [comment]
Ok thanks for the workaround. Closing this, I'll follow the related issue for updates.
