### ISSUE TITLE
Blocks of type dependency are not expected here

### ISSUE THREAD

**Issue by agdespopoulos** [gruntwork-io/terragrunt#880]
Ok, this feels a little ridiculous, because it's so simple, but I can't get Terragrunt to run with a dependency block. When running seemingly any Terragrunt command, the following error comes up. I've tried it with `hclfmt`, `validate`, `validate-all`, `plan`, and `plan-all` specifically, from both the root and `api` directories - all fail with the same error.

```
% terragrunt validate
[terragrunt] [/home/redacted/api] 2019/09/25 15:13:10 Running command: terraform --version
[terragrunt] 2019/09/25 15:13:11 Reading Terragrunt config file at /home/redacted/api/terragrunt.hcl
[terragrunt] 2019/09/25 15:13:11 /home/redacted/api/terragrunt.hcl:5,1-11: Unsupported block type; Blocks of type "dependency" are not expected here.
[terragrunt] 2019/09/25 15:13:11 Unable to determine underlying exit code, so Terragrunt will exit with error code 1
```

My directory looks like this:

```
.
├── terragrunt.hcl
├── api
│   ├── main.tf
│   └── terragrunt.hcl
└── vpc
    ├── main.tf
    └── terragrunt.hcl
```

`api/terragrunt.hcl` looks like this:

```hcl
include {
  path = find_in_parent_folders()
}

dependency "vpc" {
  config_path = "../vpc"
}
```

There also used to be an `input` block that referenced the some outputs of the VPC dependency, but I got rid of it for now while trying to narrow this down.

The VPC module (which is also very simple) validates, plans, and applies just fine, but it also doesn't have a `dependency` block.

Happy to include anything else, but it's an extremely simple configuration, obviously. Not sure what I'm doing wrong here.

Terragrunt v0.19.17 (upgraded from v0.19.16 after seeing the same problem there)
Terraform v0.12.9

**Comment by yorinasub17** [comment]
`dependency` blocks were introduced in terragrunt `v0.19.20`: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.20, so you need to upgrade to at least that version.

**Comment by yorinasub17** [comment]
Ah forgot to mention that we had a few bug fixes to `dependency` along the way, so you will want to update to the latest version ([0.19.27](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.19.27)) if you can.

Let us know if it still doesn't work after upgrading!

**Comment by agdespopoulos** [comment]
Well, I knew it was something stupid. Tried to be smart and pin my terragrunt version and managed to pin it to 0.17 instead of 0.27... Thanks for the help.
