### ISSUE TITLE
Is there a CDN or link to download tarballs or zips for inclusion in Dockerfiles?

### ISSUE THREAD

**Issue by Gabelbombe** [gruntwork-io/terragrunt#881]
We're looking to build our Jenkins slaves with a non-AWS auth url (which is unrelianble without witchcraft) so we can build a set version of the AMD 64 v0.19.27 release binary. Is there a binary releases page that can be leveraged?

Something like:

```bash
###############################
### INSTALL Terragrunt 64 BIT ##
###############################
RUN wget --quiet https://github.com/gruntwork-io/terragrunt/archive/v0.19.27.zip \
 && unzip v0.19.27.zip \
 && mv terragrunt /usr/bin \
 && rm v0.19.27.zip
```

**Comment by yorinasub17** [comment]
Thanks for your inquiry! Each [release we publish](https://github.com/gruntwork-io/terragrunt/releases) has the binary attached, so you should be able to get the binary you need using something like the following:

```
wget --quiet https://github.com/gruntwork-io/terragrunt/releases/download/$VERSION/terragrunt_linux_amd64
```

**Comment by Gabelbombe** [comment]
Thanks you're absolutely correct.
