### ISSUE TITLE
"terragrunt apply-all" doesn't support -help?

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#884]
Can't get help with command `apply-all`

    terragrunt apply-all --help

    terragrunt apply-all -help

Seems `destroy-all` doesn't support `help` option as well. 

Could we have some helps for these commands?

**Comment by yorinasub17** [comment]
Due to the way the command passing works between terragrunt and terraform, this is a bit tricky to implement but definitely agreed we can improve this. A bit buried to implement this, but if anyone has cycles, would be happy to review a PR.

**Comment by levkohimins** [comment]
Resolved in [v0.48.7](https://github.com/gruntwork-io/terragrunt/releases/tag/v0.48.7) release.
