### ISSUE TITLE
Document variable precedence between dependency variable and common.tfvars variable

### ISSUE THREAD

**Issue by hehnope** [gruntwork-io/terragrunt#887]
I searched the issues to see if this question was asked; did not see that it was.

If I have a variable dependency from a module, such as like below:

```
inputs = {
  region   = dependency.vpc.outputs.region
}
```

But, I also have a `common.tfvars` like below:

```
region      = "us-west-2"
```

Which variable takes precedence?

**Comment by yorinasub17** [comment]
The variables from terragrunt inputs are set as environment variables (`TF_VAR_variable_name`), so they are the lowest precedence as mentioned in [the official tf docs](https://www.terraform.io/docs/configuration/variables.html#variable-definition-precedence).

But that is a good point that this isn't documented!

**Comment by yorinasub17** [comment]
I updated the issue to reflect the lack of documentation and will keep this open until we resolve the missing docs.

**Comment by hehnope** [comment]
@yorinasub17 can you assign it to me? I'll send a PR with updated readme.

**Comment by yorinasub17** [comment]
Feel free to jump in and open the PR! Your comment above is enough to indicate ownership.

**Comment by hehnope** [comment]
#889 was merged, so closing.
