### ISSUE TITLE
Inconsistent cache behavior for TF modules (symlinking and copying)

### ISSUE THREAD

**Issue by agrzegorczyk-leonsoftware** [gruntwork-io/terragrunt#896]
Terragrunt: 0.19.28
Terraform: 0.12.9

I observed some inconsistent cache behavior when I use multiple instances of the same terraform module (local modules with absolute paths).

For example, when I have definitions like this:
```
module "app-config_stable" {
  source = "/home/devops/terragrunt/tf-modules/app-config2s3"
  <some parameters>
}

module "app-config_rc" {
  source = "/home/devops/terragrunt/tf-modules/app-config2s3"
  <some parameters>
}

module "app-config_bgjobs" {
  source = "/home/devops/terragrunt/tf-modules/app-config2s3"
  <some parameters>
}
```
after `terragrunt init` 
 ```
Initializing modules...
Downloading /home/devops/terragrunt/tf-modules/app-config2s3 for app-config_bgjobs...
- app-config_bgjobs in .terraform/modules/app-config_bgjobs
Downloading /home/devops/terragrunt/tf-modules/app-config2s3 for app-config_rc...
- app-config_rc in .terraform/modules/app-config_rc
Downloading /home/devops/terragrunt/tf-modules/app-config2s3 for app-config_stable...
- app-config_stable in .terraform/modules/app-config_stable
```
my cache folder looks like that :

```
$ ls -l .terragrunt-cache/KEfyB7ITkLsPXqImO_Z92_U_A-g/fx0EFDFeTvQ9pVZgnTHLPg1JonE/.terraform/modules/ | grep 'config'
lrwxrwxrwx 1 geck geck   48 Oct  7 18:16 app-config_bgjobs -> /home/devops/terragrunt/tf-modules/app-config2s3
drwxrwxr-x 2 geck geck 4096 Oct  7 18:16 app-config_rc
drwxrwxr-x 2 geck geck 4096 Oct  7 18:16 app-config_stable
```

One instance of the module is symlinked and all others are copied. AFAIS this behavior is repeatable, always the same, and only one instance is symlinked. This applies to all other used TF modules.
Personally, I prefer symlinking over copying in that case, but more important is consisted behavior for all occurrences of the module because current situation produces hard-to-tracking side effects.

**Comment by lorengordon** [comment]
I'm fairly certain this is a TF 0.12 feature, where it now detects whether multiple modules reference the same source and only downloads the source one time. Other module instances are symlinked to the downloaded copy (presuming the OS supports symlinks).

However, now I cannot find the reference for that feature... Was either in a GitHub issue or one of the TF 0.12 blog entries...

**Comment by lorengordon** [comment]
Here it is: https://github.com/hashicorp/terraform/issues/11435#issuecomment-435680988

**Comment by agrzegorczyk-leonsoftware** [comment]
@lorengordon 
Thank you for comment, but this is exactly the opposite: one symlink to the source and many independent copies of it.

**Comment by yorinasub17** [comment]
Do you get the exact same inconsistent behavior if you use `terraform` directly, without going through `terragrunt`?

**Comment by agrzegorczyk-leonsoftware** [comment]
@lorengordon 
You probably are right about the root cause of this problem. This behavior can be a side effect of change you linked.
@yorinasub17 
In fact, this problem occurs on a terraform level, not terragrunt.

Thank you both for your tips, I will recreate this issue on terraform repo.

**Comment by agrzegorczyk-leonsoftware** [comment]
https://github.com/hashicorp/terraform/issues/23031
