### ISSUE TITLE
Build with a more recent version of terraform

### ISSUE THREAD

**Issue by johanfleury** [gruntwork-io/terragrunt#902]
# Description

As a way to work around [Terraform not supporting setting variables that are not declared in root modules anymore](https://github.com/hashicorp/terraform/issues/19424) and [Terragrunt not supporting multiple include's level](https://github.com/gruntwork-io/terragrunt/issues/303), we were trying to use the `regexall` function to create “conditional `extra_arguments` block” (see example below).

The `regexall` function was introduced in Terraform version 0.12.7, but is not present in Terragrunt has it is built with [Terraform version 0.12.6](https://github.com/gruntwork-io/terragrunt/blob/master/Gopkg.toml#L82)

# Current behavior

With the following `terragrunt.hcl`:

```
terraform {
  extra_arguments "gcp_vars" {
    commands = length(regexall("^foobar/.+", get_terragrunt_dir())) > 0 ? get_terraform_commands_that_need_vars() : []

    arguments = [
      "-var", "foobar=${get_terragrunt_dir()}/../../foo.bar"
    ]
  }
}
```

Terragrunt fails with:

```
[terragrunt] 2019/10/09 10:50:48 Error processing module at '[SNIPPED]/projects/foo/bar/ca/terragrunt.hcl'. How this module was found: Terragrunt config file found in a subdirectory of [SNIPPED]/projects/foo/bar/. Underlying error: [SNIPPED]/projects/terragrunt.hcl:25,23-31: Call to unknown function; There is no function named "regexall"., and 1 other diagnostic(s)
```

# Expected behavior

Terragrunt should be able to execute `regexall`.

# Proposed fix

Update the terraform version constraint to at least [0.12.7 (released in august 2019)](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0127-august-22-2019).

Also, it would be great to add the Terraform version on which Terragrunt was built in the output of `terragrunt --version`.

**Comment by brikis98** [comment]
PR welcome!

**Comment by johanfleury** [comment]
I can do the PR if all it takes is changing the constraint in Gopkg.toml and validating that build/tests still work.

I was just wondering, what do you think would be the best way to keep in sync with Terraform in the future? Would it be possible and/or wanted to build Terragrunt with the latest version of Terraform?

**Comment by lorengordon** [comment]
> I was just wondering, what do you think would be the best way to keep in sync with Terraform in the future?

[Dependabot](https://dependabot.com/) does a great job of making it easy...

**Comment by brikis98** [comment]
> I was just wondering, what do you think would be the best way to keep in sync with Terraform in the future? Would it be possible and/or wanted to build Terragrunt with the latest version of Terraform?

Terraform is pre 1.0.0 and backwards incompatible / breaking changes are quite frequent... I'd be tempted to opt in to upgrades manually rather than automatically for now. Thx!

**Comment by lorengordon** [comment]
The wonderful thing about leveraging Dependabot, is it just opens a PR. (It *can* automatically merge also, if you want, but it is optional.) The PR makes it easy for CI to execute tests, plus raises awareness that changes have occurred in the project's dependencies.

**Comment by brennerm** [comment]
Created a PR to bump up the version.

Also had a look at printing the Terraform version. Right now I see no "clean" way of achieving this as urfave is taking care of handling the `--version` flag.
