### ISSUE TITLE
no `init-all` so what do you recommend?

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#913]
When run with new version of terraform with terragrunt, it will ask for `init` first. 

But there is no `init-all` option currently.

What did you do with this situation?

Currently I write a quick script to go through the files of `terragrunt.hcl` and run `terragrunt init` in each folder.

**Comment by yorinasub17** [comment]
> Currently I write a quick script to go through the files of terragrunt.hcl and run terragrunt init in each folder.

This is basically what most people do. See also https://github.com/gruntwork-io/terragrunt/issues/609#issuecomment-441751036

https://github.com/gruntwork-io/terragrunt/issues/492 and https://github.com/gruntwork-io/terragrunt/issues/388 are the relevant bugfixes and feature improvements to achieve `init-all` like capability. Note that we have not gotten around to start on these yet.

We would also be happy to review a PR that adds `init-all` as an interim workaround (https://github.com/gruntwork-io/terragrunt/issues/388#issuecomment-360773506).
