### ISSUE TITLE
Using relative get_terragrunt_dir in deeper terragrunt.hcl where include fails

### ISSUE THREAD

**Issue by jondkelley** [gruntwork-io/terragrunt#915]
terragrunt version v0.19.19
terraform version 0.12.x

I've got a project with this sort of logical structure

```
|── account_names.tfvars.json
|── groups
|   |── team
|   │   |── dev
│   │   │    |── terragrunt.hcl
│   │   │    |── terraform.tfvars.json
│   │   │    |── vpc
│   │   │    │   └── terragrunt.hcl
│   │   │    |── ec2
│   │   │    │   └── terragrunt.hcl
│   │   │    |── jenkins
│   │   │    │   └── terragrunt.hcl
```
The "root" terragrunt.hcl contains the relative paths in extra_vars as described in the documentation.

```
#### ./groups/team/dev/terragrunt.hcl
terraform {
  extra_arguments "custom_vars" {
    commands = [
      "apply",
      "plan",
      "import",
      "push",
      "refresh",
    ]
    arguments = [
      "-var-file=${get_terragrunt_dir()}/../../../account_names.tfvars.json",
    ]
  }

remote_state {
  backend = "s3"

  config = { stuff....... }
}
```

The leaf terragrunt.hcl uses include to inherit the parent (because DRY is the dream)

```
#### ./groups/team/dev/vpc/terragrunt.hcl
# Include all settings from the root terragrunt.hcl file
include {
  path = find_in_parent_folders()
}

terraform {
  source = "git::git@github.com:my_org/tf-modules.git//aws/ec2/vpc?ref=develop"
}
```

The following error will occur:

`Given variables file
/workspace/groups/group/dev/vpc/../../../account_names.tfvars.json
does not exist.`

Of course it doesn't, it needs an extra `..` to exist.

Should I duplicate the `terraform { extra_arguements {} }` to overload these settings in a deeper level with extra `..`, or how should this work in practice? The docs don't go into this level of detail. Where should my module folder with `terragrunt.hcl` to an external source live?

I have so many projects, I actually need `account_names.tfvars.json` at my repository root for many seperate projects under `groups`.

Feels like I'd have to put my module parallel to my `groups/dev/team/dev/` folder for relative paths to work, but then `include { path = find_in_parent_folders() }` would never work, as it would be a leaf path in the parent (`../dev`), but not strictly in a parent folder.

There's got to be a way to inherit higher level common region-level variables across included namespaces.

**Comment by yorinasub17** [comment]
I think you want to use [get_parent_terragrunt_dir](https://github.com/gruntwork-io/terragrunt#get_parent_terragrunt_dir) here, which would return the directory of the included `terragrunt.hcl` file.

**Comment by jondkelley** [comment]
@yorinasub17 Very true. Saw this in the docs earlier today, but terragrunts been an adventure and forgot =)

Seems like the modules are trying to run now, thanks so much!
