### ISSUE TITLE
Access Denied when using S3 and assume role

### ISSUE THREAD

**Issue by kromol** [gruntwork-io/terragrunt#919]
I'm facing `Access Denied` error when using `remote_state S3`. This is how it's declared in the root `terragrunt.hcl`:
```
remote_state {
  backend = "s3"
  config  = {
    bucket   = "BUCKET NAME"
    region   = "us-east-1"
    profile  = "my profile"
    role_arn = "arn:aws:iam::ACCOUNT_NUMBER:role/my role"
    key      = "dev/terraform.tfstate"
  }
}

```
In `terraform` module that is included:
```
terraform {
  backend "s3" {}
}
```

When I'm running it with `terragrunt plan-all` I'm getting following logs:
```
...
Initializing remote state for the s3 backend
[terragrunt] 2019/10/18 18:28:07 Encountered the following errors:
AccessDenied: Access Denied
```

If I move remote state configuration to `tf` file and run the same command everything works fine.

Versions:
```
kromol@kromol-i7:~$ terraform -v
Terraform v0.12.10
kromol@kromol-i7:~$ terragrunt -v
terragrunt version v0.20.4
```

Am I missing something?

Thanks

**Comment by yorinasub17** [comment]
So what is failing is terragrunt's routine for setting up the S3 bucket, and terragrunt doesn't use the `role_arn` parameter set on the remote state config for it's authentication.

To assume a role with terragrunt, you will need to use the terragrunt configuration parameters: https://github.com/gruntwork-io/terragrunt#configuring-terragrunt-to-assume-an-iam-role

**Comment by kromol** [comment]
I've just found a solution. The problem is that `terragrunt` requires more permissions than `terraform`. 
[From terraform docs](https://www.terraform.io/docs/backends/types/s3.html#s3-bucket-permissions):
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:ListBucket",
      "Resource": "arn:aws:s3:::mybucket"
    },
    {
      "Effect": "Allow",
      "Action": ["s3:GetObject", "s3:PutObject"],
      "Resource": "arn:aws:s3:::mybucket/path/to/my/key"
    }
  ]
}
```
This is the permissions needed, but it does not work with `terragrunt`. I've found [another thread on terragrunt forum](https://community.gruntwork.io/t/minimum-permissions-needed-for-s3-backed/164) with similar problem, and solution suggested there works. This is the correct permissions for `terragrunt`:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
                "s3:ListBucket",
                "s3:GetBucketVersioning",
                "s3:CreateBucket"
            ],
      "Resource": "arn:aws:s3:::mybucket"
    },
    {
      "Effect": "Allow",
      "Action": ["s3:GetObject", "s3:PutObject"],
      "Resource": "arn:aws:s3:::mybucket/path/to/my/key"
    }
  ]
}
```
I will re-check docs one more time and will open PR to adjust docs if it's missing there.

**Comment by yorinasub17** [comment]
Got it. Yup that makes sense, since Terragrunt needs to be able to create the S3 bucket if it does not exist to initialize the state. Glad you got it resolved and will be very happy to review a PR that improves the docs! 🍻

**Comment by kromol** [comment]
In this case bucket exists, so probably `s3:GetBucketVersioning` was missing

**Comment by christophetd** [comment]
I can confirm that migrating from Terraform to Terragrunt, I had to add the following permissions:
- `s3:GetBucketVersioning` on the S3 bucket holding the state
- `dynamodb:DescribeTable` on the DynaboDB table for locking

**Comment by AlexanderWiechert** [comment]
I also have isues with the remote_state S3 Bucket. The bucket was already created via terragrunt. I had to swtich now from a setup with Profiles to use role_arn instead and I run into the same issue with finding the credentials

```
terragrunt init
ERRO[0005] Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
