### ISSUE TITLE
AWS_SHARED_CREDENTIALS_FILE environment variable does not seem to be read

### ISSUE THREAD

**Issue by mechastorm** [gruntwork-io/terragrunt#92]
Similar to #85 

Terragrunt Version: v0.7.3
OS: Ubuntu 14.04 LTS
Terraform Version: 0.8.2

Repro:
- set up a custom AWS credentials file with multiple account access keys ad secrets
- set the path to file into the global environment AWS_SHARED_CREDENTIALS_FILE 
- run terraform plan
- run terragrunt plan

Result
- Terraform runs as expected
- Terragrunt gives a credential error. Example output
```
terragrunt plan -var-file=/my_path/env.tfvars -out=/my_path/env.tfplan --terragrunt-config /my_path/env.terragrunt
[terragrunt] 2017/01/03 22:43:02 Reading Terragrunt config file at /my_path/env.terragrunt
[terragrunt] 2017/01/03 22:43:02 Initializing remote state for the s3 backend
[terragrunt] 2017/01/03 22:43:07 Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

The official AWS GO support the global AWS_SHARED_CREDENTIALS_FILE  -  https://github.com/aws/aws-sdk-go/blob/b2dc98bb584e48b0f5f39c93110633173c5da43c/aws/credentials/shared_credentials_provider.go#L30

So in theory terragrunt should just be able to read it but I am not sure what could be messing with it. Any ideas?

**Comment by mechastorm** [comment]
Ok I found a possible cause of this issue.

It looks like we are using an older version of the AWS GO SDK

On the [glide.lock on master](https://github.com/gruntwork-io/terragrunt/blob/master/glide.lock), the version it points to is https://github.com/aws/aws-sdk-go/commit/665c623d7f3e0ee276596b006655ba4dbe0565b0 (May 29)

AWS_SHARED_CREDENTIALS_FILE env support was introduced to the SDK on Aug 11 (https://github.com/aws/aws-sdk-go/commit/33201594b4a9739b28d96517dad34a47bc741910)

As such I think the fix for this is to rebuild terrragrunt with the latest AWS GO SDK - bumping it from 1.4.14 to the latest v1.6.9 (https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md).

I am still a newbie at Go, so will take awhile for me to try to get this running but if someone can do the version bump and test, please go ahead.

**Comment by brikis98** [comment]
Ah, nice find. To update to the latest version (you'll have to install [glide](https://github.com/Masterminds/glide)), you should be able to just run: 

```
glide up --all-dependencies
``` 

You can then build a new binary locally by running (you'll have to install [gox](https://github.com/mitchellh/gox)): 

```
gox -os windows -arch amd64 -output my-terragrunt-binary -ldflags "-X main.VERSION=testing-version"
```

If `my-terragrunt-binary` works correctly, submit a PR!
