### ISSUE TITLE
Is there a way to explicitly disable in terragrunt.hcl?

### ISSUE THREAD

**Issue by hehnope** [gruntwork-io/terragrunt#920]
I have `terragrunt.hcl` resource that I don't want to delete from my directory structure. But, some members regularly apply `apply-all`; which means this will get applied; is there a way to explicitly disable it?

**Comment by yorinasub17** [comment]
You can use the `skip` flag: https://github.com/gruntwork-io/terragrunt#skip

**Comment by hehnope** [comment]
Thanks! I searched but was looking for `disable`, so missed it.
