### ISSUE TITLE
[question] Would you like Terragrunt to create it? (y/n) 

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#921]
so when run the plan/apply on cicd pipeline to a new aws account, it asks below question. 

>Remote state S3 bucket 123456789012-terraform-state does not exist or you don't have permissions to access it. Would you like Terragrunt to create it? (y/n) 

I can't find an option to forcely create it. Is this option in `init` I should use?

```
  -force-copy          Suppress prompts about copying state data. This is
                       equivalent to providing a "yes" to all confirmation
                       prompts.
```
The option name `-force-copy` is little bit misleading to me. 

I also saw some [discussion](https://github.com/gruntwork-io/terragrunt/issues/788) about with below codes

```
terraform {
  extra_arguments "init" {
    commands = [
      "init",
    ]

    arguments = [
      "-force-copy",
      "-backend=true",
    ]
  }
```

Will it work for this purpose or not?

**Comment by yorinasub17** [comment]
You can pass in the command line argument `--terragrunt-non-interactive`. This is actually a terragrunt feature of automatically creating the remote state bucket if it doesn't exist, so it isn't a terraform CLI arg. See [the relevant section in the README for more details](https://github.com/gruntwork-io/terragrunt#create-remote-state-and-locking-resources-automatically).

**Comment by pavelpulec** [comment]
The option `--terragrunt-non-interactive` is dangerous because it automatically answers "yes". Is there an option to answer "no" by default?
