### ISSUE TITLE
Go modules

### ISSUE THREAD

**Issue by chenrui333** [gruntwork-io/terragrunt#925]
While I was trying to help upgrade terrafrom to v0.12.12, I have found the module dependency has been changed to use `Subpackage github.com/hashicorp/hcl/v2`.

Based on the [Version-Selection doc](https://github.com/hashicorp/hcl/wiki/Version-Selection), to be able to use hcl/v2, it requires to do the go modules upgrade.

Furthermore, with go v1.14, go modules would be the default toolchain, so I think it would be nice that we can upgrade the build toolchain to use go modules. 

Kind of relates to https://github.com/Homebrew/homebrew-core/pull/45521

**Comment by brikis98** [comment]
This is on our roadmap, but I'm not sure if we'll be able to get to it soon. In the meantime, a PR to switch to Go modules is very welcome!

**Comment by brikis98** [comment]
Done in #1105
