### ISSUE TITLE
Cognito user pool schema question

### ISSUE THREAD

**Issue by rfasouliotis** [gruntwork-io/terragrunt#947]
Hello,

I've been working on implementing Cognito User Pools using Terragrunt, and I am encountering an interesting thing that I hadn't seen before in Terraform code.

Specifically, the schema containers that can be added as part of the pool. The resource looks something like this:

```terraform
resource "aws_cognito_user_pool" "pool" {
  count = "${var.cognito_num_user_pools}"

  name = "${lookup(var.cognito_user_pools[count.index], "user_pool_name_app")}"

  # Password policy
  password_policy = [{
    require_uppercase                = "${lookup(var.cognito_user_pools[count.index], "password_require_uppercase")}"
    require_lowercase                = "${lookup(var.cognito_user_pools[count.index], "password_require_lowercase")}"
    require_numbers                  = "${lookup(var.cognito_user_pools[count.index], "password_require_numbers")}"
    require_symbols                  = "${lookup(var.cognito_user_pools[count.index], "password_require_symbols")}"
    minimum_length                   = "${lookup(var.cognito_user_pools[count.index], "password_minimum_length")}"
  }]

  # I am hardcoding these for now. Not sure how to do this 
  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = false
    name                     = "name"
    required                 = true

    string_attribute_constraints {
      min_length = 2
      max_length = 25
    }
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = false
    name                     = "family_name"
    required                 = true

    string_attribute_constraints {
      min_length = 2
      max_length = 25
    }
  }
}
```

As you can see, the resource allows for multiple "schema" entries (up to 50 of them) to be defined. Is there any way to do this dynamically using Terragrunt since the number of "schema" entries may be different depending on the environment?

**Comment by mcalhoun** [comment]
This actually isn't a terragrunt question, but rather a terraform question. The tl;dr is that if you're using terraform 0.12+, then you can use the new `dynamic` keyword (https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/), otherwise, there wasn't really a great way to handle this prior to terraform 0.12.

**Comment by rfasouliotis** [comment]
Thanks @mcalhoun. I opened it here because it was a question in terms of interpolation. I figured there wasn't a simple way to do it in 0.11 but I figured I would ask anyway in case I missed something in the documentation. I haven't gone down the 0.12 path yet, but should be soon. Thanks for the reply and the keyword tip.
