### ISSUE TITLE
Allow Skipping All Initialization of a Dependency's Dependencies

### ISSUE THREAD

**Issue by jason-huling** [gruntwork-io/terragrunt#949]
I was wondering if it is possible to prevent a dependency's dependencies from being initialized?

When I have been utilizing dependencies I only typically care about the output of the dependency that I am calling directly, so I am not sure what value initializing the dependency's dependencies brings? Since their state files are separated, it seems as though it is unneeded and only the state file of the dependency I am calling needs to be accessed and initialized.

For example, right now I am setting up a Shared VPC in GCP between a host project and three service projects, so I have something like this:

```
# Host project
dependency "vpc-host" {
  config_path = "../../projects/vpc-host"
}

# Service projects
dependency "service-project-1" {
  config_path = "../../projects/service-project-1"
}
dependency "service-project-2" {
  config_path = "../../projects/service-project-2"
}
dependency "service-project-3" {
  config_path = "../../projects/service-project-3"
}

# Additional dependency
dependency "foo" {
  config_path = "../../foo"
}
```
Each of these projects have a folder dependency though, since they are organized by lifecycle/environment, and those lifecycle folders have a dependency on our top level department folder. There are also one other dependency (foo) which itself also has its own dependency.

Terragrunt is doing a great job of deduplicating the dependencies, the projects are all within the same folders which are only initialized once, but it still seems like a lot of overhead to initialize the remote state for these.

Right now terragrunt is initializing 8 remote state dependencies (4 projects, 2 folders, foo, foo's dependency)  when it could just be initializing 5 (4 projects, foo).

**Comment by yorinasub17** [comment]
There might be a way to do this, where terragrunt only initializes the module source but not the module itself with a `terraform init` call. This assumes `terraform output` works without init though.

We are a bit burried with other priorities at the moment so we are unlikely to get to this anytime soon. If anyone from the community wants to attempt this in the meantime, that will be greatly appreciated!

**Comment by jason-huling** [comment]
Thanks for the response @yorinasub17. I'm not familiar enough with `terraform output` to know if that would be the case, but I wonder if for dependencies if [`terraform state show`](https://www.terraform.io/docs/commands/state/show.html) could be used to access these values without requiring initialization?

Or is this a way for `dependency` to either act more like [`terraform_remote_state`](https://www.terraform.io/docs/providers/terraform/d/remote_state.html), or is it possible to utilize `data` outputs in terragrunt's `hcl` inputs as a workaround?

**Comment by yorinasub17** [comment]
The goal of `dependency` is to have a well documented way of extracting outputs from a module to use as inputs to another module. Being able to access any state data would be nice, but the format isn't well documented and it isn't easy to parse (see https://www.terraform.io/docs/internals/json-format.html). On the other hand, the output of `terraform output` is fairly easy to understand and is not prone to a lot of complexity.
