### ISSUE TITLE
[new feature] any chances to get all outputs inherited from modules directly?

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#953]
when deploy via terragrunt with many modules, I need write seperate module to handle all outputs. that's not convenience. 

Will it be good feature to export the outputs directly from modules? 

For example, in a module, there is output from that module

```
module.ecs.this_name
```
So currently I have to add below codes to get that output as `module.ecs.this_name`

```
output "module.<module_name>.<same_output_name>" {
  value = module.<module_name>.<same_output_name>
}
```

1. Are there any easy ways to export all outputs from reference modules?
2. different modules have multiple outputs, how to easily export all of them after terragrunt deployment?

**Comment by brikis98** [comment]
I think this is by design in Terraform: they want you to be explicit with all inputs and outputs. That does mean it's more verbose, but less "magic" makes the behavior more predictable.

**Comment by ozbillwang** [comment]
I am fine with this feature now. I will work it with `dependency`. But I found a bug in it.

https://github.com/gruntwork-io/terragrunt/issues/955
