### ISSUE TITLE
[bug] terragrunt import aws_cloudwatch_log_subscription_filter.xxx need be escaped 

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#954]
got this bug when try to import resource `aws_cloudwatch_log_subscription_filter`

I have to excaped the pipe `|` as below
```
terragrunt import aws_cloudwatch_log_subscription_filter.subscription_filter application_logs\|subscription_filter
```
Otherwise, I got no action (no error, no resource imported)

From the output, you would see the filter after pipe is missed. 

>terragrunt import aws_cloudwatch_log_subscription_filter.subscription_filter application_logs|subscription_filter

>[terragrunt] 2019/11/20 06:45:43 Running command: terraform import aws_cloudwatch_log_subscription_filter.subscription_filter application_logs

**Comment by brikis98** [comment]
What is the pipe for?

**Comment by ozbillwang** [comment]
@brikis98 

it is asked by import

https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_subscription_filter.html#import

**Comment by brikis98** [comment]
Oh, gotcha, didn't know about that!

Note that the pipe character has special meaning on the shell! So if you run:

```
terragrunt import aws_cloudwatch_log_subscription_filter.subscription_filter application_logs|subscription_filter
```

It is seen as "pipe the output of `terragrunt import aws_cloudwatch_log_subscription_filter.subscription_filter application_logs` as the input of `subscription_filter`. 

Therefore, escaping it or wrapping the `aws_cloudwatch_log_subscription_filter.subscription_filter application_logs|subscription_filter` part in quotes is necessary. I don't think that's Terragrunt specific.

**Comment by ozbillwang** [comment]
thanks, looks fine for me
