### ISSUE TITLE
[bug] output doesn't work with dependency 

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#955]
I have folders as below
```
$ tree 
.
├── application_logs
│   ├── backend.tf
│   └── terragrunt.hcl
├── ecs
│   ├── backend.tf
│   └── terragrunt.hcl
```
`application_logs` had beed `terragrunt apply` successfully several days before, no change after applied

I need reference the output with below codes in `ecs`

```
dependency "application_logs" {
  config_path = "../application_logs"
}

inputs = {
    log_group_name                = dependency.application_logs.outputs.log_group_name
}
```

But when run terragrunt plan or apply in `ecs` in a new `alpine/terragrunt:0.12.15` container in cicd pipeline, I got this error

```
[terragrunt] 2019/11/20 07:06:28 Running command: terraform output
The state file either has no outputs defined, or all the defined
outputs are empty. Please define an output in your configuration
with the `output` keyword and run `terraform refresh` for it to
become available. If you are using interpolation, please verify
the interpolated value is not empty. You can use the 
`terraform console` command to assist.
[terragrunt] 2019/11/20 07:06:31 Hit multiple errors:
exit status 1
```

Then I have to go back the folder `application_logs` and run `terragrunt apply`, see the output without any changes.

Then I can run `terragrunt apply` in `ecs`, then everything works.

**Comment by Fabianoshz** [comment]
So, you're trying to get an output of a state that hasn't run yet? If that's the case, of course you're not going to get the output. Take a look at the Readme, as far as i know this is a expected behaviour using Terraform.

You might accomplish what you want by using the apply-all command.

**Comment by ozbillwang** [comment]
@Fabianoshz 

my updates.

The module “application_logs” had been applied.

when run in the other which need reference its dependency, i saw the error

**Comment by yorinasub17** [comment]
Do you have remote state configured, or are you relying on local state (the default)?

**Comment by ozbillwang** [comment]
I used s3 as backend for tfstate files

**Comment by yorinasub17** [comment]
Can you share the following (sanitizing anything sensitive):

- Version of terragrunt
- Version of terraform, specifically in your local environment
- The contents of `backend.tf` for each folder

**Comment by yorinasub17** [comment]
Closing as stale. If this is still an issue, please open a new ticket with the requested information above. Thanks!
