### ISSUE TITLE
[feature] Will it be good idea to manage multiple modules in one terragrunt.hcl

### ISSUE THREAD

**Issue by ozbillwang** [gruntwork-io/terragrunt#957]
So terragrunt is a wrapper on terraform, but it managed modules individually. One `terragrunt.hcl` can manage one module only, which is not convenience at all. 

Will it be good idea to make another wrapper on terragrunt to manage multiple modules, such as
```
terragrunt "module_1"  {
  source = "<git_module_1_path>"

  include {
    path = find_in_parent_folders()
  }

  inputs = {
    name = "module_1"
  }
}

terragrunt "module_2"  {
  source = "<git_module_2_path>"

  dependency "module_1" {
    config_path = "."
  }
  include {
    path = find_in_parent_folders()
  }

  inputs = {
    name = "module_2"
  }
}
```

**Comment by brikis98** [comment]
I suggested something very similar in https://github.com/gruntwork-io/terragrunt/issues/759, so please continue the discussion there.

**Comment by leiarenee** [comment]
Multiples module support in Terragrunt is a must and should be done immediately. Lets get our hands dirty and do it.
