### ISSUE TITLE
Difference between terrafrom code in ‘.tfvars’ file vs ‘.hcl’ file

### ISSUE THREAD

**Issue by sanooprajps** [gruntwork-io/terragrunt#962]
Good day all.
I am a newbie in Terragrunt and pardon me for asking such a basic question.
I am wondering what is the difference of putting terragrunt code in ‘.tfvars’ file under 'terragrunt block and inside ‘.hcl’ file. Is it mandatory to use ‘.hcl’ file in latest version or something?!

I don't see terragrunt latest version is reading '.tfvars' files having terragrunt code in it, instead it is expecting to have a '.hcl' file!

**Comment by brikis98** [comment]
Yes, use `terragrunt.hcl` for the latest version of Terragrunt.

**Comment by sanooprajps** [comment]
Please find the reason behind it.
Before version 0.19.0, Terragrunt had you define its configuration in a terragrunt = { ... } variable in a terraform.tfvars file, but due to item (1) this no longer works with Terraform 0.12 and newer. That means we had to move to a new file format. This requires a migration, which is unfortunate, but as a nice benefit, item (2) gives us a nicer syntax and new functionality!
