### ISSUE TITLE
Easy way to switch between terragrunt versions

### ISSUE THREAD

**Issue by w32-blaster** [gruntwork-io/terragrunt#963]
Hi,

We are migrating our modules to the new terraform 0.12 version syntax, but because of the size of our code base to upgrade, we need a solution to switch between version numbers in case if we have to make changes on the old format before migrating to tf 0.12. 
For this we started to use tfenv which works great. Do we have something similar for terragrunt, or is there an easy way to switch between terragrunt versions?

**Comment by ekini** [comment]
There is a way.
You can the terraform 0.11 binary to something like `terraform-v11` and then use this in the parent`terragrunt.hcl` https://github.com/gruntwork-io/terragrunt#terraform_binary:
```
terraform_binary = "terraform-v11"
terraform_version_constraint = ">= 0.11"
```
And if a module is using the new code for terraform 0.12 you just set in in the terragrunt module `terragrunt.hcl`:
```
terraform_binary = "terraform"
```
Eventually `terraform_binary` will become redundant (as all of the code will have been converted to 0.12 syntax)

**Comment by autero1** [comment]
No, we don't have a utility like `tfenv` for `terragrunt`. I personally have set up `terragrunt11` for `terragrunt` versions < v0.19.0 and `terragrunt` for versions >=v0.19.0. Worked well for me during our module upgrade.

**Comment by brikis98** [comment]
There is https://github.com/cunymatthieu/tgenv

**Comment by ozbillwang** [comment]
Make sure you have `version.tf` in your repo

```
$ cat versions.tf

terraform {
  required_version = ">= 0.12"
}
```

then run terraform/terragrunt command in container, especially with CICD pipeline, so you can fix the terraform and terragrunt version with your expect.

**Comment by w32-blaster** [comment]
Thanks for the tgenv @brikis98 , it works well on local development.
