### ISSUE TITLE
[Question] How to interpolate parent outputs and child variables in remote_backend?

### ISSUE THREAD

**Issue by feliperfmarques** [gruntwork-io/terragrunt#964]
Hey guys,

I have following structure:

└── gcp(Cloud)
    ├── main.tf (create projects)
    ├── terragrunt.hcl
    **├── management(Environment)**
    │   ├── environment.yaml
    **│   └── us-central1(Region)**
    │       ├── cloud-dns
    │       ├── kubernetes-engine
    │       └── region.yaml
    **├── pre-production(Environment)**
    │   ├── environment.yaml
    **│   └── us-central1(Region)**
    │       ├── cloud-dns
    │       ├── kubernetes-engine
    │       └── region.yaml
    **├── production(Environment)**
   │   ├── environment.yaml
    **│   └── us-central1(Region)**
    │       ├── cloud-dns
    │       ├── kubernetes-engine
    │       └── region.yaml

In `main.tf` I have created projects(google resource) for each environment (Production, Pre-Production, Management), generating project_id outputs for each one. In terragrunt.hcl(parent) I have configured a GCS backend. But, I would like to create one state into each region, for this reason I put the files region.yaml and environment.yaml in the root at each corresponding level, defining a string(name) of each region and environment. My question is:

1 - How to interpolate outputs created in main.tf(parent level) for define project parameter in remote backend params? Where I should save root main.tf state?

2 -  How to interpolate region.yaml and environment.yaml for define location and bucket in remote backend params?

terragrunt.hcl (parent):
```
# Configure Terragrunt to automatically store tfstate files in an GCS bucket
remote_state {
  backend = "gcs"
  config = {
    # location = "${var.region.name}" ?? How to setup this?
    # project  = "all-timing-${outputs.project_id}" ?? How to setup this?
    # bucket   = "all-timing-${var.environment.name}-terraform-state" ?? How to setup this?
    prefix   = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```

terragrunt.hcl (child):
```
 dependency "project" {
  #dependency of main.tf
  config_path = "../../../"

  mock_outputs = {
    project_id = "temporary-dummy-id"
  }

  mock_outputs_allowed_terraform_commands = ["plan", "validate"]
}

inputs = {
  project_id = "${dependency.all_timing_management_project.outputs.project_id}"
}
```

3 - Does anyone have any other suggestions, please?

**Comment by yorinasub17** [comment]
> How to interpolate outputs created in main.tf(parent level) for define project parameter in remote backend params? Where I should save root main.tf state?

I would suggest using `terragrunt` to manage that, and define an `admin` project for storing the state files. Then, you can use `dependency` blocks to read those outputs.

> 2 - How to interpolate region.yaml and environment.yaml for define location and bucket in remote backend params?

You can do this using `yamldecode` and `file` in `locals` (or directly in `terraform` block).

---

So in the end, something like the following should address your use case:

```
locals {
  region = yamldecode(file("region.yaml"))
  environment = yamldecode(file("environment.yaml"))
}

dependency "project_factory" {
  config_path = "../../admin/my-project"
}

remote_state {
  backend = "gcs"
  config = {
    location = "${local.region.name}"
    project  = "all-timing-${dependency.project_factory.outputs.project_id}"
    bucket   = "all-timing-${local.environment.name}-terraform-state"
    prefix   = "${path_relative_to_include()}/terraform.tfstate"
  }
}
```
