### ISSUE TITLE
Use of profile in terraform provider ignored when using iam_role

### ISSUE THREAD

**Issue by houdinisparks** [gruntwork-io/terragrunt#966]
Hi,

When I am configuring my parent terragrunt.hcl file with the below

```hcl
iam_role                     = "arn:aws:iam::xxxxxxxxxxxx:role/iam-role-bgp-stgdzna-bamboo"
```

terraform is unable to set the profile for another provider that I am using:

```hcl
provider "aws" {
  alias = "mgmt"

  region = "ap-southeast-1"
  endpoints {
    sts = "https://sts.ap-southeast-1.amazonaws.com"
  }
  profile = "MGMT"
}
```

It is still using assumed `iam_role` creds for resources with `provider = aws.mgmt` block.

```hcl
# the below is not using the profile creds
data "aws_subnet_ids" "devops" {
  provider = aws.mgmt
  vpc_id   = var.mgmt_vpc_id

  filter {
    name   = "tag:Zone"
    values = ["dz"]
  }

  filter {
    name   = "tag:Environment"
    values = [var.environment]
  }
}

```

Any help?

**Comment by brikis98** [comment]
From the [iam_role docs](https://github.com/gruntwork-io/terragrunt#configuring-terragrunt-to-assume-an-iam-role): 

> Terragrunt will call the sts assume-role API on your behalf and expose the credentials it gets back as environment variables when running Terraform.

From the [AWS provider docs](https://www.terraform.io/docs/providers/aws/index.html#authentication) (emphasis mine):

> The AWS provider offers a flexible means of providing credentials for authentication. The following methods are supported, **in this order**, and explained below:
>
> * Static credentials
> * Environment variables
> * Shared credentials file
> * EC2 Role

So from what I'm seeing, if you set environment variables—which Terragrunt does when you specify an `iam_role`—then shared credentials file auth (including `profile`) will be ignored.

**Comment by houdinisparks** [comment]
Ah.. I see. Okay thanks!
