### ISSUE TITLE
[Question] - Referencing inputs in child terragrunt.hcl

### ISSUE THREAD

**Issue by johanssone** [gruntwork-io/terragrunt#967]
Hi, I have a question I can't really wrap my head around

I have the following structure for a set of openstack resources:
```
../
|-- empty.yaml
|-- region-mon
|   |-- region01
|   |   |-- network-wiring
|   |   |   |-- internal
|   |   |   |   |-- net
|   |   |       |   `-- terragrunt.hcl
|   |   |   |   `-- secgroup
|   |   |       |   `-- terragrunt.hcl
|   |   |   `-- mgmt
|   |   |       |-- net
|   |   |       |   `-- terragrunt.hcl
|   |   |       `-- secgroup
|   |   |       |   `-- terragrunt.hcl
|   |   `-- region.yaml
`-- terragrunt.hcl
```

In my root `terragrunt.hcl` I have some common config for backend etc but also reference common vars for region, somewhat following [this](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/blob/019e351dbe0689e57a9e8448db84e1a79d1e8ee3/non-prod/terragrunt.hcl#L41):
```
...
inputs = merge(
  yamldecode(
    file("${get_terragrunt_dir()}/${find_in_parent_folders("region.yaml")}"),
  ),
)
...
```

In region.yaml I have a couple of variables that will be sent in as input to child terragrunt.hcl files:
```
---
openstack_cloud: region01
external_network_name: xx
dns_nameservers: [xxx, yyy]
```

Question is if it's possible in a good way to reference the variables set in region.yaml i child terragrunt.hcl files.

Scenario:
In one of the terragrunt.hcl files under region01 directory, I have a input called name, but I want to prefix that name with `openstack_cloud` and potentially accessing other values as well, without the need to put that logic in the module(s) themselfs

Child terragrunt.hcl:
```
include {
  path = find_in_parent_folders()
}

terraform {
  source = "../../../../modules/os-network"
}

inputs = {
 #  Psuedo code for what I'm trying to achieve
  name = join(region_var.openstack_cloud, "mgmt-net")
}
```

I've tried play around with `locals` to no avail:
```
locals {
   name1 = join(get_env("TF_VAR_openstack_cloud "default"), "mgmt-net")
   name2 = join(var.name, "mgmt-net")
}

inputs = {
 
  name = local.name1
  name = local.name2
}
```

I'm I planning up repo structure completely wrong, trying to share variables? (in this case based in region or geographic location)

**Comment by johanssone** [comment]
I just realized that putting this particular logic inside the modules makes more sense... 

The questions still remains though, is there a way to reference parent inputs in child terragrunt.hcl files?

**Comment by yorinasub17** [comment]
Not currently, but this is an active feature request. See the conversation on globals (https://github.com/gruntwork-io/terragrunt/issues/814) and the related PR (https://github.com/gruntwork-io/terragrunt/pull/858) for the latest.

**Comment by yorinasub17** [comment]
Closing as duplicate.
