### ISSUE TITLE
Ability to run terragrunt programmatically

### ISSUE THREAD

**Issue by rvodden** [gruntwork-io/terragrunt#968]
It would be really helpful to be able to run terragrunt programmatically (i.e. link terragrunt into another go executable). Unfortunately, this is made quite difficult by `runTerragrunt` in `cli_app.go` not being exported. Could we discuss the possibility of exporting it? I'd be happy to raise a PR if we felt it was a suitable direction. Naturally, if there's another/better way of achieving what I'm trying to do I'd be very open to opinions.

**Comment by brikis98** [comment]
Exporting it sounds fine. Out of curiosity, what is your use case?

**Comment by rvodden** [comment]
We're writing a linter that checks that various opinions we have about how terragrunt/terraform should be run are implemented correctly. We're very much of the opinion that we shouldn't write a coding standard (which will sit on a shelf) but we should write a linter (which will be part of our CI chain). Like many organizations, we have a hierarchy of modules and therefore only a subset of these modules should be specified as a source in a `terragrunt.hcl`. So one of the steps in our linter uses `github.com/gruntwork-io/terragrunt/config/ParseConfigFile` to read `terragrunt.hcl`. This works really well until `terragrunt.hcl` has a `dependency` block which doesn't have skip output set, at which point it fails because `RunTerragrunt` isn't defined in the TerragruntOptions struct.

Naturally, this is only the first of many reasons it would be cool to be able to parse `terragrunt.hcl` programmatically, so whilst we might be able to tell it to not bother getting the outputs from the other module initially, I'm sure there will be reasons we'd like to do it.

Thanks for the super quick reply, and expect PR very soon!

**Comment by brikis98** [comment]
Sounds intriguing! Is this a linter you'll be open sourcing by any chance?

Thx for the PR!

**Comment by rvodden** [comment]
Open-sourcing is very much the plan. At the moment the rules are a bit mixed up with the code. I need to think of a good rules struct then do a bit of refactoring. I definitely want to do that before we get much further though, or it will become a pig of a refactor.
