### ISSUE TITLE
Create multiple public subnet groups using Terrafrom

### ISSUE THREAD

**Issue by sanooprajps** [gruntwork-io/terragrunt#973]
Good day all!
We are trying to achieve the following requirement using Terraform.

We need to have multiple public subnets with different Tag names across three AZs as below.
What is the best way to achieve this using terraform modules. 

AZ1				AZ2				AZ3
---				---				---
subnet_public_group1_1a		subnet_public_group1_1b		subnet_public_group1_1c
subnet_public_group2_1a		subnet_public_group2_1b		subnet_public_group2_1c
subnet_public_group3_1a		subnet_public_group3_1b		subnet_public_group3_1c

We currently have an approach of using separate resources defined for each subnet groups(subnet_public_group1, subnet_public_group2, subnet_public_group3) in Terraform modules.

Is there a better way to achieve this using the existing terraform modules(aws_subnet resource for public network)?

Also, we are going to associate single route table to all these subnets created above.

Any help is appreciated.

**Comment by yorinasub17** [comment]
See response in https://community.gruntwork.io/t/create-multiple-public-subnet-groups-using-terrafrom/370/2.

Will close this as it does not have to do with terragrunt.

**Comment by sanooprajps** [comment]
Thank you!
