### ISSUE TITLE
get_terraform_commands_that_need_vars function falsely returns "validate" as one of the commands

### ISSUE THREAD

**Issue by ryno75** [gruntwork-io/terragrunt#974]
When using the `get_terraform_commands_that_need_vars()` function to specify a var file it will throw a warning/error during a `terragrunt validate` run.

Example config:
```hcl
terraform {
  extra_arguments "shared_vars" {
    commands           = get_terraform_commands_that_need_vars()
    optional_var_files = ["shared.tfvars"]
  }
```

While running a `terragrunt validate` I receive the warning from `terraform`:
```
Warning: The -var and -var-file flags are not used in validate. Setting them has no effect.
```

Obviously `validate` should not be included in the `get_terraform_commands_that_need_vars()` output list now as the use of `-var` and `-var-file` is not supported by `terraform validate`.

I confirmed `get_terraform_commands_that_need_vars()` indeed returns`validate` in the list:
https://github.com/gruntwork-io/terragrunt/blob/v0.21.8/config/config_helpers.go#L42

That line should be removed.

**Comment by yorinasub17** [comment]
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.21.9
