### ISSUE TITLE
Can you please change the Release tag for 0.21.10?

### ISSUE THREAD

**Issue by cryptomatt** [gruntwork-io/terragrunt#981]
Am using an ansible role to download terragrunt and install it. when it encounters 
"https://github.com/gruntwork-io/terragrunt/releases/download/v0.21.10: Grant root account access to remote state bucket/terragrunt_linux_amd64"

it gets an error. Please change the release title to meet the standard v0.21.10

**Comment by brikis98** [comment]
Done!
