### ISSUE TITLE
`terragrunt apply <dir>` and `terragrunt apply-all` are not interchangeable

### ISSUE THREAD

**Issue by zachwhaley** [gruntwork-io/terragrunt#984]
I've just started using terragrunt and something I thought would work does not.

I have two terraform modules with terragrunt configs like so:
```
./
├── terragrunt.hcl
├── one/
│   ├── main.tf
│   ├── outputs.tf
│   ├── terragrunt.hcl
│   └── variables.tf
├── two/
│   ├── main.tf
│   ├── outputs.tf
│   ├── terragrunt.hcl
│   └── variables.tf
```
I've setup my backend config as described here https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#keep-your-backend-configuration-dry

Then I went to run `terragrunt apply-all` and module one failed due to my own mistakes, so I went and fixed things and then ran `terragrunt apply one/` thinking I could check if my mistake was corrected and then continue with `apply-all` afterwards, but apparently this is not true and terragrunt proceeded to make a new remote state without the directory prefix which resulted in duplicate resources being created and a lot of confusion for me.

My expectation was that with terragrunt I would be able to run `apply-all` and `apply <dir>` interchangeably, one applying all modules while the other applying just one module but both would use the same remote config.

Don't know if this is a bug or just a misunderstanding, but just wanted to let y'all know this was a big mental disconnect for me.

Thanks for the great tool!

**Comment by yorinasub17** [comment]
Terragrunt arguments are all prefixed with `--terragrunt` (See [cli options docs](https://terragrunt.gruntwork.io/docs/getting-started/cli-options/)). All positional args are forwarded directly to Terraform. This means that `terragrunt apply <dir>` is really just running `terragrunt apply` in the current directory (wherever that is) and forwarding `<dir>` directly to `terraform apply` without doing any kind of special processing within terragrunt itself.

What you want is accomplished with the `--terragrunt-working-dir` arg:

```
terragurnt apply --terragrunt-working-dir <dir>
```
