### ISSUE TITLE
Documentation or Parser error with get_terraform_commands_that_need_vars

### ISSUE THREAD

**Issue by Houlistonm** [gruntwork-io/terragrunt#987]
The following block of code was copied from [here](https://terragrunt.gruntwork.io/docs/features/built-in-functions/#get_terraform_commands_that_need_vars)

This code works using terragrunt version v0.21.10

```hcl
terraform {
  extra_arguments "common_var" {
    commands  = get_terraform_commands_that_need_vars()
    arguments = ["-var-file=${get_aws_account_id()}.tfvars"]
  }
}
```

When I use any CLI tool that uses the hashicorp HCL parsing library such as:
[json2hcl](https://github.com/kvz/json2hcl) or [yj](https://github.com/sclevine/yj)  (I rebuilt both locally using the latest version of the HCL parser)
I get the following error.
```
Unable to parse HCL: At 12:16: Unknown token: 12:16 IDENT get_terraform_commands_that_need_vars
```
Where 12:16 is the line:col of my file.

I was able to make both terragrunt and the HCL parsing library function with the following modification.
```hcl
terraform {
  extra_arguments "common_var" {
    commands  = "${get_terraform_commands_that_need_vars()}"
    arguments = ["-var-file=${get_aws_account_id()}.tfvars"]
  }
}
```

Shouldn't interpretation functions be quoted this way (or just strings that require interpretation) ?

**Comment by yorinasub17** [comment]
`json2hcl` and `yj` are HCL1 tools. Terragrunt uses HCL2. That is why you are getting the syntax errors.

Your best bet is to wait for an alternative version of those tools that support HCL2.

Relevant links:

- https://github.com/kvz/json2hcl/issues/12
- https://github.com/sclevine/yj/blob/master/go.mod#L7 (note that this links with v1 of HCL. HCL2 parser lives in another module path. See [version selection guide](https://github.com/hashicorp/hcl/wiki/Version-Selection))
