### ISSUE TITLE
migrating flat terraform.state to nested terragrunt DRY state

### ISSUE THREAD

**Issue by jeffdyke** [gruntwork-io/terragrunt#988]
I had started with a relatively flat structure and imported all my existing resources using `terraform import foo foo-name` or similar.  When creating and changing that structure i noticed i could modify the state manually to reflect the directory structure.  I'm trying to avoid re-importing everything, 

Old Structure
```
- staging
 - dynamodb
   - main.tf
   - tables.tf
   - outputs.tf
   ...ext
  main.tf (which pointed at modules at child directories)
```
New -
```
 - staging
   - terraform.hcl (actual backend configuration and some inputs)
   - dynamodb
     - terraform.hcl (containing `include block with path`)
     - main.tf (provider and empty backend)
     - tables.tf (all terraform imported tables)
     - outputs.tf  
```

Is there a way to modify the state file and reconfigure so it matches with what is in the bottom block, so i can run `terragrunt plan` in `staging/dynamodb` and it will not want to create new tables?

Thanks.  I have seen similar questions, but all involve an answer like import again...which i'm trying desperately to avoid.  Especially when it comes to account level, rather than environment level resources. 

Thanks for any pointers.  I'll re-import if required, but wanted to ask before i do.

**Comment by jeffdyke** [comment]
since this will automagically write to `staging/{path}/terraform.tfstate`...it would seem I would need to perform some operating type deconstruction of `/staging/terraform.tfstate`  or import them in the directories.

**Comment by jeffdyke** [comment]
I'm going to close this as i think i have found my own answer.

**Comment by mattayes** [comment]
@jeffdyke Could you share your answer?

**Comment by jeffdyke** [comment]
sure.  Many people don't like my answer b/c it involves modifying the state, which IMHO is not different than modifying a database when you are fully aware of the schema.

first i made a module for all `aws_instance` creation and the key is simply `server`, then in the individual directories like `webservers` i create an `inputs` block to define how the server should be created and in the module create them with `for_each = var.servers`

now that i have the directories separate i add the servers providing an index name
`terragrunt import 'aws_instance.server["devweb01"]' instanceId`

This creates a server block with an `index_name` of `devweb01`.  Now i can go the original directory where devweb01 was defined like `resource "aws_instance" "devweb01"` and remove it.
The smarter way to remove it is `terragrunt state list | grep aws_instance.devweb01 | xargs terragrunt state rm`

The other thing that i have done is pull down the state file
`aws s3://terraform-bucket/env/dir/terraform.tfstate .`
vim terraform.tfstate
change the main index from "devweb01" to "server" and inside instances add the pair of  `"index_key": "devweb01"` inside the resources block so it looks like
```
...other config
"resources": [
    {
      "mode": "managed",
      "type": "aws_instance",
      "name": "server",
      "each": "map",
      "provider": "provider.aws",
      "instances": [
        {
          "index_key": "devweb01",
...more config
```
and then run `terragrunt state push terraform.tfstate`  

I normally do the latter if i'm in a directory with lots of changes and all i need is the generic key `servers` and setting the `index_key` appropriately.

This is not the simplest thing to explain how i went about it i guess, so YMMV, always run a plan.  

Hope this helps!
