### ISSUE TITLE
Warning: Missing terraform backend block instead of an error.

### ISSUE THREAD

**Issue by Divya1388** [gruntwork-io/terragrunt#990]
I have a parent terragrunt.hcl which defines the backend as :
```
remote_state {
    backend = "azurerm"
    config = {
        resource_group_name = "AOBTfStateResourceGroup"
        storage_account_name = "aobtfstatestorageaccount"
        container_name       = get_env("TG_STATE_CONTAINER", "livetrial-tfstate-${local.env.environment}")
        key = "${path_relative_to_include()}/terraform.tfstate"   
  }
}
locals {
  default_yaml_path     = find_in_parent_folders("empty.yml")
  env                   = yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders("env.yml", local.default_yaml_path)}"))
  # common_resource_group = "demo-terraform-live"
  # subscription          = "be62f057-87be-48e5-9c5f-c6fc74ac9d19"
}
inputs = merge(
  yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders("env.yml", local.default_yaml_path)}")),
  yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders("location.yml", local.default_yaml_path)}")),
  yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders("appplan.yml", local.default_yaml_path)}")),
  yamldecode(file("${get_terragrunt_dir()}/${find_in_parent_folders("gateway.yml", local.default_yaml_path)}")),
)
```
And i have a child terragrunt.hcl which deploys a web appas:
```
include {
    path = find_in_parent_folders()
}
terraform {
    source = "git::https://__PATTF__@dev.azure.com/Trial-Org/IacTF/_git/terraform-azure-liveportalwebapp"
}
inputs = {
    app_service_name = "dev1-livetrial"
    gateway_resource_group_name = "LiveTrial-Shared"
    # resource_group_name = "LiveTrial-Shared"
}
```
And i purposefully did not define terraform backend block in module.
Now when i do terragrunt apply it throws warning instead of error as follows:
```
Warning: Missing backend configuration

-backend-config was used without a "backend" block in the configuration.

If you intended to override the default local backend configuration,
no action is required, but you may add an explicit backend block to your
configuration to clear this warning:

terraform {
  backend "local" {}
}

However, if you intended to override a defined backend, please verify that
the backend configuration is present and valid
```
And if we miss this warning the state file will be stored in .terragrunt-cache directory, which will be a big issue if we run terragrunt apply on agents.
Earlier i remember seeing an error rather than warning which is nice to have.
How to deal with such situation

**Comment by brikis98** [comment]
Terragrunt's check is here: https://github.com/gruntwork-io/terragrunt/blob/586f3e4516d8b65cc2a8ad41e508fabd8cd8a4e1/cli/cli_app.go#L536. Note that it does a fairly lame regex search... Perhaps your code contains a `backend "foo" { ... }` somewhere?

**Comment by Divya1388** [comment]
No there is no backend config. I puposefullly commented out the backend block in the module, deleted the terragrunt cache directory and ran the command specifying the source path. It gave a warning as:

```
Warning: Missing backend configuration

-backend-config was used without a "backend" block in the configuration.

If you intended to override the default local backend configuration,
no action is required, but you may add an explicit backend block to your
configuration to clear this warning:

terraform {
  backend "local" {}
}

However, if you intended to override a defined backend, please verify that
the backend configuration is present and valid.
```
And when i continued with apply, it stored the state in the cache directory

**Comment by yorinasub17** [comment]
You need to add an empty backend block for `azurerm` in your terraform module, as you are configuring remote state with terragrunt.

See https://terragrunt.gruntwork.io/docs/getting-started/quick-start/#keep-your-backend-configuration-dry, where we mention that you need an empty backend `s3` block for terragrunt to fill in.

This is because terragrunt achieves the DRY for remote state config by using `-backend-config`, but `-backend-config` only works if the module has the backend block defined.

---

> Earlier i remember seeing an error rather than warning which is nice to have.

I believe the error => warning change is a change in terraform behavior. Can you share what version you are using?

**Comment by Divya1388** [comment]
Yes, i totally understand that it needs a backend block. I was testing against what if the backend block is not defined by somebody on the team. In that scenario error is a nice to have. Because when we deploy using pipelines, the sate will be stored on the agents with a warning and somebody overlooking the warning. Earlier i remember seeing an error. But now i see a warning and success on terragrunt plan/ terragrunt apply -auto-approve. 
I am using v0.21.6

**Comment by yorinasub17** [comment]
> I am using v0.21.6

Can you share the terraform version?

Note that this underlying message is based on what terraform tells us, not terragrunt. Terragrunt currently does not implement any capabilities to inspect and parse the terraform files, so there is no way for terragrunt to know if the backend block is missing.

**Comment by Divya1388** [comment]
Ok. 
Terraform Version: 0.12.17

**Comment by yorinasub17** [comment]
Closing as I believe the original issue is now solved, especially in newer terragrunt versions. If this is still an issue, consider trying to use the `generate` pattern (with either [generate blocks](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#generate), or the [generate attr on remote_state](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state)), and if you still have problems, open a new ticket with the updated context. Thanks!
