### ISSUE TITLE
From 0.19.24 to 0.21.10, can't use dependency in before_hook execute ? 

### ISSUE THREAD

**Issue by rgarrigue** [gruntwork-io/terragrunt#992]
Hi there

I've been using this successfully in 0.19.24 

      before_hook "open_tunnel_through_bastion" {
        commands = ["plan", "apply", "show", "destroy"]
        execute  = ["screen", "-d", "-m", "ssh", "-L", "12345:${dependency.instance.outputs.this_db_instance_address}:${dependency.instance.outputs.this_db_instance_port}", dependency.bastion.outputs.hostname, "-p", "22000", "sleep", "60"]
      }

Got a laptop issue, reinstalled latest Terragrunt 0.21.10, I ended up with 

> [terragrunt] 2020/01/09 17:27:59 /home/remy/work/terraform-live/development/aws/eu-west-1/postgres/databases/swarm-accessd/terragrunt.hcl:11,16-17: Unsuitable value type; Unsuitable value: element 6: string required

Does that ring a bell ? 

(edited to fix code block)

**Comment by yorinasub17** [comment]
Hmm I'm surprised that worked before, because I am pretty sure this was always not supported due to the parsing order. As in, we need to parse the `terraform` block without `dependency` in order to build the tree.

Are you running `xxx-all`? Does it work if it is not the `-all` flavor?

**Comment by yorinasub17** [comment]
By the way, we want to support this, but the implementation is a bit involved as it requires partial parsing of the `terraform` block to only extract the source when building the tree.

**Comment by rgarrigue** [comment]
I reinstalled 0.19.24 and it doesn't work either. I'm confused, I'm sure it did worked before :confused: The terragrunt apply-all didn't work, #923

**Comment by yorinasub17** [comment]
Fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.23.32
