### ISSUE TITLE
AWS_SECURITY_TOKEN is not set when terragrunt assumes role causing local-exec to have broken credentials 

### ISSUE THREAD

**Issue by mateimicu** [gruntwork-io/terragrunt#998]
I am using [aws-vault](https://github.com/99designs/aws-vault) to exec a `main` role and Terragrunt is configured to use separate roles for multiple aws-accounts. 

[aws-vault](https://github.com/99designs/aws-vault) actually sets `AWS_SECURITY_TOKEN` and `AWS_SESSION_TOKEN`.

From what I see Terragrunt actually overwrites only `AWS_SESSION_TOKEN`.

Some tools (like [botocore](https://github.com/boto/botocore/blob/master/botocore/credentials.py#L1022-L1024)) can read both and due to order, they end up using the correct `ACCESS_KEY/SECRET_KEY` but the wrong `TOKEN` when using local-exec.

Not sure if you consider this a bug in Terragrunt (AWS switched from AWS_SECURITY_TOKEN to AWS_SESSION_TOKEN [article](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/)), definitely a workaround is to use `unset AWS_SECURITY_TOKEN` before local-exec but I was wondering if you would accept an MR adding a fix for this.

**Comment by yorinasub17** [comment]
This was fixed in https://github.com/gruntwork-io/terragrunt/releases/tag/v0.21.11

**Comment by mateimicu** [comment]
Wow, this was fast 👍
